### ISSUE TITLE
Display visual indication that you are viewing a workspace that you don't own

### ISSUE THREAD

**Issue by alex-gron** [airbytehq/airbyte#22209] opened 2023-02-01 14:51 UTC
## Tell us about the problem you're trying to solve
When working on cloud support, it is difficult to tell if you are looking at a customer workspace, or your own workspace. This makes it very easy to accidentally make a change on the wrong workspace. 

## Describe the solution you’d like
A visual indication (banner, color change, etc) to let you know that you are not viewing a workspace that you own 

## Describe the alternative you’ve considered or used
The workspace name is somewhat helpful, but it is still easy to make a mistake.

**Comment by timroes** [comment] 2023-02-16 10:01
Closing as a duplicate of https://github.com/airbytehq/airbyte/issues/7614 (Adjusting some comments there to make this clear).

**Closed by timroes** 2023-02-16 10:01 UTC
Labels: type/enhancement, needs-triage, team/platform-compose, area/frontend
