### ISSUE TITLE
Mailchimp Source Error - `$.access_token: is missing but it is required`

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#10647] opened 2022-02-24 23:35 UTC
## Environment
- **Airbyte version**:  (dev, master branch - v0.35.36-alpha is closest tag)
- **OS Version / Instance**: Mac OS Monterrey (M1)
- **Deployment**: Docker
- **Source Connector and version**:  Mailchimp 0.2.11
- **Destination Connector and version**: Postgres 0.4.8
- **Severity**: Medium 
- **Step where error happened**: 

1. Create a sync from Mailchimp to Postgres
2. Choose `Authentication Method` = `API Key`
3. Sync the connection 

## Current Behavior

The connection fails all 3 attempts with the following error:

> errors: $.access_token: is missing but it is required, $.auth_type: must be a constant value oauth2.0, $.auth_type: does not have a value in the enumeration [oauth2.0]

## Expected Behavior

The sync should succeed! 

## Logs
(attached - too large)
[logs-18.txt](https://github.com/airbytehq/airbyte/files/8137248/logs-18.txt)

## Are you willing to submit a PR?
Sure!

**Comment by marcosmarxm** [comment] 2022-03-02 23:34
Hello @evantahler the root cause of the sync failure is:
```
2022-02-24 23:21:27 [42mnormalization[0m > Traceback (most recent call last):
2022-02-24 23:21:27 [42mnormalization[0m >   File "/usr/local/bin/transform-catalog", line 8, in <module>
2022-02-24 23:21:27 [42mnormalization[0m >     sys.exit(main())
2022-02-24 23:21:27 [42mnormalization[0m >   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/transform.py", line 82, in main
2022-02-24 23:21:27 [42mnormalization[0m >     TransformCatalog().run(args)
2022-02-24 23:21:27 [42mnormalization[0m >   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/transform.py", line 35, in run
2022-02-24 23:21:27 [42mnormalization[0m >     self.process_catalog()
2022-02-24 23:21:27 [42mnormalization[0m >   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/transform.py", line 62, in process_catalog
2022-02-24 23:21:27 [42mnormalization[0m >     processor.process(catalog_file=catalog_file, json_column_name=json_col, default_schema=schema)
2022-02-24 23:21:27 [42mnormalization[0m >   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/catalog_processor.py", line 63, in process
2022-02-24 23:21:27 [42mnormalization[0m >     for conflict in tables_registry.resolve_names():
2022-02-24 23:21:27 [42mnormalization[0m >   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/table_name_registry.py", line 157, in resolve_names
2022-02-24 23:21:27 [42mnormalization[0m >     conflicts = self.resolve_table_names()
2022-02-24 23:21:27 [42mnormalization[0m >   File "/usr/local/lib/python3.8/site-packages/normalization/transform_catalog/table_name_registry.py", line 196, in resolve_table_names
2022-02-24 23:21:27 [42mnormalization[0m >     assert (table_count * 2) == registry_size, f"Mismatched number of tables {table_count * 2} vs {registry_size} being resolved"
2022-02-24 23:21:27 [42mnormalization[0m > AssertionError: Mismatched number of tables 62 vs 60 being resolved
```

**Comment by marcosmarxm** [comment] 2022-03-02 23:34
Closing as duplicate of https://github.com/airbytehq/airbyte/issues/8825

**Closed by marcosmarxm** 2022-03-02 23:34 UTC
Labels: type/bug, community, needs-triage
