### ISSUE TITLE
Source MySQL: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by dimoschi** [airbytehq/airbyte#28621] opened 2023-07-24 16:35 UTC
### Connector Name

source-mysql

### Connector Version

2.0.24

### What step the error happened?

During the sync

### Revelant information

Trying to sync tables without a Primary Key with either Full Refresh | Append or Overwrite fails. However, the records can be found in the destination (Snowflake), which is very odd.

[a0117286_6815_4c3a_8575_98b3b5ac8274_logs_3855_txt.txt](https://github.com/airbytehq/airbyte/files/12148052/a0117286_6815_4c3a_8575_98b3b5ac8274_logs_3855_txt.txt)

### Relevant log output

```shell
at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:124) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:699) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2033) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:401) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java) ~[HikariCP-5.0.1.jar:?]
	at io.airbyte.db.jdbc.StreamingJdbcDatabase.lambda$unsafeQuery$0(StreamingJdbcDatabase.java:72) ~[io.airbyte.airbyte-db-db-lib-20.10.23.jar:?]
	at java.util.stream.AbstractPipeline.close(AbstractPipeline.java:323) ~[?:?]
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-20.10.23.jar:?]
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:53) ~[io.airbyte-airbyte-commons-20.10.23.jar:?]
	at io.airbyte.commons.util.LazyAutoCloseableIterator.close(LazyAutoCloseableIterator.java:56) ~[io.airbyte-airbyte-commons-20.10.23.jar:?]
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-20.10.23.jar:?]
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:53) ~[io.airbyte-airbyte-commons-20.10.23.jar:?]
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-20.10.23.jar:?]
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:53) ~[io.airbyte-airbyte-commons-20.10.23.jar:?]
	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:74) ~[io.airbyte-airbyte-commons-20.10.23.jar:?]
	... 15 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.mysql.cj.protocol.a.NativePacketPayload.readInteger(NativePacketPayload.java:398) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativePacketPayload.readString(NativePacketPayload.java:605) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeServerSessionStateController$NativeServerSessionStateChanges.init(NativeServerSessionStateController.java:112) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.result.OkPacket.parse(OkPacket.java:66) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.readServerStatusForResultSets(NativeProtocol.java:1755) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:116) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1664) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1718) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1064) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:997) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:663) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2033) ~[mysql-connector-java-8.0.30.jar:8.0.30]
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:401) ~[HikariCP-5.0.1.jar:?]
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java) ~[HikariCP-5.0.1.jar:?]
	at io.airbyte.db.jdbc.StreamingJdbcDatabase.lambda$unsafeQuery$0(StreamingJdbcDatabase.java:72) ~[io.airbyte.airbyte-db-db-lib-20.10.23.jar:?]
	at java.util.stream.AbstractPipeline.close(AbstractPipeline.java:323) ~[?:?]
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-20.10.23.jar:?]
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:53) ~[io.airbyte-airbyte-commons-20.10.23.jar:?]
	at io.airbyte.commons.util.LazyAutoCloseableIterator.close(LazyAutoCloseableIterator.java:56) ~[io.airbyte-airbyte-commons-20.10.23.jar:?]
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-20.10.23.jar:?]
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:53) ~[io.airbyte-airbyte-commons-20.10.23.jar:?]
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15) ~[io.airbyte-airbyte-commons-20.10.23.jar:?]
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:53) ~[io.airbyte-airbyte-commons-20.10.23.jar:?]
	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:74) ~[io.airbyte-airbyte-commons-20.10.23.jar:?]
	... 15 more
Stack Trace: java.lang.RuntimeException: java.lang.RuntimeException: java.sql.SQLException: Index 0 out of bounds for length 0
	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:78)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:42)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:42)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:146)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:141)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at io.airbyte.integrations.base.IntegrationRunner.lambda$produceMessages$0(IntegrationRunner.java:191)
	at io.airbyte.integrations.base.IntegrationRunner.watchForOrphanThreads(IntegrationRunner.java:241)
	at io.airbyte.integrations.base.IntegrationRunner.produceMessages(IntegrationRunner.java:190)
	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:142)
	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:101)
	at io.airbyte.integrations.source.mysql.MySqlSource.main(MySqlSource.java:453)
Caused by: java.lang.RuntimeException: java.sql.SQLException: Index 0 out of bounds for length 0
	at io.airbyte.db.jdbc.StreamingJdbcDatabase.lambda$unsafeQuery$0(StreamingJdbcDatabase.java:78)
	at java.base/java.util.stream.AbstractPipeline.close(AbstractPipeline.java:323)
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:53)
	at io.airbyte.commons.util.LazyAutoCloseableIterator.close(LazyAutoCloseableIterator.java:56)
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:53)
	at io.airbyte.commons.concurrency.VoidCallable.call(VoidCallable.java:15)
	at io.airbyte.commons.util.DefaultAutoCloseableIterator.close(DefaultAutoCloseableIterator.java:53)
	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:74)
	... 15 more
Caused by: java.sql.SQLException: Index 0 out of bounds for length 0
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2042)
	at com.zaxxer.hikari.pool.ProxyConnection.setAutoCommit(ProxyConnection.java:401)
	at com.zaxxer.hikari.pool.HikariProxyConnection.setAutoCommit(HikariProxyConnection.java)
	at io.airbyte.db.jdbc.StreamingJdbcDatabase.lambda$unsafeQuery$0(StreamingJdbcDatabase.java:72)
	... 24 more
Caused by: com.mysql.cj.exceptions.CJException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:124)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:699)
	at com.mysql.cj.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:2033)
	... 27 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at com.mysql.cj.protocol.a.NativePacketPayload.readInteger(NativePacketPayload.java:398)
	at com.mysql.cj.protocol.a.NativePacketPayload.readString(NativePacketPayload.java:605)
	at com.mysql.cj.protocol.a.NativeServerSessionStateController$NativeServerSessionStateChanges.init(NativeServerSessionStateController.java:112)
	at com.mysql.cj.protocol.a.result.OkPacket.parse(OkPacket.java:66)
	at com.mysql.cj.protocol.a.NativeProtocol.readServerStatusForResultSets(NativeProtocol.java:1755)
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:116)
	at com.mysql.cj.protocol.a.TextResultsetReader.read(TextResultsetReader.java:48)
	at com.mysql.cj.protocol.a.NativeProtocol.read(NativeProtocol.java:1664)
	at com.mysql.cj.protocol.a.NativeProtocol.readAllResults(NativeProtocol.java:1718)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryPacket(NativeProtocol.java:1064)
	at com.mysql.cj.protocol.a.NativeProtocol.sendQueryString(NativeProtocol.java:997)
	at com.mysql.cj.NativeSession.execSQL(NativeSession.java:663)
	... 28 more
```

### Contribute

- [x] Yes, I want to contribute

**Comment by rodireich** [comment] 2023-07-27 18:39
Hi @dimoschi 
Can you try with the latest mysql source connector [2.1.0](https://hub.docker.com/layers/airbyte/source-mysql/2.1.0/images/sha256-bd5766df69a84e6a179f55efc9f412df40be0edb8c7e6cd81db4d4b2c4657c4d?context=explore) see if it's successful?

I'm looking at the log you attached trying to understand the cause of failure.
In all cases we see this error right after completing the `hackthebox.profile_user` table.
out of curiosity - is there a reason there's it has no PK? I don't know if this is the cause as reading is complete

Looks like all 3 tables are done. So the issue may be related to improper closing of connection, which explains why you see all(?) records in destination

I wanted to ask you if you can add more information about the server you're using - is it on hosted environment? is is mariadb or mysql or any other type? which version?

Thanks

**Comment by dimoschi** [comment] 2023-09-04 08:35
Hi @rodireich, sorry for not responding earlier, but I was OOO. Please find below the answers to your questions.

> Hi @dimoschi Can you try with the latest mysql source connector [2.1.0](https://hub.docker.com/layers/airbyte/source-mysql/2.1.0/images/sha256-bd5766df69a84e6a179f55efc9f412df40be0edb8c7e6cd81db4d4b2c4657c4d?context=explore) see if it's successful?

I have tried with 2.1.0 and the issue persists. I've also tried the latest version 3.0.3 and again the same error appears.

> 
> I'm looking at the log you attached trying to understand the cause of failure. In all cases we see this error right after completing the `hackthebox.profile_user` table. out of curiosity - is there a reason there's it has no PK? I don't know if this is the cause as reading is complete

No particular reason it doesn't have a PK, it was a developer's decision, probably because this table is a join table for many-to-many relationship.

> 
> I wanted to ask you if you can add more information about the server you're using - is it on hosted environment? is is mariadb or mysql or any other type? which version?

We are running MariaDB 10.5.8, with the only weird parameter being the server time_zone that is in Europe/Athens.

I will try to provide some example data of the `hackthebox.profile_user` so you can further test it because atm I'm clueless.

**Comment by dimoschi** [comment] 2023-09-27 10:50
Can someone respond to this, it blocks us from connecting some resources. Attached you can find additional logs.
[a0117286_6815_4c3a_8575_98b3b5ac8274_job_6010_attempt_1_txt.txt](https://github.com/airbytehq/airbyte/files/12737719/a0117286_6815_4c3a_8575_98b3b5ac8274_job_6010_attempt_1_txt.txt)

**Closed** 2024-02-08 01:04 UTC
Labels: type/bug, area/connectors, community, needs-triage, team/connectors-python, autoteam, team/db-dw-sources
