### ISSUE TITLE
When creating a new connection, changing the connection name edits the unsaved replication settings

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#14989] opened 2022-07-24 22:06 UTC
Repro Steps
1. Create a new connection
2. Change the replication settings but don't save 
3. Start typing in the connection name
4. See that the replication settings didn't save. 

Video here: ![2022-07-24_15-03-57 (1).gif](https://images.zenhubusercontent.com/6259fa2f135cc77b44d5821f/cbc497b4-72c4-4fa8-b76b-6820d66d4759)

**Comment by octavia-squidington-iii** [comment] 2022-07-24 22:06
cc @airbytehq/frontend

**Comment by timroes** [comment] 2022-08-04 18:47
Duplicate of https://github.com/airbytehq/airbyte/issues/14844

**Closed by timroes** 2022-08-04 18:47 UTC
Labels: type/bug, team/frontend

**Comment by edmundito** [comment] 2022-08-04 19:43
Not necessarily a duplicate. The fix for #14844 also fixes this.
