### ISSUE TITLE
Update lowcode CDK demo video

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#23019] opened 2023-02-14 17:50 UTC
### Tell us about the documentation you'd like us to add or update.
The video (commented out on [this page](https://github.com/airbytehq/airbyte/blob/master/docs/connector-development/config-based/connector-builder-ui.md)) currently references the old yaml-based UI whereas now we have the form-based connector builder. It should be re-recorded using the new UI.

**Comment by girarda** [comment] 2023-04-27 02:06
closing as duplicate of https://github.com/airbytehq/airbyte/issues/24953

**Closed by girarda** 2023-04-27 02:06 UTC
Labels: type/enhancement, team/extensibility, autoteam
