### ISSUE TITLE
Need easy way how to show advanced error messages instead of for example: 'failed request' 404 url is not correct

### ISSUE THREAD

**Issue by YuliiaNahoha** [airbytehq/airbyte#19592] opened 2022-11-18 14:31 UTC
ideally we need to see full information about  failed requests:
url, params, headers 
because now is everyhting constructing 'magically' and from different sources- slicers, requester, paginators etc

**Comment by girarda** [comment] 2022-11-29 18:18
closing as duplicate of https://github.com/airbytehq/airbyte/issues/19632

**Closed by girarda** 2022-11-29 18:18 UTC
Labels: team/connectors-python
