### ISSUE TITLE
Connector setup page does not show full field when the title is long

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#8523] opened 2021-12-06 08:31 UTC
## Environment
* **Airbyte version**:  0.32.2-alpha
* **OS Version / Instance**: K8S
* **Deployment**: Cloud
* **Source Connector and version**: any source connector
* **Destination Connector and version**: Snowflake 0.3.18
* **Severity**: Low
* **Step where error happened**: destination connector setup page

## Current Behavior
![](https://user-images.githubusercontent.com/1933157/144812661-bf3d96e9-696e-4c98-86d1-71ec4a75f7a7.png)

## Expected Behavior
Show the full title even if it's a bit long.

## Logs
N/A

## Steps to Reproduce
1. Go to the latest snowflake destination connector setup page.
1. Scroll down to `Loading Method` section.
1. You can see that the first option has a long title, and it's cut off.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1202102171868563/1202126684097363) by [Unito](https://www.unito.io)

**Comment by tuliren** [comment] 2021-12-06 08:31
@jrhizor, FYI.

**Comment by timroes** [comment] 2022-06-28 17:27
Duplicate of https://github.com/airbytehq/airbyte/issues/8130

**Closed by timroes** 2022-06-28 17:27 UTC
Labels: type/bug, area/frontend, airbyte-cloud, UX, connectors/destinations-warehouse, connectors/destination/snowflake, autoteam, team/frontend, ui/connectors
