### ISSUE TITLE
Reduce duplication of User IDs to Emails

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#4409] opened 2021-06-29 18:08 UTC
## Tell us about the problem you're trying to solve
When reporting on the number of new users, I see a wide gap between the number of distinct user IDs to distinct emails. This is apparent now that email is a required field for users as of 5/26, so we have emails for every new user.  Since we turned on emails, we see 1.3 - 1.5x new IDs per unique email a week.

- Week of 06/20: 469 users; 241 distinct emails (one user had a disproportionate impact here creating 115 users) 
- Week of 06/13: 276 users; 188 distinct emails
- Week of 06/06: 322 users; 232 distinct emails

After chatting with Charles, my understanding is this duplication will be resolved in Airbyte Cloud. However, in Airbyte community, some level of duplication will persist as there is a natural motion for users to spin up Airbyte multiple times completely separately. 

## Describe the solution you’d like
While we accept some degree of duplication, the difference between user IDs and email is wide enough to investigate further. 
- Is the duplication valid in all cases? Is restarting Airbyte the only reason user IDs are created? 
- If a user is spinning up Airbyte multiple times, can we reduce the frequency this occurs by improving a part of the experience? What is the user trying to achieve?

A few examples of multiple IDs for a single email:
- sabolc.franjo@everon.io (Some user IDs: b6c059ca-5a15-4895-a6f2-ac24035ff16f, 	
bc4f270e-42c6-44a8-98bd-12dc694a3c4c, ab48ad10-1be4-4819-84e7-fef4b964be14)
- hudsondba@gmail.com (adcde261-b97a-44fb-9a71-8ff28bae93e7, d5f959f2-942f-446d-a810-f7df13da7e7a, 0661b6d6-9dda-4059-bc7d-13d084814da0)
- vpetrenko@pineparkhealth.com (73afa765-ce3c-4c82-8c7f-7b6e61d0419e, 	
f4f2882c-d962-4196-b17d-bc66cffb8118, 9e67f439-465b-4098-a4dc-87c360b1cf77)

**Comment by johnlafleur** [comment] 2021-06-29 19:18
I can't think of any reason for a duplicate ID to be valid from a metrics standpoint. 
I think the issue is why Segment doesn't merge IDs when this is for the same email address. 
I'm wondering if contacting Segment's support could be interesting, wdyt @nataliekwong ?

**Comment by nataliekwong** [comment] 2021-06-29 21:13
My understanding from @cgardens was that User IDs are generated from Amplitude. Additionally, there is merging that happens within Amplitude, which Segment should receive as well. I think we could start with investigation in Amplitude if it is the source of ID generation, whereas Segment only receives & sends information and doesn't do any modification/transformation itself.

**Comment by johnlafleur** [comment] 2021-06-30 01:25
Ok. Could you discuss with Amplitude's support then and take that over?

**Comment by nataliekwong** [comment] 2021-06-30 01:53
Reached out to Amplitude support.

**Comment by nataliekwong** [comment] 2021-07-01 04:13
Amplitude responded with a deferral to reach out to Segment. I'll reach out to Segment support to see if they have a suggestion for next steps. Amplitude sometimes identifies that a user is returning, and other times it does not. After chatting with John we landed on Segment as the creator of IDs, not Amplitude.

Amplitude's response:
> Since you are sending in data via a third-party CDP (Segment), it is hard for me to comment on your instrumentation. As the first step to troubleshooting, you can perhaps work with your instrumentation team to look at whether there is a difference in the way you are capturing data for these two sets of users (one set being users who have their identities correctly merged and another set being users who do not have their identities correctly merged). 

I noticed a few things in your users that seem to suggest that your instrumentation is assigning a User ID to users every single time they appear in your app or use a different device.

1. Upon cross-checking these two users with the same email property sabolc.franjo@everon.io​, they never share the same device IDs. 
2. In each user ID that sabolc.franjo@everon.io has, he/she has the same first seen and last seen date. This is suspicious as it seems that the user is not tracked across days/sessions.

In Amplitude, we identify and merge users based on three IDs: user IDs, device IDs, and Amplitude IDs.

Device ID: Amplitude pulls the IDFV or generates a random alphanumeric string for the device ID; this string is stored locally in the browser's cookie or mobile device. For web-based applications, Amplitude will set the device ID to a randomly-generated UUID by default. It will persist unless a user clears their browser cookies and/ or is browsing in private mode. 

User ID: This identifier is configured by you. Many products use a username or an internal unique identifier to track their users. A user ID should be something that does not and will not change. If it does, Amplitude will have no way of knowing it's intended to represent a currently-existing user, and will instead assume it stands for a separate user.
Anonymous users should not be assigned a user ID. These users will still have Amplitude IDs and device IDs. Users will later be merged when Amplitude recognizes the different user IDs belong to the same user.​

Amplitude ID: After gathering the device and user IDs, Amplitude generates the Amplitude ID and associates it with the user and device IDs it has already collected for this user. Amplitude only needs one or the other to generate an Amplitude ID; however, the user ID is preferred, as multiple unique users could share the same device.

This section explains in detail how Amplitude generates an Amplitude ID in different scenarios. Read more here: https://help.amplitude.com/hc/en-us/articles/115003135607#h_7cf7c47f-ec71-4e15-8c47-a2bda5d84186 

Based on the above, I will recommend you check how your instrumentation is assigning user IDs currently, in order to make sure that Amplitude is able to identify and merge users. Usually, user IDs should be set when the user logs in using a unique identifier like their email address (and not every time they use a different device since a user can have multiple devices).

**Comment by misteryeo** [comment] 2022-04-19 15:32
@nataliekwong is this still an issue?

My understanding from @ChristopheDuong is that we are moving away from using Amplitude so are we able to close this out?

**Comment by nataliekwong** [comment] 2022-04-21 03:14
We can close this. My understanding is that we should just always expect there to be a level of duplication with emails and IDs.  However, this doesn't actually have to do with Amplitude in the end, so moving away from Amplitude is independent to closing this. 

As an aside, Amplitude still has some value to us by being able to pivot very quickly by any attributes in a no-code way, so you don't have to know how to manipulate SQL to get quick funnel reporting. That's the only thing we lose by moving away from Amplitude completely.

**Closed** 2022-04-28 14:25 UTC
Labels: type/enhancement, area/metrics, team/analytics
