### ISSUE TITLE
Destination BigQuery : 400 Bad Request

### ISSUE THREAD

**Issue by AnatolePledg** [airbytehq/airbyte#12813] opened 2022-05-12 15:51 UTC
Is this your first time deploying Airbyte : No
OS Version / Instance: EC2 t2.large
Deployment : EC2 Docker
Airbyte Version : 0.35.4-alpha
Source name/version : Postgres 0.4.14
Destination name/version : BigQuery 1.0.1
Description : BigQuery destination fails to close and causes sync failures

## Current Behavior
Receiving a 400 error after the sync process when sending a PUT request to GoogleAPI. It makes the sync fail

## Expected Behavior
No error

## Relevant Logs

<details>
<summary>LOG</summary> 

```
Failed to close AbstractBigQueryUploader{table=_airbyte_raw_share, tmpTable=_airbyte_tmp_dig_share, syncMode=WRITE_APPEND, writer=class io.airbyte.integrations.destination.bigquery.writer.BigQueryTableWriter, recordFormatter=class io.airbyte.integrations.destination.bigquery.formatter.DefaultBigQueryRecordFormatter} writer, 
details: 400 Bad Request
PUT https://www.googleapis.com/upload/bigquery/v2/projects/pledg-331014/jobs?uploadType=resumable&upload_id=ADPycdsKhyT9oLRZsfCeIIpq9Znkgpuz5wAz2PLhx1-f1_937uNcnu5GHAqJ2Hcmv33gZp1c2ADSZiBJ8JKESguZACSg3Q
i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $: string found, object expected
2022-05-12 07:51:18 e[1;31mERRORe[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$1):70 - Validation failed: "error"
2022-05-12 07:51:18 e[32mINFOe[m i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $: string found, object expected
2022-05-12 07:51:18 [1;31mERROR[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$1):70 - Validation failed: null
2022-05-12 07:51:18 [43mdestination[0m > 	at io.airbyte.integrations.destination.bigquery.uploader.AbstractBigQueryUploader.close(AbstractBigQueryUploader.java:90) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery-0.35.59-alpha.jar:?]
2022-05-12 07:51:18 [43mdestination[0m > 	at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.lambda$close$0(BigQueryRecordConsumer.java:62) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery-0.35.59-alpha.jar:?]
2022-05-12 07:51:18 [43mdestination[0m > 	at java.util.HashMap$Values.forEach(HashMap.java:1065) ~[?:?]
2022-05-12 07:51:18 [43mdestination[0m > 	at io.airbyte.integrations.destination.bigquery.BigQueryRecordConsumer.close(BigQueryRecordConsumer.java:60) ~[io.airbyte.airbyte-integrations.connectors-destination-bigquery-0.35.59-alpha.jar:?]
2022-05-12 07:51:18 [43mdestination[0m > 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.lambda$close$0(FailureTrackingAirbyteMessageConsumer.java:67) ~[io.airbyte.airbyte-integrations.bases-base-java-0.35.59-alpha.jar:?]
2022-05-12 07:51:18[43mdestination[0m > 	at io.airbyte.integrations.base.sentry.AirbyteSentry.executeWithTracing(AirbyteSentry.java:54) [io.airbyte.airbyte-integrations.bases-base-java-0.35.59-alpha.jar:?]
2022-05-12 07:51:18[43mdestination[0m > 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:67) [io.airbyte.airbyte-integrations.bases-base-java-0.35.59-alpha.jar:?]
2022-05-12 07:51:18 [43mdestination[0m > 	at io.airbyte.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:164) [io.airbyte.airbyte-integrations.bases-base-java-0.35.59-alpha.jar:?]
2022-05-12 07:51:18 [43mdestination[0m > 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:105) [io.airbyte.airbyte-integrations.bases-base-java-0.35.59-alpha.jar:?]
2022-05-12 07:51:18 [43mdestination[0m > 	at io.airbyte.integrations.destination.bigquery.BigQueryDestination.main(BigQueryDestination.java:262) [io.airbyte.airbyte-integrations.connectors-destination-bigquery-0.35.59-alpha.jar:?]
2022-05-12 07:51:18[43mdestination[0m > Caused by: com.google.cloud.bigquery.BigQueryException: 400 Bad Request
2022-05-12 07:51:18 [43mdestination[0m > PUT https://www.googleapis.com/upload/bigquery/v2/projects/pledg-331014/jobs?uploadType=resumable&upload_id=ADPycdsWbhMvLzh82W8JXaFqP0vkrTln1qCVwtIBrI7zwlFqvBpi-PC5W-gb2LbJj2kfdjXq12m5sb5-S4_RfwS8gJgiaA
2022-05-12 07:51:18 [43mdestination[
```
</details>

The Full logs are too long to be attached here.

## Similar issues
https://discuss.airbyte.io/t/postgres-to-bigquery-sync-fails/1043/5
https://discuss.airbyte.io/t/bigquery-details-400-bad-request/1049/2

## Are you willing to submit a PR?
Not at the moment

**Comment by AnatolePledg** [comment] 2022-05-12 16:05
The error is 400 Bad Request and not 404 Not Found, but except that it really looks like this bug:
https://github.com/airbytehq/airbyte/issues/3549
And there is no solution for it, except to use GCS Staging.

**Comment by marcosmarxm** [comment] 2022-05-12 16:06
@AnatolePledg how large are the tables you're trying to sync to bigquery rows + Gbs?

**Comment by AnatolePledg** [comment] 2022-05-12 16:09
All the big tables are in incremental mode. I have a total of 50 tables and the largest table has 5k new rows at every sync.

**Comment by marcosmarxm** [comment] 2022-05-13 12:07
@AnatolePledg are you using Standard Syncs or GCS Staging? See recommendations here: https://docs.airbyte.com/integrations/destinations/bigquery#standard-uploads

**Comment by petr-simon** [comment] 2022-05-13 12:12
We use different ETL tool than Airbyte (Keboola) but we facing same problem during data export to BigQuery. We figured out only that it happens mainly for bigger tables. Small one are transferred smoothly.

**Comment by AnatolePledg** [comment] 2022-05-13 12:12
@marcosmarxm I am using the Standard method. I see that now the doc says "we strongly recommend that you do not use this option for anything other than a quick demo". But when I implemented it it was the preferred option and the GCS Staging was only needed for syncs that lasted several hours. Here my syncs only take a few minutes (up to 20 minutes). Besides the error is different than the one described in [the issue](https://github.com/airbytehq/airbyte/issues/3549) that introduced GCS staging

**Comment by andresbravog** [comment] 2022-05-13 14:14
Same situation here in some of the pipelines (not all) with a small amount of records ingested no changes on our airbyte version or connectors. In fact, sometimes this actually succeeds so we are assuming the issue could reside on the GCP side.

**Comment by ciminelli** [comment] 2022-05-13 20:45
Same issue here, just started for us yesterday: https://github.com/airbytehq/airbyte/issues/12804

As others have mentioned it looks like something changed or the issue is on the GCP side.

**Comment by andresbravog** [comment] 2022-05-14 07:03
Ours is resolved now does anyone found a related bug or status degradation reported in GCP?

**Comment by marcosmarxm** [comment] 2022-05-16 16:56
> Ours is resolved now does anyone found a related bug or status degradation reported in GCP?

Was solved without any changes in Airbyte from Std to Staging method?

**Comment by andresbravog** [comment] 2022-05-16 20:48
@marcosmarxm that is correct we have changed nothing and the issue disappeared after ~6hours

**Comment by AnatolePledg** [comment] 2022-05-17 09:29
The issue is not happening again, despite no actions taken on my side..
Maybe we can put this on hold ?

**Comment by MaxKrog** [comment] 2022-05-17 10:16
Same here. Issue disappeared

**Comment by marcosmarxm** [comment] 2022-05-17 14:04
I'm closing this one and if happens again I'll open it.

**Closed by marcosmarxm** 2022-05-17 14:04 UTC
Labels: type/bug, community, needs-triage, team/use, autoteam
