### ISSUE TITLE
Destination Snowflake: Upgrade JDBC driver version to prevent Driver deprecation in GCP

### ISSUE THREAD

**Issue by SoerenStahlmann** [airbytehq/airbyte#30923] opened 2023-09-29 06:47 UTC
### Connector Name

destination-snowflake

### Connector Version

3.1.16

### What step the error happened?

Other

## Background
Historically, signed (or more commonly presigned) URL API requests to Snowflake GCP buckets, only required the payload to be signed (with SigV4).  However, currently, Google requires both the request headers and payload to be signed.

After the cutover date, once this requirement is enforced, PUT requests to the stage from clients below the minimum version will fail (see FAQs).

To avoid these failures, Snowflake has decided in consultation with Google to switch all drivers from using presigned URL authentication to using GCS downscoped token authentication.

## Action to take
In response to Google’s changes, Snowflake has released a new set of drivers, with critical fixes. All customers with their Snowflake account hosted on Google Cloud must update their client drivers to these new minimum versions listed below by October 30, 2023.

Snowflake will ensure that the older drivers continue to work for GCP Accounts until this date. They will be supported as per the Snowflake Client and Version Support policy for this duration.

See also here: https://community.snowflake.com/s/article/faq-2023-client-driver-deprecation-for-GCP-customers

The snowflake JDBC driver version needs to be at least 3.13.25.

### Contribute

- [X] Yes, I want to contribute

**Comment by evantahler** [comment] 2023-10-04 23:33
Closing as a duplicate of https://github.com/airbytehq/airbyte/issues/25849

**Closed by evantahler** 2023-10-04 23:33 UTC
Labels: type/bug, area/connectors, community, connectors/destination/snowflake, releaseStage/ga, team/destinations
