### ISSUE TITLE
Collect heapdump of OOM syncs 

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#10404] opened 2022-02-17 10:42 UTC
We have seen an increased number of syncs failing causing of OOM issues. The right way to debug this is to collect heap dumps and analyse it to identify whats occupying the memory. We can collect heapdumps via JVM flag `-XX:+HeapDumpOnOutOfMemoryError` and specify the path where heapdump is generated via flag `-XX:HeapDumpPath=` 

The problem is that the dump is generated inside the pod and once the pod exits, the dump is lost. We can attach a persistent volume with each pod and then provide the path of this volume in the JVM flag `-XX:HeapDumpPath=` so that the dump is generated inside the volume. Next we can write a separate deployment which can take dump files from this volume and move it to a GCS bucket so that people can download and analyse them. This can also work with OSS.

We would need to figure out how to pass in the connector information in the heapdump filename.

**Comment by tuliren** [comment] 2022-08-12 17:51
Similar request from Ievgenii:

> Basically I would suggest to add those args for dump collection on OOM error (`XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/data/dump.hprof`) for all connectors. It will collect data only in case when it fails with OOM. So shouldn't much affect resources. But it's almost impossible to find why it failed without memory dump.  This file could be attached to raised ticket.  For example in case of current issue customer has terabytes of data. It would be pretty expensive to create a DBs on aws for attempts to reproduce it and collect such heap memory dump.

Slack [thread](https://airbytehq-team.slack.com/archives/C02UF50V9HA/p1660305952716559?thread_ts=1660222415.873109&cid=C02UF50V9HA)

**Comment by grishick** [comment] 2022-08-24 17:33
@evantahler is this something that the platform team can do?

**Comment by evantahler** [comment] 2022-08-24 17:36
This is probably a duplicate of https://github.com/airbytehq/airbyte/issues/13936.  To accomplish this, we need tighter integration between the orchestrator which is killing the pods/containers and the platform, which can then read those reasons in.

I'll close this issue in favor of https://github.com/airbytehq/airbyte/issues/13936

**Closed by evantahler** 2022-08-24 17:36 UTC
Labels: type/enhancement, area/connectors, team/oss
