### ISSUE TITLE
[Low-Code CDK] Document what objects are available at runtime for components that support interpolation

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#21630] opened 2023-01-20 00:07 UTC
## Tell us about the problem you're trying to solve

It is nebulous to developers what objects and values are accessible for interpolation for different components. Certain things like $options and macros are always accessible, but depending on the component certain fields like `response` may be accessible or not be.

## Describe the solution you would like

As a first step we should be focused on documenting what values are available for interpolation. This should be a clear mapping of component -> object(s) available for interpolation. For example, the RecordFilter component has access to `$options`, `stream_state`, `stream_slice`, `next_page_token`, and macros. This should be done for all components that support interpolation

Non-exhaustive list originally compiled by Lake:

- Macros as defined in macros.py (now_local(), now_utc(), today_utc(), timestamp(), max(), day_delta(), format_datetime())
- stream_slice object (example) - what area all of the properties that can be accessed on this? Is this defined by the data returned by the API?
- config object (example), used to access fields in the connector spec (properties are the keys of the spec fields)
- options object (example), used to access fields passed in to a component through $options
- headers object (example), the keys of which seem to come from what is returned by the API (?)
- response object (example), the keys of which seem to come from what is returned by the API (?)
- record object (example) - seems like this may only be used in transformations and record_filter, so I’m guessing this is accessing the fields of the record actively being processed by those components?
- last_records object (example) - seems like it lets you access one of the records in the response? What does the last_ prefix mean here?

As part of this ticket, we should do the following:

- Review the declarative components that support interpolation (they have at least one field that uses interpolated string/boolean/mapping)
- Determine if it is more valuable to break things down further so it isn't just component -> interpolated objects, but we may need it to be granular to fields if they differ
- Identify where in the documentation it best fits.

## Acceptance Criteria

- [ ] Low-Code documentation is updated with a comprehensive list of declarative components supporting interpolation and objects they have access to.

**Comment by girarda** [comment] 2023-04-17 21:22
closing as duplicate of https://github.com/airbytehq/airbyte/issues/24576

**Closed by girarda** 2023-04-17 21:22 UTC
Labels: team/extensibility
