### ISSUE TITLE
Automatically repair terminated connection manager workflows

### ISSUE THREAD

**Issue by lmossman** [airbytehq/airbyte#12746] opened 2022-05-10 17:39 UTC
Connection manager workflows are sometimes terminated for unknown reasons. When this happens, future syncs for that connection are no longer scheduled as there is no workflow to do so.

[This PR](https://github.com/airbytehq/airbyte/pull/12289) took care of repairing these workflows when manual actions are performed. We should also have something in place to repair these workflows even if no manual action is performed. This should likely be some cron-like temporal process that periodically checks for terminated workflows and restarts them if necessary

**Acceptance Criteria**
- Connection manager workflows that end up in a terminated state are automatically repaired after some maximum time (e.g. 10 mins?)

**Comment by cgardens** [comment] 2022-06-30 22:22
duplicate of: https://github.com/airbytehq/airbyte/issues/14043

**Closed by cgardens** 2022-06-30 22:22 UTC
Labels: team/oss
