### ISSUE TITLE
Per-stream state support (to be broken down)

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#12024] opened 2022-04-14 16:11 UTC
Add per-stream state support, in service of the Schema Evolution epic
[Tech spec](https://docs.google.com/document/d/1zJVUQkVy8ZJUcqzM_hYPGijr4pI0Xx6I2eqpagJ2r7E/edit#heading=h.fa72b39y2m99)

**Comment by grishick** [comment] 2022-04-15 20:59
@benmoriceau would this issue https://github.com/airbytehq/airbyte/issues/3206 be part of the solution?

**Comment by benmoriceau** [comment] 2022-04-27 17:49
@benmoriceau Next sprint: API focus and sync with Tim.

**Comment by grishick** [comment] 2022-05-06 15:55
Is this a duplicate of https://github.com/airbytehq/airbyte/issues/6911?

**Closed** 2022-07-20 22:31 UTC
Labels: area/platform, area/platform-oss, team/oss
