### ISSUE TITLE
Should all Source connectors respect the `at-least-once delivery guarantee`?

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#15158] opened 2022-08-01 12:40 UTC
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1752](https://airbyte7538.zendesk.com/agent/tickets/1752)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Marcos Marx

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">According to the doc of <a href="https://docs.airbyte.com/understanding-airbyte/connections/incremental-deduped-history#inclusive-cursors" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">incremental sync with deduped history</a>, it says</p>
<blockquote style="background-color: #f8f8f8; border-left-color: #e9e9e9; border-left-style: solid; border-left-width: 5px; margin-left: 0; padding: 12px;">
<p style="margin-bottom: 0; margin-top: 0; padding: 0;" dir="auto">When replicating data incrementally, Airbyte provides an <strong>at-least-once delivery guarantee</strong>. This means that it is acceptable for sources to re-send some data when ran incrementally. One case where this is particularly relevant is when a source’s cursor is not very granular. <strong>For example, if a cursor field has the granularity of a day (but not hours, seconds, etc)</strong>, then if that source is run twice in the same day, there is no way for the source to know which records that are that date were already replicated earlier that day. By convention, sources should prefer resending data if the cursor field is ambiguous.</p>
</blockquote>
<p dir="auto">MSSQL source code:</p>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;">final String sql = String.format("SELECT %s FROM %s WHERE %s &gt; ?",
String.join(",", newColumnNames),
sourceOperations.getFullyQualifiedTableNameWithQuoting(connection, schemaName, tableName),
sourceOperations.enquoteIdentifier(connection, cursorField));
</code></pre>
<p dir="auto">Say I have a table that I’m currently syncing and the only cursor available is a date column (without hours, minutes, seconds), I then do a sync daily at 14:00 on 2022-07-29; my cursor becomes 2022-07-29 (latest date of the cursor).</p>
<p dir="auto">Then the next day, at 14:00 the query will execute <code style="background-color: #f9f9f9; padding: 2px 5px;">"SELECT %s FROM %s WHERE %s &gt;  2022-07-29"</code>, however other data was inserted in that table between 14:00 and midnight on 2022-07-29. The source connector won’t be able to pick those rows that were inserted between 14:00 and 23:59 on 2022-07-29.</p>
<p dir="auto">Would there be eventually a way to tell the connector what kind of operator we want to use with the cursor (<code style="background-color: #f9f9f9; padding: 2px 5px;">&gt;</code> or <code style="background-color: #f9f9f9; padding: 2px 5px;">&gt;=</code>) ? That way we could have MSSQL query be <code style="background-color: #f9f9f9; padding: 2px 5px;">"SELECT %s FROM %s WHERE %s &gt;= ?</code> instead (<strong>greater or equal</strong>) if the cursor field is ambiguous.</p>
<p dir="auto">Ideally, my source would have a complete timestamp for the cursor but we don’t live in a perfect data world, unfortunately.</p> 

[<a href="https://discuss.airbyte.io/t/should-all-source-connectors-respect-the-at-least-once-delivery-guarantee/2050/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment] 2022-08-01 12:44
*Comment made from Zendesk by Marcos Marx on 2022-08-01 at 12:44:*

<blockquote><div class="zd-comment" dir="auto">Good question Philippe! I raised this question as an issue in Github <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/15158">https://github.com/airbytehq/airbyte/issues/15158</a> if this is identified as bug by our team.&nbsp;<br>&nbsp;<br></div></blockquote>

**Comment by alexander-marquardt** [comment] 2022-08-11 12:13
I have documented a process that may be used to guarantee _exactly once_ delivery here: https://www.elastic.co/blog/how-to-keep-elasticsearch-synchronized-with-a-relational-database-using-logstash

**Comment by cgardens** [comment] 2022-08-11 16:22
We should definitely be hitting _at least once_ guarantee. 

@alexander-marquardt I agree. Looking at this code snippet, it looks like we are not meeting that. Feels like a bug. I'm trying to remember why we did this. The only explanation I can imagine is that we said that the contract was that that the cursor in the state should only represent values that we can guarantee were _fully_ present. e.g. if you put 2022-08-02 in the state, it is the source saying that it isn't possible to get anymore 2022-08-02. That's nuanced and confusing though. I think I'm on the same page as @alexander-marquardt that it should be `>=`.

@tuliren what do you think?

**Comment by alexander-marquardt** [comment] 2022-08-11 16:51
Also, it  is probably worth noting that (as far as I can tell), the normalization code will deduplicate in the event that the same document is sent twice -- so while >= could in some cases result in duplicate documents being sent and stored in the raw tables, in theory it should not result in duplicates in the normalized data. 

But I think this can also be solved using the method I documented in the above blog as well .. `WHERE modification_time > value AND modification_time < NOW()` , rather than just  `WHERE modification_time > last_value `. Detailed explanation is given in the article.

**Comment by tuliren** [comment] 2022-08-11 18:52
@alexander-marquardt, I am working on this in this issue: https://github.com/airbytehq/airbyte/issues/14732

We have considered the approached you wrote about. However, it does not work for us because the cursor field is not necessary a modification time. We allow users to use all kinds of fields as the cursor field (e.g. primary key). So the `< NOW()` trick does not apply.

The problem of using `>=` is that if there is no new data, the rows with the cursor value will be duplicated each time. If a connector is scheduled to run every 30 minutes, that's 48x duplications per day. This experience seems pretty bad to me. If I see this in my data syncing tool, I would definitely look for other vendors. More importantly, it is possible that there may be a ton of data with the same cursor value. For example, the cursor is the creation date, and 1 million rows are generated programmatically with the same creation date. Under those scenarios, duplication should be avoided as much as possible.

The solution I am currently implementing is to use `>` by default, and use `>=` when needed. The idea is to track the number of rows synced together with the cursor value. So the state looks something like `{ users: { count: 3, cursor: "2022-01-03 00:00:00"}}`. Each time before the incremental sync, count the number of rows with `cursorColumn = cursorValue`. If the result is different from the one in the state, we know there are changes, and use `>=` for the incremental query. Otherwise, use `>` to avoid the duplication.

This approach does not prevent duplication all the time. But it should do the job most of the time, and also avoids a zero-duplication but super complicated solution.

**Comment by alexander-marquardt** [comment] 2022-08-11 19:46
@tuliren - it sounds like you have worked around the known limitation documented https://docs.airbyte.com/understanding-airbyte/connections/incremental-deduped-history/#known-limitations. 

If so, it sounds like our docs should be updated. Do you agree? 

CC: @Amruta-Ranade

**Comment by tuliren** [comment] 2022-08-11 19:51
I think the main limitation still exists after the new implementation:

> if modifications to the underlying records are made without properly updating the cursor field, then the updated records won't be picked up by the Incremental sync

If the cursor field is not changed, we still won't be able to detect that using the ordinary incremental mode (non-cdc).

**Comment by alexander-marquardt** [comment] 2022-08-11 19:57
You are right - I totally mis-read what was being mentioned as a limitation in the docs, and assumed that it was the potential for missing some records ... 

However, given the optimization that you are referring to , is seems like the example given in the docs that state that the query is `select * from table where cursor_field > 'last_sync_max_cursor_field_value'` is not quite accurate ... although I am not sure how this should be written, given that it is a bit more complicated ..

**Comment by bleonard** [comment] 2022-09-30 00:53
Closing as duplicate of https://github.com/airbytehq/airbyte/issues/14732

**Comment by bleonard** [comment] 2022-09-30 00:53
Closing as duplicate of https://github.com/airbytehq/airbyte/issues/14732

**Closed by bleonard** 2022-09-30 00:53 UTC
Labels: community, area/databases, team/databases, zendesk, team/db-dw-sources
