### ISSUE TITLE
Get normalization image from the connector definition file

### ISSUE THREAD

**Issue by andriikorotkov** [airbytehq/airbyte#18232] opened 2022-10-20 13:51 UTC
Get normalization image from the connector definition file and read the information from both the definition file and the spec and add logs if have difference.

**Comment by evantahler** [comment] 2022-11-29 17:37
Can you please link the PR that's related to this story?

**Comment by pedroslopez** [comment] 2022-11-29 20:48
@andriikorotkov Is this a duplicate of https://github.com/airbytehq/airbyte/issues/18235 ?

**Comment by andriikorotkov** [comment] 2022-11-29 21:04
@pedroslopez, yes, I added a description to this task, and closed the one you specified.

**Closed** 2022-11-30 10:16 UTC
Labels: team/connector-ops
