### ISSUE TITLE
pasting a value into connector specification secret input pastes extra characters

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1745] opened 2021-01-20 20:09 UTC
## Behavior
If I paste a value from clipboard to a secret field in the UI it seems like a longer (incorrect) value gets pasted. See the gif below where I paste an API token into the Github connector as an example: 

![input](https://user-images.githubusercontent.com/6246757/105228939-11beed00-5b18-11eb-8d7c-5ea0aff7284e.gif)

in the screenshot I use cmd-v to paste the value. When I use rightclick->paste the issue doesn't happen. This issue only seems to happen the first time I input a value into the field, and only to secrets fields, not others.

## Steps to Reproduce
1. go to the connector settings page 
1. paste a value from the clipboard in a secret field
1. the pasted value is sometimes longer than the original. Paste it again and you'll notice that the "real" value is shorter

## Severity of the bug for you
medium -- kind of confusing UX because it took me a couple of tries to realize the credentials were correct but being pasted incorrectly

## Airbyte Version
0.11.2-alpha

## Additional context
OS X using chrome, with or without adblocker

**Comment by cgardens** [comment] 2021-01-20 20:43
Artem is working on this.

**Comment by cgardens** [comment] 2021-01-26 03:10
duplicate of https://github.com/airbytehq/airbyte/issues/1695

**Closed by cgardens** 2021-01-26 03:10 UTC
Labels: area/frontend, type/bug
