### ISSUE TITLE
Source Shopify: error normalizing `orders` table

### ISSUE THREAD

**Issue by andrewlreeve** [airbytehq/airbyte#14565] opened 2022-07-10 23:45 UTC
## Environment
- **Airbyte version**:  0.39.23-alpha
- **OS Version / Instance**: Gcloud
- **Deployment**: Gcloud
- **Source Connector and version**: Shopify 0.1.37 
- **Destination Connector and version**: BigQuery 1.1.11
- **Step where error happened**: Setup new connection

## Current Behavior
On first run, the DBT normalization hits an error trying to normalize orders_scd.sql. The error is caused by orders having an empty array for `payment_gateway_names` which returns null.

## Expected Behavior
Null allowed or return an empty string

## Logs
2022-07-10 18:07:29 [42mnormalization[0m > 18:07:21.072087 [error] [MainThread]: [33mDatabase Error in model orders_scd (models/generated/airbyte_incremental/scd/shopify_uk/orders_scd.sql)[0m
2022-07-10 18:07:29 [42mnormalization[0m > 18:07:21.072721 [error] [MainThread]:   Array cannot have a null element; error in writing field payment_gateway_names
2022-07-10 18:07:29 [42mnormalization[0m > 18:07:21.073283 [error] [MainThread]:   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/scd/shopify_uk/orders_scd.sql
2022-07-10 18:07:29 [42mnormalization[0m > 18:07:21.074651 [info ] [MainThread]: 
2022-07-10 18:07:29 [42mnormalization[0m > 18:07:21.074978 [info ] [MainThread]: Done. PASS=158 WARN=0 ERROR=1 SKIP=141 TOTAL=300

## Steps to Reproduce
1. Connect with Shopify
2. Try to normailize with a store that doesn't have a payment method on all orders

``` sql
SELECT
    JSON_QUERY(_airbyte_data, '$.id') AS order_id,
    JSON_QUERY(_airbyte_data, '$.created_at') AS created_at,
    JSON_QUERY(_airbyte_data, '$.payment_gateway_names') AS payment_gateway
FROM # table
WHERE JSON_QUERY(_airbyte_data, '$.payment_gateway_names') = '[""]'
ORDER BY created_at desc
LIMIT 100
```
To find orders on Bigquery.

## Are you willing to submit a PR?
I can, but will need to do a deep dive on how this connector is built.

**Comment by alafanechere** [comment] 2022-07-11 08:41
Hey @andrewlreeve , thank you for opening this issue. 
We do not have a Shopify test account yet, so we cannot test this connector thoroughly.
I would suggest changing the connector itself to return an empty array for the field `payment_gateway_names`.
You should open a PR to change the schema of this field in `airbyte-integrations/connectors/source-shopify/source_shopify/schemas/orders.json` to : 
```json
    "payment_gateway_names": {
      "type": [, "array"],
      "items": {
        "type": ["null", "string"]
      }
    },
```
You should also override the `read_records` function of the `Orders` stream to set `payment_gateway_names` to `[]` if the value in the record from the API is `null`. (`airbyte-integrations/connectors/source-shopify/source_shopify/source.py`)

**Comment by bazarnov** [comment] 2022-10-10 15:14
> You should open a PR to change the schema of this field in `airbyte-integrations/connectors/source-shopify/source_shopify/schemas/orders.json` to:

The schema for `payment_gateway_names` already declares that this array could be `null`. It seems like the issue is in normalization, rather than the connector, or on the destination side.

```json
"payment_gateway_names": {
      "type": ["null", "array"],
      "items": {
        "type": ["null", "string"]
      }
    },
```

**Comment by andrewlreeve** [comment] 2022-10-10 21:40
@bazarnov thanks for following up. You're correct that it was the normalisation or destination that was causing the issue.

I'm not using normalisation with this flow anymore and doing my own normalisation with DBT instead so I'm not able to test it with the latest BigQuery connector. If I setup a new flow in the future I will test it with normalisation enabled.

**Comment by bazarnov** [comment] 2023-01-16 11:48
It is closed as there are no action items.

**Closed by bazarnov** 2023-01-16 11:48 UTC
Labels: type/bug, area/connectors, community, connectors/source/shopify, team/connectors-python
