### ISSUE TITLE
Support heavy log file on the webapp (add pagination for logs)

### ISSUE THREAD

**Issue by AM-I-Human** [airbytehq/airbyte#9563] opened 2022-01-18 08:25 UTC
## Tell us about the problem you're trying to solve
I'm trying to debug a long sync job, and I need to see the error. The problem is that if the log is huge, there will be a lot of time spent on downloading the full log.

## Describe the solution you’d like
The worked api support paginations starting from the tail of the log. It will enable you to have an hidden pagination that is called by scrolling upwards. 

## Describe the alternative you’ve considered or used
Attach to the docker worker and see all logs until you find the correct one.

## Additional context
You don't know which log is it because 

## Are you willing to submit a PR?
Yes, but I don't think my employer let me do that

**Comment by timroes** [comment] 2022-06-28 15:56
Duplicate of https://github.com/airbytehq/airbyte/issues/3501

**Closed by timroes** 2022-06-28 15:56 UTC
Labels: type/enhancement, area/frontend, community, team/frontend
