### ISSUE TITLE
Handle a case of full vacuum during a sync

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#27984] opened 2023-07-05 17:09 UTC

**Comment by rodireich** [comment] 2023-07-05 20:27
@prateekmukhedkar After thinking more about adding a check at the very _end_ of the over all initial sync, it doesn't make sense to me because while we may be able to fail the source sync session, at that point the records will have already been written to destination - potentially missing records as a result of a vacuum.
A following sync may be lengthy since it goes back to (0,0) and meantime customer will see partial content.

**Comment by rodireich** [comment] 2023-07-05 20:31
Ideally we want to test for mid sync vacuum at the beginning of each sub-query –– as you suggested initially
I'm seeing how we can make this working with current architecture.

**Comment by subodh1810** [comment] 2023-08-22 17:08
Closing cause this is a duplicate of https://github.com/airbytehq/airbyte/issues/29419

**Closed by subodh1810** 2023-08-22 17:08 UTC
Labels: team/triage
