### ISSUE TITLE
make admin status obvious in the UI

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#7614] opened 2021-11-04 00:25 UTC
We should display a banner, change the color of the sidebar, have a bright icon in the sidebar, or anything to make it obvious that the user is a superadmin.

**Comment by tealjulia** [comment] 2023-02-09 20:16
IIRC it's something along the lines of our call to /workspaces/get would need to return all associated emails, but it only returns the first associated email (ie the person who created it) currently.

This has come up in three separate conversations I've been a part of recently.

**Comment by evantahler** [comment] 2023-02-09 21:00
Because we lack the concept of 'roles' or 'impersonation', perhaps we could always show the banner if you are an instance admin user (which is really what controls workspace access) and you aren't the workspace owner.  It will produce a lot of false positives for anyone looking at the company workspace... but... it's something? 

https://internal-docs.airbyte.io/DBs/Promoting-a-Cloud-User-to-admin

**Comment by mfsiega-airbyte** [comment] 2023-02-14 18:16
Refining notes:
- It's not _totally_ trivial to identify the case.
- If we wanted to make this info available, it would probably have to happen in the backend.
- Proposal: if you're an @airbyte.io user and the workspace owner isn't the same as your email (and/or isn't an airbyte email), then you're a super admin
- Proposal: we can detect admins checking the `cloud/v1/permissions/list` endpoint (and ensure that the instance admin role is getting returned)
- Proposal: beyond just showing a banner, we could consider some frontend-only mechanism to prevent e.g., submitting buttons
- Next steps: spike seeing how feasible this is without (many) backend changes

**Comment by timroes** [comment] 2023-02-16 10:03
I've merged https://github.com/airbytehq/airbyte/issues/22209 into this. I don't think the problem is to indicate you're really an admin user, but basically to indicate whether you are officially a member of a workspace or not, i.e. I think all workspace get/list APIs should return an `isMember: boolean` flag indicating if the current user is a member of that workspace or not. That would help us (a) sorting the workspace listing page to make sure your own workspaces appear on top and (b) indicate if you're inside a workspace that's not "yours" (which is what I have seen people care about, and not if their user in theory has admin rights and could see other workspaces).

**Closed** 2023-03-03 02:15 UTC
Labels: type/enhancement, priority/low, team/platform-compose, autoteam, area/frontend, ui/auth
