### ISSUE TITLE
Failure Origin: replication, Message: Something went wrong during replication

### ISSUE THREAD

**Issue by ramitheeb** [airbytehq/airbyte#19545] opened 2022-11-17 13:25 UTC
## Environment
- **Airbyte version**:  0.40.18
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: k8s
- **Source Connector and version**: E2E Testing 2.1.3
- **Destination Connector and version**: Azure Blob Storage 0.1.6
- **Step where error happened**: Sync job .

## Current Behavior
sync jobs are failing with error:  Failure Origin: replication, Message: Something went wrong during replication

## Expected Behavior
sync jobs should work 

## Logs
[logs](https://github.com/airbytehq/airbyte/files/10031915/stress_test_logs_832_txt.txt)

## Steps to Reproduce
no idea, the issue happens randomly

**Comment by natalyjazzviolin** [comment] 2022-11-28 16:19
Hi @ramitheeb this looks like something that we should troubleshoot first, as it is not reliably reproducible. Could you please start a thread on the forum or Slack? Closing this issue for now.

**Closed by natalyjazzviolin** 2022-11-28 16:19 UTC
Labels: type/bug, community, needs-triage, team/use, autoteam
