### ISSUE TITLE
MySql to Snowflake Error

### ISSUE THREAD

**Issue by thisisile** [airbytehq/airbyte#10159] opened 2022-02-07 20:21 UTC
## Environment **Tried on two machines** ec2 & local machine
- **Airbyte version**:  0.35.6-alpha & 0.35.15-alpha
- **OS Version / Instance**: AWS EC2 8Gb t2/3 large instance & Ubuntu 20.04.3 LTS
- **Deployment**: Kubernetes & Docker
- **Source Connector and version**: MySql 0.5.1 & MySql 0.5.1
- **Destination Connector and version**: Snowflake 0.4.3 & Snowflake 0.4.8
- **Severity**: High / Critical
- **Step where error happened**: Sync job

## Current Behavior
We have Moodle hosted on AWS with its data sitting in Amazon Aurora (not serverless).
Example Moodle schema can be found here: https://www.examulator.com/er/3.7/index.html
I'm doing CDC sync and about 8 tables fail (just to list a few: mdl_user, mdl_block_launchpad)

## Expected Behavior
CDC sync should work for all tables

## Logs
Getting "invalid message" on Kubernetes (AWS EC2)
Sometimes got Java heap memory error.

<details>
<summary>LOG</summary> 

```
**LOG 1(AWS EC2 KUBERNETES):**
2022-01-28 07:19:59 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-01-28 07:19:59 [1;31mERROR[m i.a.i.b.IntegrationRunner(consumeWriteStream):149 - Received invalid message: {"type":"RECORD","record":{"stream":"mdl_question_attempts","data":{"id":46147,"questionusageid":8307,"slot":4,"behaviour":"deferredfeedback","questionid":3309,"variant":1,"maxmark":2,"minfraction":0,"maxfraction":1,"flagged":false,"questionsummary":"What topic has the highest learning time in Grade 9?\n\n: Graphs \n\n; Algebraic equations\n\n; Construction of geometric figures\n\n; Algebraic expressions","rightanswer":"Graphs \n\n","timemodified":1643102878},"emitted_at":1643354264395,"namespace":"MOODLE_UCT_PARTIAL_CDC"}}
2022-01-28 07:20:26 [32mINFO[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-01-28 07:20:26 [1;31mERROR[m i.a.i.b.IntegrationRunner(consumeWriteStream):149 - Received invalid message: {"type":"RECORD","record":{"stream":"mdl_question_attempts","data":{"id":46108,"questionusageid":3078,"slot":1,"behaviour":"deferredfeedback","questionid":3053,"variant":1,"maxmark":1,"minfraction":0,"maxfraction":1,"flagged":false,"questionsummary":"\\( -\\sqrt3 \\) is an imaginary number.","rightanswer":"False","responsesummary":"False","timemodified":1643102076},"emitted_at":1643354264395,"namespace":"MOODLE_UCT_PARTIAL_CDC"}}


**LOG 2 (UBUNTU):**

**2022-02-03 19:59:26 ERROR i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$1):70 - Validation failed: null**


2022-02-03 19:59:35 source > 2022-02-03 19:59:35 INFO i.d.c.m.SnapshotReader(execute):494 - {dbz.connectorContext=snapshot, dbz.connectorName=uctohsDB, dbz.connectorType=MySQL} - Step 6: generating DROP and CREATE statements to reflect current database schemas:
**2022-02-03 20:00:14 ERROR i.a.w.DefaultReplicationWorker(run):158 - Sync worker failed.**
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Destination process exited with non-zero exit code 1



**2022-02-03 20:02:21 normalization > 20:02:21 | 1 of 6 ERROR creating view model _AIRBYTE_MOODLE_TEST_ERRORS_ABS_LOCAL_3515.LATEST_MDL_BLOCK_LAUNCHPAD_STG... [ERROR in 3.60s]**
2022-02-03 20:02:21 normalization > 20:02:21 | 3 of 6 SKIP relation MOODLE_TEST_ERRORS_ABS_LOCAL_3515.LATEST_MDL_BLOCK_LAUNCHPAD_SCD........................ [SKIP]
2022-02-03 20:02:21 normalization > 20:02:21 | 4 of 6 SKIP relation MOODLE_TEST_ERRORS_ABS_LOCAL_3515.LATEST_MDL_BLOCK_LAUNCHPAD............................ [SKIP]
**2022-02-03 20:02:21 normalization > 20:02:21 | 2 of 6 ERROR creating view model _AIRBYTE_MOODLE_TEST_ERRORS_ABS_LOCAL_3515.LATEST_MDL_QUESTION_ATTEMPTS_STG. [ERROR in 3.82s]**
2022-02-03 20:02:21 normalization > 20:02:21 | 5 of 6 SKIP relation MOODLE_TEST_ERRORS_ABS_LOCAL_3515.LATEST_MDL_QUESTION_ATTEMPTS_SCD...................... [SKIP]



**java.lang.RuntimeException: io.temporal.serviceclient.CheckedExceptionWrapper: java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Normalization Failed.**
    at io.airbyte.workers.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:210) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
    at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.normalize(NormalizationActivityImpl.java:74) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
    at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
    at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:286) ~[temporal-sdk-1.6.0.jar:?]
    at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:252) ~[temporal-sdk-1.6.0.jar:?]
    at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:209) ~[temporal-sdk-1.6.0.jar:?]
    at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:193) ~[temporal-sdk-1.6.0.jar:?]
    at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:151) ~[temporal-sdk-1.6.0.jar:?]
    at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) ~[temporal-sdk-1.6.0.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
    at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: io.temporal.serviceclient.CheckedExceptionWrapper: java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Normalization Failed.
    at io.temporal.serviceclient.CheckedExceptionWrapper.wrap(CheckedExceptionWrapper.java:56) ~[temporal-serviceclient-1.6.0.jar:?]
    at io.temporal.internal.sync.WorkflowInternal.wrap(WorkflowInternal.java:412) ~[temporal-sdk-1.6.0.jar:?]
    at io.temporal.activity.Activity.wrap(Activity.java:51) ~[temporal-sdk-1.6.0.jar:?]
    at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:145) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
    at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.lambda$normalize$1(NormalizationActivityImpl.java:98) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
    at io.airbyte.workers.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:205) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
    ... 14 more
Caused by: java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Normalization Failed.
    at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
    at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
    at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:139) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
    at io.airbyte.workers.temporal.sync.NormalizationActivityImpl.lambda$normalize$1(NormalizationActivityImpl.java:98) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
    at io.airbyte.workers.temporal.TemporalUtils.withBackgroundHeartbeat(TemporalUtils.java:205) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
    ... 14 more
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
    at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
    at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
    at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:171) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
    ... 1 more
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
    at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:57) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
    at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
    at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:171) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
    ... 1 more
    Suppressed: io.airbyte.workers.WorkerException: Normalization process wasn't successful
   	 at io.airbyte.workers.normalization.DefaultNormalizationRunner.close(DefaultNormalizationRunner.java:159) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
   	 at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:45) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
   	 at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
   	 at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:171) ~[io.airbyte-airbyte-workers-0.35.15-alpha.jar:?]
   	 at java.lang.Thread.run(Thread.java:833)

```

</details>

## Steps to Reproduce
1. Start Airbyte, setup MySql source (CDC, Incremental deduped history, Jump server), setup Snowflake destination
2. Sync

**Comment by harshithmullapudi** [comment] 2022-02-09 05:47
Hey can you try increasing the resources as mentioned here https://docs.airbyte.io/operator-guides/scaling-airbyte#memory

**Comment by thisisile** [comment] 2022-02-14 08:37
Tried again
Airbyte version: **0.35.26-alpha**
Hosted on AWS EC2 Docker  r5b.large 16Gb RAM

Things work a bit better now, still getting some error logs.

## Logs
*Syncs used to fail when getting below errors in previous versions of Airbyte, but now it seems to succeed. Why do these logs come up ? Will they have an accuracy on the data sync'ed*

<details>
<summary>Binglog position log</summary> 

```
2022-02-14 06:05:16 source > 2022-02-14 06:05:13 INFO i.a.i.s.m.MySqlCdcTargetPosition(reachedTargetPosition):83 - {} - Signalling close because record's binlog file : mysql-bin-changelog.000496 , position : 64295304 is after target file : mysql-bin-changelog.000496 , target position : 64288029

```

</details>
<details>
<summary>Validation failed log</summary> 

```
2022-02-14 08:05:10 source > 	ssl.truststore.type = JKS
2022-02-14 08:05:10 source > 	task.shutdown.graceful.timeout.ms = 5000
2022-02-14 08:05:10 source > 	topic.creation.enable = true
2022-02-14 08:05:10 source > 	topic.tracking.allow.reset = true
2022-02-14 08:05:10 source > 	topic.tracking.enable = true
2022-02-14 08:05:10 source > 	value.converter = class org.apache.kafka.connect.json.JsonConverter
2022-02-14 08:05:10 INFO i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed.
errors: $: unknown found, object expected
**2022-02-14 08:05:10 ERROR i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$1):70 - Validation failed: null**
2022-02-14 08:05:10 source > 2022-02-14 08:05:10 WARN o.a.k.c.r.WorkerConfig(logPluginPathConfigProviderWarning):420 - {} - Variables cannot be used in the 'plugin.path' property, since the property is used by plugin scanning before the config providers that replace the variables are initialized. The raw value 'null' was used for plugin scanning, as opposed to the transformed value 'null', and this may cause unexpected results.
2022-02-14 08:05:10 source > 2022-02-14 08:05:10 WARN i.d.c.Configuration(lambda$getFallbackStringProperty$34):2135 - {} - Using configuration property "table.blacklist" is deprecated and will be removed in future versions. Please use "table.exclude.list" instead.
```

</details>

**Comment by mkhokh-33** [comment] 2022-02-21 14:52
Hi, @thisisile 

I've tried to reproduce the issue from steps to reproduce:
1.Start Airbyte, setup MySql source (CDC, Incremental deduped history, Jump server), setup Snowflake destination
2.Sync

Unfortunately didn't catch any error.

All provided logs seems to be related to different issues:

1. "**2022-02-03 20:02:21 normalization > 20:02:21 | 1 of 6 ERROR creating view model _AIRBYTE_MOODLE_TEST_ERRORS_ABS_LOCAL_3515.LATEST_MDL_BLOCK_LAUNCHPAD_STG... [ERROR in 3.60s]**
2022-02-03 20:02:21 normalization > 20:02:21 | 3 of 6 SKIP relation MOODLE_TEST_ERRORS_ABS_LOCAL_3515.LATEST_MDL_BLOCK_LAUNCHPAD_SCD........................ [SKIP]
"  the first log is about destination normalization issue

2.  "Aborting snapshot due to error when last running SELECT * FROM <DB>.<SCHEMA>: can't call rollback when autocommit=true" is related to source, it's about db snapshot that debezuim is trying to read from db source. 
"autocommit=true" it's mysql setting - https://dev.mysql.com/doc/refman/5.6/en/innodb-autocommit-commit-rollback.html
Maybe there are some particular issue with db settings, but it would be nice to see more logs here,  if possible

3. ".JsonSchemaValidator(test):56 - JSON schema validation failed." this seems to be a known issue where we didn't check that message is empty and log it like error, I'll create an issue to fix it, but is has no impact on sync(I've made small investigation on that)

Could you please provide full sync log? Maybe it will give more information about the way how to reproduce and understand the issue.

Thanks

**Comment by thisisile** [comment] 2022-03-22 14:08
Hi @mkhokh-33
Sorry for the late response and thank you for the update.

I've been fiddling with this for a while. I've tried on updated Airbyte versions too and other issues have appeared.
Current versions:
airbyte 0.35.54-alpha
mysql 0.5.6
snowflake 0.4.20

I have a big dataset and if I'm lucky the sync runs but many a times I get a binlog position error towards the end which stops the whole sync and I have to start again. This seems to be the most common issue that repeats. What could be causing this ?

## Logs
<details>
<summary>Signalling close because record's binlog file : mysql-bin-changelog.000861 , position : 2768433 is after target file : mysql-bin-changelog.000861 , target position : 2732454</summary>
```
2022-03-17 11:11:30 source > 2022-03-17 11:11:30 INFO i.d.c.m.SnapshotReader(lambda$execute$16):677 - Step 7: - 40000 of 27810 rows scanned from table 'uctohsDB.mdl_user_lastaccess' after 00:00:02.656
2022-03-17 11:11:30 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13010000 (5 GB)
2022-03-17 11:11:30 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13011000 (5 GB)
2022-03-17 11:11:31 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13012000 (5 GB)
2022-03-17 11:11:31 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13013000 (5 GB)
2022-03-17 11:11:31 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13014000 (5 GB)
2022-03-17 11:11:31 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13015000 (5 GB)
2022-03-17 11:11:31 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13016000 (5 GB)
2022-03-17 11:11:31 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13017000 (5 GB)
2022-03-17 11:11:31 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13018000 (5 GB)
2022-03-17 11:11:31 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13019000 (5 GB)
2022-03-17 11:11:31 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13020000 (5 GB)
2022-03-17 11:11:31 source > 2022-03-17 11:11:31 INFO i.d.c.m.SnapshotReader(lambda$execute$16):677 - Step 7: - 50000 of 27810 rows scanned from table 'uctohsDB.mdl_user_lastaccess' after 00:00:03.428
2022-03-17 11:11:31 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13021000 (5 GB)
2022-03-17 11:11:31 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13022000 (5 GB)
2022-03-17 11:11:31 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13023000 (5 GB)
2022-03-17 11:11:31 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13024000 (5 GB)
2022-03-17 11:11:31 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13025000 (5 GB)
2022-03-17 11:11:31 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13026000 (5 GB)
2022-03-17 11:11:32 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13027000 (5 GB)
2022-03-17 11:11:32 source > 2022-03-17 11:11:31 INFO i.d.c.m.SnapshotReader(lambda$execute$16):687 - Step 7: - Completed scanning a total of 58939 rows from table 'uctohsDB.mdl_user_lastaccess' after 00:00:03.867
2022-03-17 11:11:32 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13028000 (5 GB)
2022-03-17 11:11:32 source > 2022-03-17 11:11:31 INFO i.d.c.m.SnapshotReader(execute):724 - Step 7: scanned 13046772 rows in 34 tables in 00:28:05.866
2022-03-17 11:11:32 source > 2022-03-17 11:11:31 INFO i.d.c.m.SnapshotReader(execute):761 - Step 8: committing transaction
2022-03-17 11:11:32 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13029000 (5 GB)
2022-03-17 11:11:32 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13030000 (5 GB)
2022-03-17 11:11:32 source > 2022-03-17 11:11:31 INFO i.d.c.m.SnapshotReader(execute):840 - Completed snapshot in 00:28:58.127
2022-03-17 11:11:32 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13031000 (5 GB)
2022-03-17 11:11:32 source > 2022-03-17 11:11:31 INFO i.d.j.JdbcConnection(lambda$doClose$3):945 - Connection gracefully closed
2022-03-17 11:11:32 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13032000 (5 GB)
2022-03-17 11:11:32 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13033000 (5 GB)
2022-03-17 11:11:32 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13034000 (5 GB)
2022-03-17 11:11:32 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13035000 (5 GB)
2022-03-17 11:11:32 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13036000 (5 GB)
2022-03-17 11:11:32 source > 2022-03-17 11:11:32 INFO i.d.c.m.ChainedReader(startNextReader):201 - Transitioning from the snapshot reader to the binlog reader
2022-03-17 11:11:32 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13037000 (5 GB)
2022-03-17 11:11:32 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13038000 (5 GB)
2022-03-17 11:11:32 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13039000 (5 GB)
2022-03-17 11:11:32 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13040000 (5 GB)
2022-03-17 11:11:32 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13041000 (5 GB)
2022-03-17 11:11:32 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13042000 (5 GB)
2022-03-17 11:11:33 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13043000 (5 GB)
2022-03-17 11:11:33 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13044000 (5 GB)
2022-03-17 11:11:33 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13045000 (5 GB)
2022-03-17 11:11:33 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$5):301 - Records read: 13046000 (5 GB)
2022-03-17 11:11:33 source > 2022-03-17 11:11:32 INFO i.a.i.s.m.MySqlCdcTargetPosition(reachedTargetPosition):83 - Signalling close because record's binlog file : mysql-bin-changelog.000861 , position : 2768433 is after target file : mysql-bin-changelog.000861 , target position : 2732454
2022-03-17 11:11:33 source > 2022-03-17 11:11:32 INFO i.d.e.EmbeddedEngine(stop):996 - Stopping the embedded engine
2022-03-17 11:11:33 source > 2022-03-17 11:11:32 INFO i.d.e.EmbeddedEngine(stop):1004 - Waiting for PT5M for connector to stop
2022-03-17 11:11:33 source > 2022-03-17 11:11:33 INFO i.d.c.m.BinlogReader(doStart):367 - GTID set purged on server: 
2022-03-17 11:11:33 source > 2022-03-17 11:11:33 INFO i.d.u.Threads$3(newThread):287 - Creating thread debezium-mysqlconnector-uctohsDB-binlog-client
2022-03-17 11:11:33 source > 2022-03-17 11:11:33 INFO i.d.u.Threads$3(newThread):287 - Creating thread debezium-mysqlconnector-uctohsDB-binlog-client
2022-03-17 11:11:33 source > Mar 17, 2022 11:11:33 AM com.github.shyiko.mysql.binlog.BinaryLogClient connect
2022-03-17 11:11:33 source > INFO: Connected to 127.0.0.1:36769 at mysql-bin-changelog.000861/2768433 (sid:6226, cid:500219)
2022-03-17 11:11:33 source > 2022-03-17 11:11:33 INFO i.d.c.m.BinlogReader$ReaderThreadLifecycleListener(onConnect):1128 - Connected to MySQL binlog at 127.0.0.1:36769, starting at binlog file 'mysql-bin-changelog.000861', pos=2768433, skipping 0 events plus 0 rows
2022-03-17 11:11:33 source > 2022-03-17 11:11:33 INFO i.d.c.m.BinlogReader(doStart):415 - Waiting for keepalive thread to start
2022-03-17 11:11:33 source > 2022-03-17 11:11:33 INFO i.d.u.Threads$3(newThread):287 - Creating thread debezium-mysqlconnector-uctohsDB-binlog-client
2022-03-17 11:11:33 source > 2022-03-17 11:11:33 INFO i.d.c.m.BinlogReader(doStart):422 - Keepalive thread is running
2022-03-17 11:11:33 source > 2022-03-17 11:11:33 INFO i.d.c.c.BaseSourceTask(stop):192 - Stopping down connector
2022-03-17 11:11:33 source > 2022-03-17 11:11:33 INFO i.d.c.m.MySqlConnectorTask(doStop):453 - Stopping MySQL connector task
2022-03-17 11:11:33 source > 2022-03-17 11:11:33 INFO i.d.c.m.ChainedReader(stop):121 - ChainedReader: Stopping the binlog reader
2022-03-17 11:11:33 source > 2022-03-17 11:11:33 INFO i.d.c.m.AbstractReader(stop):140 - Discarding 15 unsent record(s) due to the connector shutting down
2022-03-17 11:16:33 source > 2022-03-17 11:16:33 WARN o.a.s.c.c.AbstractChannel(handleUnknownChannelRequest):312 - handleUnknownChannelRequest(TcpipClientChannel[id=3, recipient=0]-ClientSessionImpl[user@/51.71.132.162:22]) Unknown channel request: keepalive@openssh.com[want-reply=true]
2022-03-17 11:16:33 source > 2022-03-17 11:16:33 WARN o.a.s.c.c.AbstractChannel(handleUnknownChannelRequest):312 - handleUnknownChannelRequest(TcpipClientChannel[id=3, recipient=0]-ClientSessionImpl[user@/51.71.132.162:22]) Unknown channel request: keepalive@openssh.com[want-reply=true]
```
</details>

**Comment by nauxliu** [comment] 2022-04-17 05:47
We are having the same issue with the latest Airbyte

Airbyte Version: 0.36.0-alpha
Source: MySQL (0.5.6)
Destination: Snowflake (0.4.24)

```
2022-04-17 05:39:26 source > 2022-04-17 05:39:26 INFO i.d.c.m.SnapshotReader(lambda$execute$16):677 - Step 7: - 5270000 of 4137144 rows scanned from table 'test.logins' after 00:07:01.546
2022-04-17 05:39:27 source > 2022-04-17 05:39:27 INFO i.d.c.m.SnapshotReader(lambda$execute$16):677 - Step 7: - 5280000 of 4137144 rows scanned from table 'test.logins' after 00:07:02.331
2022-04-17 05:39:27 source > 2022-04-17 05:39:27 INFO i.d.c.m.SnapshotReader(lambda$execute$16):677 - Step 7: - 5290000 of 4137144 rows scanned from table 'test.logins' after 00:07:03.106
2022-04-17 05:39:28 source > 2022-04-17 05:39:28 INFO i.d.c.m.SnapshotReader(lambda$execute$16):687 - Step 7: - Completed scanning a total of 5297029 rows from table 'test.logins' after 00:07:03.636
2022-04-17 05:39:28 source > 2022-04-17 05:39:28 WARN o.a.s.c.u.l.LoggingUtils(warn):618 - exceptionCaught(ClientSessionImpl[airbyte@bastion.ec2.test.com/x.x.x.x:22])[state=Opened] SocketException: Connection reset
2022-04-17 05:39:28 source > 2022-04-17 05:39:28 INFO i.d.c.m.SnapshotReader(execute):761 - Step 7: committing transaction
2022-04-17 05:39:28 source > 2022-04-17 05:39:28 ERROR i.d.c.m.AbstractReader(failed):219 - Failed due to error: Aborting snapshot due to error when last running 'SELECT * FROM `test`.`logins`': Communications link failure
2022-04-17 05:39:28 source > The last packet successfully received from the server was 31 milliseconds ago. The last packet sent successfully to the server was 423,665 milliseconds ago.
2022-04-17 05:39:28 source > org.apache.kafka.connect.errors.ConnectException: Communications link failure
2022-04-17 05:39:28 source > The last packet successfully received from the server was 31 milliseconds ago. The last packet sent successfully to the server was 423,665 milliseconds ago. Error code: 0; SQLSTATE: 08S01.
```

**Comment by thisisile** [comment] 2022-05-13 06:54
@bleonard @mkhokh-33 @harshithmullapudi  This happened again. Any updates on this ?

**Comment by grishick** [comment] 2022-09-01 16:19
@thisisile could you please attach the full log file?

**Comment by grishick** [comment] 2022-09-01 16:21
@nauxliu your error looks like it is caused by SSH tunnel tunnel timeout which was fixed yesterday. Could you try with the latest version of MySQL Source?

**Comment by bleonard** [comment] 2022-09-30 20:44
Closing based on being duplicate of SSH tunnel timeout. @nauxliu @thisisile please reopen if you are still experiencing this issue.

**Closed by bleonard** 2022-09-30 20:44 UTC
Labels: type/bug, community, team/databases, team/db-dw-sources
