### ISSUE TITLE
[destination-s3] Error uploading file to S3 compatible storage due to ETag mismatch

### ISSUE THREAD

**Issue by anikoo-aka** [airbytehq/airbyte#36035] opened 2024-03-13 19:25 UTC
### Connector Name

destination-s3

### Connector Version

0.5.8

### What step the error happened?

During the sync

### Relevant information

The S3 destination connector is complaining about the ETag mismatch. I tried uploading and verifying the ETag using [s3cmd](https://github.com/s3tools/s3cmd) and it worked as expected.

S3 service used in the test: [Linode Object Storage](https://www.linode.com/docs/products/storage/object-storage/) (S3 Compatible)

### Relevant log output

```shell
2024-03-13 18:43:02 destination > 2024-03-13 18:43:02 INFO a.m.s.StreamTransferManager(complete):367 - [Manager uploading to automated-backup-test/backup/orders/2024_03_130.parquet with id 2~HiWD6tn...fGEYmtDv7]: Uploading leftover stream [Part number 1 containing 3.46 MB]
2024-03-13 18:43:02 destination > 2024-03-13 18:43:02 INFO a.m.s.StreamTransferManager(uploadStreamPart):558 - [Manager uploading to automated-backup-test/backup/orders/2024_03_130.parquet with id 2~HiWD6tn...fGEYmtDv7]: Finished uploading [Part number 1 containing 3.46 MB]
2024-03-13 18:43:02 destination > 2024-03-13 18:43:02 ERROR i.a.c.i.d.s.S3StorageOperations(uploadRecordsToBucket):138 - Failed to upload records into storage backup/orders/2024_03_13
2024-03-13 18:43:02 destination > alex.mojaki.s3upload.IntegrityCheckException: File upload completed, but integrity check failed. Expected ETag: 3a7881329c7ea3c7480b590ac8b21634-1 but actual is 
2024-03-13 18:43:02 destination >         at alex.mojaki.s3upload.StreamTransferManager.checkCompleteFileIntegrity(StreamTransferManager.java:407) ~[s3-stream-upload-2.2.2.jar:?]
2024-03-13 18:43:02 destination >         at alex.mojaki.s3upload.StreamTransferManager.complete(StreamTransferManager.java:392) ~[s3-stream-upload-2.2.2.jar:?]
2024-03-13 18:43:02 destination >         at io.airbyte.cdk.integrations.destination.s3.S3StorageOperations.loadDataIntoBucket(S3StorageOperations.java:210) ~[airbyte-cdk-s3-destinations-0.10.2.jar:?]
2024-03-13 18:43:02 destination >         at io.airbyte.cdk.integrations.destination.s3.S3StorageOperations.uploadRecordsToBucket(S3StorageOperations.java:134) ~[airbyte-cdk-s3-destinations-0.10.2.jar:?]
2024-03-13 18:43:02 destination >         at io.airbyte.cdk.integrations.destination.s3.S3ConsumerFactory.lambda$flushBufferFunction$2(S3ConsumerFactory.java:128) ~[airbyte-cdk-s3-destinations-0.10.2.jar:?]
2024-03-13 18:43:02 destination >         at io.airbyte.cdk.integrations.destination.record_buffer.SerializedBufferingStrategy.flushAllBuffers(SerializedBufferingStrategy.java:137) [airbyte-cdk-core-0.10.2.jar:?]
2024-03-13 18:43:02 destination >         at io.airbyte.cdk.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:298) [airbyte-cdk-core-0.10.2.jar:?]
2024-03-13 18:43:02 destination >         at io.airbyte.cdk.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:82) [airbyte-cdk-core-0.10.2.jar:?]
2024-03-13 18:43:02 destination >         at io.airbyte.cdk.integrations.base.Destination$ShimToSerializedAirbyteMessageConsumer.close(Destination.java:96) [airbyte-cdk-core-0.10.2.jar:?]
2024-03-13 18:43:02 destination >         at io.airbyte.cdk.integrations.base.IntegrationRunner.runInternal(IntegrationRunner.java:191) [airbyte-cdk-core-0.10.2.jar:?]
2024-03-13 18:43:02 destination >         at io.airbyte.cdk.integrations.base.IntegrationRunner.run(IntegrationRunner.java:125) [airbyte-cdk-core-0.10.2.jar:?]
2024-03-13 18:43:02 destination >         at io.airbyte.cdk.integrations.base.adaptive.AdaptiveDestinationRunner$Runner.run(AdaptiveDestinationRunner.java:102) [airbyte-cdk-core-0.10.2.jar:?]
2024-03-13 18:43:02 destination >         at io.airbyte.integrations.destination.s3.S3DestinationRunner.main(S3DestinationRunner.java:15) [io.airbyte.airbyte-integrations.connectors-destination-s3-0.50.41.jar:?]
2024-03-13 18:43:02 destination > 2024-03-13 18:43:02 INFO i.a.c.i.d.s.S3StorageOperations(uploadRecordsToBucket):128 - Retrying to upload records into storage backup/orders/2024_03_13 (1/3})
2024-03-13 18:43:02 destination > 2024-03-13 18:43:02 INFO i.a.c.i.d.s.S3DestinationConfig(createS3Client):239 - Creating S3 client...
2024-03-13 18:43:02 destination > 2024-03-13 18:43:02 INFO a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 - Initiated multipart upload to automated-backup-test/backup/orders/2024_03_131.parquet with full ID 2~ZiM--1N2ORdvVY8KFj1N_XHKokesbJt
2024-03-13 18:43:02 destination > 2024-03-13 18:43:02 INFO a.m.s.MultiPartOutputStream(close):158 - Called close() on [MultipartOutputStream for parts 1 - 10000]
2024-03-13 18:43:02 destination > 2024-03-13 18:43:02 ERROR i.a.c.i.d.s.S3StorageOperations(loadDataIntoBucket):204 - Failed to load data into storage backup/orders/2024_03_13
2024-03-13 18:43:02 destination > java.io.IOException: Stream Closed
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by anikoo-aka** [comment] 2024-03-13 19:29
Worth mentioning this issue happens regardless of the output format. I tried with Apache Avro, Parquet, and JSON but got the same error.

**Comment by nitso** [comment] 2024-03-21 07:07
I encounter same error with other S3 compatible storage.
@anikoo-aka do you use encrypted storage? I'm not used with Linode, but I've google couples of messages regarding ETag problem with encrypted storages.

**Comment by marcosmarxm** [comment] 2024-03-22 13:52
@airbytehq/destinations can someone take a look in this issue in the next grooming section?

**Comment by nitso** [comment] 2024-03-28 08:14
FYI: version 0.3.5 works well.

**Comment by PsycheShaman** [comment] 2024-05-15 16:32
Facing a similar issue using Ceph S3 as the destination. File is created successfully on S3 and the E-tag of the object matches the expected E-tag. Not sure how to downgrade only the destination-S3, since I've deployed Airbyte using helm. I haven't changed the helm chart version recently though, so not sure why it's causing a problem now...

**Comment by evantahler** [comment] 2024-05-16 00:33
Can you please confirm you are on the latest s3 destination - 0.6.1?

Would anyone here be willing to look into fixing this check, or to add an option to disable the etag match check if the vendor doesn't report etag properly?

**Comment by PsycheShaman** [comment] 2024-05-17 13:21
@evantahler I can confirm that 0.6.1 and 0.5.9 both give these issues and downgrading to 0.3.5 as @nitso suggested works. Have not tried other versions...

Maybe someone can help me identify the definition_id for Airbyte S3 Destination version 0.3.9 so that I can at least terraform it instead of manually specifying it in the UI? My best guess has been to use this definition_id, but I don't think it's correct, because it looks the same for 3.8 and 3.9: https://github.com/airbytehq/airbyte/pull/14114/files#diff-cf6d9c25b8431c548f892f1628738b7906118ee3be857d15be354119a8130f0f:~:text=name%3A%20S3-,%2D%20name%3A%20S3,destinationDefinitionId%3A%204816b78f%2D1489%2D44c1%2D9060%2D4b19d5fa9362,-destinationDefinitionId%3A%204816b78f

**Comment by evantahler** [comment] 2024-08-13 20:56
Linode is not following the S3 spec, closing this issue as we will not work on an exception at this time.

**Closed by evantahler** 2024-08-13 20:56 UTC
Labels: type/bug, area/connectors, community, connectors/destination/s3, team/destinations, good first issue, good-first-issue

**Comment by nitso** [comment] 2024-08-16 06:45
@evantahler could you please pick exact features from S3 specs that are not followed? These are good to be documented.
Linode is not the only one storage that does not work with S3 connector.

**Comment by Gexar** [comment] 2025-01-31 08:19
Having the the same problem here, ETags do not match
-airbyte platform 1.4.0 
-deployed via abctl local install 0.24
-s3 dest connector version 1.4.0
target service is on prem seaweedfs
