### ISSUE TITLE
Too little logs for deduced incremental replication

### ISSUE THREAD

**Issue by ptkgupta** [airbytehq/airbyte#7227] opened 2021-10-20 22:24 UTC
## Enviroment
- **Airbyte version**:  0.29.21 alpha
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker deployed on AWS instance
- **Source Connector and version**: Postgresql
- **Destination Connector and version**:  Postgresql (deduped history)
- **Severity**: Medium
- **Step where error happened**: Sync job

## Current Behavior
I am using airbyte to replicate a table in postgres which is around 69GBs in size, the read step had to read 59 million entries and tool over 2 days during which the log showed the message about how many rows have been read however after the read was complete I got a few log messages ending with
Currently after the read step of the sync and the log message 
"2021-10-20 10:35:16 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-10-20 10:35:16 INFO i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onCloseFunction$3):194 - {} - Executing finalization of tables."
There are no logs after this and the process has been running for over 5 hours, so without any messages displayed I don't know what is going on (whether the sync is working fine or is there an error). I am uusing 4 GB ram, 200GB diskspace, 2VCPU

## Expected Behavior
I should have some messages about what is happening to help me find a problem and see how the process can be optimised for speed or just check if the process is working fine or not

## Logs

<details>
<summary>LOG</summary> 

[logs-463-0.txt](https://github.com/airbytehq/airbyte/files/7384656/logs-463-0.txt)

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. setup a postgresql-postresql connector with over 100GB of data to be replicated

## Are you willing to submit a PR?
sure, but will need help regarding ow to do it

**Comment by marcosmarxm** [comment] 2021-12-09 23:21
The sync for every source will output the same logs, if the logs is not the same probably the sync is still running.

**Comment by marcosmarxm** [comment] 2022-06-14 00:53
Closing because doens't have enough information to reproduce issue.

**Closed by marcosmarxm** 2022-06-14 00:53 UTC
Labels: type/enhancement, area/platform, community, needs-triage, team/cloud, team/oss
