### ISSUE TITLE
Batch is too large for cassandra as destination.

### ISSUE THREAD

**Issue by Danissss** [airbytehq/airbyte#13589] opened 2022-06-08 05:09 UTC
## Environment
- **Airbyte version**:  0.39.9-alpha
- **OS Version / Instance**: Ubuntu 22.04
- **Deployment**: Docker (docker-compose)
- **Source Connector and version**: MySQL 0.5.11 
- **Destination Connector and version**: Cassandra 0.1.1 
- **Step where error happened**: Sync job 

## Current Behavior
Batch is too large for cassandra intake. 
I can modify the batch_size_fail_threshold_in_kb in cassandra.yaml but I looked around and people say it's not recommended; therefore I was wondering if it's possible to reduce the batch size from airbyte side.

/var/logs/cassandra/system.log
```
ERROR [Native-Transport-Requests-1] 2022-06-08 04:40:49,515 BatchStatement.java:352 - Batch for [amap.airbyte_raw_property_transformed] is of size 753.761KiB, exceeding specified threshold of 50.000KiB by 703.761KiB. (see batch_size_fail_threshold_in_kb)
ERROR [Native-Transport-Requests-1] 2022-06-08 04:40:49,605 BatchStatement.java:352 - Batch for [amap.airbyte_raw_property_transformed] is of size 1.270MiB, exceeding specified threshold of 50.000KiB by 1.221MiB. (see batch_size_fail_threshold_in_kb)
ERROR [Native-Transport-Requests-1] 2022-06-08 04:40:49,675 BatchStatement.java:352 - Batch for [amap.airbyte_raw_property_transformed] is of size 989.195KiB, exceeding specified threshold of 50.000KiB by 939.195KiB. (see batch_size_fail_threshold_in_kb)
ERROR [Native-Transport-Requests-1] 2022-06-08 04:40:49,743 BatchStatement.java:352 - Batch for [amap.airbyte_raw_property_transformed] is of size 929.509KiB, exceeding specified threshold of 50.000KiB by 879.509KiB. (see batch_size_fail_threshold_in_kb)
ERROR [Native-Transport-Requests-1] 2022-06-08 04:40:49,820 BatchStatement.java:352 - Batch for [amap.airbyte_raw_property_transformed] is of size 776.414KiB, exceeding specified threshold of 50.000KiB by 726.414KiB. (see batch_size_fail_threshold_in_kb)
ERROR [Native-Transport-Requests-1] 2022-06-08 04:40:49,898 BatchStatement.java:352 - Batch for [amap.airbyte_raw_property_transformed] is of size 954.118KiB, exceeding specified threshold of 50.000KiB by 904.118KiB. (see batch_size_fail_threshold_in_kb)
ERROR [Native-Transport-Requests-2] 2022-06-08 04:40:49,944 BatchStatement.java:352 - Batch for [amap.airbyte_raw_property_transformed] is of size 690.000KiB, exceeding specified threshold of 50.000KiB by 640.000KiB. (see batch_size_fail_threshold_in_kb)
ERROR [Native-Transport-Requests-1] 2022-06-08 04:40:50,024 BatchStatement.java:352 - Batch for [amap.airbyte_raw_property_transformed] is of size 1018.827KiB, exceeding specified threshold of 50.000KiB by 968.827KiB. (see batch_size_fail_threshold_in_kb)
ERROR [Native-Transport-Requests-1] 2022-06-08 04:40:50,322 BatchStatement.java:352 - Batch for [amap.airbyte_raw_property_transformed] is of size 1.140MiB, exceeding specified threshold of 50.000KiB by 1.091MiB. (see batch_size_fail_threshold_in_kb)
ERROR [Native-Transport-Requests-1] 2022-06-08 04:40:50,385 BatchStatement.java:352 - Batch for [amap.airbyte_raw_property_transformed] is of size 891.752KiB, exceeding specified threshold of 50.000KiB by 841.752KiB. (see batch_size_fail_threshold_in_kb)
ERROR [Native-Transport-Requests-1] 2022-06-08 04:40:50,507 BatchStatement.java:352 - Batch for [amap.airbyte_raw_property_transformed] is of size 1.450MiB, exceeding specified threshold of 50.000KiB by 1.401MiB. (see batch_size_fail_threshold_in_kb)
ERROR [Native-Transport-Requests-1] 2022-06-08 04:40:50,615 BatchStatement.java:352 - Batch for [amap.airbyte_raw_property_transformed] is of size 1.492MiB, exceeding specified threshold of 50.000KiB by 1.443MiB. (see batch_size_fail_threshold_in_kb)
ERROR [Native-Transport-Requests-1] 2022-06-08 04:40:50,675 BatchStatement.java:352 - Batch for [amap.airbyte_raw_property_transformed] is of size 868.115KiB, exceeding specified threshold of 50.000KiB by 818.115KiB. (see batch_size_fail_threshold_in_kb)
ERROR [Native-Transport-Requests-1] 2022-06-08 04:40:50,803 BatchStatement.java:352 - Batch for [amap.airbyte_raw_property_transformed] is of size 1.632MiB, exceeding specified threshold of 50.000KiB by 1.583MiB. (see batch_size_fail_threshold_in_kb)
ERROR [Native-Transport-Requests-1] 2022-06-08 04:40:50,862 BatchStatement.java:352 - Batch for [amap.airbyte_raw_property_transformed] is of size 1.013MiB, exceeding specified threshold of 50.000KiB by 987.269KiB. (see batch_size_fail_threshold_in_kb)
ERROR [Native-Transport-Requests-2] 2022-06-08 04:40:50,925 BatchStatement.java:352 - Batch for [amap.airbyte_raw_property_transformed] is of size 969.914KiB, exceeding specified threshold of 50.000KiB by 919.914KiB. (see batch_size_fail_threshold_in_kb)
WARN  [Native-Transport-Requests-1] 2022-06-08 04:40:50,935 BatchStatement.java:358 - Batch for [amap.airbyte_raw_property_transformed] is of size 22.867KiB, exceeding specified threshold of 5.000KiB by 17.867KiB.
```
## Expected Behavior
*Tell us what should happen.*

## Logs

Log from airbyte
```
2022-06-08 04:40:50 destination > 2022-06-08 04:40:50 ERROR i.a.i.d.c.CassandraCqlProvider(awaitThread):167 - Error while copying data with reason: 
2022-06-08 04:40:50 destination > java.util.concurrent.ExecutionException: com.datastax.oss.driver.api.core.servererrors.InvalidQueryException: Batch too large
2022-06-08 04:40:50 destination > 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
2022-06-08 04:40:50 destination > 	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
2022-06-08 04:40:50 destination > 	at io.airbyte.integrations.destination.cassandra.CassandraCqlProvider.awaitThread(CassandraCqlProvider.java:162) ~[io.airbyte.airbyte-integrations.connectors-destination-cassandra-0.35.27-alpha.jar:?]
2022-06-08 04:40:50 destination > 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
2022-06-08 04:40:50 destination > 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
2022-06-08 04:40:50 destination > 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
2022-06-08 04:40:50 destination > 	at java.util.Collections$2.tryAdvance(Collections.java:4853) ~[?:?]
```

## Steps to Reproduce
1. MySQL as source
2. Cassandra as destination (with default Cassandra configuration)
3. Sync
4. Check the /var/logs/cassandra/system.log

## Are you willing to submit a PR?

Yes.

BTW, the airbyte is super cool

**Comment by marcosmarxm** [comment] 2022-08-01 16:34
Zendesk ticket #[1743](https://airbyte7538.zendesk.com/agent/tickets/1743) has been linked to this issue.

**Comment by pmcfadin** [comment] 2022-08-10 16:29
Hi! Cassandra contributor here and just happened to see this issue. I'm unfamiliar with Airbyte code, but I can help with some guidance on using batches in Cassandra. A Cassandra batch was designed to ensure coordination between like statements. In a distributed system, that coordination comes with a cost, so using a batch statement for performance is an anti-pattern. We put several gaurdrails in Cassandra to prevent users from burning down their clusters.

The fastest way to move data in bulk is by using the async methods in the driver to write in parallel. When a client is sending writes, you can take advantage of multiple nodes by executing one write per mutation in rapid fire. There is a good blog on this here: https://foundev.medium.com/cassandra-batch-loading-without-the-batch-the-nuanced-edition-dd78d61e9885

I would be happy to talk more about this with anyone wanting more insight. You can find me on the ASF slack or patrick@datastax.com

**Comment by yurii-bidiuk** [comment] 2022-08-23 20:13
Hi @grishick 
I replaced our batch insert with async method as @pmcfadin recommended. It resolves this issue and we stop getting `Batch too large`. I made data sync and everything works well, all data is transferred (see logs attached).
Old logs with batch insert with `Batch too large` error:
[sync_with_batch.txt](https://github.com/airbytehq/airbyte/files/9410354/sync_with_batch.txt)
Logs with async method:
[sync with async method.txt](https://github.com/airbytehq/airbyte/files/9410360/sync.with.async.method.txt)

Can we proceed with this approach or we should continue using batch insertion?

**Comment by pmcfadin** [comment] 2022-08-23 23:37
Looks great @yurii-bidiuk ! There really shouldn't be any limit on sizes with this method. I did notice in the logs that the parent process closed while the async threads were still in flight. You've collected all the futures so it should be a matter of waiting for all threads to complete.

**Closed** 2022-08-26 10:35 UTC
Labels: type/bug, area/connectors, community, connectors/destination/cassandra, team/databases, team/connectors-java, zendesk

**Comment by marcosmarxm** [comment] 2022-08-29 14:24
*Comment made from Zendesk by Nataly Merezhuk on 2022-08-29 at 14:24:*

<blockquote><div class="zd-comment" dir="auto">Hi again @animer3009, looks like the issue has been resolved - could you check if the error is gone on your end?<br></div></blockquote>
