### ISSUE TITLE
[Survey Monkey] Better handle backoff policy from Survey Monkey 

### ISSUE THREAD

**Issue by alex-nexus** [airbytehq/airbyte#9131] opened 2021-12-27 23:31 UTC
## Environment
- **Airbyte version**:  example is 0.34.0-alpha
- **OS Version / Instance**: macOS
- **Deployment**: local dev
- **Source Connector and version**: SurveyMonkey 0.1.4
- **Destination Connector and version**: BigQuery 0.5.1
- **Severity**: High 
- **Step where error happened**: Sync job

## Current Behavior

![Screen Shot 2021-12-27 at 1 58 01 PM](https://user-images.githubusercontent.com/1060981/147513401-463dc773-3bab-4c2d-abec-dc05ca6f426a.png)

Error: 
    for record in record_iterator:
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 204, in _read_full_refresh
    for slice in slices:
  File "/airbyte/integration_code/source_surveymonkey/streams.py", line 185, in stream_slices
    for survey in survey_stream.read_records(sync_mode=SyncMode.full_refresh):
  File "/airbyte/integration_code/source_surveymonkey/streams.py", line 84, in read_records
    sync_mode=sync_mode, cursor_field=cursor_field, stream_slice=stream_slice, stream_state=stream_state
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 351, in read_records
    response = self._send_request(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 318, in _send_request
    return backoff_handler(user_backoff_handler)(request, request_kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/streams/http/http.py", line 281, in _send
    raise DefaultBackoffException(request=request, response=response)
airbyte_cdk.sources.streams.http.exceptions.DefaultBackoffException

## Expected Behavior
Should handle backoff policy smoothly

## Logs
[logs-16-0.txt](https://github.com/airbytehq/airbyte/files/7782018/logs-16-0.txt)

## Steps to Reproduce
1. Run `Sync Now`

**Comment by midavadim** [comment] 2022-07-23 19:50
Reproduced error by running 20 parallel syncs.

Fixed incorrect condition in user-defined backoff_time function, so now UserDefinedBackoffException message looks like:

{"type": "LOG", "log": {"level": "INFO", "message": "Backing off _send(...) for 0.0s (airbyte_cdk.sources.streams.http.exceptions.UserDefinedBackoffException: Request URL: https://api.surveymonkey.com/v3/surveys?sort_order=ASC&sort_by=date_modified&per_page=1000&start_modified_at=2021-01-01T00%3A00%3A00, Response Code: 429, Response Text: {\"error\": {\"id\": 1040, \"name\": \"Rate limit reached\", \"docs\": \"https://developer.surveymonkey.com/api/v3/#error-codes\", \"message\": \"Too many requests were made, try again later.\", \"http_status_code\": 429}})"}}
{"type": "LOG", "log": {"level": "INFO", "message": "Retrying. Sleeping for 60 seconds"}}

Additional information:

https://developer.surveymonkey.com/api/v3/#headers
X-Ratelimit-App-Global-Minute-Remaining - Number of remaining requests app has before hitting per minute limit
X-Ratelimit-App-Global-Minute-Reset     - Number of seconds until the rate limit remaining resets

Limits: https://developer.surveymonkey.com/api/v3/#request-and-response-limits
Max Requests Per Day - 500
Max Requests Per Minute - 120

Real limits from API response headers:
"X-Ratelimit-App-Global-Minute-Limit": "720"
"X-Ratelimit-App-Global-Day-Limit": "500000"

**Closed** 2022-08-03 17:45 UTC
Labels: type/bug, area/connectors, community, connectors/sources-api, connectors/source/surveymonkey, team/connectors-python, autoteam
