### ISSUE TITLE
Changing schedule to manual resets the destination naming and vice versa

### ISSUE THREAD

**Issue by edvard-exinity** [airbytehq/airbyte#10844] opened 2022-03-03 21:42 UTC
Is this your first time deploying Airbyte: No
OS Version / Instance: Debian,  GCP c1-standard-4,
Memory / Disk: 16Gb / 100GB SSD
Deployment: Docker
Airbyte Version: 0.35.45-alpha
Source name/version: MSSQL 0.3.17
Destination name/version: BigQuery 0.6.11
Way to replicate:
1. Set custom destination naming for the connection, Save.
2. Change the frequency to manual, Save.
3. The destination namespace changes back to its default.
4. Then try to change the destination namespace back to custom, save
5. The schedule will now be reset to 24hr instead of manual
I am using Prefect to automate Airbyte which automatically sets the sync frequency to manual, this also meant that my namespace reset and changed on the first Airbyte sync.

**Comment by Jamakase** [comment] 2022-03-03 23:30
Duplicate of https://github.com/airbytehq/airbyte/issues/10671

**Closed** 2022-03-04 09:33 UTC
Labels: type/bug, area/frontend, community
