### ISSUE TITLE
Deploy on AWS ECS

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#4919] opened 2021-07-22 17:30 UTC
## Tell us about the problem you're trying to solve
From [slack convo](https://airbytehq.slack.com/archives/C019WJFR1JT/p1626955536311700) was commented [Dagster ECS deployment.](https://github.com/dagster-io/dagster/tree/master/examples/deploy_ecs)

## Describe the solution you’d like
Try if it's possible to use Airbyte docker-compose file to deploy on AWS ECS.

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by davinchia** [comment] 2021-08-16 04:39
this is duplicate of #4847

**Closed by davinchia** 2021-08-16 04:39 UTC
Labels: type/enhancement
