### ISSUE TITLE
🐛 Source Confluence: missing seed files

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#8307] opened 2021-11-29 14:53 UTC
Source Confluence connector is not available for users because it's not listed in `./airbyte-config/init/src/main/resources/seed/source_definitions.yaml`

**Comment by YowanR** [comment] 2023-02-14 02:48
@alafanechere this looks like it has been resolved. Can you confirm before I close this issue?

**Comment by darynaishchenko** [comment] 2023-03-10 09:29
> @alafanechere this looks like it has been resolved. Can you confirm before I close this issue?

@YowanR I can confirm. It's listed in https://github.com/airbytehq/airbyte/blob/master/airbyte-config/init/src/main/resources/seed/source_definitions.yaml#L370

**Closed** 2023-03-15 00:43 UTC
Labels: type/bug, area/connectors, connectors/sources-api, connectors/source/confluence, team/connectors-python, autoteam
