### ISSUE TITLE
Identify where gradle caching is not working

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#11131] opened 2022-03-15 01:12 UTC
## Tell us about the problem you're trying to solve
Identify where gradle caching is not working in OSS and Cloud. For each instance, create an issue and add it to the execution plan in this epic: https://github.com/airbytehq/airbyte/issues/11130

**Comment by davinchia** [comment] 2023-04-06 23:32
duplicate of https://github.com/airbytehq/airbyte-platform-internal/issues/4947

**Closed by davinchia** 2023-04-06 23:32 UTC
Labels: type/enhancement, area/platform, team/platform-compose, team/platform-move
