### ISSUE TITLE
Source Mixpanel: Fails during import

### ISSUE THREAD

**Issue by lfrodrigues** [airbytehq/airbyte#15405] opened 2022-08-08 16:19 UTC
## Environment
- **Airbyte version**:  0.39.42-alpha
- **OS Version / Instance**: Ubuntu 18.04, AWS EC2
- **Deployment**: Docker 
- **Source Connector and version**: Mixpanel 0.1.18
- **Destination Connector and version**: Postgres 1.0.0
- **Step where error happened**: Sync job 

## Current Behavior
Mixpanel sync job fails with the following error:

```  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/utils/transform.py", line 155, in normalizator
    for index, item in enumerate((instance or [])):
RuntimeError: dictionary changed size during iteration
```

## Expected Behavior
It should not crash :) 

## Logs
Attached
[logs-266.txt](https://github.com/airbytehq/airbyte/files/9283365/logs-266.txt)

**Comment by grubberr** [comment] 2022-09-13 07:42
@lfrodrigues 

The problem was in the stream: `cohort_members`.
This stream provided a record field that was inconsistent with the schema and such inconsistency just killed the source connector.

In this PR https://github.com/airbytehq/airbyte/pull/16544 I have fixed part of the problem and the connector will not be killed in such cases anymore.
The 2-nd part of the problem is this inconsistency itself which should be fixed.

Mixpanel connector schema should conform to data.

I cannot understand from log records: what field has a problem

```
{'config': {}, 'list': []} is not of type 'null', 'array'
```

@lfrodrigues
Maybe you can synchronize `cohort_members` again and search all records which contain sub-object: `{'config': {}, 'list': []}`
we would be able to identify a problem and improve the schema

**Comment by grubberr** [comment] 2022-09-15 13:20
I am closing this
This PR https://github.com/airbytehq/airbyte/pull/16544 has to help with crashing

**Closed by grubberr** 2022-09-15 13:20 UTC
Labels: type/bug, community, connectors/source/mixpanel, team/connectors-python, autoteam
