### ISSUE TITLE
Source Google Sheets: Incremental Sync support

### ISSUE THREAD

**Issue by artem1205** [airbytehq/airbyte#29014] opened 2023-08-02 19:38 UTC
### What area the feature impact?

Connectors

### Revelant Information

Add Incremental sync support to connector

**Comment by sherifnada** [comment] 2023-08-02 20:44
duplicate of https://github.com/airbytehq/airbyte/issues/3936 -- gsheets doesn't support incremental

**Closed** 2023-08-09 14:28 UTC
Labels: type/enhancement, connectors/source/google-sheets, team/connectors-python
