### ISSUE TITLE
UI: Connections list shows green success checkmark for syncs that haven't succeeded yet

### ISSUE THREAD

**Issue by zestyping** [airbytehq/airbyte#3723] opened 2021-05-28 19:02 UTC
## Expected Behavior
In the Connections list, the status icon (red X or green checkmark) for each row should reflect the last sync result for that connection.

Specifically, when the last finished sync for a connection failed, and the current sync is still running (i.e. status unknown), the Connections list should show that it is still in the failed state until a success actually occurs.

## Current Behavior
When a sync fails, the Connections list shows the failure as a red X.  But then when the next sync starts, the red X changes to a green checkmark immediately, even though the sync has not succeeded.  If a sync fails repeatedly, the status keeps oscillating between a red X and a green checkmark.

In this example, the Facebook connection has been attempted twice and failed, and it is being attempted again:

![image](https://user-images.githubusercontent.com/236086/120030355-33d7e880-bfac-11eb-961d-fe40c1f47389.png)

But the Connections list shows a green checkmark:

![image](https://user-images.githubusercontent.com/236086/120030456-5b2eb580-bfac-11eb-8bcb-808ac8499d35.png)

## Steps to Reproduce
1. Set up a sync job that fails repeatedly and observe the Connections list when it starts up after a failed attempt.

## Severity of the bug for you
Medium — this does not block anything, but the UI is misleading.  It gives the impression that valid data has been successfully written to the destination, when in fact there might not be anything there.

## Airbyte Version
0.24.2-alpha

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200398796158139) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment] 2021-05-28 19:11
thanks @zestyping, @Jamakase I saw we get icon directly in the front-end, this is correct? can we add a running state?

**Comment by zestyping** [comment] 2021-05-28 20:36
A running state would be great in addition! But please keep the checkmark
or the red X around so I can immediately answer the question "do I have
good data?"

**Comment by marcosmarxm** [comment] 2021-05-28 20:52
yes @zestyping the idea is when the connection is syncing (long-running per example) has one specific icon, but after finished should displayed success/failed status

**Comment by zestyping** [comment] 2021-05-28 21:02
Just to be clear, I mean I'd like the green checkmark or red X to be visible at all times, whether the sync is running or not.  It is useful to know the status of the last completed sync even while the next sync is in progress.

**Comment by marcosmarxm** [comment] 2021-05-28 21:04
oh, sorry totally misunderstand you before

**Comment by Jamakase** [comment] 2021-06-01 23:03
@marcosmarxm as I remember initially this icon showed whether the connection is active or not, so we supported only the next 4 statuses: 
```
export const getConnectionSyncStatus = (
  status: string,
  lastSyncStatus: string | null
): ConnectionStatus | null => {
  if (status === ConnectionStatus.INACTIVE) return ConnectionStatus.INACTIVE;
  if (!lastSyncStatus) return ConnectionStatus.EMPTY;
  if (lastSyncStatus === Status.FAILED) return ConnectionStatus.FAILED;

  return ConnectionStatus.ACTIVE;
};
```

So pending, cancelled and running are all assumed as active.

We could add icons for those statuses, but the problem is that we do not update those statuses on the fly. As there is no support for websockets yet, we use polling where it makes sense. We do not poll lists because it could lead to perf issues.
In this particular case displaying running job and do not updating the status when it is ready - may be a bit confusing.

To successfully implement this task, I think we should have a better protocol for getting real-time updates ( websockets ).

**Comment by jrhizor** [comment] 2021-06-14 14:47
This is particularly confusing for new users when they are performing their first sync. They see the green checkmark when the sync starts running and then look in their destination and only see our temporary tables at best instead of seeing the actual data written.

**Comment by erica-airbyte** [comment] 2022-04-21 15:47
@supertopher it does not look like this was an oncall issue but it is related to one. I think we can close the oncall issue and reopen if more users have confusion with the green check mark when syncs are running.

**Comment by timroes** [comment] 2022-06-29 11:44
This has been fixed by now and the status icon now more accurately represent the status of the connection.

**Closed by timroes** 2022-06-29 11:44 UTC
Labels: type/bug, area/frontend, priority/medium, community, team/frontend
