### ISSUE TITLE
Remove MS-SQL strict encrypt

### ISSUE THREAD

**Issue by prateekmukhedkar** [airbytehq/airbyte#32892] opened 2023-11-28 19:14 UTC

**Comment by alafanechere** [comment] 2023-11-29 13:38
Closing as duplicate of https://github.com/airbytehq/airbyte/issues/32789
FYI @prateekmukhedkar we have this [epic](https://github.com/airbytehq/airbyte/issues/30623) tracking all the strict encrypt removal stories

**Closed by alafanechere** 2023-11-29 13:38 UTC
Labels: team/db-dw-sources
