### ISSUE TITLE
[source-intercom] conversations/search failed with status code 404 and error message Conversation not found. Message deleted.

### ISSUE THREAD

**Issue by proof-nicholas** [airbytehq/airbyte#42853] opened 2024-07-29 16:30 UTC
### Connector Name

Intercom

### Connector Version

0.6.16

### What step the error happened?

During the sync

### Relevant information

We are getting the following error during all our Sync operations using this connector, causing it to partially fail:

"Sync Partially Succeeded:  Request to https://api.intercom.io/conversations/search failed with status code 404 and error message Conversation not found. Message deleted."

My interpretation is that a conversation was deleted and Airbyte can't handle it not being there. Not sure why it would get stuck on this step though or how to get past it.   

Any help would be appreciated, thanks!

### Contribute

- [ ] Yes, I want to contribute

**Comment by proof-nicholas** [comment] 2024-07-31 11:05
Hi, any update on this?

**Comment by topefolorunso** [comment] 2024-08-19 17:12
I'm unable to reproduce this @proof-nicholas . Can you share your error logs?

**Comment by proof-nicholas** [comment] 2024-08-20 23:29
How can I share with you the logs securely, thanks?

**Comment by topefolorunso** [comment] 2024-08-21 01:15
> How can I share with you the logs securely, thanks?

Ping me in slack (@topefolorunso)

**Comment by topefolorunso** [comment] 2024-08-28 21:35
This issue was resolved in #36277. Apparently, something else is causing this.

Below is the cause of what was resolved in #36277
> The issue is under the conversations stream, having the user that might be either an external customer, in this case, there is no opportunity to fetch the data for that conversation, that has been linked to the actual Intercom conversation because it's restricted for the External Users; or - it's a simply the user doesn't exist anymore and we are trying to fetch non-existent entity, which leads to the 404.

fix then was to downgrade from API v2.10 to v2.9. But since then, API has been upgraded to v2.11. Perhaps upgrading to v2.11 will fix this without breaking the previous fix. cc: @natikgadzhi

**Comment by natikgadzhi** [comment] 2024-11-06 17:57
We have another issue to bump to 2.11, so I'll close this and make a new issue for 2.11 in a bit.

**Closed by natikgadzhi** 2024-11-06 17:57 UTC
Labels: type/bug, area/connectors, community, connectors/source/intercom, team/connectors-python, team/marketplace
