### ISSUE TITLE
Encrypt connexion data

### ISSUE THREAD

**Issue by haithem-souala** [airbytehq/airbyte#1971] opened 2021-02-05 14:11 UTC
## Tell us about the problem you're trying to solve
Encrypt source & destination connexion data (e.g: username, password for database)

## Describe the solution you’d like
I think, it would be awesome if we could encrypt sensitive data like database username, password, host & table  when configuring source or destination connector, with the possibility to load the encryption key from different sources:

* Vault - Hashicorp
* KMS - GCP
* Secret - K8s

## Describe the alternative you’ve considered or used
N/A

## Additional context
N/A

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368146650116) by [Unito](https://www.unito.io)

**Comment by michel-tricot** [comment] 2021-02-08 05:50
@haithem-souala is it blocking you today to use Airbyte? We have that in our roadmap, but not in the next 2 months.

**Comment by haithem-souala** [comment] 2021-02-08 08:45
Hi @michel-tricot, Absolutely not, it's a suggestion :)

**Comment by deepsand** [comment] 2021-06-06 06:51
Hi @michel-tricot the above use case is currently blocking me from using Airbyte (really impressed with it otherwise). I suspect this would be the same for any others who want to use it with enterprise clients dealing with sensitive information (I see the request has come up in Slack too). Can you please let me know if it is in the roadmap? Thanks!

**Comment by michel-tricot** [comment] 2021-06-11 05:04
It is actually on our roadmap but medium term.

**Comment by novotl** [comment] 2022-01-19 10:24
Possible duplicate of https://github.com/airbytehq/airbyte/issues/837

**Comment by davinchia** [comment] 2022-11-09 22:34
We've implemented secret persistence support for GCP Secret Manager. See https://docs.airbyte.com/operator-guides/security#credential-management on how to configure.

**Comment by davinchia** [comment] 2022-11-09 22:36
Indeed this is a duplicate of https://github.com/airbytehq/airbyte/issues/837 - will close this as duplicate. Please route discussions there!

**Closed by davinchia** 2022-11-09 22:36 UTC
Labels: type/enhancement, airbyte-cloud, team/cloud, autoteam
