### ISSUE TITLE
Add date selector for any date input field 

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#7840] opened 2021-11-11 00:45 UTC
## Tell us about the problem you're trying to solve
Most users encounter an error at least once when typing the entire date and timestamp and need to go back to the date field to enter it in the right format. It's difficult to know the correct format to enter for these fields on setup.

## Describe the solution you’d like
For a date field, add a calendar so that the user can select a date. For a timestamp field, add an additional time selection.

**Comment by timroes** [comment] 2022-06-28 16:53
Duplicate of https://github.com/airbytehq/airbyte/issues/12197

**Closed by timroes** 2022-06-28 16:53 UTC
Labels: type/enhancement, area/frontend, area/connectors, UX, team/sources-dx, autoteam, team/frontend
