### ISSUE TITLE
Add a dagster job for nightly test reports

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#26398] opened 2023-05-23 07:35 UTC
## Overview
1. Listens for a new nightly test folder
2. Aggregates all results into an html report
3. writes the report to `nightly/reports/<timestamp>/index.html
4. publishes the markdown version of the report to slack

**Comment by alafanechere** [comment] 2023-06-13 14:15
Duplicate of #26397

**Closed** 2023-06-30 10:07 UTC
Labels: team/connector-ops
