### ISSUE TITLE
Automatically detect when gradle caching is broken

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#11132] opened 2022-03-15 01:14 UTC
## Tell us about the problem you're trying to solve
Right now, it is really easy to make a change in gradle and accidentally break caching for the whole project.

## Describe the solution you’d like
I would like a build step (part of static analysis?) that can detect when a gradle module is configured in such a way that it will never cache properly and fails the build.

@jdpgrailsdev do you know if this is actually feasible or if it's me being pie in the sky?

**Comment by davinchia** [comment] 2023-04-06 23:33
duplicate of https://github.com/airbytehq/airbyte-platform-internal/issues/4947

**Closed by davinchia** 2023-04-06 23:33 UTC
Labels: type/enhancement, area/platform, team/platform-compose, team/platform-move
