### ISSUE TITLE
"Confirm verify email" page needs a "Sign Out" button 

### ISSUE THREAD

**Issue by airbyte-jenny** [airbytehq/airbyte#6788] opened 2021-10-05 18:28 UTC
## Enviroment
- **Airbyte version**:  dev cloud
- **OS Version / Instance**: all
- **Deployment**: kubernetes
- **Severity**: Low
- **Step where error happened**: Confirm-verify-email

## Current Behavior
If I sign up for an account, and either don't verify my email address, or follow one of the weird UI flows where I verify it but my current session doesn't know about that, I can get stuck on the confirm-verify-email content, unable to use the app.  It treats me like I have a logged in session.  But it doesn't give the user any way to log out of that session, since I can't get to the main page where the logout functionality is.  My only option is to force my browser to clear my cookies, which is excessive and technical.

## Expected Behavior
The waiting page for confirming email should have a Sign Out button so that, as a regular user, I can invalidate that login session if I want to.  This frees me up to start over if I messed up my sign-up (like a typo'd email address) or if I need to switch user (in case of a team lead creating accounts for all their teammates).

**Comment by jrhizor** [comment] 2021-10-05 20:59
https://github.com/airbytehq/airbyte/issues/6776 is a less specified duplicate of this. I'll close that one.

**Closed** 2021-10-11 16:58 UTC
Labels: type/bug, area/frontend, priority/medium
