### ISSUE TITLE
Provide ability to delete connector (source or destination)

### ISSUE THREAD

**Issue by fwdolegp** [airbytehq/airbyte#2794] opened 2021-04-07 22:58 UTC
## At some point users or developers may want to remove connector from the system. Would be nice to have that capability by using API or UI. 
Use cases: 

1. developer tested new connector and want to clean up.
1. user made a mistake by added wrong connector.
1. keep system thin.

Delete should be disabled if connector in use by at least one integration.

## Describe the solution you’d like
Have an API delete method to remove connector.
Enable delete option on UI (some kind of sub menu).

## Describe the alternative you’ve considered or used
I don't think there are comfortable alternatives.

## Additional context

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368100201719) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment] 2021-04-07 23:40
thanks for the great suggestion @fwdolegp. Totally agreed we should have this. We'll comment here after we prioritize this into a future sprint.

**Comment by sherifnada** [comment] 2021-04-07 23:40
@johnlafleur we'll probably want a design mockup for this too

**Comment by johnlafleur** [comment] 2021-04-08 04:37
If you go in the Settings of your connector, you should be able to delete your source / destination connector. 
<img width="1790" alt="Screen Shot 2021-04-08 at 3 36 17 PM" src="https://user-images.githubusercontent.com/68561602/113969180-3c4f5500-9880-11eb-811c-6b70e1bb92f3.png">

So we're saying essentially that this option is not discoverable enough, aren't we?

**Comment by sherifnada** [comment] 2021-04-08 06:34
@johnlafleur this is for connector **definition** i.e: you can add a new connector defintiion in the admin panel, but you can't remove one the same way

**Comment by johnlafleur** [comment] 2021-04-08 08:49
Here's a design draft:
https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=24507%3A1817

Let me know what you think!

**Comment by michel-tricot** [comment] 2021-04-08 17:50
Questions that we should also ask ourselves for that issue:
- should deleting an active connector automatically delete the active sources or destinations associated to it? should we only support the deletion for unsused connectors?
- should it only apply to the custom added connectors? Or also the ones coming from the airbyte project? What happen when we check for updates?

**Comment by fwdolegp** [comment] 2021-04-08 18:39
I would suggest to be able delete only unused connectors. Advice user with proper information about connector been in use.
On second topic. It was really surprising to see that many connectors bundled at the beginning.  Some of them may be used, but not all of them for sure. Would be nice to have "list of available connectors" with option to add/remove them on demand. This will keep repo or deployment lighter. In addition connectors may have own release schedules.

**Comment by michel-tricot** [comment] 2021-04-08 20:08
Actually the list you see is the list of available connectors, they are not shipped with core. They only get downloaded if you create a source or a destination.

Last month we released the ability separate release schedule and the UI now warns you if your connector is outdated. (https://github.com/airbytehq/airbyte/issues/1983)

What I had in mind was more around: should we provide a way for the administrator of Airbyte to prevent the use of some connectors and not make them available when you create a source/destination.

**Comment by cgardens** [comment] 2021-12-18 00:31
duplicate of: https://github.com/airbytehq/airbyte/issues/8732 which is being actively worked on

**Closed by cgardens** 2021-12-18 00:31 UTC
Labels: type/enhancement
