### ISSUE TITLE
When publishing multiple connectors, one failure can affect the other connectors

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#27681] opened 2023-06-23 22:42 UTC
## overview
When publishing multiple (java) connectors there exists a case where the buildkit/docker daemon can fail.

The cause of this is unknown.

But what does happen is after this moment all other connectors in the publish queue will fail.
[Github action](https://github.com/airbytehq/airbyte/actions/runs/5360434755/jobs/9725303036)
[Slack thread](https://airbytehq-team.slack.com/archives/C056HGD1QSW/p1687557576484219)
![image.png](https://images.zenhubusercontent.com/63d02817d1857451994bd656/764e54ea-7db8-4caa-ac5f-5dc90a25cf77)

## Possible Solution(s)
1. Ignore and hope dagger improves
2. Introduce a supervisor that ensures if there is a docker problem it is restarted
3. One dagger client per connector

**Comment by bnchrch** [comment] 2023-06-23 23:24
Further investigation:

I reran all failed connectors

The pipeline that included s3 failed
![image.png](https://images.zenhubusercontent.com/63d02817d1857451994bd656/0a10c36a-2ac5-41ec-beaa-cfd3e43842d2)

and the other connector in the GHA run also failed with a buildkit scheduler error
![image.png](https://images.zenhubusercontent.com/63d02817d1857451994bd656/fde2ad0e-1922-4a92-8414-5a502db5d088)

**Comment by alafanechere** [comment] 2023-06-26 07:22
> Ignore and hope dagger improves
This is not a dagger error per se, more a problem with the long running docker daemon which is shared with all connectors. Dagger offering us a better way a managing "service container" lifecycle could indeed help/

> One dagger client per connector
I think it's rather one dockerd per connector. It's indeed worth a try as no connector needs to share the dockerd built images with others.

**Comment by alafanechere** [comment] 2023-06-26 08:52
In these failures the root cause is related to a crash of the shared docker daemon used by all connector. This is why the shared dockerd is a single point of failure that can make all connector specific pipeline fail.

**The role of `dockerd`**
* Some integration tests for Java connector start docker test containers.
* Connector acceptance test run `docker run` commands.
* Any gradle project making actual use of the `airbyteDocker` plugin.

**Why we use a shared dockerd daemon:**
We start dockerd as a Dagger service to which container needing access to `docker` are bound to. 
Dagger stops a service if it's not used after 10sec.
We had multiple problems on `dockerd` restart. We believe they are due to not graceful shutdown of the service container by Dagger.
A workaround solution was to implement a long running global dockerd engine that would only be killed on pipeline end.
See https://github.com/airbytehq/airbyte/issues/27233

My suggestion to get more stable pipeline would be to minimize the reliance on dockerd: 
1. I believe the recent rework of normalization mean `dockerd` is not required to build a java connector. I'll try not bounding the gradle container to dockerd [here](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/builds/java_connectors.py#L14) .
2. For CAT: we can replace `docker run` calls with dagger logics.
3. For Java integration tests: we should replace the use of `https://java.testcontainers.org/` with actual connection to test database instances.

1. can be quickly implemented and can help stabilize the publish pipeline for java connectors.
I believe 2 and 3 can wait as the recent nightly builds did not show failures related to `dockerd`.

**Comment by alafanechere** [comment] 2023-08-18 11:54
Closing as the daggerization of CAT should reduce the load on the global dockerd and give java connectors test/build context more resource.

**Closed by alafanechere** 2023-08-18 11:54 UTC
Labels: team/connector-ops, CI/P4
