### ISSUE TITLE
Source Facebook Marketing: upgrade to v13

### ISSUE THREAD

**Issue by valerioditinno** [airbytehq/airbyte#10316] opened 2022-02-14 13:56 UTC
## Environment
- **Airbyte version**:  0.35.27-alpha
- **OS Version / Instance**: Debian GNU/Linux 10 (buster), GCP n1-standard-2
- **Deployment**: on GCP (Compute Engine)
- **Source Connector and version**: Facebook Marketing 0.2.33
- **Severity**: High
- **Step where error happened**: Setup new connection

## Current Behavior
The connection tests failed.
"FacebookAPIException('Error: 2635, (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v13.0.')"

## Expected Behavior
Airbyte connector should handle the newest version of the API.

## Logs
<img width="404" alt="Screenshot 2022-02-14 at 14 51 16" src="https://user-images.githubusercontent.com/11361969/153876994-5e0c62fc-67a5-4fbb-b639-b5cc604a0fdd.png">

## Steps to Reproduce
1.
2.
3.

**Comment by valerioditinno** [comment] 2022-02-14 14:00
similar to [issues/6337](https://github.com/airbytehq/airbyte/issues/6337)

**Comment by marcosmarxm** [comment] 2022-03-04 00:27
@valerioditinno thanks opening this. I'll close as duplicate of  https://github.com/airbytehq/airbyte/issues/10629. I'm doing this because that issue was already asign to the developer.

**Closed by marcosmarxm** 2022-03-04 00:27 UTC
Labels: type/bug, area/connectors, priority/high, community, connectors/source/facebook_marketing
