### ISSUE TITLE
Kubernetes: S3 Destination Sync froze

### ISSUE THREAD

**Issue by m-ronchi** [airbytehq/airbyte#4660] opened 2021-07-09 09:15 UTC
## Enviroment
- **Airbyte version**:  0.27.0-alpha
- **OS Version / Instance**: AWS
- **Deployment**: Kubernetes
- **Source Connector and version**: MySQL 0.3.9
- **Destination Connector and version**: S3 0.1.8
- **Severity**: Medium
- **Step where error happened**:Sync job

## Current Behavior
Job hanging since 3+ hours (previous jobs completed in ~3m)

## Expected Behavior
Job doesn't hangs

## Logs
[logs-15-0.txt](https://github.com/airbytehq/airbyte/files/6790219/logs-15-0.txt)

**Comment by m-ronchi** [comment] 2021-07-09 09:41
I cancelled the job, next job also froze
[logs-15-0.txt](https://github.com/airbytehq/airbyte/files/6790391/logs-15-0.txt)
[logs-16-0.txt](https://github.com/airbytehq/airbyte/files/6790392/logs-16-0.txt)

**Comment by marcosmarxm** [comment] 2021-07-10 16:26
Thanks for reporting this @m-ronchi looks is something related with the pod launch. @jrhizor / @davinchia could you guys check and give your opinion?

**Comment by jrhizor** [comment] 2021-07-12 23:30
@m-ronchi I know this might be too late, but could you `kubectl describe airbyte-worker-15-0-xqvmd`? It looks like the pod for the source got stuck before executing anything. I'm wondering if it had trouble scheduling or was hitting some sort of error before launching. If you encounter this error again, describing the involved pods and posting that would help us debug.

@davinchia judging by the logs in attempt 15 vs attempt 16, does it look like on cancellation it isn't properly closing the socket server?

**Comment by davinchia** [comment] 2021-07-13 03:22
@jrhizor agree looks like 16 is trying to access ports that 15 apparently released by didn't. Specifically from 16:
```
2021-07-09 09:15:34 INFO  Running destination...
2021-07-09 09:15:56 INFO  stdoutLocalPort = 9016
2021-07-09 09:15:56 INFO  stderrLocalPort = 9017
2021-07-09 09:15:56 ERROR Sync worker failed.
io.airbyte.workers.WorkerException: Address already in use
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:116) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
	at io.airbyte.workers.process.AirbyteIntegrationLauncher.write(AirbyteIntegrationLauncher.java:163) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.start(DefaultAirbyteDestination.java:79) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:122) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:52) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:479) ~[?:?]
	at sun.nio.ch.Net.bind(Net.java:468) ~[?:?]
	at sun.nio.ch.NioSocketImpl.bind(NioSocketImpl.java:643) ~[?:?]
	at java.net.ServerSocket.bind(ServerSocket.java:396) ~[?:?]
	at java.net.ServerSocket.<init>(ServerSocket.java:282) ~[?:?]
	at java.net.ServerSocket.<init>(ServerSocket.java:173) ~[?:?]
	at io.airbyte.workers.process.KubePodProcess.<init>(KubePodProcess.java:304) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
	at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:100) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
```

and in 15:
```
2021-07-09 09:15:56 WARN  Process is taking too long to finish. Killing it
2021-07-09 09:15:56 INFO  Destroying Kube process: airbyte-worker-15-0-xqvmd
2021-07-09 09:15:56 INFO  Port consumer releasing: 9016
2021-07-09 09:15:56 INFO  Port consumer releasing: 9017
2021-07-09 09:15:56 INFO  Destroyed Kube process: airbyte-worker-15-0-xqvmd
2021-07-09 09:16:16 INFO  Unable to find pod airbyte-worker-15-0-xqvmd to retrieve exit value. Defaulting to  value 143. This is expected if the job was cancelled.
2021-07-09 09:16:16 INFO  Port consumer releasing: 9016
2021-07-09 09:16:16 INFO  Port consumer releasing: 9017
```

**Comment by m-ronchi** [comment] 2021-07-13 09:23
@jrhizor sorry, it seems that pod has been deleted.

**Comment by m-ronchi** [comment] 2021-07-15 08:17
Hi,
it happened again last night.
all my connections are frozen:
- `MySQL` -> `S3`
- `MySQL` -> `Redshift`
- `Postgres` -> `S3`
- `Postgres` -> `Redshift`
the only worker pod I have seems to be the S3 destination of the first connection.

[logs-39-0.txt](https://github.com/airbytehq/airbyte/files/6821392/logs-39-0.txt)
[logs-40-0.txt](https://github.com/airbytehq/airbyte/files/6821426/logs-40-0.txt)
[logs-41-0.txt](https://github.com/airbytehq/airbyte/files/6821427/logs-41-0.txt)
[logs-42-0.txt](https://github.com/airbytehq/airbyte/files/6821428/logs-42-0.txt)

kubectl diagnostics:
[diagnostics.txt](https://github.com/airbytehq/airbyte/files/6821401/diagnostics.txt)
[pod-sweeper.txt](https://github.com/airbytehq/airbyte/files/6821449/pod-sweeper.txt)

connector versions:
- MySQL: 0.4.0
- Postgres: 0.3.4
- S3: 0.1.9
- Redshift: 0.3.10

**Comment by m-ronchi** [comment] 2021-07-15 10:51
I am delving into the source.

unless I missed something, the only "interesting" place that can cause a deadlock between the last log printed in the frozen job and the next log that should normally print is [around here](https://github.com/airbytehq/airbyte/blob/af57170d215b90ef8de9a80e6436892e0e8bc3db/airbyte-workers/src/main/java/io/airbyte/workers/process/KubeProcessFactory.java#L85) when fetching the port from a blocking queue.

then I checked a previous log and I found this:

```
.....
2021-07-14 14:04:19 INFO  stdoutLocalPort = 9026
2021-07-14 14:04:19 INFO  stderrLocalPort = 9027
.....
2021-07-14 14:04:30 INFO  stdoutLocalPort = 9012
2021-07-14 14:04:30 INFO  stderrLocalPort = 9013
.....
2021-07-14 14:05:22 INFO  Port consumer releasing: 9026
2021-07-14 14:05:22 INFO  Port consumer releasing: 9027
.....
2021-07-14 14:05:22 INFO  stdoutLocalPort = 9016
2021-07-14 14:05:22 INFO  stderrLocalPort = 9017
.....
2021-07-14 14:05:56 INFO  Port consumer releasing: 9016
2021-07-14 14:05:56 INFO  Port consumer releasing: 9017
2021-07-14 14:05:56 INFO  Port consumer skipping releasing: 9016
2021-07-14 14:05:56 INFO  Port consumer skipping releasing: 9017
.....
```

it appears that some ports (9012, 9013) are not released and leaked. then the scheduler runs out of ports and blocks forever?

**Comment by davinchia** [comment] 2021-07-15 12:21
@m-ronchi how closely spaced are your jobs? what is the duration between them? I will try to reproduce this my side.

**Comment by m-ronchi** [comment] 2021-07-15 12:23
I have a total of 6 jobs for now, pretty spaced out: 
![image](https://user-images.githubusercontent.com/35332423/125787374-2f9194c2-4aeb-4ed1-b7aa-b401e8015758.png)

**Comment by m-ronchi** [comment] 2021-07-15 13:15
checking most of my logs, [this line](https://github.com/airbytehq/airbyte/blob/aca70d0f0d1dc1c7d230db29abd1fe6e99d0042e/airbyte-workers/src/main/java/io/airbyte/workers/protocols/airbyte/DefaultAirbyteSource.java#L124) is never printed

**Comment by davinchia** [comment] 2021-07-15 14:57
how long does each job take to run? do they run concurrently?

**Comment by m-ronchi** [comment] 2021-07-15 15:15
I don't think they run concurrently, as they were added one at a time. they usually complete in a couple of minutes (the longest one 18 but it was the first sync to redshift of 2GB of data - all connections are set to incremental)

I noticed from my logs that the ports from sources are never released, while destinations seems to be ok

**Comment by jrhizor** [comment] 2021-07-15 16:22
@davinchia After looking at this for a bit I thought of a potential deadlock case that may happen if there were other sources and destinations running concurrently. We `take` individual ports, but it's theoretically possible (but not extremely likely) that two separate `KubePodProcess` would `take` the last port and they would both be deadlocked waiting for a port. Changing from a `BlockingQueue<Integer>` to a `BlockingQueue<Pair<Integer>>` would fix this issue. Just because other pods aren't running doesn't mean the other `take` calls aren't deadlocked.

That doesn't explain the lack of releasing, so this ticket may be a different problem.

Separately, we also need better testing around failure cases for port releasing. 

I won't be able to have time to work on this today but I should be able to spend time on this tomorrow.

**Comment by jrhizor** [comment] 2021-07-15 16:23
@m-ronchi Thanks for your detailed logs / versions / `kubectl` output by the way! This _really_ helps our debugging process here.

**Comment by davinchia** [comment] 2021-07-16 14:44
I was able to replicate the hanging behaviour in EKS on the 15th job.

<img width="1073" alt="Screen Shot 2021-07-16 at 10 42 48 PM" src="https://user-images.githubusercontent.com/9772859/125965543-0a62fbeb-6ace-4694-b88c-fb073c6510f1.png">

@m-ronchi Jared and I think we know what the issue is. Currently working on a fix. Will tag you when it's ready!

I think this is related to #4389

**Closed** 2021-07-20 04:23 UTC
Labels: kubernetes, priority/high, type/bug
