### ISSUE TITLE
[EPIC] Auto-Detect Schema Changes

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#14278] opened 2022-06-29 23:05 UTC
PRD:
https://docs.google.com/document/d/1hvwPXnfi0TMK05dnh4Oy-n5WEDCD9msCbUOLxwnp0Uw/edit

**Comment by octavia-squidington-iii** [comment] 2022-07-07 15:37
cc @airbytehq/frontend

**Comment by evantahler** [comment] 2022-08-01 20:44
There's some info in the original feature request https://github.com/airbytehq/airbyte/issues/1000

**Comment by edmundito** [comment] 2022-08-04 15:39
Current status:
- PRD Ready
- Backend work is expected to start in Late August/Early September
- Frontend work may be at risk for EOQ delivery

**Comment by edmundito** [comment] 2022-08-19 20:47
Followed up with @andyjih:

* PRD is still in-flight and needs more iteration
* There are some designs ready but will change based on PRD changes.

**Comment by grishick** [comment] 2022-09-06 17:50
Use case: https://github.com/airbytehq/oncall/issues/505

**Comment by jdpgrailsdev** [comment] 2022-10-05 18:04
Duplicate of #17520

**Closed by jdpgrailsdev** 2022-10-05 18:05 UTC
Labels: Epic, team/workflow, team/frontend
