### ISSUE TITLE
Destination Postgres: can not connect schema with `/` in schema

### ISSUE THREAD

**Issue by thanhlmm** [airbytehq/airbyte#6661] opened 2021-10-03 02:53 UTC
## Enviroment
- **Airbyte version**:  0.29.7-alpha
- **OS Version / Instance**: Ubuntu 20
- **Deployment**: Docker
- **Source Connector and version**: Github
- **Destination Connector and version**: Postgres
- **Severity**: Medium
- **Step where error happened**: Setup new connection

## Current Behavior
![image](https://user-images.githubusercontent.com/9281080/135737694-f40d3fc3-13e7-4e07-8e13-823995f73484.png)
The schema name automatically replace `/` with `_`

## Expected Behavior
Expected we can connect normally with `/` in schema

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by marcosmarxm** [comment] 2021-10-05 00:33
Thanks for reporting this @thanhlmm. If you create previously the schema is possible to connect, can you do this workaround for now?

**Comment by thanhlmm** [comment] 2021-10-05 01:27
No I can not, this is created schema and I can not connect to it

**Comment by sashaNeshcheret** [comment] 2021-12-07 16:52
Previously we replaced all non alphanumeric characters with `_`, so everywhere we expect schema names without `/`. @sherifnada please clarify that for now we want to allow `/` in at least schema name(need to investigate tables and identifiers). If yes are we going to do it only for postgres or for all destination? Additionally for we need put "" around all names where we allow `/`, like "schema/name".

**Comment by sherifnada** [comment] 2021-12-08 05:37
@sashaNeshcheret I believe it is required to also do this in normalization for it to work correctly. @ChristopheDuong do you mind taking point on this issue/on what are the steps required to implement this? Is it the below? 
1. replace `/` with `_` in the DB connector
2. do the same in normalization

**Comment by ChristopheDuong** [comment] 2021-12-08 09:59
The problem reported here is that Airbyte does not allow special characters in the schema:

> The schema name automatically replace / with _

So if my destination settings are:
![Screenshot 2021-12-08 at 10 54 36](https://user-images.githubusercontent.com/7718175/145187654-aaca9591-373a-402a-9ad8-63c03d43b442.png)

and my connection settings are:
![Screenshot 2021-12-08 at 10 56 27](https://user-images.githubusercontent.com/7718175/145187924-59734b36-0305-4efb-9152-c62b59169a55.png)


I would expect data being sync into `"airbyte/tests"."files/covid"` but using current Airbyte, they end up as:
![Screenshot 2021-12-08 at 10 58 07](https://user-images.githubusercontent.com/7718175/145188245-f565ca1a-bf19-4413-829c-bcc2dd3f22ef.png)

**Comment by ChristopheDuong** [comment] 2021-12-08 10:16
Making the following changes to the output of normalization:
- `dbt_project.yml`
- models files:
![Screenshot 2021-12-08 at 11 11 28](https://user-images.githubusercontent.com/7718175/145190190-8d3ad5b4-46b9-4565-858e-f6eb8c0ca164.png)

Would give the expected output:
![Screenshot 2021-12-08 at 11 09 47](https://user-images.githubusercontent.com/7718175/145190217-ebc59fe8-d569-4bc4-8eba-2d213a3e61e8.png)

Since this is different from default Airbyte choices of replacing everything by `_`, please follow https://docs.airbyte.io/operator-guides/transformation-and-normalization/transformations-with-dbt to customize your outputs as you desire!

**Comment by ChristopheDuong** [comment] 2021-12-08 10:37
Or maybe it's time to revert this: https://github.com/airbytehq/airbyte/issues/1785 WDYT @sherifnada?

**Comment by sherifnada** [comment] 2021-12-08 21:14
It feels like the "ideal" choice here is to allow special chars for destinations which allow it and disable for those that don't. But doing that correctly would require a destination to either declare the charset it supports in schema/table names (maybe via spec?), _or_ to run a connection check that creates a table in the target namespace to verify it can be done. 

Both of those are not trivial changes. So maybe we do the following instead? 

1. for destinations which support special chars, it's okay to use them in destination schemas (in connector configuration)
2. when configuring table prefixes on connectors, limit the user to the alphanumeric + `_` charset. This would be a platform/UI-level change. 

Chris if this sounds good to you we can probably do point1 on the connector team, but point 2 will need to go to platform/frontend

**Comment by sashaNeshcheret** [comment] 2021-12-09 11:59
@ChristopheDuong what do you think about the above-mentioned by Sherif?

**Comment by ChristopheDuong** [comment] 2021-12-09 12:56
Yes, it would be nice to add in the spec of the connector the supported charset for identifiers (schema/table/column names)

We would then be able to refactor and retire this set of java classes:
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/bases/base-java/src/main/java/io/airbyte/integrations/destination/NamingConventionTransformer.java

The declared charset would make this logic handled regardless of the language used to implement the destination.

The UI, the platform, and normalization would then be able to adapt their behavior to follow the charset.

> when configuring table prefixes on connectors, limit the user to the alphanumeric + _ charset. 

In that case, the prefixes and namespace override don't have to limit that much but they would check the declared charset is enforced

**Comment by sashaNeshcheret** [comment] 2022-01-12 14:12
@sherifnada After discussion with team we have several concerns about moving allowed symbols for identifiers into specs, should it be hidden from user on ui, do we want to keep validation and replacing forbidden symbols on server side or we will do it only on UI? Just want to double check it. And if we move on this way, connector team should do following:
	- investigate all databases to identify allowed symbols,
	- add this symbols to specs
	- remove logic about converting to alphabetic, numeric and underscore symbols in identifiers from connectors.

**Comment by sherifnada** [comment] 2022-01-12 14:47
@sashaNeshcheret that makes sense.  Wdyt about restrict the charset to alphanumeric+underscore, basically the two bullet points I made in my previous post above?

**Comment by sashaNeshcheret** [comment] 2022-01-14 14:00
@sherifnada sorry for delay, it looks good. We will implement adding allowed symbols for identifiers to postgres destination connector in scope of this issue. Additionally we will wait for implementing UI part before pushing our changes.

**Comment by sashaNeshcheret** [comment] 2022-05-20 10:18
Currently the issue is blocked by [UI part ](https://github.com/airbytehq/airbyte/issues/13051)

**Comment by cgardens** [comment] 2024-04-03 22:36
Closing due to staleness. Please reopen if you're still running into this!

**Closed by cgardens** 2024-04-03 22:36 UTC
Labels: type/bug, help-welcome, area/connectors, community, connectors/destinations-database, connectors/destination/postgres, team/destinations, frozen
