### ISSUE TITLE
add `airbyte-proxy` to helm chart

### ISSUE THREAD

**Issue by pcorbel** [airbytehq/airbyte#23433] opened 2023-02-24 14:12 UTC
## Tell us about the problem you're trying to solve
With the current helm chart, when deploying Airbyte, all the API calls are going through the `airbyte-webapp` pod and ingress.
It's a SPOF and, in no way, using the frontend should impact the access to the API.

## Describe the solution you’d like
I would like a dedicated `airbyte-proxy` pod and ingress available to securely and efficiently access the API.

## Describe the alternative you’ve considered or used
For now, I access the API via the `airbyte-webapp` and I've secured the access at the ingress level.

## Additional context
Original slack discussion -> https://airbytehq.slack.com/archives/C021JANJ6TY/p1676933974638849

## Are you willing to submit a PR?
I'm not confident enough

**Comment by evantahler** [comment] 2023-03-13 14:16
Closing as a duplicate of https://github.com/airbytehq/airbyte/issues/17866

**Closed** 2023-03-13 14:16 UTC
Labels: type/enhancement, area/api, area/platform, community, helm, team/platform-compose, team/platform-enablement
