### ISSUE TITLE
[source-notion] syncs failing since 06/25/2024

### ISSUE THREAD

**Issue by stuartjohnpage** [airbytehq/airbyte#40663] opened 2024-07-01 18:51 UTC
### Connector Name

source-notion

### Connector Version

3.0.6

### What step the error happened?

During the sync

### Relevant information

The Notion source connection is created from Oauth 2.0, both through the Airbyte Cloud UI, or using the integration we have on our app. Each time, regardless of how the connection is created, it fails with the message below.

I'd wager this was due to a PR on the day that all the syncs started failing, when the docker build was bumped.

It's worth mentioning that the sync doesn't actually *fail* immediately after the error. It continues lurching on for another hour before eventually falling over.

### Relevant log output

```shell
at com.networknt.schema.JsonSchema.from(JsonSchema.java:66) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.doCreate(JsonSchemaFactory.java:313) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.create(JsonSchemaFactory.java:309) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidationContext.newSchema(ValidationContext.java:57) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.PropertiesValidator.<init>(PropertiesValidator.java:52) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:163) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:496) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:62) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.read(JsonSchema.java:467) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:1085) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:150) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.from(JsonSchema.java:66) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.doCreate(JsonSchemaFactory.java:313) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.create(JsonSchemaFactory.java:309) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidationContext.newSchema(ValidationContext.java:57) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.PropertiesValidator.<init>(PropertiesValidator.java:52) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:163) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:496) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:62) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.read(JsonSchema.java:467) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:1085) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:150) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.from(JsonSchema.java:66) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.doCreate(JsonSchemaFactory.java:313) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.create(JsonSchemaFactory.java:309) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidationContext.newSchema(ValidationContext.java:57) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.PropertiesValidator.<init>(PropertiesValidator.java:52) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:163) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:496) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:62) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.read(JsonSchema.java:467) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:1085) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:150) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.from(JsonSchema.java:66) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.doCreate(JsonSchemaFactory.java:313) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.create(JsonSchemaFactory.java:309) ~[json-schema-validator-1.4.0.jar:?]
        at io.airbyte.validation.json.JsonSchemaValidator.getSchemaValidator(JsonSchemaValidator.java:220) ~[io.airbyte-airbyte-json-validation-dev.jar:?]
        at io.airbyte.validation.json.JsonSchemaValidator.initializeSchemaValidator(JsonSchemaValidator.java:81) ~[io.airbyte-airbyte-json-validation-dev.jar:?]
        at io.airbyte.workers.RecordSchemaValidator.<init>(RecordSchemaValidator.java:64) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at io.airbyte.workers.RecordSchemaValidator.<init>(RecordSchemaValidator.java:46) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at io.airbyte.workers.RecordSchemaValidator.<init>(RecordSchemaValidator.java:41) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at io.airbyte.workers.general.ReplicationWorkerFactory.createRecordSchemaValidator(ReplicationWorkerFactory.java:288) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at io.airbyte.workers.general.ReplicationWorkerFactory.create(ReplicationWorkerFactory.java:150) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at io.airbyte.container_orchestrator.orchestrator.ReplicationJobOrchestrator.runJob(ReplicationJobOrchestrator.java:118) ~[io.airbyte-airbyte-container-orchestrator-dev.jar:?]
        at io.airbyte.container_orchestrator.Application.run(Application.java:78) [io.airbyte-airbyte-container-orchestrator-dev.jar:?]
        at io.airbyte.container_orchestrator.Application.main(Application.java:38) [io.airbyte-airbyte-container-orchestrator-dev.jar:?]
Caused by: java.lang.UnsupportedOperationException: No suitable validator for id
        at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:161) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:496) ~[json-schema-validator-1.4.0.jar:?]
        ... 50 more
2024-07-01 18:49:44 INFO i.a.c.AsyncStateManager(write):51 - Writing async status FAILED for KubePodInfo[namespace=jobs, name=orchestrator-repl-job-14062310-attempt-0, mainContainerInfo=KubeContainerInfo[image=airbyte/container-orchestrator:build-45735c0269-19179-master, pullPolicy=IfNotPresent]]...
2024-07-01 18:49:44 INFO i.a.a.SegmentAnalyticsClient(close):240 - Closing Segment analytics client...
2024-07-01 18:49:44 INFO i.a.a.BlockingShutdownAnalyticsPlugin(waitForFlush):296 - Waiting for Segment analytic client to flush enqueued messages...
2024-07-01 18:49:44 INFO i.a.a.BlockingShutdownAnalyticsPlugin(waitForFlush):308 - Segment analytic client flush complete.
2024-07-01 18:49:44 INFO i.a.a.SegmentAnalyticsClient(close):244 - Segment analytics client closed.  No new events will be accepted.
2024-07-01 18:49:41 replication-orchestrator > sourceLauncherConfig is: io.airbyte.persistence.job.models.IntegrationLauncherConfig@253a2bfa[jobId=14062310,attemptId=0,connectionId=691a8f7c-f125-4123-bd75-22e0bd2334e2,workspaceId=cd9b6354-f881-4f66-9314-ebce33aeaa19,dockerImage=airbyte/source-notion:3.0.6,normalizationDockerImage=<null>,supportsDbt=false,normalizationIntegrationType=<null>,protocolVersion=Version{version='0.2.0', major='0', minor='2', patch='0'},isCustomConnector=false,allowedHosts=io.airbyte.config.AllowedHosts@22c5c530[hosts=[api.notion.com, *.datadoghq.com, *.datadoghq.eu, *.sentry.io],additionalProperties={}],additionalEnvironmentVariables=<null>,additionalLabels={connection_id=691a8f7c-f125-4123-bd75-22e0bd2334e2, job_id=14062310, attempt_id=0, workspace_id=cd9b6354-f881-4f66-9314-ebce33aeaa19, airbyte=job-pod, mutex_key=691a8f7c-f125-4123-bd75-22e0bd2334e2, workload_id=691a8f7c-f125-4123-bd75-22e0bd2334e2_14062310_0_sync, auto_id=76169b6b-bb43-4d20-b1c6-30e9a06c7cec},priority=<null>,additionalProperties={}]
2024-07-01 18:49:44 replication-orchestrator > Could not load validator id
2024-07-01 18:49:03 platform > Executing worker wrapper. Airbyte version: build-45735c0269-19179-master-cloud
2024-07-01 18:49:03 platform > Creating workload 691a8f7c-f125-4123-bd75-22e0bd2334e2_14062310_0_sync
2024-07-01 18:49:03 platform > Unknown feature flag "workload.polling.interval"; returning default value
2024-07-01 18:49:03 platform > Workload 691a8f7c-f125-4123-bd75-22e0bd2334e2_14062310_0_sync is pending
2024-07-01 18:49:03 INFO i.a.w.l.c.WorkloadApiClient(claim):69 - Claimed: true for 691a8f7c-f125-4123-bd75-22e0bd2334e2_14062310_0_sync via API for prod-dataplane-gcp-us-west3-0
2024-07-01 18:49:03 INFO i.a.w.l.p.s.m.Stage(apply):39 - APPLY Stage: CHECK_STATUS — (workloadId = 691a8f7c-f125-4123-bd75-22e0bd2334e2_14062310_0_sync) — (dataplaneId = prod-dataplane-gcp-us-west3-0)
2024-07-01 18:49:03 INFO i.a.w.l.p.s.CheckStatusStage(applyStage):59 - No pod found running for workload 691a8f7c-f125-4123-bd75-22e0bd2334e2_14062310_0_sync
2024-07-01 18:49:03 INFO i.a.w.l.p.s.m.Stage(apply):39 - APPLY Stage: BUILD — (workloadId = 691a8f7c-f125-4123-bd75-22e0bd2334e2_14062310_0_sync) — (dataplaneId = prod-dataplane-gcp-us-west3-0)
2024-07-01 18:49:04 INFO i.a.w.l.p.s.m.Stage(apply):39 - APPLY Stage: MUTEX — (workloadId = 691a8f7c-f125-4123-bd75-22e0bd2334e2_14062310_0_sync) — (dataplaneId = prod-dataplane-gcp-us-west3-0)
2024-07-01 18:49:04 INFO i.a.w.l.p.s.EnforceMutexStage(applyStage):54 - Mutex key: 691a8f7c-f125-4123-bd75-22e0bd2334e2 specified for workload: 691a8f7c-f125-4123-bd75-22e0bd2334e2_14062310_0_sync. Attempting to delete existing pods...
2024-07-01 18:49:04 INFO i.a.w.l.p.s.EnforceMutexStage(applyStage):58 - Existing pods for mutex key: 691a8f7c-f125-4123-bd75-22e0bd2334e2 deleted.
2024-07-01 18:49:04 INFO i.a.w.l.p.s.m.Stage(apply):39 - APPLY Stage: LAUNCH — (workloadId = 691a8f7c-f125-4123-bd75-22e0bd2334e2_14062310_0_sync) — (dataplaneId = prod-dataplane-gcp-us-west3-0)
2024-07-01 18:49:04 INFO i.a.c.EnvConfigs(getEnvOrDefault):382 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2024-07-01 18:49:04 INFO i.a.c.EnvConfigs(getEnvOrDefault):382 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2024-07-01 18:49:04 INFO i.a.c.EnvConfigs(getEnvOrDefault):382 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2024-07-01 18:49:04 INFO i.a.c.EnvConfigs(getEnvOrDefault):382 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2024-07-01 18:51:03 platform > Workload 691a8f7c-f125-4123-bd75-22e0bd2334e2_14062310_0_sync is claimed
2024-07-01 18:53:03 platform > Workload 691a8f7c-f125-4123-bd75-22e0bd2334e2_14062310_0_sync is claimed
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by MoralesPablo** [comment] 2024-07-01 20:54
Same problem here.

**Comment by mgoldsborough** [comment] 2024-07-01 23:39
Same issue here.

**Comment by marcosmarxm** [comment] 2024-07-03 16:41
Hello all 👋 I raised the problem to the connector team. Any update return here.

**Comment by marcosmarxm** [comment] 2024-07-03 16:50
Hello all, this was fixed in [this commit](https://github.com/airbytehq/airbyte-platform/commit/3e123edaa2a7feb7240ac469db84dc82520804c1), if you're using Airbyte Cloud the problem is solved, if you're using Airbyte OSS please upgrade to the latest version. 

@stuartjohnpage let me know if it's working now.

**Comment by stuartjohnpage** [comment] 2024-07-03 16:57
@marcosmarxm this has indeed fixed it! Thank you so much!

**Comment by mag-Ss** [comment] 2024-07-08 20:47
Hello everyone,
I am facing a sync problem with my Airbyte instance (version 0.63.4). I am getting the following error message:

Sync Failed
0 Bytes
No records extracted
No records loaded
1m 15s
Error in destination: "You must upgrade your platform version to use this connector version. Either downgrade your connector or upgrade platform to 0.63.0."
Has anyone encountered this issue before or know how I can resolve it?
Thank you in advance for your help!

**Comment by stuartjohnpage** [comment] 2024-07-09 16:49
@mag-Ss That seems like a separate issue that may warrant its own issue. 

oh, nice! beat me to it 😁

**Closed** 2024-07-09 16:49 UTC
Labels: type/bug, area/connectors, community, connectors/source/notion, team/connectors-python
