### ISSUE TITLE
CDK: typing errors in sources.singer

### ISSUE THREAD

**Issue by vitaliizazmic** [airbytehq/airbyte#9975] opened 2022-02-01 17:24 UTC
## Environment
- **Source Connector and version**: CDK
- **Severity**: Low

## Current Behavior
This is part of #9500. Running ```mypy airbyte_cdk``` returns typing errors. Most of them is connected with ```sources.singer``` code. They are "Incompatible type error". E.g, Return type "str" of "read_catalog" incompatible with return type "ConfiguredAirbyteCatalog" in supertype "Source" in ```singer.source```.

## Expected Behavior
Need to fix typing errors in ```sources.singer```

## Steps to Reproduce
1. Go to airbyte_cdk
2. ```mypy airbyte_cdk```

## Are you willing to submit a PR?
Yes

**Comment by maxi297** [comment] 2023-01-31 19:18
Duplicate of https://github.com/airbytehq/airbyte/issues/14907

**Closed by maxi297** 2023-01-31 19:18 UTC
Labels: type/bug, team/extensibility
