### ISSUE TITLE
413 Request Entity Too Large nginx/1.23.2 for Airbyte 0.40.15 & above versions

### ISSUE THREAD

**Issue by CoCoStudyStudy** [airbytehq/airbyte#18822] opened 2022-11-01 22:17 UTC
## Environment
- **Airbyte version**:  0.40.15 & 0.40.17
- **OS Version / Instance**:  macOS, AWS EC2
- **Deployment**: example are Docker deploy env
- **Source Connector and version**: MSSQL 0.4.22
- **Destination Connector and version**: SNOWFLAKE 0.4.38
- **Step where error happened**: Setup new connection 

## Current Behavior
*Tell us what happens.*
We deployed Airbyte OSS on AWS EC2 and Airbyte OSS on macOS and upgraded EC2 instance to 0.40.15 and macOS instance to 0.40.17. After upgrade, both have the error when building the connection. New streams can't be saved when rebuilding the connections.
Error:
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.23.2</center>

## Expected Behavior
The issue didn't occur with the older version. It appeared once we upgraded to the recent version.
We expect the new streams can be saved and the connections can be built.

## Steps to Reproduce
1.Replication Tab Refresh Source Schema
2.Add new stream
3.Save changes
4. Changes can not be saved due to the Error: non-json response, in inspect mode, Error: Status Code: 413 Request Entity Too Large

##Finding
We looked into the proxy server, guess it's caused by the default file size set by nginx server.

**Comment by koconder** [comment] 2022-11-03 08:37
We found the same issue with our nginx, and feel like it can be resolved by increasing `client_max_body_size` in nginx

**Comment by natalyjazzviolin** [comment] 2022-11-03 12:01
@koconder did you apply the fix/did it work for you?

**Comment by koconder** [comment] 2022-11-04 13:45
Also has been mentioned here before https://github.com/airbytehq/airbyte/issues/4086

**Comment by mikemlg** [comment] 2022-11-23 09:51
so when will this issue be resolved. It will happen if you have a source with many tables such salesforce?

**Comment by oleg-savko** [comment] 2022-11-30 15:11
Have the same problem, trying to increase property in the following way but it not help:

```
 docker exec -it airbyte-webapp sh
 / # vi /etc/nginx/conf.d/default.conf
 change:
  client_max_body_size 200M; 
 to:
   client_max_body_size 12000M;  
 nginx -s reload
```

Any news about when or how it can be resolved?

**Comment by mijonmustard** [comment] 2022-11-30 20:38
I note airbyte-webapp has a 100M client_max_body_size so I suspect this is being restricted by the default 1MB limit in airbyte-proxy? My request is 1.45MB.

**Comment by andresbravog** [comment] 2022-12-12 18:58
Working on a PR, the issue is on `airbyte-proxy` as @mijonmustard suggested.

In the meantime you can:

```
docker-compose exec airbyte-proxy bash
> apt-get update
> apt-get install vim
> vim /etc/nginx/templates/nginx-auth.conf.template
# Add client_max_body_size 200M; to all `/`
> vim /etc/nginx/templates/nginx-no-auth.conf.template
# Add client_max_body_size 200M; to all `/`
> exit

docker-compose restart airbyte-proxy
```

**Comment by andresbravog** [comment] 2022-12-12 19:46
PR provided

**Closed** 2022-12-12 22:44 UTC
Labels: type/bug, area/platform, community, team/prod-eng
