### ISSUE TITLE
Source Shopify: Line Item Discount Application

### ISSUE THREAD

**Issue by lluisgassovillarejo** [airbytehq/airbyte#19348] opened 2022-11-11 11:42 UTC
## Environment
- **Airbyte version**:  0.40.18
- **OS Version / Instance**: Debian 11
- **Deployment**: Docker in GCP
- **Source Connector and version**: Shopify 0.2.0
- **Destination Connector and version**: BigQuery Denomralized 1.2.5
- **Step where error happened**: Sync job

## Current Behavior
In the orders stream, each struct in the line_items array has an attribute called discount_allocations, which is always empty.

## Expected Behavior
The attribute should be called discount_applications and contain an array of discounts applied to the line item, as per the [Shopify API documentation](https://shopify.dev/api/admin-rest/2022-10/resources/order).

## Logs
Not relevant

## Steps to Reproduce
Connect a Shopify instance with BigQuery denormalized and run a sync.

## Are you willing to submit a PR?
I can't develop at this point.

Thanks!

**Comment by lluisgassovillarejo** [comment] 2023-01-10 15:57
JFI: We have noticed that discount_allocations are identified in the [orders schema](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-shopify/source_shopify/schemas/orders.json) (line 1887) instead of discount_applications. This may be one of the reasons for the bug.

**Comment by sajarin** [comment] 2023-01-10 16:28
Thanks @lluisgassovillarejo, looks like there might have been a regression with the orders schema. Are you open to trying to push a fix for this?

**Closed** 2023-01-17 16:49 UTC
Labels: type/bug, area/connectors, community, connectors/source/shopify, team/connectors-python
