### ISSUE TITLE
PostgreSQL silent failure bug

### ISSUE THREAD

**Issue by potatozerg** [airbytehq/airbyte#4898] opened 2021-07-21 22:58 UTC
Succeeded
1.13 MB | 1,053 records | 20s | Sync

Part of Log:
2021-07-21 22:54:31 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):220 - Records read: 1000
2021-07-21 22:54:31 ERROR () LineGobbler(voidCall):85 - Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: permission denied for table accounts

I'm trying to figure out what causes it. But it's a silent failure anyway.
[logs-375-0.txt](https://github.com/airbytehq/airbyte/files/6859185/logs-375-0.txt)

**Comment by sherifnada** [comment] 2021-07-21 23:04
@potatozerg can you upgrade to the latest Airbyte version? the silent failure issue has been fixed on it.

**Comment by sherifnada** [comment] 2021-07-21 23:05
Also, it seems like the issue is that the DB user being used for the airbyte sync doesn't have permissions on the `accounts` table. Can you ensure the user has access?

**Comment by potatozerg** [comment] 2021-07-21 23:13
Got it. I saw the issue you referred to, it's a MySQL issue. Thought the fix is only for MySQL. Will try to upgrade, and thanks for the tip!

**Closed** 2021-07-21 23:40 UTC
Labels: type/bug
