### ISSUE TITLE
Display the namespace name in connection settings

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#11873] opened 2022-04-11 05:06 UTC
We should display in the connection settings where the streams in the connection will be replicated to.

Today we show both the source namespace and the destination namespace as columns, but this doesn't help the user understand where the data will actually go, and wouldn't be relevant if the user selected custom format. Instead of showing these two, consolidate to a single column where the value is dependent on what the user has selected above. 

In this example below it should say "github_oncall" for all the streams as it is set to custom format.  
<img width="865" alt="Screen Shot 2022-04-10 at 10 03 10 PM" src="https://user-images.githubusercontent.com/38087517/162668288-bbb986fd-fd67-4b84-a8c0-ef1db836a5bf.png">

**Comment by octavia-squidington-iii** [comment] 2022-04-11 05:07
cc @airbytehq/frontend

**Comment by andyjih** [comment] 2022-09-27 20:24
Closing this one as a duplicate of #10637

**Closed by andyjih** 2022-09-27 20:24 UTC
Labels: area/frontend, project/onboarding-improvements, team/workflow, autoteam, team/frontend, ui/connection
