### ISSUE TITLE
Missing records from 2nd batch on Destination

### ISSUE THREAD

**Issue by erichartono** [airbytehq/airbyte#2599] opened 2021-03-24 04:20 UTC
## Expected Behavior
I synced 7,188 records of data from 2 tables, accounts and brokers. 
Accounts has 7,179 records and I expect to get 7,179 rows in Destination

## Current Behavior
Accounts has 7,179 records, and sync happened in 2 batches. 1st batch has 870, and 2nd batch has 6309.
On destination, I only get 870 records on accounts table. 

## Logs
[logs-47-0.txt](https://github.com/airbytehq/airbyte/files/6194339/logs-47-0.txt)

## Steps to Reproduce
1. Reset Data
2. Sync 

## Severity of the bug for you
Critical

## Airbyte Version
0.17.2

## Connector Version (if applicable)
mssql 0.2.1
redshift 0.2.0

## Additional context
Running on Linux EC2

**Comment by ChristopheDuong** [comment] 2021-03-24 12:11
Related thread on slack interacting with @davinchia (who's reworking the redshift destination too) is available here: https://airbytehq.slack.com/archives/C01MFR03D5W/p1616481563058700

**Comment by cgardens** [comment] 2021-03-24 17:43
Is the data getting into the `*_raw` versions of the tables on that second batch? or it is not getting there either? I am trying to understand a little better where in the process things are going wrong. Knowing if it's getting into the raw table but not the normalized one or if it is not even getting into the raw one will help us diagnose.

**Comment by erichartono** [comment] 2021-03-24 21:47
@cgardens In _airbyte_raw_dbo_accounts table, it has 870 rows as well. Is there a way to check temp table before it gets deleted?

**Comment by cgardens** [comment] 2021-03-24 21:57
Got it! That's helpful. Unfortunately, without modifying the connector directly, there's not a way  to preventing deleting the tmp table. If the sync takes a little time though, you should be able to query it as it is written to. We write to those tmp tables in small batches so you should see records added to it incrementally.

**Comment by erichartono** [comment] 2021-03-24 23:12
I have expanded to sync more tables, and I have 1 table which doesnt sync at all, when it should have synced 7465 rows. 

2021-03-24 23:04:27 INFO (/tmp/workspace/70/0) LineGobbler(voidCall):69 - 2021-03-24 23:04:27 [32mINFO[m i.a.i.d.b.BufferedStreamConsumer(writeStreamsWithNRecords):194 - {} - Writing stream dbo.contracts. Max batch size: 10000, Actual batch size: 7465, Remaining buffered records: 0
2021-03-24 23:04:27 INFO (/tmp/workspace/70/0) LineGobbler(voidCall):69 - 2021-03-24 23:04:27 [32mINFO[m i.a.i.d.r.RedshiftSqlOperations(insertRecords):59 - {} - actual size of batch: 7465

From _airbyte_1616626927521__airbyte_raw_dbo_contracts temp table, it was showing 0 all the time, while other tables have rows. 

Based on this, I think there's something blocking data being pushed to temp raw table.

**Comment by erichartono** [comment] 2021-03-25 22:24
These are logs from manual and automated sync. 

This is from manual and failed, missing 10,000 records in contracts table
[logs-88-0-failed.txt](https://github.com/airbytehq/airbyte/files/6208184/logs-88-0-failed.txt)

This is from automated sync and success, no missing data in contracts table
[logs-89-0-success.txt](https://github.com/airbytehq/airbyte/files/6208185/logs-89-0-success.txt)

**Comment by davinchia** [comment] 2021-03-31 09:30
Update: Eric, shared with me the schema and some prod data in a DM. Attempting to reproduce this.

**Comment by davinchia** [comment] 2021-03-31 10:52
Update: Paired with Eric on this. This problem went away on switching to the new S3 Copy strategy (latest version) on 0.18.2 Core, which reduces the urgency of this ticket. Transfer time also decrease from 50 mins to 1.3 min (Yay!).

@erichartono kindly agreed to perform a test with the older strategy to see if the previous bug still pops up. I'm going to leave this issue open till he gets back to me. If this is still a problem, I will open a separate issue.

**Comment by davinchia** [comment] 2021-04-01 06:21
Strangely enough, everything seems fine. Eric also reported the insert strategy taking much faster when on the latest version. 

Since no other user has reported this. I am going to close this for now.

**Closed by davinchia** 2021-04-01 06:21 UTC
Labels: type/bug

**Comment by Boopathy-Raja** [comment] 2021-10-06 02:04
I think I face a similar kind of issue.
After the first snapshot in the CDC configuration, the new records didn't get loaded.

More Information in https://airbytehq.slack.com/archives/C019WJFR1JT/p1633485557359000

Can you look, whether the issue similar to this?

**Comment by cgardens** [comment] 2021-10-11 22:01
moved this conversation to this issue: https://github.com/airbytehq/airbyte/issues/6942
