### ISSUE TITLE
Paginate the sync history

### ISSUE THREAD

**Issue by roshan** [airbytehq/airbyte#2216] opened 2021-02-25 22:08 UTC
## Tell us about the problem you're trying to solve
I am trying to delete a connection. One of the places I'm going to look is at the bottom of the connection's page. It's not there but eliminating that as an option takes forever since I need to scroll quite a bit to get there when I sync every 10 mins.

## Describe the solution you’d like
Paginate my history or show me the last day's worth (and if none in the last day, then the last 10) and then hide in "Show all..."

## Describe the alternative you’ve considered or used
Hold down my spacebar

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368092210002) by [Unito](https://www.unito.io)

**Comment by timroes** [comment] 2022-06-02 10:14
Duplicate of #11114

**Closed by timroes** 2022-06-02 10:14 UTC
Labels: type/enhancement, team/frontend
