### ISSUE TITLE
Object filtering when creating a salesforce source has confusing UI

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#14417] opened 2022-07-05 15:40 UTC
## Environment
- **Airbyte version**: latest cloud
- **OS Version / Instance**: cloud
- **Deployment**: cloud
- **Source Connector and version**: salesforce `1.0.10`
- **Step where error happened**: Setup new connection

## Current Behavior
- Create a new salesforce connector.
- Add an object filtering criteria:
<img width="688" alt="Screen Shot 2022-07-05 at 08 31 58" src="https://user-images.githubusercontent.com/1933157/177364615-90d80d77-15ab-4815-9782-d727d210edff.png">
- Click "done":
<img width="692" alt="Screen Shot 2022-07-05 at 08 32 05" src="https://user-images.githubusercontent.com/1933157/177364635-91b9127f-22e9-45a2-b9fd-a7ad14d6470f.png">
- The items shows an "0", which is confusing.
- After adding more criteria, it is clear that the numbers are the indices:
<img width="496" alt="Screen Shot 2022-07-05 at 08 38 34" src="https://user-images.githubusercontent.com/1933157/177365579-bfc9f854-14e9-4ab2-a23f-fe236f056704.png">
- But this is still confusing. Users need to click "edit to see the details.

## Expected Behavior
The UI should show the filtering criteria themselves, not just the indices.

## Steps to Reproduce
- Already described above.

**Comment by timroes** [comment] 2022-07-05 15:45
Duplicate of https://github.com/airbytehq/airbyte/issues/10858

**Closed by timroes** 2022-07-05 15:45 UTC
Labels: type/bug, needs-triage, connectors/source/salesforce, team/frontend, ui/connectors
