### ISSUE TITLE
Not able to create source / destination in docker + mac silicon chip

### ISSUE THREAD

**Issue by shubhransh-locale** [airbytehq/airbyte#12233] opened 2022-04-21 07:46 UTC
## Environment
- **Airbyte version**:  0.36.1-alpha
- **OS Version / Instance**: mac 12.3.1 (Silicon chip)
- **Deployment**: Docker
- **Source Connector and version**:  PokeAPI
- **Destination Connector and version**: LocalCSV
- **Severity**: High 
- **Step where error happened**: Deploy

## Current Behavior
*Tell us what happens.*
I am trying airbyte for first time in my local machine with docker,  and trying to setup a sample source and destination. But when I create it, its been running for more than 30 mins and source and destination are not getting created

## Expected Behavior
Source and destination should get connected

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by marcosmarxm** [comment] 2022-06-14 12:43
@shubhransh-locale latest version of Airbyte you should be able to use Airbyte without any problem with Mac Silicon Chip. Give a try. I'll close it because it's a duplicate of https://github.com/airbytehq/airbyte/issues/2017

**Closed by marcosmarxm** 2022-06-14 12:43 UTC
Labels: type/bug, community, needs-triage, team/use, autoteam
