### ISSUE TITLE
New Connector: Zoro CRM

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#7137] opened 2021-10-18 20:10 UTC
## Tell us about the new connector you’d like to have
https://www.zoho.com/crm/developer/docs/api/v2/

## Describe the context around this new connector
* Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?
* If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name? 

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by sherifnada** [comment] 2021-10-19 01:43
duplicate of #4934

**Closed by sherifnada** 2021-10-19 01:43 UTC
Labels: area/connectors, new-connector
