### ISSUE TITLE
🐛 Source Postgres: full refresh error when using UUID typed primary key  

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#8569] opened 2021-12-07 07:27 UTC
## Environment
- **Airbyte version**:  0.32.5-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: Postgres 0.3.14
- **Destination Connector and version**: Redshift 0.3.4
- **Severity**: Medium
- **Step where error happened**: Sync job

**Reported following this [slack thread](https://airbytehq.slack.com/archives/C01MFR03D5W/p1637819815441500) with user Tony Mao and @tuliren** 

## Current Behavior
When syncing a stream with a UUID typed primary key the source fails with
```
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - Exception in thread "main" java.lang.RuntimeException: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: function max(uuid) does not exist
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 -   Hint: No function matches the given name and argument types. You might need to add explicit type casts.
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 -   Where: PL/pgSQL function wywm_main.exec(character varying) line 3 at RETURN QUERY
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.source.relationaldb.AbstractRelationalDbSource.lambda$queryTable$0(AbstractRelationalDbSource.java:64)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.LazyAutoCloseableIterator.computeNext(LazyAutoCloseableIterator.java:37)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.TransformedIterator.hasNext(TransformedIterator.java:42)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.CompositeIterator.computeNext(CompositeIterator.java:63)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.commons.util.DefaultAutoCloseableIterator.computeNext(DefaultAutoCloseableIterator.java:38)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:141)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:136)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:119)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.source.postgres.PostgresSource.main(PostgresSource.java:280)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - Caused by: java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: function max(uuid) does not exist
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 -   Hint: No function matches the given name and argument types. You might need to add explicit type casts.
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 -   Where: PL/pgSQL function wywm_main.exec(character varying) line 3 at RETURN QUERY
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.db.jdbc.StreamingJdbcDatabase.query(StreamingJdbcDatabase.java:104)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.db.jdbc.JdbcDatabase.query(JdbcDatabase.java:126)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.source.relationaldb.AbstractRelationalDbSource.lambda$queryTable$0(AbstractRelationalDbSource.java:61)
[34msource[0m - 2021-12-01 03:40:46 ERROR () LineGobbler(voidCall):82 - 	... 23 more
```

It's not preventing a full refresh to run.
Here's the source table schema:
```
id                        uuid                     default gen_random_uuid() not null
"aptitudeResultSectionId" integer                                            not null
"questionId"              integer                                            not null,
index                     integer                                            not null,
"answerId"                integer,
"isCorrect"               boolean,
theta                     numeric(12, 10),
"submittedAt"             timestamp with time zone,
"createdAt"               timestamp with time zone default CURRENT_TIMESTAMP not null,
"updatedAt"               timestamp with time zone
```

## Expected Behavior
No error should be displayed during full refresh with an UUID primary key.

## Logs
[logs-758-1.txt](https://github.com/airbytehq/airbyte/files/7666317/logs-758-1.txt)

## Steps to
 Reproduce
1. Declare a table with a UUID primary key in Postgres
2. Set up full refresh stream with this table in Airbyte
3. Run the sync

**Comment by etsybaev** [comment] 2021-12-26 12:26
Hi there.
Whatever tried to do, but was not able to reproduce it.

Env:
App v. 0.35.1-alpha, source-postgres conenctor v. 4.0.0.
![Selection_310](https://user-images.githubusercontent.com/4688354/147407932-9da65a7a-9555-46eb-a64f-dce1030494eb.png)



Created table and populated it with dummy data:
![Selection_311](https://user-images.githubusercontent.com/4688354/147407924-20e19b7f-67e7-415e-9438-8c14013378f8.png)

Also created a CSV destination and replicated data with no errors:
![Selection_310](https://user-images.githubusercontent.com/4688354/147407947-2fddface-f9cb-47cc-8335-6e234278cdcb.png)
![Selection_308](https://user-images.githubusercontent.com/4688354/147407951-10311aea-9b0e-4140-b356-55d67b5da740.png)

Result CSV file:
![Selection_309](https://user-images.githubusercontent.com/4688354/147407942-9e196772-6775-419b-ab5b-ec99d7fe9464.png)


Is there anything specific I should know to reproduce it?
Thanks in advance!

**Comment by etsybaev** [comment] 2022-01-05 08:46
Hi there.
Closing this ticket as wasn't able to reproduce it in the latest 4.0.0 version. 
Feel free to re-open in case it still occurs somehow, but please add more details.
Thanks

**Closed by etsybaev** 2022-01-05 08:46 UTC
Labels: type/bug, area/connectors, community
