### ISSUE TITLE
MySQL connection drop when there is a Json column

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#8100] opened 2021-11-18 16:18 UTC
## Enviroment
- OS Version: Mac OS X 11.6
- Memory / Disk: 32 Gb / 1 Tb SSD
- Deployment: Local
- Airbyte Version:v0.32.0-alpha
- Source name/version: Mysql 5.7
- Destination name/version: Snowflake

## Current Behavior

Slack [thread](https://airbytehq.slack.com/archives/C01MFR03D5W/p1637068472116200).

> Hello, we have a strange problem while setting up the MySql to Snowflake connector, it stops working as soon as we try to import a table that contains a json column but the error only says that the connection was terminated without an answer. I wasn’t able to find any reference to this error online.

> it only happens when i pick a table with a json column

## Logs

See this slack [message](https://airbytehq.slack.com/archives/C01MFR03D5W/p1637221060188700?thread_ts=1637068472.116200&cid=C01MFR03D5W).

**Comment by pquadri** [comment] 2022-06-14 08:24
Hello, update: I periodically try again to reproduce the issue to see if it went away. It's still there but maybe there is something more meaningful in the logs

```
airbyte-worker      | 2022-06-14 08:14:08 INFO i.a.w.t.s.ConnectionManagerWorkflowImpl(checkConnections):346 - SOURCE CHECK: Starting
airbyte-worker      | 2022-06-14 08:14:08 INFO i.a.w.t.s.ConnectionManagerWorkflowImpl(checkConnections):353 - SOURCE CHECK: Successful
airbyte-worker      | 2022-06-14 08:14:08 INFO i.a.w.t.s.ConnectionManagerWorkflowImpl(checkConnections):363 - DESTINATION CHECK: Starting
airbyte-worker      | 2022-06-14 08:14:08 INFO i.a.w.t.s.ConnectionManagerWorkflowImpl(checkConnections):370 - DESTINATION CHECK: Successful
airbyte-worker      | 2022-06-14 08:14:08 INFO i.a.w.t.s.ConnectionManagerWorkflowImpl(run):126 - Cancelling the current running job because a connection deletion was requested
airbyte-worker      | 2022-06-14 08:14:08 INFO i.a.w.t.s.ConnectionManagerWorkflowImpl(run):129 - Workflow deletion was requested. Calling deleteConnection activity before terminating the workflow.
airbyte-worker      | 2022-06-14 08:14:08 WARN i.t.i.s.DeterministicRunnerImpl(close):304 - Promise completed with exception and was never accessed. The ignored exception:
airbyte-worker      | io.temporal.failure.CanceledFailure: Canceled by request
airbyte-worker      | 	at java.lang.Thread.getStackTrace(Thread.java:1610) ~[?:?]
airbyte-worker      | 	at io.temporal.internal.sync.CompletablePromiseImpl.throwFailure(CompletablePromiseImpl.java:136) ~[temporal-sdk-1.8.1.jar:?]
airbyte-worker      | 	at io.temporal.internal.sync.CompletablePromiseImpl.getImpl(CompletablePromiseImpl.java:95) ~[temporal-sdk-1.8.1.jar:?]
airbyte-worker      | 	at io.temporal.internal.sync.CompletablePromiseImpl.get(CompletablePromiseImpl.java:74) ~[temporal-sdk-1.8.1.jar:?]
airbyte-worker      | 	at io.temporal.internal.sync.DeterministicRunnerImpl.close(DeterministicRunnerImpl.java:301) ~[temporal-sdk-1.8.1.jar:?]
airbyte-worker      | 	at io.temporal.internal.sync.SyncWorkflow.close(SyncWorkflow.java:173) ~[temporal-sdk-1.8.1.jar:?]
airbyte-worker      | 	at io.temporal.internal.replay.ReplayWorkflowExecutor.close(ReplayWorkflowExecutor.java:144) ~[temporal-sdk-1.8.1.jar:?]
airbyte-worker      | 	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.close(ReplayWorkflowRunTaskHandler.java:232) ~[temporal-sdk-1.8.1.jar:?]
airbyte-worker      | 	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleWorkflowTaskImpl(ReplayWorkflowRunTaskHandler.java:199) ~[temporal-sdk-1.8.1.jar:?]
airbyte-worker      | 	at io.temporal.internal.replay.ReplayWorkflowRunTaskHandler.handleQueryWorkflowTask(ReplayWorkflowRunTaskHandler.java:243) ~[temporal-sdk-1.8.1.jar:?]
airbyte-worker      | 	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTaskWithQuery(ReplayWorkflowTaskHandler.java:117) ~[temporal-sdk-1.8.1.jar:?]
airbyte-worker      | 	at io.temporal.internal.replay.ReplayWorkflowTaskHandler.handleWorkflowTask(ReplayWorkflowTaskHandler.java:97) ~[temporal-sdk-1.8.1.jar:?]
airbyte-worker      | 	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:241) ~[temporal-sdk-1.8.1.jar:?]
airbyte-worker      | 	at io.temporal.internal.worker.WorkflowWorker$TaskHandlerImpl.handle(WorkflowWorker.java:199) ~[temporal-sdk-1.8.1.jar:?]
airbyte-worker      | 	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:93) ~[temporal-sdk-1.8.1.jar:?]
airbyte-worker      | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
airbyte-worker      | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
airbyte-worker      | 	at java.lang.Thread.run(Thread.java:833) [?:?]
airbyte-temporal    | {"level":"info","ts":"2022-06-14T08:14:08.798Z","msg":"query directly through matching on sticky timed out, attempting to query on non-sticky","service":"history","shard-id":3,"address":"172.26.0.8:7234","shard-item":"0xc00003a280","component":"history-engine","wf-namespace":"default","wf-id":"connection_manager_d60b2771-605c-43a8-a238-e2d6e5dab5d8","wf-run-id":"67c7dd4e-724b-4cdd-bfaf-2d7551c41414","wf-query-type":"getState","wf-task-queue-name":"","wf-next-event-id":98,"logging-call-at":"historyEngine.go:923"}
```

**Comment by grishick** [comment] 2022-08-26 23:12
Duplicate of https://github.com/airbytehq/airbyte/issues/14346

**Closed by grishick** 2022-08-26 23:12 UTC
Labels: type/bug, area/connectors, area/databases, connectors/sources-database, connectors/source/mysql, team/databases
