### ISSUE TITLE
Unable to install release 0.50.9 with run-ab-platform.sh

### ISSUE THREAD

**Issue by selfscrum** [airbytehq/airbyte#28567] opened 2023-07-21 14:46 UTC
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.50.9

### What step the error happened?

On deploy

### Revelant information

it ends with an error message that the airbyte/airbyte-api-server:0.50.9 has an unknown manifest.

**Comment by iainad** [comment] 2023-07-21 15:30
I can confirm the same thing attempting to install on Debian/11 on GCP.

If this impacts anyone for now, to allow you to use the previous release until this gets fixed you can download the 0.50.8 version of the `run-ab-platform.sh` or edit the `VERSION` at the top of the downloaded file and then run:

```
./run-ab-platform.sh -r
./run-ab-platform.sh -b
```

This just ensures it clears any downloaded config files and reverts to the old release.

On this bug this is the output I get:

```
[+] Running 11/11
 ✘ airbyte-connector-builder-server Error                                                                 1.0s 
 ✘ webapp Error                                                                                           1.0s 
 ✘ worker Error                                                                                           1.0s 
 ✘ airbyte-cron Error                                                                                     1.0s 
 ✘ airbyte-temporal Error                                                                                 1.0s 
 ✘ airbyte-proxy Error                                                                                    1.0s 
 ✘ server Error                                                                                           1.0s 
 ✘ init Error                                                                                             1.0s 
 ✘ db Error                                                                                               1.0s 
 ✘ airbyte-api-server Error                                                                               1.0s 
 ✘ bootloader Error                                                                                       1.0s 
Error response from daemon: manifest for airbyte/airbyte-api-server:0.50.9 not found: manifest unknown: manifest unknown
```

**Comment by iainad** [comment] 2023-07-21 15:52
OK figured this out - if you are installing on anything but debian buster you need to modify this line in the [install instructions](https://docs.airbyte.com/deploying-airbyte/on-gcp-compute-engine/) to get docker etc to install properly:

```
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"
```
In my case (Debian/11 bullseye):

```
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"
```
After that the install starts up ok.

**Comment by iainad** [comment] 2023-07-21 16:06
Hmmm no I just did all that from scratch again and it didn't work sorry - it doesn't look like that's it!

**Comment by theissn** [comment] 2023-07-21 16:10
Looks like the tag hasn't been built/pushed to docker hub?

https://hub.docker.com/r/airbyte/airbyte-api-server/tags

Latest on above is `0.50.8`

**Comment by cpdeethree** [comment] 2023-07-24 22:06
This image was missing, but we pushed a new tag on Friday. can you please verify that issue is still occurring? https://hub.docker.com/r/airbyte/airbyte-api-server/tags

**Comment by marcosmarxm** [comment] 2023-07-25 19:56
Fixed by https://github.com/airbytehq/airbyte/issues/28629

**Closed by marcosmarxm** 2023-07-25 19:56 UTC
Labels: type/bug, area/platform, community, needs-triage, team/platform-compose, team/platform-move, autoteam
