### ISSUE TITLE
Source Quickbooks: Customers stream not populating any data

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#25928] opened 2023-05-09 18:26 UTC
Observation:  The Oauth connection works and it creates the correct schema and tables in BigQuery, but it doesn't fetch any data for a table verified via Postman, which has data using the credentials provided (Using full refresh/overwrite). Data is verified to be fetched using Postman.

Data emitted by Airbyte contains no data about customers in the customers table. Sync history shows 0 records emitted.

Link to Cloud workspace: https://cloud.airbyte.com/workspaces/16f8a338-a089-44a3-889f-02c0a3c7bdd5/connections

**Comment by nataliekwong** [comment] 2023-05-09 18:32
Reached out to user to confirm if we are able to access his data.

**Comment by nataliekwong** [comment] 2023-05-23 00:30
@davydov-d Do you need any more information from me on this issue? The details are noted here: https://airbytehq-team.slack.com/archives/C02U9R3AF37/p1683581313134559

**Comment by davydov-d** [comment] 2023-05-23 05:09
@nataliekwong so far no more info needed. Sorry for the delay, I've been working on other issues, now looking into this one

**Comment by davydov-d** [comment] 2023-05-23 14:33
@nataliekwong it looks like the user has changed the source connector config yesterday (probably the start date) and the sync started emitting records. This seems to be the only reasonable explanation to what has happened. I tried to reproduce this issue but both full refresh and incremental syncs work fine for me. I'm closing this one as a user config error, please let me know if I am wrong and the original start date was not a couple of days in the past so I would dig into it even more.

**Closed by davydov-d** 2023-05-23 14:33 UTC
Labels: team/connectors-python

**Comment by nataliekwong** [comment] 2023-05-26 21:49
Thanks @davydov-d ! The user confirmed that changing the start date allowed data to sync.

He also shared the feedback that some streams (like customers) should never be limited by date as they are not event based tables. I'll create a separate issue to address that improvement to the connector.

**Comment by davydov-d** [comment] 2023-05-27 05:00
@nataliekwong this is not a quickbooks related problem, it's a more common issue for all the connectors. I believe this should be discussed with the team and if the team decides this is worth implementing - implementation should be done for the CDK
