### ISSUE TITLE
Allow selecting previously unselected streams in a source without requiring a reset of the connection

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#3520] opened 2021-05-21 00:23 UTC
## Tell us about the problem you're trying to solve
When a user selects some streams from a schema, we only retain the streams which they selected in the catalog we store on the backend. For example, if my sql db has tables 1-10 but I initially only replicate table 1 (say to test out airbyte or because I now need to replicate more data) then on the backend we store a catalog which contains only 1 stream corresponding with the selected table. 

If I later want to replicate more streams from my source, I have to refresh the schema. 

This is problematic because refreshing the schema requires resetting the state for that connection, which means we end up re-replicating lots of data. This can be very costly if we're pulling data from a rate limited API or a DB with lots of data. 

## Describe the solution you’d like
There's a few options we can go with: 

1. 20/80 approach: Add a metadata field to each configured stream which denotes whether it was selected or not. This way we can store the full catalog at all times and never need to reset the connection. This seems like the simplest approach with the least amount of effort required. It would however require changes to the CDK and our connectors to make sure they are respecting this flag (today the presence of a stream in the catalog passed to a connector implies that it is selected for syncing). Although we can do this in a backwards compatible way inside the worker until all connectors are migrated to this approach. 
1. Whole hog: refreshing schemas should not require resetting the connection state and re-syncing data -- this should only happen if there was a schema migration like a rename or something. 

## Describe the alternative you’ve considered or used
do nothing about this problem; re-sync data every time you want to update the schema selection.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368195382469) by [Unito](https://www.unito.io)

**Comment by fixico-abdel** [comment] 2021-06-04 12:57
upvote

**Comment by harshithmullapudi** [comment] 2021-06-11 11:56
I didn't dig deep but. We can use the way singer does it have all the fields and use `selected` field to understand which one user selected. I think this can also avoid  having both `source_catalog` and `singer_rendered_catalog.json`.

**Comment by JCWahoo** [comment] 2021-06-14 15:22
upvote as well !

**Comment by tylerdelange** [comment] 2021-06-22 19:44
This functionality is going to be incredibly important to us as we have a single DB with 300 tables we are ingesting. The thought of having to re-import around 1B rows of data every time we have a schema change gives me shivers up my spine.

The ability for a software to be able to handle schema changes is why competitors like FiveTran and Stitch exist. Airbyte needs the ability to handle (automagically) incoming schema changes that occur from the source tables if they are going to want to compete.

**Comment by lypham87** [comment] 2021-06-24 13:49
This function is really needed. Often than not this flexilbility is needed both for governance and optimize resources issues. So many cases need to add or stop a table. We surelly long term cannot create new flow and for every new table.

**Comment by ChristopheDuong** [comment] 2021-07-21 19:06
related to https://github.com/airbytehq/airbyte/issues/4295?

**Comment by kyle-cheung** [comment] 2021-08-17 19:08
would be nice to even be able to select which tables you want to refresh

**Comment by sherifnada** [comment] 2021-08-17 21:02
@kyle-cheung agreed - we'd love to ship this. No firm ETA yet but will probably ship late this quarter (september) or next quarter (oct/nov)

**Comment by bkrausz** [comment] 2021-08-19 18:08
Does anyone have pointers on how to hackily accomplish this today while we wait for feature? It seems like we should be able to get the source schema for the new stream and insert it into the `STANDARD_SYNC` config, but I want to be cautious since an accidental reset would be unpleasant for us.

Similarly, a guide on how to jumpstart incremental syncs would be excellent as it would give confidence in changing configs being safe. For example, I have a backup snapshot of an old sync that took days to run in Snowflake. Being able to tell Airbyte to only sync details after that backup would be immensely helpful.

**Comment by kyle-cheung** [comment] 2021-09-21 19:52
Sorry for the double comment but this has been happening a lot as of the past 2 weeks. We're adding more tables in production and also piping more tables into Snowflake. I'm running into purely human error when reselecting the tables after updating the source streams. A second problem is that I'm using Incremental + Deduped so i actually lose the SCDs when resetting which is totally unnecessary since I only need to bring 1 additional table but am forced to resync the entire db

**Comment by aforlorncat1** [comment] 2021-11-15 08:19
Upvoted. This feature is critical for our use cases.

**Comment by grkhr** [comment] 2021-12-07 08:59
Upvote. We have a large db and resyncing every time a new field is added to a small table is hell.

**Comment by thomasclavet** [comment] 2021-12-15 09:59
Upvote; very interesting feature IMO as well

**Comment by acolyer** [comment] 2022-04-26 08:23
Upvote, this is a major pain for us too.

**Comment by sherifnada** [comment] 2022-04-26 22:15
@acolyer and all --  good news! this is actively in progress and slated for Q2 2022!

**Comment by sherifnada** [comment] 2022-04-27 01:24
@acolyer  and all - good news! This is happening this quarter. Actively being worked on at the moment.

**Comment by kyle-cheung** [comment] 2022-04-27 16:40
@sherifnada this is awesome! Will this feature allow us to reset only a single table? Say if the schema changed for only 1 table. Will there also be anything along the lines of auto schema change detection

**Comment by andyjih** [comment] 2022-05-06 22:03
@kyle-cheung That's correct! If the schema changed only for 1 table, then only that 1 table would be reset.

I've connected this issue to the main Epic where we're tracking all of our work towards this feature, so when that work is done, we'll follow-up here.

Lastly, we **are** planning on supporting auto-schema change detection! It'll be the next project we tackle after this one. I'd love to get your thoughts on what you'd expect with auto-detecting schema changes!

**Comment by Soufraz** [comment] 2022-06-14 15:38
Hi @andyjih. Will it be available for all connectors? Or only for postgres as it was the most reported issues mentioned here?

**Comment by kyle-cheung** [comment] 2022-06-14 16:32
@andyjih that's amazing, super looking forward to this change. For schema resets, I wonder if there's a way for Airbyte to create a temporary table and then swap the new table with the old, so during the *reset* period, there's no lost data or empty table. This generally is an issue whenver I reset my connection now, there's a few hour lull where the database is empty, my work around is to create a separate dev schema and then swap the schemas once the rseet completes

**Comment by validumitru** [comment] 2022-06-15 12:52
Upvote! Major pain point for us also! Each table has 100Gigs and we have hundreds of them

**Comment by cgardens** [comment] 2022-06-29 23:45
duplicate of https://github.com/airbytehq/airbyte/issues/6912. will be released shortly.

**Closed by cgardens** 2022-06-29 23:45 UTC
Labels: type/enhancement, area/platform, team/cloud, team/oss, autoteam
