### ISSUE TITLE
[API] Return type for each field in "get stream properties" `/v1/streams`

### ISSUE THREAD

**Issue by tomlynchRNA** [airbytehq/airbyte#44489] opened 2024-08-21 00:47 UTC
### Topic

add field types to /v1/streams

### Relevant information

The get [stream properties API](https://reference.airbyte.com/reference/getstreamproperties) doesn't return types for each field like the [internal apis discover_schema](https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#post-/v1/sources/discover_schema) call does.
Our use case requires that we know the types for each field and we're stuck still using the deprecated internal API.

**Comment by pmossman** [comment] 2024-08-26 18:44
Closing as duplicate of https://github.com/airbytehq/airbyte/issues/41646

**Closed by pmossman** 2024-08-26 18:44 UTC
Labels: area/api, community, team/compose

**Comment by vrishin-bolt** [comment] 2025-02-17 07:55
I still see the `v1/streams` endpoint not returning the data type
