### ISSUE TITLE
Octavia CLI error: Could not find configuration for STANDARD_SOURCE_DEFINITION

### ISSUE THREAD

**Issue by vyckiuz** [airbytehq/airbyte#28616] opened 2023-07-24 15:32 UTC
### Octavia CLI Version

0.44.4

### Revelant information

Hello,
I have question/problem regarding Octavia CLI. In my airbyte instance I have custom connectors (https://docs.airbyte.com/connector-development/cdk-python/), for those I build Docker images and add it in Settings -> Sources -> New connector. And after that I can add new Source.  
When I’m using **octavia import all** it does export my source configs. Everything works smoothly. 
But, when I try to apply these configs to fresh Airbyte instance I’m getting error: Internal Server Error: Could not find configuration for STANDARD_SOURCE_DEFINITION.
 I believe it’s because this source is not added to Settings -> Sources. How I can solve this? Because if I add it manually it still will have different ID than it’s defined in source configuration file (generated by octavia). 

### Relevant log output

```shell
HTTP response body: {"message":"Internal Server Error: Could not find configuration for STANDARD_SOURCE_DEFINITION: 18ab0164-1999-4334-8834-d4020266d071.","exceptionClassName":"io.airbyte.commons.server.errors.IdNotFoundKnownException","exceptionStack":["io.airbyte.commons.server.errors.IdNotFoundKnownException: Could not find configuration for STANDARD_SOURCE_DEFINITION: 18ab0164-1999-4334-8834-d4020266d071.","\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:30)","\tat io.airbyte.server.apis.SourceApiController.createSource(SourceApiController.java:82)","\tat io.airbyte.server.apis.$SourceApiController$Definition$Exec.dispatch(Unknown Source)","\tat io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)","\tat io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)","\tat io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)","\tat io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)","\tat io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)","\tat io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)","\tat reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)","\tat reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)","\tat reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)","\tat io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)","\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)","\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)","\tat io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)","\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)","\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)","\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)","\tat java.base/java.lang.Thread.run(Thread.java:1589)","Caused by: io.airbyte.config.persistence.ConfigNotFoundException: config type: STANDARD_SOURCE_DEFINITION id: 18ab0164-1999-4334-8834-d4020266d071","\tat io.airbyte.config.persistence.ConfigRepository.lambda$getStandardSourceDefinition$9(ConfigRepository.java:406)","\tat java.base/java.util.Optional.orElseThrow(Optional.java:403)","\tat io.airbyte.config.persistence.ConfigRepository.getStandardSourceDefinition(ConfigRepository.java:406)","\tat io.airbyte.commons.server.handlers.SourceHandler.getSpecFromSourceDefinitionIdForWorkspace(SourceHandler.java:379)","\tat io.airbyte.commons.server.handlers.SourceHandler.createSource(SourceHandler.java:136)","\tat io.airbyte.commons.server.handlers.SourceHandler.createSourceWithOptionalSecret(SourceHandler.java:129)","\tat io.airbyte.server.apis.SourceApiController.lambda$createSource$3(SourceApiController.java:82)","\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:26)","\t... 19 more"],"rootCauseExceptionClassName":"java.lang.Class","rootCauseExceptionStack":["io.airbyte.config.persistence.ConfigNotFoundException: config type: STANDARD_SOURCE_DEFINITION id: 18ab0164-1999-4334-8834-d4020266d071","\tat io.airbyte.config.persistence.ConfigRepository.lambda$getStandardSourceDefinition$9(ConfigRepository.java:406)","\tat java.base/java.util.Optional.orElseThrow(Optional.java:403)","\tat io.airbyte.config.persistence.ConfigRepository.getStandardSourceDefinition(ConfigRepository.java:406)","\tat io.airbyte.commons.server.handlers.SourceHandler.getSpecFromSourceDefinitionIdForWorkspace(SourceHandler.java:379)","\tat io.airbyte.commons.server.handlers.SourceHandler.createSource(SourceHandler.java:136)","\tat io.airbyte.commons.server.handlers.SourceHandler.createSourceWithOptionalSecret(SourceHandler.java:129)","\tat io.airbyte.server.apis.SourceApiController.lambda$createSource$3(SourceApiController.java:82)","\tat io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:26)","\tat io.airbyte.server.apis.SourceApiController.createSource(SourceApiController.java:82)","\tat io.airbyte.server.apis.$SourceApiController$Definition$Exec.dispatch(Unknown Source)","\tat io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371)","\tat io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594)","\tat io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303)","\tat io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111)","\tat io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103)","\tat io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659)","\tat reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49)","\tat reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)","\tat reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)","\tat io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62)","\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)","\tat reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)","\tat io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53)","\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)","\tat java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)","\tat java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)","\tat java.base/java.lang.Thread.run(Thread.java:1589)"]}
```

**Comment by marcosmarxm** [comment] 2023-07-24 18:04
Close as duplicate of https://github.com/airbytehq/airbyte/discussions/28615

**Closed by marcosmarxm** 2023-07-24 18:04 UTC
Labels: type/bug, community, needs-triage, area/octavia-cli, autoteam, team/use
