### ISSUE TITLE
clean up ec2 runners

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#5353] opened 2021-08-11 18:56 UTC
There are a few EC2 action runners that look like they're pretty old.

I imagine this is because of cases where we have the cleanup mechanism fail. Ideally we'd have an action/cron that just deletes instances that are older than a certain amount of time (like 3hr). For this we may need a way of identifying action runners vs other instances running in that AWS project.

*Why?*
Saves us $$.

**Comment by jrhizor** [comment] 2021-08-11 18:58
@davinchia For now, is it safe to delete any `c5.2xlarge` older than a day in `us-east2` on the `dev` project? I see you have a few things running there manually that are other instance types.

**Comment by davinchia** [comment] 2021-08-12 02:21
yes

**Comment by jrhizor** [comment] 2021-08-13 01:03
Alright. I just terminated 17 old instances:
```
i-0b63f835a4ed0c570, i-05d0ae4b64bdbd4de, i-04e280c0af69c08d8, i-08286ab8e36c36e31, i-00c855dfc0c2ca32c, i-01c22fd6931e2074b, i-0b797ec8c21be3f68, i-0ea4cb07944624bbe, i-0a18ffd4f6b143a79, i-0e0e5e2017bdccdf5, i-0a2a2f5aeda82c4e8, i-0c2e5a3c7709d81fa, i-07d2901599365f513, i-0d6ac2483650be725, i-01ed30813ee2b3898, i-0ec286e479b3c6f92, i-0b2b2aa6ae291dc43
```

**Comment by davinchia** [comment] 2021-08-13 02:31
thanks

**Comment by davinchia** [comment] 2022-03-15 11:08
This is duplicate of #10824 and has been implemented.

**Closed by davinchia** 2022-03-15 11:08 UTC
Labels: type/bug, needs-triage
