### ISSUE TITLE
Sync job does not finish - Mysql to S3

### ISSUE THREAD

**Issue by jefersonmsantos** [airbytehq/airbyte#7641] opened 2021-11-04 17:05 UTC
## Enviroment
- **Airbyte version**:  example is 0.30.20-alpha
- **OS Version / Instance**: GKE optimized
- **Deployment**: Kubernetes
- **Source Connector and version**: source.-mysql / 0.4.8
- **Destination Connector and version**:destinatio-s3 / 0.1.12
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
Executing mysql connector to S3 destination. After read all records, it looks like something gets hanged and the job does not finish.

## Expected Behavior
Finish sync job and store parameters for next sync (CDC).

## Logs
[logs-112-0 (1).txt](https://github.com/airbytehq/airbyte/files/7476716/logs-112-0.1.txt)

<details>
<summary>LOG</summary> 

```

</details>

## Steps to Reproduce
1. Create source from mysql
2. Create destination s3
3. Run sync

**Comment by sherifnada** [comment] 2021-11-29 06:57
cc @tuliren added to the database project

**Comment by grishick** [comment] 2022-08-03 22:05
@jefersonmsantos we have made many improvements to MySQL source connector in the year since this issue was filed. Is it still happening?

**Comment by jefersonmsantos** [comment] 2022-08-03 23:54
@grishick , sorry, stopped using airbyte due to this and other errors. I do not know if it would be solved.

**Comment by grishick** [comment] 2022-09-27 18:52
Closing this as unreproducible.

**Closed by grishick** 2022-09-27 18:52 UTC
Labels: type/bug, area/connectors, community, area/databases, connectors/sources-database, connectors/destination/s3, connectors/source/mysql, team/databases, team/db-dw-sources
