### ISSUE TITLE
[destination-Google Cloud Storage (GCS)]  Sync failing

### ISSUE THREAD

**Issue by slawekgarcarz** [airbytehq/airbyte#40658] opened 2024-07-01 16:35 UTC
### Connector Name

Google Cloud Storage (GCS)

### Connector Version

0.4.6

### What step the error happened?

During the sync

### Relevant information

My connection [source-notion] -> [destination-Google Cloud Storage (GCS)] started failing on 27.06.2024 and it's not working since then. Every time failing with the same error (logs available below). I think it's the same problem as https://github.com/airbytehq/airbyte/issues/40620.

I've already tried:

- resetting the connection
- setting up new destination with the new GCS credentials and new bucket

I'm using Airbyte Cloud.

### Relevant log output

```shell
2024-07-01 16:03:34 ERROR i.a.c.Application(run):80 - Killing orchestrator because of an Exception
com.networknt.schema.JsonSchemaException: java.lang.UnsupportedOperationException: No suitable validator for id
        at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:508) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:62) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.read(JsonSchema.java:467) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:1085) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:150) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.from(JsonSchema.java:66) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.doCreate(JsonSchemaFactory.java:313) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.create(JsonSchemaFactory.java:309) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidationContext.newSchema(ValidationContext.java:57) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.PropertiesValidator.<init>(PropertiesValidator.java:52) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:163) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:496) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:62) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.read(JsonSchema.java:467) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:1085) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:150) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.from(JsonSchema.java:66) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.doCreate(JsonSchemaFactory.java:313) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.create(JsonSchemaFactory.java:309) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidationContext.newSchema(ValidationContext.java:57) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.PropertiesValidator.<init>(PropertiesValidator.java:52) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:163) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:496) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:62) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.read(JsonSchema.java:467) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:1085) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:150) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.from(JsonSchema.java:66) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.doCreate(JsonSchemaFactory.java:313) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.create(JsonSchemaFactory.java:309) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidationContext.newSchema(ValidationContext.java:57) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.PropertiesValidator.<init>(PropertiesValidator.java:52) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:163) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:496) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:62) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.read(JsonSchema.java:467) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:1085) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.<init>(JsonSchema.java:150) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchema.from(JsonSchema.java:66) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.doCreate(JsonSchemaFactory.java:313) ~[json-schema-validator-1.4.0.jar:?]
        at com.networknt.schema.JsonSchemaFactory.create(JsonSchemaFactory.java:309) ~[json-schema-validator-1.4.0.jar:?]
        at io.airbyte.validation.json.JsonSchemaValidator.getSchemaValidator(JsonSchemaValidator.java:220) ~[io.airbyte-airbyte-json-validation-dev.jar:?]
        at io.airbyte.validation.json.JsonSchemaValidator.initializeSchemaValidator(JsonSchemaValidator.java:81) ~[io.airbyte-airbyte-json-validation-dev.jar:?]
        at io.airbyte.workers.RecordSchemaValidator.<init>(RecordSchemaValidator.java:64) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at io.airbyte.workers.RecordSchemaValidator.<init>(RecordSchemaValidator.java:46) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at io.airbyte.workers.RecordSchemaValidator.<init>(RecordSchemaValidator.java:41) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at io.airbyte.workers.general.ReplicationWorkerFactory.createRecordSchemaValidator(ReplicationWorkerFactory.java:288) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at io.airbyte.workers.general.ReplicationWorkerFactory.create(ReplicationWorkerFactory.java:150) ~[io.airbyte-airbyte-commons-worker-dev.jar:?]
        at io.airbyte.container_orchestrator.orchestrator.ReplicationJobOrchestrator.runJob(ReplicationJobOrchestrator.java:118) ~[io.airbyte-airbyte-container-orchestrator-dev.jar:?]
        at io.airbyte.container_orchestrator.Application.run(Application.java:78) [io.airbyte-airbyte-container-orchestrator-dev.jar:?]
        at io.airbyte.container_orchestrator.Application.main(Application.java:38) [io.airbyte-airbyte-container-orchestrator-dev.jar:?]
Caused by: java.lang.UnsupportedOperationException: No suitable validator for id
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by stuartjohnpage** [comment] 2024-07-01 18:46
I can confirm, it seems that none of my Notion syncs have been working since 06/25. I'd assume this is connected to when the latest PR was merged. Perhaps bumping the docker version caused this...?

**Comment by marcosmarxm** [comment] 2024-07-03 16:49
Hello this was fixed in the [Airbyte platform](https://github.com/airbytehq/airbyte-platform/commit/3e123edaa2a7feb7240ac469db84dc82520804c1). Please upgrade to the latest version and let me know if it is fixed.

**Closed** 2024-07-03 16:49 UTC
Labels: type/bug, community
