### ISSUE TITLE
Google Sheets Incremental Sync

### ISSUE THREAD

**Issue by leiii** [airbytehq/airbyte#9432] opened 2022-01-12 10:33 UTC
Hi, we would like to use Airbyte to sync data from Google Sheets, where our daily data collection/operation runs on. However, according to the doc (https://docs.airbyte.com/integrations/sources/google-sheets), currently, Airbyte cannot do incremental sync from Google Sheets. Also from the doc, it said this feature will come soon. We would like to know the roadmap of this feature.

**Comment by fabform** [comment] 2022-01-13 12:51
Handy to [find google sheet id](https://fabform.io/a/how-to-find-google-sheet-id)

**Comment by alafanechere** [comment] 2022-01-13 19:00
Hi @leiii , I close this issue as this a duplicate of this one https://github.com/airbytehq/airbyte/issues/3936

**Closed by alafanechere** 2022-01-13 19:00 UTC
Labels: type/enhancement, community, needs-triage
