### ISSUE TITLE
Gradle build's ability to find python is clumsy and requires workarounds

### ISSUE THREAD

**Issue by airbyte-jenny** [airbytehq/airbyte#4007] opened 2021-06-09 21:35 UTC
## Expected Behavior
Gradle's checkPython process should find the python in the user's PATH and, if it's a reasonable version, use it.  If it cannot trust the user's PATH and must use an isolated search process for finding python, it should tell the user where it's looking, what it did or didn't find (in a clear message), and make it clear how the user can change their configuration to use a different python.  All portions of the build should consistently use the same python.  There should be no surprises in how python is found and used.

## Current Behavior
Under various conditions on mac osx, the gradle build checkPython step fails to find pythons that are in the PATH, requiring a custom override to pythonPath='mypath' and possibly also pythonBinary='python', to build at all, and also shows some behaviors that suggest portions of the build are using a different config than others when finding python.

## Logs
*If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window.*

Testing all the nuances of this resulted in more logs than I attempted to keep track of.  The most relevant bit was simply that checkPython test failed, and using --stacktrace with it showed a FileNotFoundException where it was looking for python or python3 in a virtual environment directory.

## Steps to Reproduce

As this issue describes a whole set of scenarios that were attempted, most of which failed for various reasons, the exact steps vary a bit.  

In general, start with a clean (empty) brew install on mac osx mojave, and anaconda python in a user-homedir installation, with ~/anaconda3/bin/ in the PATH.  

Using "brew install python" will trigger 3.9 which breaks the build with a virtualenv hard crash.  

Using "brew install python@3.7" will produce a directory that must be custom added to the PATH, exhibiting the same problem as the conda scenario (python not found in PATH despite being valid).  Using pyenv with python 3.7.9 works partially when pythonBinary is updated, but requires changing the pythonPath as well in order to work fully.  Exact details are in the Additional Context section below.

This is almost certainly mac specific and related to how various python versions are located and managed on mac.

## Severity of the bug for you
Low - can hack around it by hardcoding the pythonPath, and hope the local change doesn't accidentally get checked in to git. The main impact is poor new-user experience.

## Airbyte Version
0.24.7-alpha

## Connector Version (if applicable)
-na-

## Additional context

Summary

The Airbyte gradle plugin that locates and version-checks python is poorly behaved with respect to the surrounding user shell environment, resulting in a variety of closely related problems finding and using python.  Adjustments to the airbyte-python.gradle project.python {} section can alter the behavior and provide workarounds, but it’s still a bad user experience and opaque to troubleshoot.

Possible Goals

The build system should either do the intuitively obvious thing of accepting any appropriate-version python found in the user’s PATH, or it should make its actual search logic transparent, consistent, and open to adjustment by the user (possibly via environment variables, so the user doesn’t have to modify the code repository), with clearly visible suggestions for next steps when failures occur.    If it’s possible to simplify how the build references python to make that more consistent, that may also help.    Additionally, some testing with a range of newer python versions could also be useful; 3.7.9 is not the newest, and 3.9 seems to introduce a breaking bug in virtualenv.  It would be helpful to have automated tests verifying that builds work across a known-good range of python versions, as new versions of python come out, so we aren’t surprised by externally introduced failures.

Technical Deep Dive

Scenario: Mac OSX Mojave 10.14.6, system python of 2.7, brew pythons of (3.7, 3.8, 3.9 variously installed and uninstalled in various combinations), anaconda python 3.8 in a user home dir, and eventually pyenv pythons of 3.7 and 3.8, tried in varying combinations.  This was the first time the user (airbyte-jenny) had pulled the git repo and attempted to build it from scratch.  User PATH was short and sane, with conda python in it, and then later, pyenv given precedence at the very beginning of the path.  Nearly all of the testing below was done with pyenv's python shim dir listed first in the path, and pyenv init configured per its usual instructions.

What finally did work: 

Brew install pyenv, pyenv install 3.7.9, pyenv global 3.7.9 (global might be optional)  AND modify airbyte-python.gradle:19 to pythonPath =  '/Users/jennybrown/.pyenv/shims' AND pythonBinary=‘python’ (not python3 or blank).  This leaves a wart of a user having to put their own custom path into a shared code repo, which is unintuitive, risky if they commit code with it, and interferes with simple 'git pull' updates.

What didn’t work:

Without pyenv, the system python 2.7 was being found by default, and obviously isn’t new enough.

Conda python was not found at all despite being first in the PATH of the shell launching the gradle build.  The user’s PATH seems to be completely ignored.  Thus gradle ignored a probably-acceptable condo python that ought to be supported, as it’s used heavily by data science and machine learning teams.

Running ‘brew install python’ gives the currently-newest version, which is 3.9.  That crashed with a virtualenv bug that claimed to be a true bug in virtualenv and asked to be reported, and which completely crashed the build hard.  This made the default path location for a brew python/python3 to be a non-starter.  Sidenote, this probably needs to be fixed in virtualenv before 3.9 will be suitable for use by airbyte.

Running ‘brew install python@3.7’ produces a nonstandard install path on the system (one with /python@3.7/ in the folder path).  Because the build was already ignoring condo python found in the PATH, it didn’t make sense to adjust the user’s PATH variable to find the specially located brew python, either, as it also wouldn’t be found.

After condo and brew were eliminated as options for python installs, pyenv was attempted next.  Using an incorrect pyenv version resulted in some noise in .venv/ folders within the airbyte repo, which made for inconsistent builds on reruns after installing a different pyenv python version.  Shrif added a cleanVenv target to clean those up.  

Once I had a stable pyenv 3.7.9 installation and a clean directory, but had not yet put pythonPath into the options, the gradle plugin for checkPython still only found python part of the time.  It would get past a first checkpoint successfully by using pythonBinary=‘python’ (instead of blank or python3) but then in a later stage, it escaped the pyenv directory-specific version sandbox and stumbled into the system python instead, then complained that it was too old.  Even setting pyenv global 3.7.9 wasn’t enough to fix that.  The only fix that solved it, and make checkPython consistently succeed, was to set a hardcoded, absolute pythonPath.  That some portion of the build escaped the sandbox at all implies it's starting a subshell without inheriting environment variables from the parent shell, which implies that any environment-variable solution (like PATH or some of the pyenv setup) might be insufficient on its own; that portion of the build (which I think was airbyte-cdk?) should be checked to make sure it's maintaining env vars in subshells and child builds.

Additionally, when checkPython fails to find any version of python in its search locations, it gives a blank error message instead of a FileNotFoundException or some user-friendly error.  It just says that checkPython failed, but doesn’t explain that it was a command not found unless you run with --stacktrace enabled.  This could also be made more user-friendly.

Ideally, dependencies like python should be checked before the main build even starts, and if the precheck passes, the entire build should succeed without dependency-related issues.  It shouldn't be possible to have checkPython pass in one area of the code and fail in another, as was observed when pythonPath wasn't set.

It is also unclear why pythonBinary='python3' was failing to detect python from a valid pyenv configuration, as python3 was clearly available in the shim directory right alongside python, and both were valid and pointed to python 3.7.9 as shown by --version run by the user.  That should have been a valid configuration, but it also gave a command-not-found type of error during gradle build.

**Comment by airbyte-jenny** [comment] 2021-06-22 22:36
Further follow-up on this.  When I got a new mac with Big Sur, this workaround was no longer necessary.  I don't know the exact scenario that caused it to be needed on Mojave.  A potential workaround might simply be upgrading, but not sure.

**Comment by davinchia** [comment] 2022-05-17 10:59
duplicate of https://github.com/airbytehq/airbyte/issues/3970

**Closed by davinchia** 2022-05-17 10:59 UTC
Labels: type/bug, build, team/infra
