### ISSUE TITLE
Ability to not reset data when schema changes

### ISSUE THREAD

**Issue by m-ronchi** [airbytehq/airbyte#6089] opened 2021-09-15 14:33 UTC
## Tell us about the problem you're trying to solve
I upgraded facebook marketing to 0.2.17, that triggered a schema change and forced me to reset all data, which is causing a full refresh sync that takes hours to complete because api limit is hit.
I know that (at least for redshift destination) data is first stored in json blob, then normalized (and normalization is not incremental)

## Describe the solution you’d like
it would be nice to not be forced to reset data when schema or settings are changed.
either detect that destination is resilient to such changes (e.g. for all destinations that store data as json blobs) or make it optional in the UI (with a "I know what I am doing" warning)

**Comment by ChristopheDuong** [comment] 2021-11-10 10:07
This can be seen as an extension of https://github.com/airbytehq/airbyte/issues/3520

**Comment by misteryeo** [comment] 2022-01-06 05:04
Removing tags as this is not a Facebook Marketing specific issue.

**Comment by Gunnnn** [comment] 2022-05-05 07:12
It is vital to the Product! This feature is everyday need when loading data.

**Comment by andyjih** [comment] 2022-05-06 21:58
Hi @Gunnnn! I've connected this issue to #6912 that we're tackling this quarter. We'll follow-up on this issue when it's done. :)

**Comment by cgardens** [comment] 2022-06-29 23:59
duplicate of https://github.com/airbytehq/airbyte/issues/6912. will be released soon.

**Closed by cgardens** 2022-06-29 23:59 UTC
Labels: type/enhancement, team/oss
