### ISSUE TITLE
🐛 Bug: Manual Per-Stream Resets are not working

### ISSUE THREAD

**Issue by alex-gron** [airbytehq/airbyte#27040] opened 2023-06-05 21:05 UTC
I am using a Salesforce connection to BigQuery on Airbyte Cloud

When I manually trigger the reset from the Status page

- The raw table salesforce.airbyte_raw_Opportunity still has records in it
  - This is surprising to me. Is this a bug? 
- The state for Opportunity is still set in the Airbyte Cloud UI

When I trigger the reset modal by turning off the stream on the Replication tab:

- I still have raw data in salesforce.airbyte_raw_Opportunity
  - This is surprising to me. Is this a bug? 
- I no longer have a state for Opportunity
  - This is expected ✅

**Comment by gosusnp** [comment] 2023-09-05 18:02
> When I trigger the reset modal by turning off the stream on the Replication tab:
>
> * I still have raw data in salesforce.airbyte_raw_Opportunity
>   * This is surprising to me. Is this a bug?

I believe this was a choice to not delete data when disabling a stream. It left the user an option to keep the data while no longer syncing.

**Comment by AnilEMaharjan** [comment] 2023-09-05 18:59
Part of the issue that I am running into is that I need to actually reset this Stream and get a full resync and when I click the Reset Stream there are 0 records processed

**Comment by AnilEMaharjan** [comment] 2023-09-05 19:00
> Still seeing this issue in [this job](https://cloud.airbyte.com/workspaces/bed3b473-1518-4461-a37f-730ea3d3a848/connections/c517d9b2-2c78-4f6d-8a52-230db1ed431c/job-history#4460192::0)

When I ran the above reset job, I got the following outcome: 
<img width="738" alt="image" src="https://github.com/airbytehq/airbyte/assets/126518506/09465049-4f01-4214-87ab-475d73db6408">

**Comment by davinchia** [comment] 2023-10-08 22:09
Sorry for the slow reply - Move is finally back on Platform work in Q4 so we can take a closer look here.

Reading through the thread, 
- there is an open question on the raw tables being present. That's destination behaviour I believe is correct. @evantahler can you confirm?
- the platform error seems to be that the per stream reset leaves the final table in the destination while the reset modal does not. Is that right?

**Comment by alex-gron** [comment] 2023-10-09 17:27
@davinchia  There is an internal thread in #dev-platform-compose where @malikdiarra  and @nataliekwong  are discussing, and have the latest information on when this does/doesn't work. I'll tag you in it.

**Comment by davinchia** [comment] 2023-10-16 22:53
Relevant thread: https://airbytehq-team.slack.com/archives/C03A8CSANPQ/p1696872453718639?thread_ts=1696007933.907689&cid=C03A8CSANPQ

**Comment by davinchia** [comment] 2023-10-27 05:22
Update: this turned out to be a destination issue. See https://airbytehq-team.slack.com/archives/C03C4AVJWG4/p1697823971406669

**Comment by nataliekwong** [comment] 2023-10-29 05:18
It looks like the destination bug is now resolved. However, I tested this again with this [connection](https://cloud.airbyte.com/workspaces/56812376-bba8-4eb6-a6a1-df64ea889a5d/connections/9dac07ce-1e05-40ab-91b9-ecc5aacd5890/status) and saw that the state was not cleared and the tables persisted after the reset succeeded. Here's the Loom (no audio) https://www.loom.com/share/08e91d5ac64d497e9b0a83130ab5b5db?sid=e388ce59-fd9b-4ce7-a47e-d03d72fdb5bc

Steps to reproduce: 
- Query BigQuery table to show it exists with records (I'm using checkout_sessions_line_items in this example)
- Verify the state of the stream contains the cursor
- Reset the stream in the UI
- Wait for the reset to succeed (sorry, this takes up most of the video time)

Observed behavior:
- Query of the BigQuery table still shows it exists with the same number of records
- The state of the stream still contains the same cursor
- Subsequent syncs continue to sync incrementally (as we would expect, given the cursor didn't change).

**Comment by davinchia** [comment] 2023-10-30 15:39
fyi: @jdpgrailsdev

**Comment by jdpgrailsdev** [comment] 2023-10-30 19:38
@davinchia @nataliekwong Has the customer given us permission to run the reset?  I would like to run one to see exactly what happens in the logs, as the most recent reset on that connection shows that a sync was executed.  That would explain why the state appears to not have been reset.  I do not see any reference in the logs to the empty source, which we should see if it actually ran the reset.  Instead, it looks like we are just running a sync.

**Comment by nataliekwong** [comment] 2023-10-30 19:48
@jdpgrailsdev I think if you're referring to this one, free to do anything on this workspace! https://cloud.airbyte.com/workspaces/56812376-bba8-4eb6-a6a1-df64ea889a5d/connections (it's an internal one).

There's an external customer (Preply) who has not given us permission yet, but I can ask if you were referencing that one.

**Comment by jdpgrailsdev** [comment] 2023-10-30 20:10
> https://cloud.airbyte.com/workspaces/56812376-bba8-4eb6-a6a1-df64ea889a5d/connections

@nataliekwong I was specifically talking about the one in your Loom recording, which I now realize is in our internal space.  Thanks!

**Comment by jdpgrailsdev** [comment] 2023-10-31 18:17
@davinchia @nataliekwong Something appears to be broken with resets.  I did a local test using the same source configuration from @nataliekwong 's internal example above (Stripe source) sending to the /dev/null source.  I can see the reset API being called and the code identifying the streams to reset.  However, the worker never runs the reset.  It runs a check, followed by a real replication, which is why the state never appears to be reset.  My suspicion is something got removed/changed in the Temporal workflow code.  I don't see how this is isolated to just our internal workspace or these sources/destinations, so I suspect this is a much broader issue.  I am going to add some more debugging locally to see if I can determine what is actually happening.

**Comment by nataliekwong** [comment] 2023-10-31 18:46
Thanks @jdpgrailsdev!! And just as an FYI: we're working on backfilling streams on the Compose side as a new feature this cycle. The backfill is done by doing a per-stream reset. We were doing testing, and found similarly that Postgres succeeded with the per-stream reset, whereas Hubspot kept failing. We were a bit puzzled as to why, and finally connected this morning that it likely is dependent on the same issue we see here. We're going to wait until we resolve this issue before we pick that project back up. 

cc @flutra-osmani

**Comment by jdpgrailsdev** [comment] 2023-10-31 18:54
@nataliekwong That would confirm my suspicion that it is related to the backfill logic added to the `ReplicationActivityImpl`, which is the bit in the sync workflow that actually kicks off the orchestrator.

**Comment by jdpgrailsdev** [comment] 2023-10-31 20:09
Update:  after testing both in the internal workspace and locally using the same source connector and configuration, I can confirm that the rest is happening.  The reset removes the stream from the state table.  However, the UI does not show the updated state unless you refresh the connection page.  At that point, the UI displays an error message stating that the state JSON is invalid (because it is null/not present).  The UI should probably be modified to handle the "no state" case better and/or note that you may need to refresh the page to see the most recent state after a reset or sync.

**Comment by jdpgrailsdev** [comment] 2023-11-02 14:59
Another update:  I believe that I have tracked this down.  There is a feature flag in the `ReplicationActivityImpl` chooses between calling the `replicate` and `replicateV2` method.  Only the `replicateV2` method updates the configured catalog to have the correct `destinationSyncMode` in the configured catalog used by the destination as part of the reset.  For whatever reason, a full reset appears to have the correct `destinationSyncMode` despite not being modified by the `ReplicationActivityImpl`.  The "Reset this stream" option does not, which is why the staging table in the BigQuery destination does not get cleared out.  I cannot tell if this has always existed or whatever introduced the `replicateV2` caused this (or something else).  In any event, there appears to be a lot of variance between where and how the configured catalog is modified (or not modified) as part of a reset.  The feature flag in question is `platform.remove-large-sync-inputs` and checks on the workspace ID for inclusion (it's actual an inverted check, so if off it uses replicate, if on, it uses replicateV2).  Git blame seems to indicate a change made by 
[@Michael Siega](https://airbytehq-team.slack.com/team/U03N969EM25)
 [back in September](https://github.com/airbytehq/airbyte-platform-internal/pull/8795), but again, I am unable to determine if this is when this started or if it pre-existed.  The fact that the full reset works even though it also goes through the `replicate` method that does not modified the configured catalog seems to indicate a bigger, pre-existing issue.

**Comment by alex-gron** [comment] 2023-11-02 19:03
@jdpgrailsdev I created this original issue in June, so I agree that it doesn't seem like this is new behavior.

**Comment by flutra-osmani** [comment] 2023-11-02 19:30
@jdpgrailsdev "replicatev2" path is not yet enabled. I just enabled it for 1% now. It was also enabled for 2 workspaces Natalie was testing on the last couple of days. This new path is tied to the "large sync input" flag. What it does is fetch the catalog and state when needed, instead of relying on the sync input from the upstream workflow.

**Comment by jdpgrailsdev** [comment] 2023-11-02 19:51
After a lot of additional digging, I have found the bug.  The UI sets the `namespace` on the individual stream to reset to a blank string when the namespace of the stream is `null`:

```
        "resetConfig": {
            "streamsToReset": [
                {
                    "name": "checkout_sessions",
                    "namespace": ""
                }
            ]
        }
```
When the configured catalog is loaded by the backend, missing `namespaces` appear as Java `null` objects, not empty strings.  The code that updates the configured catalog to prepare it for reset uses Java equality on the `StreamDescriptor` representation of the stream:

```java
    public boolean equals(Object other) {
        if (other == this) {
            return true;
        } else if (!(other instanceof StreamDescriptor)) {
            return false;
        } else {
            StreamDescriptor rhs = (StreamDescriptor)other;
            return (this.name == rhs.name || this.name != null && this.name.equals(rhs.name)) && (this.namespace == rhs.namespace || this.namespace != null && this.namespace.equals(rhs.namespace)) && (this.additionalProperties == rhs.additionalProperties || this.additionalProperties != null && this.additionalProperties.equals(rhs.additionalProperties));
        }
    }
```
Because the UI passes in an empty string, the equality check fails (`null` != ""), and therefore the catalog is not updated to have the correct `destinationSyncMode`.  Streams that have a non-null/non-blank namespace would not have this problem.  Full resets do not have this problem because all streams are fetched on the backend when the reset request is made, therefore having the correct namespace for the Java equality check.

**Comment by jdpgrailsdev** [comment] 2023-11-02 20:43
After discussing this with @chandlerprall, the approach will be to mark the namespace as optional in the [`ConnectionStream` domain object in the API spec](https://github.com/airbytehq/airbyte-platform-internal/blob/0730411aa84c195d5d98fe502837fff031b48e5b/oss/airbyte-api/src/main/openapi/config.yaml#L5572) and stop passing the `namespace` parameter from the UI if it is blank.

**Comment by chandlerprall** [comment] 2023-11-03 14:13
PR resolving the stream namespace issue has been merged. I'm leaving this issue open until it can be confirmed as fixed.

**Comment by nataliekwong** [comment] 2023-11-03 16:36
I've tested and verified with two API connections, and this WORKS! 🙌 🙌 

What I saw:
- Raw tables were cleared to 0 records
- Final tables were cleared to 0 records
- State removed those streams completely
- Subsequent backfill created all records again in that stream

**Comment by jdpgrailsdev** [comment] 2023-11-06 16:10
@nataliekwong May I close this ticket now that we have confirmed the fix?

**Comment by nataliekwong** [comment] 2023-11-06 17:19
Yes! Please go ahead.

**Closed** 2023-11-07 02:37 UTC
Labels: team/platform-move, platform-move/requires-grooming

**Comment by Ishankoradia** [comment] 2024-08-26 09:57
Hi @jdpgrailsdev @chandlerprall i am facing this issue in my oss version `0.50.44`. Is this suppose to be fixed ? Can you please let me know if i should be upgrading the version?
