### ISSUE TITLE
Source Trello: connector inconsistent run

### ISSUE THREAD

**Issue by StuartMiddleton** [airbytehq/airbyte#15449] opened 2022-08-09 13:58 UTC
## Environment
- **Airbyte version**:  0.39.42-alpha
- **OS Version / Instance**: Linux (ubuntu 20.04)
- **Deployment**: Docker
- **Source Connector and version**: Trello 0.1.6
- **Destination Connector and version**: Snowflake 0.4.34
- **Step where error happened**: Sync job

## Current Behavior
Inconsistent behaviour with each run. May succeed or fail with no obvious reason.

## Expected Behavior
Consistent running.

## Logs
[logs-1038.txt](https://github.com/airbytehq/airbyte/files/9291366/logs-1038.txt)

## Steps to Reproduce
1. Set up a simple extract on restricted boards.
2. Initiate sync.
3. Watch fail or success.

## Are you willing to submit a PR?
Unlikely to be much use I'm afraid.

**Comment by sajarin** [comment] 2022-08-09 15:55
@StuartMiddleton would it be possible to be more specific? What do you mean by inconsistent runs? What differences have you noticed between different sync attempts?

**Comment by StuartMiddleton** [comment] 2022-08-09 16:34
@sajarin not a lot really. Here's the sequence of events:
* The connection was working, I changed the output tables, and then it didn't.
* I returned the output tables back to what they were and it failed again.
* I created a new connection with the same details. It failed twice and then ran successfully on the third attempt (i.e. 2nd retry).

I can provide the logs of the successful attempt vs. the second failed attempt, but as far as I'm concerned there was no change in the external variables between the two runs. I'm also unable to give any suggestion for why any of the runs that worked did so vs. those that didn't.

**Comment by grubberr** [comment] 2023-03-17 08:06
Too low information. I cannot reproduce it for now.
It would be good to have some logs of unsuccessful attempts to proceed.

**Comment by YowanR** [comment] 2023-03-17 19:55
@StuartMiddleton Can you share more details here, please?

**Comment by YowanR** [comment] 2023-03-21 21:51
Since we don't have more data, let's close the issue. If anyone runs into the same problem, please tag us and we'll investigate further

**Closed by YowanR** 2023-03-21 21:51 UTC
Labels: type/bug, area/connectors, community, connectors/source/trello, team/connectors-python

**Comment by lumilinks-prefect** [comment] 2023-03-22 14:14
Sorry for late response (away from office). I've had to rebuild the environment and no longer have access to the old logs. Our latest implementation has been working though and the solution has been upgraded, so I'm happy for it to be closed until (/if) it reoccurs.

**Comment by StuartMiddleton** [comment] 2023-03-22 14:15
Sorry for late response (away from office). I've had to rebuild the environment and no longer have access to the old logs. Our latest implementation has been working though and the solution has been upgraded, so I'm happy for it to be closed until (/if) it reoccurs.
