### ISSUE TITLE
Source Google ads: Refresh token error when changing start_date in source settings

### ISSUE THREAD

**Issue by octavia-squidington-iii** [airbytehq/airbyte#9779] opened 2022-01-25 06:10 UTC
*Is this your first time deploying Airbyte:* No
*OS Version / Instance:* Ubuntu
*Memory / Disk:* 16Gb / 250GB
*Deployment:* Docker compose
*Airbyte Version:* 0.35.3-alpha

Our Google Ads connector imports data just fine, but once we try to reconfigure it in the settings (eg. change of startDate), we receive *RefreshError('invalid_client: Unauthorized', {'error': 'invalid_client', 'error_description': 'Unauthorized'})* after hitting the "retest source" button. We modified the actor configuration in the database directly, which works fine.

 https://airbytehq.slack.com/archives/C01MFR03D5W/p1642667748315200?thread_ts=1642667748.315200&cid=C01MFR03D5W

**Comment by davydov-d** [comment] 2022-05-16 08:48
hey @harshithmullapudi since you were the one who managed to reproduce this issue, can you please confirm it still remains? The connector version used to be 0.1.21 when the issue was reported, now it is 0.1.38 and personally I can not reproduce the problem

**Comment by harshithmullapudi** [comment] 2022-05-16 09:01
Yeah couldn't reproduce it anymore. Closing this now

**Closed** 2022-05-16 09:01 UTC
Labels: area/connectors, community, slack, team/use, autoteam
