### ISSUE TITLE
Source Stripe: Two different connections seem to be intertwining

### ISSUE THREAD

**Issue by set5think** [airbytehq/airbyte#22052] opened 2023-01-28 14:59 UTC
## Environment
- **Airbyte version**:  0.40.29
- **OS Version / Instance**: Amazon Linux 2, EC2
- **Deployment**: Docker using Nomad
- **Source Connector and version**: source-stripe 0.1.40
- **Destination Connector and version**: destination-redshift 0.3.28
- **Step where error happened**: Sync Job

## Current Behavior
*Tell us what happens.*

I have two connections set up in airbyte.  One is Stripe <> Redshift. and other is Zendesk Support <> Redshift.  When I synced stripe, it failed on a zendesk normalization error according to the logs.  On the second attempt. it succeeded, with no mention of zendesk in the logs.

## Expected Behavior
The two connections should be independent of each other

## Logs

[click for logs](https://gist.githubusercontent.com/set5think/3e5dbffd5d2bece0fdb95b692aa46961/raw/f6f27f70073634dca052f63198dccb4a0b722c72/airbyte_stripe_redshift_sync.txt)

## Steps to Reproduce
1. Set up Stripe <> Redshift.
2. Set up Zendesk <> Redshift.
3. Run Zendesk, receive normalization failure.
4.  Run Stripe, and sync fails due to Zendesk failure from step 3.
5. Run Stripe again, Zendesk failure goes away and Stripe succeeds.

## Are you willing to submit a PR?
Sure

**Comment by marcosmarxm** [comment] 2023-01-30 21:38
In the Replication tab -> Destination Namespace, are you using **Destination Default**? Maybe this is causing conflict between the connectors.

**Comment by set5think** [comment] 2023-01-30 23:07
@marcosmarxm Yes we are using that, with different prefixes for each.  What should we use instead to avoid this?

**Comment by marcosmarxm** [comment] 2023-01-31 09:21
If you're using prefixes shouldn't be a problem. The log file you shared it was generated from the airbyte-worker container or did you download from the UI in the Stripe connection page? 

In any case the root cause of failure is https://github.com/airbytehq/airbyte/issues/16412

**Comment by set5think** [comment] 2023-01-31 14:25
I downloaded the log file from the stripe connection page in the ui.  And yea I’ve seen the concat issue.  The thing is I dealt with that by downgrading the redshift connector to 0.3.28.  But this seems to be tangling log files from a run of the zendesk connection using a later version of the redshift connector.

**Comment by marcosmarxm** [comment] 2023-06-27 19:51
I'm closing as no one else reported the problem, let us know if this continue to affect you @set5think

**Closed by marcosmarxm** 2023-06-27 19:51 UTC
Labels: type/bug, area/connectors, community, connectors/sources-api, connectors/source/stripe, releaseStage/ga, team/connectors-python
