### ISSUE TITLE
web_backend/connections/updateNew API does not return disabled streams

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#14839] opened 2022-07-19 14:44 UTC
While testing our [FE changes](https://github.com/airbytehq/airbyte/pull/14634) we've noticed an issue with the `updateNew` API. It currently will only return enabled streams in the `syncCatalog` it returns from the API, and won't return disabled streams. That leads to the weird UI behavior, described here: https://github.com/airbytehq/airbyte/pull/14634#issuecomment-1185794754

The API should return all streams (same as `web_backend/connections/get`), to prevent this issue from happening.

**Comment by alovew** [comment] 2022-07-20 18:41
An update -- this is happening with the current endpoint as well, so is not a per-stream release blocker, but still a bug to fix.

**Comment by alovew** [comment] 2022-07-21 22:53
@timroes I'm looking into this now, but wasn't able to reproduce the stated UI behavior locally. 

When a new stream is added I'm seeing the full catalog returned by the new update endpoint including the newly selected streams (with the `selected:true` attribute)

One difference I'm seeing between the get and update endpoints is what is returned when a stream is removed. The get endpoint returns the stream in the catalog with `selected` set to `false`, but the update endpoint does not include that stream in the catalog returned. I'm not seeing any UI bugs around this though - the streams still show up correctly.

Do you have more details on how to reproduce this?

**Comment by edmundito** [comment] 2022-07-21 23:09
@timroes @alovew followed up with me about the issue and as I was looking at it turns out to be a frontend problem. `updateNew` is returning the disabled stream but for some reason, the frontend is no longer showing it until page refresh.

I will close this specific issue, but we need to open one for frontend instead.

**Comment by timroes** [comment] 2022-07-22 12:14
Do we know if something very recently changed about that? I was demoing this to Teal earlier this week, and it was that time bit returning them. 

Also do we have a follow up issue for FE already, we can link here?

**Comment by timroes** [comment] 2022-08-17 16:28
I've checked that again agains the recent master. The `updateNew` method (same as `create`) are not returning disabled streams in the syncCatalog they return. The only one that seems to return disabled catalogs is the `get` API. This is causing some weird behavior in the FE, since we basically can't accept the answer the BE took, but need to merge our own previous catalog into it.

I'd be happy if we could shortly sync about this, if we're seeing different behaviors here.

**Closed** 2022-08-30 00:19 UTC
Labels: type/bug, needs-triage, area/platform-oss, team/oss, platform-workflow/service
