### ISSUE TITLE
Update connector build to use local CDK on flag

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#28428] opened 2023-07-18 21:52 UTC
## Problem

Not being able to build the CDK with Dagger makes testing CDK change on connector difficult

The PyYAML upgrade problem would’ve been easier to fix if we could test connector against the “local” CDK

## Possible Solution
add a --local-cdk flag / env var to `airbyte-ci connector build` toggle this behaviour

**Comment by alafanechere** [comment] 2023-07-19 07:53
Closing as duplicate of https://github.com/airbytehq/airbyte/issues/24374

**Closed by alafanechere** 2023-07-19 07:53 UTC
Labels: team/connector-ops
