### ISSUE TITLE
Design of Sorting buttons in Credits page broken

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#17491] opened 2022-10-01 07:26 UTC
The design of the sorting buttons in the credits per connection table is broken:

![screenshot-20221001-092434](https://user-images.githubusercontent.com/877229/193398175-77ac012d-08f9-4df0-a9e3-d4c319ab481b.png)

cc @dizel852 @edmundito (While this page is cloud team, I feel this likely broke due to the button component refactoring, so would appreciate if you could have a look at this).

**Comment by octavia-squidington-iv** [comment] 2022-10-01 07:26
cc @airbytehq/frontend

**Comment by tealjulia** [comment] 2022-10-03 15:50
The issue is showing up in Cloud, but is likely due to a Platform change with the new Button component.

**Comment by dizel852** [comment] 2022-10-18 12:01
The issue is fixed in the scope of #17798

**Closed** 2022-10-20 10:36 UTC
Labels: type/bug, team/cloud, team/workflow, team/frontend, regression
