### ISSUE TITLE
Check Connection when updating destination credentials in the UI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#352] opened 2020-09-21 00:43 UTC
## Tell us about the problem you're trying to solve
I updated my bigquery destination with incorrect credentials in the UI (`/destination`) but did not receive any error messages.

**Comment by sherifnada** [comment] 2020-09-21 00:45
Potentially related to #340

**Comment by cgardens** [comment] 2020-09-21 17:24
yeah. this is a duplicate of https://github.com/airbytehq/airbyte/issues/340

**Closed by cgardens** 2020-09-21 17:24 UTC
Labels: type/bug
