### ISSUE TITLE
Support connector configuration via environment variables

### ISSUE THREAD

**Issue by reubano** [airbytehq/airbyte#9267] opened 2022-01-04 07:20 UTC
## Tell us about the problem you're trying to solve

Configuring connectors is quite cumbersome

## Describe the solution you’d like

I would like to be able to configure connectors via environment variables

## Describe the alternative you’ve considered or used
Copy/paste

## Additional context

[Meltano](https://docs.meltano.com/guide/configuration#configuration-layers) looks for configuration values in

- Environment variable
- meltano.yml project file
- project's system database
- parent plugin's own configuration
- default plugin's value

## Are you willing to submit a PR?
sure

**Comment by marcosmarxm** [comment] 2022-01-05 02:21
Thanks for requesting this @reubano. @alafanechere is working in the Airbyte CLI, which can achieve some of features you're requesting.

**Comment by alafanechere** [comment] 2022-01-06 16:16
Hi @reubano, if you want more details about this project feel free to have a look at this [deck](https://docs.google.com/presentation/d/10RjkCzBiVhCivnjSh63icYI7wG6S0N0ZIErEIsmXTqM/edit?usp=sharing).

**Comment by reubano** [comment] 2022-01-07 02:32
Thanks @alafanechere! Where should i put my comments/suggestions?

**Comment by alafanechere** [comment] 2022-01-07 14:24
> Thanks @alafanechere! Where should i put my comments/suggestions?

Feedback is welcomed as comments on the deck.

**Comment by marcosmarxm** [comment] 2022-07-05 17:52
I'm not closing this because is different from Octavia CLI.

**Comment by evantahler** [comment] 2022-08-01 22:03
Re-tagging this to `area/ocatvia-cli`.  For now, the path forward for using environment variables to set up a connector would be to allow for variables in Octavia's config files, and then apply those changes.  Due to the way we run Airbyte (e.g. lots of docker containers), there's not a per-connection way to pass environment variables easily to a container.

**Comment by marcosmarxm** [comment] 2022-11-30 18:00
Duplicate of https://github.com/airbytehq/airbyte/issues/4035

**Closed by marcosmarxm** 2022-11-30 18:00 UTC
Labels: type/enhancement, area/connectors, community, area/octavia-cli, team/use, autoteam
