### ISSUE TITLE
Google Ads Source: Ad cost is inconsistent from real value 

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/airbyte#10392] opened 2022-02-16 23:05 UTC
## Main Issue
It appears that Google Ads performance reports are inconsistent aggregating the cost of ads. 

## Notes
@bigdatawonders is facing this issue and will provide more context below before we triage.

**Comment by bigdatawonders** [comment] 2022-02-19 10:12
Hello, current Google Ads API does not extract removed ads spend:
attaching image
<img width="712" alt="Screenshot 2022-02-19 at 11 12 05" src="https://user-images.githubusercontent.com/22476549/154796608-d5f5d20c-f061-43a8-be8d-0a5e01396c63.png">

**Comment by sherifnada** [comment] 2022-03-22 04:23
@bigdatawonders could you clarify which field in the output from Airbyte you are referring to?

**Comment by sherifnada** [comment] 2022-03-22 04:40
For what it's worth, Airbyte grabs the data for all ads regardless of their status i.e: the connector doesn't filter based on ad status using a `WHERE status = active` or anything like that. So I'm trying to understand how the field in your UI screenshot is generated.

**Comment by edgao** [comment] 2022-03-23 21:53
@bigdatawonders is the trouble that we _aren't_

**Comment by bigdatawonders** [comment] 2022-03-24 07:20
I believe this issue happens with deleted ads… So the problem is that ad
spend does not match with campaign spend… not sure if there flags to
include deleted ads or something I the stream…

**Comment by sherifnada** [comment] 2022-03-24 16:00
@bigdatawonders could you help us resolve the issue by providing the following info:

* what is the airbyte  field name which displays the incorrect value?
* in what UI did you generate the screenshot above?

**Comment by sherifnada** [comment] 2022-03-30 00:56
marking this as blocked pending a response from @bigdatawonders

**Comment by davydov-d** [comment] 2022-04-05 16:28
@bigdatawonders hello, could you please provide us with information needed for further investigation? I'm on this issue now, but I'm blind until I know 
 - what is the airbyte field name which displays the incorrect value?
 - in what UI did you generate the screenshot above? do you know which API fields it queries to reach this value/which parametrs it uses?

**Comment by davydov-d** [comment] 2022-04-22 15:35
@bigdatawonders sorry for the long delay, I'm back on this again now.
The screenshots you have made are not actually attached, could you try again?

I've tried to reproduce the issue for a couple of times but failed. So I have some more questions to clarify:
- Do you apply any filters or segmentation on the UI?
- How do you get the aggregated value in the stream? From what I see, the connector does not do any aggregation, just pulls the raw values

**Comment by davydov-d** [comment] 2022-04-28 16:36
@bigdatawonders could you please comment my question above?

cc @misteryeo

**Comment by davydov-d** [comment] 2022-06-02 14:24
this looks like the duplicate of https://github.com/airbytehq/airbyte/issues/12999, closing

**Closed by davydov-d** 2022-06-02 14:24 UTC
Labels: type/bug, area/connectors, connectors/sources-api, connectors/source/google-ads, team/connectors-python
