### ISSUE TITLE
Connector builder: Reorder and explicitly order user inputs

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#24395] opened 2023-03-23 10:48 UTC
User inputs in the connector builder are currently ordered alphabetically by their key and the user can't control this.

It should be possible to reorder the inputs and translate these into "order" properties in the spec so they are picked up correctly from the connector form.

**Comment by lmossman** [comment] 2023-05-11 19:42
Duplicate of https://github.com/airbytehq/airbyte/issues/20579

**Closed by lmossman** 2023-05-11 19:42 UTC
Labels: needs-triage, team/extensibility, ui/connector-builder
