### ISSUE TITLE
Source doesn't support some type of unicode and there is no skip onboard button on step 3 so I got stuck on webpage.

### ISSUE THREAD

**Issue by Elshir** [airbytehq/airbyte#1928] opened 2021-02-02 10:09 UTC
I fresh installed airbyte on my centos 7, and here are the problems I encountered:

1. I setup both source and destination correctly and sure both of them works
1. when I got step 3 of 'on board' it said: Failed to fetch schema. Please try again.
1. there is no way back so I stuck on page but click 'try agagin'

I've contacted with Chris and we found out this error:
`airbyte-scheduler | 2021-02-02 09:49:02 ERROR i.a.c.i.LineGobbler(voidCall):69 - {job_id=47, job_log_filename=logs.log, job_root=/tmp/workspace/47/0} - Exception in thread "main" java.sql.SQLSyntaxErrorException: Table 'test.xiaoyi??????????' doesn't exist`

## Severity of the bug for you
High

## Airbyte Version: 
Latest

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368210993995) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment] 2021-02-02 10:26
With the stack trace, it looks like this:

```
2021-02-02 09:48:56 INFO (/tmp/workspace/47/0) LineGobbler(voidCall):69 - airbyte/source-mysql:0.1.9 was found locally.
2021-02-02 09:48:56 DEBUG (/tmp/workspace/47/0) DockerProcessBuilderFactory(create):104 - Preparing command: docker run --rm -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/47/0 --network host airbyte/source-mysql:0.1.9 discover --config tap_config.json
2021-02-02 09:48:59 INFO (/tmp/workspace/47/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-02-02 09:48:59 [32mINFO[m i.a.i.s.m.MySqlSource(main):75 - {} - starting source: class io.airbyte.integrations.source.mysql.MySqlSource
2021-02-02 09:48:59 INFO (/tmp/workspace/47/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-02-02 09:48:59 [32mINFO[m i.a.i.b.IntegrationRunner(run):78 - {} - Running integration: io.airbyte.integrations.source.mysql.MySqlSource
2021-02-02 09:48:59 INFO (/tmp/workspace/47/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-02-02 09:48:59 [32mINFO[m i.a.i.b.IntegrationCliParser(parseOptions):135 - {} - integration args: {discover=null, config=tap_config.json}
2021-02-02 09:48:59 INFO (/tmp/workspace/47/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-02-02 09:48:59 [32mINFO[m i.a.i.b.IntegrationRunner(run):82 - {} - Command: DISCOVER
2021-02-02 09:48:59 INFO (/tmp/workspace/47/0) DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-02-02 09:48:59 [32mINFO[m i.a.i.b.IntegrationRunner(run):83 - {} - Integration config: IntegrationConfig{command=DISCOVER, configPath='tap_config.json', catalogPath='null', statePath='null'}
2021-02-02 09:49:02 ERROR (/tmp/workspace/47/0) LineGobbler(voidCall):69 - Exception in thread "main" java.sql.SQLSyntaxErrorException: Table 'test.xiaoyi??????????' doesn't exist
2021-02-02 09:49:02 ERROR (/tmp/workspace/47/0) LineGobbler(voidCall):69 - at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
2021-02-02 09:49:02 ERROR (/tmp/workspace/47/0) LineGobbler(voidCall):69 - at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
2021-02-02 09:49:02 ERROR (/tmp/workspace/47/0) LineGobbler(voidCall):69 - at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
2021-02-02 09:49:02 ERROR (/tmp/workspace/47/0) LineGobbler(voidCall):69 - at com.mysql.cj.jdbc.StatementImpl.executeQuery(StatementImpl.java:1200)
2021-02-02 09:49:02 ERROR (/tmp/workspace/47/0) LineGobbler(voidCall):69 - at com.mysql.cj.jdbc.DatabaseMetaData$2.forEach(DatabaseMetaData.java:2140)
2021-02-02 09:49:02 ERROR (/tmp/workspace/47/0) LineGobbler(voidCall):69 - at com.mysql.cj.jdbc.DatabaseMetaData$2.forEach(DatabaseMetaData.java:2069)
2021-02-02 09:49:02 ERROR (/tmp/workspace/47/0) LineGobbler(voidCall):69 - at com.mysql.cj.jdbc.IterateBlock.doForAll(IterateBlock.java:56)
2021-02-02 09:49:02 ERROR (/tmp/workspace/47/0) LineGobbler(voidCall):69 - at com.mysql.cj.jdbc.DatabaseMetaData.getColumns(DatabaseMetaData.java:2245)
2021-02-02 09:49:02 ERROR (/tmp/workspace/47/0) LineGobbler(voidCall):69 - at org.apache.commons.dbcp2.DelegatingDatabaseMetaData.getColumns(DelegatingDatabaseMetaData.java:227)
2021-02-02 09:49:02 ERROR (/tmp/workspace/47/0) LineGobbler(voidCall):69 - at org.apache.commons.dbcp2.DelegatingDatabaseMetaData.getColumns(DelegatingDatabaseMetaData.java:227)
2021-02-02 09:49:02 ERROR (/tmp/workspace/47/0) LineGobbler(voidCall):69 - at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.lambda$discoverInternal$11(AbstractJdbcSource.java:327)
2021-02-02 09:49:02 ERROR (/tmp/workspace/47/0) LineGobbler(voidCall):69 - at io.airbyte.db.jdbc.DefaultJdbcDatabase.bufferedResultSetQuery(DefaultJdbcDatabase.java:66)
```

**Comment by jrhizor** [comment] 2021-02-11 20:11
#1970 fixed this.

**Comment by jrhizor** [comment] 2021-02-11 20:15
#1970 fixes the lack of skipping, but not the Unicode issue.

**Comment by Jamakase** [comment] 2021-02-19 21:07
@ChristopheDuong Any info on how to reproduce this issue? I tried to create a table with Unicode symbols and didn't have any issues so far.

**Comment by cgardens** [comment] 2021-03-01 18:32
@ChristopheDuong bump.

**Comment by ChristopheDuong** [comment] 2021-03-01 18:40
I don't have more info on this, I suppose it is just a matter of having Unicode characters in the table names in the sources: @Elshir could you maybe retry with the latest versions of Airbyte/source connectors as we may have fixed this recently?

Thanks

**Comment by davinchia** [comment] 2021-04-22 14:09
@Elshir is this still causing a problem?

**Comment by cgardens** [comment] 2021-06-22 22:34
Let's close this for now. @Elshir feel free to reopen if the suggested remediation by @davinchia and @ChristopheDuong don't solve your problem.

**Closed by cgardens** 2021-06-22 22:34 UTC
Labels: community_request, priority/high, type/bug
