### ISSUE TITLE
need clickhouse has destination connector

### ISSUE THREAD

**Issue by bindu29** [airbytehq/airbyte#3812] opened 2021-06-02 12:40 UTC
## Tell us about the new connector you’d like to have
* Which source and which destination?
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

## Describe the context around this new connector
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

we are trying to write source connectors data to clickhouse in the destination 
is it possible to add clickhouse in destination and do sync for every few minutes

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200415554616065) by [Unito](https://www.unito.io)

**Comment by sherifnada** [comment] 2021-06-02 14:15
@bindu29 duplicate of #1903 , can you leave any comments you have it there? We'll support clickchouse soon

**Closed by sherifnada** 2021-06-02 14:15 UTC
Labels: area/connectors, new-connector
