### ISSUE TITLE
Postgres oldest lsn doesn't update when there is no new records

### ISSUE THREAD

**Issue by mohammad-bolt** [airbytehq/airbyte#6230] opened 2021-09-17 19:55 UTC
## Enviroment
- **Airbyte version**:  example is 0.27.0-alpha
- **Deployment**: kubernetes 
- **Source Connector and version**: postgress 0.3.11
- **Destination Connector and version**:  bigquery
- **Severity**: High
- **Step where error happened**: Sync job

## Current Behavior
*Tell us what happens.*

I noticed when in incremental mode, postgress source doesn’t update postgre server when there is no new data.
that means postgress doesn’t empty its logs in this case. has anybody else noticed this? I ran this

```
SELECT 
    slot_name, 
    plugin,
    pg_size_pretty(pg_current_wal_lsn()-restart_lsn) as replication_lag,
    restart_lsn
FROM pg_replication_slots;
```

and confirmed.
the table in questions has only 3 rows with no updates. 

## Expected Behavior
In order to prevent binlogs from piling up on the DB, the connector should always update its read position in the binlog to the latest available, even if none of the updates are from tables we care about. 

## Logs

[logs-273-0.txt.gz](https://github.com/airbytehq/airbyte/files/7188163/logs-273-0.txt.gz)

**Comment by sherifnada** [comment] 2021-09-24 06:20
@mohammad-bolt thanks for creating this - we've heard this from other users and will prioritize shortly!

**Comment by smartpierre** [comment] 2021-12-28 11:59
I confirm I had the same issue on my side.

**Comment by ashligel** [comment] 2022-01-19 10:46
I am also experiencing this in my Postgres setup -- I have to manually insert data so that the oldest lsn updates.

**Comment by etsybaev** [comment] 2022-05-08 12:41
Just tried to check with CDC, but can't get wats wrong. Kidly ask to add steps to reproduce, actual and expected results. Thanks!
One of my tests was:
Updated record with id=11 to set value "1111" instead of old record "1".
![Selection_159.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/772782b4-e557-4fad-a863-a4180255ffd2)
So only one change was in DB since previous sync and it was an Update DB change.
![Selection_162.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/aae8c0df-a7d0-425a-a589-0ad7a7054c3f)Then tried to replicate on more time:
![Selection_160.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/aeee8e57-0b1c-4a00-ba0b-f4def0a1fb39)

Checking the result:
![Selection_162.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/f96ee43b-0d26-4ec5-9bac-eaae4478ffd6)

Then did nothing with DB and tried to sync again. expectedly no reconds have been replicated, and no fails:
![Selection_163.png](https://images.zenhubusercontent.com/627269f99b780c901a3d24e2/7e2aef0a-7b29-48bd-8cf9-0d74c6e9558d)

**Comment by etsybaev** [comment] 2022-05-16 12:09
Hi there. I'm closing this ticket since I haven't got any replies and do not see any issues from the end-user perspective. Please feel free to reopen, but kindly ask to add clear steps to reproduce, actual and expected behavior. Thanks

**Closed by etsybaev** 2022-05-16 12:09 UTC
Labels: type/bug, area/connectors, cdc, connectors/source/postgres, team/connectors-java
