### ISSUE TITLE
Source Hubspot: problem with normalization in `items_properties`

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#6592] opened 2021-09-30 23:49 UTC
## Enviroment
Airbyte version: 0.29.19-alpha
HubSpot integration version: 0.1.15
Normalization version: airbyte/normalization:0.1.44 

## Current Behavior
```
2021-09-25 23:34:29 INFO () LineGobbler(voidCall):85 - [31mCompleted with 1 error and 0 warnings:[0m
2021-09-25 23:34:29 INFO () LineGobbler(voidCall):85 - 
2021-09-25 23:34:29 INFO () LineGobbler(voidCall):85 - [33mDatabase Error in model line_items_properties (models/generated/airbyte_tables/integration_1618_HubSpot_1632407265/line_items_properties.sql)[0m
2021-09-25 23:34:29 INFO () LineGobbler(voidCall):85 -   Invalid timestamp: '1611360000000'
2021-09-25 23:34:29 INFO () LineGobbler(voidCall):85 -   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_tables/integration_1618_HubSpot_1632407265/line_items_properties.sql
2021-09-25 23:34:29 INFO () LineGobbler(voidCall):85 - 
2021-09-25 23:34:29 INFO () LineGobbler(voidCall):85 - Done. PASS=178 WARN=0 ERROR=1 SKIP=0 TOTAL=179
```

## Expected Behavior
*Tell us what should happen.*

## Logs
[logs-1062-2.txt](https://github.com/airbytehq/airbyte/files/7263100/logs-1062-2.txt)

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by htrueman** [comment] 2021-10-04 14:59
## Scoping report

Found that `line_items.json` schema is not matching to the object sample from the docs https://developers.hubspot.com/docs/api/crm/line-items. So it seems that the issue should disappear after we fix the schema.

**Comment by yevhenii-ldv** [comment] 2021-11-05 13:59
Hi @marcosmarxm
I am trying to figure out this problem.
I have great doubts that this error is a Hubspot connector error at the moment.
@htrueman suggested that the error might be due to an incorrect scheme for the `line_items` stream, but in the recent version of Hubspot, the scheme was fixed (2021-10-26).
I am guessing it might be a data normalization error. In order to understand a little more details, please tell me,
1. was it a one-time failure in general, or were there similar problems with other connectors?
2. after 2021-10-26, perhaps you tried to start another synchronization for Hubspot Connector, were there any problems?

Additional logs about this would be useful to me if you have them.

**Comment by yevhenii-ldv** [comment] 2021-11-05 15:20
@marcosmarxm 
And if you used Destination `BigQuery`, then I see that a similar bug was fixed on 10/25/2021. I'm not sure if this is it, but it seems to be a very similar bug (these changes corrected the #7240 and #2579 issues).
![image](https://user-images.githubusercontent.com/34103125/140534703-69b374ac-6f14-4d8c-adf5-807b4a873364.png)

Therefore, could you please set up the connector and destination again, start the synchronization and inform me of its result? Since I am unable to reproduce this problem.

**Comment by yevhenii-ldv** [comment] 2021-11-11 14:48
Hi, @marcosmarxm!)
I tested the new and old (which were relevant at the time of the ticket creation) versions of the connector (Hubspot) and the destination (BigQuery with normalization), and got the following results:
1. Hubspot v0.1.24 and BigQuery v0.5.0.
![image](https://user-images.githubusercontent.com/34103125/141316589-1d8245e7-0d5c-48ab-859a-3e5279c94beb.png)
Logs are here: [logs-14-0.txt](https://github.com/airbytehq/airbyte/files/7521156/logs-14-0.txt)
2. Hubspot v0.1.16 and BigQuery v0.4.0.
![image](https://user-images.githubusercontent.com/34103125/141317187-0a556431-699a-44aa-8f60-24298ddea49a.png)
Logs are here: [logs-13-0.txt](https://github.com/airbytehq/airbyte/files/7521165/logs-13-0.txt)
 
Older versions found an error during normalization with `function TIMESTAMP_TRUNC` in my case. Now everything works out without problems and I get all the data in my dataset, even with the normalization of this data.

If you do not have more information, then I think that this issue can be closed.

**Comment by sherifnada** [comment] 2021-11-12 20:03
@yevhenii-ldv thanks! let's close it

**Closed by sherifnada** 2021-11-12 20:03 UTC
Labels: type/bug, area/connectors

**Comment by marcosmarxm** [comment] 2021-11-12 21:45
Thanks @yevhenii-ldv sorry not answered before.
