### ISSUE TITLE
Source MongoDB: cann't connect to TLS enabled Amazon DocumentDB

### ISSUE THREAD

**Issue by awill1** [airbytehq/airbyte#10388] opened 2022-02-16 21:03 UTC
## Environment
- **Airbyte version**:  0.35.12-alpha
- **OS Version / Instance**: Amazon Linux 2
- **Deployment**: AWS EC2
- **Source Connector and version**: MongoDB 0.1.11
- **Severity**: Medium
- **Step where error happened**: Setup new connection

## Current Behavior
When setting up a MongoDB source connector that connects to a TLS enabled Amazon DocumentDB (which is basically an AWS hosted MongoDB solution) the test connection fails because it is not using the Amazon RDS CA Certificate for the TLS connection that is required by Amazon DocumentDB. The error seen is:

```
Could not connect with provided configuration. Error: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=<DOCUMENTDB_HOST>:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}, caused by {sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}, caused by {sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}}]
```

## Expected Behavior
The MongoDB source connection to the Amazon DocumentDB should be successful and the source should be created. The connection should work because it should use Amazon's CA certificate when connecting to the DocumentDB instance. This is the location of the pem file that is needed: `https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem` to make the connection. Here is AWS's documentation on connecting to a TLS enabled DocumentDB https://docs.aws.amazon.com/documentdb/latest/developerguide/connect_programmatically.html#connect_programmatically-tls_enabled

## Logs
Error seen in the new source UI page is:

<details>

```
Could not connect with provided configuration. Error: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=<DOCUMENTDB_HOST>:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}, caused by {sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}, caused by {sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target}}]
```

</details>

## Steps to Reproduce
1. Create a Amazon DocumentDB
2. In Airbyte, create a new source using the MongoDB source type
3. Fill in all information to connect to the source
4. Click "Set up source" to create the source. If encountering this issue, the connection test will fail.

## Are you willing to submit a PR?
Yes. I have an idea how I can add this support.

**Comment by awill1** [comment] 2022-02-23 13:51
I have a solution working locally. I am a little concerned with the design. I see two options for getting the Amazon RDS CA Certificate added to the Java keystore in the mongodb-v2 connector container to make the DocumentDB TLS enabled connections work:

1. Add the certificates to the keystore at docker build time. This is the solution I have working locally. Pros: minimal changes to the connector code and the DocumentDB connections just work. Cons: Certificates will get stale in the image. When certs expire they will need a new image build. I think this is only done when changes are make to the connector. I think this con makes my current solution a showstopper. 
2. Add the certificate to the keystore at runtime only when connecting to an Amazon DocumentDB database. I have not verified this is possible in the connector code yet. Pros: Certificates will always be valid and the latest version of the certs will be used. Cons: Requires a connection to the internet to download the latest cert file from https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem . Some networks where airbyte is installed may not allow this connection due to firewall rules.

Maybe I could combine the two options into a third option, but it still would mean the certs would eventually be stale in a locked down network and would eventually fail. I don't think the extra complexity of the combined option is worth the showstopping con.

I am leaning toward option two if it is possible. I think since Amazon DocumentDB is a hosted service, a connection to the internet (at least https to s3.amazon.com) is a reasonable requirement. Maybe AWS VPC endpoints would help by getting rid of the public internet requirement.

**Comment by ntkawasaki** [comment] 2022-02-23 14:12
I agree that 2 would be ideal, especially because there will be other cases where people need to upload custom or self-signed SSL certificates potentially for any connector and supporting a code path to install certificates on a per-connector basis would solve that problem for every connector including this RDS case. 

That being said I don't know if this option currently exists for any connector (I think I might have seen this for one though?) and how much effort number 2 would take. 

Option 1 seems fine to me in the short term assuming 2 is infeasible until there is a way to upload certificates at runtime, since the URL to download the up-to-date certificate is constant. If this cert expires (which is does in `Not After : Jun  1 12:00:00 2022 GMT`) the only effort someone would need to take is to re-build the image, and publish a new release for it to Airbyte's DockerHub. Then users would just need to set their DocumentDB connections to use the latest release for the new certificate. AWS is super loud about expiring certificates, they posted a ton of articles and made a lot of noise about this in 2019 when the last round of certs expired so the update would not silently slip through.

**Comment by ntkawasaki** [comment] 2022-02-23 14:22
This is essentially the same issue for MySQL: https://github.com/airbytehq/airbyte/issues/6985

**Comment by walidaziz** [comment] 2022-03-04 07:45
Hi @awill1 
Maybe a newbie/trivial question. 
Regarding the first solution, once local changes are done, and once the connector is pushed on a personal online docker repository, how could I use inside it staging Airbytes. I tried through the admin UI but without success.
 Thanks

**Comment by awill1** [comment] 2022-03-04 15:01
@walidaziz when you have made a code change to the connector and built the image locally you can use the local image in your local running airbyte by changing the version of the connector to `dev`. In your local airbyte go to **Settings** > **Sources** > **MongoDB** , then set the version to `dev` and click **Change**. Then your local image should be used.

**Comment by walidaziz** [comment] 2022-03-04 16:40
@awill1  thanks, but the problem is that my local build machine is not the same as the Airbytes staging one. I tried to go through a private docker registry, but I get "Internal Server Error: Get Spec job failed." message  on gui and on console : 

`airbyte-server      | 2022-03-04 16:35:33 ERROR i.a.s.e.UncaughtExceptionMapper(toResponse):22 - Uncaught exception
airbyte-server      | java.lang.IllegalStateException: Get Spec job failed.
airbyte-server      |   at com.google.common.base.Preconditions.checkState(Preconditions.java:502) ~[guava-31.0.1-jre.jar:?]
airbyte-server      |   at io.airbyte.server.converters.SpecFetcher.getSpecFromJob(SpecFetcher.java:14) ~[io.airbyte-airbyte-server-0.35.45-alpha.jar:?]`

**Comment by kodeine** [comment] 2022-03-11 01:00
I think it should be renamed from DocumentDB support to something generic because Digital Ocean provides the same and it could be used with D/O.

**Comment by kodeine** [comment] 2022-03-11 15:09
@awill1 is it possible to make it work with Digital Ocean's managed mongodb cert as well?

**Comment by octavia-squidington-iii** [comment] 2022-03-29 19:24
Marcos Marx commented: I agree that 2 would be ideal, especially because there will be other cases where people need to upload custom or self-signed SSL certificates potentially for any connector and supporting a code path to install certificates on a per-connector basis would solve that problem for every connector including this RDS case. 

That being said I don't know if this option currently exists for any connector (I think I might have seen this for one though?) and how much effort number 2 would take. 

Option 1 seems fine to me in the short term assuming 2 is infeasible until there is a way to upload certificates at runtime, since the URL to download the up-to-date certificate is constant. If this cert expires (which is does in `Not After : Jun  1 12:00:00 2022 GMT`) the only effort someone would need to take is to re-build the image, and publish a new release for it to Airbyte's DockerHub. Then users would just need to set their DocumentDB connections to use the latest release for the new certificate. AWS is super loud about expiring certificates, they posted a ton of articles and made a lot of noise about this in 2019 when the last round of certs expired so the update would not silently slip through.

**Comment by thepr0blem** [comment] 2023-12-12 20:45
is there any solution to this issue? any way to setup document db as a source?

**Comment by rodireich** [comment] 2023-12-13 21:47
@thepr0blem Please follow #33452 to track a solution. thank you

**Comment by evantahler** [comment] 2024-03-22 16:09
Closing as duplicate of https://github.com/airbytehq/airbyte/issues/33452 - join us over there!

**Closed by evantahler** 2024-03-22 16:09 UTC
Labels: type/bug, help-welcome, area/connectors, community, area/databases, connectors/source/mongodb, team/db-dw-sources
