### ISSUE TITLE
🐛 Source Notion: Integration with AuthToken fails to collect all streams.

### ISSUE THREAD

**Issue by ghost** [airbytehq/airbyte#23247] opened 2023-02-20 10:59 UTC
## Environment
- **Airbyte version**:  0.40.32
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker container
- **Source Connector and version**: Notion 1.0.1
- **Destination Connector and version**:  E2E and Postgres
- **Step where error happened**: Sync data

## Current Behavior
The connection is successfully created using the AuthToken from Notion. When syncing the data to either E2E or Postgres, only the users stream is synced. The logs are attached - seems the error is with the auth method.

## Expected Behavior
All streams should sync.

## Logs
The log file is attached.

## Steps to Reproduce
1. Setup Notion integration - Source
2. Copy Notion secret to Airbyte authToken
3. Setup E2E or Postgres DB as Destination
4. Sync the connection.

[671dc7d6_12d4_4bec_aac6_87b789c3ea1c_logs_25_txt.txt](https://github.com/airbytehq/airbyte/files/10783600/671dc7d6_12d4_4bec_aac6_87b789c3ea1c_logs_25_txt.txt)

**Comment by philippeboyd** [comment] 2023-02-20 15:27
I think this is a duplicate of https://github.com/airbytehq/airbyte/issues/16987

**Comment by Philip-Nell** [comment] 2023-02-21 07:13
It is similar in the sense that the streams are not syncing. I have implemented the changes as specified by ticket https://github.com/airbytehq/airbyte/issues/16987. However, the difference comes with the auth method. The errors from the log file state there is a problem with the auth method, irrespectable of which auth method is used:

2023-02-20 10:08:40 [32mINFO[m i.a.v.j.JsonSchemaValidator(test):130 - JSON schema validation failed. 
errors: $.auth_type: must be a constant value OAuth2.0, $.client_id: is missing but it is required, $.client_secret: is missing but it is required, $.access_token: is missing but it is required
2023-02-20 10:08:40 [32mINFO[m i.a.v.j.JsonSchemaValidator(test):130 - JSON schema validation failed. 
errors: $.token: object found, string expected

In the above instance, the access_token auth method is used.

**Comment by ChristoGrab** [comment] 2023-09-21 22:33
I've tried reproducing this error with multiple permutations of keys and permissions, but have been unable to do so. I believe the underlying cause was fixed with the [migration to AdvancedAuth](https://github.com/airbytehq/airbyte/pull/26535). I am closing for now, but will keep an ear to the ground in case a similar issue is reported in the future.

**Closed by ChristoGrab** 2023-09-21 22:33 UTC
Labels: type/bug, help-welcome, area/connectors, community, connectors/sources-api, connectors/source/notion, releaseStage/ga, team/connectors-python
