### ISSUE TITLE
Source: Elasticsearch

### ISSUE THREAD

**Issue by mohamed-mubeen** [airbytehq/airbyte#3331] opened 2021-05-10 15:13 UTC
## Tell us about the new integration you’d like to have
* Which source and which destination?
> Source - Elasticsearch
> Destination - Snowflake
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 
> No

## Describe the context around this new integration
* Which team in your company wants this integration, what for? This helps us understand the use case.
> Data Science Team (for BI purpose)
* How often do you want to run syncs?
> 5 minutes (near real-time)

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
> ELK to AWS S3 to Snowflake via Snowpipe

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368230958449) by [Unito](https://www.unito.io)

**Comment by marcosmarxm** [comment] 2021-05-10 21:30
Thanks for opening this @mohamed-mubeen we already support Snowflake as a destination. Source/Destination are decoupled then after adding ElasticSearch as a source you should be able to replicate to any destination we support. I added this request to our roadmap.

**Comment by davinchia** [comment] 2021-06-27 09:37
This is a duplicate of #2255. Closing this in favor of that. Please follow that for updates!

**Closed by davinchia** 2021-06-27 09:37 UTC
Labels: area/connectors, new-connector
