### ISSUE TITLE
Timestamp '+292269055-12-02T23:00:00.000000 BC' is not recognized  in Postgres <> Snowflake sync

### ISSUE THREAD

**Issue by rodireich** [airbytehq/airbyte#20648] opened 2022-12-19 17:02 UTC
## Environment
- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: Postgres 1.0.34
- **Destination Connector and version**: Snowflake 0.4.40
- **Step where error happened**: Sync job

## Current Behavior
Sync failing on normalization with 
```
Timestamp '+292269055-12-02T23:00:00.000000 BC' is not recognized,retryable=<null>,timestamp=1670854419937]]]
```
In the following [connection](https://cloud.airbyte.io/workspaces/e9159746-6a8d-4e75-a7e9-f78d7cfbcb21/connections/88b1ccb1-4439-43cd-aea4-8db2ccdb5dc7/status).

## Expected Behavior
Sync should be able to handle values successfully.

## Logs
See [connection](https://cloud.airbyte.io/workspaces/e9159746-6a8d-4e75-a7e9-f78d7cfbcb21/connections/88b1ccb1-4439-43cd-aea4-8db2ccdb5dc7/status).

**Comment by akashkulk** [comment] 2022-12-28 01:48
Duplicate of https://github.com/airbytehq/airbyte/issues/19952

**Closed by akashkulk** 2022-12-28 01:48 UTC
Labels: type/bug, needs-triage, connectors/source/postgres, team/db-dw-sources
