### ISSUE TITLE
Transformations not working in custom connectors Builder

### ISSUE THREAD

**Issue by alanmmolina** [airbytehq/airbyte#44192] opened 2024-08-16 20:30 UTC
### Topic

custom connectors builder

### Relevant information

Hey folks!

We're encountering an issue with our custom connectors created using the UI Builder. After updating the Airbyte version, the custom connectors that use the “Add Field” transformation are broken; we can’t even edit them. The only workaround is to remove the transformation property directly in the manifest YAML.

It seems to be related to `4.3.2` version of the `airbyte-cdk` ([commit](https://github.com/airbytehq/airbyte-platform/commit/474d714889dace8db97f2327ec4624fe93702113)).

We're using Helm chart version `0.442.3`, and we’ve tested this both in a Kubernetes environment and with the local `abctl` setup.

Here is an example:

![image](https://github.com/user-attachments/assets/c63ab44e-be56-45ca-8d5c-fd6117f97d24)

**Comment by erohmensing** [comment] 2024-08-19 18:04
Hi @alanmmolina, thanks for reporting this - sorry this got into a published version! This issue was fixed in [this commit](https://github.com/airbytehq/airbyte-platform/commit/f9e913d177dac3aa3f0d90902ccc0c09032cd0cf)

Can you try updating to the [latest version](https://github.com/airbytehq/airbyte-platform/releases/tag/v0.63.18) to see if it resolves the issue?

**Comment by fredmny** [comment] 2024-08-20 15:19
Thanks a lot for your message @erohmensing 
We'll upgrade the version next week (I'm also on @alanmmolina 's team). Do you want us to let you know if everything runs successfully? If you already know this will work we can close this issue as resolved as well.

**Comment by erohmensing** [comment] 2024-08-20 21:07
@fredmny I'm reasonably confident that this issue is the same as the one we were seeing before, but I'll let you close the issue when it's resolved for you since I can't reproduce your specific issue to check :)

**Comment by natikgadzhi** [comment] 2024-08-22 00:12
+1, it's fixed in the latest release. Ping us if it persists after updating!

**Closed by natikgadzhi** 2024-08-22 00:12 UTC
Labels: community, needs-triage, autoteam, team/use

**Comment by brianbolt** [comment] 2024-08-29 20:12
@natikgadzhi Was there a regression?  I'm on version `0.63.17` and am seeing the same issue.

<img width="1486" alt="Screenshot 2024-08-29 at 1 12 25 PM" src="https://github.com/user-attachments/assets/c324d378-c4f7-42c3-9c1c-3f3831b4c7d7">

**Comment by brianbolt** [comment] 2024-08-29 20:17
Err, ignore me. I was confused on my version numbers.  I’m actually on 0.63.17 thought I was on latest since I updated recently but I see 0.67.17 latest currently and i’m already behind.
