### ISSUE TITLE
mini-postmortem of why auth change impacted connector builder server

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#26004] opened 2023-05-11 17:26 UTC
OC Page:
https://airbytehq-team.slack.com/archives/C05507UP11A/p1683752242123749

Slack Thread for Context:
https://airbytehq-team.slack.com/archives/C02U46QK5C3/p1683754866584499

Do a small investigation as to why the connector-builder-server in cloud stopped working briefly yesterday.

# Acceptance Criteria
1. (brief) write up of why the auth change impacted builder server
2. action items to remedy root cause

**Comment by brianjlai** [comment] 2023-05-12 01:07
## What Happened?
* On 5/10, the OC engineer was alerted that the /v1/health endpoint had not emitted a successful response for 5+ minutes. 
* The health of the system was checked and it was confirmed that the connector-builder-server running in production was handling any successful requests and there were no healthy instances that could receive traffic from the load balancer that handles builder traffic.
* The connector-builder-server-wrapped instances in the prod GKE cluster were marked as “Healthy”, although when making requests to the /v1/health endpoint, requests would hang or fail.
* From the Airbyte UI, requests to test manifests would fail with a 502 error from the ELB.

## Root Cause
* There was a refactor of various micronaut dependencies in https://github.com/airbytehq/airbyte-platform-internal/pull/6126 specifically the `cloud-auth` library.
* Currently all services share the same CloudAuthenticationProvider and with the latest refactor, the Stripe library and env arg became required for services using cloud-auth to start up successfully.
* The `connector-builder-server-wrapped` was missing the required library and env arg.
* Once they were added the server started up correctly.

## Action Items
Immediate fix for the Connector Builder Server
* Parker fixed the Connector Builder Server in Cloud w/ his Micronaut migration by adding the missing dependency to build.gradle in `airbyte-connector-builder-server-wrapped`.
* The `endpoint-secret: ${STRIPE_ENDPOINT_SECRET:}` was also added the the Micronaut app config.
* The medium term fix is that all services should not be sharing a single CloudAuthenticationProvider. The work for that will to be scoped after all services have been migrated over.

Implement liveness probe on Connector Builder Server on GKE
* We should have been able to catch this earlier in the testing process. However, the connector-builder-server-wrapped was incorrectly displaying pod state as “Healthy” because we did not implement readiness or liveness checks in the `deployment.yml`
* Brian to implement a liveness/readiness probe testing so prevent unhealthy pods from being marked “Healthy” within a cluster.

**Comment by girarda** [comment] 2023-05-17 16:47
@sherifnada I think there's something missing from the action items.

The health check wouldn't have detected the issue because the endpoint is not authenticated.

Did we not get notified on the 502 errors?

**Closed** 2023-05-17 18:34 UTC
Labels: team/extensibility

**Comment by brianjlai** [comment] 2023-05-17 18:42
I don't think we got notified because we alert on 5XX errors from the server, but the ELB fielding the requests erroring because no servers are available might not get captured in our dashboards. I'm just hypothesizing since I don't have the full extent of how Micronaut service is instrumeneted

**Comment by brianjlai** [comment] 2023-05-17 18:42
@girarda this auto closed when i merged the liveness check, if you still have open questions I can reopen
