### ISSUE TITLE
Shopify Connector Error: The source is unresponsive

### ISSUE THREAD

**Issue by lluisgassovillarejo** [airbytehq/airbyte#28604] opened 2023-07-24 10:22 UTC
### Connector Name

source-shopify

### Connector Version

0.5

### What step the error happened?

During the sync

### Revelant information

The connector starts well, but it throws a Failure Origin: source, Message: The source is unresponsive after synchronizing the customers' stream.
We are synchronizing customers, order_refunds, orders, and products.

### Relevant log output

```shell
2023-07-23 17:11:32 INFO i.a.w.t.TemporalAttemptExecution(get):136 - Docker volume job log path: /tmp/workspace/20231/2/logs.log
2023-07-23 17:11:32 INFO i.a.w.t.TemporalAttemptExecution(get):141 - Executing worker wrapper. Airbyte version: 0.44.5
2023-07-23 17:11:32 INFO i.a.a.c.AirbyteApiClient(retryWithJitterThrows):222 - Attempt 0 to save workflow id for cancellation
2023-07-23 17:11:32 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-07-23 17:11:32 INFO i.a.c.i.LineGobbler(voidCall):149 - ----- START CHECK -----
2023-07-23 17:11:32 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-07-23 17:11:32 INFO i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2023-07-23 17:11:32 INFO i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2023-07-23 17:11:32 INFO i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2023-07-23 17:11:32 INFO i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2023-07-23 17:11:32 INFO i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable LAUNCHDARKLY_KEY: ''
2023-07-23 17:11:32 INFO i.a.c.EnvConfigs(getEnvOrDefault):1222 - Using default value for environment variable FEATURE_FLAG_CLIENT: ''
2023-07-23 17:11:32 INFO i.a.c.i.LineGobbler(voidCall):149 - Checking if airbyte/source-shopify:0.5.0 exists...
2023-07-23 17:11:32 INFO i.a.c.i.LineGobbler(voidCall):149 - airbyte/source-shopify:0.5.0 was found locally.
2023-07-23 17:11:32 INFO i.a.w.p.DockerProcessFactory(create):139 - Creating docker container = source-shopify-check-20231-2-nhdtx with resources io.airbyte.config.ResourceRequirements@7772063f[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2023-07-23 17:11:32 INFO i.a.w.p.DockerProcessFactory(create):192 - Preparing command: docker run --rm --init -i -w /data/20231/2 --log-driver none --name source-shopify-check-20231-2-nhdtx --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-shopify:0.5.0 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e USE_STREAM_CAPABLE_STATE=true -e FIELD_SELECTION_WORKSPACES= -e WORKER_ENVIRONMENT=DOCKER -e AIRBYTE_ROLE= -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=2 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT= -e AIRBYTE_VERSION=0.44.5 -e WORKER_JOB_ID=20231 airbyte/source-shopify:0.5.0 check --config source_config.json
2023-07-23 17:11:32 INFO i.a.w.i.VersionedAirbyteStreamFactory(create):181 - Reading messages from protocol version 0.2.0
2023-07-23 17:11:34 INFO i.a.w.i.VersionedAirbyteStreamFactory(internalLog):317 - Check succeeded
2023-07-23 17:11:34 INFO i.a.w.g.DefaultCheckConnectionWorker(run):115 - Check connection job received output: io.airbyte.config.StandardCheckConnectionOutput@26bfd603[status=succeeded,message=<null>,additionalProperties={}]
2023-07-23 17:11:34 INFO i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-07-23 17:11:34 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-07-23 17:11:34 INFO i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by bazarnov** [comment] 2023-07-24 11:05
@lluisgassovillarejo Hello, could you please provide more details about your connection? Please share the Airbyte Cloud connection link in particular so we could check additional details. Thank you.

**Comment by Wolff-Lucas** [comment] 2023-07-27 14:27
I have the same issue with zendesk sync after airbyte upgrade to 50.11

**Comment by bazarnov** [comment] 2023-07-31 08:50
@Wolff-Lucas Nicely underlined, we'll check the issues on the platform side as well, thank you!

**Comment by bazarnov** [comment] 2023-08-10 10:08
Closing this for now, as far as there is no reply and no details from  @lluisgassovillarejo. The platform issues are not confirmed also. Probably it was a temp bug due to the platform changes.

**Closed by bazarnov** 2023-08-10 10:08 UTC
Labels: type/bug, area/connectors, community, needs-triage, team/connectors-python, autoteam

**Comment by bwattleworth8** [comment] 2024-01-25 21:56
I am having the same issue as posted above. Happy to share more details upon request.
