### ISSUE TITLE
Google Analytics sync not working.

### ISSUE THREAD

**Issue by dajkatal** [airbytehq/airbyte#4585] opened 2021-07-06 21:24 UTC
## Enviroment
- **Airbyte version**: 0.27.0-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Source Connector and version**: Google Analytics 0.2.6
- **Destination Connector and version**: Postgres 0.3.6
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior
*Tell us what happens.*

There are two issues. One is most likely already known, but the other I'm not quite sure. When I sync for Google Analytics, the log shows data is properly received by Airbyte from the Google APIs. However, it then runs into an issue writing that data to the database. Given the line in the log:

> 2021-07-06 09:24:08 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-06 09:24:08 mFactory(lambda$create$0):73 - 2021-07-06 09:24:08 r(voidCall):85 - Exception in thread “main” java.lang.IllegalArgumentException: Message contained record from a stream that was not in the catalog.

It seems Airbyte is receiving a type of data it is not expecting and then runs into an error because of that. 

When this error occurs, one of two things happen.
1) Airbyte continues making requests (Two days ago it kept making requests to Google for 20 minutes, and finished my daily quota)
2) It freezes and you need to manually press "cancel" for the sync.

Additionally, this is the more known error I think, Airbyte gets many errors like this:

> 2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:01 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

Which Google still counts as a request, but Airbyte cannot use.

## Expected Behavior
*Tell us what should happen.*

The data from Google Analytics should be written into the database.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

2021-07-06 09:23:56 INFO () WorkerRun(call):62 - Executing worker wrapper. Airbyte version: 0.27.0-alpha
2021-07-06 09:23:56 INFO () TemporalAttemptExecution(get):110 - Executing worker wrapper. Airbyte version: 0.27.0-alpha
2021-07-06 09:23:56 INFO () DefaultReplicationWorker(run):102 - start sync worker. job id: 22 attempt id: 0
2021-07-06 09:23:56 INFO () DefaultReplicationWorker(run):111 - configured sync modes: {null.weekly_active_users=incremental - append}
2021-07-06 09:23:56 INFO () DefaultAirbyteDestination(start):78 - Running destination...
2021-07-06 09:23:56 INFO () LineGobbler(voidCall):85 - Checking if airbyte/destination-postgres:0.3.6 exists...
2021-07-06 09:23:56 INFO () LineGobbler(voidCall):85 - airbyte/destination-postgres:0.3.6 was found locally.
2021-07-06 09:23:56 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/22/0 --network host --log-driver none airbyte/destination-postgres:0.3.6 write --config destination_config.json --catalog destination_catalog.json
2021-07-06 09:23:56 INFO () LineGobbler(voidCall):85 - Checking if airbyte/source-googleanalytics-singer:0.2.6 exists...
2021-07-06 09:23:56 INFO () LineGobbler(voidCall):85 - airbyte/source-googleanalytics-singer:0.2.6 was found locally.
2021-07-06 09:23:56 INFO () DockerProcessFactory(create):146 - Preparing command: docker run --rm --init -i -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -w /data/22/0 --network host --log-driver none airbyte/source-googleanalytics-singer:0.2.6 read --config source_config.json --catalog source_catalog.json --state input_state.json
2021-07-06 09:23:56 INFO () DefaultReplicationWorker(run):139 - Waiting for source thread to join.
2021-07-06 09:23:56 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):207 - Replication thread started.
2021-07-06 09:23:56 INFO () DefaultReplicationWorker(lambda$getDestinationOutputRunnable$3):243 - Destination output thread started.
2021-07-06 09:23:57 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-06 09:23:57 b.IntegrationRunner(run):83 - {} - Integration config: IntegrationConfig{command=WRITE, configPath='destination_config.json', catalogPath='destination_catalog.json', statePath='null'}
2021-07-06 09:23:57 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-06 09:23:57 e_raw_ga_weekly_active_users
2021-07-06 09:23:57 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-06 09:23:57 () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:23:58 name=oauth2client.transport level=INFO message=Attempting refresh to obtain initial access_token
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:23:58 name=oauth2client.client level=INFO message=Refreshing access_token
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:23:59 name=googleapiclient.discovery level=INFO message=URL being requested: GET https://www.googleapis.com/discovery/v1/apis/analyticsreporting/v4/rest
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:23:59 name=googleapiclient.discovery level=INFO message=URL being requested: GET https://www.googleapis.com/discovery/v1/apis/analytics/v3/rest
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:00 name=googleapiclient.discovery level=INFO message=URL being requested: GET https://analytics.googleapis.com/analytics/v3/metadata/ga/columns?alt=json
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:00 name=oauth2client.transport level=INFO message=Attempting refresh to obtain initial access_token
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:00 name=oauth2client.client level=INFO message=Refreshing access_token
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:01 name=tap_google_analytics level=INFO message=Syncing stream: website_overview
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:01 name=tap_google_analytics level=INFO message=Sending request for 2021-07-01
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:01 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:01 name=tap_google_analytics level=INFO message=Sending request for 2021-07-02
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:01 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:02 name=tap_google_analytics level=INFO message=Sending request for 2021-07-03
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:02 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:02 name=tap_google_analytics level=INFO message=Sending request for 2021-07-04
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:02 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:02 name=tap_google_analytics level=INFO message=Sending request for 2021-07-05
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:02 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:03 name=tap_google_analytics level=INFO message=Syncing stream: traffic_sources
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:03 name=tap_google_analytics level=INFO message=Sending request for 2021-07-01
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:03 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:04 name=tap_google_analytics level=INFO message=Sending request for 2021-07-02
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:04 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:04 name=tap_google_analytics level=INFO message=Sending request for 2021-07-03
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:04 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:04 name=tap_google_analytics level=INFO message=Sending request for 2021-07-04
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:04 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:05 name=tap_google_analytics level=INFO message=Sending request for 2021-07-05
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:05 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:05 name=tap_google_analytics level=INFO message=Syncing stream: pages
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:05 name=tap_google_analytics level=INFO message=Sending request for 2021-07-01
2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:05 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:07 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:06 name=tap_google_analytics level=INFO message=Sending request for 2021-07-02
2021-07-06 09:24:07 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:06 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:07 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:06 name=tap_google_analytics level=INFO message=Sending request for 2021-07-03
2021-07-06 09:24:07 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:06 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:07 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:07 name=tap_google_analytics level=INFO message=Sending request for 2021-07-04
2021-07-06 09:24:07 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:07 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:07 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:07 name=tap_google_analytics level=INFO message=Sending request for 2021-07-05
2021-07-06 09:24:07 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:07 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:07 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:07 name=tap_google_analytics level=INFO message=Syncing stream: locations
2021-07-06 09:24:07 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:07 name=tap_google_analytics level=INFO message=Sending request for 2021-07-01
2021-07-06 09:24:07 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:07 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:08 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-06 09:24:08 mFactory(lambda$create$0):73 - 2021-07-06 09:24:08 r(voidCall):85 - Exception in thread "main" java.lang.IllegalArgumentException: Message contained record from a stream that was not in the catalog.
2021-07-06 09:24:08 ERROR () LineGobbler(voidCall):85 - catalog: {"streams":[{"stream":{"name":"ga_weekly_active_users","json_schema":{"type":["null","object"],"properties":{"ga_date":{"type":["string"]},"ga_7dayUsers":{"type":["null","integer"]},"report_end_date":{"type":["string"]},"report_start_date":{"type":["string"]}},"additionalProperties":false},"supported_sync_modes":["incremental"],"source_defined_cursor":true,"default_cursor_field":[],"source_defined_primary_key":[]},"sync_mode":"incremental","cursor_field":[],"destination_sync_mode":"append","primary_key":[]}]} ,
2021-07-06 09:24:08 ERROR () LineGobbler(voidCall):85 - message: {"type":"RECORD","record":{"stream":"ga_website_overview","data":{"ga_date":"20210701","ga_users":23,"ga_newUsers":20,"ga_sessions":24,"ga_sessionsPerUser":1.0434782608695652,"ga_avgSessionDuration":10.416666666666666,"ga_pageviews":32,"ga_pageviewsPerSession":1.3333333333333333,"ga_avgTimeOnPage":31.5,"ga_bounceRate":79.16666666666666,"ga_exitRate":75.0,"report_start_date":"2021-07-01","report_end_date":"2021-07-01"},"emitted_at":1625563443000}}
2021-07-06 09:24:08 ERROR () LineGobbler(voidCall):85 - at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.throwUnrecognizedStream(BufferedStreamConsumer.java:175)
2021-07-06 09:24:08 ERROR () LineGobbler(voidCall):85 - at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.acceptTracked(BufferedStreamConsumer.java:135)
2021-07-06 09:24:08 ERROR () LineGobbler(voidCall):85 - at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.accept(FailureTrackingAirbyteMessageConsumer.java:66)
2021-07-06 09:24:08 ERROR () LineGobbler(voidCall):85 - at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:132)
2021-07-06 09:24:08 ERROR () LineGobbler(voidCall):85 - at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:113)
2021-07-06 09:24:08 ERROR () LineGobbler(voidCall):85 - at io.airbyte.integrations.destination.postgres.PostgresDestination.main(PostgresDestination.java:84)
2021-07-06 09:24:10 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:08 name=tap_google_analytics level=INFO message=Sending request for 2021-07-02
2021-07-06 09:24:10 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:08 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:10 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:08 name=tap_google_analytics level=INFO message=Sending request for 2021-07-03
2021-07-06 09:24:10 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:08 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:10 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:09 name=tap_google_analytics level=INFO message=Sending request for 2021-07-04
2021-07-06 09:24:10 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:09 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json
2021-07-06 09:24:10 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:09 name=tap_google_analytics level=INFO message=Sending request for 2021-07-05
2021-07-06 09:24:10 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:09 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json


```

</details>

## Steps to Reproduce
1. Make Google Analytics source using Credentials JSON from Service account with Google Analytics API and Google Analytics Report API. (The service account was made from the same account with admin privileges on Google Analytics)
2. Share Google Analytics with the Service Account.
3. Sync Google Analytics.

## Are you willing to submit a PR?
At the moment, no.

**Comment by marcosmarxm** [comment] 2021-07-07 02:56
>2021-07-06 09:24:05 ERROR () DefaultAirbyteStreamFactory(internalLog):108 - time=2021-07-06 09:24:01 name=googleapiclient.discovery level=INFO message=URL being requested: POST https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json

Is something that is strange because the actual log level is INFO, there is issue to discovery the cause of that.

**Comment by marcosmarxm** [comment] 2021-07-07 02:58
>2021-07-06 09:24:08 INFO () DefaultAirbyteStreamFactory(lambda$create$0):73 - 2021-07-06 09:24:08 mFactory(lambda$create$0):73 - 2021-07-06 09:24:08 r(voidCall):85 - Exception in thread “main” java.lang.IllegalArgumentException: Message contained record from a stream that was not in the catalog.

@sherifnada should this only a modification in the `configured_catalog` or could be more complex? Is possible to address to the connector team?

**Comment by dajkatal** [comment] 2021-07-07 07:39
I was able to get Google Analytics working using the source version 0.1.9. However, it only works when all source schemas are enabled. If I want to get data for something specific, like traffic_sources, it would run into the same error as shown in the log.

**Comment by sherifnada** [comment] 2021-09-03 03:20
this is fixed in the latest google analytics connector.

**Closed by sherifnada** 2021-09-03 03:20 UTC
Labels: type/bug, area/connectors
