### ISSUE TITLE
Updating streams on UI silently fails

### ISSUE THREAD

**Issue by mariusz89016** [airbytehq/airbyte#14460] opened 2022-07-06 17:20 UTC
## Environment
- **Airbyte version**:  0.39.31-alpha (and verified locally on 0.39.34-alpha)
- **Deployment**: Kubernetes deploy
- **Step where error happened**: Updating streams on UI by clicking `Refresh source schema`

## Current Behavior
In webapp, on connection settings, on replication tab when clicking `Refresh source schema` it silently fails. Thrown exception is like this:
```
Duplicate key [Labels] (attempted merging values {"type":"array","items":{"type":"object","properties":{"Id":{"type":"integer","format":"int32"}}}} and {"type":"object","properties":{"Id":{"type":"integer","format":"int32"}}})
...
```
(example schema below)

Digging a little bit more I found that problem is in logic diffing streams: `CatalogHelpers.getStreamDiff` (in `airbyte-protocol` module) calls `getFullyQualifiedFieldNamesWithTypes` which returns duplicated entries and it fails few lines later on when collecting stream to map.

Minimal schema to reproduce should contain array, e.g.:
```
{
  "type": "object",
  "title": "invoices",
  "properties": {
    "qwerty": {
      "type": "string"
    },
    "Labels": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Id": {
            "type": "integer",
            "format": "int32"
          }
        }
      }
    }
  }
}
```

## Expected Behavior
Logic for diffing streams should not fail on arrays.
Also this issue seems connected to: https://github.com/airbytehq/airbyte/issues/14096

## Are you willing to submit a PR?
With some tips - yes ;)

**Comment by grishick** [comment] 2022-07-13 21:47
@harshithmullapudi not sure why you tagged this with team/connectors-java. This seems like a platform issue to me. Tagging with team/oss, but feel free to ping me on Slack if you disagree or if I am missing some context.
cc: @evantahler

**Comment by evantahler** [comment] 2022-07-13 22:44
@mariusz89016 Can you share a little more information about your source - which connector and version are you using.  If it's a database source, can you share your schema in full?  Thanks!

**Comment by mariusz89016** [comment] 2022-07-15 10:02
We're developing a custom connector using Python CDK in version `0.1.62` - it's not published yet so I'd rather not share that schema for now BUT I found a way to reproduce that error with E2E testing source instead:
* create E2E testing source: 
  * Mock catalog: Single Schema
  * Stream Schema:
```
{
  "type": "object",
  "title": "invoices",
  "properties": {
    "qwerty": {
      "type": "string"
    }
  }
}
```
* create any connection (to create streams catalog)
* update Stream Schema in E2E testing source to:
```
{
  "type": "object",
  "title": "invoices",
  "properties": {
    "qwerty": {
      "type": "string"
    },
    "Labels": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Id": {
            "type": "integer",
            "format": "int32"
          }
        }
      }
    }
  }
}
```
* refresh source schema in the connection -> error should be visible in a web browser developer tools (networking tab)

**Comment by evantahler** [comment] 2022-07-15 20:23
Thanks @mariusz89016! I'll assign this to our front-end team to take a look

**Comment by octavia-squidington-iii** [comment] 2022-07-15 20:23
cc @airbytehq/frontend

**Comment by timroes** [comment] 2022-07-17 15:01
Duplicate of https://github.com/airbytehq/airbyte/issues/14096

**Closed by timroes** 2022-07-17 15:01 UTC
Labels: type/bug, community, team/frontend
