### ISSUE TITLE
Discover schema fails when databases have too many tables.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#3943] opened 2021-06-08 08:27 UTC
## Expected Behavior
The discover schema operation should return the entire catalog.

## Current Behavior
If a database has more than 10k tables, discover schema fails with the following Temporal error:
```
airbyte-scheduler   | 2021-06-08 08:11:11 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):73 - {job_id=3a72511e-be63-4e59-affc-d5cf7269f694, job_log_filename=logs.log, job_root=/tmp/workspace/3a72511e-be63-4e59-affc-d5cf7269f694/0} - 2021-06-08 08:11:11 INFO i.a.i.s.p.PostgresSource(isCdc):277 - {} - using CDC: false
airbyte-scheduler   | 2021-06-08 08:11:11 INFO i.a.w.t.TemporalAttemptExecution(get):134 - {ActivityId=f7a8ae81-575b-313b-8971-509760dca3d5, ActivityType=Run, Namespace=default, RunId=1581f0a1-56b5-44c0-9212-daaccd6bac9c, TaskQueue=DISCOVER_SCHEMA, WorkflowId=f5151b46-037b-4cbb-b190-62fb9f148dca, job_id=3a72511e-be63-4e59-affc-d5cf7269f694, job_log_filename=logs.log, job_root=/tmp/workspace/3a72511e-be63-4e59-affc-d5cf7269f694/0} - Stopping cancellation check scheduling...
airbyte-server      | 2021-06-08 08:11:12 INFO i.a.s.RequestLogger(filter):107 - {workspace_app_root=/tmp/workspace/server/logs} - REQ 172.26.0.1 POST 200 /api/v1/sources/discover_schema - {"destinationDefinitionId":"a625d593-bba5-4a1c-a53d-2d246268a816"}
airbyte-scheduler   | 2021-06-08 08:11:14 WARN i.t.i.c.GrpcRetryer(retryWithResult):152 - {ActivityId=eb490354-3461-3c6e-8973-87516c725a2c, ActivityType=Run, Namespace=default, RunId=231b218a-e8c6-4db7-93e1-aac0f9aa05d1, TaskQueue=DISCOVER_SCHEMA, WorkflowId=ddbcdbf9-d7a6-4a8b-aa02-e28e0df017c6, job_id=ab868a89-9bda-44ca-9328-e2d7d33cd61f, job_log_filename=logs.log, job_root=/tmp/workspace/ab868a89-9bda-44ca-9328-e2d7d33cd61f/0} - Retrying after failure
airbyte-scheduler   | io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: grpc: received message larger than max (4394339 vs. 4194304)
airbyte-scheduler   | 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.34.1.jar:1.34.1]
airbyte-scheduler   | 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[grpc-stub-1.34.1.jar:1.34.1]
airbyte-scheduler   | 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.34.1.jar:1.34.1]
airbyte-scheduler   | 	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.respondActivityTaskCompleted(WorkflowServiceGrpc.java:2740) ~[temporal-serviceclient-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.lambda$sendReply$0(ActivityWorker.java:281) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.common.GrpcRetryer.lambda$retry$0(GrpcRetryer.java:109) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.common.GrpcRetryer.retryWithResult(GrpcRetryer.java:127) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.common.GrpcRetryer.retry(GrpcRetryer.java:106) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.sendReply(ActivityWorker.java:275) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:196) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
airbyte-scheduler   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
airbyte-scheduler   | 	at java.lang.Thread.run(Thread.java:832) [?:?]
airbyte-scheduler   | 2021-06-08 08:11:14 INFO i.a.s.a.JobRetrier(run):58 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Running Job Retrier...
airbyte-scheduler   | 2021-06-08 08:11:14 INFO i.a.s.a.JobRetrier(run):74 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Completed Job Retrier...
airbyte-scheduler   | 2021-06-08 08:11:14 INFO i.a.s.a.JobRetrier(run):75 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Job Retrier Summary. Incomplete jobs: 0, Job set to retry: 0, Jobs set to failed: 0
airbyte-scheduler   | 2021-06-08 08:11:14 INFO i.a.s.a.JobScheduler(run):80 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Running job-scheduler...
airbyte-scheduler   | 2021-06-08 08:11:14 INFO i.a.s.a.JobScheduler(scheduleSyncJobs):101 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Job-Scheduler Summary. Active connections: 1, Jobs scheduler: 0
airbyte-scheduler   | 2021-06-08 08:11:14 INFO i.a.s.a.JobScheduler(run):84 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Completed Job-Scheduler...
airbyte-scheduler   | 2021-06-08 08:11:14 INFO i.a.s.a.JobSubmitter(run):66 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Running job-submitter...
airbyte-scheduler   | 2021-06-08 08:11:14 INFO i.a.s.a.JobSubmitter(run):76 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Completed Job-Submitter...
airbyte-scheduler   | 2021-06-08 08:11:19 INFO i.a.s.a.JobRetrier(run):58 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Running Job Retrier...
airbyte-scheduler   | 2021-06-08 08:11:19 INFO i.a.s.a.JobRetrier(run):74 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Completed Job Retrier...
airbyte-scheduler   | 2021-06-08 08:11:19 INFO i.a.s.a.JobRetrier(run):75 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Job Retrier Summary. Incomplete jobs: 0, Job set to retry: 0, Jobs set to failed: 0
airbyte-scheduler   | 2021-06-08 08:11:19 INFO i.a.s.a.JobScheduler(run):80 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Running job-scheduler...
airbyte-scheduler   | 2021-06-08 08:11:19 INFO i.a.s.a.JobScheduler(scheduleSyncJobs):101 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Job-Scheduler Summary. Active connections: 1, Jobs scheduler: 0
airbyte-scheduler   | 2021-06-08 08:11:19 INFO i.a.s.a.JobScheduler(run):84 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Completed Job-Scheduler...
airbyte-scheduler   | 2021-06-08 08:11:19 INFO i.a.s.a.JobSubmitter(run):66 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Running job-submitter...
airbyte-scheduler   | 2021-06-08 08:11:19 INFO i.a.s.a.JobSubmitter(run):76 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Completed Job-Submitter...
airbyte-scheduler   | 2021-06-08 08:11:20 WARN i.t.i.c.GrpcRetryer(retryWithResult):152 - {ActivityId=eb490354-3461-3c6e-8973-87516c725a2c, ActivityType=Run, Namespace=default, RunId=231b218a-e8c6-4db7-93e1-aac0f9aa05d1, TaskQueue=DISCOVER_SCHEMA, WorkflowId=ddbcdbf9-d7a6-4a8b-aa02-e28e0df017c6, job_id=ab868a89-9bda-44ca-9328-e2d7d33cd61f, job_log_filename=logs.log, job_root=/tmp/workspace/ab868a89-9bda-44ca-9328-e2d7d33cd61f/0} - Retrying after failure
airbyte-scheduler   | io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: grpc: received message larger than max (4394339 vs. 4194304)
airbyte-scheduler   | 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.34.1.jar:1.34.1]
airbyte-scheduler   | 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[grpc-stub-1.34.1.jar:1.34.1]
airbyte-scheduler   | 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.34.1.jar:1.34.1]
airbyte-scheduler   | 	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.respondActivityTaskCompleted(WorkflowServiceGrpc.java:2740) ~[temporal-serviceclient-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.lambda$sendReply$0(ActivityWorker.java:281) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.common.GrpcRetryer.lambda$retry$0(GrpcRetryer.java:109) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.common.GrpcRetryer.retryWithResult(GrpcRetryer.java:127) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.common.GrpcRetryer.retry(GrpcRetryer.java:106) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.sendReply(ActivityWorker.java:275) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:196) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
airbyte-scheduler   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
airbyte-scheduler   | 	at java.lang.Thread.run(Thread.java:832) [?:?]
airbyte-scheduler   | 2021-06-08 08:11:24 INFO i.a.s.a.JobRetrier(run):58 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Running Job Retrier...
airbyte-scheduler   | 2021-06-08 08:11:24 INFO i.a.s.a.JobRetrier(run):74 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Completed Job Retrier...
airbyte-scheduler   | 2021-06-08 08:11:24 INFO i.a.s.a.JobRetrier(run):75 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Job Retrier Summary. Incomplete jobs: 0, Job set to retry: 0, Jobs set to failed: 0
airbyte-scheduler   | 2021-06-08 08:11:24 INFO i.a.s.a.JobScheduler(run):80 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Running job-scheduler...
airbyte-scheduler   | 2021-06-08 08:11:24 INFO i.a.s.a.JobScheduler(scheduleSyncJobs):101 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Job-Scheduler Summary. Active connections: 1, Jobs scheduler: 0
airbyte-scheduler   | 2021-06-08 08:11:24 INFO i.a.s.a.JobScheduler(run):84 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Completed Job-Scheduler...
airbyte-scheduler   | 2021-06-08 08:11:24 INFO i.a.s.a.JobSubmitter(run):66 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Running job-submitter...
airbyte-scheduler   | 2021-06-08 08:11:24 INFO i.a.s.a.JobSubmitter(run):76 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Completed Job-Submitter...
airbyte-scheduler   | 2021-06-08 08:11:26 WARN i.t.i.c.GrpcRetryer(retryWithResult):152 - {ActivityId=eb490354-3461-3c6e-8973-87516c725a2c, ActivityType=Run, Namespace=default, RunId=231b218a-e8c6-4db7-93e1-aac0f9aa05d1, TaskQueue=DISCOVER_SCHEMA, WorkflowId=ddbcdbf9-d7a6-4a8b-aa02-e28e0df017c6, job_id=ab868a89-9bda-44ca-9328-e2d7d33cd61f, job_log_filename=logs.log, job_root=/tmp/workspace/ab868a89-9bda-44ca-9328-e2d7d33cd61f/0} - Retrying after failure
airbyte-scheduler   | io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: grpc: received message larger than max (4394339 vs. 4194304)
airbyte-scheduler   | 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.34.1.jar:1.34.1]
airbyte-scheduler   | 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[grpc-stub-1.34.1.jar:1.34.1]
airbyte-scheduler   | 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.34.1.jar:1.34.1]
airbyte-scheduler   | 	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.respondActivityTaskCompleted(WorkflowServiceGrpc.java:2740) ~[temporal-serviceclient-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.lambda$sendReply$0(ActivityWorker.java:281) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.common.GrpcRetryer.lambda$retry$0(GrpcRetryer.java:109) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.common.GrpcRetryer.retryWithResult(GrpcRetryer.java:127) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.common.GrpcRetryer.retry(GrpcRetryer.java:106) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.sendReply(ActivityWorker.java:275) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:196) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
airbyte-scheduler   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
airbyte-scheduler   | 	at java.lang.Thread.run(Thread.java:832) [?:?]
airbyte-scheduler   | 2021-06-08 08:11:29 INFO i.a.s.a.JobRetrier(run):58 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Running Job Retrier...
airbyte-scheduler   | 2021-06-08 08:11:29 INFO i.a.s.a.JobRetrier(run):74 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Completed Job Retrier...
airbyte-scheduler   | 2021-06-08 08:11:29 INFO i.a.s.a.JobRetrier(run):75 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Job Retrier Summary. Incomplete jobs: 0, Job set to retry: 0, Jobs set to failed: 0
airbyte-scheduler   | 2021-06-08 08:11:29 INFO i.a.s.a.JobScheduler(run):80 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Running job-scheduler...
airbyte-scheduler   | 2021-06-08 08:11:29 INFO i.a.s.a.JobScheduler(scheduleSyncJobs):101 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Job-Scheduler Summary. Active connections: 1, Jobs scheduler: 0
airbyte-scheduler   | 2021-06-08 08:11:29 INFO i.a.s.a.JobScheduler(run):84 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Completed Job-Scheduler...
airbyte-scheduler   | 2021-06-08 08:11:29 INFO i.a.s.a.JobSubmitter(run):66 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Running job-submitter...
airbyte-scheduler   | 2021-06-08 08:11:29 INFO i.a.s.a.JobSubmitter(run):76 - {workspace_app_root=/tmp/workspace/scheduler/logs} - Completed Job-Submitter...
airbyte-scheduler   | 2021-06-08 08:11:32 ERROR i.t.i.w.PollerOptions$Builder(lambda$build$0):138 - {Namespace=default, TaskQueue=DISCOVER_SCHEMA, job_id=ab868a89-9bda-44ca-9328-e2d7d33cd61f, job_log_filename=logs.log, job_root=/tmp/workspace/ab868a89-9bda-44ca-9328-e2d7d33cd61f/0} - uncaught exception
airbyte-scheduler   | java.lang.RuntimeException: Failure processing activity response. WorkflowId=ddbcdbf9-d7a6-4a8b-aa02-e28e0df017c6, RunId=231b218a-e8c6-4db7-93e1-aac0f9aa05d1, ActivityType=Run, ActivityId=eb490354-3461-3c6e-8973-87516c725a2c
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.wrapFailure(ActivityWorker.java:256) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.wrapFailure(ActivityWorker.java:154) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:79) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
airbyte-scheduler   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
airbyte-scheduler   | 	at java.lang.Thread.run(Thread.java:832) [?:?]
airbyte-scheduler   | Caused by: io.grpc.StatusRuntimeException: RESOURCE_EXHAUSTED: grpc: received message larger than max (4394339 vs. 4194304)
airbyte-scheduler   | 	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:262) ~[grpc-stub-1.34.1.jar:1.34.1]
airbyte-scheduler   | 	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:243) ~[grpc-stub-1.34.1.jar:1.34.1]
airbyte-scheduler   | 	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:156) ~[grpc-stub-1.34.1.jar:1.34.1]
airbyte-scheduler   | 	at io.temporal.api.workflowservice.v1.WorkflowServiceGrpc$WorkflowServiceBlockingStub.respondActivityTaskCompleted(WorkflowServiceGrpc.java:2740) ~[temporal-serviceclient-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.lambda$sendReply$0(ActivityWorker.java:281) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.common.GrpcRetryer.lambda$retry$0(GrpcRetryer.java:109) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.common.GrpcRetryer.retryWithResult(GrpcRetryer.java:127) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.common.GrpcRetryer.retry(GrpcRetryer.java:106) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.sendReply(ActivityWorker.java:275) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:196) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   | 	... 3 more
```

## Steps to Reproduce
Run discover on a database with more than 10k tables.

## Severity of the bug for you
 Low

**Comment by mcfuhrt** [comment] 2021-08-06 11:25
Hi,
we have connected our Dynamics NAV system to Airbyte and we cannot retrieve the schema and get the same error of exhausted resources.

We deleted several clients from our NAV database and then were able to retrieve all schema successfully, but of course this is not possible in practice. Is there anything we can do? Maybe allocate more RAM to the machine? We also noticed that the page responds very slowly and sluggishly when all tables are displayed in the UI.
[excerpt_error_log.txt](https://github.com/airbytehq/airbyte/files/6945187/excerpt_error_log.txt)

**Comment by marcosmarxm** [comment] 2021-08-20 00:44
@vitoravancini is possible to you share what did you change in temporal timeout to overcome the problem reading 1k+ tables in Redshift?

**Comment by aizenshtat** [comment] 2021-09-04 05:04
Hello, we have the same problem with Dynamics and it very critical for us. Here are all the details: [Slack Thread](https://airbytehq.slack.com/archives/C01MFR03D5W/p1629382834392400?thread_ts=1629382834.392400&cid=C01MFR03D5W)

**Comment by vitoravancini** [comment] 2021-09-04 14:48
Hello everyone,  Im on my phone right now só I wont be able to show examples, but what I've done was to change the temporal dynamic config. 

I was deploying using docker compose, and in the compose file there is a volume for the temporal config, ive edited this temporal config file and restarted the containers.

I cant tell how this can impact the temporal system.

**Comment by vitoravancini** [comment] 2021-09-04 14:52
This is the file I have edited:

https://github.com/airbytehq/airbyte/blob/master/temporal/dynamicconfig/development.yaml

Changed the limit.blobSize.error size.

Hope it helps.

**Comment by ramamohank** [comment] 2021-09-21 12:46
I increased these and not helped 

# Limit for responses. This mostly impacts discovery jobs since they have the largest responses.
limit.blobSize.error:
  - value: 15728640 # 15MB
    constraints: {}
limit.blobSize.warn:
  - value: 10485760 # 10MB

**Comment by alvaroqueiroz** [comment] 2022-01-25 20:34
i have also experienced this problem with 4.100 tables in a mssql source.
![image](https://user-images.githubusercontent.com/23335136/151055212-2202534a-ae6a-4334-8e70-1abf487846ed.png)

**Comment by saheemsiddiqi** [comment] 2022-03-22 01:19
This seems to be a hard-coded value in Temporal.  The limit.blogSize.error value doesn't seem to have an impact.  Note that in my particular case, the error occurs after this log-line:

[[33;1mairbyte-worker      |^[[0m 2022-03-22 00:55:31 ^[[32mINFO^[[m i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-03-22 00:55:28 ^[[32mINFO^[[m i.a.i.s.j.AbstractJdbcSource(discoverPrimaryKeys):209 - Discover primary keys for tables: [...]


See [this](https://community.temporal.io/t/resource-exhausted-received-message-larger-than-max-4853862-vs-4194304/1165).

**Comment by brunofaustino** [comment] 2022-06-06 22:23
We had the same problem.

In our case, it would not be possible to change or create a new schema in the source database, and only a few tables would need to be loaded.
So we limit the database user for him to have access only the tables that would be loaded in Airbyte.

It is a possible solution to the specific case where there are many tables on the source database, but only a few need to be loaded.

**Comment by Toumaske** [comment] 2022-06-17 07:19
We still have this problem. 

@joowoo can you maybe explain how one would use namespaces to reduce tables (Implementation) ? did you follow a tutorial?

**Comment by marcosmarxm** [comment] 2022-06-21 11:33
> 

@Amruta-Ranade maybe this is a valuable comment to add in out source database documentation until Airbyte have a way to fix this issue.

**Comment by Amruta-Ranade** [comment] 2022-06-21 14:58
@marcosmarxm DMing you on Slack to understand the issue/solution.

**Comment by evantahler** [comment] 2022-08-01 23:30
This is a duplicate of https://github.com/airbytehq/airbyte/issues/4564.  I'm closing this issue in favor of https://github.com/airbytehq/airbyte/issues/4564

**Closed by evantahler** 2022-08-01 23:30 UTC
Labels: type/bug, priority/high, temporal, team/oss, platform-workflow/service
