### ISSUE TITLE
[Low-Code CDK] All low-code components should always have type defined on them

### ISSUE THREAD

**Issue by brianjlai** [airbytehq/airbyte#22849] opened 2023-02-10 22:48 UTC
## Tell us about the problem you're trying to solve

When we first released the alpha of the low-code framework, we added an additional transformation layer that would hydrate components with `type` if it was missing and we could reasonably infer the type based on the name of the parent's field. This made the YAML editing experience better, but is problematic because this deviates from our documented schema `declarative_component_schema.yaml` which explicitly requires a type. We've continued to maintain this transformer on the backend, but also still serves as an aspect of where the connector builder frontend deviates from the backend. The frontend is already generating manifests where all components have `type`.

## Describe the solution you’d like
We should move away from this halfway state where we continue to support manifests where `type` is not defined on every component. We should do the following to move us to a world where all manifest components are typed:

- Go through all existing manifests and add the relevant type if it is not present
- In `manifest_component_transformer.py`, remove the `DEFAULT_MODEL_TYPES` and `CUSTOM_COMPONENTS_MAPPING` so we don't need them while propagating

The templates should already have types added in order to encourage developers to always include types

## Acceptance Criteria
- [ ] All components have a `type` and all custom components have `type` + `class_name`
- [ ] The type hydration code has been removed from `manifest_component_transformer.py`
- [ ] Documentation and examples are updated to include components with `type`
- [ ] `./gradlew validateSourceYamlManifest` passes which should indicate that the manifest is correctly parsed

**Comment by girarda** [comment] 2023-04-17 21:33
closing as duplicate of https://github.com/airbytehq/airbyte/issues/23837

**Closed by girarda** 2023-04-17 21:33 UTC
Labels: team/extensibility
