### ISSUE TITLE
Update ci to use dev versoin of airbyte-ci when pipeline is edited

### ISSUE THREAD

**Issue by bnchrch** [airbytehq/airbyte#33418] opened 2023-12-13 14:00 UTC
## Problem
We cant test pipeline changes in our branch

## Solution 
Wait for a dev release to build and install that instead of latest

**Comment by evantahler** [comment] 2023-12-13 18:33
This is a duplicate of https://github.com/airbytehq/airbyte/issues/32947 - there's some more details here

**Closed** 2023-12-20 17:03 UTC
Labels: team/connector-ops
