### ISSUE TITLE
[Duplicate] Change Overlay component background color to match design

### ISSUE THREAD

**Issue by edmundito** [airbytehq/airbyte#20476] opened 2022-12-14 14:39 UTC
Update the Overlay component background to `dark-blue` 50% to match what's currently in the designs.

**Comment by octavia-squidington-iv** [comment] 2022-12-14 14:40
cc @airbytehq/frontend

**Comment by tealjulia** [comment] 2022-12-14 15:56
this is a duplicate of #20453

happy to close either

**Closed** 2022-12-19 15:20 UTC
Labels: area/frontend, team/platform-workflow, team/frontend, ui/components, platform-workflow/requires-grooming
