### ISSUE TITLE
Source Facebook: uses Invalid JSON Schema in video stream

### ISSUE THREAD

**Issue by dyaffe** [airbytehq/airbyte#8975] opened 2021-12-20 22:54 UTC
## Environment
- **Airbyte version**:  N/A
- **OS Version / Instance**: N/A
- **Deployment**: N/A
- **Source Connector and version**: Facebook 0.2.26
- **Destination Connector and version**: N/A
- **Severity**: Medium
- **Step where error happened**: This is present in Airbyte connectors and makes them incompatible with JSON schema

## Current Behavior
Facebook connectors have a few specific issues with JSON Schema validity.

1. The format section under [/videos](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/videos.json) is invalid (line 47).  It's missing type declarations:

    "format": {
      "type": ["null", "array"],
      "items": {
        "filter": "string",
        "embed_html": "string",
        "width": "integer",
        "height": "integer",
        "picture": "string"
      }

2. Top level objects on most Airbyte schema's are nullable and there's no valid use case for a connector to emit nulls.  Allowing Nulls at the top level hurts reliability.  [Here's](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-facebook-marketing/source_facebook_marketing/schemas/ad_creatives.json) an example (line 857).  

## Expected Behavior
Ideally all updates to connectors would be required to use valid JSON Schema to be accepted by Airbyte.  

## Logs
N/A

## Steps to Reproduce
1. Go to the above files

## Are you willing to submit a PR?
Yes, but issue (2) requires updates to the script that generates schemas and an overall fix to both of these would require more validation before schemas are accepted by Airbyte.

**Comment by marcosmarxm** [comment] 2021-12-21 23:03
Thanks for opening this issue @dyaffe. I added the issue in our roadmap. Did you have any problems using the connector to get data?

**Comment by avida** [comment] 2021-12-27 09:26
Looks like it meant to represent list of [VideoFormat](https://developers.facebook.com/docs/graph-api/reference/video-format/) objects, will update the schema.

Considering
> Top level objects on most Airbyte schema's are nullable and there's no valid use case for a connector to emit nulls. Allowing Nulls at the top level hurts reliability

Its was inspired by the singer facebook connector [schema](https://github.com/singer-io/tap-facebook/blob/master/tap_facebook/schemas/adcreative.json). We agreed that this is the best approach cause some fields on response object could be missed despite it not marked as optional in reference. Usually it happens on old sets of data and cannot be reproduced on fresh account.

**Closed** 2021-12-29 09:03 UTC
Labels: type/bug, area/connectors, community
