### ISSUE TITLE
MSSQL Destination Connector

### ISSUE THREAD

**Issue by satyampurwar** [airbytehq/airbyte#2434] opened 2021-03-12 10:16 UTC
## Tell us about the new integration you’d like to have
* Which source and which destination?

Please help in building the MSSQL Destination connector as the general documentation around building source connector is not guiding enough to build destination connectors.

* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

## Describe the context around this new integration
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

**Comment by satyampurwar** [comment] 2021-03-12 10:26
MSSQL - Source (I can see this)  >>> Extract
MSSQL - Destination (this is missing) >>> Load

**Comment by jrhizor** [comment] 2021-03-12 15:07
duplicate of https://github.com/airbytehq/airbyte/issues/613 ?

**Comment by sherifnada** [comment] 2021-03-13 02:42
@satyampurwar Let me look into what it would take to do MSSQL destination and get back to you soon.

**Comment by cgardens** [comment] 2021-05-17 20:37
closed by https://github.com/airbytehq/airbyte/pull/3195

**Closed by cgardens** 2021-05-17 20:37 UTC
Labels: area/integration, new-integration
