### ISSUE TITLE
Display favicons on the UI for connectors

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#744] opened 2020-10-29 19:00 UTC
## Tell us about the problem you're trying to solve
Connectors currently have a stock favicon displayed in the UI: 
<img width="331" alt="Screen Shot 2020-10-29 at 10 28 34 AM" src="https://user-images.githubusercontent.com/6246757/97619951-1a52cc00-19de-11eb-88ca-6999560d6b3f.png">

ideally the UI should display the correct favicon/logo for each integration. @Jamakase does this require any work on your part, or is it expected that the backend should completely supply this information?

**Comment by cgardens** [comment] 2020-12-19 02:45
duplicate of https://github.com/airbytehq/airbyte/issues?page=8&q=is%3Aissue+is%3Aopen

**Closed by cgardens** 2020-12-19 02:45 UTC
Labels: type/enhancement
