### ISSUE TITLE
source-postgres: `PostgresSourceStrictEncryptTest` are failing

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#24244] opened 2023-03-20 15:43 UTC
Multiple tests are failing locally when running source-postgres integration tests.
I'd love to understand why these tests are not failing in `/test` but are locally. This could be something related to Apple M1.
It's blocking me to make progress on the containerization of `integrationTest` Gradle run.

The following tests are failing:
<img width="857" alt="Screen Shot 2023-03-20 at 16 42 35" src="https://user-images.githubusercontent.com/5551758/226392473-87fb8bfc-7d87-48cc-99eb-bff9fc72150d.png">

[The full gradle scan ](https://scans.gradle.com/s/sp3ahq2wttwvo)

**Comment by rodireich** [comment] 2023-03-22 17:42
There is an issue with running integration tests on M1 macs.
![screen_shot_2022-08-23_at_11 20 16_am](https://user-images.githubusercontent.com/867491/226991828-262e9c48-d2c5-4de6-b9c6-750b04663098.png)
This is a trick @edgao taught me.

We should make the tests stable

**Comment by edgao** [comment] 2023-03-22 18:05
I thought we'd committed this to github :/ this is transparent to CI, so there's no reason not to have it pushed to master

**Comment by alafanechere** [comment] 2023-03-29 15:53
Thank you for your suggestion @edgao and @rodireich .
The problem is specific to a couple of tests interacting with the bastion container and using the HostPortResolver helper did not fix it.
Other tests, that are not using tunnels + bastion, are passing.

**Comment by rodireich** [comment] 2023-03-30 05:34
I see where the problem is @alafanechere 
To unblock yourself, you can copy or cherry-pick the code change in #24683.
The test giving you trouble, `PostgresSourceStrictEncryptTest` is going to pass on your mac as well as on CI.

I fully see where the problem is. I'll file an issue so we can look at it:
In a nutshell docker network behavior is different between macOS and the linux vm that is used in ci slash test command.
The fix is ensuring that the host and port used in test are correct on both.

Let me know if this is helping to unblock you or any other question.

**Comment by rodireich** [comment] 2023-03-30 05:39
@edgao The reason this fix is not always straightforward is that some tests explicitly need the _inner_ host:port of a container – that is the address inside docker.
While other tests need the explicit outer address - that is the address as seen on the host machine. `localhost:22` for example.
On CI both seem to be the same so no problem, but on Mac they are different, so the API we use to get that address need to return the correct one.

**Comment by rodireich** [comment] 2023-03-30 15:51
Consider the following test: `PostgresSourceStrictEncryptTest` → tunnel → db

From test code running on your host machine
to tunnel reachable at localhost:xxxx where xxxx maps to bastion's port 22
to db container reachable from bastion by inner docker network address, something like 172.0.4.2:5432.

that is the test in `PostgresSourceStrictEncryptTest.testSSlRequiredWithTunnelIfServerDoesNotSupportSSL()`

One linux I think inner and outer address are the same so there's no distinction and both APIs return the same address

**Closed** 2023-04-12 17:24 UTC
Labels: type/bug, needs-triage, connectors/source/postgres, team/db-dw-sources
