### ISSUE TITLE
MySQL (source) -> BigQuery (destination) - JSON schema validation failed.

### ISSUE THREAD

**Issue by jrmanes** [airbytehq/airbyte#11875] opened 2022-04-11 11:51 UTC
## Environment
- **Airbyte version**:  0.35.65-alpha (also tested: 0.35.56-alpha, 0.35.62-alpha)
- **OS Version / Instance**: Ubuntu - GCP Instance
- **Deployment**: docker-compose
- **Source Connector and version**: MySQL
- **Destination Connector and version**: BigQuery
- **Severity**:  High
- **Step where error happened**:  I can create the source and destination, the issue appears when I try to sync data

## Current Behavior
BigQuery configured with Loading method GCS Staging.
- [x] Credentials created
- [x] Permissions added to the Service Account
- [x] Bucket created
- [x] HMAC key/secret created
- [x] Credentials JSON created
- [x] Test connection

The connectivity seems to work, also from the source, I can see the tables when I go to the connections tab in the Replication part.
I tried with different approaches in the transformation part ` and Normalized tabular data` and I got the error in both.

## Expected Behavior
Start syncing data in the BigQuery

## Logs

With the configuration in the Replication tab, using `Raw data (JSON)`, I got this error:
It tries to use some S3 configuration, but it's not defined anywhere because I'm using GCS:
```
Exception in thread "main" com.amazonaws.services.s3.model.AmazonS3Exception: The provided security credentials are not valid. (Service: Amazon S3; Status Code: 403; Error Code: InvalidSecurity; Request ID: null; S3 Extended Request ID: null; Proxy: null), S3 Extended Request ID: null
```

With the configuration in the Replication tab, using `Normalized tabular data`, I got this error:
```
2022-04-11 11:28:11 INFO i.a.v.j.JsonSchemaValidator(test):56 - JSON schema validation failed. 
errors: $.credential: is not defined in the schema and the schema does not allow additional properties, $.part_size_mb: is not defined in the schema and the schema does not allow additional properties, $.gcs_bucket_name: is not defined in the schema and the schema does not allow additional properties, $.gcs_bucket_path: is not defined in the schema and the schema does not allow additional properties, $.keep_files_in_gcs-bucket: is not defined in the schema and the schema does not allow additional properties, $.method: must be a constant value Standard
```

## Are you willing to submit a PR?

Not yet.

**Comment by BlueStalker** [comment] 2022-05-11 04:18
Are this issues being resolved?

**Comment by ufou** [comment] 2022-05-11 08:45
Not as far as I can tell, I've updated to the latest version of airbyte and ensured the source and destination plugins are up to date but I still get the same errors

**Comment by jrmanes** [comment] 2022-05-11 10:02
not in my case... I still having the issue :/

**Comment by bendnorman** [comment] 2022-08-25 03:38
@jrmanes were you able to resolve this issue?

**Comment by fcatanzaro** [comment] 2022-08-31 14:15
Same issue.  Any news?

**Comment by marcosmarxm** [comment] 2022-11-30 19:59
I'm closing the issue because the error shared here doesn't correspond to the root cause. Please when you create an issue upload the complete log file instead of only posting a single line. Also sorry the delay to any feedback about the issue.

**Closed by marcosmarxm** 2022-11-30 19:59 UTC
Labels: type/bug, community, needs-triage, team/use, autoteam
