### ISSUE TITLE
Improve streams table performance with large number of streams

### ISSUE THREAD

**Issue by krishnaglick** [airbytehq/airbyte#21662] opened 2023-01-20 16:41 UTC
Measure and determine why the streams table is very slow to render sources with many streams (example Salesforce). Determine a solution and implement.

One solution to consider is to virtualize scrolling:

The streams table had some UI work done to re-surface it but behind the scenes it's still a bunch of flexbox.
It may be difficult to implement the virtual scrolling in the table without refactoring its bones to something like react-table but it would be a net performance increase.

**Comment by edmundito** [comment] 2023-02-03 15:10
The current state of the Salesforce connector:
https://www.loom.com/share/ce08dcb17cbc44648bf734868cf2ea69

**Comment by krishnaglick** [comment] 2023-02-10 14:29
Reopening as more performance improvements can still be made here.

**Comment by krishnaglick** [comment] 2023-02-10 14:30
This ticket is de-prioritized due to other, more important work for q1a. But the work here is still worth doing. This will likely be easier once we complete the latest round of new streams table work as well.

**Comment by josephkmh** [comment] 2023-06-09 08:44
We had more internal feedback about poor salesforce catalog performance here: https://airbytehq-team.slack.com/archives/C02U6CXJQFN/p1686268674237899

**Comment by josephkmh** [comment] 2023-06-09 09:05
Just did a quick test because I suspected that the yup validation schema was the cause of the performance issue. Turns out it's not - it takes around 30-40ms to validate all 800+ salesforces streams.

The performance bottleneck seems to be react rendering so many nodes. If you enable only a few streams, then click "Hide disabled streams", the performance gets dramatically better. This indicates that we just need to virtualize the streams list.

**Comment by josephkmh** [comment] 2023-07-31 16:41
This is also an issue in the stream panel when a single stream has many fields. Interacting with e.g. column selection is very slow: https://github.com/airbytehq/oncall/issues/2608

**Comment by tealjulia** [comment] 2023-10-16 14:40
Related PRs that will close this: 
https://github.com/airbytehq/airbyte-platform-internal/pull/9214 (adds virtualization to the table)
https://github.com/airbytehq/airbyte-platform-internal/pull/9203 (adjusts our main page styling so that the scrollbox is the window not the card)

**Comment by josephkmh** [comment] 2023-10-30 13:18
Closing this since https://github.com/airbytehq/airbyte-platform-internal/pull/9214 is merged! 9203 will just be a further enhancement

**Closed by josephkmh** 2023-10-30 13:18 UTC
Labels: team/platform-compose, area/frontend, ui/performance
