### ISSUE TITLE
MySQL - Snowflake Job gets stuck in running status

### ISSUE THREAD

**Issue by aniket-vh** [airbytehq/airbyte#9834] opened 2022-01-27 12:36 UTC
## Environment
- **Airbyte version**:  0.35.6-alpha
- **OS Version / Instance**: k8s
- **Deployment**: k8s
- **Source Connector and version**: MySQL 0.5.1
- **Destination Connector and version**: Snowflake 0.4.3
- **Severity**: Medium
- **Step where error happened**:  Sync job

## Current Behavior

Connection failing to fetch records from MySql to Snowflake. 
Working for a few tables, so jobs are getting completed. 
Other tables job is not getting completed. Stays in running status for other tabels.

## Expected Behavior
Job was expected to get completed in 10 min based on number of records. 

## Logs
Deployment 
```
Namespace                   Name                                              CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
data-engg-edge-poc      airbyte-minio-c86d4f4bc-7m8v2                     0 (0%)        0 (0%)      0 (0%)           0 (0%)         6d12h
data-engg-edge-poc      airbyte-pod-sweeper-66896c45b5-qtt9t              0 (0%)        0 (0%)      0 (0%)           0 (0%)         6d12h
data-engg-edge-poc      airbyte-postgresql-0                              250m (3%)     0 (0%)      256Mi (0%)       0 (0%)         6d12h
data-engg-edge-poc      airbyte-temporal-6767fb9596-fdrhn                 0 (0%)        0 (0%)      0 (0%)           0 (0%)         6d12h
data-engg-edge-poc      airbyte-webapp-79647b97d8-tx267                   1 (12%)       1 (12%)     512Mi (1%)       2Gi (6%)       6d12h
data-engg-edge-poc      airbyte-scheduler-6b4779b6bf-q7zmv                250m (3%)     300m (3%)   256Mi (0%)       1Gi (3%)       6d12h
data-engg-edge-poc      airbyte-server-64648cfb9c-nqfhp                   250m (3%)     600m (7%)   1Gi (3%)         2Gi (6%)       6d12h
data-engg-edge-poc      airbyte-worker-66f4d78cf-tbqrq                    1 (12%)       2 (25%)     2Gi (6%)         4Gi (13%)      5d2h
data-engg-edge-poc      airbyte-worker-66f4d78cf-wp8nv                    1 (12%)       2 (25%)     2Gi (6%)         4Gi (13%)      6d12h
data-engg-edge-poc      airbyte-worker-66f4d78cf-wp8nv                1 (12%)       2 (25%)     2Gi (6%)         4Gi (13%)      6d12h
data-engg-edge-poc      destination-snowflake-sync-114-0-npeus           0 (0%)        0 (0%)      100Mi (0%)       200Mi (0%)     61m
data-engg-edge-poc      destination-snowflake-sync-70-0-yfpaq       0 (0%)        0 (0%)      100Mi (0%)       200Mi (0%)     2d3h
```

Job log: 
```
2022-01-27 08:45:05 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 408000
2022-01-27 08:45:05 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 409000
2022-01-27 08:45:05 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 410000
2022-01-27 08:45:05 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 411000
2022-01-27 08:45:05 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 412000
2022-01-27 08:45:05 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 413000
2022-01-27 08:45:05 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 414000
2022-01-27 08:45:05 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 415000
2022-01-27 08:45:05 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 416000
2022-01-27 08:45:06 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 417000
2022-01-27 08:45:06 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 418000
2022-01-27 08:45:06 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 419000
2022-01-27 08:45:06 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 420000
2022-01-27 08:45:06 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 421000
2022-01-27 08:45:06 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 422000
2022-01-27 08:45:06 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 423000
2022-01-27 08:45:06 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 424000
2022-01-27 08:45:06 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 425000
2022-01-27 08:45:06 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 426000
2022-01-27 08:45:07 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 427000
2022-01-27 08:45:07 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 428000
2022-01-27 08:45:07 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 429000
2022-01-27 08:45:07 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 430000
2022-01-27 08:45:07 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 431000
2022-01-27 08:45:07 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 432000
2022-01-27 08:45:07 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 433000
2022-01-27 08:45:07 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 434000
2022-01-27 08:45:07 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 435000
2022-01-27 08:45:07 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 436000
2022-01-27 08:45:08 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 437000
2022-01-27 08:45:08 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 438000
2022-01-27 08:45:08 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 439000
2022-01-27 08:45:08 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 440000
2022-01-27 08:45:08 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 441000
2022-01-27 08:45:08 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 442000
2022-01-27 08:45:08 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 443000
2022-01-27 08:45:08 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 444000
2022-01-27 08:45:08 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 445000
2022-01-27 08:45:08 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 446000
2022-01-27 08:45:09 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 447000
2022-01-27 08:45:09 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 448000
2022-01-27 08:45:09 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 449000
2022-01-27 08:45:09 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 450000
2022-01-27 08:45:09 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 451000
2022-01-27 08:45:09 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$3):251 - Records read: 452000
2022-01-27 08:45:09 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-01-27 08:45:01 INFO i.a.i.s.r.AbstractDbSource(lambda$createReadIterator$7):249 - {} - Reading stream user_gender. Records read: 160000
```
No logs after this. Job was cancelled manually after 1 hours. 
```
	at io.airbyte.workers.protocols.airbyte.DefaultAirbyteDestination.close(DefaultAirbyteDestination.java:111) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:139) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.run(DefaultReplicationWorker.java:52) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:174) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
2022-01-27 10:03:36 WARN i.t.i.s.POJOActivityTaskHandler(activityFailureToResult):363 - Activity failure. ActivityId=d8fbc1c6-6ea3-379f-911a-061b48bb5f34, activityType=Replicate, attempt=1
java.util.concurrent.CancellationException: null
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2478) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$3(TemporalAttemptExecution.java:220) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
	at io.airbyte.workers.temporal.CancellationHandler$TemporalCancellationHandler.checkAndHandleCancellation(CancellationHandler.java:49) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$4(TemporalAttemptExecution.java:223) ~[io.airbyte-airbyte-workers-0.35.6-alpha.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
2022-01-27 10:03:36 INFO i.a.w.DefaultReplicationWorker(run):200 - sync summary: io.airbyte.config.ReplicationAttemptSummary@6323fc4e[status=cancelled,recordsSynced=452615,bytesSynced=196798680,startTime=1643273006308,endTime=1643277816369,totalStats=io.airbyte.config.SyncStats@7108f83[recordsEmitted=452615,bytesEmitted=196798680,stateMessagesEmitted=1,recordsCommitted=0],streamStats=[io.airbyte.config.StreamSyncStats@6677378f[streamName=AIR2_user_gender,stats=io.airbyte.config.SyncStats@7884636c[recordsEmitted=162598,bytesEmitted=21512226,stateMessagesEmitted=<null>,recordsCommitted=<null>]], io.airbyte.config.StreamSyncStats@43921be[streamName=AIR2_jhi_user,stats=io.airbyte.config.SyncStats@756da2d[recordsEmitted=290017,bytesEmitted=175286454,stateMessagesEmitted=<null>,recordsCommitted=<null>]]]]
2022-01-27 10:03:36 INFO i.a.w.DefaultReplicationWorker(run):207 - Source output at least one state message
2022-01-27 10:03:36 WARN i.a.w.DefaultReplicationWorker(run):217 - State capture: No new state, falling back on input state: io.airbyte.config.State@35b15ba7[state={}]
2022-01-27 10:03:36 WARN i.a.w.t.CancellationHandler$TemporalCancellationHandler(checkAndHandleCancellation):50 - Job either timeout-ed or was cancelled.
```

Airbyte server logs: 

```
2022-01-27 08:44:17 [44msource[0m > 2022-01-27 08:44:17 [32mINFO[m i.a.i.s.j.AbstractJdbcSource(lambda$discoverInternal$5):136 - {} - Table program_expiration_audit column error_message (type LONGTEXT[2147483647]) -> Json type STRING
2022-01-27 08:44:17 [44msource[0m > 2022-01-27 08:44:17 [32mINFO[m i.a.i.s.j.AbstractJdbcSource(lambda$discoverInternal$5):136 - {} - Table program_import_file_history column error_message (type VARCHAR[512]) -> Json type STRING
2022-01-27 08:44:17 [44msource[0m > 2022-01-27 08:44:17 [32mINFO[m i.a.i.s.j.AbstractJdbcSource(lambda$discoverInternal$5):136 - {} - Table jhi_user column failed_login_attempts (type INT[10]) -> Json type NUMBER
```

## Steps to Reproduce
1. Setup Source - MySQL
2. Setup Destination - Snowflake
3. Create connection
4. Run sync - Stuck in Running mode

**Comment by ShahBinoy** [comment] 2022-01-27 19:19
I am facing similar problem

```
2022-01-27 19:10:54 source > 2022-01-27 19:10:47 INFO i.a.i.s.r.AbstractDbSource(lambda$createReadIterator$7):249 - {} - Reading stream user_gender. Records read: 130000
2022-01-27 19:10:55 source > 2022-01-27 19:10:48 INFO i.a.i.s.r.AbstractDbSource(lambda$createReadIterator$7):249 - {} - Reading stream user_gender. Records read: 140000
2022-01-27 19:10:56 source > 2022-01-27 19:10:49 INFO i.a.i.s.r.AbstractDbSource(lambda$createReadIterator$7):249 - {} - Reading stream user_gender. Records read: 150000
2022-01-27 19:10:57 source > 2022-01-27 19:10:50 INFO i.a.i.s.r.AbstractDbSource(lambda$createReadIterator$7):249 - {} - Reading stream user_gender. Records read: 160000
2022-01-27 19:10:59 source > 2022-01-27 19:10:51 INFO i.a.i.s.r.AbstractDbSource(lambda$createReadIterator$7):249 - {} - Reading stream user_gender. Records read: 170000
2022-01-27 19:11:00 source > 2022-01-27 19:10:52 INFO i.a.i.s.r.AbstractDbSource(lambda$createReadIterator$7):249 - {} - Reading stream user_gender. Records read: 180000
2022-01-27 19:11:03 DEBUG i.a.c.h.LogClientSingleton(setJobMdc):137 - Setting kube job mdc
2022-01-27 19:11:13 DEBUG i.a.c.h.LogClientSingleton(setJobMdc):137 - Setting kube job mdc
2022-01-27 19:11:23 DEBUG i.a.c.h.LogClientSingleton(setJobMdc):137 - Setting kube job mdc
2022-01-27 19:11:33 DEBUG i.a.c.h.LogClientSingleton(setJobMdc):137 - Setting kube job mdc
2022-01-27 19:11:43 DEBUG i.a.c.h.LogClientSingleton(setJobMdc):137 - Setting kube job mdc
2022-01-27 19:11:53 DEBUG i.a.c.h.LogClientSingleton(setJobMdc):137 - Setting kube job mdc
2022-01-27 19:12:03 DEBUG i.a.c.h.LogClientSingleton(setJobMdc):137 - Setting kube job mdc
```

After this, all I see is log upload messages like 
```
│ airbyte-worker-5496cff97d-89hl2 2022-01-27 19:17:43 DEBUG i.a.c.h.LogClientSingleton(setJobMdc):137 - Setting kube job mdc                                                                                                                                                            │
│ airbyte-worker-5496cff97d-89hl2 2022-01-27 19:17:53 DEBUG i.a.c.h.LogClientSingleton(setJobMdc):137 - Setting kube job mdc                                                                                                                                                            │
│ airbyte-worker-5496cff97d-89hl2 Collecting content into /tmp/toBePublished17373438507311543393.tmp before uploading.                                                                                                                                                                  │
│ airbyte-worker-5496cff97d-89hl2 Publishing to S3 (bucket=airbyte-dev-logs; key=job-logging/workspace/129/0/logs.log/20220127191803_airbyte-worker-5496cff97d-89hl2_9ab5000fd8db43bfa98f88346e43330a):                                                                                 │
│ airbyte-worker-5496cff97d-89hl2 2022-01-27 19:18:03 DEBUG i.a.c.h.LogClientSingleton(setJobMdc):137 - Setting kube job mdc                                                                                                                                                            │
│ airbyte-worker-5496cff97d-89hl2 2022-01-27 19:18:13 DEBUG i.a.c.h.LogClientSingleton(setJobMdc):137 - Setting kube job mdc                                                                                                                                                            │
│ airbyte-worker-5496cff97d-89hl2 2022-01-27 19:18:23 DEBUG i.a.c.h.LogClientSingleton(setJobMdc):137 - Setting kube job mdc                                                                                                                                                            │
│ airbyte-worker-5496cff97d-89hl2 2022-01-27 19:18:33 DEBUG i.a.c.h.LogClientSingleton(setJobMdc):137 - Setting kube job mdc                                                                                                                                                            │
│ airbyte-worker-5496cff97d-89hl2 2022-01-27 19:18:43 DEBUG i.a.c.h.LogClientSingleton(setJobMdc):137 - Setting kube job mdc
```

**Comment by ShahBinoy** [comment] 2022-01-28 15:15
Attaching full Log below as per @harshithmullapudi 's feedback on Slack

Sharing logs as gist below since issue editor would not accept full log
https://gist.github.com/ShahBinoy/272f3ac388d1da381c5a4676f383e058

**Comment by aniket-vh** [comment] 2022-01-31 09:18
## Environment - Updated
- **Airbyte version**:  0.35.12-alpha
- **OS Version / Instance**: k8s
- **Deployment**: k8s
- **Source Connector and version**: MySQL 0.5.1
- **Destination Connector and version**: Local File system
- **Severity**: Medium
- **Step where error happened**:  Sync job

## job logs: 
```
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:286) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:252) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:209) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:193) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:151) ~[temporal-sdk-1.6.0.jar:?]
	at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) ~[temporal-sdk-1.6.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.cancel(CompletableFuture.java:2478) ~[?:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$3(TemporalAttemptExecution.java:217) ~[io.airbyte-airbyte-workers-0.35.12-alpha.jar:?]
	at io.airbyte.workers.temporal.CancellationHandler$TemporalCancellationHandler.checkAndHandleCancellation(CancellationHandler.java:53) ~[io.airbyte-airbyte-workers-0.35.12-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getCancellationChecker$4(TemporalAttemptExecution.java:220) ~[io.airbyte-airbyte-workers-0.35.12-alpha.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[?:?]
	... 3 more
2022-01-28 17:28:24 INFO i.a.w.DefaultReplicationWorker(run):217 - sync summary: io.airbyte.config.ReplicationAttemptSummary@103393c4[status=cancelled,recordsSynced=164579,bytesSynced=21776264,startTime=1643389484005,endTime=1643390904115,totalStats=io.airbyte.config.SyncStats@1e1cc3de[recordsEmitted=164579,bytesEmitted=21776264,stateMessagesEmitted=0,recordsCommitted=0],streamStats=[io.airbyte.config.StreamSyncStats@678e2a72[streamName=file_user_gender,stats=io.airbyte.config.SyncStats@659f7ad[recordsEmitted=164579,bytesEmitted=21776264,stateMessagesEmitted=<null>,recordsCommitted=<null>]]]]
2022-01-28 17:28:24 INFO i.a.w.DefaultReplicationWorker(run):239 - Source did not output any state messages
2022-01-28 17:28:24 WARN i.a.w.DefaultReplicationWorker(run):250 - State capture: No state retained.
```

**Comment by ShahBinoy** [comment] 2022-01-31 14:18
+1 👍

**Comment by alafanechere** [comment] 2022-01-31 14:35
@ShahBinoy are you facing the same problem with the same source connector (MySQL?)

**Comment by ShahBinoy** [comment] 2022-01-31 18:07
> 

Yes @alafanechere Running in Kubernetes 1.18

**Comment by ryanmeekins** [comment] 2022-02-23 15:08
I'm facing a similar issue of it getting stuck on `DEBUG i.a.c.h.LogClientSingleton(setJobMdc):133 - Setting docker job mdc`

Airbyte version: 0.35.32-alpha
OS Version / Instance: Ubuntu 20.04
Deployment: Docker on Azure VM
Source Connector and version: MSSQL 0.3.17
Destination Connector and version: Snowflake 0.4.15
Severity: Medium
Step where error happened: Sync job

The job keeps getting stuck in the running state for larger tables (~82 MB) but worked for a much smaller table.

[logs-7.txt](https://github.com/airbytehq/airbyte/files/8125341/logs-7.txt)

**Comment by alafanechere** [comment] 2022-03-02 15:49
Hi @aniket-vh, could you please attach your full log file? 
I'm under the impression that the problem is on MySQL side.
* Could you please also share what is the size of the table  (in Mb or Gb) you're trying to replicate.
* Does this problem occur for all tables? Does the load succeeds if you discard the `user_gender` table?

**Comment by grishick** [comment] 2022-08-26 23:50
This should be fixed now after we've introduced more frequent checkpointing and auto-sizing number of rows to fetch

**Closed by grishick** 2022-08-26 23:50 UTC
Labels: type/bug, community, connectors/source/mysql, team/databases
