### ISSUE TITLE
Source Facebook Marketing & Facebook Pages: Need to upgrade Facebook graph api version from v16.0 to v17.0

### ISSUE THREAD

**Issue by parthprydotinfotech** [airbytehq/airbyte#26745] opened 2023-05-30 09:59 UTC
### Connector Name

Facebook Marketing & Facebook Pages

### Connector Version

0.3.6

### What step the error happened?

Updating the connector

### Revelant information

Internal message: Error: 2635, (#2635) Your app has been upgraded to version v17.0, please use this version or newer. This can be verified in the settings tab on the App Dashboard.. Please also verify your Account ID: See the https://www.facebook.com/business/help/1492627900875762 for more information.

### Relevant log output

```shell
File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 156, in launch
    for message in source_entrypoint.run(parsed_args):
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 91, in run
    yield from map(AirbyteEntrypoint.airbyte_message_to_string, self.check(source_spec, config))
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/entrypoint.py", line 112, in check
    check_result = self.source.check(self.logger, config)
  File "/usr/local/lib/python3.9/site-packages/airbyte_cdk/sources/abstract_source.py", line 84, in check
    check_succeeded, error = self.check_connection(logger, config)
  File "/airbyte/integration_code/source_facebook_marketing/source.py", line 68, in check_connection
    logger.info(f"Select account {api.account}")
  File "/usr/local/lib/python3.9/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/airbyte/integration_code/source_facebook_marketing/api.py", line 170, in account
    return self._find_account(self._account_id)
  File "/airbyte/integration_code/source_facebook_marketing/api.py", line 178, in _find_account
    raise FacebookAPIException(
source_facebook_marketing.api.FacebookAPIException: Error: 2635, (#2635) Your app has been upgraded to version v17.0, please use this version or newer. This can be verified in the settings tab on the App Dashboard.. Please also verify your Account ID: See the https://www.facebook.com/business/help/1492627900875762 for more information.
2023-05-30 09:51:21 WARN i.a.w.g.DefaultCheckConnectionWorker(run):108 - Check connection job subprocess finished with exit code 1
2023-05-30 09:51:21 INFO i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
2023-05-30 09:51:21 INFO i.a.c.i.LineGobbler(voidCall):149 - 
2023-05-30 09:51:21 INFO i.a.c.i.LineGobbler(voidCall):149 - ----- END CHECK -----
2023-05-30 09:51:21 INFO i.a.c.i.LineGobbler(voidCall):149 -
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by amrael** [comment] 2023-06-05 00:25
Any news regarding this matter? It seems that new users of the Facebook app who created their account after the v17.0 release are unable to sync with this source as they cannot downgrade the API version.

**Comment by parthprydotinfotech** [comment] 2023-06-05 05:00
Yes @amrael you're correct. I have created the Facebook app after releasing version v17.0 and I can not downgrade that version.

**Comment by haranesh** [comment] 2023-06-05 11:21
Have tested api its just have to change only url. Can any one help how to change this default url ?

**Comment by rafaelstalse** [comment] 2023-06-05 19:51
I recently created an app and facebook won't let me downgrade.

I tested it with other apps I have and they are in version 15... 16 and everything is ok, the problem is for v17.

I'm waiting for the solution of this issue to continue my connection.

**Comment by quangdvn** [comment] 2023-06-08 06:59
Just wonder if someone has come up with any solutions yet
Because Facebook app won't allow downgrading from v17 to older one (v15, v16)

**Comment by parthprydotinfotech** [comment] 2023-06-08 07:02
Still, I am also waiting for the solution. In airbyte just need to change the version but don't know where to change it. Currently, facebook api is calling by passing version v16.0 and we need to replace it by v17.0 but, I don't know from where it's passing.


If anyone aware about that location please write it down in comments. Thanks!

**Comment by parthprydotinfotech** [comment] 2023-06-08 07:03
@airbyteio Please look into this issue.

**Comment by rafaelstalse** [comment] 2023-06-27 17:46
Any updates or predictions to resolve this issue?

**Comment by marvin-lg** [comment] 2023-08-03 09:56
Any news on this issue? It has been more than two months and this GA connector is not usable. As a workaround we created a custom connector where we only changed the API version to 17.0 to make it work. But for certain pages the sync via this custom connector fails from time to time.

**Comment by marcosmarxm** [comment] 2023-09-15 18:18
Closed by https://github.com/airbytehq/airbyte/pull/27563

**Closed by marcosmarxm** 2023-09-15 18:18 UTC
Labels: type/bug, help-welcome, area/connectors, community, connectors/sources-api, connectors/source/facebook-pages, releaseStage/ga, team/connectors-python, releaseStage/beta
