### ISSUE TITLE
Google Ads ad_group_ad_report only return Search campaigns costs

### ISSUE THREAD

**Issue by bigdatawonders** [airbytehq/airbyte#13425] opened 2022-06-02 14:51 UTC
## Environment
- **Airbyte version**:  0.35.10-alpha
- **OS Version / Instance**:AWS EC2
- **Source Connector and version**: Google ads 0.1.39
- **Destination Connector and version**: S3 v.0.3.1  

## Context
We are using Airbyte to report clients spend by ad level. Which makes this quite urgent.
Some previous versions were showing this data +- correctly.

## Current Behavior
account_performance cost_micros does not match with ad_group_ad_report cost micros for the same day.

## Expected Behavior
I expect the costs to match across all granularities

**Comment by bigdatawonders** [comment] 2022-06-02 15:18
Hey @alafanechere,
The field is cost_micros. If I sum ad_group_ad_report and divide to get currency amount I get much less than on total account level.
Example from Airbyte extracted data:
May 31st - total account spend 211.120966 EUR (matches with google UI)
total ad_group_ad_report - 69.960488 EUR (should be 211.120966 as total per account)

FROM UI by ad categories:
Total: Search campaigns
€69.96 
Total: Video campaigns
€71.37
Total: Discovery campaigns
€69.79
---- total sum (211.12)

thanks!

**Comment by marcosmarxm** [comment] 2022-06-02 15:27
@bigdatawonders closing as duplicate of https://github.com/airbytehq/airbyte/issues/12999

**Closed by marcosmarxm** 2022-06-02 15:27 UTC
Labels: type/bug, area/connectors, priority/critical, community, connectors/source/google-ads, team/connectors-python
