### ISSUE TITLE
Platform Issue: temporal pod crashing on Kubernetes for new deployment

### ISSUE THREAD

**Issue by bkonicek-calm** [airbytehq/airbyte#25815] opened 2023-05-04 18:55 UTC
### Platform Version

0.44.0

### What step the error happened?

On deploy

### Revelant information

I'm deploying Helm chart version 0.45.11 with an external GCP Postgres Database. I've already successfully deployed this to other environments with the exact same chart version and same values.

Now, my `temporal` pod is failing to start, which causes the deployment to fail.

When I start a debug pod and copy the temporal pod to it, I can see that there is no `config/docker.yaml` file. Since the image tag for the temporal container is the same as in all my other clusters, what could be causing the config file to not be generated?

### Relevant log output

```shell
+ temporal-sql-tool --plugin postgres --ep 10.24.0.24 -u airbyte -p 5432 create --db temporal
2023-05-04T18:48:49.897Z	ERROR	Unable to create SQL database.	{"error": "pq: database \"temporal\" already exists", "logging-call-at": "handler.go:97"}
2023/05/04 18:48:49 Loading config; env=docker,zone=,configDir=config
2023/05/04 18:48:49 Loading config files=[config/docker.yaml]
Unable to load configuration: config file corrupted: yaml: line 17: found unknown escape character.
```

**Comment by kijewskimateusz** [comment] 2023-05-04 19:04
Hello Everyone,

I am having very similar issue on my end. I am too trying to deploy Airbyte using GCP Cloud-SQL database and after successful bootloader, my temporal is failing with logs:

```
+ temporal-sql-tool --plugin postgres --ep 172.27.5.3 -u airbyte -p 5432 create --db temporal
2023-05-04T18:47:04.590Z    ERROR    Unable to create SQL database.    {"error": "pq: database \"temporal\" already exists", "logging-call-at": "handler.go:97"} 
2023/05/04 18:47:04 Loading config; env=docker,zone=,configDir=config
2023/05/04 18:47:04 Loading config files=[config/docker.yaml]
Unable to load configuration: config file corrupted: yaml: line 29: did not find expected key. 
```

**Comment by bkonicek-calm** [comment] 2023-05-05 19:55
@rowanmoul interesting find. It's odd because I didn't do anything differently on my previous deployments, and it didn't have this problem. Unfortunately I'm not able to see that far back in the logs to confirm whether or not they also tried to initialize the database.

The other thing that's confusing me is what happens if the temporal pod restarts - won't it try to create the database again?

**Comment by rowanmoul** [comment] 2023-05-08 21:57
Further digging has uncovered what appears to be the root cause of the problem (though it doesn't explain why more people didn't encounter this issue before now).
`airbyte-temporal` is using a rather ancient version of Temporal from 2021 (1.13.0) which does not include a `temporal-sql-tool` which fails gracefully when the database already exists. Compare [1.13.0](https://github.com/temporalio/temporal/blob/6cbfa2a3a569fcc856788b37616876538d904b3d/common/persistence/sql/sqlplugin/postgresql/admin.go#L134) to the only marginally more recent [1.14.0](https://github.com/temporalio/temporal/blob/074d8ebb171f96752d7fae6020a36bdd0720bea4/common/persistence/sql/sqlplugin/postgresql/admin.go#L138) (current latest version is 1.20.2)

Also, I noticed that while [this module](https://github.com/airbytehq/airbyte-platform/tree/main/airbyte-temporal) exists (and the [image](https://hub.docker.com/r/airbyte/temporal) that contains it), it doesn't appear to be used with the airbyte helm chart, which just references [airtbyte/temporal-auto-setup](https://hub.docker.com/r/airbyte/temporal-auto-setup) directly (see [here](https://github.com/airbytehq/airbyte-platform/blob/8a7ba2f710d73c3a08c94f242c2e03ded1aa6dde/charts/airbyte/values.yaml#L1093) and [here](https://github.com/airbytehq/airbyte-platform/blob/1305bc927a5cc8e62946ef8ec92fe30ab638051e/charts/airbyte-temporal/values.yaml#L25)).
Using the `airbyte/temporal` image seems to allow temporal to startup correctly, despite the errors about the database already existing.

**Comment by rowanmoul** [comment] 2023-10-17 16:24
It looks like the Airbyte team have resolved this by updating to a newer Temporal version and using the upstream container image directly, so the above is not needed as of Helm Chart version 47.11 ([release 50.11](https://github.com/airbytehq/airbyte-platform/releases/tag/v0.50.11))

**Comment by davinchia** [comment] 2024-05-09 17:41
Thanks, closing this as it's old.

**Closed by davinchia** 2024-05-09 17:41 UTC
Labels: type/bug, area/platform, community, team/platform-move, autoteam
