### ISSUE TITLE
Handle change in schema at source

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#7809] opened 2021-11-10 08:05 UTC
## Tell us about the problem you're trying to solve
General query on schema evolution from data pipeline standpoint:
If someone changes table meta data at source table and ingestion is set with incremental mode, Let say, table contains column A and B and now dev team has added column C. If we are going to rescan the new structure it will going to reset complete data at destination. If this happens then user might end up in loosing all the transactional updates which has been done at source level so far, so in short, user cannot afford reseting of data at destination. 
Now what we want here, to add new column in existing table which is column C and backfill the data with some default data. What can we do here with Airbyte with minimal manual intervention.
Would love to know, if anyone has come across any such scenario.

### solution
https://airbytehq.slack.com/archives/C019WEENQRM/p1623173312192100?thread_ts=1623173050.192000&cid=C019WEENQRM

### Slack Convo
https://airbytehq.slack.com/archives/C01MFR03D5W/p1636470898344300

**Comment by ChristopheDuong** [comment] 2021-11-10 10:05
Probably a duplicate of https://github.com/airbytehq/airbyte/issues/3520

also related to https://github.com/airbytehq/airbyte/issues/6089

**Closed** 2023-01-07 01:04 UTC
Labels: type/enhancement, area/connectors, team/extensibility, autoteam
