### ISSUE TITLE
NullPointerException while sync when source-s3 CSV -> destination-s3 PARQUET

### ISSUE THREAD

**Issue by amorskoy** [airbytehq/airbyte#6871] opened 2021-10-07 08:46 UTC
## Enviroment
- **Airbyte version**:  fresh master, commit `11645689431a69c689a15b620e4a2b6bc7b045c3`
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker
- **Source Connector and version**: source-s3:0.1.5
- **Destination Connector and version**: destination-s3:0.1.12
- **Severity**: Critical
- **Step where error happened**: Sync job
 
## Current Behavior
I have small CSV file on S3: 3.7MB, 4k rows x 150 columns generated by Python Faker lib.
File is attached
[sample_synth_4K_150.csv](https://github.com/airbytehq/airbyte/files/7300619/sample_synth_4K_150.csv)

I want to save it on S3 as Parquet file using destination-s3.
I get `java.lang.NullPointerException` for `io.airbyte.integrations.destination.s3.avro.JsonToAvroSchemaConverter.getAvroSchema(JsonToAvroSchemaConverter.java:139)`

## Expected Behavior
Sync should infer schema correctly and finish correctly with Parquet file output

## Logs
Please see attached
[logs-2-0.txt](https://github.com/airbytehq/airbyte/files/7300652/logs-2-0.txt)

**Comment by tuliren** [comment] 2021-10-15 20:24
The line 139 in `JsonToAvroSchemaConverter` is actually this line:
https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/destination-s3/src/main/java/io/airbyte/integrations/destination/s3/avro/JsonToAvroSchemaConverter.java#L119

The line number is wrong due to the license update.

This means the json schema passed into the s3 destination misses a `properties` field.

Still investigating.

**Comment by tuliren** [comment] 2021-10-18 17:02
I see. Avro schema requires a definitive type for each field. Currently our Avro to Json schema converter does not support `additionalProperties` yet. So this should be the root cause of this NPE.

**Comment by VitaliiMaltsev** [comment] 2021-12-01 11:30
Can not reproduce at the moment
I believe this issue was fixed in scope of https://github.com/airbytehq/airbyte/pull/7288
@tuliren please verify

**Comment by VitaliiMaltsev** [comment] 2021-12-07 08:53
@tuliren can we close this issue?

**Comment by tuliren** [comment] 2021-12-07 23:15
Yes, we can close. Sorry that I missed your comment.

**Closed by tuliren** 2021-12-07 23:15 UTC
Labels: type/bug, area/connectors, lang/java, community
