### ISSUE TITLE
Adding an un-existing user to a workspace stopped working

### ISSUE THREAD

**Issue by benmoriceau** [airbytehq/airbyte#8111] opened 2021-11-18 22:38 UTC
There is a regression, when adding a un-existing user to a workspace in the cloud. It used to be possible unfortunately it is not possible because an error happens in the server while adding the user to the workspace.
The way to reproduce the issue can be found here: https://github.com/airbytehq/oncall/issues/24

The workaround to that is to ask the users to signup to airbyte prior to getting the invite to join the workspace.

**Comment by davinchia** [comment] 2021-11-19 01:15
this is the error
```2021-11-19 01:14:02 ERROR i.a.s.e.UncaughtExceptionMapper(toResponse):22 - {} - Uncaught exception
java.lang.IllegalArgumentException: Project ID is required to access the auth service. Use a service account credential or set the project ID explicitly via FirebaseOptions. Alternatively you can also set the project ID via the GOOGLE_CLOUD_PROJECT environment variable.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:144) ~[guava-30.1.1-jre.jar:?]
	at com.google.firebase.auth.FirebaseUserManager.<init>(FirebaseUserManager.java:86) ~[firebase-admin-8.1.0.jar:?]
	at com.google.firebase.auth.FirebaseUserManager.<init>(FirebaseUserManager.java:62) ~[firebase-admin-8.1.0.jar:?]
	at com.google.firebase.auth.FirebaseUserManager$Builder.build(FirebaseUserManager.java:437) ~[firebase-admin-8.1.0.jar:?]
	at com.google.firebase.auth.FirebaseUserManager.createUserManager(FirebaseUserManager.java:400) ~[firebase-admin-8.1.0.jar:?]
	at com.google.firebase.auth.AbstractFirebaseAuth$30.get(AbstractFirebaseAuth.java:1842) ~[firebase-admin-8.1.0.jar:?]
	at com.google.firebase.auth.AbstractFirebaseAuth$30.get(AbstractFirebaseAuth.java:1839) ~[firebase-admin-8.1.0.jar:?]
	at com.google.firebase.auth.AbstractFirebaseAuth$29.get(AbstractFirebaseAuth.java:1768) ~[firebase-admin-8.1.0.jar:?]
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167) ~[guava-30.1.1-jre.jar:?]
	at com.google.firebase.auth.AbstractFirebaseAuth.getUserManager(AbstractFirebaseAuth.java:1758) ~[firebase-admin-8.1.0.jar:?]
	at com.google.firebase.auth.AbstractFirebaseAuth.getUserByEmailOp(AbstractFirebaseAuth.java:516) ~[firebase-admin-8.1.0.jar:?]
	at com.google.firebase.auth.AbstractFirebaseAuth.getUserByEmail(AbstractFirebaseAuth.java:497) ~[firebase-admin-8.1.0.jar:?]
	at io.airbyte.cloud.server.handlers.WebBackendPermissionHandler.getFirebaseUser(WebBackendPermissionHandler.java:329) ~[io.airbyte-cloud-cloud-server-0.32.3-alpha.jar:?]
	at io.airbyte.cloud.server.handlers.WebBackendPermissionHandler.inviteUserToWorkspace(WebBackendPermissionHandler.java:282) ~[io.airbyte-cloud-cloud-server-0.32.3-alpha.jar:?]
	at io.airbyte.cloud.server.apis.CloudApi.lambda$webBackendInviteUserToWorkspace$24(CloudApi.java:371) ~[io.airbyte-cloud-cloud-server-0.32.3-alpha.jar:?]
	at io.airbyte.cloud.auth.AuthHelper.execute(AuthHelper.java:101) ~[io.airbyte-cloud-cloud-auth-0.32.3-alpha.jar:?]
	at io.airbyte.cloud.auth.AuthHelper.callForWorkspace(AuthHelper.java:78) ~[io.airbyte-cloud-cloud-auth-0.32.3-alpha.jar:?]
	at io.airbyte.cloud.server.apis.CloudApi.webBackendInviteUserToWorkspace(CloudApi.java:368) ~[io.airbyte-cloud-cloud-server-0.32.3-alpha.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.server.Server.handle(Server.java:501) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [airbyte-server-0.32.3-alpha.jar:?]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [airbyte-server-0.32.3-alpha.jar:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
2021-11-19 01:14:02 ERROR i.a.s.RequestLogger(filter):93 - {} - REQ 127.0.0.1 POST 500 /cloud/v1/web_backend/cloud_workspaces/invite - {"email":"davin+400@airbyte.io","workspaceId":"5efef4df-9276-4c23-b83d-adc8856a1953"}
2021-11-19 01:14:07 INFO i.a.s.RequestLogger(filter):95 - {} - REQ 172.20.100.233 GET 200 /cloud/v1/health
2021-11-19 01:14:09 INFO i.a.s.RequestLogger(filter):95 - {} - REQ 172.23.3.95 POST 200 /cloud/v1/users/get_by_auth_id - {"authUserId":"hkWRfS095IbT39CvoKgjqeCI9Sr2","authProvider":"google_identity_platform"}
2021-11-19 01:14:09 INFO i.a.s.RequestLogger(filter):95 - {} - REQ 172.23.3.95 POST 200 /cloud/v1/users/get_by_auth_id - {"authUserId":"hkWRfS095IbT39CvoKgjqeCI9Sr2","authProvider":"google_identity_platform"}
2021-11-19 01:14:09 INFO i.a.s.RequestLogger(filter):95 - {} - REQ 172.23.3.95 POST 200 /cloud/v1/web_backend/permissions/list_by_user - {"userId":"6acaa09d-0aa9-4a15-93cc-284b22de1f79"}
2021-11-19 01:14:09 INFO i.a.s.RequestLogger(filter):95 - {} - REQ 172.23.3.95 POST 200 /cloud/v1/web_backend/permissions/list_by_user - {"userId":"6acaa09d-0aa9-4a15-93cc-284b22de1f79"}```

**Comment by davinchia** [comment] 2021-11-23 05:16
Closing this as duplicate of https://github.com/airbytehq/oncall/issues/24, which was fixed.

**Closed by davinchia** 2021-11-23 05:16 UTC
Labels: type/bug, area/platform
