### ISSUE TITLE
manual operations sync/reset/cancel should show errors when the server fails

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#10605] opened 2022-02-24 05:43 UTC
Currently, if a user attempts to sync/reset/cancel and there is a server-side failure, no error is shown to the user and the page just feels uninteractive. For sync now, it's left in a consistently spinning state.

**Comment by octavia-squidington-iii** [comment] 2022-02-24 05:43
cc @airbytehq/frontend

**Comment by Jamakase** [comment] 2022-02-24 06:29
This is duplicate of https://github.com/airbytehq/airbyte/issues/10215

**Closed** 2022-02-24 08:10 UTC
Labels: type/bug, area/frontend, needs-triage
