### ISSUE TITLE
Source S3: errors when using JSON data

### ISSUE THREAD

**Issue by davidfromtandym** [airbytehq/airbyte#15339] opened 2022-08-04 23:53 UTC
## Environment
Airbyte Version: 0.39.41-alpha
Source: S3 (0.1.18)
Destination: Redshift (0.3.47)
Instance: AWS EC2
Deployment: Docker
Step where error happened: Sync job

## Current Behavior
Attempting to use a JSON file in the s3-source results in connector errors. I have two JSON objects in my source data, both of which have nested data within them. I've attempted a) letting the connector infer the datatypes; b) defining the datatypes for the two fields as `object`; and c) defining the datatypes for the two fields as `string`. In every case, the connector fails.

When I attempt to define the datatype as `object`, I get an error stating `Should be 'object', but found 'string'`. When I define the datatype as `string`, I get an error stating `pyarrow.lib.ArrowInvalid: JSON parse error: Column(/meta) changed from string to object in row 0`.

## Expected Behavior
The connector should import the JSON data without error.

## Logs
[logs-10500.txt](https://github.com/airbytehq/airbyte/files/9264138/logs-10500.txt)
Note, this set of logs is from a run where I defined the datatypes as `object`.

## Are you willing to submit a PR?
No

**Comment by natalyjazzviolin** [comment] 2022-08-05 14:22
Hey @davidfromtandym! Are you using the line-delimited json format in your source data? That's the only format currently supported as per the [docs](https://docs.airbyte.com/integrations/sources/s3/#jsonl).

**Comment by natalyjazzviolin** [comment] 2022-08-05 15:04
Could you give me an example of what one of the json files might look like?

**Comment by davidfromtandym** [comment] 2022-08-05 16:08
Sure! Here is an example of our data structure:

```
{"meta":{"entity": "accounts","url": "https://example.com/api/accounts/123","changed_on": "2022/04/20T16:20Z"},"payload": {"accounts": ["data", "goes","here"]}}
{"meta":{"entity": "line_items","url": "https://example.com/api/accounts/123/line_items/42","changed_on": "2022/04/20T16:20Z"},"payload": {"line_items": ["data", "goes","here"]}}
```

**Comment by natalyjazzviolin** [comment] 2022-08-05 19:21
Thanks! I'm working on reproducing this, but have also triaged it to the connectors team.

**Comment by davidfromtandym** [comment] 2022-08-10 13:59
Hi @natalyjazzviolin .. just curious if you'd been able to reproduce the issue. I can provide more details if it's helpful.

**Comment by abankspdx** [comment] 2022-08-17 19:36
I'm also encountering this issue @natalyjazzviolin for both Object and Array JSON types. My JSONL file only has a single record. Any updates?

**Comment by abankspdx** [comment] 2022-08-22 17:28
@davidfromtandym did you find a workaround?

**Comment by davidfromtandym** [comment] 2022-08-22 17:34
@abankspdx we're landing data into redshift, so we ended up using some different AWS functionality ([see here](https://docs.aws.amazon.com/redshift/latest/gsg/bring-own-data.html), if helpful). Would have liked to keep all extract and load jobs in one spot with Airbyte, but didn't want to spend the time troubleshooting the connector myself and there doesn't seem to be any traction with investigating the issue.

**Comment by zhxnlai** [comment] 2022-08-28 17:20
I also ran into this issue. My input is in newline delimited GeoJSON format.

I think the issue is [here](https://github.com/airbytehq/airbyte/blob/dca2256a7ccc0108eb076e2849a476c969b958e2/airbyte-integrations/connectors/source-s3/source_s3/source_files_abstract/formats/abstract_file_parser.py#L73
): S3 connector's JSONL parser does not support nested object 

```
        # this is a map of airbyte types to pyarrow types. The first list element of the pyarrow types should be the one to use where required.
        map = {
            "boolean": ("bool_", "bool"),
            "integer": ("int64", "int8", "int16", "int32", "uint8", "uint16", "uint32", "uint64"),
            "number": ("float64", "float16", "float32", "decimal128", "decimal256", "halffloat", "float", "double"),
            "string": ("large_string", "string"),
            # TODO: support object type rather than coercing to string
            "object": ("large_string",),
            # TODO: support array type rather than coercing to string
            "array": ("large_string",),
            "null": ("large_string",),
        }
```

**Comment by krosenst** [comment] 2022-11-11 16:23
Thank you for raising this issue. I have also encountered this error with new-line delimited JSON file in S3. The error I'm seeing is `JSON parse error: Column(/name) changed from string to array in row 1` so it's hitting this issue with arrays as well.

**Comment by davydov-d** [comment] 2023-02-13 12:49
fixed in https://github.com/airbytehq/oncall/issues/531

**Closed by davydov-d** 2023-02-13 12:49 UTC
Labels: type/bug, area/connectors, lang/python, community, connectors/source/s3, team/connectors-python
