### ISSUE TITLE
Provide a way to clean up old data (logs)

### ISSUE THREAD

**Issue by gosusnp** [airbytehq/airbyte#15567] opened 2022-08-11 18:14 UTC
## Tell us about the problem you're trying to solve
We no longer clean up data which can cause [space issues](https://discuss.airbyte.io/t/unsure-how-to-set-workspace-retention-variables-correctly-in-docker-based-deployment/2200).

It was part of the old scheduler, it has been removed temporarily and is planned to be migrated (#11869)
As a result, until that is done, we no longer offer a way to programmatically clean up space.

## Describe the solution you’d like
When we deprecated the code, we kept around the former clean up [code](https://github.com/airbytehq/airbyte/blob/master/airbyte-scheduler/scheduler-persistence/src/main/java/io/airbyte/scheduler/persistence/JobCleaner.java).
Could we package it as a script to manually clean up as a workaround for now?

**Comment by marcosmarxm** [comment] 2022-08-12 14:03
Zendesk ticket #[1884](https://airbyte7538.zendesk.com/agent/tickets/1884) has been linked to this issue.

**Comment by marcosmarxm** [comment] 2022-08-12 14:04
*Comment made from Zendesk by Marcos Marx on 2022-08-12 at 14:04:*

<blockquote><div class="zd-comment" dir="auto">Looks this feature was removed with the Scheduler. A ticket was created in Github <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/15567">https://github.com/airbytehq/airbyte/issues/15567</a> any updates I'll return to you. Today as a workaround you need to clean the logs yourself<br></div></blockquote>

**Comment by marcosmarxm** [comment] 2022-08-12 14:17
*Comment made from Zendesk by Marcos Marx on 2022-08-12 at 14:17:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Thanks, that’s excellent info! Will keep an eye on that issue. In the meantime I’ve done exactly that (a systemd timer and a cleanup script, but it’s a bit too hacky).</p>
<blockquote style="background-color: #f8f8f8; border-left-color: #e9e9e9; border-left-style: solid; border-left-width: 5px; margin-left: 0; padding: 12px;">
<p style="margin-bottom: 0; margin-top: 0; padding: 0;" dir="auto">Could we package it as a script to manually clean up as a workaround for now?</p>
</blockquote>
<p dir="auto">Really appreciate this suggestion in the ticket!</p> 

 [<a href="https://discuss.airbyte.io/t/unsure-how-to-set-workspace-retention-variables-correctly-in-docker-based-deployment/2200/5" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by evantahler** [comment] 2022-08-15 18:14
This should be addressed by https://github.com/airbytehq/airbyte/issues/15218

**Comment by marcosmarxm** [comment] 2022-08-30 16:22
Zendesk ticket #[2096](https://airbyte7538.zendesk.com/agent/tickets/2096) has been linked to this issue.

**Comment by marcosmarxm** [comment] 2022-08-30 16:23
*Comment made from Zendesk by Marcos Marx on 2022-08-30 at 16:23:*

<blockquote><div class="zd-comment" dir="auto">Sorry to hear that Arash. Looks there is a problem after removing the airbyte-scheduler service.<br>Check issue: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/15567">https://github.com/airbytehq/airbyte/issues/15567</a><br>&nbsp;<br>A workaround for now is clean the data folder to not consume so much space. I'll ask the engineer team to take a look and see what is possible to do too.<br></div></blockquote>

**Comment by evantahler** [comment] 2022-09-01 16:10
This is part of https://github.com/airbytehq/airbyte/issues/15218

**Comment by marcosmarxm** [comment] 2022-09-01 17:19
*Comment made from Zendesk by Marcos Marx on 2022-09-01 at 17:19:*

<blockquote><div class="zd-comment" dir="auto">Today there isn't an easy script to run this Gergely. We need to wait a complete solution for now :(<br></div></blockquote>

**Closed** 2022-09-02 20:21 UTC
Labels: type/enhancement, needs-triage, team/oss, zendesk

**Comment by gosusnp** [comment] 2022-09-02 20:33
@marcosmarxm, https://github.com/airbytehq/airbyte/pull/16247 re-adds a job that removes old files from the workspace.

Currently, we will remove any files older than 30days by default.
This retention can be configured by setting `TEMPORAL_HISTORY_RETENTION_IN_DAYS` variable.
We should still document this behavior properly and improve how this is configured, but this should mitigate the space issues users are seeing.

**Comment by marcosmarxm** [comment] 2022-09-04 06:07
*Comment made from Zendesk by Marcos Marx on 2022-09-04 at 06:07:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto"><a href="/u/marcosmarxm" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@marcosmarxm</a> Do you have any timeframe for fixing this issue? I think it’s very important.<br>
Thanks</p> 

 [<a href="https://discuss.airbyte.io/t/quickly-run-out-of-storage/2417/3" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment] 2022-09-05 16:47
*Comment made from Zendesk by Marcos Marx on 2022-09-05 at 16:47:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto"><a href="/u/arashlayeghi" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">@arashlayeghi</a> I’ve had the same issue. I manually delete logs that are older than 7 days every week or so. Pain in the ass, though I suppose I could setup a cronjob. Would be great if this feature worked correctly in the Airbyte deployment.</p> 

 [<a href="https://discuss.airbyte.io/t/quickly-run-out-of-storage/2417/4" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment] 2022-09-05 17:41
*Comment made from Zendesk by Marcos Marx on 2022-09-05 at 17:41:*

<blockquote><div class="zd-comment" dir="auto">Hello updating the status of this issue.<br>The solution was merged but isn't published to latest version, probably version: v0.40.5 will have those modifications.<br>&nbsp;<br>You can check the discussion here: <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/pull/16247">https://github.com/airbytehq/airbyte/pull/16247</a><br></div></blockquote>

**Comment by marcosmarxm** [comment] 2022-09-05 17:42
*Comment made from Zendesk by Marcos Marx on 2022-09-05 at 17:42:*

<blockquote><div class="zd-comment" dir="auto">Hello update here: the solution was merged.<br>But only next version v0.40.5 will receive the modifications, probably end of this week will have another update.<br>&nbsp;<br>Please check PR <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/pull/16247">https://github.com/airbytehq/airbyte/pull/16247</a><br></div></blockquote>

**Comment by marcosmarxm** [comment] 2022-09-13 05:23
*Comment made from Zendesk by Marcos Marx on 2022-09-13 at 05:22:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Thanks, Marcos,<br>
I updated it to v0.40.5 now. Do I need to do something or does it automatically clean up the storage when needed?</p> 

 [<a href="https://discuss.airbyte.io/t/quickly-run-out-of-storage/2417/6" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment] 2022-09-13 16:16
*Comment made from Zendesk by Marcos Marx on 2022-09-13 at 16:16:*

<blockquote><div class="zd-comment" dir="auto">Airbyte version 0.45.5 reimplemented the feature, you can change the default value changing the variable <code>TEMPORAL_HISTORY_RETENTION_IN_DAYS</code><br></div></blockquote>

**Comment by marcosmarxm** [comment] 2022-09-13 16:17
*Comment made from Zendesk by Marcos Marx on 2022-09-13 at 16:17:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Airbyte version 0.45.5 reimplemented the feature, you can change the default value changing the variable <code style="background-color: #f9f9f9; padding: 2px 5px;">TEMPORAL_HISTORY_RETENTION_IN_DAYS</code></p> 

 [<a href="https://discuss.airbyte.io/t/unsure-how-to-set-workspace-retention-variables-correctly-in-docker-based-deployment/2200/8" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment] 2022-09-13 16:22
*Comment made from Zendesk by Marcos Marx on 2022-09-13 at 16:22:*

<blockquote><div class="zd-comment" dir="auto">You can&nbsp;<br></div></blockquote>

**Comment by marcosmarxm** [comment] 2022-09-14 07:20
*Comment made from Zendesk by Marcos Marx on 2022-09-14 at 07:20:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Thanks, will give that a try!</p>
<p dir="auto">Just for reference, as I wasn’t sure reading your comment, I see that <a href="https://github.com/airbytehq/airbyte/blob/d8567310297eb685fe0b81d4721393af82cfb851/airbyte-config/config-models/src/main/java/io/airbyte/config/EnvConfigs.java#L206" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">the current default value is 30 day</a>s, that’s good to know.</p> 

 [<a href="https://discuss.airbyte.io/t/unsure-how-to-set-workspace-retention-variables-correctly-in-docker-based-deployment/2200/9" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment] 2022-09-14 15:06
*Comment made from Zendesk by Marcos Marx on 2022-09-14 at 15:05:*

<blockquote><div class="zd-comment" dir="auto">You're correct.<br></div></blockquote>

**Comment by marcosmarxm** [comment] 2022-09-19 15:38
*Comment made from Zendesk by Marcos Marx on 2022-09-19 at 15:38:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hello Marcos,</p>
<p dir="auto">This is our <code style="background-color: #f9f9f9; padding: 2px 5px;">.env</code> file containing <code style="background-color: #f9f9f9; padding: 2px 5px;">TEMPORAL_HISTORY_RETENTION_IN_DAYS=1</code> at the end.<br>
I ran <code style="background-color: #f9f9f9; padding: 2px 5px;">docker-compose up -d</code> more than 34 hours ago but it seems the storage is getting full without cleaning up. What is wrong with my deployment?</p>
<p dir="auto"><a href="https://discuss.airbyte.io/uploads/short-url/cdaOn91PaZkO4uIfV5bKqA6wkKK.txt" style="color: #006699; font-weight: bold; text-decoration: none;" rel="noreferrer">env.txt</a> (3.6 KB)</p> 

 [<a href="https://discuss.airbyte.io/t/quickly-run-out-of-storage/2417/8" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment] 2022-09-21 14:05
*Comment made from Zendesk by Marcos Marx on 2022-09-21 at 14:05:*

<blockquote><div class="zd-comment" dir="auto">Did you update to latest version of Airbyte?<br></div></blockquote>

**Comment by marcosmarxm** [comment] 2022-11-15 09:19
*Comment made from Zendesk by Marcos Marx on 2022-11-15 at 09:19:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hi <a href="/u/marcosmarxm" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">@marcosmarxm</a><br>
Follow your introduce above I config variable <code style="background-color: #f9f9f9; padding: 2px 5px">TEMPORAL_HISTORY_RETENTION_IN_DAYS=7</code> in <code style="background-color: #f9f9f9; padding: 2px 5px">.env</code>.<br>
I run <code style="background-color: #f9f9f9; padding: 2px 5px">docker compose up -d</code> more than 7 days but the storage is still full without clean up.</p>
<h2 dir="auto">
<a href="#environment-1" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer"></a>Environment</h2>
<ul style="margin: 0 0 0 10px; padding: 0 0 0 20px" dir="auto">
<li style="padding-bottom: 10px">Airbyte version:  0.40.18</li>
<li style="padding-bottom: 10px">OS Version / Instance: AWS EC2</li>
<li style="padding-bottom: 10px">Deployment: Docker compose</li>
<li style="padding-bottom: 10px">Step where error happened: Deploy with docker compose up</li>
</ul>
<pre style="max-width: 694px; word-wrap: break-word"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px">cat .env
# This file only contains Docker relevant variables.
#
# Variables with defaults have been omitted to avoid duplication of defaults.
# The only exception to the non-default rule are env vars related to scaling.
#
# See https://github.com/airbytehq/airbyte/blob/master/airbyte-config/config-models/src/main/java/io/airbyte/config/Configs.java
# for the latest environment variables.
#
# # Contributors - please organise this env file according to the above linked file.


### SHARED ###
VERSION=0.40.18

# When using the airbyte-db via default docker image
CONFIG_ROOT=/data
DATA_DOCKER_MOUNT=airbyte_data
DB_DOCKER_MOUNT=airbyte_db

# Workspace storage for running jobs (logs, etc)
WORKSPACE_ROOT=/tmp/workspace
WORKSPACE_DOCKER_MOUNT=airbyte_workspace

# Local mount to access local files from filesystem
# todo (cgardens) - when we are mount raw directories instead of named volumes, *_DOCKER_MOUNT must
# be the same as *_ROOT.
# Issue: https://github.com/airbytehq/airbyte/issues/578
LOCAL_ROOT=/tmp/airbyte_local
LOCAL_DOCKER_MOUNT=/tmp/airbyte_local
# todo (cgardens) - hack to handle behavior change in docker compose. *_PARENT directories MUST
# already exist on the host filesystem and MUST be parents of *_ROOT.
# Issue: https://github.com/airbytehq/airbyte/issues/577
HACK_LOCAL_ROOT_PARENT=/tmp

# Proxy Configuration
# Set to empty values, e.g. "" to disable basic auth
BASIC_AUTH_USERNAME=airbyte
BASIC_AUTH_PASSWORD=password

### DATABASE ###
# Airbyte Internal Job Database, see https://docs.airbyte.io/operator-guides/configuring-airbyte-db
DATABASE_USER=docker
DATABASE_PASSWORD=docker
DATABASE_HOST=db
DATABASE_PORT=5432
DATABASE_DB=airbyte
# translate manually DATABASE_URL=jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_DB} (do not include the username or password here)
DATABASE_URL=jdbc:postgresql://db:5432/airbyte
JOBS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=0.29.15.001

# Airbyte Internal Config Database, defaults to Job Database if empty. Explicitly left empty to mute docker compose warnings.
CONFIG_DATABASE_USER=
CONFIG_DATABASE_PASSWORD=
CONFIG_DATABASE_URL=
CONFIGS_DATABASE_MINIMUM_FLYWAY_MIGRATION_VERSION=0.35.15.001

### AIRBYTE SERVICES ###
TEMPORAL_HOST=airbyte-temporal:7233
INTERNAL_API_HOST=airbyte-server:8001
#CONNECTOR_BUILDER_API_HOST=airbyte-connector-builder-server:80 #FIXME: Uncomment this when enabling the connector-builder
WEBAPP_URL=http://localhost:8000/
# Although not present as an env var, required for webapp configuration.
API_URL=/api/v1/

### JOBS ###
# Relevant to scaling.
SYNC_JOB_MAX_ATTEMPTS=3
SYNC_JOB_MAX_TIMEOUT_DAYS=3
JOB_MAIN_CONTAINER_CPU_REQUEST=
JOB_MAIN_CONTAINER_CPU_LIMIT=
JOB_MAIN_CONTAINER_MEMORY_REQUEST=
JOB_MAIN_CONTAINER_MEMORY_LIMIT=

NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_LIMIT=
NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_REQUEST=
NORMALIZATION_JOB_MAIN_CONTAINER_CPU_LIMIT=
NORMALIZATION_JOB_MAIN_CONTAINER_CPU_REQUEST=

### LOGGING/MONITORING/TRACKING ###
TRACKING_STRATEGY=segment
JOB_ERROR_REPORTING_STRATEGY=logging
# Although not present as an env var, expected by Log4J configuration.
LOG_LEVEL=INFO


### APPLICATIONS ###
# Worker #
WORKERS_MICRONAUT_ENVIRONMENTS=control-plane
# Cron #
CRON_MICRONAUT_ENVIRONMENTS=control-plane
# Relevant to scaling.
MAX_SYNC_WORKERS=5
MAX_SPEC_WORKERS=5
MAX_CHECK_WORKERS=5
MAX_DISCOVER_WORKERS=5
# Temporal Activity configuration
ACTIVITY_MAX_ATTEMPT=
ACTIVITY_INITIAL_DELAY_BETWEEN_ATTEMPTS_SECONDS=
ACTIVITY_MAX_DELAY_BETWEEN_ATTEMPTS_SECONDS=
WORKFLOW_FAILURE_RESTART_DELAY_SECONDS=
TEMPORAL_HISTORY_RETENTION_IN_DAYS=7

### FEATURE FLAGS ###
AUTO_DISABLE_FAILING_CONNECTIONS=false
FORCE_MIGRATE_SECRET_STORE=false

### MONITORING FLAGS ###
# Accepted values are datadog and otel (open telemetry)
METRIC_CLIENT=
# Useful only when metric client is set to be otel. Must start with http:// or https://.
OTEL_COLLECTOR_ENDPOINT="http://host.docker.internal:4317"

USE_STREAM_CAPABLE_STATE=true
</code></pre>
<pre style="max-width: 694px; word-wrap: break-word"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px">ls -lah airbyte_workspace
..............
drwxr-xr-x    3 root root   4096 Nov  4 03:39 8290/
drwxr-xr-x    3 root root   4096 Nov  4 04:02 8291/
drwxr-xr-x    3 root root   4096 Nov  4 04:02 8292/
drwxr-xr-x    3 root root   4096 Nov  4 04:02 8293/
drwxr-xr-x    3 root root   4096 Nov  4 04:02 8294/
drwxr-xr-x    3 root root   4096 Nov  4 04:03 8295/
drwxr-xr-x    3 root root   4096 Nov  4 04:09 8296/
drwxr-xr-x    3 root root   4096 Nov  4 04:30 8297/
drwxr-xr-x    3 root root   4096 Nov  4 04:32 8298/
drwxr-xr-x    3 root root   4096 Nov  4 04:32 8299/
..............
</code></pre> 

 [<a href="https://discuss.airbyte.io/t/quickly-run-out-of-storage/2417/9" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by attaxia** [comment] 2022-11-16 09:23
I can confirm that setting TEMPORAL_HISTORY_RETENTION_IN_DAYS does not have the expected effect. I also checked the logs and don't see any [entries indicating the cleanup has started](https://github.com/airbytehq/airbyte/blob/558bc6df6bd3f7559ee78fda3a4af25d87cc7cc0/airbyte-cron/src/main/java/io/airbyte/cron/selfhealing/WorkspaceCleaner.java#L38).

**Comment by marcosmarxm** [comment] 2022-11-21 20:20
@attaxia can you open a new issue to discuss the problem?

**Comment by marcosmarxm** [comment] 2022-11-21 20:23
*Comment made from Zendesk by Marcos Marx on 2022-11-21 at 20:23:*

<blockquote><div class="zd-comment" dir="auto">Sorry the delay here Arash and Quân, I'll need take a deeper look during the week.<br></div></blockquote>

**Comment by marcosmarxm** [comment] 2022-12-01 20:06
*Comment made from Zendesk by Marcos Marx on 2022-12-01 at 20:06:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">It seems for me the issue lies in <code style="background-color: #f9f9f9; padding: 2px 5px">/var/lib/docker</code>, which I also can’t seem to access without sudo permissions.</p> 

 [<a href="https://discuss.airbyte.io/t/quickly-run-out-of-storage/2417/11" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment] 2022-12-02 18:13
*Comment made from Zendesk by Marcos Marx on 2022-12-02 at 18:13:*

<blockquote><div class="zd-comment" dir="auto">Are you have issues with storage in latest version Lucas?<br></div></blockquote>

**Comment by marcosmarxm** [comment] 2022-12-05 05:43
*Comment made from Zendesk by Marcos Marx on 2022-12-05 at 05:43:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hey <a href="/u/marcosmarxm" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">@marcosmarxm</a> I bumped disk to 60gb, and am going to set that variable <code style="background-color: #f9f9f9; padding: 2px 5px">TEMPORAL_HISTORY_RETENTION_IN_DAYS=7</code> to see if that solves it. I was migrating a 700M row size table and that was taking up all 30gb of previous disk.</p>
<p dir="auto">I resolved the issue by doubling disk size and turning off all other connections while I ran the backfill on the 700M table. It would be great to know a better solution but disk is cheap.</p> 

 [<a href="https://discuss.airbyte.io/t/quickly-run-out-of-storage/2417/13" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment] 2023-01-16 14:51
*Comment made from Zendesk by Marcos Marx on 2023-01-16 at 14:51:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto"><a href="/u/marcosmarxm" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">@marcosmarxm</a> Any word on a fix for this yet?</p>
<p dir="auto">I’ve attempted to set TEMPORAL_HISTORY_RETENTION_IN_DAYS=7 but this has had no effect.</p> 

 [<a href="https://discuss.airbyte.io/t/quickly-run-out-of-storage/2417/15" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment] 2023-01-16 14:52
*Comment made from Zendesk by Marcos Marx on 2023-01-16 at 14:52:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Typo in the version number here, 0.45.5 does not exist yet.</p> 

 [<a href="https://discuss.airbyte.io/t/quickly-run-out-of-storage/2417/16" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment] 2023-01-17 09:08
*Comment made from Zendesk by Marcos Marx on 2023-01-17 at 09:07:*

<blockquote><div class="zd-comment" dir="auto">Hello Billy the PR <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/pull/20317">https://github.com/airbytehq/airbyte/pull/20317</a> renabled the log rotation for Airbyte 0.40.26 version. Can you check you're using this or later version?<br></div></blockquote>

**Comment by marcosmarxm** [comment] 2023-01-17 09:29
*Comment made from Zendesk by Marcos Marx on 2023-01-17 at 09:28:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hey <a href="/u/marcosmarxm" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">@marcosmarxm</a> , I can confirm i’m using version 0.40.22.<br>
I will upgrade to latest ( <a href="https://github.com/airbytehq/airbyte/releases/tag/v0.40.28" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none">v0.40.28</a> and report back.</p> 

 [<a href="https://discuss.airbyte.io/t/quickly-run-out-of-storage/2417/18" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment] 2023-01-17 10:07
*Comment made from Zendesk by Marcos Marx on 2023-01-17 at 10:06:*

<blockquote><div class="zd-comment" dir="auto">Please update to version 0.40.26 version see PR <a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/pull/20317">https://github.com/airbytehq/airbyte/pull/20317</a><br></div></blockquote>

**Comment by marcosmarxm** [comment] 2023-01-17 11:17
*Comment made from Zendesk by Marcos Marx on 2023-01-17 at 11:17:*

<blockquote><div class="zd-comment" dir="auto"><blockquote style="background-color: #f8f8f8; border-left-color: #e9e9e9; border-left-style: solid; border-left-width: 5px; margin: 0 0 10px; padding: 12px 25px 2px 12px">

<img alt="" width="20" height="20" src="https://sea2.discourse-cdn.com/business7/user_avatar/discuss.airbyte.io/marcosmarxm/40/37_2.png" style="height: 20px; margin-right: 5px; vertical-align: middle; width: 20px"> marcosmarxm:
<p style="padding: 0" dir="auto">Hello Billy the PR <a href="https://github.com/airbytehq/airbyte/pull/20317" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none">Airbyte Cron: renable schedule to file cleaner by marcosmarxm · Pull Request #20317 · airbytehq/airbyte · GitHub</a> renabled the log rotation for Airbyte 0.40.26 version. Can you check you’re using this or later version?</p>
</blockquote>
<p dir="auto">Upgrading from 0.40.22 to 0.40.28 has resolved the issue where setting TEMPORAL_HISTORY_RETENTION_IN_DAYS= had no affect.</p>
<p dir="auto">Thanks <a href="/u/marcosmarxm" style="color: #006699; font-weight: bold; text-decoration: none" rel="noreferrer">@marcosmarxm</a></p> 

 [<a href="https://discuss.airbyte.io/t/quickly-run-out-of-storage/2417/19" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by CamPen21** [comment] 2023-10-13 21:58
Hey Guys, question, my EC2 instance got full due to airbyte logs. I hadn't set the TEMPORAL_HISTORY_RETENTION_IN_DAYS option.
How can I manually free up space safely?
The stack won't start because the DB doesn't have any more space.
Thank you.
