### ISSUE TITLE
[Connector builder] support record transformations

### ISSUE THREAD

**Issue by girarda** [airbytehq/airbyte#20778] opened 2022-12-21 22:45 UTC
## Tell us about the problem you're trying to solve
The low-code framework supports record transformations

examples:
### Adding a field
```
stream:
  <...>
  transformations:
      - type: AddFields
        fields:
          - path: [ "field1" ]
            value: "static_value"
```

### Removing a field
```
the_stream:
  <...>
  transformations:
      - type: RemoveFields
        field_pointers:
          - [ "path", "to", "field1" ]
          - [ "path2" ]
```

[Link to documentation](https://docs.airbyte.com/connector-development/config-based/understanding-the-yaml-file/record-selector#transformations)

## Describe the solution you’d like
The connector builder should support record transformations

**Comment by flash1293** [comment] 2023-03-24 15:57
Duplicate of https://github.com/airbytehq/airbyte/issues/21187

**Closed by flash1293** 2023-03-24 15:57 UTC
Labels: type/enhancement, team/extensibility, ui/connector-builder
