### ISSUE TITLE
Connector builder UI: Allow configuring page number injection on first request

### ISSUE THREAD

**Issue by flash1293** [airbytehq/airbyte#31101] opened 2023-10-05 14:05 UTC
### What area the feature impact?

Airbyte Platform

### Relevant Information

With https://github.com/airbytehq/airbyte/pull/30978 merged, the low code CDK now supports to inject the page number on the first request as well.

This should be exposed as a an additional flag in the connector builder UI as well (in the "advanced options" section)

**Comment by flash1293** [comment] 2023-10-30 16:02
+1 from a customer

**Comment by lmossman** [comment] 2023-11-07 17:54
Duplicate of https://github.com/airbytehq/airbyte/issues/30987

**Closed by lmossman** 2023-11-07 17:54 UTC
Labels: type/enhancement, needs-triage, team/extensibility
