### ISSUE TITLE
User permissions are being revoked on the tables (destination postgres) 

### ISSUE THREAD

**Issue by keshav-multi** [airbytehq/airbyte#5247] opened 2021-08-06 14:15 UTC
I  have added another user in my database which has only read privileges on only some tables that are synced by airbyte. Those permissions are getting revoked after sync. 
 
## Enviroment
- **Airbyte version**:  0.29.2-alpha
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: Docker
- **Severity**: Medium
- **Database**:Postgres -12

## Current Behavior
Other user permissions on another user are getting revoked after sync. 

## Expected Behavior
Permissions of users on tables staying the same and not getting revoked. 

## Steps to Reproduce

1. Connect a source
2. Create a new user in postgres
3. Give the new user read permission on a couple of tables from that source
4. Let the source sync again
5. The privileges given to the user have now been revoked/deleted. 

Asked about the issue on slack too, this was the response by the Admin which helped in identifying the problem. 

> this is happening because the normalization module execute a full refresh and delete the table and recreate from scratch. It's possible to you GRANT SELECT ON ALL TABLES IN SCHEMA airbyte-schema TO non-airbyte-user? It's not ideal and for some cases cant be done.

**Comment by grishick** [comment] 2022-04-19 17:07
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/5247?planning-poker) with ZenHub @tuliren @edgao @subodh1810

**Comment by mfrye** [comment] 2022-06-16 19:05
I'm running into this as well. We already ran our version of `GRANT SELECT ON ALL TABLES IN SCHEMA airbyte-schema TO non-airbyte-user`, so it appears the whole schema is being dropped and not just the tables. 

Airbyte has been great so far, but this is a border line deal breaker for us.

**Comment by grishick** [comment] 2022-06-28 21:34
The description of the issue sounds like permissions are being revoked on the source database. However, normalization runs on destination. @mfrye @keshav-multi can you please confirm the following:
 - source connector type/version
 - destination connector type/version
 - where the permissions are being revoked: source DB or destination DB

**Comment by mfrye** [comment] 2022-06-29 00:35
It doesn't appear that source is a factor. We're using the latest mysql source and a custom source we haven't shared publicly yet.

The destination is Postgres, latest version. Permissions are revoked on the destination DB.

My guess is that with the full refresh option, the entire schema is being dropped vs truncating all the existing tables. If the schema is dropped and recreated, the permissions would disappear.

**Comment by evantahler** [comment] 2023-07-20 18:48
closing in favor of https://github.com/airbytehq/airbyte/issues/28540

**Closed by evantahler** 2023-07-20 18:48 UTC
Labels: type/bug, area/connectors, normalization, connectors/destination/postgres, team/destinations

**Comment by mertalpt** [comment] 2024-03-15 08:10
@evantahler The link is private. Is there any way to tell what has been the resolution to this?

**Comment by laurent-leconte** [comment] 2025-01-28 11:08
This is frustrating... I can confirm the issue is still there, despite this issue and another one (https://github.com/airbytehq/airbyte/issues/15146) having both been closed. Are there any workarounds to fix this?

**Comment by mertalpt** [comment] 2025-01-28 11:19
@laurent-leconte You can use [default privileges](https://www.postgresql.org/docs/current/sql-alterdefaultprivileges.html) so that the replacement table would have the same permissions as the old one.

**Comment by mertalpt** [comment] 2025-02-03 09:52
@laurent-leconte It would be tough to get into a debug session over GitHub comments so I will leave you a final gotcha we had to figure out. The `ALTER DEFAULT PRIVILEGES` command works on an ownership basis. By default, new relations created by whoever ran that query will be granted those privileges to `non_airbyte_user`. If who runs the query is different than the user for the destination connector, you can modify the query so that the default privileges will be for tables owned by the connector user for the `non_airbyte_user`.

IIRC the Postgres destination recreates the schema, so you should not need that but I might be mistaken.
