### ISSUE TITLE
Creating a connection through the destination creation workflow does not work

### ISSUE THREAD

**Issue by avaidyanatha** [airbytehq/airbyte#4893] opened 2021-07-21 20:01 UTC
## Enviroment
- **Airbyte version**:  example is 0.27.3-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker Desktop
- **Source Connector and version**: Not applicable
- **Destination Connector and version**: Not applicable
- **Severity**: High
- **Step where error happened**: Setting up Connection

## Current Behavior
When trying to connect a source and destination, after destination creation, it runs connection checks and asks again to create a destination.

https://user-images.githubusercontent.com/33042053/126552260-a02c6970-a260-4766-9757-74a105d33efe.mov

## Expected Behavior
After destination creation, I should proceed to the connection settings and setup page.

## Steps to Reproduce
1. Create a Source
2. Add a destination to that source when immediately prompted to

**Comment by avaidyanatha** [comment] 2021-07-21 20:06
@cgardens I've been running into this for ages and thought it was just me. Then, a week and a half ago, I saw @michel-tricot run into it too and now I'm suspicious. Do we have an open ticket for this? I'm a little surprised no one has complained about this.

**Comment by avaidyanatha** [comment] 2021-07-21 20:06
cc @marcosmarxm

**Comment by Jamakase** [comment] 2021-07-21 21:53
I have faced the same problem a few times before too and I think I know the root cause. Will try to create a fix for it ASAP.

**Comment by cgardens** [comment] 2021-07-26 16:41
I agree that this is a bug that we should fix quickly. Going to say that we should still focus on cloud stuff on top of it.

**Comment by Jamakase** [comment] 2021-08-12 19:43
Should be fixed in #5323

**Comment by avaidyanatha** [comment] 2021-08-12 19:50
> Should be fixed in #5323

Thanks @Jamakase!

**Closed** 2021-08-13 15:01 UTC
Labels: type/bug, area/frontend, priority/high
