### ISSUE TITLE
CDC Postgres (Incremental | Deduped+history) to BigQuery: deleted_at field is not getting updated for deleted records.

### ISSUE THREAD

**Issue by ameyabhope** [airbytehq/airbyte#11805] opened 2022-04-07 15:28 UTC
## Environment
* **Airbyte version**:  `0.35.56-alpha`
* **OS Version / Instance**: GCP
* **Deployment**: Docker
* **Source Connector and version**: postgres `0.4.9`
* **Destination Connector and version**: BigQuery
* **Severity**: High
* **Step where error happened**: Sync job

## Current Behavior
We’re observing the same replication problem as - [:bug: CDC MySQL (Deduped+history) to Bigquery: deleted_at field is not getting updated for deleted records. · Issue #8830 · airbytehq/airbyte · GitHub](https://github.com/airbytehq/airbyte/issues/8830), for postgres, where if a row is deleted in source, the destination continues to display the row in the replicated table. 

The <table_name>_scd shows _is_airbyte_active column which reflects the deletion, which indicates that there’s a bug in the transformation logic that builds the main table.

## Expected Behavior
Sync job should populate the `_deleted_at` field for syncing when syncing a row which has been deleted at the source.

## Are you willing to submit a PR?
Yes. This is a blocker for us and would be happy to open a PR, if pointed in the right direction.

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537092049) by [Unito](https://www.unito.io)

**Comment by yurii-bidiuk** [comment] 2022-05-23 13:39
Hi @edgao
Looks like this issue has the same root cause as #8830 
Could you please clarify if your [your PR](https://github.com/airbytehq/airbyte/pull/12846) potentially fixes this issue as well?

**Comment by edgao** [comment] 2022-05-23 16:01
Yep, should be the same - do you want to close this as a dup? I updated https://github.com/airbytehq/airbyte/issues/8830's title to reflect that it affects all CDC source -> normalized destination syncs.

**Closed** 2022-06-14 21:56 UTC
Labels: type/bug, area/connectors, normalization, community, connectors/destination/bigquery, connectors/source/postgres, team/databases, autoteam
