### ISSUE TITLE
Source S3: Fails to correctly detect the "master" schema of a CSV file

### ISSUE THREAD

**Issue by niedfelj** [airbytehq/airbyte#6480] opened 2021-09-27 18:39 UTC
## Enviroment
- **Airbyte version**:  0.29.22-alpha
- **OS Version / Instance**:  MacOS 11.6
- **Deployment**: Docker local instance
- **Source Connector and version**: S3 0.1.5
- **Destination Connector and version**:  Redshift 0.3.14
- **Severity**: Critical
- **Step where error happened**: Setup new connection/sync

## Current Behavior
*Tell us what happens.*
It is creating an incorrect master schema which prevents it from doing almost anything (it's inferring columns as integers that are strings). No matter what I do, if it doesn't get the master schema right it fails to load the data into the raw tables.

## Expected Behavior
*Tell us what should happen.*
Why doesn't it just load everything into the raw table as strings, isn't this safer and easier for the LOAD step and then other transformations happen after that? I've even tried giving a schema for one field, just to test it and it still fails because it can't load the original data from the CSV files at all.

## Logs
<details>
<summary>LOG</summary> 

```

airbyte-worker      | 2021-09-27 18:23:48 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(internalLog):110 - {job_log_path=/tmp/workspace/24/0/logs.log} - Syncing stream: airbyte_purchase_test 
airbyte-worker      | 2021-09-27 18:23:48 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(internalLog):110 - {job_log_path=/tmp/workspace/24/0/logs.log} - Iterating S3 bucket 'fltdata-hevo'
airbyte-worker      | 2021-09-27 18:23:48 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):73 - {job_log_path=/tmp/workspace/24/0/logs.log} - 2021-09-27 18:23:48 INFO i.a.i.d.j.JdbcBufferedConsumerFactory(lambda$onStartFunction$1):149 - {} - Preparing tables in destination completed.
airbyte-server      | 2021-09-27 18:23:48 INFO i.a.s.RequestLogger(filter):109 - {workspace_app_root=/tmp/workspace/server/logs} - REQ 172.18.0.4 GET 200 /api/v1/health
airbyte-server      | 2021-09-27 18:23:48 INFO i.a.s.RequestLogger(filter):109 - {workspace_app_root=/tmp/workspace/server/logs} - REQ 172.18.0.4 POST 200 /api/v1/jobs/list - {"configId":"fb4b7c55-b4b5-4361-8c0e-6982dfb9f9c2","configTypes":["sync","reset_connection"]}
airbyte-webapp      | 172.18.0.1 - - [27/Sep/2021:18:23:48 +0000] "POST /api/v1/jobs/list HTTP/1.1" 200 305 "http://localhost:8000/connections/fb4b7c55-b4b5-4361-8c0e-6982dfb9f9c2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36" "-"
airbyte-webapp      | 172.18.0.1 - - [27/Sep/2021:18:23:48 +0000] "GET /api/v1/health HTTP/1.1" 200 11 "http://localhost:8000/connections/fb4b7c55-b4b5-4361-8c0e-6982dfb9f9c2" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36" "-"
airbyte-worker      | 2021-09-27 18:23:49 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(internalLog):110 - {job_log_path=/tmp/workspace/24/0/logs.log} - determined master schema: {'Wholesaler': 'string', 'Account_Number': 'integer', 'Account_Name': 'string', 'Account_Alias': 'string', 'NDC': 'string', 'Supplier_IID': 'string', 'Generic_Name': 'string', 'Trade_Name': 'string', 'Brand_Generic': 'string', 'GPI_Description': 'string', 'Strength': 'string', 'Size': 'string', 'Form': 'string', 'Package_Size': 'string', 'Package_Qty': 'string', 'Total_Package_Quantity': 'number', 'Unit_Dose': 'string', 'UOM': 'string', 'Package_U_M': 'string', 'Manufacturer': 'string', 'AHFS_Number': 'string', 'AHFS_Description': 'string', 'DEA_Schedule_Number': 'string', 'Product_Addl_Description': 'string', 'Unit_Price': 'string', 'Order_Qty': 'string', 'Ship_Qty': 'string', 'Purchase_Dollars': 'string', 'Order_Date': 'string', 'Invoice_Date': 'string', 'PO_Number': 'string', 'Invoice_Number': 'string', 'Contract_Indicator': 'string', 'Contract_Number': 'string', 'Contract_Name': 'string', 'DC_Name': 'string', 'Fineline_Description': 'string', 'GCN': 'string', 'Private_Label_Description': 'string', 'UPC': 'string', 'Product_Active_Status': 'string', 'Order_Entry_Method': 'string', 'PRIMARY_KEY': 'integer'}
airbyte-worker      | 2021-09-27 18:23:49 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$2):223 - {job_log_path=/tmp/workspace/24/0/logs.log} - Records read: 1000
airbyte-worker      | 2021-09-27 18:23:50 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$2):223 - {job_log_path=/tmp/workspace/24/0/logs.log} - Records read: 2000
airbyte-worker      | 2021-09-27 18:23:50 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$2):223 - {job_log_path=/tmp/workspace/24/0/logs.log} - Records read: 3000
airbyte-worker      | 2021-09-27 18:23:50 INFO i.a.w.DefaultReplicationWorker(lambda$getReplicationRunnable$2):223 - {job_log_path=/tmp/workspace/24/0/logs.log} - Records read: 4000
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.w.p.a.DefaultAirbyteStreamFactory(internalLog):108 - {job_log_path=/tmp/workspace/24/0/logs.log} - Encountered an exception while reading stream SourceS3
airbyte-worker      | Traceback (most recent call last):
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 124, in read
airbyte-worker      |     internal_config=internal_config,
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 154, in _read_stream
airbyte-worker      |     for record in record_iterator:
airbyte-worker      |   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 226, in _read_full_refresh
airbyte-worker      |     for record in records:
airbyte-worker      |   File "/airbyte/integration_code/source_s3/source_files_abstract/stream.py", line 355, in read_records
airbyte-worker      |     for record in file_reader.stream_records(f):
airbyte-worker      |   File "/airbyte/integration_code/source_s3/source_files_abstract/formats/csv_parser.py", line 177, in stream_records
airbyte-worker      |     batch = streaming_reader.read_next_batch()
airbyte-worker      |   File "pyarrow/ipc.pxi", line 543, in pyarrow.lib.RecordBatchReader.read_next_batch
airbyte-worker      |   File "pyarrow/error.pxi", line 97, in pyarrow.lib.check_status
airbyte-worker      | pyarrow.lib.ArrowInvalid: In CSV column #1: CSV conversion error to int64: invalid value 'FOH00458A'
airbyte-worker      | 
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} - Traceback (most recent call last):
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -   File "/airbyte/integration_code/main.py", line 33, in <module>
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -     launch(source, sys.argv[1:])
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 125, in launch
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -     for message in source_entrypoint.run(parsed_args):
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py", line 116, in run
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -     for message in generator:
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 128, in read
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -     raise e
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 124, in read
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -     internal_config=internal_config,
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 154, in _read_stream
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -     for record in record_iterator:
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -   File "/usr/local/lib/python3.7/site-packages/airbyte_cdk/sources/abstract_source.py", line 226, in _read_full_refresh
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -     for record in records:
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -   File "/airbyte/integration_code/source_s3/source_files_abstract/stream.py", line 355, in read_records
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -     for record in file_reader.stream_records(f):
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -   File "/airbyte/integration_code/source_s3/source_files_abstract/formats/csv_parser.py", line 177, in stream_records
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -     batch = streaming_reader.read_next_batch()
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -   File "pyarrow/ipc.pxi", line 543, in pyarrow.lib.RecordBatchReader.read_next_batch
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} -   File "pyarrow/error.pxi", line 97, in pyarrow.lib.check_status
airbyte-worker      | 2021-09-27 18:23:50 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/24/0/logs.log} - pyarrow.lib.ArrowInvalid: In CSV column #1: CSV conversion error to int64: invalid value 'FOH00458A'

```

</details>

## Steps to Reproduce
1. Give it a master schema that denotes some column in a csv file as "integer" that actually contains strings.
2. Try to do anything, it will fail.

## Are you willing to submit a PR?
Yes

**Comment by sherifnada** [comment] 2021-10-01 05:31
@niedfelj just to make sure I follow, it is still detecting ints even when you don't provide a master schema?

**Comment by niedfelj** [comment] 2021-10-01 14:37
@sherifnada When I provided a schema override for all of the columns that were being detected incorrectly, it did work. But I was only able to figure that out after reading through the source code to see that that would work. Because even when I tried to just define/pull one field, the load still failed because it was still trying to use the master schema to parse the whole file with the incorrectly detected columns and load them into the "extra data" array. Maybe another good solution would be just to have a setting that says something like "Use string for all columns"

**Comment by Phlair** [comment] 2021-11-05 11:58
Proposing solution:

#### UX
- checkbox in UI for `Infer Datatypes` with description explicitly explaining difference between on/off
    - on would be current behaviour.
    - off would turn off schema inference and parse every value as a string.
    
#### Implementation
- Adding the `Infer Dataypes` toggle to `csv_spec.py` to make it available in the UI.
- Based on the value of the `Infer Datatypes` toggle, `get_inferred_schema()` in `csv_parser.py` can either run through the current schema inference, or alternatively a new non inference flow.
    - this would be propagated and available in the `self._format` dict. 
- The non inference flow could use python's csv lib to read the header _only_ of the file and return `{column: "string" for column in header}`.
    - would need to ensure the read parameters (separator, escape, quote) are used so parsing of the header is accurate.
- Adding relevant test(s) to unit/integration.

**Comment by sherifnada** [comment] 2021-11-08 06:20
@Phlair specifically this would be for CSV files correct? that seems reasonable to me if so. It might also make sense to add another option `Custom schema` but it's not required for closing this particular issue.

**Comment by eliziario** [comment] 2021-11-11 11:47
Hey @Phlair, I am free, is it ok if I go ahead and implement your plan?

**Comment by sherifnada** [comment] 2021-11-12 18:18
@eliziario feel free to reach out to me here as george is taking some time off next week!

**Comment by sherifnada** [comment] 2021-12-24 02:31
@eliziario was this published?

**Comment by eliziario** [comment] 2021-12-30 14:33
> @eliziario was this published?

yes

**Closed by eliziario** 2021-12-30 14:34 UTC
Labels: type/bug, area/connectors

**Comment by MiguelMadero** [comment] 2023-10-07 00:48
Is this working as intended? Or was there a further change? I don't see the checkbox to control type inference and everything is defaulting to a string (behaving as no schema)
