### ISSUE TITLE
Source Trello: not accepting board ids

### ISSUE THREAD

**Issue by shivgargsquad** [airbytehq/airbyte#24775] opened 2023-04-03 04:46 UTC
## Environment
- **Airbyte version**: 0.42.1
- **OS Version / Instance**:  macOS,
- **Deployment**: Docker
- **Source Connector and version**:  Trello 0.3.1
- **Step where error happened**: Setting up Trello connector

## Current Behavior
Not accepting correct board ids
## Expected Behavior
Should Accept correct board ids
## Logs

<img width="630" alt="image" src="https://user-images.githubusercontent.com/95614743/229413673-e66330da-f392-4d42-b1ca-86293a914bb3.png">

**Comment by rob-boltman** [comment] 2023-05-05 15:35
This is due to misunderstanding of what the Board ID is that is required here.
It isn't the 8 character code that is present in the URL of the board (this is known as the 'shortlLink'.
It is the 24 character ID that is returned by eg https://api.trello.com/1/members/me/boards?key="&TrelloAPIKey&"&token="&TrelloAPIToken

(The connector is working correctly, although it would be useful to be able to specify the boards by their "shortLink" attribute as this is easier to obtain).

**Comment by topefolorunso** [comment] 2023-10-08 21:37
I think it's best we stick to the 24-character ID rather than the 8-character. The API returns the 24-character code and the ones extracted from the organization stream are needed to compare with the list from the config. Hence, inputting the 8-character IDs in the config will require getting the corresponding 24-character ID and that might require some complex and breaking changes to the low code.

As an alternative, we can improve the config description so that users are clear on the ID that is required.

cc: @marcosmarxm @shivgargsquad

**Comment by topefolorunso** [comment] 2023-10-09 21:35
Assign this to me please @justinbchau

**Comment by justinbchau** [comment] 2023-10-10 01:47
hey @topefolorunso , you have an issue already assigned to you right now so I will leave this open to give others a chance. If you submit PRs for the other issue and this is still open, I can assign this to you!

**Comment by topefolorunso** [comment] 2023-10-10 10:10
> hey @topefolorunso , you have an issue already assigned to you right now

@justinbchau I am not working on it yet, still getting the clarification. I want to work on other issues while the problem is clarified.

**Closed** 2023-10-13 19:12 UTC
Labels: type/bug, help-welcome, area/connectors, community, connectors/sources-api, connectors/source/trello, team/connectors-python, releaseStage/beta
