### ISSUE TITLE
add a unique connection name 

### ISSUE THREAD

**Issue by ameyabhope** [airbytehq/airbyte#9889] opened 2022-01-29 01:02 UTC
We currently have multiple connections for the same source and destination pair, each having a different set of tables. It'd be great to have them easily identified by a connection name in the UI. This is addition to connection_id will also make working with connections really easy.

**Comment by alafanechere** [comment] 2022-01-31 17:11
Closing because this is a duplicate of https://github.com/airbytehq/airbyte/issues/9737

**Closed by alafanechere** 2022-01-31 17:11 UTC
Labels: type/enhancement, community, needs-triage
