### ISSUE TITLE
Connector Issue: Pipedrive custom fields do not sync

### ISSUE THREAD

**Issue by rbeilvert** [airbytehq/airbyte#25766] opened 2023-05-02 18:20 UTC
### Connector Name

airbyte/source-pipedrive, airbyte/destination-bigquery

### Connector Version

pipedrive 0.1.17, bigquery 1.3.4

### What step the error happened?

Other

### Revelant information

I am replicating the `organizations` and `organization_fields` tables from Pipedrive to BigQuery.

I have a custom organization field called "SIRET" which is present on pipedrive and has a dedicated row in the replicated `organization_fields` table.

However, the SIRET value for each organization in the `organizations` replicated table is nowhere to be found on BigQuery. 

### Contribute

- [ ] Yes, I want to contribute

**Comment by matebaranyi1995** [comment] 2023-08-28 13:27
I would like to add that we have the same issue with syncing Pipedrive (connector version: 1.0.0) to Snowflake (connector version: 2.1.3). (We are trying to set this up for the first time.)

The existence of the custom fields is recorded in the `xxx_fields` tables but their value per record (nor the column itself) is not present in the `xxx` tables, nor in the `_airbyte_raw_xxx` tables. Turning off the basic normalization (and resyncing everything) won't resolve the issue either.

Tested it with `xxx` being deals, organizations, and persons.

I'm unsure if the issue is related to the custom fields in `xxx_fields` not having a human-readable key value (only some alphanumeric value.)

**Comment by moligslagers** [comment] 2023-08-30 13:55
I have the same issue getting the data into S3 / AWS Glue. I have found a workaround with the Octavia CLI (see [here](https://github.com/airbytehq/airbyte/discussions/29702)). The problem seems to be that Airbyte does not automatically detect the custom fields when infering the schema.

**Comment by topefolorunso** [comment] 2023-10-06 22:29
I can work on this @justinbchau. Please assign to me, PR raised for other issues

**Closed** 2023-10-13 14:33 UTC
Labels: type/bug, help-welcome, area/connectors, community, connectors/source/pipedrive, team/connectors-python, autoteam

**Comment by Rasha-Dj** [comment] 2023-10-24 19:23
Hey @topefolorunso I have been trying to set this up with the latest version of airbyte but the custom field values are still not being shown anywhere. They show up in the fields table as metadata, but values aren't anywhere. Is there something that should be additionally done in order for this enhancement to work?
Thanks a lot for working on this.

**Comment by marcosmarxm** [comment] 2023-10-24 20:26
@Rasha-Dj did you confirm you're using the latest version of the connector and update the schema?

**Comment by Rasha-Dj** [comment] 2023-10-26 10:15
@marcosmarxm yes. I did this by ensuring I've pulled latest stable version with git pull, I then rebuilt and restarted my containers. I also ensured my source pipedrive version is `io.airbyte.version=2.2.0`. I deleted all of my tables and restarted the syncing, but I haven't gotten better results. Am I missing anything?
Thank you for your help.

**Comment by topefolorunso** [comment] 2023-10-30 14:15
I will investigate this further. @marcosmarxm can I get credentials for pipedrive?

**Comment by laumc98** [comment] 2024-05-01 22:02
@topefolorunso were u able to find a solution for this?

**Comment by gmzgian** [comment] 2024-05-22 09:59
@topefolorunso Hi there, I am still facing the same problem too. Any updates? Thank you for helping us here.

**Comment by marcosmarxm** [comment] 2024-05-22 13:35
@gmzgian @laumc98 can you opena. new issue?

**Comment by matebaranyi1995** [comment] 2024-05-22 13:53
@marcosmarxm, I opened this one earlier: https://github.com/airbytehq/airbyte/issues/33622; and @laumc98 opened this one: https://github.com/airbytehq/airbyte/issues/37747

**Comment by gmzgian** [comment] 2024-05-22 13:57
> I would like to add that we have the same issue with syncing Pipedrive (connector version: 1.0.0) to Snowflake (connector version: 2.1.3). (We are trying to set this up for the first time.)
> 
> The existence of the custom fields is recorded in the `xxx_fields` tables but their value per record (nor the column itself) is not present in the `xxx` tables, nor in the `_airbyte_raw_xxx` tables. Turning off the basic normalization (and resyncing everything) won't resolve the issue either.
> 
> Tested it with `xxx` being deals, organizations, and persons.

@marcosmarxm  Opened a new one:
https://github.com/airbytehq/airbyte/issues/38557
