### ISSUE TITLE
Source Hubspot: `line_items` association not syncing for `deals` stream even in Full | Overwrite mode

### ISSUE THREAD

**Issue by mattyweb** [airbytehq/airbyte#20624] opened 2022-12-17 19:08 UTC
Using current Airbyte: v0.40.25
...and current Hubspot connector: v0.30.0
(can repro running locally on Docker with a Postgres target on latest connector version)

## Current Behavior

When running the deals stream the line_items association for deals is NULL for all records. Can confirm that our Hubspot instance has line_items for some deals by looking at the HubSpot API endpoints. Other associations are loading just fine (contacts and companies).

Here's a query of the normalized output table:
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/10199792/208257357-123b1457-89df-416c-b773-05ebb9b854b8.png">

## Expected Behavior

Expect the line_items to be populated for those deals that have them.

## Logs

2022-12-17 17:45:48 source > Syncing stream: deals 
2022-12-17 17:45:53 source > Advancing bookmark for deals stream from None to 2022-12-17T14:00:14.717000+00:00
2022-12-17 17:45:53 source > Read 555 records from deals stream
2022-12-17 17:45:53 source > Finished syncing SourceHubspot

## Are you willing to submit a PR?

Yes

**Comment by marcosmarxm** [comment] 2022-12-19 20:57
@mattyweb the issue is similar to https://github.com/airbytehq/airbyte/issues/14390 right?

**Comment by mattyweb** [comment] 2022-12-26 14:07
> @mattyweb the issue is similar to #14390 right?

I looked at that one. It's similar but it says that NONE of the associations work when in incremental mode including line items, companies, and contacts.

In Full | Overwrite mode the `companies` and `contacts` work but not the `line_items`. I'm happy to use Full syncs so that's what I'm hoping gets fixed so I can use line_items. 

I feel like these are separate issues. Someone who knows the code better might be able to say whether they should be fixed at the same time.

**Comment by artem1205** [comment] 2023-04-07 11:43
Fixed in https://github.com/airbytehq/airbyte/pull/24915

**Closed by artem1205** 2023-04-07 11:43 UTC
Labels: type/bug, community, connectors/source/hubspot, ga, team/connectors-python, autoteam
