### ISSUE TITLE
🐛 Source Facebook Marketing: There have been too many calls to this ad-account.

### ISSUE THREAD

**Issue by mihir-kanzariya** [airbytehq/airbyte#8773] opened 2021-12-14 11:31 UTC
Hey all, I am getting this error after configuring facebook marketing connectors.

```
Status:  400
  Response:
    {
      "error": {
        "message": "(#80004) There have been too many calls to this ad-account. Wait a bit and try again. For more info, please refer to https://developers.facebook.com/docs/graph-api/overview/rate-limiting.",
        "type": "OAuthException",
        "code": 80004,
        "error_subcode": 2446079,
        "fbtrace_id": "AFm-w0VSqFxoRyuKXJgg48H"
      }
    }
```

When I check it also says it also says 
`Utilization is too high (118)%, pausing for 47 minutes .`

As per @alafanechere, The connector already has a backoff logic that should avoid the error. Maybe there could be some backoff optimizations to be made.

You can find logs in the attachment.
[logs-1731-0.txt](https://github.com/airbytehq/airbyte/files/7712655/logs-1731-0.txt)

**Comment by alafanechere** [comment] 2021-12-14 15:21
To add more context the Slack discussion can be found [here](https://airbytehq.slack.com/archives/C01MFR03D5W/p1639150133176100).
From Facebook API's documentation, the rate limit is dynamically computed according to the number of ads on the user account. What they are calling the Business Use Case Rate Limits which is documented [here](https://developers.facebook.com/docs/graph-api/overview/rate-limiting#buc-rate-limits). I don't think our connector is handling this dynamic rate limit and it might be the root cause of the error encountered by @mihir-kanzariya .

**Comment by sherifnada** [comment] 2021-12-15 09:10
@mihir-kanzariya do you have the advanced access token tier enabled like described in [this section? ](https://docs.airbyte.io/integrations/sources/facebook-marketing#request-rate-limit-increase)

**Comment by alafanechere** [comment] 2021-12-15 09:14
@sherifnada I asked @mihir-kanzariya on Slack to upgrade his app to the advanced access token tier.

**Comment by misteryeo** [comment] 2022-01-06 03:34
@alafanechere @mihir-kanzariya following up here to see if the advanced access token being enabled fixes this issue or it still persists?

**Comment by misteryeo** [comment] 2022-01-12 01:50
Closing this issue since there's no response from @mihir-kanzariya - feel let us know if we need to re-open this.

**Comment by wub** [comment] 2022-08-14 05:02
Hey @misteryeo, we're encountering this issue even with advanced access to ads_read, so I imagine @alafanechere's hypothesis is correct re: BUC rate limits.

**Comment by misteryeo** [comment] 2022-09-13 21:00
Sorry for the delay here folks - @YowanR can you take a look at this with the team?

**Comment by YowanR** [comment] 2022-09-13 21:52
@davydov-d @lazebnyi Adding this to our backlog for prioritization.
Cc @YuliiaNahoha

**Comment by plorenzatto** [comment] 2022-09-14 17:54
We had some progress by splitting the source in multiple ones each with campaigns from a different region. We suppose that this worked because of the lower number of concurrent requests which may be an issue when fetching a large number of records to fill a large lookup window.
If that's the case I would suggest adding a way to control fetching concurrency or at least adding some indications on how to resolve the issue in the error message.

**Comment by tinomerl** [comment] 2022-12-01 11:26
@plorenzatto what did you do for the screencast for the advanced access? Did you show your Airbyte Syncs and the dashboards for the data? And did you use the custom Insights for splitting the source up?

**Comment by midavadim** [comment] 2023-09-20 20:08
This is should be fixed by this PR: https://github.com/airbytehq/airbyte/pull/29994

There we removed batch processing for a lot of streams

**Closed by midavadim** 2023-09-20 20:08 UTC
Labels: type/bug, area/connectors, community, connectors/sources-api, connectors/source/facebook-marketing, team/tse, autoteam, team/use
