### ISSUE TITLE
Introduce Substreams

### ISSUE THREAD

**Issue by eugene-kulak** [airbytehq/airbyte#1315] opened 2020-12-14 00:16 UTC
I haven't found an existing ticket or discussion...

## Tell us about the problem you're trying to solve
Many APIs have One-To-Many relations between entities. Unfortunately, not every dependent entity can be retrieved directly (without specifying parent ID, etc). 
For example, Drift API has [Conversations and Messages](https://devdocs.drift.com/docs/conversation-model)

## Describe the solution you’d like
I see a few problems here that need to be solved in order to support nested streams.

1. Somehow be able to configure each stream/substream individually in the source (UI)
1. Somehow be able to initiate reading from substream during the reading from the parent stream

## Describe the alternative you’ve considered or used
This is more like a question - do we need a new abstraction (substream?) here or not? I see some key differences from the current stream abstraction, but maybe if there is a way to extend existing streams I'm ok with it.

## Additional context
| . |Streams | Substreams|
|----|----|----|
|Retrive  | yes | needs some external ID, can be retrieved in batches (per parent)|
|Update | maybe | updates propagated through a parent entity|
|Delete | maybe | updates propagated through a parent entity|

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368202261046) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment] 2020-12-22 14:41
Thanks, this might be a duplicate of what I call nested data in #886

**Comment by girarda** [comment] 2022-12-22 10:53
done

**Closed by girarda** 2022-12-22 10:53 UTC
Labels: type/enhancement, area/connectors, team/extensibility, autoteam
