### ISSUE TITLE
Get a connector spec hangs indefinitely

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1462] opened 2020-12-28 21:51 UTC
## Expected Behavior
When I start the onboarding process for Airbyte I expect the configuration parameters for the connector I choose to be loaded. 

## Current Behavior
The UI is stuck with the message "Loading required parameters for Postgres". 

![image](https://user-images.githubusercontent.com/6246757/103244955-6e612a80-4913-11eb-9ce5-207dc3e3a27e.png)

## Steps to Reproduce
This issue hasn't been reproducible by any of the Airbyte maintainers but two users have reported it thus far in Slack. The way to reproduce it on their machines is: 

1. Start up a fresh instance of Airbyte and choose a source connector
1. Some connectors load their parameters and some hang indefinitely

## Severity of the bug for you
High. This blocks users from using Airbyte. 

## Additional context
reported on v0.9.0 and v0.9.1

**Comment by sherifnada** [comment] 2020-12-28 21:52
The logs for one of the failing get spec jobs (github connector) running in v0.9.1 contained the following: 

```
2020-12-28 06:39:36 INFO (/tmp/workspace/12/0) WorkerRun(call):58 - Executing worker wrapper...
2020-12-28 06:40:36 ERROR (/tmp/workspace/12/0) DefaultGetSpecWorker(run):97 - Error while getting spec from image airbyte/source-github-singer:0.1.4: java.lang.IllegalThreadStateException: process hasn't exited
```

**Comment by sherifnada** [comment] 2020-12-29 03:14
I was able to reliably reproduce this issue with the following: 

1. Install [throttle](https://www.sitespeed.io/documentation/throttle/)
2. Run `throttle --up 330 --down 780 --rtt 200` to simulate slow network conditions
3. Run a fresh instance of airbyte `docker-compose down -v && docker-compose up`
4. Choose postgres as the source connector (it's 440mb so won't be downloaded in time) 
5. 💣

**Comment by sherifnada** [comment] 2020-12-29 03:24
I've created #1466 to provide users with guidance for now. Ideally we either:
1. show a progress bar on the UI (maybe) but for now it's easier to tell them to interact with the Docker CLI directly. 
2. Detect connectivity ourselves and display a warning on the UI

**Comment by jrhizor** [comment] 2020-12-30 23:16
So this is just happening if it takes >2min to load? And `WorkerUtils.gentleClose` is unable to guarantee that the process has an exit code immediately afterwards? 

We should be more forceful about closing non-sync workers and increase this timeout.

**Comment by jrhizor** [comment] 2020-12-30 23:22
We also probably need a UI fix to prevent this from looking like it's hanging if it is actually still running. 

> show a progress bar on the UI (maybe)
This seems difficult, especially since the loading happens during a different part of the lifecycle on different platforms like Kubernetes.

> Detect connectivity ourselves and display a warning on the UI
We should design the processes behind the scene and the comments in the UI so they make sense for all connectivities.

Maybe showing the logs on this screen in some way would make it more clear?  I also don't know what the server timeouts are for connections. Maybe they're timing out when they shouldn't?

**Comment by gordalina** [comment] 2021-01-16 20:59
I can reproduce this every time in 0.10.0

Heres the logs:

```
airbyte-server | Jan 16, 2021 8:55:00 PM org.glassfish.jersey.logging.LoggingInterceptor log
airbyte-server | INFO: 436 * Server has received a request on thread qtp1802736936-22
airbyte-server | 436 > POST http://localhost:8001/api/v1/source_definition_specifications/get
airbyte-server | 436 > Accept: */*
airbyte-server | 436 > Content-Length: 62
airbyte-server | 436 > Content-Type: application/json
airbyte-server | 436 > Host: localhost:8001
airbyte-server | 436 > User-Agent: curl/7.64.1
airbyte-server | {"sourceDefinitionId": "decd338e-5647-4c0b-adf4-da0e75f5a750"}
airbyte-server |
airbyte-server | 2021-01-16 20:55:00 DEBUG i.a.s.c.SpecCachingSchedulerJobClient(createGetSpecJob):60 - {} - cache miss: airbyte/source-postgres:0.1.6
airbyte-server | 2021-01-16 20:55:00 INFO i.a.s.p.DefaultJobPersistence(enqueueJob):100 - {} - enqueuing pending job for scope: airbyte/source-postgres:0.1.6
airbyte-server | 2021-01-16 20:55:00 INFO i.a.s.c.DefaultSchedulerJobClient(waitUntilJobIsTerminalOrTimeout):113 - {} - Waiting for job id: 1062
airbyte-server | 2021-01-16 20:57:00 DEBUG i.a.s.e.UncaughtExceptionMapper(toResponse):42 - {} - Uncaught exception
airbyte-server | java.lang.RuntimeException: Check connection job did not complete.
airbyte-server | 	at io.airbyte.scheduler.client.DefaultSchedulerJobClient.waitUntilJobIsTerminalOrTimeout(DefaultSchedulerJobClient.java:128) ~[io.airbyte-airbyte-scheduler-0.10.0-alpha.jar:?]
airbyte-server | 	at io.airbyte.scheduler.client.DefaultSchedulerJobClient.createGetSpecJob(DefaultSchedulerJobClient.java:73) ~[io.airbyte-airbyte-scheduler-0.10.0-alpha.jar:?]
airbyte-server | 	at io.airbyte.scheduler.client.SpecCachingSchedulerJobClient.createGetSpecJob(SpecCachingSchedulerJobClient.java:61) ~[io.airbyte-airbyte-scheduler-0.10.0-alpha.jar:?]
airbyte-server | 	at io.airbyte.server.handlers.SchedulerHandler.getConnectorSpecification(SchedulerHandler.java:195) ~[io.airbyte-airbyte-server-0.10.0-alpha.jar:?]
airbyte-server | 	at io.airbyte.server.handlers.SchedulerHandler.getSourceDefinitionSpecification(SchedulerHandler.java:175) ~[io.airbyte-airbyte-server-0.10.0-alpha.jar:?]
airbyte-server | 	at io.airbyte.server.apis.ConfigurationApi.lambda$getSourceDefinitionSpecification$6(ConfigurationApi.java:177) ~[io.airbyte-airbyte-server-0.10.0-alpha.jar:?]
airbyte-server | 	at io.airbyte.server.apis.ConfigurationApi.execute(ConfigurationApi.java:390) ~[io.airbyte-airbyte-server-0.10.0-alpha.jar:?]
airbyte-server | 	at io.airbyte.server.apis.ConfigurationApi.getSourceDefinitionSpecification(ConfigurationApi.java:177) ~[io.airbyte-airbyte-server-0.10.0-alpha.jar:?]
airbyte-server | 	at jdk.internal.reflect.GeneratedMethodAccessor26.invoke(Unknown Source) ~[?:?]
airbyte-server | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
airbyte-server | 	at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
airbyte-server | 	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[jersey-server-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[jersey-server-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[jersey-server-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[jersey-server-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) [jersey-server-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) [jersey-common-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) [jersey-common-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) [jersey-common-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) [jersey-common-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) [jersey-common-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) [jersey-common-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) [jersey-server-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) [jersey-server-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) [jersey-container-servlet-core-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) [jersey-container-servlet-core-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) [jersey-container-servlet-core-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) [jersey-container-servlet-core-2.31.jar:?]
airbyte-server | 	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) [jersey-container-servlet-core-2.31.jar:?]
airbyte-server | 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) [jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569) [jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) [jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.server.Server.handle(Server.java:501) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) [jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) [jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) [jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
airbyte-server | 	at java.lang.Thread.run(Thread.java:832) [?:?]
airbyte-server | Jan 16, 2021 8:57:00 PM org.glassfish.jersey.logging.LoggingInterceptor log
airbyte-server | INFO: 436 * Server responded with a response on thread qtp1802736936-22
airbyte-server | 436 < 500
airbyte-server | 436 < Access-Control-Allow-Headers: Origin, Content-Type, Accept
airbyte-server | 436 < Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS, HEAD
airbyte-server | 436 < Access-Control-Allow-Origin: *
airbyte-server | 436 < Content-Type: application/json
airbyte-server | {"message":"internal server error"}
airbyte-server |
airbyte-scheduler | 2021-01-16 20:57:03 INFO i.a.s.JobRetrier(run):54 - {} - Running job-retrier...
```

**Comment by sherifnada** [comment] 2021-01-17 05:58
@gordalina one of the main causes of this issue has been fixed in v0.11.0-alpha (#1622) . Would you be able to upgrade and verify if you can still reproduce?

**Closed** 2021-01-19 19:56 UTC
Labels: priority/high, type/bug

**Comment by gordalina** [comment] 2021-01-19 22:37
Is there any issue when just changing the image from 10 to 11 in docker compose? is there any migrations requirements?

**Comment by sherifnada** [comment] 2021-01-19 23:31
@gordalina 

URL for the changelog: https://github.com/airbytehq/airbyte/blob/master/docs/changelog/platform.md


> Are there any issue when just changing the image from 10 to 11 in docker compose?
> Are there any migrations requirements?

v11 contains a breaking change, so you would need to remove your currently setup volumes by running: 
```
docker-compose down -v
rm .env docker-compose.yaml 
wget https://raw.githubusercontent.com/airbytehq/airbyte/master/{.env,docker-compose.yaml} # or curl if wget not available
docker-compose up
```
**Note that this will remove your setup sources/destinations/connections**. We're actively working on a graceful migration capability so you don't have to do this in the future and expect to release it next week. So hopefully this will be the last time you need to do something like this.

**Comment by gordalina** [comment] 2021-01-20 16:59
Can confirmed this is solved in master. Thank you
