### ISSUE TITLE
Source/Destination/Last sync/Status data disappeared from destination/source overview grid when one of destination/source was dropped

### ISSUE THREAD

**Issue by SofiiaZaitseva** [airbytehq/airbyte#15613] opened 2022-08-12 16:29 UTC
## Environment
- **Airbyte version**:  0.39.34-alpha
- **OS Version / Instance**: macOS
- **Deployment**: Docker
- **Step where error happened**: Update connector

## Current Behavior
Deleted source disappeared from grid. Source, Last sync, Status for existing sources doesn't appeared.
<img width="1329" alt="Screenshot 2022-08-12 at 18 25 07" src="https://user-images.githubusercontent.com/108751383/184401932-0a98d839-7649-4c53-8f4a-27a7f0475611.png">
After refreshing page all data displayed correctly.

## Expected Behavior
Deleted source disappeared from grid. All existing source and their destinations displayed with the same view as before dropping.

## Preconditions
Several sources with connection created
<img width="1317" alt="Screenshot 2022-08-12 at 18 22 54" src="https://user-images.githubusercontent.com/108751383/184401162-48884c00-8a32-4939-b028-1efa76a39789.png">

## Steps to Reproduce
1. Go to Source page
2. Drop one of the source
3. Check Source grid

Note: the same behaviour for the Destination!

**Comment by octavia-squidington-iii** [comment] 2022-08-12 16:29
cc @airbytehq/frontend

**Comment by tealjulia** [comment] 2022-08-12 16:38
Noting that there's a duplicate of this issue in cloud (https://github.com/airbytehq/airbyte-cloud/issues/2341)

**Comment by robgleason** [comment] 2022-08-23 21:42
I was planning on making a PR for this, and I thought it looked like an interesting issue. I like the PR that @edmundito made for this!

**Closed** 2022-08-29 13:08 UTC
Labels: type/bug, area/platform, needs-triage, team/frontend, ui/connectors
