### ISSUE TITLE
Failed sync overwrite destination

### ISSUE THREAD

**Issue by TSkrebe** [airbytehq/airbyte#11251] opened 2022-03-18 06:27 UTC
## Environment
- **Airbyte version**:  0.35.12-alpha
- **Deployment**: kubernetes
- **Source Connector and version**: mixpanel 0.1.9
- **Destination Connector and version**: bigquery 0.6.1
- **Severity**:  High
- **Step where error happened**: Sync job 

## Current Behavior
Mixpanel <> bigquery "full-refresh overwrite" sync failed and it overwrote destination with an empty file.

## Expected Behavior
Destination should not be changed if sync failed.

## Logs
[logs-626.txt](https://github.com/airbytehq/airbyte/files/8302089/logs-626.txt)

**Comment by octavia-squidington-iii** [comment] 2022-03-30 01:04
Marcos Marx commented: Thanks for opening the isse @TSkrebe, team will investigate further.

**Comment by octavia-squidington-iii** [comment] 2022-03-30 01:12
Marcos Marx commented: Another test.

**Comment by octavia-squidington-iii** [comment] 2022-03-30 01:12
Marcos Marx commented: Testing

**Comment by roman-romanov-o** [comment] 2022-05-24 20:51
@TSkrebe, hello!
 Is bug still reproduces for you? (I could not reproduce it)

And additional question is about `sync failed and it overwrote destination with an empty file.`:
Since destination is BigQuery, did you mean that whole table were overrided by empty table?

**Comment by davydov-d** [comment] 2022-05-25 10:23
I've made (mocking the error) the connection Mixpanel => CSV rewrite the destination file with empty body as it was in the bug report. This means we have a bug in platform when destination is overwritten with empty body if the source connector throws exception and the sync mode is full refresh - overwrite. @sherifnada @misteryeo 

Still I could not reproduce the source sync fail, neither using version 0.1.9, nor 0.1.15. @TSkrebe could you please confirm the problem persists?

**Comment by davydov-d** [comment] 2022-05-30 14:34
the platform issue is now described in the separate ticket https://github.com/airbytehq/airbyte/issues/13312

I'm closing this one now since no one has confirmed the issue in the source persists for six days already. If you'r lucky to reproduce it - feel free to reopen the issue

**Closed by davydov-d** 2022-05-30 14:34 UTC
Labels: type/bug, team/connectors-python, autoteam
