### ISSUE TITLE
create easy workflow for publishing webapp to a dev cluster

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#9493] opened 2022-01-13 23:15 UTC
Right now to test out a frontend-only change on cloud you have to either do a full release process or you need to build a version of OSS locally, update the cloud webapp to use it, build the cloud webapp, push the webapp to the repo, and then deploy.

Ideally there would be a way to just deploy this from a branch on master.

This is a specific use case for the more general "easier releases" problem set.

**Comment by davinchia** [comment] 2022-01-14 14:50
Staging = the staging GKE cluster or any GKE cluster?

**Comment by jrhizor** [comment] 2022-01-14 17:20
Oops, renamed to "a dev cluster". Any GKE cluster really.

**Comment by davinchia** [comment] 2022-05-23 08:46
This is essentially a duplicate of https://github.com/airbytehq/airbyte-cloud/issues/1550.

**Closed by davinchia** 2022-05-23 08:46 UTC
Labels: type/enhancement, area/frontend, build, area/platform, needs-triage, team/cloud, team/oss
