### ISSUE TITLE
User unable to delete a workspace

### ISSUE THREAD

**Issue by andyjih** [airbytehq/airbyte#12830] opened 2022-05-12 23:06 UTC
Getting a 401 error when attempting to delete a workspace. No user feedback is shown as to why the deletion has failed. 

Loom: https://www.loom.com/share/6348f4e7b5604db2bc968ca16b3857d2

**Comment by octavia-squidington-iii** [comment] 2022-05-12 23:06
cc @airbytehq/frontend

**Comment by timroes** [comment] 2022-05-13 12:48
Duplicate of https://github.com/airbytehq/airbyte-cloud/issues/1475

**Closed by timroes** 2022-05-13 12:48 UTC
Labels: type/bug, area/frontend, team/frontend
