### ISSUE TITLE
[Epic] Multiple Connector Versions (Dynamic / LaunchDarkly + DB)

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#24443] opened 2023-03-24 01:27 UTC

**Comment by pedroslopez** [comment] 2023-04-18 15:30
(forgot to post this here last week)

### Project Update 4/11

:white_check_mark: What's been completed:
General planning of the next steps - there’s a new epic with the next set of issues to get started with.

:seedling: What’s next:
- (In progress) Moving the platform to use the registry types to decouple it from the actor definition types and unblock later stages.
- Define actor definition versions in the database and add config repository methods to work with them.
- Bring Ella onboard and start to divide and conquer

**Comment by pedroslopez** [comment] 2023-04-25 16:14
## Project update 4/25 

:white_check_mark: What's been completed:
- Support for optional spec field when declaring overrides by pulling from the GCS Spec Cache bucket, setting us up to be able to only specify the version tag in launch darkly overrides, and validated this in prod
- PR in review for pulling default versions from the new actor_definition_version_table
- OC and Connector teams successfully used version overrides to validate pre-release connector versions with real customers in prod last week to gain confidence in rollouts and get more information
- Seeding logic for creating/updating actor definition versions in the db when loading definitions is in progress

:books: Learnings and hurdles:
- The complex logic in place for OSS's ActorDefinitionMigrator (updates definitions depending on whether a connector is in use and based on major/minor/patch bump criteria) is making the update to the new seeding behavior that creates - ActorDefinitionVersions more difficult than expected (slowdown)
Initially we assumed that the seeding logic change would be enough to create ActorDefinitionVersions for all connectors (since we load them at boot and in cron), but this will only be true for connectors that airbyte provides via the registry. To fully support custom connectors that users may have added to their database, we'll need to add a data migration to create versions for any existing connector in the db. (issue)
- Flaky and slow platform deploys really accentuate the "suboptimalness" of static version overrides, and users of the static overrides have really been looking forward to not have to deal with this as we move to launch darkly :smile: 

:no_entry: Blockers:
- Still not a hard blocker, but this is coming up real soon: We now have an issue for defining the new SourceDefinition and DestinationDefinition contexts to be able to target properly on the LaunchDarkly side, but Cole has been out on surgery/recovery and we'll need to wait for his approval on the plan before continuing.

:seedling: What's next:
- Wrap up the seeding logic update to create actor definition versions on boot/cron
- Implement User context support for PbA use-case (target by workspace creator)
- Implement version lookup/creation in the database in the ActorDefinitionVersionHelper when processing overrides
- Properly handle actor definition versions for custom connectors

**Comment by pedroslopez** [comment] 2023-05-25 21:23
## Project update 5/23

**:white_check_mark: What's been accomplished:**
- Actor definition version seeding work has been completed and looking good- looking into adding a bit more testing but should be merged today.
- User context support merged.
- LaunchDarkly-based overrides + on-the-fly ADV creation based on overrides is done and working. [PR](https://github.com/airbytehq/airbyte-platform-internal/pull/6769) in review.

**:warning: What got in the way:**
- Slowdowns due to hackdays / project team being out of office

**:no_entry: Blockers:**
- Not a blocker at the moment, but noting that since Ella's out I'll need some reviews on PRs from others on the team to keep moving things forward

**:seedling: What's next:**
- Merge outstanding PRs
- Release / communicate how to use LaunchDarkly for overrides
- Handle creation of actor definition versions for custom/ lowcode builder connectors
- Begin clean up work to remove version-specific fields from standard definitions

**Comment by pedroslopez** [comment] 2023-06-09 14:17
## Project update 6/6

**✅ What's been accomplished:**

- Added remaining per-version fields to ActorDefinitionVersions POJO and database ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/6871)](https://github.com/airbytehq/airbyte-platform-internal/pull/6871))
- Ready to be merged (see “what got in the way”)
    - Data migration to populate default actor definition versions for existing definitions (addresses custom connectors and those that have been manually added to the db by oss users) ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/6875)](https://github.com/airbytehq/airbyte-platform-internal/pull/6875))
    - Write/set default actor definition versions when using the API to manage connector definitions (custom connectors, oss) ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/6846)](https://github.com/airbytehq/airbyte-platform-internal/pull/6846))
    - Handle default version tag updates for declarative builder connectors ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/6846)](https://github.com/airbytehq/airbyte-platform-internal/pull/6846))

**⚠ What got in the way:**

- On-call issues took up a lot of the time over the past week
- Ongoing P0 on the platform team
    - This project was heavily impacted by the database-related P0s going on.
    - Initially this was flagged because we’re making lots of queries to seed actor definition versions. This was expected, but we were still doing double the queries we had to.
        - We retroactively feature flagged this ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/6959)](https://github.com/airbytehq/airbyte-platform-internal/pull/6959), [[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/6963)](https://github.com/airbytehq/airbyte-platform-internal/pull/6963)) to be able to turn it off, and did so over the weekend. We turned this back on yesterday, but subsequently turned it back off since things still weren’t stable. It remains off at time of writing.
        - This [[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/6979)](https://github.com/airbytehq/airbyte-platform-internal/pull/6979) reduces the queries by half. There’s still some room for improvement to try get actor definition / actor definition version updates batched and doing existence checks in constant time, but will not prioritize for now since this is off and we’re still seeing issues, which points to this not being the cause of the instability.
    - Connector Version Overrides were also disabled for some time during this period. It seems there may have been an issue here with our version retrieval queries holding onto connections. [[PR here](https://github.com/airbytehq/airbyte-platform-internal/pull/7041)](https://github.com/airbytehq/airbyte-platform-internal/pull/7041) with a fix. It’s currently being evaluated if this was the root cause, but seems likely.
    - Due to our database connections being unstable, I held off on merging the ready-to-go PRs since they would involve putting a bit more load on the DB. I don’t think they will be an issue, but since investigations are still going on for the p0 I want to wait until things are stable to avoid introducing new variables.

**⛔ Blockers:**

- Awaiting regained stability from platform/db

**🌱 What's next:**

- Merge open PRs
- Before the slowdowns, got a lot of progress in for moving usages of version-specific fields to use ADVs. However, there are failing acceptance tests to work through for the first [[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/6912)](https://github.com/airbytehq/airbyte-platform-internal/pull/6912).
- I decided to split out the above PR, which contains pretty straightforward changes, from a second upcoming PR that addresses usages that are less straightforward. This is coming up next.
- Remove version-specific fields from standard definitions

**Comment by pedroslopez** [comment] 2023-06-14 00:39
### Project Update 6/13

**✅ What's been accomplished:**

- Data migration to populate default actor definition versions for existing definitions (addresses custom connectors and those that have been manually added to the db by oss users) ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/6875)](https://github.com/airbytehq/airbyte-platform-internal/pull/6875))
- Handle default version tag updates for declarative builder connectors ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/6846)](https://github.com/airbytehq/airbyte-platform-internal/pull/6846))
- Write/set default actor definition versions when using the API to manage connector definitions (custom connectors, oss) ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/6846)](https://github.com/airbytehq/airbyte-platform-internal/pull/6846))
- All feature flags have been rolled out! The previously disabled flags from the incidents are back, and we successfully gradually rolled out using the actor_definition_version table to get default ADVs.
- PRs ready to go and in review:
    - Move version-specific field usages from standard defs to ADVHelper ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/6912/)](https://github.com/airbytehq/airbyte-platform-internal/pull/6912/))
    - SourceDefinitionHandler / DestinationDefinitionHandler use deafult ADVs to get version-specific fields ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7167)](https://github.com/airbytehq/airbyte-platform-internal/pull/7167))
    - WebBackendCheckUpdatesHandler moves to using apis (removing version-specific field usage from ADs) ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7206)](https://github.com/airbytehq/airbyte-platform-internal/pull/7206))
    - ProtocolVersionChecker uses ADVs for version-specific fields + Handle Protocol Versioning checks when processing connector version overrides ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7248)](https://github.com/airbytehq/airbyte-platform-internal/pull/7248))
    - Add version info to the UI ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7101)](https://github.com/airbytehq/airbyte-platform-internal/pull/7101))
    - Don’t upsert ADVs and treat versions as immutable ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7093)](https://github.com/airbytehq/airbyte-platform-internal/pull/7093))
    

**⚠ What got in the way:**

- Lingering slowdowns over the last week from OC - this issue has now been resolved though.

**⛔ Blockers:**

- none at the moment

**🌱 What's next:**

- Merge open PRs
- Remove version-specific field usage from JobErrorReporter
- Remove SecretsMigrator - it was using version-specific fields but is not needed anymore (see [[thread](https://airbytehq-team.slack.com/archives/C02TXQ020QM/p1686667684603789)](https://airbytehq-team.slack.com/archives/C02TXQ020QM/p1686667684603789))
- Actually remove the fields from the DB

**Comment by pedroslopez** [comment] 2023-07-05 14:40
## Project Update 6/20

**✅ What's been accomplished:**

- Move version-specific field usages from standard defs to ADVHelper ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/6912/)](https://github.com/airbytehq/airbyte-platform-internal/pull/6912/))
- SourceDefinitionHandler / DestinationDefinitionHandler use deafult ADVs to get version-specific fields ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7167)](https://github.com/airbytehq/airbyte-platform-internal/pull/7167))
- WebBackendCheckUpdatesHandler moves to using apis (removing version-specific field usage from ADs) ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7206)](https://github.com/airbytehq/airbyte-platform-internal/pull/7206))
- ProtocolVersionChecker uses ADVs for version-specific fields + Handle Protocol Versioning checks when processing connector version overrides ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7248)](https://github.com/airbytehq/airbyte-platform-internal/pull/7248))
- Remove SecretMigrator ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7255)](https://github.com/airbytehq/airbyte-platform-internal/pull/7255))
- Don’t upsert ADVs and treat versions as immutable ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7093)](https://github.com/airbytehq/airbyte-platform-internal/pull/7093))
- PRs ready to merge or in review:
    - Add version info to the UI ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7101)](https://github.com/airbytehq/airbyte-platform-internal/pull/7101))
    - JobErrorReporter gets version-specific fields from ADVs ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7268)](https://github.com/airbytehq/airbyte-platform-internal/pull/7268))

**⚠ What got in the way:**

- Slowdowns in PR review + micronaut bean replacement struggles when working on adding ADVHelper usage to cloud-server
- More direct usage of version-specific fields in DB queries. A miss here was to look at usages of the fields in the POJOs, but we were referencing the cols directly elsewhere.
- Getting the right version used for the job when reporting errors in JobErrorReporter required some refactoring in how we were creating jobs in order to be able to reference the version.

**⛔ Blockers:**

- none at the moment

**🌱 What's next:**

- (in progress) remove the fields from the DB
- remove YAML overrides
- remove feature flags that have been rolled out from the code

**Comment by pedroslopez** [comment] 2023-07-05 14:41
## Project Update 6/27

**✅ What's been accomplished:**

- Add version info to the UI ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7101)](https://github.com/airbytehq/airbyte-platform-internal/pull/7101))
- JobErrorReporter gets version-specific fields from ADVs ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7268)](https://github.com/airbytehq/airbyte-platform-internal/pull/7268))
- Fix builder connectors: write new spec to ADV when switching active manifest version ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7404)](https://github.com/airbytehq/airbyte-platform-internal/pull/7404))
- Remove static YAML overrides ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7377)](https://github.com/airbytehq/airbyte-platform-internal/pull/7377))
- refactor release stage metrics to use job ActorDefinitionVersions ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7473)](https://github.com/airbytehq/airbyte-platform-internal/pull/7473))
- Remove rolled out feature flags:
    - useActorDefinitionVersionTableDefaults feature flag ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7493)](https://github.com/airbytehq/airbyte-platform-internal/pull/7493))
    - ADV seeding feature flag ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7361)](https://github.com/airbytehq/airbyte-platform-internal/pull/7361))
- PRs ready to merge:
    - use ActorDefinitionVersionHelper in DelinquentWorkspaceCronJob ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7499)](https://github.com/airbytehq/airbyte-platform-internal/pull/7499))
    - remove version-specific columns from actor definitions ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7358)](https://github.com/airbytehq/airbyte-platform-internal/pull/7358))

**⚠ What got in the way:**

- When sorting through the one-off queries, it was found that there was a bug when switching the active declarative connector manifest version in the connector builder, preventing changes in specs from being shown in cloud. Fixed [[here](https://github.com/airbytehq/airbyte-platform-internal/pull/7404)](https://github.com/airbytehq/airbyte-platform-internal/pull/7404).
- Release stage metrics + DelinquentWorkspaceCronJob required spinning out separate PRs to address

**🌱 What's next:**

- Click the merge button on the remaining 2 PRs!

**Comment by pedroslopez** [comment] 2023-07-05 14:42
## Project Update 6/4

✅ What's been accomplished:

- use ActorDefinitionVersionHelper in DelinquentWorkspaceCronJob ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7499)](https://github.com/airbytehq/airbyte-platform-internal/pull/7499))
- remove version-specific columns from actor definitions ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7358)](https://github.com/airbytehq/airbyte-platform-internal/pull/7358))
- docs for how to set up overrides are now in internal-docs ([[PR](https://github.com/airbytehq/airbyte-platform-internal/pull/7599)](https://github.com/airbytehq/airbyte-platform-internal/pull/7599))

This project is now concluded! The database and codebase are now sane in terms of always using actor definition versions to get version-related information, and we've been using connector overrides for a while now.

**Comment by evantahler** [comment] 2023-07-13 22:53
@pedroslopez I think you can close this epic!

**Closed** 2023-07-18 16:18 UTC
Labels: Epic, team/connector-ops
