### ISSUE TITLE
Sync pods can only setup main container cpu en memory requests and limits?

### ISSUE THREAD

**Issue by ro8inmorgan** [airbytehq/airbyte#31335] opened 2023-10-12 10:03 UTC
### What method are you using to run Airbyte?

Kubernetes

### Platform Version or Helm Chart Version

helm chart: 0.49.4 app version: 0.50.30

### What step the error happened?

None

### Revelant information

The latest versions of airbyte don't honor the cpu en mem requests and limits set in the config, but they do honor them from the database at connection level. But this only apply's to the main container of the sync pods. The other containers have their own requests and limits which IMO seem to be quite high, is there no way to set these requests and limits as well?

**Comment by davinchia** [comment] 2023-10-18 14:54
duplicate of #17714

**Closed by davinchia** 2023-10-18 14:54 UTC
Labels: type/bug, area/platform, community, needs-triage, team/platform-compose, team/platform-move, autoteam
