### ISSUE TITLE
Source Intercom: Missing data in the destination after switching to declarative source (0.2.0)

### ISSUE THREAD

**Issue by killthekitten** [airbytehq/airbyte#26301] opened 2023-05-19 14:22 UTC
### Connector Name

source-intercom

### Connector Version

0.2.0

### What step the error happened?

During the sync

### Revelant information

We are running on the [new declarative intercom connector](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-intercom/source_intercom/manifest.yaml) (0.2.0) and with every sync some of the records would not appear in the destination (could be anywhere from 0.01% to 95%). The total contact count in the sync logs is almost always lower than the total number of contacts on Intercom, but sometimes it adds up. 

All of our streams are configured for full refresh, and the destination is BigQuery (via GCS staging). Our API key is pointed at v2.5 of the intercom API. Airbyte version is OSS v0.44.0. 

The records that are missing usually re-appear in one of the following syncs. My current theory is that it is somehow linked to the pagination implementation and/or the API endpoint that the source uses.

Here are my findings so far:

- The `contacts` stream uses `stream_incremental_search` instead of `stream_full_refresh`.
- Incremental search request is a POST to `/contacts/search` and not a GET `https://api.intercom.io/contacts`. 
- The stream is sorted by `updated_at`.
- The stream is using [Stream Slices](https://docs.airbyte.com/connector-development/cdk-python/stream-slices/) feature of the Airbyte CDK.
- The source is using API v2.5, while the latest is v2.9.

### Open questions

- Given that the results are sorted using the `updated_at` field, could it be that the pagination breaks when the upstream records are updated while fetching the records?

Here's some relevant info from the [Pagination & Sorting (Search)](https://developers.intercom.com/building-apps/docs/pagination-sorting-search) docs:
>The starting_after context is stateless. Consequently, if items are updated between 2 paginated queries, this can lead to duplicate or missed records.
> For example, if a query is sorting results by number of sessions and an item is updated from 1 session to 2 sessions during the pagination, they may be listed on page 1 of the results, but also on page 2.

- What is the purpose of the [record filter condition](https://github.com/airbytehq/airbyte/blob/master/airbyte-integrations/connectors/source-intercom/source_intercom/manifest.yaml#L265-L269) in manifest.yaml?

- ~~I set up a test replication with only the contacts stream, and it fetches all the records correctly each time, although could be that there were no changes upstream within that timeframe. It also runs much faster (25 minutes vs 10 hours). What might this imply?~~ This setup failed as well, most of the records disappeared.

Happy to work on a fix if someone could point me in the right direction! CC @bazarnov 

### Relevant log output

In this case most of the records were dropped, only 6050 appeared in the destination.

```
2023-05-19 18:44:04 [43mdestination[0m > INFO i.a.i.d.b.BigQueryGcsOperations(createSchemaIfNotExists):86 Creating dataset airbyte_test_intercom_connector
2023-05-19 18:44:05 [43mdestination[0m > INFO i.a.i.d.b.BigQueryGcsOperations(createTableIfNotExists):102 Creating target table GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=airbyte_test_intercom_connector, tableId=_airbyte_raw_contacts}}
2023-05-19 18:44:05 [43mdestination[0m > INFO i.a.i.d.b.BigQueryUtils(createPartitionedTableIfNotExists):224 Partitioned table ALREADY EXISTS: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=airbyte_test_intercom_connector, tableId=_airbyte_raw_contacts}}
2023-05-19 18:44:05 [43mdestination[0m > INFO i.a.i.d.b.BigQueryGcsOperations(createStageIfNotExists):109 Creating staging path for stream contacts (dataset airbyte_test_intercom_connector): airbyte_test_intercom_connector/airbyte_test_intercom_connector_contacts/2023/05/19/18/92afe7ea-324b-4807-b661-e2874c37646e/
2023-05-19 18:44:05 [43mdestination[0m > INFO i.a.i.d.b.BigQueryGcsOperations(truncateTableIfExists):207 Truncating target table GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=airbyte_test_intercom_connector, tableId=_airbyte_raw_contacts}} (dataset airbyte_test_intercom_connector)
2023-05-19 18:44:05 [43mdestination[0m > INFO i.a.i.d.b.BigQueryGcsOperations(dropTableIfExists):175 Deleting target table GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=airbyte_test_intercom_connector, tableId=_airbyte_raw_contacts}} (dataset airbyte_test_intercom_connector)
2023-05-19 18:44:06 [43mdestination[0m > INFO i.a.i.d.b.BigQueryGcsOperations(createTableIfNotExists):102 Creating target table GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=airbyte_test_intercom_connector, tableId=_airbyte_raw_contacts}}
2023-05-19 18:44:06 [43mdestination[0m > INFO i.a.i.d.b.BigQueryUtils(createPartitionedTableIfNotExists):227 Partitioned table created successfully: GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=airbyte_test_intercom_connector, tableId=_airbyte_raw_contacts}}
2023-05-19 18:44:06 [43mdestination[0m > INFO i.a.i.d.b.BigQueryStagingConsumerFactory(lambda$onStartFunction$3):131 Preparing airbyte_raw tables in destination completed.
2023-05-19 18:44:06 [43mdestination[0m > INFO i.a.i.d.r.SerializedBufferingStrategy(lambda$addRecord$0):76 Starting a new buffer for stream contacts (current state: 0 bytes in 0 buffers)
2023-05-19 18:44:06 [43mdestination[0m > INFO i.a.i.d.g.u.GcsUtils(getDefaultAvroSchema):25 Default schema.
2023-05-19 18:45:51 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$8):434 - Records read: 5000 (11 MB)
2023-05-19 18:46:13 [44msource[0m > Read 6050 records from contacts stream
2023-05-19 18:46:13 [44msource[0m > Finished syncing contacts
2023-05-19 18:46:13 [44msource[0m > SourceIntercom runtimes:
Syncing stream contacts 0:02:09.230458
2023-05-19 18:46:13 [44msource[0m > Finished syncing SourceIntercom
2023-05-19 18:46:13 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$8):447 - Total records read: 6050 (14 MB)
2023-05-19 18:46:13 [32mINFO[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$8):456 - Schema validation was performed to a max of 10 records with errors per stream.
2023-05-19 18:46:13 [33mWARN[m i.a.w.g.DefaultReplicationWorker(lambda$readFromSrcAndWriteToDstRunnable$7):464 - Source 5b557886-d09d-4239-a7aa-56e99ec91f22 has unexpected fields [utm_term, referrer, utm_campaign, utm_medium, utm_content, utm_source] in stream _contacts
2023-05-19 18:46:13 [32mINFO[m i.a.w.i.HeartbeatTimeoutChaperone(runWithHeartbeatThread):111 - thread status... heartbeat thread: false , replication thread: true
2023-05-19 18:46:13 [32mINFO[m i.a.w.g.DefaultReplicationWorker(replicate):266 - Waiting for source and destination threads to complete.
2023-05-19 18:46:13 [32mINFO[m i.a.w.g.DefaultReplicationWorker(replicate):271 - One of source or destination thread complete. Waiting on the other.
2023-05-19 18:46:13 [43mdestination[0m > INFO i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):80 Airbyte message consumer: succeeded.
2023-05-19 18:46:13 [43mdestination[0m > INFO i.a.i.d.b.BufferedStreamConsumer(close):257 executing on success close procedure.
2023-05-19 18:46:13 [43mdestination[0m > INFO i.a.i.d.r.SerializedBufferingStrategy(flushAll):130 Flushing all 1 current buffers (14 MB in total)
2023-05-19 18:46:13 [43mdestination[0m > INFO i.a.i.d.r.SerializedBufferingStrategy(flushAll):132 Flushing buffer of stream contacts (14 MB)
2023-05-19 18:46:13 [43mdestination[0m > INFO i.a.i.d.b.BigQueryStagingConsumerFactory(lambda$flushBufferFunction$4):147 Flushing buffer for stream contacts (14 MB) to staging
2023-05-19 18:46:13 [43mdestination[0m > INFO i.a.i.d.r.BaseSerializedBuffer(flush):138 Finished writing data to 88f6ea84-92df-4497-ae82-badbd284702e9233920641501566045.avro (14 MB)
2023-05-19 18:46:13 [43mdestination[0m > INFO i.a.i.d.b.BigQueryGcsOperations(uploadRecordsToStage):116 Uploading records to staging for stream contacts (dataset airbyte_test_intercom_connector): airbyte_test_intercom_connector/airbyte_test_intercom_connector_contacts/2023/05/19/18/92afe7ea-324b-4807-b661-e2874c37646e/
2023-05-19 18:46:14 [43mdestination[0m > INFO a.m.s.StreamTransferManager(getMultiPartOutputStreams):329 Initiated multipart upload to airbyte-staging-area/airbyte_test_intercom_connector/airbyte_test_intercom_connector_contacts/2023/05/19/18/92afe7ea-324b-4807-b661-e2874c37646e/0.avro with full ID ABPnzm409SXEq_eflx4kFhIXj8zjn_F2IVTihW__SBKRoQEbHoB0d-iBACIOgno0U_Xcoco
2023-05-19 18:46:14 [43mdestination[0m > INFO a.m.s.MultiPartOutputStream(close):158 Called close() on [MultipartOutputStream for parts 1 - 10000]
2023-05-19 18:46:14 [43mdestination[0m > INFO a.m.s.StreamTransferManager(uploadStreamPart):558 [Manager uploading to airbyte-staging-area/airbyte_test_intercom_connector/airbyte_test_intercom_connector_contacts/2023/05/19/18/92afe7ea-324b-4807-b661-e2874c37646e/0.avro with id ABPnzm409...o0U_Xcoco]: Finished uploading [Part number 1 containing 14.49 MB]
2023-05-19 18:46:15 [43mdestination[0m > INFO a.m.s.StreamTransferManager(complete):395 [Manager uploading to airbyte-staging-area/airbyte_test_intercom_connector/airbyte_test_intercom_connector_contacts/2023/05/19/18/92afe7ea-324b-4807-b661-e2874c37646e/0.avro with id ABPnzm409...o0U_Xcoco]: Completed
2023-05-19 18:46:15 [43mdestination[0m > INFO i.a.i.d.s.S3StorageOperations(loadDataIntoBucket):214 Uploaded buffer file to storage: 88f6ea84-92df-4497-ae82-badbd284702e9233920641501566045.avro -> airbyte_test_intercom_connector/airbyte_test_intercom_connector_contacts/2023/05/19/18/92afe7ea-324b-4807-b661-e2874c37646e/0.avro (filename: 0.avro)
2023-05-19 18:46:15 [43mdestination[0m > INFO i.a.i.d.s.S3StorageOperations(uploadRecordsToBucket):131 Successfully loaded records to stage airbyte_test_intercom_connector/airbyte_test_intercom_connector_contacts/2023/05/19/18/92afe7ea-324b-4807-b661-e2874c37646e/ with 0 re-attempt(s)
2023-05-19 18:46:15 [43mdestination[0m > INFO i.a.i.d.b.BigQueryWriteConfig(addStagedFile):61 Added staged file: 0.avro
2023-05-19 18:46:15 [43mdestination[0m > INFO i.a.i.d.b.BigQueryGcsOperations(copyIntoTableFromStage):133 Uploading records from staging files to target table GenericData{classInfo=[datasetId, projectId, tableId], {datasetId=airbyte_test_intercom_connector, tableId=_airbyte_raw_contacts}} (dataset airbyte_test_intercom_connector): [0.avro]
2023-05-19 18:46:15 [43mdestination[0m > INFO i.a.i.d.b.BigQueryGcsOperations(lambda$copyIntoTableFromStage$0):138 Uploading staged file: gs://airbyte-staging-area/airbyte_test_intercom_connector/airbyte_test_intercom_connector_contacts/2023/05/19/18/92afe7ea-324b-4807-b661-e2874c37646e/0.avro
2023-05-19 18:46:15 [43mdestination[0m > INFO i.a.i.d.b.BigQueryGcsOperations(lambda$copyIntoTableFromStage$0):147 [**STRIPPED**]
2023-05-19 18:46:18 [43mdestination[0m > INFO i.a.i.d.r.FileBuffer(deleteFile):109 Deleting tempFile data 88f6ea84-92df-4497-ae82-badbd284702e9233920641501566045.avro
2023-05-19 18:46:18 [43mdestination[0m > INFO i.a.i.d.r.SerializedBufferingStrategy(flushAll):134 Flushing completed for contacts
2023-05-19 18:46:18 [43mdestination[0m > INFO i.a.i.d.r.SerializedBufferingStrategy(close):152 Closing buffer for stream contacts
2023-05-19 18:46:18 [43mdestination[0m > INFO i.a.i.d.b.BigQueryStagingConsumerFactory(lambda$onCloseFunction$5):190 Cleaning up destination started for 1 streams
2023-05-19 18:46:18 [43mdestination[0m > INFO i.a.i.d.b.BigQueryGcsOperations(dropStageIfExists):186 Cleaning up staging path for stream contacts (dataset airbyte_test_intercom_connector): airbyte_test_intercom_connector/airbyte_test_intercom_connector_contacts
2023-05-19 18:46:18 [43mdestination[0m > INFO i.a.i.d.g.GcsStorageOperations(cleanUpObjects):43 Deleting object airbyte_test_intercom_connector/airbyte_test_intercom_connector_contacts/2023/05/19/18/92afe7ea-324b-4807-b661-e2874c37646e/0.avro
2023-05-19 18:46:18 [43mdestination[0m > INFO i.a.i.d.s.S3StorageOperations(cleanUpBucketObject):306 Storage bucket airbyte_test_intercom_connector/airbyte_test_intercom_connector_contacts has been cleaned-up (1 objects were deleted)...
2023-05-19 18:46:18 [43mdestination[0m > INFO i.a.i.d.b.BigQueryStagingConsumerFactory(lambda$onCloseFunction$5):194 Cleaning up destination completed.
2023-05-19 18:46:18 [43mdestination[0m > INFO i.a.i.b.IntegrationRunner(runInternal):186 Completed integration: io.airbyte.integrations.destination.bigquery.BigQueryDestination
2023-05-19 18:46:18 [32mINFO[m i.a.w.g.DefaultReplicationWorker(replicate):273 - Source and destination threads complete.
2023-05-19 18:46:18 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):561 - sync summary: {
  "status" : "completed",
  "recordsSynced" : 6050,
  "bytesSynced" : 14911992,
  "startTime" : 1684521841646,
  "endTime" : 1684521978786,
  "totalStats" : {
    "bytesCommitted" : 14911992,
    "bytesEmitted" : 14911992,
    "destinationStateMessagesEmitted" : 0,
    "destinationWriteEndTime" : 1684521978785,
    "destinationWriteStartTime" : 1684521841729,
    "meanSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBeforeSourceStateMessageEmitted" : 0,
    "maxSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "meanSecondsBetweenStateMessageEmittedandCommitted" : 0,
    "recordsEmitted" : 6050,
    "recordsCommitted" : 6050,
    "replicationEndTime" : 1684521978786,
    "replicationStartTime" : 1684521841646,
    "sourceReadEndTime" : 1684521973809,
    "sourceReadStartTime" : 1684521841684,
    "sourceStateMessagesEmitted" : 0
  },
  "streamStats" : [ {
    "streamName" : "contacts",
    "stats" : {
      "bytesCommitted" : 14911992,
      "bytesEmitted" : 14911992,
      "recordsEmitted" : 6050,
      "recordsCommitted" : 6050
    }
  } ]
}
2023-05-19 18:46:18 [32mINFO[m i.a.w.g.DefaultReplicationWorker(getReplicationOutput):562 - failures: [ ]
2023-05-19 18:46:18 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):163 - Stopping cancellation check scheduling...
```

### Contribute

- [X] Yes, I want to contribute

**Comment by bazarnov** [comment] 2023-05-22 12:07
@lazebnyi Please prioritize this issue for investigation.

**Comment by girarda** [comment] 2023-06-13 22:35
Hi, thanks for flagging this @killthekitten!

I have a few questions to help us understand the root cause:
- Did you use the connector on a previous version and did you experience the same issue?

**Comment by killthekitten** [comment] 2023-06-13 22:47
@girarda happy to help!

- We didn't have this problem on the previous version of the connector.
- I considered this, but that would explain only some of the missing records.

I think we fixed this by switching to incremental sync where the stream allows. IIRC when I reported the issue, we were running full syncs for every stream.

**Comment by darynaishchenko** [comment] 2023-07-04 11:51
@killthekitten Hi, I'm currently working on it. I have couple questions that help me better understand your cause.

1. Is it possible for you to share your creds with me? With our test creds connector doesn't produce missing data. And before switching to low-code we have tested connector working with other accounts and didn't face this issue. So it can be much easier to find the problem with your creds.

2. Could you please send screenshots of Intercom UI, where you see that's contacts total amount is bigger then in connectors logs. I'm trying to understand your way to detect missing data, maybe you use filters in your intercom reports that don't match with our. Also here is a [link](https://www.intercom.com/help/en/articles/5053685-why-do-i-have-duplicate-users) to intercom help center about duplicates in users. 

Thanks in advance.

Answering your questions:
1. Contacts stream uses POST contacts/search to allow us using querying by updated_at field to get new updated contacts.
2. /contacts endpoint doesn’t allow filtering, so can be used only for full_refresh syncs, but for low-code connector it’s hard to switch endpoint according to sync mode.
3. I don’t see any difference between v2.5 and v2.9 in API docs, that can effect connector working.

**Comment by killthekitten** [comment] 2023-07-06 00:41
Hey @darynaishchenko, thanks for the insightful answers! 

1. Unfortunately, I won't be able to share the creds. That said, I'm open to help you some other way, let me know if you have other ideas.
2. Here's where I check the numbers (these are fake):

![image](https://github.com/airbytehq/airbyte/assets/1201569/b543692f-3364-40e2-82e1-c18514c7571f)

I will try to see if this can be reproduced in a different workspace, but can't promise it will happen soon.

**Comment by darynaishchenko** [comment] 2023-07-06 09:36
@killthekitten Thanks for answering! 
Unfortunately I'm blind without your creds, so your proposal about reproducing in a different  workspace will help us. 
So I'll wait for your updates about it. 
But if nothing found, can you test my future PR on your data and tell me what works correctly and what doesn't? I can't promise that the first time my changes will fix this problem, but we will able to test on your data.

**Comment by killthekitten** [comment] 2023-07-06 18:34
@darynaishchenko great idea, I have a local setup just for that purpose!

**Comment by darynaishchenko** [comment] 2023-07-07 13:27
Airbyte guarantees the correctness of the data at the beginning of the sync. If the data changes during the sync, it will be synchronized the next time. So if your data has changes during the sync process, but it is pulled in the next sync, this is normal and expected working of connector. Therefore, this issue doesn't require changes in connectors code.

**Comment by killthekitten** [comment] 2023-07-07 18:33
@darynaishchenko with all due respect, I don't feel this is an honest statement. Given that the connector syncs for at least a few hours, some data drift is normal, but it wouldn't explain dropping 95% of data. 

In any case, thanks for the help! A note for anyone who might encounter the same issue: we moved on from full sync already and it does the trick.

**Comment by girarda** [comment] 2023-07-07 18:50
@darynaishchenko this behavior wasn't present in the Python implementation of the connector so I don't think it's a problem with API itself. Given that there is no missing data when running full refresh syncs, the custom state management and record filtering look like good places to start the investigation

**Comment by darynaishchenko** [comment] 2023-07-10 08:00
@killthekitten sorry for misunderstanding, so lets stay on [this step](https://github.com/airbytehq/airbyte/issues/26301#issuecomment-1623346299). 
@girarda  I've tested  the custom state management and record filtering with our data. All works good. So we need some other workspaces to catch a bug or add switching to other endpoint for contacts for full_refresh sync mode. But the second one isn't pretty solution in my opinion.

**Comment by killthekitten** [comment] 2023-07-10 11:37
@darynaishchenko I could collect some more debug information from the failing sync and anonymise it on my end. What kind of data could be helpful for your investigation?

**Comment by darynaishchenko** [comment] 2023-07-10 13:45
@killthekitten could it be raw records from connectors logs? I'm interested in `id`, `created_at` and `updated at` fields. You can delete the others.

**Comment by killthekitten** [comment] 2023-07-10 14:08
@darynaishchenko that's doable! Would the contents of _raw tables work, or did you mean something else as logs?

**Comment by darynaishchenko** [comment] 2023-07-11 08:36
@killthekitten I guess  the contents of _raw tables is suitable. Let's start with it.

**Comment by darynaishchenko** [comment] 2023-07-11 13:22
Here is my investigation status. @killthekitten 
    • archive/unarchive users (contacts search doesn’t return them or return from time to time, list contacts returns all contacts). Is it relevant for you? Can users be  archived/unarchived in your account? 
         ◦ we can’t add searching by  archived==true/false, because this field is not in a list of contact fields.
    • v0.1.21 changed the endpoint from `contacts`  to `contacts/search`, so all lower versions use `contacts` and higher versions use ‘contacts/search’. Which version did you use before switching to 0.2.0?
        ◦ Why we switched to search endpoint: https://github.com/airbytehq/airbyte/pull/14403– it provides incremental functionality and decrease time of connectors work.
    • Also search endpoint has a [delay](https://developers.intercom.com/intercom-api-reference/reference/searchcontacts). This may explain partial absence of data in the full refresh mode.  
    
 I will prepare a PR with changes for your local testing with your data. It will use `contacts` endpoint on full refresh. So I will wait for your test result with your creds on contacts stream in full refresh mode.

**Comment by roman-yermilov-gl** [comment] 2023-08-26 14:33
Was not able to reproduce this issue on our test data set. As I also see there is no any answer to @darynaishchenko comment for long time, so closing this issue

**Closed by roman-yermilov-gl** 2023-08-26 14:33 UTC
Labels: type/bug, help-welcome, area/connectors, community, connectors/sources-api, connectors/source/intercom, releaseStage/ga, team/connectors-python

**Comment by killthekitten** [comment] 2023-08-26 15:44
@roman-yermilov-gl thanks for taking care of this, I didn't have a chance to look into it once more.

If I get to it again, I'll report back here.
