### ISSUE TITLE
Failed to finalize copy to temp table due to: java.lang.IndexOutOfBoundsException: This stream was allocated the part numbers from 1 (inclusive) to 10001 (exclusive)and it has gone beyond the end

### ISSUE THREAD

**Issue by joshuataylor** [airbytehq/airbyte#8129] opened 2021-11-19 04:43 UTC
## Environment
- **Airbyte version**:  v0.32.3-alpha
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: docker
- **Source Connector and version**: Postgres
- **Destination Connector and version**: Snowflake with S3 Stage
- **Severity**: High
- **Step where error happened**: Syncing

## Current Behavior
It seems that when the part number reaches 10,000, it fails?

## Expected Behavior
It does not fail.

## Logs
```
2021-11-19 04:34:50 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):203 - Records read: 85481000
2021-11-19 04:34:50 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):203 - Records read: 85482000
2021-11-19 04:34:50 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):203 - Records read: 85483000
2021-11-19 04:34:51 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):203 - Records read: 85484000
2021-11-19 04:34:51 INFO () DefaultReplicationWorker(lambda$getReplicationRunnable$2):203 - Records read: 85485000
destination - 2021-11-19 04:34:52 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:52 INFO a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to mys3bucket/76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/mytablename_00000 with id 4GZ6vLD_0...Z1iTIxIZB]: Finished uploading [Part number 9992 containing 10.01 MB]
destination - 2021-11-19 04:34:52 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:52 INFO a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to mys3bucket/76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/mytablename_00000 with id 4GZ6vLD_0...Z1iTIxIZB]: Finished uploading [Part number 9993 containing 10.01 MB]
destination - 2021-11-19 04:34:52 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:52 INFO a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to mys3bucket/76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/mytablename_00000 with id 4GZ6vLD_0...Z1iTIxIZB]: Finished uploading [Part number 9994 containing 10.01 MB]
destination - 2021-11-19 04:34:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:53 INFO a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to mys3bucket/76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/mytablename_00000 with id 4GZ6vLD_0...Z1iTIxIZB]: Finished uploading [Part number 9995 containing 10.01 MB]
destination - 2021-11-19 04:34:53 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:53 INFO a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to mys3bucket/76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/mytablename_00000 with id 4GZ6vLD_0...Z1iTIxIZB]: Finished uploading [Part number 9996 containing 10.01 MB]
destination - 2021-11-19 04:34:54 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:54 INFO a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to mys3bucket/76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/mytablename_00000 with id 4GZ6vLD_0...Z1iTIxIZB]: Finished uploading [Part number 9997 containing 10.01 MB]
destination - 2021-11-19 04:34:54 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:54 INFO a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to mys3bucket/76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/mytablename_00000 with id 4GZ6vLD_0...Z1iTIxIZB]: Finished uploading [Part number 9998 containing 10.01 MB]
destination - 2021-11-19 04:34:55 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:55 INFO a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to mys3bucket/76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/mytablename_00000 with id 4GZ6vLD_0...Z1iTIxIZB]: Finished uploading [Part number 9999 containing 10.01 MB]
destination - 2021-11-19 04:34:55 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:55 INFO a.m.s.StreamTransferManager(uploadStreamPart):558 - {} - [Manager uploading to mys3bucket/76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/mytablename_00000 with id 4GZ6vLD_0...Z1iTIxIZB]: Finished uploading [Part number 10000 containing 10.01 MB]
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 WARN i.a.i.b.FailureTrackingAirbyteMessageConsumer(close):58 - {} - Airbyte message consumer: failed.
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 ERROR i.a.i.d.b.BufferedStreamConsumer(close):197 - {} - executing on failed close procedure.
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 INFO i.a.i.d.j.c.s.S3StreamCopier(closeAndWaitForUpload):221 - {} - Uploading remaining data for mytablename stream.
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 INFO a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 ERROR i.a.i.d.j.c.CopyConsumerFactory(closeAsOneTransaction):137 - {} - Failed to finalize copy to temp table due to: java.lang.IndexOutOfBoundsException: This stream was allocated the part numbers from 1 (inclusive) to 10001 (exclusive)and it has gone beyond the end.
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 INFO a.m.s.StreamTransferManager(abort):470 - {} - [Manager uploading to mys3bucket/76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/othertable_00000 with id TqooeWi9k...BjZMCAtTm]: Aborted
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 INFO i.a.i.d.j.c.s.S3StreamCopier(closeAndWaitForUpload):221 - {} - Uploading remaining data for othertable stream.
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 INFO a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 INFO a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 WARN a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 ERROR i.a.i.d.j.c.CopyConsumerFactory(closeAsOneTransaction):137 - {} - Failed to finalize copy to temp table due to: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.InterruptedException
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 INFO a.m.s.StreamTransferManager(abort):470 - {} - [Manager uploading to mys3bucket/76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/othertable_00000 with id 79v5a24IG...i.uQsch0k]: Aborted
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 INFO i.a.i.d.j.c.s.S3StreamCopier(closeAndWaitForUpload):221 - {} - Uploading remaining data for othertable stream.
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 INFO a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 INFO a.m.s.MultiPartOutputStream(close):158 - {} - Called close() on [MultipartOutputStream for parts 1 - 10000]
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 WARN a.m.s.MultiPartOutputStream(close):160 - {} - [MultipartOutputStream for parts 1 - 10000] is already closed
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 ERROR i.a.i.d.j.c.CopyConsumerFactory(closeAsOneTransaction):137 - {} - Failed to finalize copy to temp table due to: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.InterruptedException
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 INFO i.a.i.d.j.c.s.S3StreamCopier(lambda$removeFileAndDropTmpTable$2):201 - {} - Begin cleaning s3 staging file 76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/mytablename_00000.
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 INFO i.a.i.d.j.c.s.S3StreamCopier(lambda$removeFileAndDropTmpTable$2):205 - {} - S3 staging file 76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/mytablename_00000 cleaned.
destination - 2021-11-19 04:34:56 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:34:56 INFO i.a.i.d.j.c.s.S3StreamCopier(removeFileAndDropTmpTable):208 - {} - Begin cleaning _airbyte_tmp_idu_mytablename tmp table in destination.
destination - 2021-11-19 04:35:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:35:00 INFO i.a.i.d.j.c.s.S3StreamCopier(removeFileAndDropTmpTable):210 - {} - _airbyte_tmp_idu_mytablename tmp table in destination cleaned.
destination - 2021-11-19 04:35:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:35:00 INFO i.a.i.d.j.c.s.S3StreamCopier(lambda$removeFileAndDropTmpTable$2):201 - {} - Begin cleaning s3 staging file 76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/othertable_00000.
destination - 2021-11-19 04:35:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:35:00 INFO i.a.i.d.j.c.s.S3StreamCopier(lambda$removeFileAndDropTmpTable$2):205 - {} - S3 staging file 76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/othertable_00000 cleaned.
destination - 2021-11-19 04:35:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:35:00 INFO i.a.i.d.j.c.s.S3StreamCopier(removeFileAndDropTmpTable):208 - {} - Begin cleaning _airbyte_tmp_pzb_othertable tmp table in destination.
destination - 2021-11-19 04:35:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:35:00 INFO i.a.i.d.j.c.s.S3StreamCopier(removeFileAndDropTmpTable):210 - {} - _airbyte_tmp_pzb_othertable tmp table in destination cleaned.
destination - 2021-11-19 04:35:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:35:00 INFO i.a.i.d.j.c.s.S3StreamCopier(lambda$removeFileAndDropTmpTable$2):201 - {} - Begin cleaning s3 staging file 76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/othertable_00000.
destination - 2021-11-19 04:35:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:35:00 INFO i.a.i.d.j.c.s.S3StreamCopier(lambda$removeFileAndDropTmpTable$2):205 - {} - S3 staging file 76d937b9-dbb1-463f-9e77-bdbfcbca0d43/public/othertable_00000 cleaned.
destination - 2021-11-19 04:35:00 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:35:00 INFO i.a.i.d.j.c.s.S3StreamCopier(removeFileAndDropTmpTable):208 - {} - Begin cleaning _airbyte_tmp_neq_othertable tmp table in destination.
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:35:01 INFO i.a.i.d.j.c.s.S3StreamCopier(removeFileAndDropTmpTable):210 - {} - _airbyte_tmp_neq_othertable tmp table in destination cleaned.
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-11-19 04:35:01 ERROR i.a.i.d.b.BufferedStreamConsumer(close):219 - {} - Close failed.
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - java.lang.IndexOutOfBoundsException: This stream was allocated the part numbers from 1 (inclusive) to 10001 (exclusive)and it has gone beyond the end.
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at alex.mojaki.s3upload.MultiPartOutputStream.putCurrentStream(MultiPartOutputStream.java:121) ~[s3-stream-upload-2.2.2.jar:?]
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at alex.mojaki.s3upload.MultiPartOutputStream.close(MultiPartOutputStream.java:164) ~[s3-stream-upload-2.2.2.jar:?]
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:353) ~[?:?]
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:168) ~[?:?]
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at java.io.OutputStreamWriter.close(OutputStreamWriter.java:255) ~[?:?]
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at java.io.BufferedWriter.close(BufferedWriter.java:269) ~[?:?]
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at java.io.PrintWriter.close(PrintWriter.java:415) ~[?:?]
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at org.apache.commons.csv.CSVPrinter.close(CSVPrinter.java:87) ~[commons-csv-1.4.jar:1.4]
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.destination.jdbc.copy.s3.S3StreamCopier.closeAndWaitForUpload(S3StreamCopier.java:223) ~[io.airbyte.airbyte-integrations.connectors-destination-jdbc-0.30.34-alpha.jar:?]
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - Exception in thread "main" java.lang.IndexOutOfBoundsException: This stream was allocated the part numbers from 1 (inclusive) to 10001 (exclusive)and it has gone beyond the end.
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at alex.mojaki.s3upload.MultiPartOutputStream.putCurrentStream(MultiPartOutputStream.java:121)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at alex.mojaki.s3upload.MultiPartOutputStream.checkSize(MultiPartOutputStream.java:110)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at alex.mojaki.s3upload.MultiPartOutputStream.write(MultiPartOutputStream.java:143)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:312)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at java.base/sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:290)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at java.base/sun.nio.cs.StreamEncoder.write(StreamEncoder.java:131)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.io.OutputStreamWriter.write(OutputStreamWriter.java:208)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.io.BufferedWriter.flushBuffer(BufferedWriter.java:120)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.io.BufferedWriter.write(BufferedWriter.java:233)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.io.PrintWriter.write(PrintWriter.java:542)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.io.PrintWriter.write(PrintWriter.java:559)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.io.PrintWriter.append(PrintWriter.java:1088)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.io.PrintWriter.append(PrintWriter.java:1128)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at java.base/java.io.PrintWriter.append(PrintWriter.java:61)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at org.apache.commons.csv.CSVFormat.printAndQuote(CSVFormat.java:1023)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at org.apache.commons.csv.CSVFormat.print(CSVFormat.java:902)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at org.apache.commons.csv.CSVFormat.print(CSVFormat.java:890)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at org.apache.commons.csv.CSVFormat.printRecord(CSVFormat.java:1098)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at org.apache.commons.csv.CSVPrinter.printRecord(CSVPrinter.java:216)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.jdbc.copy.s3.S3StreamCopier.write(S3StreamCopier.java:139)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.jdbc.copy.CopyConsumerFactory.lambda$recordWriterFunction$0(CopyConsumerFactory.java:96)
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.destination.jdbc.copy.s3.S3StreamCopier.closeStagingUploader(S3StreamCopier.java:152) ~[io.airbyte.airbyte-integrations.connectors-destination-jdbc-0.30.34-alpha.jar:?]
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.flushQueueToDestination(BufferedStreamConsumer.java:173)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.acceptTracked(BufferedStreamConsumer.java:150)
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.destination.jdbc.copy.CopyConsumerFactory.closeAsOneTransaction(CopyConsumerFactory.java:125) ~[io.airbyte.airbyte-integrations.connectors-destination-jdbc-0.30.34-alpha.jar:?]
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.accept(FailureTrackingAirbyteMessageConsumer.java:46)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:147)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:128)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	at io.airbyte.integrations.destination.snowflake.SnowflakeDestination.main(SnowflakeDestination.java:62)
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.destination.jdbc.copy.CopyConsumerFactory.lambda$onCloseFunction$2(CopyConsumerFactory.java:111) ~[io.airbyte.airbyte-integrations.connectors-destination-jdbc-0.30.34-alpha.jar:?]
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.destination.buffered_stream_consumer.OnCloseFunction.accept(OnCloseFunction.java:9) ~[io.airbyte.airbyte-integrations.bases-base-java-0.30.34-alpha.jar:?]
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:210) [io.airbyte.airbyte-integrations.bases-base-java-0.30.34-alpha.jar:?]
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:62) [io.airbyte.airbyte-integrations.bases-base-java-0.30.34-alpha.jar:?]
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 	Suppressed: java.lang.IndexOutOfBoundsException: This stream was allocated the part numbers from 1 (inclusive) to 10001 (exclusive)and it has gone beyond the end.
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		at alex.mojaki.s3upload.MultiPartOutputStream.putCurrentStream(MultiPartOutputStream.java:121)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		at alex.mojaki.s3upload.MultiPartOutputStream.close(MultiPartOutputStream.java:164)
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:141) [io.airbyte.airbyte-integrations.bases-base-java-0.30.34-alpha.jar:?]
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		at java.base/sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:353)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		at java.base/sun.nio.cs.StreamEncoder.close(StreamEncoder.java:168)
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:128) [io.airbyte.airbyte-integrations.bases-base-java-0.30.34-alpha.jar:?]
destination - 2021-11-19 04:35:01 INFO () DefaultAirbyteStreamFactory(lambda$create$0):61 - 	at io.airbyte.integrations.destination.snowflake.SnowflakeDestination.main(SnowflakeDestination.java:62) [io.airbyte.airbyte-integrations.connectors-destination-snowflake-0.30.34-alpha.jar:?]
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		at java.base/java.io.OutputStreamWriter.close(OutputStreamWriter.java:255)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		at java.base/java.io.BufferedWriter.close(BufferedWriter.java:269)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		at java.base/java.io.PrintWriter.close(PrintWriter.java:415)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		at org.apache.commons.csv.CSVPrinter.close(CSVPrinter.java:87)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.integrations.destination.jdbc.copy.s3.S3StreamCopier.closeAndWaitForUpload(S3StreamCopier.java:223)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.integrations.destination.jdbc.copy.s3.S3StreamCopier.closeStagingUploader(S3StreamCopier.java:152)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.integrations.destination.jdbc.copy.CopyConsumerFactory.closeAsOneTransaction(CopyConsumerFactory.java:125)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.integrations.destination.jdbc.copy.CopyConsumerFactory.lambda$onCloseFunction$2(CopyConsumerFactory.java:111)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.integrations.destination.buffered_stream_consumer.OnCloseFunction.accept(OnCloseFunction.java:9)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.integrations.destination.buffered_stream_consumer.BufferedStreamConsumer.close(BufferedStreamConsumer.java:210)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.integrations.base.FailureTrackingAirbyteMessageConsumer.close(FailureTrackingAirbyteMessageConsumer.java:62)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		at io.airbyte.integrations.base.IntegrationRunner.consumeWriteStream(IntegrationRunner.java:141)
destination - 2021-11-19 04:35:01 ERROR () LineGobbler(voidCall):82 - 		... 2 more
```

**Comment by sherifnada** [comment] 2021-11-19 08:12
duplicate of https://github.com/airbytehq/airbyte/issues/6245 -- @joshuataylor we're going to be tackling this very soon! please follow that issue for updates

**Closed by sherifnada** 2021-11-19 08:12 UTC
Labels: type/bug, community
