### ISSUE TITLE
deploy airbyte is not working using helm

### ISSUE THREAD

**Issue by navi86** [airbytehq/airbyte#17384] opened 2022-09-29 12:18 UTC
## Environment
- **Airbyte version**:  0.40.10
- **OS Version / Instance**: k8s
- **Deployment**: helm install

## Current Behavior
helm install airbyte airbyte/aibyte --version(any deployable) failed due to
0.41.2 - is not deployable due to ingress error
0.41.1 - has error below
other version that are available has "airbyte-db" so there error is the same, because image the same. Do you test deploy of new releases ???
```
kubectl logs -n airbyte -f airbyte-db-5965d9c677-nwnb6 -c airbyte-db-container --previous

/usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/000_init.sql
ALTER SYSTEM
CREATE DATABASE
You are now connected to database "airbyte" as user "airbyte".
2022-09-21 07:58:11.385 UTC [52] ERROR:  role "docker" does not exist
2022-09-21 07:58:11.385 UTC [52] STATEMENT:  GRANT ALL ON
	DATABASE airbyte TO docker;
psql:/docker-entrypoint-initdb.d/000_init.sql:12: ERROR:  role "docker" does not exist
```

## Expected Behavior
everything is working

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by navi86** [comment] 2022-09-29 21:14
One more question, why from 0.40.4 is two postgresql instance are deployed ? what is the point to have two ?
first one is 
https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/templates/airbyte-db.yaml#L1
and secondly 
https://github.com/airbytehq/airbyte/blob/master/charts/airbyte/Chart.yaml#L32

**Comment by navi86** [comment] 2022-09-30 11:04
the same issue as here https://github.com/airbytehq/airbyte/issues/16587

**Comment by natalyjazzviolin** [comment] 2022-09-30 13:19
Closing because this is a duplicate of https://github.com/airbytehq/airbyte/issues/16587

**Closed by natalyjazzviolin** 2022-09-30 13:19 UTC
Labels: type/bug, area/platform, community, helm, team/prod-eng
