### ISSUE TITLE
Input fields turn red after a successful connection check

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#1583] opened 2021-01-08 00:52 UTC
## Description
After inputting configuration parameters for a new source or destination then clicking the create source button, the input fields all briefly turn red while the page is loading. This makes it look like the user input was incorrect. 

## Steps to Reproduce
1. Create a new source (e.g postgres)
1. input all fields correctly
1. Click the button to create the source

## Severity of the bug for you
Low because functionality is correct.

**Comment by cgardens** [comment] 2021-01-08 03:32
This is a duplicate.

Would be really helpful if some you can describe how to replicate.

**Comment by michel-tricot** [comment] 2021-01-08 04:00
duplicate of https://github.com/airbytehq/airbyte/issues/1496

**Closed by michel-tricot** 2021-01-08 04:00 UTC
Labels: area/frontend, priority/low, type/bug

**Comment by michel-tricot** [comment] 2021-01-08 04:02
I added a gif of the error on  #1496
