### ISSUE TITLE
post mortem: api (enum serialization issue)

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#10990] opened 2022-03-09 16:16 UTC

**Comment by pmossman** [comment] 2022-03-17 14:56
# 2022-02-07 API Enum Serialization Postmortem


## Summary

The FailureOrigin#replicationWorker enum value was changed to FailureOrigin#replication without proper handling for database records containing the old value in the attempts.failure_summary jsonb column. When the API attempted to deserialize such records into an AttemptFailureSummary object, an exception was thrown, leading to a page crash for workspaces with a record containing the old enum value.


### Timeline



* **Friday, Feb 4th**: [v0.35.17-alpha](https://github.com/airbytehq/airbyte/releases/tag/v0.35.17-alpha) release created containing the [commit](https://github.com/airbytehq/airbyte/commit/01f4675a5988f3bfdb68a89957619343033cfd7a) that renamed `replicationWorker` to `replication`, and that exposed AttemptFailureSummaries in the API. Cloud was upgraded to this release on the same day. QA on staging did not encounter the issue because the tested workspace did not contain a record with the old enum value. Change was **not** deployed to prod until Monday.
* **Monday, Feb 7th:**
    * **5:21pm:** Lake deploys **v0.35.18-alpha** to Cloud production (prior to this, prod was at **v0.35.16-alpha**).
    * **6:24pm**: Lake encounters failure_summary deserialization error while testing his unrelated change on Cloud production, asks Parker if there were any recent changes related to failure summaries.
    * **6:52pm**: Parker confirms that the root cause of the issue was the enum value rename from `replicationWorker` to `replication`
    * **7:12pm**: After some brainstorming, Parker and Lake decide that the best immediate course of action is to add `replicationWorker` to the API’s AttemptFailureSummary schema so that affected database records could be successfully deserialized. Parker creates [this PR](https://github.com/airbytehq/airbyte/pull/10166/files) that adds `replicationWorker` and `unknown` back into the FailureOrigin enum
        * `unknown` was removed at the same time as the `replicationWorker` -> `replication` rename. It didn’t cause any issues because no code path ever executed that persisted a database record containing this value in Cloud. Parker and Lake decided it would be safest to add it back in regardless, especially in case somebody’s OSS deployment did persist such a record.
    * **9:17pm**: Parker creates a new open source version [v0.35.21-alpha](https://github.com/airbytehq/airbyte/releases/tag/v0.35.21-alpha) containing the `replicationWorker` enum value, and upgrades Cloud to it. Lake loads the same workspace where he observed the original issue, and it now has a new error complaining that `AttemptFailureOrigin.REPLICATION_WORKER` could not be found.
    * **9:18pm**: Lake verifies that the AttemptFailureOrigin enum codegen resulted in `replicationworker` instead of ‘replication_worker`, and the value should have been added as ‘replication_worker’ instead of ‘replicationWorker’ to the openapi/config.yaml enum definition.
    * **10:08pm**: Parker creates another new open source version [v0.35.23-alpha](https://github.com/airbytehq/airbyte/releases/tag/v0.35.23-alpha) containing the fixed replication_worker enum value definition and prepares it for Cloud release.
    * **10:52pm**: Cloud prod deploy finished. Lake verifies that the test workspace in which he saw the original issue was now working as expected. \

* _At this point, the system was in a working state. All new records were being written with ‘replication’ enum values, and old records containing ‘replicationWorker’ enum values were able to be deserialized and presented in the UI. Parker later [created a Flyway migration](https://github.com/airbytehq/airbyte/pull/10773) that handled the deprecation of ‘replicationWorker’ enum values correctly, by identifying records containing the deprecated enum values and updating them to the correct new values. This PR also corrected any instances of snake_case vs camelCase discrepancies in enum definitions that could have caused more issues if their code path had ever been activated._


### Impact

From **5:21pm **until **10:52pm**, Cloud customers attempting to load a workspace with a job history containing a ‘replicationWorker’ failure would encounter a page load error, preventing them from using the Connections page. Furthermore, any OSS user who upgraded their deployment to **v0.35.17-alpha **could have potentially encountered this issue until upgrading to **v0.35.23-alpha**.

No Cloud customer or OSS user ever reported an issue, so it is believed that not many workspaces had associated records with the bad enum values and that external impact was minimal.


### Resolution

Once it was learned that old database records with ‘replicationWorker’ enum values couldn’t be deserialized, Parker and Lake brainstormed ideas to quickly get the system back to a working state. They decided to add ‘replicationWorker’ as an eligible enum value to the AttemptFailureSummary object, to enable deserialization of database records containing the old value.


### Detection

Lake noticed this issue while testing an unrelated change on Cloud. The workspace he was using for his test happened to contain a database record with the ‘replicationWorker’ value, which caused his page to crash on the deserialization error.


### Lessons learned

**_What went well?_**



* The root cause was quickly identified as the error message was very clear

**_What went wrong?_**



* Unit tests and integration tests did not catch the original issue. This particular situation is hard to specifically test for, as it involves storing and processing a value that was no longer referenced anywhere in source code.
* The initial fix did not work because of the unexpected codegen behavior that differs between openapi/config.yaml and FailureReason.yaml for camelCase values.
* Build/release process was painfully slow and had transient test failures that caused further delays.
* The camelCase codegen issue was not caught before trying to load the workspace in production
* It was very difficult to determine the scope of the issue due to difficulty of querying on nested properties of a jsonb column

**_Where did we get lucky?_**



* No customers or users ever reported encountering this issue, it seems like this was noticed and fixed by engineering without noticeable customer impact.
* Lake happened to test his feature using a workspace that was affected by this issue.


### Action Items

**Should be prioritized ASAP:**



* The commit/build/release/deploy process should be improved, especially for validating and releasing bug fixes to Cloud environments quickly.
    * Issues:
        * Improve deploy process of an OSS branch to Cloud dev [#9651](https://github.com/airbytehq/airbyte/issues/9651)
        * Investigate what we need to do to develop on cloud locally [#1155](https://github.com/airbytehq/airbyte-cloud/issues/1155)

**Should be addressed in a future reliability quarter:**



* We should try to make it possible to share enum definitions between [openapi/config.yaml](https://github.com/airbytehq/airbyte/blob/master/airbyte-api/src/main/openapi/config.yaml#L3342-L3351) and json-schema definitions like [FailureReason.yaml](https://github.com/airbytehq/airbyte/blob/master/airbyte-config/models/src/main/resources/types/FailureReason.yaml#L10-L19) so that codegen discrepancies like we ran into here are impossible
    * Issues:
        * Will add issues once team reviews/aligns on action items
* We could populate a staging environment with mock data that tries to comprehensively cover all possible configurations, and evolves as our codebase does. This way, bugs/regressions like removing an enum value could potentially be caught by an automated integration test before going live.
    * Issues:
        * Will add issues once team reviews/aligns on action items

**Closed by pmossman** 2022-03-17 14:56 UTC
Labels: type/enhancement, area/platform
