### ISSUE TITLE
Create WebBackend endpoints that support pagination

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#828] opened 2020-11-05 18:55 UTC
## Tell us about the problem you're trying to solve
As of v0.4.0, the UI supports a couple of views which group sources by the destination they're connected to or vice-versa (example in the screenshot below). 
![image](https://user-images.githubusercontent.com/6246757/98283170-17168d80-1f54-11eb-80b1-3bae3217c394.png)

Currently this view performs its work by calling `web_backend/connections/list` then performing the group-by client-side. 

If we ever want to support pagination, we'll need to move this call to the web backend in order to return complete groupings in each page.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368112717076) by [Unito](https://www.unito.io)

**Comment by davinchia** [comment] 2021-05-25 02:33
@harshithmullapudi is contributing this as part of #3550.

@johnlafleur the back end changes are mostly done and will let us paginate connections, sources and destinations. Can we get some UI mock ups so we can hand this to @Jamakase ?

@harshithmullapudi is there a particular page tab you want paginated? Or would you require all of them to be paginated? It should be marginal to add pagination to more pages; I'm asking in case we have scheduling constraints and need to prioritise tabs.

**Comment by harshithmullapudi** [comment] 2021-05-25 03:45
@davinchia our priority is to add it to connections page first.

**Comment by davinchia** [comment] 2021-05-25 07:00
@harshithmullapudi would you also like the UI to expose configuring the number of connections per page? Or is the default of 25 good enough for your use case? 

Allowing the user to configure the number of connections per page (the limit in the api request) is probably slightly more complex on the front end.

**Comment by harshithmullapudi** [comment] 2021-05-25 07:49
@davinchia for our use case 25 should be more than enough. But I think that feature of having limit configuration on frontend is something which is a good to have. I can work on that should be fine.

**Comment by johnlafleur** [comment] 2021-05-25 09:52
Suggestion of design: https://www.figma.com/file/etaOkOsnXMoKwbfhCD71kw/Web-app?node-id=25478%3A1813

**Comment by harshithmullapudi** [comment] 2021-05-25 09:55
@johnlafleur looks good to me.

**Comment by Jamakase** [comment] 2021-05-25 10:49
Another option that we could consider instead of having pagination controls: have infinite scroll, so we will load new items when we scrolled down till the end of old items.

**Comment by Jamakase** [comment] 2021-05-25 10:56
@sherifnada @davinchia Also keep in mind, that we can't just add pagination on the backend without additional changes on UI. 

The main issue that we will need to fix is not only listings. What is actually more important, that in some parts of the application we assume that we receive all the data ( especially all created connections ) This is how we understand which connectors we are using and which not in the admin page and then groupBy usage. 

Also, quite the same way we display icons for connections: we find them from list of sourceDefinitions or destinationDefinitions, but this one would be easier to fix as we could use get request in place here.

So just adding pagination could break logic on UI. We have discussed it with @cgardens numerous times before, that it was safe to assume no pagination for now and logic could be broken when we need to add pagination.

**Comment by cgardens** [comment] 2021-05-25 23:08
@Jamakase makes a good point. as we paginate various endpoints we need to make sure there is a migration path for the UI as well. I'm definitely in favor of us starting to move towards pagination, if we are starting to inhibitive performance issues, but @Jamakase is right, we have made some tradeoffs in the UI where we assume all data is sent so, as we change the API interface, we need to make sure give him an idea of how we want the UI to change or how we will still get him all of the data he needs in a paginated form.

@harshithmullapudi - for posterity, can you explain why you're looking for pagination? are you having issues with page load times? i'm looking at the implementation [here](https://github.com/airbytehq/airbyte/pull/3550/files) and it seems like we would still be pulling all records from the "database", so the cost server side will still be relatively high. so i'm guess that the issue is that the browser can't handle all of the data. sorry if you explained this to @davinchia already, but i want to make sure we get all the info for this in one spot.

**Comment by harshithmullapudi** [comment] 2021-05-26 03:41
@cgardens i understand what @Jamakase is trying to put here. We did try couple of things before deciding that we need pagination. We have approx 240 connections and the query from backend is fast enough but our UI we are no able to use, sometimes scroll gets stuck, sometimes whole page gets stuck. Our connections grow 3 or 4 per day.

**Comment by harshithmullapudi** [comment] 2021-05-26 16:38
@cgardens any update on this ?

**Comment by cgardens** [comment] 2021-05-26 17:20
@harshithmullapudi - thanks for the extra info.
 
@Jamakase is going to work on doing some client side pagination / infinite scroll that should address the rendering issues you are seeing. Our plan would be to have it shipped by the end of next week. Would that work okay for you?

**Comment by harshithmullapudi** [comment] 2021-05-27 04:06
Hey @cgardens by end of next week we would be reaching 500 connections or so having all that in memory do you think that's a good idea? If this doesn't cause any issue we would be happy to go ahead.

We did spend sometime on it so we want to have a good solution so that we don't have to come back and reload at it in near time

**Comment by cgardens** [comment] 2021-05-28 04:19
@harshithmullapudi would you like to try to jump on a call tomorrow morning? I think I need to understand the projected growth of your connectors. If your connectors are going to keep growing at this point, then yeah, you'll run into more problems. I need to better understand where you're going.

**Comment by cgardens** [comment] 2021-05-28 04:36
Actually will let @davinchia  take back over since he has a bit more context.

**Comment by evantahler** [comment] 2022-08-01 19:09
Closing in favor of the new epic https://github.com/airbytehq/airbyte/issues/14282

**Closed by evantahler** 2022-08-01 19:09 UTC
Labels: type/enhancement, priority/low, team/oss
