### ISSUE TITLE
MySQL connector not working without any valid reason

### ISSUE THREAD

**Issue by kristiyan-scaleforce** [airbytehq/airbyte#27947] opened 2023-07-04 13:42 UTC
### Connector Name

mysql

### Connector Version

0.40.18

### What step the error happened?

During the sync

### Revelant information

The integration works randomly and stops randomly as well. There isn't any particular issue in terms of readable error. Here is a part of the log that we find as a possible explanation: 

2023-06-30 14:35:08  [1;31mERROR [m i.a.w.g.DefaultReplicationWorker(run):209 - Sync worker failed.
java.util.concurrent.ExecutionException: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
 at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
 at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
 at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:201) ~[io.airbyte-airbyte-commons-worker-0.40.18.jar:?]
 at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:78) ~[io.airbyte-airbyte-commons-worker-0.40.18.jar:?]
 at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$4(TemporalAttemptExecution.java:190) ~[io.airbyte-airbyte-workers-0.40.18.jar:?]
 at java.lang.Thread.run(Thread.java:1589) ~[?:?]
 Suppressed: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
  at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:144) ~[io.airbyte-airbyte-commons-worker-0.40.18.jar:?]
  at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:161) ~[io.airbyte-airbyte-commons-worker-0.40.18.jar:?]
  at io.airbyte.workers.general.DefaultReplicationWorker.run(DefaultReplicationWorker.java:78) ~[io.airbyte-airbyte-commons-worker-0.40.18.jar:?]
  at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$4(TemporalAttemptExecution.java:190) ~[io.airbyte-airbyte-workers-0.40.18.jar:?]
  at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: io.airbyte.workers.general.DefaultReplicationWorker$SourceException: Source cannot be stopped!
 at io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:390) ~[io.airbyte-airbyte-commons-worker-0.40.18.jar:?]
 at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
 ... 1 more
Caused by: io.airbyte.workers.exception.WorkerException: Source process exit with code 1. This warning is normal if the job was cancelled.
 at io.airbyte.workers.internal.DefaultAirbyteSource.close(DefaultAirbyteSource.java:144) ~[io.airbyte-airbyte-commons-worker-0.40.18.jar:?]
 at io.airbyte.workers.general.DefaultReplicationWorker.lambda$getReplicationRunnable$6(DefaultReplicationWorker.java:388) ~[io.airbyte-airbyte-commons-worker-0.40.18.jar:?]
 at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]

### Contribute

- [ ] Yes, I want to contribute

**Comment by marcosmarxm** [comment] 2023-09-15 17:31
Hello @kristiyan-scaleforce I'm closing this because you need to provide more information to make the issue reproducible.

**Closed by marcosmarxm** 2023-09-15 17:31 UTC
Labels: type/bug, area/connectors, community, needs-triage, team/connectors-python, autoteam
