### ISSUE TITLE
Support multiple columns for cursor in Incremental Load

### ISSUE THREAD

**Issue by vaibhavpals** [airbytehq/airbyte#14404] opened 2022-07-05 09:53 UTC
## Environment
- **Airbyte version**:  0.39.32-alpha
- **OS Version / Instance**: Ubuntu 22 AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: All RDBMS Source connectors (Oracle DB 0.3.17)
- **Destination Connector and version**: Any Destination (Redshift 0.3.46)
- **Step where error happened**:  Sync job 

## Current Behavior
Only able to select one column for cursor. This causes incremental sync to miss updates if we track only using created_date column.

## Expected Behavior
We should be able to select multiple columns to track incremental data. Many Applications use modified date as well as created date columns. Modified Date column remains NULL for inserts and gets updated in case of UPDATES. We need to track both INSERTS and UPDATES. Connector should implement like COALESCE(MODIFIED_DATE,CREATED_DATE) as cursor.

## Logs
NA

## Steps to Reproduce
1. Create a sync job on a table which maintains both created_dt and modified_dt column. modified_dt column only gets populated and updated whenever there is an update to an existing record. created_dt column gets populated at the time of insert. 
2. Creating a sync job using created_dt as cursor, we miss the UPDATES. If we create a job using modified_dt as cursor, we miss the INSERTS

## Are you willing to submit a PR? 
Not at the moment.

**Comment by marcosmarxm** [comment] 2022-07-05 11:35
Thanks for requesting this @vaibhavpals the issue is a duplicate of https://github.com/airbytehq/airbyte/issues/3737. I'll close this in favor of older one. Feel free to comment in the original issue.

**Closed by marcosmarxm** 2022-07-05 11:35 UTC
Labels: type/bug, community, needs-triage, team/use, autoteam
