### ISSUE TITLE
🐛 Source Amplitude: failure in events stream, sends incorrect timestamp to postgres

### ISSUE THREAD

**Issue by giletichart** [airbytehq/airbyte#13266] opened 2022-05-27 13:33 UTC
## Environment
- **Airbyte version**: 0.38.4-alpha
- **OS Version / Instance**: Ubuntu 20.04.3 LTS
- **Deployment**: Docker
- **Source Connector and version**: Amplitude 0.1.7
- **Destination Connector and version**: Postgres 0.3.20
- **Severity**: Critical
- **Step where error happened**: Sync job

## Current Behavior
I updated an Amplitude connector from 0.1.6 to 0.1.7 and sync stopped working. I've tried to rollback connector to previous version (0.1.6) and still got the same issue.

```
2022-05-27 07:17:49 [42mnormalization[0m > 07:17:44.528710 [error] [MainThread]: [33mDatabase Error in model events (models/generated/airbyte_incremental/amplitude_airbyte_mtvl_android/events.sql)[0m
2022-05-27 07:17:49 [42mnormalization[0m > 07:17:44.529108 [error] [MainThread]:   date/time field value out of range: "2022:05:27 05:59:45.471635"
```

There are updates in dates formatting in [last version](https://github.com/airbytehq/airbyte/pull/13074/files). Maybe some of them is causing the issue. However, I don't fully understand, why this issue still occurs on previous version.

## Expected Behavior
Dates should be send to postgres in format like this: ```"2022-05-27 05:59:45.471635"``` instead of ```"2022:05:27 05:59:45.471635"```. 

## Logs
[failure at 0.1.7.txt](https://github.com/airbytehq/airbyte/files/8786944/failure.at.0.1.7.txt)

[failure at 0.1.6 (after rollback).txt](https://github.com/airbytehq/airbyte/files/8786945/failure.at.0.1.6.after.rollback.txt) 
Please disregard errors with duplicate values, I'll clean it up after main error will be fixed

[last success at 0.1.6 (before upgrading connector).log](https://github.com/airbytehq/airbyte/files/8786949/last.success.at.0.1.6.before.upgrading.connector.log)
original file is 205mb, I deleted all lines containing message "The supplied date/time format type does not match the specification" and "Failed to apply RFC3339 pattern on..."  #13057, #13075 

## Steps to Reproduce
1. Create Amplitude connection with events stream enabled.
2. Trigger a few syncs.

## Are you willing to submit a PR?
Yes. But I would need some guidance.

**Comment by grkhr** [comment] 2022-05-27 16:40
Same here. It seems like it's the bug on Amplitude's side. It started happening today at ~1AM and still happening.
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/40689054/170742063-079400e6-1141-45c4-aeda-2fedabfb74e8.png">

**Comment by bazarnov** [comment] 2022-06-02 21:47
> Same here. But it seems like the bug is on Amplitude's side. It started happening today at ~1AM and still happening.

Great catch @grkhr ! Will keep an eye on this before reproduction.

**Comment by toandm** [comment] 2022-06-07 02:58
Hi guys, looks like this issue is fixed by Amplitude, but the old affected data will still be the same. Any idea on how to resolve this in Airbyte?
Ref: https://community.amplitude.com/instrumentation-and-data-management-57/incorrect-date-format-for-processed-time-field-from-the-export-api-1089?postid=3707#post3707

**Comment by bazarnov** [comment] 2022-06-07 11:39
@giletichart 
Considering this comment: https://github.com/airbytehq/airbyte/issues/13266#issuecomment-1148138271
I believe the issue could be closed, please re-open it if required.

**Comment by bazarnov** [comment] 2022-06-07 12:46
Please verify your data for the period considered as `period when broken date-times comes from API side`, if the API response is fixed now, you might probably have the wrong date-time in the past, which causes the normalization fail.

**Comment by toandm** [comment] 2022-06-07 12:57
Yes, I just checked, and the data is still in the incorrect form of "YYYY:MM:DD" instead of "YYYY-MM-DD" for the broken period. My period is specifically from 2022-05-27.
In the article that I sent above, they mentioned that the data is fixed from Friday (Jun 3rd 2022) onwards. But the old data that has the wrong form is still the same.

**Comment by bazarnov** [comment] 2022-06-07 12:57
This is a very big issue then.

**Comment by bazarnov** [comment] 2022-06-07 13:13
Thank you for the data sample! Very useful.

I guess we need to fact-check first, if the connector could handle/parse this broken date-time into the correct date-time object. If so, there should be the issue in other place. I'll make the test asap and will keep you posted. Thanks again.

**Comment by bazarnov** [comment] 2022-06-07 13:24
In a meanwhile, @toandm, would that be a problem to make another fresh sync, using new connection created?
I believe there is a raw data in the database, which causes the issue with normalization, since the connector handles the: `processed_time` column correctly and formats it as expected, even if the date-time is something like: `"2022:05:27 02:00:43.324890"`. The new fresh connection will create fresh `_airbyte_raw_data` tables and the dates should be correctly passed.

**Comment by toandm** [comment] 2022-06-07 14:11
@bazarnov You mean perform a fresh sync with Amplitude connector version 0.1.8? I have already created a fresh Amplitude source, run the sync again to get data from 2022-05-25. It's been running for 3 hours with over 3 million records now, but the current data I have in the database only have 1.4M records. So I'm not sure what's going on.

**Comment by toandm** [comment] 2022-06-07 14:16
@bazarnov Here is the log file if you are interested. I don't think there should be that many records.
[logs-369-0.txt](https://github.com/airbytehq/airbyte/files/8853968/logs-369-0.txt)

**Comment by toandm** [comment] 2022-06-07 14:43
You mean you would like me to make a fresh sync after your update right? Absolutely

**Comment by toandm** [comment] 2022-06-08 04:04
Hi guys, while waiting for the update, I performed a hot fix by transforming the data in my data warehouse
Turns out for every sync, Airbyte stores raw data in a table with "_airbyte_raw" prefix. Then if an incremental job fails at the normalization step, it will continue to use the data in that raw table, using the _airbyte_emitted_at as a cursor field.
So what I did was backing up the _airbyte_raw_events table, and perform a regex replace for all bad datetime values. After that, the normalization runs successfully.
I attached herewith a SQL script of what I did. My data warehouse is Google BigQuery. Please replace the REGEX_REPLACE with your database's respective function. Hopefully this helps some of you guys out there.

[bigquery_replace_bad_datetime.txt](https://github.com/airbytehq/airbyte/files/8858206/bigquery_replace_bad_datetime.txt)

**Comment by bazarnov** [comment] 2022-06-08 09:23
> I attached herewith a SQL script of what I did. My data warehouse is Google BigQuery.

This links is broken. Please review.

> I performed a hot fix by transforming the data in my data warehouse.

This is the best strategy could be performed in this case. Great work.

> There is nothing to update so far, the connector handles the bad date-times like this: "2022:05:27 02:00:43.324890" correctly, and transforms it into the correct format for normalization.

The issue is in  "_airbyte_raw*" tables which holds the old bad values, as was said here: https://github.com/airbytehq/airbyte/issues/13266#issuecomment-1148671693
Unfortunately, we could not maintain the ambiguous responses from API, and this problem is not related to either connector, or normalization. Couple of ways how to be in this case: 
1) `Find and Replace` in your destination, like @toandm did in his case.
2) `Reset the data` in your active connection and re-sync all over again (time consuming, but will definitely work)

**Comment by toandm** [comment] 2022-06-08 09:31
> This links is broken. Please review.
I can still download it though. I'll post the content here then.
```
TRUNCATE TABLE `my-project.amplitude._airbyte_raw_events`
;
SELECT * FROM `my-project.amplitude._airbyte_raw_events` LIMIT 10
;
INSERT INTO `my-project.amplitude._airbyte_raw_events`
SELECT
  _airbyte_ab_id
  ,_airbyte_emitted_at
  ,REGEXP_REPLACE(_airbyte_data, r'(\d{4}):(\d{2}):(\d{2}.+)', r'\1-\2-\3') AS _airbyte_data
FROM `my-project.backup_amplitude._airbyte_raw_events_copy` --This is the backup table
```
Thank you for your timely response @bazarnov You've been really helpful

**Closed** 2022-06-09 10:02 UTC
Labels: type/bug, area/connectors, lang/python, community, connectors/source/amplitude, team/connectors-python

**Comment by grkhr** [comment] 2022-06-10 12:26
@bazarnov 
> Reset the data in your active connection and re-sync all over again (time consuming, but will definitely work)

Why it will work if Amplitude gives broken timestamps for this period, as mentioned [here](https://community.amplitude.com/instrumentation-and-data-management-57/incorrect-date-format-for-processed-time-field-from-the-export-api-1089?postid=3707#post3707)? It will just break on normalization phase

**Comment by khoatrandata** [comment] 2022-07-05 02:10
The Amplitude API still sends corrupted timestamps for the period of 2022-05-27, so if your connector is incremental sync then those errors will appear again.

**Comment by khoatrandata** [comment] 2022-07-06 00:41
How can I reopen this issue? My Incremental Deduped History sync job with Amplitude source fails because there is corrupted data from 2022-05-27 to 2022-06-03 from the source API, the cursor is at 2022-05-26. I can't find a way to fix this

**Comment by khoatrandata** [comment] 2022-07-06 07:04
Hi, @toandm how do you stop the source from fetching corrupted data from 2022-05-27 to 2022-06-03 from Amplitude?

**Comment by bazarnov** [comment] 2022-07-06 08:39
@khoatrandata 
Does this help? https://github.com/airbytehq/airbyte/issues/13266#issuecomment-1149684808

**Comment by khoatrandata** [comment] 2022-07-10 23:50
@bazarnov , that doesn't help and I've tried it. Corrupted data will be repopulated on the `_airbyte_*` table upon resync since the job cursor is prior to the period.
