### ISSUE TITLE
[source-posthog] Events: One Event record fetched multiple time in one sync

### ISSUE THREAD

**Issue by Nikpatel30** [airbytehq/airbyte#35996] opened 2024-03-12 19:38 UTC
### Connector Name

posthog

### Connector Version

1.0.0

### What step the error happened?

During the sync

### Relevant information

Source: Posthog
Destination: Google Bigquery using GCS Staging
Incremental Append Sync every 24 hour.
Stream: Events

Sync was running for last 48 hour, where it usually run for 2-3 mins day to fetch alL events data. my Event data usually under 10k records, but for this last since it was manage to capture 11M records. 
Simply is capturing one event multiple times, can be seen screenshot. 

This was happened before with the connector. Simply at that time I remove the connection and re-establish it and started working fine. But it seems it's been doing this quite often. 

![Screenshot from 2024-03-12 12-36-58](https://github.com/airbytehq/airbyte/assets/34329400/d8aff18d-a17e-40f7-911b-a6fa0eea5214)

### Contribute

- [X] Yes, I want to contribute

**Comment by marcosmarxm** [comment] 2024-03-14 18:16
What version of destination and platform are you using?

**Comment by Nikpatel30** [comment] 2024-03-14 19:32
Google Bigquery : 2.3.4

**Comment by MaxwellJK** [comment] 2024-04-18 20:40
possibly a duplicate of https://github.com/airbytehq/airbyte/issues/33915? (i opened from my work account)
If so, I am working on the PR in these days - bear with me pls 🙏

**Comment by marcosmarxm** [comment] 2024-04-30 20:02
Closed as duplicated of #33915

**Closed by marcosmarxm** 2024-04-30 20:02 UTC
Labels: type/bug, area/connectors, community, connectors/source/posthog, team/connectors-python
