### ISSUE TITLE
Build failure in python 3.9.1

### ISSUE THREAD

**Issue by djKooks** [airbytehq/airbyte#2099] opened 2021-02-17 13:35 UTC
## Current Behavior
I'm using python 3.9, and facing following error at `gradlew build`:

```
> Task :airbyte-integrations:bases:base-python:checkPython FAILED
Using python 3.9.1 from /Library/Frameworks/Python.framework/Versions/3.9 (python3)
Using pip 20.2.3 from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)
         WARNING: Package(s) not found: virtualenv
[python] python3 -m pip install virtualenv==16.7.9 --user
         Collecting virtualenv==16.7.9
           Downloading virtualenv-16.7.9-py2.py3-none-any.whl (3.4 MB)
         Installing collected packages: virtualenv
           WARNING: The script virtualenv is installed in '/Users/kination/Library/Python/3.9/bin' which is not on PATH.
           WARNING: The script virtualenv is installed in '/Users/kination/Library/Python/3.9/bin' which is not on PATH.Successfully installed virtualenv-16.7.9
           Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
         WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
         You should consider upgrading via the '/Library/Frameworks/Python.framework/Versions/3.9/bin/python3 -m pip install --upgrade pip' command.
Using virtualenv 16.7.9 (.venv)
[python] python3 -m virtualenv .venv
         Using base prefix '/Library/Frameworks/Python.framework/Versions/3.9'
         New python executable in /Users/kination/workspace/oss/airbyte/airbyte-integrations/bases/base-python/.venv/bin/python3
         Also creating executable in /Users/kination/workspace/oss/airbyte/airbyte-integrations/bases/base-python/.venv/bin/python
         ERROR: The executable /Users/kination/workspace/oss/airbyte/airbyte-integrations/bases/base-python/.venv/bin/python3 is not functioning
         ERROR: It thinks sys.prefix is '/Library/Frameworks/Python.framework/Versions/3.9' (should be '/Users/kination/workspace/oss/airbyte/airbyte-integrations/bases/base-python/.venv')
         ERROR: virtualenv is not compatible with this system or executable
```

Seems it is using `virtualenv` for wrap-up dev environment, but if this project is targeting Python 3, I think it will be better to use standard module `venv` if there is no issue with this.

## Airbyte Version
0.14.3-alpha

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368213636010) by [Unito](https://www.unito.io)

**Comment by djKooks** [comment] 2021-02-17 14:20
Also tried with newest virtualenv version, and it shows different issue:
```
./gradlew clean build
/Users/kination/workspace/oss/airbyte/airbyte-integrations/connectors

> Task :airbyte-integrations:bases:base-normalization:checkPython FAILED
Using python 3.9.1 from /Library/Frameworks/Python.framework/Versions/3.9 (.venv/bin/python)
Using pip 20.2.3 from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)

> Task :airbyte-integrations:bases:airbyte-protocol:checkPython FAILED
Using python 3.9.1 from /Library/Frameworks/Python.framework/Versions/3.9 (.venv/bin/python)
Using pip 20.2.3 from /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip (python 3.9)

> Task :tools:code-generator:airbyteDocker
#1 [internal] load build definition from Dockerfile
#1 sha256:878ed124c7c1e4fd9be589419cd9c3fb5642f417e00bea8f481d8651ccac9f65
#1 transferring dockerfile: 37B done
#1 DONE 0.4s

#2 [internal] load .dockerignore
#2 sha256:11c71c0c4a91f55e9f3cdb732f155134d5c42c01b1baf87e58c6036bdc0e035b
#2 transferring context: 2B done
#2 DONE 0.4s
...
...
...
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':airbyte-integrations:bases:base-normalization:checkPython'.
> Convfigured environment is not a virtualenv: /Users/kination/workspace/oss/airbyte/airbyte-integrations/bases/base-normalization/.venv. Most likely, issue appear due to incorrect `python.envPath` configuration.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':airbyte-integrations:bases:airbyte-protocol:checkPython'.
> Convfigured environment is not a virtualenv: /Users/kination/workspace/oss/airbyte/airbyte-integrations/bases/airbyte-protocol/.venv. Most likely, issue appear due to incorrect `python.envPath` configuration.
```

**Comment by sherifnada** [comment] 2021-02-17 14:36
@djKooks thanks for creating the issue. Airbyte is tested with Python 3.7 - are you able to run the build with that version?

**Comment by djKooks** [comment] 2021-02-19 02:31
@sherifnada I've also tested with 3.8, and it does not cause this issue...but shows other test error:
```
> Task :airbyte-workers:test FAILED
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mockito.internal.util.reflection.AccessibilityChanger (file:/Users/kination/.gradle/caches/modules-2/files-2.1/org.mockito/mockito-core/3.4.6/ac377337eb06d243cf603b0d21fecdbb914b6143/mockito-core-3.4.6.jar) to field java.io.ByteArrayOutputStream.buf
WARNING: Please consider reporting this to the maintainers of org.mockito.internal.util.reflection.AccessibilityChanger
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

DockerProcessBuilderFactoryTest > testImageExists() FAILED
    org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:39)
        at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:40)
        at org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:35)
        at org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:162)
        at io.airbyte.workers.process.DockerProcessBuilderFactoryTest.testImageExists(DockerProcessBuilderFactoryTest.java:46)

51 tests completed, 1 failed, 1 skipped
```

**Comment by sherifnada** [comment] 2021-02-19 03:41
@djkooks Which Java version are you on? Can you make sure you are on Java 14, connected to the internet, and have docker daemon running then run ./gradlew clean build ?

**Comment by djKooks** [comment] 2021-02-19 04:09
@sherifnada yes, right. For more:
- Java: 14.0.2
- Python: 3.8.2
- OS: MacOS Catalina
- Docker: 20.10.2

If docker doesn't run, it fail on running `airbyte-docker`...

**Comment by sherifnada** [comment] 2021-02-22 06:20
@djKooks put up a PR to fix this test case: https://github.com/airbytehq/airbyte/pull/2144

If you apply the PR to your local codebase this would make the test pass for you in the meatnime

**Comment by sherifnada** [comment] 2021-02-22 06:38
@djKooks if you run `docker images | grep airbyte/scheduler` do you find a line like the following: 

```
airbyte/scheduler                                      dev            a3b5f352658e   6 minutes ago   980MB
```

If not, i believe the issue is a race condition where it takes too long to build the scheduler images so the test times out. Can you try running `./gradlew composeBuild` followed by `./gradlew build`?

**Comment by djKooks** [comment] 2021-03-02 10:29
@sherifnada seems it also not working in this way...
So is it the issue of testing?

**Comment by davinchia** [comment] 2021-04-22 14:06
@djKooks are you still running into this?

**Comment by davinchia** [comment] 2022-01-11 10:28
@djKooks I'm going to close this for now

**Closed by davinchia** 2022-01-11 10:28 UTC
Labels: type/bug
