### ISSUE TITLE
Make clear the cancel request is being processed.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#10825] opened 2022-03-03 12:47 UTC
## Tell us about the problem you're trying to solve
It can take a while for the cancel request to be processed. Today the button doesn't do anything. This is confusing to the user since it's not clear what is happening.

There should be an indicator of some sort that the cancel click has been registered and is being processed.

## Describe the solution you’d like
Naive solution: spinner?

## Describe the alternative you’ve considered or used
A clear and concise description of any alternative solutions or features you've considered or are using today.

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by octavia-squidington-iii** [comment] 2022-03-03 12:48
cc @airbytehq/frontend

**Comment by timroes** [comment] 2022-04-25 20:18
Duplicate of https://github.com/airbytehq/airbyte/issues/12091

(Closing this despite being older, since the other is already asigned and in the sprint.)

**Closed by timroes** 2022-04-25 20:18 UTC
Labels: type/enhancement, area/frontend
