### ISSUE TITLE
[source-intercom] Missing parts in conversation_parts sync

### ISSUE THREAD

**Issue by everron** [airbytehq/airbyte#39463] opened 2024-06-13 16:16 UTC
### Connector Name

source-intercom

### Connector Version

since 0.6.6

### What step the error happened?

None

### Relevant information

We're using the intercom source connector on Airbyte (now v0.6.7) cloud to get conversations and their conversations_parts. Our sync config is the following : incremental, append+dedup with updated_at as cursor field and id is the pk.
![image](https://github.com/airbytehq/airbyte/assets/16880552/16f1fdec-4c60-4801-a712-c0442dd71564)

I recently identified that the number of parts synced was different than the number of parts expected, by comparing the number of parts in conversations_parts for each conversation_id and the field `statistics.count_conversation_parts` in the conversations data. About 60% of conversations extracted had a lower number of conversations parts than expected. We use Redshift as the destination database.

Job history logs did not return any error and all syncs are marked as success. I can provide logs if needed

### Contribute

- [ ] Yes, I want to contribute

**Comment by bgdanterty** [comment] 2024-07-08 11:17
I have the same issue. A lot of the conversation_parts data is missing, but if I use a custom Python script that collects JSONs from intercom API 2.10 – I can see them all.

**Comment by luctchak** [comment] 2024-08-29 14:32
👋  Any update on this issue ? It's blocking me as well 😬

**Comment by Alexandros-Gk** [comment] 2024-09-05 10:00
We have the same issue. Conversation parts are missing and also **conversations are not properly updated** - There are mismatches even on state field - I guess do to the fact that the parts are missing!

It is a bit alarming - given that the impact is major and this can happen without a warning. I imagine a lot of users may not be aware this happens on their data! - We've also sent an issue on the support to help us understand why this happen.

**Comment by aldogonzalez8** [comment] 2024-09-05 19:12
I will look on this.

**Comment by octavia-squidington-iii** [comment] 2024-09-06 15:41
Zendesk ticket #[8072](https://airbyte1416.zendesk.com/agent/tickets/8072) has been linked to this issue.

**Comment by aldogonzalez8** [comment] 2024-09-09 11:14
@everron @luctchak @Alexandros-Gk I have identified in my investigation that actually, in the responses from intercom API the conversation_parts.total_count is < than statistics.count_conversation_parts and seems solid 1 diff. 

@bgdanterty  Are you seeing something different? As you mentioned you get all data with a python script.

We have opened a contact on Intercom on this matter, as I'm not sure if the API just has a wrong count or is sending less data to the conversation_parts array.

![image](https://github.com/user-attachments/assets/acabf805-f651-4839-9e3a-a08626363c1b)
![image](https://github.com/user-attachments/assets/6dcdc65f-058c-4273-9916-db366b36189c)

**Comment by everron** [comment] 2024-09-09 13:24
@aldogonzalez8 There indeed seems to be an issue regarding the conversation_parts counter stats in the GET conversation API response. I also opened a ticket for Intercom about this 👍 

However, I did see larger diffs (ie more than 1 part) between the rows count of parts in the loaded table and the real number of parts (seen directly in the Intercom UI)

**Comment by Alexandros-Gk** [comment] 2024-09-09 15:03
@aldogonzalez8 Apart from the discrepancy on the API, we have identified certain periods (where the load actually spiked) on which ingestion did not work at all and entire conversations are missing. Not sure if the issue is on Airbyte's or Intercom side
![image](https://github.com/user-attachments/assets/4a8f60ac-0685-419e-aaf7-83dd0c5e7a08)

From a contact with their CS - they can only look back a small time window.

**Comment by aldogonzalez8** [comment] 2024-09-09 15:14
> @aldogonzalez8 Apart from the discrepancy on the API, we have identified certain periods (where the load actually spiked) on which ingestion did not work at all and entire conversations are missing. Not sure if the issue is on Airbyte's or Intercom side ![image](https://private-user-images.githubusercontent.com/67148156/365704663-4a8f60ac-0685-419e-aaf7-83dd0c5e7a08.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4OTQ4MDQsIm5iZiI6MTcyNTg5NDUwNCwicGF0aCI6Ii82NzE0ODE1Ni8zNjU3MDQ2NjMtNGE4ZjYwYWMtMDY4NS00MTllLWFhZjctODNkZDBjNWU3YTA4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDE1MDgyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgyMWE5YjRmMWRiMTVjYWI1OThkOGRmODg3ZGEyMDdhMzA4ZjRmN2JiY2E4YTZiZGY2NTM4NjY1MTc2YjUzYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KyoTIUqPNF2PMLrTW4vvDjSbzUizKYWJpRmAbkZSQcs)
> 
> From a contact with their CS - they can only look back a small time window.

@Alexandros-Gk, I'm not sure about this. Did you see anything unusual in the sync logs for those days?

**Comment by Alexandros-Gk** [comment] 2024-09-09 15:29
@aldogonzalez8 Apart from a noteworthy drop on sync time there were no errors or warning to dive deeper.

**Comment by aldogonzalez8** [comment] 2024-09-09 19:46
@everron @luctchak @Alexandros-Gk @bgdanterty I got this from Intercom contact/

> For the discrepancy in count_conversation_parts and total_count in [REST API](https://developers.intercom.com/intercom-api-reference/reference/welcome) v2.11:
> 
> 
> 

>  It looks like this count_conversation_parts includes the [source object](https://developers.intercom.com/docs/references/rest-api/api.intercom.io/conversations/conversation#path=source) in the count, but total_count does not include this source object in the count.
> 
> 
> 
> 
>  So this why count_conversation_parts will be one more than the total_count.


@everron Did you get something different about this statement?

> However, I did see larger diffs (ie more than 1 part) between the rows count of parts in the loaded table and the real number of parts (seen directly in the Intercom UI)

**Comment by everron** [comment] 2024-09-10 07:43
@aldogonzalez8 

I got a similar answer from Intercom but insisted for further investigation since the 1 part difference was misleading.

>Did you get something different about this statement?
>>However, I did see larger diffs (ie more than 1 part) between the rows count of parts in the loaded table and the real number of parts (seen directly in the Intercom UI)

I was not able to reproduce the large diffs in conversation_parts by simply calling their API. I've only seen it in the data loaded by Airbyte

**Comment by aldogonzalez8** [comment] 2024-09-10 11:06
Can you extend on large diffs in conversation_parts? I'm not sure what we are discussing here.

> I was not able to reproduce the large diffs in conversation_parts by simply calling their API. I've only seen it in the data loaded by Airbyte

**Comment by everron** [comment] 2024-09-10 16:09
Here is an example.

Calling the Intercom API from postman: `GET https://api.eu.intercom.io/conversations/<conversation_id>`

I get     
```
    ...
    "statistics": {
        ...
        "count_conversation_parts": 56
    },
    ...
    "conversation_parts": {
        "type": "conversation_part.list",
        "conversation_parts": [
            ...
        ],
        "total_count": 55
```

This is the '1 Diff' issue we were talking about. 

Now looking at the number of rows in the conversation_parts table loaded by airbyte with this config:
![image](https://github.com/user-attachments/assets/0ad8e2c7-3a0d-4134-8e01-c9581a3bfaea)

Only 52 parts were loaded. 
![image](https://github.com/user-attachments/assets/fa2c5a9e-3306-4fe9-ac29-9183e3f91709)

For that particular conversation that's only at most 3 parts, but for others we're missing sometimes more than half of the conversation. We do not have errors in Airbyte logs

**Comment by aldogonzalez8** [comment] 2024-09-10 20:59
> was not able to reproduce the large diffs in conversation_parts by simply calling their API. I've only seen it in the data loaded by Airbyte

That's conversation_parts table count(*), what about data saved in conversations.statistics? What is the count_conversation_parts value?

**Comment by everron** [comment] 2024-09-11 15:29
> what about data saved in conversations.statistics? What is the count_conversation_parts value?

Same value as in the API response, "count_conversation_parts":56

**Comment by bgdanterty** [comment] 2024-09-12 07:53
> @bgdanterty Are you seeing something different? As you mentioned, you get all the data using a Python script.

There is always a difference of one record between the statistics and the actual quantity in the API response, this is true.

In my scenario and in the airbyte assignment, if I compare the number of parts in my long conversation, there is a larger discrepancy between the statistics and the number of facts.
I think there may be several bugs. Something is wrong with the intercom API but my parts count from custom and airbyte is different too. 

here is an example:
<img width="693" alt="Screenshot 2024-09-12 at 10 50 06" src="https://github.com/user-attachments/assets/50dda605-42a3-4805-bfaf-31c748974fe8">

We have also begun to migrate from the intercom to another platform, but this will not happen soon and it is still important for us to receive full volumes of data for analysis and load forecasting.

**Comment by everron** [comment] 2024-09-12 08:04
@aaronsteers 
> Can you say when you first noticed this as an issue, or when you believe the issue started?
Hard to tell, because of the statistics count, but I would say between May 10 and May 13 this year, when the % of conversations having different part counts went from ~10% to 60%

@bgdanterty 

There's also a [hard limit of 500 parts](https://developers.intercom.com/docs/references/rest-api/api.intercom.io/conversations/retrieveconversation) in the conversation API

**Comment by aaronsteers** [comment] 2024-09-12 19:14
@everron - re:

> There's also a [hard limit of 500 parts](https://developers.intercom.com/docs/references/rest-api/api.intercom.io/conversations/retrieveconversation) in the conversation API

Yikes! Is there any workaround that you are aware of? (cc @bgdanterty with the same Q)

If not, we probably should document this as a limitation (if it isn't there already) in our connector docs.

Re:

> I think there may be several bugs.

This ☝️ is increasingly my prevailing theory as well.

## One possible root cause

On the Airbyte side, I only have one prevailing theory as of now, which is that the connector might be leaking state cursors across the `conversations` and `conversation_parts` streams. If this were the case, then certain edge cases, such as the parent stream (`conversations`) succeeding while the child stream (`conversation_parts`) was either disabled, failed, or otherwise skipped. If cursor information leaks from one stream to another, then some number of parts might be added to a conversation that would be missed in the sync and then skipped on subsequent syncs.

The best practice is for sources with parent-child streams such as this one to keep stream state cursors distinct for the reasons above, even though the child stream doesn't have its own incremental key and must rely on the parent endpoint to be marked as changed. If we can confirm that the Intercom source is not performing in this way, then it would be a bug on the connector and we would try to prioritize for resolution in the coming cycle. (Unfortunately, I've done a rough scope and this could be a week or two engineering time to resolve. It is not a quick fix and likely we'd want to first confirm the root cause and then move to prioritize a refactor once confirmed.)

## Short-term Mitigation

If the above is the root cause (and even if not), a remediation step in this case would be to run a full sync on the child stream (`conversation_parts`) with the goal to re-sync any conversations who were skipped in the recurring incremental syncs.

- This mitigation doesn't solve the root cause, or prevent in the future. It would however, recover any missing records from past syncs.
- It also doesn't solve what appear to be faulty or inconsistent logics in the intercom API's statistics counts.
- It likewise wouldn't solve for the 500 part limit that @everron calls out.

@everron, @bgdanterty - would you be interested in attempting this mitigation and reporting back?

**Comment by everron** [comment] 2024-09-13 14:06
Thanks @aaronsteers 

The 500 parts limit didn't bother us too much, as we had fewer than 10 such conversations (out of thousands in 2024). We will live with it.

I'll try the full sync of the conversation_parts streams and will get back to you

**Comment by Alexandros-Gk** [comment] 2024-09-18 10:57
> @everron - re:
> 
> > There's also a [hard limit of 500 parts](https://developers.intercom.com/docs/references/rest-api/api.intercom.io/conversations/retrieveconversation) in the conversation API
> 
> Yikes! Is there any workaround that you are aware of? (cc @bgdanterty with the same Q)
> 
> If not, we probably should document this as a limitation (if it isn't there already) in our connector docs.
> 
> Re:
> 
> > I think there may be several bugs.
> 
> This ☝️ is increasingly my prevailing theory as well.
> 
> ## One possible root cause
> On the Airbyte side, I only have one prevailing theory as of now, which is that the connector might be leaking state cursors across the `conversations` and `conversation_parts` streams. If this were the case, then certain edge cases, such as the parent stream (`conversations`) succeeding while the child stream (`conversation_parts`) was either disabled, failed, or otherwise skipped. If cursor information leaks from one stream to another, then some number of parts might be added to a conversation that would be missed in the sync and then skipped on subsequent syncs.
> 
> The best practice is for sources with parent-child streams such as this one to keep stream state cursors distinct for the reasons above, even though the child stream doesn't have its own incremental key and must rely on the parent endpoint to be marked as changed. If we can confirm that the Intercom source is not performing in this way, then it would be a bug on the connector and we would try to prioritize for resolution in the coming cycle. (Unfortunately, I've done a rough scope and this could be a week or two engineering time to resolve. It is not a quick fix and likely we'd want to first confirm the root cause and then move to prioritize a refactor once confirmed.)
> 
> ## Short-term Mitigation
> If the above is the root cause (and even if not), a remediation step in this case would be to run a full sync on the child stream (`conversation_parts`) with the goal to re-sync any conversations who were skipped in the recurring incremental syncs.
> 
> * This mitigation doesn't solve the root cause, or prevent in the future. It would however, recover any missing records from past syncs.
> * It also doesn't solve what appear to be faulty or inconsistent logics in the intercom API's statistics counts.
> * It likewise wouldn't solve for the 500 part limit that @everron calls out.
> 
> @everron, @bgdanterty - would you be interested in attempting this mitigation and reporting back?

Thanks, @aaronsteers, for bringing this up! It seems likely that there may be an issue with the cursor logic. After doing a full refresh on a separate dataset, we noticed that entire conversations were missing. If it helps with your debugging, the first period when we encountered a spike in missing data was around mid-July, but this could also be related to increased traffic in the tool at the time.

### Root Cause Validation:
Is there anything we can do to help validate the root cause (perhaps through logs)?

### Short-Term Mitigation:

1. We tried the full sync, and while it worked perfectly, as you mentioned, it's not a permanent fix since it could happen again.
2. As time goes on, the full sync will take longer and longer to complete—it took four days in our case.
3. The 500 parts limit and the known discrepancy on Intercom's side for statistics counts are not issues for us.

### Question:
Once the root cause is validated, what would be the ETA for a fix and deployment?

**Comment by geo909** [comment] 2024-09-18 11:14
@aaronsteers Thank you too for looking into this.

Just wanted to add to what my coworker @Alexandros-Gk mentioned, after talking to intercom, in case it is of any help:

* We never reached an api limit; all responses they see from July onwards have been 200s
* I asked them if there is any chance that there is latency in the update of their data (which could potentially also explain the cursor moving on and missing old data) but they said (and I quote) that "updates via the API any should be reflected pretty much straight away for all types of data, such as Conversations".

Not sure if it helps but just in case.

**Comment by everron** [comment] 2024-10-11 08:25
Hello @aaronsteers Do you have an update on this ? 

The full sync was tried on a staging env and even with sampled data, it took several days and we did not consider it for production data.
We still have 60 to 70% of conversations extracted every day with missing parts.

**Comment by natikgadzhi** [comment] 2024-11-06 17:09
We've shipped a fix for this — please try the most recent connector version and tell us if that worked.

**Closed by natikgadzhi** 2024-11-06 17:09 UTC
Labels: type/bug, area/connectors, community, connectors/source/intercom, team/connectors-python, missing-data

**Comment by juoll-data** [comment] 2025-01-29 16:00
Can you please indicate since which version of the connector the issue has been solved ?

**Comment by natikgadzhi** [comment] 2025-02-12 20:02
Try 0.12.1, it just rolled on Feb 8th — latest is always the most straightforward.
