### ISSUE TITLE
TIMESTAMPS shown as null in schemas from Salesforce

### ISSUE THREAD

**Issue by shmf** [airbytehq/airbyte#4396] opened 2021-06-29 08:23 UTC
## Expected Behavior
Schema for tables retrieved from Salesforces should show TIMESTAMPS

## Current Behavior
Schema for tables retrieved from Salesforces show NULL
<img width="763" alt="Screenshot 2021-06-28 at 19 15 32" src="https://user-images.githubusercontent.com/84322199/123761661-f1ab0b00-d8b9-11eb-9b69-b80190e022fd.png">

## Logs
n/a

## Steps to Reproduce
1. create a connection between SFDC (source) and CSV (target - any should work)
2. retrieve the source schemas
3. check data type for TIMESTAMP fields

## Severity of the bug for you
Medium

## Airbyte Version
0.26.2

## Connector Version (if applicable)
0.2.3

## Additional context
Local deployment on GCP Compute Engine.
It is quite a big problem when the target is parquet because the schema shows a NULL datatype leading to a failure.

**Comment by marcosmarxm** [comment] 2021-06-29 13:50
When using Postgres as destination fields are transferred as STRING but when using Parquet format is breaking the sync.
@tuliren for your information

**Comment by sherifnada** [comment] 2021-07-07 19:00
@shmf could you upload the log file for this sync job?

**Comment by tuliren** [comment] 2021-07-07 19:26
The root cause is probably #4294.

**Comment by tuliren** [comment] 2021-07-07 22:46
@shmf, would you mind trying the latest version of the S3 connector `0.1.8`? This problem is probably solved in that version. If not, the log file should help us further debug it. Specially it would be helpful to know what the schema is for `ACH_Submit_Timestamp__c`. Thank you~~

**Comment by tuliren** [comment] 2021-07-13 17:55
Should have been resolved by #4613.

**Closed by tuliren** 2021-07-13 17:55 UTC
Labels: area/connectors, community_request, type/bug
