### ISSUE TITLE
Document all lowcode components in the YAML definition file

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#22129] opened 2023-01-31 05:36 UTC
### Tell us about the documentation you'd like us to add or update.
As described in the [strategy for documenting the lowcode framework](https://docs.google.com/document/d/1iWjJu-ZwK5wHcOxJZUO2kMUhh-5gbNKN3ju7PexpEqY/edit#heading=h.s855p94qmsou), we want to make the `declarative_components.yaml` file the source of truth for how our components behave. 

While we are still refactoring some components, the refactors are most likely going to be small, so i think we can go ahead on this workstream without blocking too much. Look for guidance from the "lowcode to beta" project team on which components to skip for now (even for components getting refactored, we might not need to skip anything at all, since presumably the descriptions would still mostly apply). 

As an implementation hint, we've generally done a pretty good job documenting how components behave in their implementation files such as [this one](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/declarative/requesters/paginators/strategies/offset_increment.py#L18) or [this one](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/declarative/requesters/paginators/default_paginator.py#L24). So we can probably copy-pasta a lot of these. 

As another implementation hint, this ticket can likely be heavily parallelized and is probably a good candidate for pairing. 

## Acceptance Criteria
1. All components are documented in the [`declarative_component_schema.yaml`](https://github.com/airbytehq/airbyte/blob/master/airbyte-cdk/python/airbyte_cdk/sources/declarative/declarative_component_schema.yaml) file with `description`, `examples`, `summary`, and `title` fields (all those fields are described [here](https://docs.google.com/document/d/1iWjJu-ZwK5wHcOxJZUO2kMUhh-5gbNKN3ju7PexpEqY/edit#heading=h.s855p94qmsou))

**Comment by sherifnada** [comment] 2023-01-31 18:37
grooming notes: 
- it will likely require some adaptation of existing docstrings
- do we want to update this for 
- **Fields** should have a `description`, `examples`, `summary`, and `title`
- **Components** (e.g: paginator) should have `description` and `title` only? 
- Concerns & Risks
  - what is the exact format that the UI accepts? e.g: how is formatting in the UI handled, how do I specify a line-break?
  - Overall, it's not clear that whatever we output here will exactly match the interface that consumers expect. So we need to ratify that first before we do this ticket. 

Blocking this ticket on solving the pieces in the concerns & risks section.

**Comment by sherifnada** [comment] 2023-01-31 18:40
@sherifnada will clarify the concerns & risks section and bring this issue back

**Comment by sherifnada** [comment] 2023-02-01 16:08
From design session: 
* all **components** should have a `description` field that describes how the component works but doesn't talk about its individual fields (those fields will have their own `description`s)
* all **components** should have a field `docs_url` which points to a docs page that the UI can use in a "Learn More" clickable text

**Comment by girarda** [comment] 2023-03-15 00:04
closing as duplicate of https://github.com/airbytehq/airbyte/issues/23837

**Closed by girarda** 2023-03-15 00:04 UTC
Labels: area/documentation, type/enhancement, team/extensibility
