### ISSUE TITLE
SFTP File Source - Excel File import Error

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#13933] opened 2022-06-20 11:58 UTC
Is this your first time deploying Airbyte?: No
OS Version / Instance: Ubuntu Server 20.04 (64-bit)
Memory / Disk: 8Gb
Deployment: Docker
Airbyte Version: 0.35.65-alpha
Source name/version: File (excel) SFTP
Destination name/version: Postgres
Step: The issue is happening during “Set up the connection” (after I click add destination button)
Error: Failed to fetch schema. Please try again

```
{“message”:“Internal Server Error: Cannot invoke “io.airbyte.protocol.models.AirbyteCatalog.equals(Object)” because the return value of “java.util.Map$Entry.getValue()” is null”,“exceptionClassName”:“java.lang.NullPointerException”,“exceptionStack”:[“java.lang.NullPointerException: Cannot invoke “io.airbyte.protocol.models.AirbyteCatalog.equals(Object)” because the return value of “java.util.Map$Entry.getValue()” is null”,"\tat io.airbyte.config.persistence.ConfigRepository.getOrInsertActorCatalog(ConfigRepository.java:831)","\tat io.airbyte.config.persistence.ConfigRepository.lambda$writeActorCatalogFetchEvent$22(ConfigRepository.java:891)","\tat io.airbyte.db.Database.lambda$transaction$0(Database.java:31)","\tat org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:564)","\tat org.jooq.impl.Tools$12$1.block(Tools.java:4926)","\tat java.base/java.util.concurrent.ForkJoinPool.unmanagedBlock(ForkJoinPool.java:3463)","\tat java.base/java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3434)","\tat org.jooq.impl.Tools$12.get(Tools.java:4923)","\tat org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:616)","\tat org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:533)","\tat io.airbyte.db.Database.transaction(Database.java:31)","\tat io.airbyte.db.ExceptionWrappingDatabase.transaction(ExceptionWrappingDatabase.java:31)","\tat io.airbyte.config.persistence.ConfigRepository.writeActorCatalogFetchEvent(ConfigRepository.java:890)","\tat io.airbyte.server.handlers.SchedulerHandler.discoverSchemaForSourceFromSourceId(SchedulerHandler.java:269)","\tat io.airbyte.server.apis.ConfigurationApi.lambda$discoverSchemaForSource$36(ConfigurationApi.java:498)","\tat io.airbyte.server.apis.ConfigurationApi.execute(ConfigurationApi.java:871)","\tat io.airbyte.server.apis.ConfigurationApi.discoverSchemaForSource(ConfigurationApi.java:498)","\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)","\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)","\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)","\tat java.base/java.lang.reflect.Method.invoke(Method.java:568)","\tat org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52)","\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124)","\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167)","\tat org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)","\tat org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)","\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)","\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)","\tat org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)","\tat org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)","\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)","\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)","\tat org.glassfish.jersey.internal.Errors.process(Errors.java:292)","\tat org.glassfish.jersey.internal.Errors.process(Errors.java:274)","\tat org.glassfish.jersey.internal.Errors.process(Errors.java:244)","\tat org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)","\tat org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)","\tat org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)","\tat org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)","\tat org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)","\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)","\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)","\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)","\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763)","\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569)","\tat org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)","\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377)","\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)","\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507)","\tat org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)","\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292)","\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)","\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)","\tat org.eclipse.jetty.server.Server.handle(Server.java:501)","\tat org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)","\tat org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)","\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)","\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)","\tat org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)","\tat org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)","\tat org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)","\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)","\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)","\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)","\tat org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)","\tat org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375)","\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)","\tat org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)","\tat java.base/java.lang.Thread.run(Thread.java:833)"],“rootCauseExceptionClassName”:null,“rootCauseExceptionStack”:}
```

**Comment by midavadim** [comment] 2022-08-04 20:24
I was not able to reproduce this error.

I have tried different ways to sync to excel files: empty and with data
source: localfile, sftp 
destination: json, postgres

@harshithmullapudi I suppose the problem is somewhere in excel file itself.
Question1: is it possible to provide us with an example of such excel file?
Question2: do you see this error if choose another destination, like local json?

**Comment by davydov-d** [comment] 2022-08-22 08:58
@harshithmullapudi could you please verify whether you experience this error after upgrading Airbyte to latest version?

**Comment by midavadim** [comment] 2022-08-25 16:16
I close this issue since we were not able to reproduce this error.

Besides that, there is a chance that https://github.com/airbytehq/airbyte/pull/15501 could fix such problem.

**Closed by midavadim** 2022-08-25 16:16 UTC
Labels: type/bug, team/connectors-python
