### ISSUE TITLE
Performance - logging improvements

### ISSUE THREAD

**Issue by colesnodgrass** [airbytehq/airbyte#21496] opened 2023-01-17 20:49 UTC
During the performance analysis work it was discovered that our logging implementation can block whenever it uploads the logs. This ticket is to determine if an async logger would be a better choice, especially when uploading the logs to a provider.

**Comment by davinchia** [comment] 2023-04-07 00:03
@colesnodgrass did we decide how to proceed with this?

**Comment by colesnodgrass** [comment] 2023-04-07 00:06
@davinchia With the loss of location information (file, class, line) when moving to async-logging, this was put on hold. As, after discussions with the team, location information was deemed too important.

**Comment by davinchia** [comment] 2023-04-07 00:09
ok! Have we confirmed this is a Log4J2 characteristic? i.e. this is not because of the current way we've tried to do this, and is because the logger itself doesn't support it. I remember we weren't clear on this when we last spoke.

**Comment by davinchia** [comment] 2023-05-30 20:57
@colesnodgrass since we aren't going to do this, should we close this for now?

**Comment by davinchia** [comment] 2023-06-08 16:10
Closing this as part of issue clean up.

**Closed by davinchia** 2023-06-08 16:10 UTC
Labels: team/platform-move
