### ISSUE TITLE
[source-stripe] Make subscription_items & invoice_line_items able to use Incremental sync mode

### ISSUE THREAD

**Issue by tomsseisums** [airbytehq/airbyte#48426] opened 2024-11-08 10:34 UTC
### Connector Name

source-stripe

### Connector Version

5.6.2

### What step the error happened?

During the sync

### Relevant information

We have subscriptions for our app, but even if we only get a couple of new subscriptions every day, whenever Airbyte runs, it has to load every single `Invoice Line Item` and `Subscription Item`, making the sync rather ineffective, especially when using Airbyte Cloud.

For instance, we have a total 24k Invoice Line Items in DB, but even if we get 13 new invoices in our hourly AirByte sync, every hour all of them are being refreshed.
![for 13 invoices, 24k invoice lines are loaded](https://github.com/user-attachments/assets/acae0db3-4120-4ea6-be1a-6664a2fac544)

Same for `Subscription Items`, having loaded just 5 new subscriptions, we still had to refresh all 7.5k items.
![for 5 subscriptions, 7.5k subscription items are loaded](https://github.com/user-attachments/assets/df417ad1-ec90-4287-99f8-83065ca3be36)

---

As can be seen, there is not even an option to use `Incremental` modes here.
![Image](https://github.com/user-attachments/assets/8717395f-822d-421d-b323-3dfe61797cd6)
![Image](https://github.com/user-attachments/assets/3e524d37-14f4-44da-8bca-4d0d1919966e)

---

I'd be open to implement the change myself, but I'd need some pointers.

### Contribute

- [x] Yes, I want to contribute

**Comment by marcosmarxm** [comment] 2024-11-14 16:08
Duplicate of https://github.com/airbytehq/airbyte/issues/30073 
@tomsseisums this is a WIP https://github.com/airbytehq/airbyte/pull/45860 I'm going try to speed up the review process asap.

**Closed by marcosmarxm** 2024-11-14 16:08 UTC
Labels: type/bug, area/connectors, community, connectors/source/stripe, team/connectors-python
