### ISSUE TITLE
Use gradle in OSS repo correctly to cache artifacts between tests

### ISSUE THREAD

**Issue by Mykyta-Serbynevskyi** [airbytehq/airbyte#19784] opened 2022-11-24 11:06 UTC
At the moment `Docker image build` gradle task is registered in `./build.gradle` in [OSS]( https://github.com/airbytehq/airbyte/blob/master/build.gradle#L244) repo which means that this task now takes part in gradle task caching. 
However, OSS project definitely still has some tasks defined that are not really Gradle tasks.

ToDo:
- [ ] It may be worth doing an audit of all `build.gradle` files just to ensure that any custom tasks are being created/registered correctly.

Cloud repo task - https://github.com/airbytehq/airbyte-cloud/issues/3578
In case you need more context, @jdpgrailsdev is PoC

**Comment by davinchia** [comment] 2023-04-06 23:33
duplicate of https://github.com/airbytehq/airbyte-platform-internal/issues/4947

**Closed by davinchia** 2023-04-06 23:33 UTC
Labels: type/enhancement, area/platform, team/platform-move, platform-move/requires-grooming
