### ISSUE TITLE
🐛 Destination MSSQL: Incremental normalization bug

### ISSUE THREAD

**Issue by rmmhd** [airbytehq/airbyte#8806] opened 2021-12-15 08:56 UTC
## Environment
- **Airbyte version**:  example is 0.33.5-alpha
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker 
- **Source Connector and version**: Oracle 0.3.9 
- **Destination Connector and version**: MS SQL Server 0.1.12
- **Severity**: High
- **Step where error happened**: On second sync with basic normalization.

## Current Behavior
*I created a Connection between Oracle and MSSQL. The first sync with basic normalization on succeeds. The second attempt fails and thorws an error. With basic normalization turned off, all these steps work fine.*

## Expected Behavior
*The basic normalization should run on every sync.*

## Logs
[logs-25-2.txt](https://github.com/airbytehq/airbyte/files/7717738/logs-25-2.txt)

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. Create Oracle as source and MSSQL server as destionation
2. Create a connection between them and start the first sync
3. Start a second manual sync and it will fail 3 times since its trying to do the task 3 times

## Are you willing to submit a PR?

No.

**Comment by alafanechere** [comment] 2021-12-16 08:40
The root cause of this error is the following according to logs:
```
Compilation Error in model hd_reptest (models/generated/airbyte_incremental/testdb/hd_reptest.sql)
When searching for a relation, dbt found an approximate match. Instead of guessing 
which relation to use, dbt will move on. Please delete "testdb2"."testdb"."hd_reptest", or rename it to be less ambiguous.
Searched for: "testdb2"."testdb"."hd_reptest"
Found: "testdb2"."testdb"."hd_reptest"
``` 
Looks like the incremental model creation is tried on the second sync even if it was previously created in the first sync.

**Comment by ChristopheDuong** [comment] 2021-12-16 09:25
Could you attach the dbt.log file to get more details on why dbt is failing please?

```
docker cp airbyte-server:/tmp/workspace/25/2/logs/dbt.log .
cat dbt.log
```

**Comment by rmmhacidoelek** [comment] 2021-12-16 11:36
Here is the dbt.log file:
[dbt.log](https://github.com/airbytehq/airbyte/files/7726929/dbt.log)

**Comment by alafanechere** [comment] 2021-12-21 17:45
Hi @rmmhacidoelek could you please list all your tables and views and check if you have a duplicate for the `hd_reptest`?

We think the error might be related to [DBT's SQL server adapter](https://github.com/dbt-msft/dbt-sqlserver) I started a discussion here on their slack to check if they could have insights about what's going on here.

**Comment by rmmhacidoelek** [comment] 2021-12-22 09:24
Hi @alafanechere, I checked all my tables and views and there is no duplicate with this name. The database is new, so there are just a few tables.

**Comment by victorolawale** [comment] 2022-01-05 10:10
I am having same issue. MSSQL is the destination while hubspot is the source. The first sync was fine (tables created with data). However, subsequent sync was throwing the errors after trying for 3 times. Please refer to the logs and screenshot below.

[logs-101-2.txt](https://github.com/airbytehq/airbyte/files/7814048/logs-101-2.txt)
[logs-101-1.txt](https://github.com/airbytehq/airbyte/files/7814050/logs-101-1.txt)
[logs-101-0.txt](https://github.com/airbytehq/airbyte/files/7814051/logs-101-0.txt)
 
![image](https://user-images.githubusercontent.com/1159462/148200062-7af90e67-eb31-4e6d-bf36-6dbf7def4e9f.png)

**Comment by marcosmarxm** [comment] 2022-08-01 13:01
> 

Not yet @yusufollaek

**Comment by marcosmarxm** [comment] 2022-08-01 13:07
Zendesk ticket #[1748](https://airbyte7538.zendesk.com/agent/tickets/1748) has been linked to this issue.

**Comment by marcosmarxm** [comment] 2022-08-01 16:24
*Comment made from Zendesk by Marcos Marx on 2022-08-01 at 16:24:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hello, that would be great if there is a workaround - how to get it to work with the workaround?</p>
<p dir="auto">As described, I set it to ‘Full refresh | Overwrite’, but this leads to failure after initial sync.<br>
Indeed, that is what I want in this case - the table should be completely overwritten.<br>
By the way, it also fails when selecting to ‘Reset your data’.</p>
<p dir="auto">Best Regards</p> 

 [<a href="https://discuss.airbyte.io/t/destination-mssql-doesnt-work-with-incremental-sync-mode/2045/4" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment] 2022-08-01 17:36
*Comment made from Zendesk by Marcos Marx on 2022-08-01 at 17:36:*

<blockquote><div class="zd-comment" dir="auto">Oh I thought the full refresh worked.&nbsp;<br>There are two ways to follow here: disable normalization OR run the first time, export normalization and edit to start working with MSSQL.<br></div></blockquote>

**Comment by marcosmarxm** [comment] 2022-08-01 18:59
*Comment made from Zendesk by Marcos Marx on 2022-08-01 at 18:59:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">many thanks, I will have a look at that!</p> 

 [<a href="https://discuss.airbyte.io/t/destination-mssql-doesnt-work-with-incremental-sync-mode/2045/6" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by mmoole** [comment] 2022-08-09 14:24
after reading this in the log: 
```
When searching for a relation, dbt found an approximate match. Instead of guessing 
which relation to use, dbt will move on. Please delete "AIRBYTE_ELT"."AIRBYTE_ELT"."abelt_devtable_1", or rename it to be less ambiguous.
Searched for: "AIRBYTE_ELT"."airbyte_elt"."abelt_devtable_1"
Found: "AIRBYTE_ELT"."AIRBYTE_ELT"."abelt_devtable_1"
```
and this issue: https://github.com/dbt-msft/dbt-sqlserver/issues/206 
I deleted and re-created the database, but this time with all letters in lower case for database name, and schema name.
And voilà: now it's also working the second and more time to run a sync (Full refresh|Overwrite) 👍🤩

So the issue seems to be that normalization to lowercase letters is handled differently at some stages during all those process steps, and using lower case letters from the start seems to circumvent the possible problems that arise because of that...

**Comment by marcosmarxm** [comment] 2022-08-09 18:49
*Comment made from Zendesk by Marcos Marx on 2022-08-09 at 18:49:*

<blockquote><div class="zd-comment" dir="auto">@mmoole can you check the comment below:<br><blockquote><p dir="auto">I deleted and re-created the database, but this time with all letters in lower case for database name, and schema name.<br>And voilà: now it's also working the second and more time to run a sync (Full refresh|Overwrite) 👍🤩<br>So the issue seems to be that normalization to lowercase letters is handled differently at some stages during all those process steps, and using lower case letters from the start seems to circumvent the possible problems that arise because of that…</p></blockquote><a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/8806#issuecomment-1209451064">https://github.com/airbytehq/airbyte/issues/8806#issuecomment-1209451064</a><br></div></blockquote>

**Comment by mmayr-kienbacher** [comment] 2024-03-11 09:30
I have the same issues by using upper cases for schemas in my destination database: 
![image](https://github.com/airbytehq/airbyte/assets/161821814/e3129e46-f1fb-4f0b-af43-077163d8d817)

So why is ist that prolem, that dbt just work case-sensitive?

**Comment by marcosmarxm** [comment] 2024-03-20 20:49
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.

**Closed by marcosmarxm** 2024-03-20 20:49 UTC
Labels: type/bug, area/connectors, priority/critical, normalization, community, area/databases, connectors/destinations-database, connectors/destination/mssql, autoteam, zendesk, team/destinations
