### ISSUE TITLE
Settings Gear redirects to wrong page

### ISSUE THREAD

**Issue by misteryeo** [airbytehq/airbyte#9670] opened 2022-01-21 00:49 UTC
## Environment
- **Airbyte version**:  Reported by an OSS user but also tried it in Cloud
- **Severity**: High 
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
Clicking on the settings gear icon on the connections page brings me to my workspaces page.

## Expected Behavior
Clicking on the settings gear icon should bring me to the connection settings page.

Screen recording: https://share.getcloudapp.com/GGuEWLBK

**Comment by timroes** [comment] 2022-01-21 08:18
Duplicate of https://github.com/airbytehq/airbyte/issues/9637

**Closed by timroes** 2022-01-21 08:18 UTC
Labels: type/bug, area/frontend, area/platform
