### ISSUE TITLE
Internal Server Error: Duplicate key  (attempted merging values...)

### ISSUE THREAD

**Issue by ajboni** [airbytehq/airbyte#19938] opened 2022-11-30 18:27 UTC
## Environment
- **Airbyte version**:  0.40.22
- **OS Version / Instance**: RHEL 
- **Deployment**:  Docker 
- **Source Connector and version**: Files 0.2.31
- **Destination Connector and version**: Postgres 0.3.26 
- **Step where error happened**: Bug appeared after creating a connection

## Current Behavior
I made a new connection and now im locked in the UI. cannot reach source, destination or connections page anymore.
Destination had already some connections set up

Server Error:
```
2022-11-30 18:14:24 [32mINFO[m i.a.s.RequestLogger(filter):112 - REQ 172.26.0.8 POST 200 /api/v1/source_definitions/list_latest
2022-11-30 18:14:24 [32mINFO[m i.a.s.RequestLogger(filter):112 - REQ 172.26.0.8 POST 200 /api/v1/source_definitions/list_for_workspace - {"workspaceId":"288c5c69-8cfd-4ab7-99e1-71ab3382721c"}
2022-11-30 18:14:24 [32mINFO[m i.a.s.RequestLogger(filter):112 - REQ 172.26.0.8 POST 200 /api/v1/destinations/list - {"workspaceId":"288c5c69-8cfd-4ab7-99e1-71ab3382721c"}
2022-11-30 18:14:24 [1;31mERROR[m i.a.s.e.UncaughtExceptionMapper(toResponse):22 - Uncaught exception
java.lang.IllegalStateException: Duplicate key 9a50e712-1a7f-48ca-80cd-ef7fd1a09961 (attempted merging values io.airbyte.config.ActorCatalogFetchEvent@700573ea[id=<null>,actorId=9a50e712-1a7f-48ca-80cd-ef7fd1a09961,actorCatalogId=f89ae5a9-c2e4-4153-b1e2-a4120f0208d6,configHash=<null>,connectorVersion=<null>,createdAt=1669828573] and io.airbyte.config.ActorCatalogFetchEvent@3a46bb1d[id=<null>,actorId=9a50e712-1a7f-48ca-80cd-ef7fd1a09961,actorCatalogId=c657bc15-ca43-4afa-9794-bb5441e2ceb4,configHash=<null>,connectorVersion=<null>,createdAt=1669828573])
	at java.util.stream.Collectors.duplicateKeyException(Collectors.java:135) ~[?:?]
	at java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182) ~[?:?]
	at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[?:?]
	at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1003) ~[?:?]
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921) ~[?:?]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
	at io.airbyte.config.persistence.ConfigRepository.getMostRecentActorCatalogFetchEventForSources(ConfigRepository.java:1113) ~[io.airbyte.airbyte-config-config-persistence-0.40.22.jar:?]
	at io.airbyte.server.handlers.WebBackendConnectionsHandler.webBackendListConnectionsForWorkspace(WebBackendConnectionsHandler.java:118) ~[io.airbyte-airbyte-server-0.40.22.jar:?]
	at io.airbyte.server.apis.WebBackendApiController.lambda$webBackendListConnectionsForWorkspace$4(WebBackendApiController.java:53) ~[io.airbyte-airbyte-server-0.40.22.jar:?]
	at io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:17) ~[io.airbyte-airbyte-server-0.40.22.jar:?]
	at io.airbyte.server.apis.WebBackendApiController.webBackendListConnectionsForWorkspace(WebBackendApiController.java:53) ~[io.airbyte-airbyte-server-0.40.22.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:124) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:167) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265) ~[jersey-common-2.31.jar:?]
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680) ~[jersey-server-2.31.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205) ~[jersey-container-servlet-core-2.31.jar:?]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:763) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:569) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1377) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:507) ~[jetty-servlet-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1292) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.Server.handle(Server.java:501) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273) ~[jetty-server-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) ~[jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) ~[jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) ~[jetty-io-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336) ~[jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313) ~[jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171) ~[jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129) ~[jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:375) ~[jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806) ~[jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938) ~[jetty-util-9.4.31.v20200723.jar:9.4.31.v20200723]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```
Web error:
```
query.js:356 
        
       Error: Internal Server Error: Duplicate key 9a50e712-1a7f-48ca-80cd-ef7fd1a09961 (attempted merging values io.airbyte.config.ActorCatalogFetchEvent@700573ea[id=<null>,actorId=9a50e712-1a7f-48ca-80cd-ef7fd1a09961,actorCatalogId=f89ae5a9-c2e4-4153-b1e2-a4120f0208d6,configHash=<null>,connectorVersion=<null>,createdAt=1669828573] and io.airbyte.config.ActorCatalogFetchEvent@3a46bb1d[id=<null>,actorId=9a50e712-1a7f-48ca-80cd-ef7fd1a09961,actorCatalogId=c657bc15-ca43-4afa-9794-bb5441e2ceb4,configHash=<null>,connectorVersion=<null>,createdAt=1669828573])
    at apiOverride.ts:107:9
    at d (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at r (asyncToGenerator.js:3:20)
    at u (asyncToGenerator.js:25:9)
```

## Expected Behavior
*Tell us what should happen.*

## Logs
Attached server logs.

## Steps to Reproduce
Not sure on how to reproduce this!!

## Are you willing to submit a PR?
No
[server-logs (3).txt](https://github.com/airbytehq/airbyte/files/10126153/server-logs.3.txt)

Any workaround would help! I'm stuck unfortunately!
Thanks!

**Comment by natalyjazzviolin** [comment] 2022-12-05 12:18
Hi @ajboni , since you don't have steps to reproduce this yet - let's take it to the Slack or the forum. Could you please start a thread in one of those and we'll try and trouble shoot this. Closing for now.

**Closed by natalyjazzviolin** 2022-12-05 12:18 UTC
Labels: type/bug, community, needs-triage, team/use, autoteam

**Comment by ajboni** [comment] 2022-12-05 12:36
Sure, thanks, just fyi  I managed to advance by simply deleting rows directly from tables that linked to those ids (`connection`, `ActorCatalogFetchEvent`, `actor-catalog` iirc). Recreated the connection and could NOT reproduce the issue again.

**Comment by hantmac** [comment] 2022-12-06 06:37
I met the same error.
