### ISSUE TITLE
🐛 Source Sendgrid doesn't display option to upgrade to current version 

### ISSUE THREAD

**Issue by jd-sanders** [airbytehq/airbyte#9624] opened 2022-01-20 00:55 UTC
## Environment
- **Airbyte version**:  0.33.2-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Sendgrid 0.2.7
- **Severity**: Low
- **Step where error happened**: Update connector

## Current Behavior
The latest version of the Sendgrid connector is 0.2.7. (image attached).  The 0.2.7 commector supports a stream that the previous version did not.  However, when looking at the settings page, the newest version is reported as 0.2.6.  It is possible to manually type in 0.2.7 and change to it, but when doing things like upgrading Airbyte, or updating the connectors, it's easy to have it accidentally roll back, which is a pain if you're depending on the new version.
<img width="870" alt="Screen Shot 2022-01-19 at 4 50 40 PM" src="https://user-images.githubusercontent.com/17693612/150242555-9119c0d6-d161-4dc5-a138-148f14c847f2.png">
<img width="1232" alt="Screen Shot 2022-01-19 at 4 50 56 PM" src="https://user-images.githubusercontent.com/17693612/150242564-4625ee56-9f1e-464d-8a0c-15e200e70ed3.png">

## Expected Behavior
The settings page should give you the option to upgrade to the newest release Sendgrid 0.2.7.

## Are you willing to submit a PR?

No

**Comment by marcosmarxm** [comment] 2022-06-14 02:34
@jd-sanders I couldn't reproduce the issue. I'll close the issue. Let us know if it happens again.

**Closed by marcosmarxm** 2022-06-14 02:34 UTC
Labels: type/bug, area/connectors, community, team/use, autoteam
