### ISSUE TITLE
JOB pods don't honor the JOB_MAIN_CONTAINER_CPU_REQUEST config anymore

### ISSUE THREAD

**Issue by ro8inmorgan** [airbytehq/airbyte#31013] opened 2023-10-03 10:07 UTC
### Topic

Job pods

### Revelant information

In the latest version 50.30 Job pods don't follow the JOB_MAIN_CONTAINER_CPU_REQUEST in the airbyte_env configmap anymore. They always request 1 full CPU which makes our kubernetes cluster scale up waaay tooo high.

This is a pretty big problem!

**Comment by ro8inmorgan** [comment] 2023-10-03 10:22
Log file entry:
023-10-03 10:00:28 INFO i.a.w.p.KubeProcessFactory(create):119 - Attempting to start pod = destination-bigquery-write-17739-0-rrjjz for airbyte/destination-bigquery:2.0.19 with resources ConnectorResourceRequirements[main=io.airbyte.config.ResourceRequirements@7e4756c2[cpuRequest=1,cpuLimit=2,memoryRequest=1Gi,memoryLimit=2Gi,additionalProperties={}], heartbeat=io.airbyte.config.ResourceRequirements@1380856c[cpuRequest=0.05,cpuLimit=0.2,memoryRequest=25Mi,memoryLimit=50Mi,additionalProperties={}], stdErr=io.airbyte.config.ResourceRequirements@1ef5e82b[cpuRequest=0.01,cpuLimit=0.5,memoryRequest=25Mi,memoryLimit=50Mi,additionalProperties={}], stdIn=io.airbyte.config.ResourceRequirements@652cb9d1[cpuRequest=0.5,cpuLimit=2,memoryRequest=25Mi,memoryLimit=50Mi,additionalProperties={}], stdOut=io.airbyte.config.ResourceRequirements@45fc56df[cpuRequest=0.01,cpuLimit=0.5,memoryRequest=25Mi,memoryLimit=50Mi,additionalProperties={}]] and allowedHosts nu

**Comment by hawkesn** [comment] 2023-10-03 19:15
Also seeing the same thing, this workaround works though: [Configuring Connection-Specific Requirements](https://docs.airbyte.com/operator-guides/configuring-connector-resources#configuring-connection-specific-requirements)

**Comment by hakuno** [comment] 2023-10-09 13:41
+1

**Comment by cnogradi** [comment] 2023-10-23 21:57
This seems to be reporting the same issue as here: https://github.com/airbytehq/airbyte/issues/30814

**Comment by davinchia** [comment] 2023-10-31 17:21
Indeed. This is a duplicate of #30814 . We are releasing a fix in the next day or so, so please watch that issue. Thanks.

**Closed by davinchia** 2023-10-31 17:21 UTC
Labels: area/platform, community, autoteam, team/use
