### ISSUE TITLE
ERROR: Failed to fetch remote definitions

### ISSUE THREAD

**Issue by bodschut** [airbytehq/airbyte#23716] opened 2023-03-03 08:23 UTC
## Environment
- **Airbyte version**:  0.41.0
- **OS Version / Instance**: Ubuntu 22.04-LTS
- **Deployment**: Azure VM Standard_D2as_v2 using docker compose and external database (azure postgres flexible)
- **Step where error happened**: While using airbyte UI

## Current Behavior
I'm getting random error screens when browsing in the airbyte UI. When checking the server logs I'm always seeing errors related to the `getRemoteDefinitionCatalog` with the message `Failed to fetch remote definitions` which seem to be caused by some timeout. However, I can't seem to figure out what is causing this...

## Logs
```
2023-03-03 07:48:51 ERROR i.a.s.a.ApiHelper(execute):37 - Unexpected Exception
java.lang.RuntimeException: Failed to fetch remote definitions
        at io.airbyte.config.init.RemoteDefinitionsProvider.getRemoteDefinitionCatalog(RemoteDefinitionsProvider.java:122) ~[io.airbyte.airbyte-config-init-0.41.0.jar:?]
        at io.airbyte.config.init.RemoteDefinitionsProvider.getDestinationDefinitionsMap(RemoteDefinitionsProvider.java:73) ~[io.airbyte.airbyte-config-init-0.41.0.jar:?]
        at io.airbyte.config.init.RemoteDefinitionsProvider.getDestinationDefinitions(RemoteDefinitionsProvider.java:105) ~[io.airbyte.airbyte-config-init-0.41.0.jar:?]
        at io.airbyte.commons.server.handlers.WebBackendCheckUpdatesHandler.getDestinationDiffCount(WebBackendCheckUpdatesHandler.java:66) ~[io.airbyte-airbyte-commons-server-0.41.0.jar:?]
        at io.airbyte.commons.server.handlers.WebBackendCheckUpdatesHandler.checkUpdates(WebBackendCheckUpdatesHandler.java:44) ~[io.airbyte-airbyte-commons-server-0.41.0.jar:?]
        at io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:23) ~[io.airbyte-airbyte-server-0.41.0.jar:?]
        at io.airbyte.server.apis.WebBackendApiController.webBackendCheckUpdates(WebBackendApiController.java:65) ~[io.airbyte-airbyte-server-0.41.0.jar:?]
        at io.airbyte.server.apis.$WebBackendApiController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-server-0.41.0.jar:?]
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371) ~[micronaut-inject-3.8.5.jar:3.8.5]
        at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594) ~[micronaut-inject-3.8.5.jar:3.8.5]
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:246) ~[micronaut-router-3.8.5.jar:3.8.5]
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111) ~[micronaut-router-3.8.5.jar:3.8.5]
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103) ~[micronaut-http-3.8.5.jar:3.8.5]
        at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659) ~[micronaut-http-server-3.8.5.jar:3.8.5]
        at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49) ~[reactor-core-3.5.0.jar:3.5.0]
        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.5.0.jar:3.5.0]
        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.5.0.jar:3.5.0]
        at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62) ~[micronaut-runtime-3.8.5.jar:3.8.5]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.0.jar:3.5.0]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.0.jar:3.5.0]
        at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53) ~[micronaut-context-3.8.5.jar:3.8.5]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.net.http.HttpTimeoutException: request timed out
        at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:844) ~[java.net.http:?]
        at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123) ~[java.net.http:?]
        at io.airbyte.config.init.RemoteDefinitionsProvider.getRemoteDefinitionCatalog(RemoteDefinitionsProvider.java:113) ~[io.airbyte.airbyte-config-init-0.41.0.jar:?]
        ... 24 more
2023-03-03 07:48:51 ERROR i.a.s.e.UncaughtExceptionHandler(handle):28 - Uncaught exception
java.lang.RuntimeException: Failed to fetch remote definitions
        at io.airbyte.config.init.RemoteDefinitionsProvider.getRemoteDefinitionCatalog(RemoteDefinitionsProvider.java:122) ~[io.airbyte.airbyte-config-init-0.41.0.jar:?]
        at io.airbyte.config.init.RemoteDefinitionsProvider.getDestinationDefinitionsMap(RemoteDefinitionsProvider.java:73) ~[io.airbyte.airbyte-config-init-0.41.0.jar:?]
        at io.airbyte.config.init.RemoteDefinitionsProvider.getDestinationDefinitions(RemoteDefinitionsProvider.java:105) ~[io.airbyte.airbyte-config-init-0.41.0.jar:?]
        at io.airbyte.commons.server.handlers.WebBackendCheckUpdatesHandler.getDestinationDiffCount(WebBackendCheckUpdatesHandler.java:66) ~[io.airbyte-airbyte-commons-server-0.41.0.jar:?]
        at io.airbyte.commons.server.handlers.WebBackendCheckUpdatesHandler.checkUpdates(WebBackendCheckUpdatesHandler.java:44) ~[io.airbyte-airbyte-commons-server-0.41.0.jar:?]
        at io.airbyte.server.apis.ApiHelper.execute(ApiHelper.java:23) ~[io.airbyte-airbyte-server-0.41.0.jar:?]
        at io.airbyte.server.apis.WebBackendApiController.webBackendCheckUpdates(WebBackendApiController.java:65) ~[io.airbyte-airbyte-server-0.41.0.jar:?]
        at io.airbyte.server.apis.$WebBackendApiController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-server-0.41.0.jar:?]
        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371) ~[micronaut-inject-3.8.5.jar:3.8.5]
        at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594) ~[micronaut-inject-3.8.5.jar:3.8.5]
        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:246) ~[micronaut-router-3.8.5.jar:3.8.5]
        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111) ~[micronaut-router-3.8.5.jar:3.8.5]
        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103) ~[micronaut-http-3.8.5.jar:3.8.5]
        at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659) ~[micronaut-http-server-3.8.5.jar:3.8.5]
        at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49) ~[reactor-core-3.5.0.jar:3.5.0]
        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.5.0.jar:3.5.0]
        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.5.0.jar:3.5.0]
        at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62) ~[micronaut-runtime-3.8.5.jar:3.8.5]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.0.jar:3.5.0]
        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.0.jar:3.5.0]
        at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53) ~[micronaut-context-3.8.5.jar:3.8.5]
        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.net.http.HttpTimeoutException: request timed out
        at jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:844) ~[java.net.http:?]
        at jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:123) ~[java.net.http:?]
        at io.airbyte.config.init.RemoteDefinitionsProvider.getRemoteDefinitionCatalog(RemoteDefinitionsProvider.java:113) ~[io.airbyte.airbyte-config-init-0.41.0.jar:?]
        ... 24 more
```

**Comment by danieldybsland** [comment] 2023-03-04 11:24
Same here, but it was started by a 401 (Unauthorized) although I am logged in with default credentials.

The installation is identical to the one described in the issue.

![image](https://user-images.githubusercontent.com/72882629/222897192-504ba901-078f-4aab-9f92-074e4c92dbe4.png)

**Comment by ftong2020** [comment] 2023-03-06 04:37
I had exactly the same issue. Our airbyte cluster works in an air-gapped environment and I can not access configuration page ever since upgraded to v0.41.0. The RemoteDefinitionsProvider will always timeout.

**Comment by bodschut** [comment] 2023-03-06 11:49
Is someone from the airbyte team aware of this issue? :-) Would it be a bug in airbyte or is it linked to our setups?

**Comment by danieldybsland** [comment] 2023-03-06 12:26
It seems to be working on and off a bit. Now I can retrieve a list of connectors/destinations and so on.

I also received an alert from Azure, regarding Azure Monitor Alert VM Availiablity which has been resolved, but not sure is related:
---
Fired:Sev3 Azure Monitor Alert VM Availability - airbyte-vm on airbyte-vm ( microsoft.compute/virtualmachines ) at 3/4/2023 6:57:08 AM

**Comment by ealexisaraujo** [comment] 2023-03-06 12:53
🔥We fixed this issue, I'm going to explain our workaround:

1. After upgrading some sources in the UI, we noticed this issue is starting to be present.
<img width="190" alt="Screenshot 2023-03-06 at 6 45 13 a m" src="https://user-images.githubusercontent.com/9372769/223113983-42e2146d-b801-463a-b93e-ca7acc09e85c.png">
2.- So I ran some queries to check and downgrade these sources manually, the table where you can find these definitions is **actor_definition**, this table contains all the definitions, after that I updated some records, the records o the sources that were upgraded :

``` sql
select * FROM actor_definition
where updated_at::date >= '2023-03-03';
```

The fields that I updated were:

docker_image_tag

This one of example I applied this fixed of every source:

``` sql
update actor_definition
set docker_image_tag = '2.0.4'
from actor_definition
    where name = 'Salesforce'
```

After that the behavior of the UI was good.

**Comment by stoensin** [comment] 2023-03-07 06:02
hi , Airbyte version: 0.41.0
a fresh installation by docker-compose reproduce this bug again.

**Comment by danieldybsland** [comment] 2023-03-13 11:23
It seems to be working fine until I upgrade (all) the connectors.

Not sure what to expect from a free version of software, but the conclusion is that I cannot use it in production right now.

**Comment by vrfn** [comment] 2023-03-14 16:17
My team is running into this issue on a fresh installation as well. When we deploy Airbyte using the most recent Helm chart version, we are completely unable to use the (web) UI.

**Comment by bodschut** [comment] 2023-03-15 07:15
For me, it seems to be fixed after an upgrade to 0.42.0. Although, some pages still take a very long time to load in the UI, e.g. the settings page or the page to create a new source or connection. So I guess maybe the timeout is resolved but some backend calls are still taking a long time.

I have one example here. For loading the settings page, the call to `/api/v1/web_backend/check_updates` took more than 1 minute to complete. detailed timing below:

<img width="576" alt="image" src="https://user-images.githubusercontent.com/1922169/225234170-463074b2-e616-4238-909d-1e541848657a.png">

**Comment by justadevopsguy** [comment] 2023-03-15 09:03
Same in our case - tried the latest helm chart ([0.45.0](https://artifacthub.io/packages/helm/airbyte/airbyte)) but encounter this error even with fresh installation, no connectors installed or configured

**Comment by don-code** [comment] 2023-04-25 04:09
I'm also running Airbyte in an environment without Internet access, and deploying it to Kubernetes with Helm.

On a fresh install of chart 0.45.12, after a few seconds/minutes, the UI will display an "Oops, something went wrong", and dev tools show that a timed out request to `/api/v1/web_backend/check_updates` is the culprit.

I attached `tcpdump` to the server container, and determined that it's attempting to reach out to `connectors.airbyte.com`. Making this resolve to localhost via `/etc/hosts` was enough to make the endpoint stop timing out - it now returns a response saying that there are no updates:

```json
{"destinationDefinitions":0,"sourceDefinitions":0}
```

Since [hostAliases](https://kubernetes.io/docs/tasks/network/customize-hosts-file-for-pods/) aren't supported in the Airbyte Helm chart, there isn't a straightforward way to hot-patch `/etc/hosts` at runtime.

As a workaround, I created a ConfigMap that specified both the response above, and a patched nginx config (forked from the [original](https://github.com/airbytehq/airbyte-platform/blob/93e82a526d066c64d9c4f3ec16a0efa3612d52b7/airbyte-webapp/nginx/default.conf.template)) that would point at it:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-config
data:
  check_updates: |-
    {"destinationDefinitions":0,"sourceDefinitions":0}
  default.conf.template: |-
    # This was derived from the upstream file in airbyte-webapp:
    # https://github.com/airbytehq/airbyte-platform/blob/93e82a526d066c64d9c4f3ec16a0efa3612d52b7/airbyte-webapp/nginx/default.conf.template
    upstream api-server {
        server $INTERNAL_API_HOST;
    }

    upstream connector-builder-server {
       server $CONNECTOR_BUILDER_API_HOST;
    }

    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        add_header Content-Security-Policy "script-src * 'unsafe-inline'; worker-src self blob:;";

        location = /api/v1/web_backend/check_updates {
          # Browser makes a POST - make it behave like a GET.
          # https://gist.github.com/baskaran-md/e46cc25ccfac83f153bb
          error_page 405 =200 $uri;
          alias /usr/share/nginx/html/check_updates;
        }

        location / {
            root   /usr/share/nginx/html;
            location ~ ^/(?!(assets/.*)) {
                try_files $uri $uri/ /index.html;
            }

            # (Developer Note): Please only add new properties to this, if they really need to be configurable
            #                   by a user at runtime i.e. without rebuilding the docker images. General webapp config
            #                   belongs in an environment file.
            sub_filter </head>
                    '<script data-script="config-overwrites">
                    window.TRACKING_STRATEGY = "$TRACKING_STRATEGY";
                    window.AIRBYTE_VERSION = "$AIRBYTE_VERSION";
                    window.API_URL = "$API_URL";
                    window.CONNECTOR_BUILDER_API_URL = "$CONNECTOR_BUILDER_API_URL";
                    </script></head>';
            sub_filter_once on;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

        location /api/ {
            fastcgi_read_timeout 1h;
            proxy_read_timeout 1h;
            client_max_body_size 200M;
            proxy_pass http://api-server/api/;
        }

        location /connector-builder-api/ {
            fastcgi_read_timeout 1h;
            proxy_read_timeout 1h;
            client_max_body_size 200M;
            proxy_pass http://connector-builder-server/;
        }
    }
```

I then mounted that ConfigMap into the webapp deployment via Helm's values.yaml:
```yaml
webapp:
  extraVolumes:
    - name: custom-config
      configMap:
        name: custom-config
  extraVolumeMounts:
    - name: custom-config
      mountPath: /etc/nginx/templates/default.conf.template
      subPath: default.conf.template
    - name: custom-config
      mountPath: /usr/share/nginx/html/check_updates
      subPath: check_updates
```

The result is that `check_updates` never hits the server deployment, and always returns a "valid" response back to the UI.

**Comment by i-yordanova** [comment] 2023-05-04 09:52
seeing the same issue on 0.42.0 and it's quite annoyingly popping up on all pages - sources/destinations/new connection creation or when going to the settings. It results in that `Oops, something went wrong` page which looks like something critical has failed.
It happens both on new installation or after updates and it happens quite often.

I don't think failing to pull the latest should fail the whole app - so maybe just show a warning that what you see might not be the latest (on the update page) on any other page the user probably won't care and what's in the DB should suffice.

Alternatively, pull those way less often - only on the updates page. 

Also, digging through the code noticed that there is a way to set `REMOTE_CONNECTOR_CATALOG_URL` which is used by the UpdateDefinitionHandler but at the same time the AirbyteRemoteOssCatalog has the URL hardcoded - that's because I was considering mirroring the catalog and updating that only occasionally so we can serve it with higher availability but the url used for that is hardcoded AirbyteCatalogConstants.REMOTE_OSS_CATALOG_URL.

**Comment by jkleinkauff** [comment] 2023-05-17 13:25
Same error here. +1 Version: 0.41.0

**Comment by pmossman** [comment] 2023-05-24 18:59
Hey all, this issue should be addressed by https://github.com/airbytehq/airbyte-platform/commit/cc662b2053140183510a5f33a249ac77e1441788 which was included in https://github.com/airbytehq/airbyte-platform/releases/tag/v0.44.5

Our next helm chart publication will reference that new Airbyte version, so hang tight and we'll get that out ASAP!

**Comment by pmossman** [comment] 2023-05-24 21:22
@don-code and others facing this issue, helm chart 0.45.22 was just published and includes the fix I linked in my previous comment. If you're able to try it out and confirm that the issue is indeed resolved, I'll close this issue. I want to leave it open for now in case that fix isn't enough, so let me know how it goes!

**Closed** 2023-06-26 14:32 UTC
Labels: type/bug, area/platform, community, needs-triage, team/use, autoteam

**Comment by nscheifler** [comment] 2023-09-13 21:10
Dropping in to say I was having this exact issue and upgrading to the latest version (airbyte 0.50.29, helm 0.48.10) fixed it 👍
