### ISSUE TITLE
Snowflake active warehouse not selected

### ISSUE THREAD

**Issue by mukulg-df** [airbytehq/airbyte#9633] opened 2022-01-20 04:50 UTC
## Environment
- **Airbyte version**:  0.35.2-alpha
- **OS Version / Instance**: AWS EC2
- **Deployment**: Docker
- **Source Connector and version**: Mailchimp 0.2.10 
- **Destination Connector and version**: Snowflake 0.3.24 
- **Severity**: Vritical
- **Step where error happened**: Sync job

## Current Behavior
Initial sync failed with 3 retries.

## Expected Behavior
Sync should succeed
## Logs
[logs-1-2.txt](https://github.com/airbytehq/airbyte/files/7902363/logs-1-2.txt)

<details>
<summary>LOG</summary> 

```

2022-01-12 16:28:41 [43mdestination[0m > 2022-01-12 16:28:41 [32mINFO[m i.a.i.d.s.SnowflakeInternalStagingConsumerFactory(lambda$onCloseFunction$3):170 - Finalizing stream mailchimp_eml_3001campaigns. schema AIRBYTE_SCHEMA, tmp table _airbyte_tmp_aby_mailchimp_eml_3001campaigns, final table _airbyte_raw_mailchimp_eml_3001campaigns
2022-01-12 16:28:42 [43mdestination[0m > Exception in thread "main" net.snowflake.client.jdbc.SnowflakeSQLException: No active warehouse selected in the current session.  Select an active warehouse with the 'use warehouse' command.

```

</details>

## Steps to Reproduce
1. Configure destination Snowflake
2. Configure source Mailchimp
3. Create connection between source and destination.

## Are you willing to submit a PR?
No

**Comment by etsybaev** [comment] 2022-02-03 16:52
Hi @mukulg-df.

Many thanks for didn't pass by and letting us know about the issue!

At the fist logs-check I see 2 issues:
1. "No active warehouse". This may occurs in snowflake if no warehouse set in jdbc connections string and no default and active warehouse set for user. But we pass this argument in connection string. Another reason may be if "Suspended" warehouse is set. Could you please make sure that it's still On?
![Selection_005](https://user-images.githubusercontent.com/4688354/152387617-b6ca6947-eeac-4b68-8bc2-449cdd37aff7.png)
2.  I see that there is also issue related to schema validation. This may be caused as you'd used pretty only snowflake connector's version (0.3.24) or something went wrong if you'd updated existing connection from earlier connector's version.. Could you please try to completely remove existing snowflake connection, go to settings and update it to the latest one (0.4.7 or later, depends on when will you try it) and then re-create a snowflake destination connection from scratch? 

Looking forward for your update.

Cheers,
Eugene

**Comment by etsybaev** [comment] 2022-02-11 13:13
Was not able to reproduce. Closing it for a while. Please feel free to re-open if that's still the case.

**Closed by etsybaev** 2022-02-11 13:13 UTC
Labels: type/bug, area/connectors, community, connectors/destinations-database, connectors/destination/snowflake

**Comment by hongbo-miao** [comment] 2024-07-01 09:24
Thank you so much @etsybaev for the tips, and I finally made it.
I posted all things that need to pay attention here https://github.com/airbytehq/airbyte/issues/40615#issuecomment-2199653132
Hope it save some time for future people! ☺️
