### ISSUE TITLE
fix Google Adwords CI  & publish new version

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2929] opened 2021-04-17 17:46 UTC
## Description
The Google Adwords CI is [failing](https://status-api.airbyte.io/tests/summary/source-google-adwords-singer/). I'm pretty sure nothing is wrong with the connector but it seems like we may have no data in the underlying source. 

Once this has been fixed, we should bump & publish a new version to pick up the changes from https://github.com/airbytehq/airbyte/pull/2918

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368101988801) by [Unito](https://www.unito.io)

**Comment by Zirochkaa** [comment] 2021-05-03 14:01
I tried to do a little research and find out when tests started to fail. I went on [`integration-test`](https://github.com/airbytehq/airbyte/actions/workflows/test-command.yml) workflow page in `Actions` section but there are 65k+ workflow runs and no search by date :(
Then I found PR https://github.com/airbytehq/airbyte/pull/1726 (already merged in master) in which tests are [failing](https://github.com/airbytehq/airbyte/pull/1726#issuecomment-763229605).
In above PR in this [comment](https://github.com/airbytehq/airbyte/pull/1726#issuecomment-766155157) I found mentioning another issue https://github.com/airbytehq/airbyte/issues/1805 about adding test data to Google Adwords. This issue is still in backlog and was never done.
Then I found this PR https://github.com/airbytehq/airbyte/pull/2688, it was created on April 1 and it's without any issue connected. It also has [failing](https://github.com/airbytehq/airbyte/pull/2688#issuecomment-811103999) tests.

Right now I can't really tell what caused this problem with tests because it requires more investigation. I believe more information could be found during the task execution.

**Comment by sherifnada** [comment] 2021-05-03 15:32
Issue is: 

```
Failures (1):
  JUnit Jupiter:ExecutableTestSource:testIncrementalSyncWithState()
    MethodSource [className = 'io.airbyte.integrations.standardtest.source.fs.ExecutableTestSource', methodName = 'testIncrementalSyncWithState', methodParameterTypes = '']
    => org.opentest4j.AssertionFailedError: Expected the first incremental sync to produce records ==> expected: <false> but was: <true>
       org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
       org.junit.jupiter.api.AssertFalse.assertFalse(AssertFalse.java:40)
       org.junit.jupiter.api.Assertions.assertFalse(Assertions.java:218)
       io.airbyte.integrations.standardtest.source.StandardSourceTest.testIncrementalSyncWithState(StandardSourceTest.java:336)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       java.base/java.lang.reflect.Method.invoke(Method.java:564)
       org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
       org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
       [...]
```

See here: https://github.com/airbytehq/airbyte/runs/2492973569?check_suite_focus=true#step:10:8673

ideas for next steps: 

1. run connector locally and try to reproduce the issue where an incremental sync does not produce any records
2. understand why #1 is happening -- an easy way to do this might be to change the config locally until you can get records to appear. If no data is in the source (e.g: if google only allows you to pull report data from <1 year ago) then we'll need to run some ad campaigns potentially. A sandbox would be useful but idk if google has it.

**Comment by po3na4skld** [comment] 2021-05-20 13:57
The issue is still exist I was faced with it when solving #2903

**Comment by keu** [comment] 2021-06-14 15:38
- [ ] - move to use SAT tests (30m)
- [ ] - reproduce the issue (4h)
- [ ] - create or update this ticket with a possible fix if an issue discovered (1h)

**Closed** 2021-06-25 22:45 UTC
Labels: area/connectors, type/bug
