### ISSUE TITLE
Source Amazon Seller Partner: Failed Adding Source: "nonetype" object has no attribute "split"

### ISSUE THREAD

**Issue by Blochergroup** [airbytehq/airbyte#28727] opened 2023-07-26 09:30 UTC
### Connector Name

 Amazon Seller Partner

### Connector Version

1.3.0

### What step the error happened?

Configuring a new connector

### Revelant information

After authenticating my Amazon Account and clicking "Set up source" I get following Error:
"nonetype" object has no attribute "split".

I tried with and without providing the optional fields (AWS Access Key...).

### Relevant log output

```shell
"nonetype" object has no attribute "split"

2023-06-20 12:46:23 [32mINFO[m i.a.w.t.TemporalAttemptExecution(get):138 - Cloud storage job log path: /workspace/6b7890bb-c7c4-48d0-b029-1a6bae25ae47/0/logs.log
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by andreyAtBB** [comment] 2023-08-04 18:54
This issue's root cause is https://github.com/airbytehq/airbyte/issues/27495
This one can be closed as duplicate IMHO

**Comment by Blochergroup** [comment] 2023-08-07 08:48
@andreyAtBB 
so it works if you just specify the Role ARN and none of the other aws credentials?

**Comment by andreyAtBB** [comment] 2023-08-07 12:29
> 

It requires Role ARN for sure and but I can't check if it works with none of the other AWS creds because we do not use AWS.

**Comment by marcosmarxm** [comment] 2023-09-15 17:47
Closed by https://github.com/airbytehq/airbyte/pull/29255

**Closed by marcosmarxm** 2023-09-15 17:47 UTC
Labels: type/bug, area/connectors, community, needs-triage, team/connectors-python, autoteam
