### ISSUE TITLE
DATETIME from MS SQL Server not returned as TIMESTAMP on postgres. It returns as text

### ISSUE THREAD

**Issue by jgngo** [airbytehq/airbyte#4657] opened 2021-07-09 08:46 UTC
## Enviroment
- **Airbyte version**:  0.26.4-alpha
- **OS Version / Instance**: Ubuntu 20.04
- **Deployment**: Docker
- **Source Connector and version**: airbyte/source-mssql 0.3.2 
- **Destination Connector and version**: airbyte/destination-postgres 0.3.6

- **Severity**: Low
- **Step where error happened**: Deploy

## Current Behavior
DATETIME from MS SQL Server becomes VARCHAR on postgres

## Expected Behavior
DATETIME from MS SQL Server should end up as TIMESTAMP on postgres

## Steps to Reproduce
1. Have DATETIME data on a SQL Server source
2. Push to a Postgres dest
3. Postgres data shows up as text, not date :(

## Are you willing to submit a PR?
No

**Comment by sherifnada** [comment] 2021-07-09 08:56
@jgngo thanks for the report. This is a duplicate of https://github.com/airbytehq/airbyte/issues/1006 so I'm closing this issue. Please follow along there!

**Closed by sherifnada** 2021-07-09 08:56 UTC
Labels: type/bug
