### ISSUE TITLE
Improve Google Analytics 4 source Error Messages

### ISSUE THREAD

**Issue by nataliekwong** [airbytehq/airbyte#26274] opened 2023-05-18 16:50 UTC
The error messages for Google Analytics (v4) can be improved to give better guidance to the user setting up the connector.

Error Type: the date was entered incorrectly
> The provided configuration does not fulfill the specification. Errors: json schema validation failed when comparing the data to the json schema. Errors: $.date_ranges_start_date: 2023-04-012 is an invalid date

Suggestion: The Start Date must be entered in the format YYYY-MM-DD.  (this should be validated in the form itself, not an error that is given when the source is tested)

Error Type: The custom report entered is not a valid configuration. 
See https://github.com/airbytehq/airbyte/issues/26212 as custom report entry should be improved to reduce the frequency and diversity of the errors here.
> custom_reports is not valid JSON'
> custom_reports is not of type 'array'
> custom_reports.0: 'dimensions' is a required property
> custom_reports.0: 'metrics' is a required property
> custom_reports.0: 'name' is a required property
> custom_reports: invalid dimension(s)
> custom_reports: invalid metric(s):  for the custom report: Horizon_Visitor'
> custom_reports.0.dimensions.0: {'name': 'city'} is not of type 'string'
> custom_reports.0.metrics: [] is too short'
> custom_reports.0.metrics.0: {'expression': 'totalUsers', 'name': 'Total_Users'} is not of type 'string'
> custom_reports.0.metrics.0: {'name': 'eventCount'} is not of type 'string'
> custom_reports.1.pivots: {'fieldNames': ['deviceCategory']} is not of type 'null', 'array'
> custom_reports.1.pivots.0: 'limit' is a required property

The custom report is not valid. Validate your custom query with the [GA 4 Query Explorer](https://ga-dev-tools.google/ga4/query-explorer/)

> custom_reports: pages already exist as a default report(s).'

Suggestion: The custom report {report name} already exists as the name of a prebuilt report. Rename your custom report.

Error Type: The API has been rate limited.
> Response Code: 429, Response Text: {  "error": {    "code": 429,    "message": "Exhausted potentially thresholded requests quota. This quota will refresh in under an hour. To learn more, see https://developers.google.com/analytics/devguides/reporting/data/v1/quotas",    "status": "RESOURCE_EXHAUSTED"  }}

Suggestion: Your API key has reached its limit for the hour. Wait until the quota refreshes to retry. 
--

Error type: Unknown
> string indices must be integers
> int' object is not subscriptable
> generator raised StopIteration

Suggestion: I'm not sure what these errors come from - for the team addressing these issues, it would be helpful to understand the root cause of these errors to provide a suggestion for improvement.

**Comment by artem1205** [comment] 2023-05-31 15:11
Hey, @nataliekwong ,

I generally agree with your propositions, described in https://github.com/airbytehq/airbyte/issues/26212, I even made a PR for another Google connector with the same improvement: https://github.com/airbytehq/airbyte/pull/23617 (unfortunately, this cannot be done at the moment due to UI limitations and limitations in backwards compatibility.

As for now it seems to me that error description that looks like:

> custom_reports is not valid JSON'
> custom_reports is not of type 'array'
> custom_reports.0: 'dimensions' is a required property
> custom_reports.0: 'metrics' is a required property
> custom_reports.0: 'name' is a required property
> custom_reports: invalid dimension(s)
> custom_reports: invalid metric(s): for the custom report: Horizon_Visitor'
> custom_reports.0.dimensions.0: {'name': 'city'} is not of type 'string'
> custom_reports.0.metrics: [] is too short'
> custom_reports.0.metrics.0: {'expression': 'totalUsers', 'name': 'Total_Users'} is not of type 'string'
> custom_reports.0.metrics.0: {'name': 'eventCount'} is not of type 'string'
> custom_reports.1.pivots: {'fieldNames': ['deviceCategory']} is not of type 'null', 'array'
> custom_reports.1.pivots.0: 'limit' is a required property

is much more informative than next one:

> The custom report is not valid. Validate your custom query with the [GA 4 Query Explorer](https://ga-dev-tools.google/ga4/query-explorer/)/

Because it may be so that customer makes copy-paste not from the `Query Explorer Tool`, or tries to import several reports, and thus a link to a third-party resource will not help him much to correct the error.

WDYT?

**Comment by nataliekwong** [comment] 2023-06-02 17:22
@artem1205 Thanks for linking your PR - sounds like this is on Frontend to make the change and we leave the spec unchanged.

Valid feedback on making the error too generic. How would you group the errors into more helpful error messages that detect when a user is running into those situations?

**Comment by nataliekwong** [comment] 2023-06-06 23:05
Got it. Here's my suggestion then as it then focuses on improved readability while addressing those cases uniquely. By the way, just double checking - we are still emitting the full / raw error message as an internal message, while the external message is the one getting improved here? Just want to make sure that's the case. 

Basic errors with formatting:
> custom_reports is not valid JSON'
> custom_reports is not of type 'array'

Suggestion: The custom report entered is not in a JSON array format. Check the entered format follows the syntax in our [docs](https://docs.airbyte.com/integrations/sources/google-analytics-data-api/).

> custom_reports.0: 'name' is a required property

Suggestion: The custom report entered does not contain a name, which is required. Check the entered format follows the syntax in our [docs](https://docs.airbyte.com/integrations/sources/google-analytics-data-api/).

> custom_reports.0: 'dimensions' is a required property

Suggestion: The custom report entered does not contain dimensions, which is required. Check the entered format follows the syntax in our [docs](https://docs.airbyte.com/integrations/sources/google-analytics-data-api/) and validate your custom query with the [GA 4 Query Explorer](https://ga-dev-tools.google/ga4/query-explorer/). 

> custom_reports.0: 'metrics' is a required property

Suggestion: The custom report entered does not contain metrics, which is required. Check the entered format follows the syntax in our [docs](https://docs.airbyte.com/integrations/sources/google-analytics-data-api/) and validate your custom query with the [GA 4 Query Explorer](https://ga-dev-tools.google/ga4/query-explorer/). 

Issues with the dimension:
> custom_reports: invalid dimension(s)
> custom_reports.0.dimensions.0: {'name': 'city'} is not of type 'string'

Suggestion: The custom report entered contains invalid dimensions. Validate your custom query with the [GA 4 Query Explorer](https://ga-dev-tools.google/ga4/query-explorer/). 

Issues with the metrics:
> custom_reports: invalid metric(s): for the custom report: Horizon_Visitor'
> custom_reports.0.metrics.0: {'expression': 'totalUsers', 'name': 'Total_Users'} is not of type 'string'
> custom_reports.0.metrics.0: {'name': 'eventCount'} is not of type 'string'

Suggestion: The custom report entered contains invalid metrics {metric value}. Validate your custom query with the [GA 4 Query Explorer](https://ga-dev-tools.google/ga4/query-explorer/). 

Issues with the pivot: 
> custom_reports.1.pivots: {'fieldNames': ['deviceCategory']} is not of type 'null', 'array'
> custom_reports.1.pivots.0: 'limit' is a required property

Suggestion: The custom report entered contains invalid pivots. Ensure the pivot follow the syntax described in the [docs](https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/Pivot).

Regarding the API limit: 

If the limit is based on the time frame, then let's make sure the error message reflects that. 

- If by hour: Your API key has reached its limit for the hour. Wait until the quota refreshes in an hour to retry.
- If by day: Your API key has reached its limit for the day. Wait until the quota refreshes tomorrow to retry.
- If by resource (did you mean property?): 
For property per hour: Your API key has reached its limit for this property for the hour. Wait until the quota refreshes in an hour to retry.
For property per day: Your API key has reached its limit for this property for the day. Wait until the quota refreshes tomorrow to retry.

**Comment by artem1205** [comment] 2023-06-09 10:39
@nataliekwong ,
If you don't mind, I would kindly ask you to present such type of task in a move convenient way, e.g.:

| Link to error | Error type | config / steps to reproduce                                                                                                                                                                                                                    | Current message                                                                                                                   | New message       |
|---------------|------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------|-------------------|
| ?             | SYNTAX     | {"custom_reports": "invalid"}                                                                                                                                                                                                                  | custom_reports is not valid JSON'                                                                                                 | WRONG_JSON_SYNTAX |
| ?             | SYNTAX     | {"custom_reports": "{}"}                                                                                                                                                                                                                       | custom_reports is not of type 'array'                                                                                             | WRONG_JSON_SYNTAX |
|               | SCHEMA     | {"custom_reports": {"custom_reports": "[{}]"}                                                                                                                                                                                                  | custom_reports.0: 'name' is a required property                                                                                   | NO_NAME           |
|               | SCHEMA     | {"custom_reports": "[{\"name\": \"name\"}]"}                                                                                                                                                                                                   | custom_reports.0: \'dimensions\' is a required property                                                                           | NO_DIMENSIONS     |
|               | SCHEMA     | {"custom_reports": "[{\"name\": \"daily_active_users\", \"dimensions\": [\"date\"]}]"}                                                                                                                                                         | custom_reports.0: 'metrics' is a required property                                                                                | NO_METRICS        |
|               | SCHEMA     | {"custom_reports": "[{\"name\": \"daily_active_users\", \"dimensions\": [{\"name\": \"city\"}]}]"}                                                                                                                                             | custom_reports.0.dimensions.0: {'name': 'city'} is not of type 'string'                                                           | WRONG_DIMENSIONS  |
|               | SCHEMA     | {"custom_reports": "[{\"name\": \"name\", \"dimensions\": [], \"metrics\": []}]"}}                                                                                                                                                             | custom_reports.0.dimensions.0: [] is too short                                                                                    | WRONG_DIMENSIONS  |
|               | SCHEMA     | {"custom_reports": "[{\"name\": \"name\", \"dimensions\": [\"date\"], \"metrics\": [\"unknown\"]}]"}                                                                                                                                           | custom_reports: invalid metric(s): unknown for the custom report: name                                                            | WRONG_METRICS     |
|               | SCHEMA     | {"custom_reports": "[{\"name\": \"pivot_report\", \"dateRanges\": [{ \"startDate\": \"2020-09-01\", \"endDate\": \"2020-09-15\" }], \"dimensions\": [\"browser\", \"country\", \"language\"], \"metrics\": [\"sessions\"], "\"pivots\": {}}]"} | custom_reports.0.pivots: {} is not of type \'null\', \'array\'                                                                    | WRONG_PIVOTS      |
|               | API LIMIT  | Your API key has reached its limit for the hour                                                                                                                                                                                                | { "error": { "code": 429, "message": "Exhausted potentially thresholded requests quota. This quota will refresh in under an hour. | API_LIMIT_HOUR    |



WRONG_JSON_SYNTAX = "The custom report entered is not in a JSON array format. Check the entered format follows the syntax in our docs: https://docs.airbyte.com/integrations/sources/google-analytics-data-api/."
WRONG_NAME = "Suggestion: The custom report entered does not contain a name, which is required. Check the entered format follows the syntax in our docs: https://docs.airbyte.com/integrations/sources/google-analytics-data-api/.""
NO_DIMENSIONS = "The custom report entered does not contain dimensions, which is required. Check the entered format follows the syntax in our docs (https://docs.airbyte.com/integrations/sources/google-analytics-data-api/) and validate your custom query with the GA 4 Query Explorer (https://ga-dev-tools.google/ga4/query-explorer/)."
NO_METRICS = "The custom report entered does not contain metrics, which is required. Check the entered format follows the syntax in our docs (https://docs.airbyte.com/integrations/sources/google-analytics-data-api/) and validate your custom query with the GA 4 Query Explorer (https://ga-dev-tools.google/ga4/query-explorer/)."
WRONG_DIMENSIONS = "The custom report {report_name} entered contains invalid dimensions: {dimensions}. Validate your custom query with the GA 4 Query Explorer (https://ga-dev-tools.google/ga4/query-explorer/)."
WRONG_METRICS = "The custom report {report_name} entered contains invalid metrics: {metrics}. Validate your custom query with the GA 4 Query Explorer (https://ga-dev-tools.google/ga4/query-explorer/)."
WRONG_PIVOTS = "The custom report {report_name} entered contains invalid pivots: {pivots}. Ensure the pivot follow the syntax described in the docs (https://developers.google.com/analytics/devguides/reporting/data/v1/rest/v1beta/Pivot)."

**Comment by lazebnyi** [comment] 2023-09-13 21:51
Look like all error handled. Custom reports will be fixed in https://github.com/airbytehq/airbyte/issues/23874.

**Closed by lazebnyi** 2023-09-13 21:51 UTC
Labels: team/connectors-python, connectors/source/google-analytics-data-api
