### ISSUE TITLE
Problem after upgrade: `java.lang.IllegalStateException: baseUrl is invalid.`

### ISSUE THREAD

**Issue by sivankumar86** [airbytehq/airbyte#38854] opened 2024-06-03 06:13 UTC
### Helm Chart Version

0.94.x

### What step the error happened?

During the Sync

### Relevant information

Sync jobs are getting failed after upgrade to 0.61.x.

P.S : we are using custom connector. 

### Relevant log output

```shell
ontainer-orchestrator:0.61.0, pullPolicy=IfNotPresent]]...
2024-06-03 04:42:22 replication-orchestrator > sourceLauncherConfig is: io.airbyte.persistence.job.models.IntegrationLauncherConfig@2480acc3[jobId=639594,attemptId=0,connectionId=8597f9d9-f203-4e2d-be23-3a5fa2eb54e0,workspaceId=c810ba10-3e93-4c4c-976f-8605746e4520,dockerImage=zipau-docker.jfrog.io/source-mssql:3.1.2,normalizationDockerImage=<null>,supportsDbt=false,normalizationIntegrationType=<null>,protocolVersion=Version{version='0.2.0', major='0', minor='2', patch='0'},isCustomConnector=true,allowedHosts=<null>,additionalEnvironmentVariables=<null>,additionalLabels=<null>,priority=<null>,additionalProperties={}]
2024-06-03 04:42:22 ERROR i.a.c.Application(run):80 - Killing orchestrator because of an Exception
java.lang.IllegalStateException: baseUrl is invalid.
	at io.airbyte.api.client.generated.SourceApi.getSourceWithHttpInfo(SourceApi.kt:3690) ~[io.airbyte-airbyte-api-0.61.0.jar:?]
	at io.airbyte.api.client.generated.SourceApi.getSource(SourceApi.kt:653) ~[io.airbyte-airbyte-api-0.61.0.jar:?]
	at io.airbyte.workers.general.ReplicationWorkerFactory.create(ReplicationWorkerFactory.java:149) ~[io.airbyte-airbyte-commons-worker-0.61.0.jar:?]
	at io.airbyte.container_orchestrator.orchestrator.ReplicationJobOrchestrator.runJob(ReplicationJobOrchestrator.java:118) ~[io.airbyte-airbyte-container-orchestrator-0.61.0.jar:?]
	at io.airbyte.container_orchestrator.Application.run(Application.java:78) [io.airbyte-airbyte-container-orchestrator-0.61.0.jar:?]
	at io.airbyte.container_orchestrator.Application.main(Application.java:38) [io.airbyte-airbyte-container-orchestrator-0.61.0.jar:?]
2024-06-03 04:42:22 INFO i.a.c.AsyncStateManager(write):51 - Writing async status FAILED for KubePodInfo[namespace=product-analytics, name=orchestrator-repl-job-639594-attempt-0, mainContainerInfo=KubeContainerInfo[image=airbyte/container-orchestrator:0.61.0, pullPolicy=IfNotPresent]]...
2024-06-03 04:42:22 INFO i.a.a.SegmentAnalyticsClient(close):221 - Closing Segment analytics client...
2024-06-03 04:42:22 INFO i.a.a.BlockingShutdownAnalyticsPlugin(waitForFlush):276 - Waiting for Segment analytic client to flush enqueued messages...
2024-06-03 04:42:22 INFO i.a.a.BlockingShutdownAnalyticsPlugin(waitForFlush):288 - Segment analytic client flush complete.
2024-06-03 04:42:22 INFO i.a.a.SegmentAnalyticsClient(close):225 - Segment analytics client closed.  No new events will be accepted.
2024-06-03 04:42:22 INFO i.m.r.Micronaut(lambda$start$0):117 - Embedded Application shutting down
2024-06-03 04:42:22 WARN c.v.l.l.Log4j2Appender(close):108 - Already shutting down. Cannot remove shutdown hook.
2024-06-03 04:42:22 WARN c.v.l.l.Log4j2Appender(close):108 - Already shutting down. Cannot remove shutdown hook.
```

**Comment by jgournet** [comment] 2024-06-03 06:40
same issue here.
I'm trying to add "global.airbyteUrl" in the helm chart  (but I'm hitting another new weird issue now)

**Comment by jgournet** [comment] 2024-06-03 08:44
just in case: after sooo many different issues, I uninstalled the helm chart and re-installed again (with the addition of  "global.airbyteUrl") and it seems to be working now

not a great experience, but after some long hours, I managed to launch a sync

**Comment by anmol1vw13** [comment] 2024-06-03 08:48
What is global.airbyteUrl? Is it an environment variable?

**Comment by jgournet** [comment] 2024-06-03 08:50
> What is global.airbyteUrl? Is it an environment variable?

If you are using the helm chart, it's a new value:
https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte/values.yaml#L22

**Comment by anmol1vw13** [comment] 2024-06-03 08:57
I'm deploying airbyte on an ec2 instance. What do you suggest I should be doing to resolve this error?

**Comment by jgournet** [comment] 2024-06-03 09:02
> I'm deploying airbyte on an ec2 instance. What do you suggest I should be doing to resolve this error?

sorry, I have no idea - I'm just someone who had the same issue as you and "resolved" by unistalling the helm chart and re-installing with that modification

**Comment by anmol1vw13** [comment] 2024-06-03 09:03
Okay, thanks @jgournet

**Comment by sivankumar86** [comment] 2024-06-03 22:02
I have tried all the options. used ingress url and service url. uninstall and reinstall the helm chart but, no luck.

**Comment by sivankumar86** [comment] 2024-06-03 22:02
@marcosmarxm Could you shed some light on this ?

**Comment by alexremn** [comment] 2024-06-03 23:07
Same here.
We are using Airbyte inside private network. Specifying external private domain or internal Kubernetes domain both not working (504 error during sync try), unsetting global.airbyteUrl - sync failure with above error.

**Comment by firehist** [comment] 2024-06-04 06:33
Hey,
That is really hard to get into the helm chart configuration for sure 😅

@pmspeixoto `global.airbyteUrl` seems to be in use only for the `airbyte-airbyte-env` ConfigMap, and populate the following env variables :
- [`AIRBYTE_URL`](https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte/templates/env-configmap.yaml#L23)
- [`KEYCLOAK_HOSTNAME_URL`](https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte/templates/env-configmap.yaml#L60)
- [`AIRBYTE_API_HOST`](https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte/templates/env-configmap.yaml#L74) __(if pro or enterprise)__
- [`AIRBYTE_API_HOST`](https://github.com/airbytehq/airbyte-platform/blob/main/charts/airbyte/templates/env-configmap.yaml#L74) __(if pro or enterprise)__

**Comment by yzislin** [comment] 2024-06-04 10:38
I am having this error on Schema discovery. I do not use helm charts or kubernetes. Just running on ec2 instance.

**Comment by yzislin** [comment] 2024-06-04 12:57
downgrading to 0.60.1 fixes this error for me. I also had a problem with named volumes versus local host path. Had to revert docker-compose to not using named volume for local root. That was a pain for me as well

**Comment by marcosmarxm** [comment] 2024-06-04 14:14
Folks sorry the delay I'd saw the issue now. I'm escalating this asap to the deployment team.

**Comment by marcosmarxm** [comment] 2024-06-04 20:18
@sivankumar86 and all, please provide any information about what steps you're doing to get into this error. 
What files you're changing, from what version and what commands are you running.

**Comment by alexremn** [comment] 2024-06-04 22:43
@marcosmarxm applying update from 0.92.9 (last working version for me) to any newer version (0.61.1) w/o changing config and all jobs start to fail complaining about:
1. baseUrl
2. api host (another bug, discussed in separate issue)

**Comment by yzislin** [comment] 2024-06-05 13:19
So latest release (0.62.0) still has this problem? I did not see this issue in the release notes

**Comment by ivan-sukhomlyn** [comment] 2024-06-06 11:21
After upgrading to `0.62` in k8s env, I have troubles with sync too.
For example,
1. Errors related to MongoDB cluster at PostgreSQL to BigQuery connector
2. Starting sync with success result with no data transfer
<img width="1263" alt="Screenshot 2024-06-05 at 16 46 08" src="https://github.com/airbytehq/airbyte/assets/55390366/f6fc67d3-f642-4b05-9a0d-89b948a45910">
<img width="597" alt="Screenshot 2024-06-06 at 11 41 27" src="https://github.com/airbytehq/airbyte/assets/55390366/05805683-722c-42ec-bc0e-6ed4478dcb1a">

errors example from `server`
```
StatsAggregationHelper(lambda$hydrateWithAggregatedStats$6):197 - No stats have been persisted for job

you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword

2024-06-06 08:00:14 ERROR i.a.c.c.ConfigReplacer(getAllowedHosts):93 - All allowedHosts values are un-replaced.  Check this connector's configuration or actor definition -
 [${connection_string}] 
```

`worker` logs:
```
2024-06-06 09:18:12 platform > State Store reports orchestrator pod orchestrator-repl-job-82-attempt-0 succeeded                                                           
2024-06-06 09:18:12 INFO i.a.w.t.s.ReplicationActivityImpl(lambda$replicateV2$3):207 - sync summary: io.airbyte.config.StandardSyncOutput@7e74007c[standardSyncSummary=io.a
    at io.airbyte.workers.general.ReplicationWorkerHelper.startDestination(ReplicationWorkerHelper.kt:211)                                                                 
    at io.airbyte.workers.general.BufferedReplicationWorker.lambda$run$0(BufferedReplicationWorker.java:170)                                                               
    at io.airbyte.workers.general.BufferedReplicationWorker.lambda$runAsync$2(BufferedReplicationWorker.java:235)                                                          
    at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)                                                                          
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)                                                                           
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)                                                                           
    at java.base/java.lang.Thread.run(Thread.java:1583)                                                                                                                    
Caused by: io.airbyte.workers.exception.WorkerException: Failed to create pod for write step                                                                               
    at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:197)                                                                                   
    at io.airbyte.workers.process.AirbyteIntegrationLauncher.write(AirbyteIntegrationLauncher.java:265)                                                                    
    at io.airbyte.workers.internal.DefaultAirbyteDestination.start(DefaultAirbyteDestination.java:110)                                                                     
    at io.airbyte.workers.general.ReplicationWorkerHelper.startDestination(ReplicationWorkerHelper.kt:209)                                                                 
    ... 6 more                                                                                                                                                             
Caused by: java.lang.RuntimeException: java.io.IOException: kubectl cp failed with exit code 1                                                                             
    at io.airbyte.workers.process.KubePodProcess.copyFilesToKubeConfigVolume(KubePodProcess.java:368)                                                                      
    at io.airbyte.workers.process.KubePodProcess.<init>(KubePodProcess.java:672)                                                                                           
    at io.airbyte.workers.process.KubeProcessFactory.create(KubeProcessFactory.java:193)                                                                                   
    ... 9 more                                                                                                                                                             
Caused by: java.io.IOException: kubectl cp failed with exit code 1                                                                                                         
    at io.airbyte.workers.process.KubePodProcess.copyFilesToKubeConfigVolume(KubePodProcess.java:362)                                                                      
    ... 11 more 
```

**Comment by marcosmarxm** [comment] 2024-06-06 13:14
@ivan-sukhomlyn from what version did you upgrade from?

**Comment by JuanPabloToniolo-Udesa** [comment] 2024-06-06 16:15
I'm using docker-compose and got the same error:

`Caused by: io.temporal.failure.ApplicationFailure: message='baseUrl is invalid.', type='java.lang.IllegalStateException', nonRetryable=false
        at io.airbyte.api.client.generated.WorkspaceApi.getWorkspaceByConnectionIdWithTombstoneWithHttpInfo(WorkspaceApi.kt:3140) ~[io.airbyte-airbyte-api-0.62.1.jar:?]
        at io.airbyte.api.client.generated.WorkspaceApi.getWorkspaceByConnectionIdWithTombstone(WorkspaceApi.kt:509) ~[io.airbyte-airbyte-api-0.62.1.jar:?]
        at io.airbyte.workers.temporal.scheduling.activities.ConfigFetchActivityImpl.isWorkspaceTombstone(ConfigFetchActivityImpl.java:248) ~[io.airbyte-airbyte-workers-0.62.1.jar:?]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[?:?]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[?:?]
        at io.temporal.internal.activity.RootActivityInboundCallsInterceptor$POJOActivityInboundCallsInterceptor.executeActivity(RootActivityInboundCallsInterceptor.java:64) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.activity.RootActivityInboundCallsInterceptor.execute(RootActivityInboundCallsInterceptor.java:43) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.activity.ActivityTaskExecutors$BaseActivityTaskExecutor.execute(ActivityTaskExecutors.java:107) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.activity.ActivityTaskHandlerImpl.handle(ActivityTaskHandlerImpl.java:124) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handleActivity(ActivityWorker.java:278) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:243) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:216) ~[temporal-sdk-1.22.3.jar:?]
        at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:105) ~[temporal-sdk-1.22.3.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
`

I upgraded from 60.1 to 61.0, got this error, and also with the lastest 62.x versions. I cannot sync any connection.

**Comment by capture-namang** [comment] 2024-06-10 06:17
I am using docker compose to deploy and am getting the same error

**Comment by M-Dahab** [comment] 2024-06-10 07:44
Downgrading to `0.60.1` worked for now.

**Comment by capture-namang** [comment] 2024-06-10 10:11
downgrading is giving me a different error : 

```
2024-06-10 15:29:09 Caused by: org.postgresql.util.PSQLException: ERROR: column actor_definition.support_refreshes does not exist
2024-06-10 15:29:09   Position: 618
2024-06-10 15:29:09     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725) ~[postgresql-42.7.3.jar:42.7.3]
2024-06-10 15:29:09     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412) ~[postgresql-42.7.3.jar:42.7.3]
2024-06-10 15:29:09     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371) ~[postgresql-42.7.3.jar:42.7.3]
2024-06-10 15:29:09     at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502) ~[postgresql-42.7.3.jar:42.7.3]
2024-06-10 15:29:09     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419) ~[postgresql-42.7.3.jar:42.7.3]
2024-06-10 15:29:09     at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194) ~[postgresql-42.7.3.jar:42.7.3]
2024-06-10 15:29:09     at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:180) ~[postgresql-42.7.3.jar:42.7.3]
2024-06-10 15:29:09     at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-5.1.0.jar:?]
2024-06-10 15:29:09     at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-5.1.0.jar:?]
2024-06-10 15:29:09     at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219) ~[jooq-3.19.7.jar:?]
2024-06-10 15:29:09     at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4940) ~[jooq-3.19.7.jar:?]
2024-06-10 15:29:09     at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236) ~[jooq-3.19.7.jar:?]
2024-06-10 15:29:09     at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348) ~[jooq-3.19.7.jar:?]
```

**Comment by AsoTora** [comment] 2024-06-10 14:36
Hey folks, for me the solution was quite straight-forward:

1. Upgrading chart version "0.94.1" -> "0.143.0"
2. Adding the global.airbyteUrl with a value of ingress host, no protocol/port specified.

**Comment by andy1xx8** [comment] 2024-06-10 20:08
> Hey folks, for me the solution was quite straight-forward:
> 
> 
> 
> 1. Upgrading chart version "0.94.1" -> "0.143.0"
> 
> 2. Adding the global.airbyteUrl with a value of ingress host, no protocol/port specified.
> 
> 

Hi how can we set up the 2nd setting? Thanks in advance

**Comment by Chammar37** [comment] 2024-06-13 20:24
I've gotten the same errors with our docker compose deployment on version 0.61.0 as well. Reverted back to 0.60.1 and it seems to be working so far

**Comment by JuanPabloToniolo-Udesa** [comment] 2024-06-13 20:48
I got fixed by downloading the repo and running run-ab-platform.sh on a new computer, with the fresh "docker-compose.yaml" and ".env" compared with mine and I have to add some env like "AIRBYTE_INSTALLATION_ID", "AIRBYTE_URL", "AIRBYTE_API_HOST" to docker-compose in specific locations and in ".env" file I have to recheck how I have declared this vars:

```
AIRBYTE_SERVER_HOST=airbyte-server:8001
INTERNAL_API_HOST=http://airbyte-server:8001
INTERNAL_API_URL=http://airbyte-server:8001
CONNECTOR_BUILDER_API_HOST=airbyte-connector-builder-server:8080
WEBAPP_URL=http://localhost:8000/
WORKLOAD_API_HOST=workload-api-server:8007
WORKLOAD_API_URL=http://workload-api-server:8007
CONNECTOR_BUILDER_API_URL=/connector-builder-api
AIRBYTE_API_HOST=airbyte-api-server:8006
```
^^ These are my updated ones

Sorry for the vage information, I have touched a lot in my files to get it working. 

After this checks got 0.63.0 working straightforward. I must say that a specific version of 0.62.X got me errors with the postgres version when running "bootloader" but not in 0.63.0.

If someone wants the files yaml and env that I get from cloning on the new machine, I can upload it

**Comment by cbeauch** [comment] 2024-06-19 16:51
> Hey folks, for me the solution was quite straight-forward:
> 
> 1. Upgrading chart version "0.94.1" -> "0.143.0"
> 2. Adding the global.airbyteUrl with a value of ingress host, no protocol/port specified.

I just did this and still having the same issue

**Comment by kzvezdarov** [comment] 2024-06-19 21:23
I'm seeing this on both `0.60.1` and `0.63.1`, the workarounds and fixes listed in this thread haven't worked so far; deployed on GKE Autopilot and trying to upgrade from 0.50.45.

If I delete all airbyte deployments, config maps, and the volume shared between server and cron, redeploying allows a few sync jobs to start up and complete, but inevitably the worker gets in a state where no workflows run and everything fails with:
`Caused by: io.temporal.failure.ApplicationFailure: message='baseUrl is invalid.', type='java.lang.IllegalStateException', nonRetryable=false`
followed by/paired with:
`Caused by: io.temporal.failure.ApplicationFailure: message='Cannot invoke "java.lang.Long.longValue()" because the return value of "io.airbyte.workers.temporal.scheduling.activities.JobCreationAndStatusUpdateActivity$AttemptNumberFailureInput.getJobId()" is null', type='java.lang.NullPointerException', nonRetryable=false`

This is rather unfortunate because due to the migrations applied when upgrading to 0.60.1, 0.63.1, I'm unable to revert back to a known working version (0.50.45).

**Comment by dantonbertuol** [comment] 2024-06-27 21:43
Any definitive solution for this?

**Comment by cconnect-tmcfadden** [comment] 2024-08-16 05:57
On 0.63.14 when using builder and testing a stream: 
ERROR Internal Server Error: baseUrl is invalid.

Same test on 0.50.11 works.

**Comment by iulianapostol-ozone** [comment] 2024-08-19 14:44
> @marcosmarxm applying update from 0.92.9 (last working version for me) to any newer version (0.61.1) w/o changing config and all jobs start to fail complaining about:
> 
> 1. baseUrl
> 2. api host (another bug, discussed in separate issue)

I'm having this issue now

**Comment by AsoTora** [comment] 2024-08-19 14:50
> > @marcosmarxm applying update from 0.92.9 (last working version for me) to any newer version (0.61.1) w/o changing config and all jobs start to fail complaining about:
> > 
> > 1. baseUrl
> > 2. api host (another bug, discussed in separate issue)
> 
> I'm having this issue now

Congratulations, why do we all need to know this? Read the thread

**Comment by dantonbertuol** [comment] 2024-08-19 16:34
I can't understand why we haven't had any positioning from the team yet. Is there no definitive solution? We won't be able to update the Airbyte version?

**Comment by MsMatias** [comment] 2024-09-05 12:26
> downgrading is giving me a different error :
> 
> ```
> 2024-06-10 15:29:09 Caused by: org.postgresql.util.PSQLException: ERROR: column actor_definition.support_refreshes does not exist
> 2024-06-10 15:29:09   Position: 618
> 2024-06-10 15:29:09     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725) ~[postgresql-42.7.3.jar:42.7.3]
> 2024-06-10 15:29:09     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412) ~[postgresql-42.7.3.jar:42.7.3]
> 2024-06-10 15:29:09     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371) ~[postgresql-42.7.3.jar:42.7.3]
> 2024-06-10 15:29:09     at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502) ~[postgresql-42.7.3.jar:42.7.3]
> 2024-06-10 15:29:09     at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419) ~[postgresql-42.7.3.jar:42.7.3]
> 2024-06-10 15:29:09     at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194) ~[postgresql-42.7.3.jar:42.7.3]
> 2024-06-10 15:29:09     at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:180) ~[postgresql-42.7.3.jar:42.7.3]
> 2024-06-10 15:29:09     at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44) ~[HikariCP-5.1.0.jar:?]
> 2024-06-10 15:29:09     at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java) ~[HikariCP-5.1.0.jar:?]
> 2024-06-10 15:29:09     at org.jooq.tools.jdbc.DefaultPreparedStatement.execute(DefaultPreparedStatement.java:219) ~[jooq-3.19.7.jar:?]
> 2024-06-10 15:29:09     at org.jooq.impl.Tools.executeStatementAndGetFirstResultSet(Tools.java:4940) ~[jooq-3.19.7.jar:?]
> 2024-06-10 15:29:09     at org.jooq.impl.AbstractResultQuery.execute(AbstractResultQuery.java:236) ~[jooq-3.19.7.jar:?]
> 2024-06-10 15:29:09     at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:348) ~[jooq-3.19.7.jar:?]
> ```

@capture-namang you can downgrade to https://artifacthub.io/packages/helm/airbyte/airbyte/0.453.2 and it will work

**Comment by marcosmarxm** [comment] 2024-10-09 19:31
Hello everyone 👋 Sorry for the lack of updates. From the discussions, it seems some users are experiencing an issue different from the main one: `java.lang.IllegalStateException: baseUrl is invalid.` If this applies to you, I strongly recommend opening a new GitHub issue and providing all the necessary information to reproduce the problem.

The latest version of the code (Helm Chart) doesn't have a `baseUrl` anymore. If you have encountered this problem recently, please feel free to contact me on Slack. We can troubleshoot it together to identify the root cause.

**Comment by marcosmarxm** [comment] 2024-12-03 17:48
Closing this as it was fixed in latest versions.

**Closed by marcosmarxm** 2024-12-03 17:48 UTC
Labels: type/bug, area/platform, community, team/deployments
