### ISSUE TITLE
allow adding names for connections in the UI

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#9737] opened 2022-01-24 08:05 UTC
Ability to add names to Connections to differentiate them, especially if the source-destination pair is identical except for the selected tables or the sync time.

The backend allows configuring names for syncs, and we should also allow configuring this in the UI + showing it on the connections view as a column.

**Comment by alafanechere** [comment] 2022-01-31 17:12
I'm closing this as this is a duplicate of https://github.com/airbytehq/airbyte/issues/4407

**Closed by alafanechere** 2022-01-31 17:12 UTC
Labels: type/enhancement, area/frontend
