### ISSUE TITLE
The webapp couldn't discover the local image.

### ISSUE THREAD

**Issue by charity1475** [airbytehq/airbyte#2687] opened 2021-03-31 11:36 UTC
## Current Behavior
On creating the new source connector in airbyte webapp from the locally built image which i asserted it was available the app searched and the could not find the image. I tried to re-build and restart several times but no changes.

*Tell us what happens instead of the expected behavior.*

## Logs
*If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window.*

## Steps to Reproduce
1.
1.
1.

## Severity of the bug for you
Very low

## Airbyte Version
Found in the .env file in the root of the project.
0.17.2

## Connector Version (if applicable)
locally built, dev 

![airbyte](https://user-images.githubusercontent.com/58939045/113138445-755b4a00-922e-11eb-9605-8d66235a0599.png)

*Environment, version, integration...*

**Comment by marcosmarxm** [comment] 2021-03-31 11:53
@charity1475 take a look [here](https://docs.airbyte.io/tutorials/toy-connector) you need to tag your image `:dev` (I think this part is not essential) and after this, you need to add manual your new connector in web-app.

**Comment by charity1475** [comment] 2021-03-31 18:33
![ps](https://user-images.githubusercontent.com/58939045/113193402-9a6cae80-9268-11eb-88fa-1e9a2c4ad03e.png)

and here is the image
![ps](https://user-images.githubusercontent.com/58939045/113193546-c12ae500-9268-11eb-8203-96e1ab5847de.png)

**Comment by jrhizor** [comment] 2021-04-01 16:37
So there's no requirement that the tag is dev, but it does have to match. So in the first screenshot it looked like you could set the tag to test to find it. Now that you set the dev image tag it should work either way.

Can you share the scheduler logs? I bet there's some problem it's encountering when trying to retrieve the spec from your image, which is incorrectly manifesting as a "Could not find docker image" error.

**Comment by charity1475** [comment] 2021-04-01 19:21
@jrhizor 
Here is the log file.
[log.txt](https://github.com/airbytehq/airbyte/files/6245988/log.txt)

**Comment by jrhizor** [comment] 2021-04-02 20:10
The final exception is the problem:`Encountered an issue while validating input docker image (airbyte/source-corebos:dev): no spec output found` 

To reproduce just this part you can run `docker run --rm -i airbyte/source-corebos:dev spec`

Here's what happens when you do this for an existing connector:
```
→ docker run --rm -i airbyte/source-exchangeratesapi-singer:0.2.1 spec
{"type": "SPEC", "spec": {"documentationUrl": "https://docs.airbyte.io/integrations/sources/ratesapi-io", "connectionSpecification": {"$schema": "http://json-schema.org/draft-07/schema#", "title": "ratesapi.io Source Spec", "type": "object", "required": ["start_date", "base"], "additionalProperties": false, "properties": {"start_date": {"type": "string", "description": "Start getting data from that date.", "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}$", "examples": ["YYYY-MM-DD"]}, "base": {"type": "string", "description": "ISO reference currency. See <a href=\"https://www.ecb.europa.eu/stats/policy_and_exchange_rates/euro_reference_exchange_rates/html/index.en.html\">here</a>."}}}}}
```

It emits a airbyte message of type "SPEC" that includes a `connectorSpecification` that adheres to the JSONSchema defined here for `ConnectorSpecification`: https://github.com/airbytehq/airbyte/blob/master/airbyte-protocol/models/src/main/resources/airbyte_protocol/airbyte_protocol.yaml#L205

Your connector is either erroring out, not outputting a spec message, or not outputting a _valid_ spec message.

**Comment by davinchia** [comment] 2021-04-22 13:28
Closing this since Jared's explanation seems like the right solution. Please reopen if you encounter this again!

**Closed by davinchia** 2021-04-22 13:28 UTC
Labels: type/bug
