### ISSUE TITLE
Improve sidecar connector pod OOM handling

### ISSUE THREAD

**Issue by tryangul** [airbytehq/airbyte#37492] opened 2024-04-22 23:04 UTC
Currently we do not indicate in the output the connector pod oomed. This would be very useful debug information to have and it has come up multiple times.

**Comment by davinchia** [comment] 2024-04-30 18:13
Duplicate of https://github.com/airbytehq/airbyte-internal-issues/issues/7175

**Closed by davinchia** 2024-04-30 18:13 UTC
Labels: team/platform-move, lights-on
