### ISSUE TITLE
AWS Graviton ARM support

### ISSUE THREAD

**Issue by nthbooth-feedr** [airbytehq/airbyte#9234] opened 2021-12-31 07:59 UTC
## Tell us about the problem you're trying to solve
AWS is pushing their Graviton ARM platform. They are not the only players who are starting to do this but they are the biggest. 
They are pushing it for a number of reasons:
1. It is cheaper for them and there leadership principles is Frugality (https://www.amazon.jobs/en-gb/principles)
2. The performance per Watt of power is better. It has taken ARM a long time to get to this point but not it is there with the compute power to rival AMD and Intel.
3. Because the performance per Watt of power is better it is greener for the end user.
4. It is a cheaper for a similar level of performance than the Intel or AMD based systems. 

## Describe the solution you’d like
I would like to see ARM become a supported platform for Airbyte and a first class host. Ideally starting docker hosting and ideally then supporting ECS and Kube. 

## Describe the alternative you’ve considered or used
We have deployed on intel/arm based devices 

## Additional context
Assuming you are hosting in AWS using ARM rather than intel or AMD would decrease your cloud hosting costs. This would allow for increased profit and or increased capacity for your customers at the same price point.

**Comment by alafanechere** [comment] 2022-01-03 17:47
Hi @nthbooth-feedr I don't know to what extent it overlaps with Apple M1 support which is also using ARM (https://github.com/airbytehq/airbyte/issues/2017). Did you try deploying Airbyte on Graviton?

**Comment by nthbooth-feedr** [comment] 2022-03-21 14:38
Yes I did and it did not work. Hence raising this ticket.

**Comment by adnanjmi21** [comment] 2022-05-10 08:50
I deployed airbyte on aws graviton instances by building using the source code with M1 instructions , Airbyte started successfully and I was able tot the use the UI but got errors while setting up anny sources or destinations 
`2022-05-10 08:39:24 ERROR i.a.c.i.LineGobbler(voidCall):82 - WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
`

**Comment by davinchia** [comment] 2022-05-12 09:27
This is related to https://github.com/airbytehq/airbyte/issues/2017.

**Comment by davinchia** [comment] 2022-05-12 09:30
This error happens because connector images are still only x86. See this comment for [updates and suggestions](https://github.com/airbytehq/airbyte/issues/2017#issuecomment-1124689972).

**Comment by davinchia** [comment] 2022-06-02 08:53
I'm going to close this as a duplicate of #2017

**Closed by davinchia** 2022-06-02 08:53 UTC
Labels: type/enhancement, area/platform, community, team/cloud, team/oss, autoteam
