### ISSUE TITLE
Google Analytics connector doesn't fail when API isn't enabled 

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1933] opened 2021-02-03 03:51 UTC
## Expected Behavior
Reported by @MarcoJoon

Job should fail based on what is written in the logs:
```
2021-02-03 02:26:12 ERROR (/tmp/workspace/71/0) DefaultAirbyteStreamFactory(internalLog):108 - time=2021-02-03 02:26:12 name=tap_google_analytics level=CRITICAL message=Received fatal error <HttpError 403 when requesting https://analyticsreporting.googleapis.com/v4/reports:batchGet?alt=json returned "Analytics Reporting API has not been used in project 728288732236 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/analyticsreporting.googleapis.com/overview?project=728288732236 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.">, reason=accessNotConfigured, status=403
```

## Current Behavior
The job succeeds

## Steps to Reproduce
1. Not sure about this one. Probably just a matter of not having the API enabled.

## Severity of the bug for you
High

## Connector Version
0.1.5

**Comment by MarcoJoon** [comment] 2021-02-03 03:57
The issue was that I enabled the analytics API in console.cloud.google.com and not in console.developers.google.com. Enabling it in the later solved the issue

**Comment by michel-tricot** [comment] 2021-02-03 03:58
Cool! That's is actually what we have in the doc. We just need to fix the connector to properly fail.

**Comment by yevhenii-ldv** [comment] 2021-02-05 13:50
The problem lies directly with the **Singer Tap** for this connector. Below are the lines of code:
```
try:
    report_definition = ReportsHelper.get_report_definition(stream)
    results = client.process_stream(report_definition)

    # we write the schema message after we are sure that we could
    #  fetch records without errors
    singer.write_schema(stream_id, stream_schema, key_properties)
    singer.write_records(stream_id, results)
except TapGaInvalidArgumentError as e:
    errors_encountered = True
    LOGGER.error("Skipping stream: '{}' due to invalid report definition.".format(stream_id))
    LOGGER.debug("Error: '{}'.".format(e))
except TapGaRateLimitError as e:
    errors_encountered = True
    LOGGER.error("Skipping stream: '{}' due to Rate Limit Errors.".format(stream_id))
    LOGGER.debug("Error: '{}'.".format(e))
except TapGaQuotaExceededError as e:
    errors_encountered = True
    LOGGER.error("Skipping stream: '{}' due to Quota Exceeded Errors.".format(stream_id))
    LOGGER.debug("Error: '{}'.".format(e))
except TapGaAuthenticationError as e:
    LOGGER.error("Stopping execution while processing '{}' due to Authentication Errors.".format(stream_id))
    LOGGER.debug("Error: '{}'.".format(e))
    sys.exit(1)
except TapGaUnknownError as e:
    LOGGER.error("Stopping execution while processing '{}' due to Unknown Errors.".format(stream_id))
    LOGGER.debug("Error: '{}'.".format(e))
    sys.exit(1)
```

**Singer Tap** catches the error, displays the Log of the error and exits the program. To solve this issue, need to change the code for library `tap_google_analytics` and raise an error when it appears.

**Comment by sherifnada** [comment] 2021-02-05 15:39
We should have the `check` method verify that the API is enabled

**Comment by yevhenii-ldv** [comment] 2021-02-11 15:16
While working on this issue, I did the following:
Using two e-mail boxes: `@gmail` and `@<corporate_email>`, I investigated this problem.
1. Using the email account from `@<corporate_email>` I could not reproduce the error, I always managed to pass the check and read the data using `pipelinewise-tap-google-analytics`. However, I was not able to fully test the possibilities of enabling the Google Analytics API through two URLs: console.developers.google.com and console.cloud.google.com. Every time I tried to go to console.developers.google.com I was redirected to console.cloud.google.com, so I used the second email account.
2. Using my personal `@gmail `account, I created Google Analytics Account and tried to reproduce the error again. I tried to turn on and off the Google Analytics API via console.developers.google.com and console.cloud.google.com. When I turned on Google Analytics API using any of the URLs, then I could receive data from Google Analytics without any errors like `403` (unfortunately, I did not receive records, because they do not exist for my account yet, but the request returned `200` status and empty data array). The most interesting thing I noticed is that if I enable the Google Analytics API using console.developers.google.com, then by refreshing the page on console.cloud.google.com, I will also see that the API is enabled (this works for the opposite direction too). That is, by turning on Google Analytics API using any of the two URLs, the user will not encounter any problems with receiving data, and when checking the connection, accordingly, everything also works correctly: turning on Google Analytics API through any of the URLs we go through the connection check. 
Just one moment, it may be necessary to wait a few seconds for the API to turn on. Google in its response tells us to wait a few minutes after turning on the API, but I tried to connect after 10-15 seconds and everything worked out correctly.


The biggest problem for me was that I could not find `viewID` anywhere to receive data.
As it turned out, now Google Analytics, when creating an account, by default creates both Google Analytics 4 and Universal Analytics property. And in order to be able to see the column with `Views`, you need to open additional parameters when creating an Google Analytics account and change the checkpoint. This [article](https://www.3-prime.com/2020/12/generation-4-analytics-missing-column-to-create-view/) describes everything in more detail. And as far as I understand, using this functionality, we will not be able to receive data for Google Analytics accounts, where Google Analytics 4 and Universal Analytics property are created both. And in this case, the [link](https://ga-dev-tools.appspot.com/account-explorer/) to the Google Analytics Account Explorer does not help, since I had it hanging in a continuous load and could not find anything.
I'm not sure, maybe we should add a clarification on this issue to the documentation on Google Analytics Source, maybe not. But I ran into quite a few problems while connecting Google Analytics Account for testing.

**Comment by sherifnada** [comment] 2021-02-14 22:10
We've been unable to repro this, and `check` is failing when the API is not enabled. Closing.

**Closed by sherifnada** 2021-02-14 22:10 UTC
Labels: area/integration, type/bug, zazmic
