### ISSUE TITLE
connector generator fails due to docker build

### ISSUE THREAD

**Issue by imrehg** [airbytehq/airbyte#21512] opened 2023-01-18 07:35 UTC
## Environment
- **Airbyte version**:  example is 0.40.28
- **OS Version / Instance**: macOS Ventura 13.1 (22C65)
- **Deployment**: N/A
- **Source Connector and version**: N/A
- **Destination Connector and version**: N/A
- **Step where error happened**: Generating new connector

## Current Behavior

Following the [new connector generation guide](https://docs.airbyte.com/connector-development/config-based/tutorial/create-source), running `./generate.sh` fails on line 30.

## Expected Behavior

Successful connector generator run.

## Logs

```
$ ./generate.sh
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
Removing previous generator if it exists...
Building generator docker image...
[+] Building 1.8s (7/7) FINISHED
 => [internal] load build definition from Dockerfile                                                                                      0.1s
 => => transferring dockerfile: 704B                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                         0.1s
 => => transferring context: 2B                                                                                                           0.0s
 => [internal] load metadata for docker.io/library/node:16-alpine                                                                         1.6s
 => [1/3] FROM docker.io/library/node:16-alpine@sha256:1298fd170c45954fec3d4d063437750f89802d72743816663664cfe9aa152b4b                   0.1s
 => => resolve docker.io/library/node:16-alpine@sha256:1298fd170c45954fec3d4d063437750f89802d72743816663664cfe9aa152b4b                   0.0s
 => CACHED [2/3] RUN mkdir -p /airbyte                                                                                                    0.0s
 => CACHED [3/3] WORKDIR /airbyte/airbyte-integrations/connector-templates/generator                                                      0.0s
 => exporting to image                                                                                                                    0.1s
 => => exporting layers                                                                                                                   0.0s
 => => exporting manifest sha256:ca0866b5b3c9310c3283c960d2566f330dda6b6e1b4167e059c08711a68f4571                                         0.0s
 => => exporting config sha256:a7e55415067c2e774113a8ed813684f4f252633440215dd6cd00a33b9b9dc86f                                           0.0s
 => => naming to docker.io/airbyte/connector-bootstrap:latest                                                                             0.0s
 => => unpacking to docker.io/airbyte/connector-bootstrap:latest                                                                          0.0s
image "docker.io/airbyte/connector-bootstrap:latest": already exists
While trying to generate a connector, an error occurred on line 30 of generate.sh and the process aborted early.  This is probably a bug.
```

The failing line is the Docker build, and to check what does it do, even when it successfully builds, I've run the relevant code manually and printed the exit code:

```
$ docker build --build-arg UID=502 --build-arg GID=20 . -t airbyte/connector-bootstrap ; echo $?
[+] Building 1.3s (7/7) FINISHED
 => [internal] load .dockerignore                                                                                                         0.0s
 => => transferring context: 2B                                                                                                           0.0s
 => [internal] load build definition from Dockerfile                                                                                      0.0s
 => => transferring dockerfile: 704B                                                                                                      0.0s
 => [internal] load metadata for docker.io/library/node:16-alpine                                                                         1.1s
 => [1/3] FROM docker.io/library/node:16-alpine@sha256:1298fd170c45954fec3d4d063437750f89802d72743816663664cfe9aa152b4b                   0.0s
 => => resolve docker.io/library/node:16-alpine@sha256:1298fd170c45954fec3d4d063437750f89802d72743816663664cfe9aa152b4b                   0.0s
 => CACHED [2/3] RUN mkdir -p /airbyte                                                                                                    0.0s
 => CACHED [3/3] WORKDIR /airbyte/airbyte-integrations/connector-templates/generator                                                      0.0s
 => exporting to image                                                                                                                    0.1s
 => => exporting layers                                                                                                                   0.0s
 => => exporting manifest sha256:ca0866b5b3c9310c3283c960d2566f330dda6b6e1b4167e059c08711a68f4571                                         0.0s
 => => exporting config sha256:a7e55415067c2e774113a8ed813684f4f252633440215dd6cd00a33b9b9dc86f                                           0.0s
 => => naming to docker.io/airbyte/connector-bootstrap:latest                                                                             0.0s
 => => unpacking to docker.io/airbyte/connector-bootstrap:latest                                                                          0.0s
image "docker.io/airbyte/connector-bootstrap:latest": already exists
1
```

So Docker has a non-zero exit code even on a successful build...

### Docker Desktop config

I'm using Docker Desktop 4.16.1 (95567) with

<img width="698" alt="Screenshot 2023-01-18 at 15 32 43" src="https://user-images.githubusercontent.com/38863/213110636-ecc0afa7-38f6-4378-a392-16f62a0c7d89.png">

and engine version v20.10.22 and settings

```
{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "experimental": false,
  "features": {
    "buildkit": true
  }
}
```

I've tried changing all these settings, so far the same behaviour with them all.

## Steps to Reproduce

1. `git clone git@github.com:airbytehq/airbyte.git`
2. `cd airbyte/airbyte-integrations/connector-templates/generator`
3. `./generate.sh`

Note that if I add ` || true` to the end of line 30 to ignore the specific docker exit code, the connector creation runs just fine.

## Are you willing to submit a PR?

Yes.

**Comment by natalyjazzviolin** [comment] 2023-01-18 15:16
Hi @imrehg I was not able to reproduce this issue. I think this error may have something to do with your setup! Closing.

**Closed by natalyjazzviolin** 2023-01-18 15:16 UTC
Labels: type/bug, community, needs-triage, team/use, autoteam
