### ISSUE TITLE
Connector Builder: Incremental sync without time filtering, there is no "No filter" option

### ISSUE THREAD

**Issue by T4Eskynet** [airbytehq/airbyte#29386] opened 2023-08-12 23:38 UTC
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.50.1

### What step the error happened?

Other

### Revelant information

In the Connector Builder UI, The documentation states that there is a "No Filter" option for [Incremental sync without time filtering](https://docs.airbyte.com/connector-development/connector-builder-ui/incremental-sync/?_gl=1*15kmatp*_gcl_au*MTc2MjI4OTQwNS4xNjg5NjExOTY5#incremental-sync-without-time-filtering)

However, there is no such option in the UI. 

![Screenshot 2023-08-12 193506](https://github.com/airbytehq/airbyte/assets/67676142/47bd5376-256d-4cc8-ac5d-f9c82759aa4a)

My API is sorted from newest to oldest records, and it only manages to synchronize the records in the first run, then it fails to synchronize the next records in the next runs, it says 0 sync.

**Comment by girarda** [comment] 2023-11-15 18:42
Closing because I can't reproduce. "No filter" is an option. I recommend upgrading to the latest version of the platform. Feel free to re-open if it doesn't solve your problem
<img width="645" alt="Screenshot 2023-11-15 at 10 41 45 AM" src="https://github.com/airbytehq/airbyte/assets/1451943/ced7d315-1d3a-4e65-88e8-8bad89549abb">

**Closed by girarda** 2023-11-15 18:42 UTC
Labels: type/bug, area/platform, community, team/extensibility, team/platform-compose, team/platform-move, autoteam, area/connector-builder
