### ISSUE TITLE
Sync hangs with error: ScheduleActivityTaskCommandAttributes.Input exceeds size limit.

### ISSUE THREAD

**Issue by alexnikitchuk** [airbytehq/airbyte#16236] opened 2022-09-01 17:32 UTC
## Environment
- **Airbyte version**:  0.40.3
- **OS Version / Instance**: Amazon Linux 2 AMI,  AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: MySQL 0.6.6 
- **Destination Connector and version**: Redshift 0.3.47 
- **Step where error happened**: Sync job

## Current Behavior
Initial sync hanged with strange error:
```
Additional Failure Information: ScheduleActivityTaskCommandAttributes.Input exceeds size limit.
```
But there are no other logs in the sync logs.
Data successfully synced into the destination but looks like state was not committed properly.
The only relevant issue I found related to the error message https://community.temporal.io/t/what-is-the-best-way-to-exchange-large-amounts-of-data-between-activities-without-running-into-complete-result-exceeds-size-limit-error/2536

## Expected Behavior
Sync successfully completed

## Steps to Reproduce
1. Setup connection between source and destination and trigger sync
2. Wait until it completes

## Are you willing to submit a PR?
Nope

**Comment by marcosmarxm** [comment] 2022-09-05 20:26
@alexnikitchuk can you share the complete log file?

**Comment by alexnikitchuk** [comment] 2022-09-06 07:20
@marcosmarxm unfortunately it is lost, but I've managed to fix it by increasing Temporal `BlobSizeLimit` to 20Mb using config:
```
limit.blobSize.error:
- value: 20971520
  constraints: {}
```

**Comment by marcosmarxm** [comment] 2022-09-06 13:18
@alexnikitchuk I see. I'll close the issue because is not possible to reproduce it.

**Closed by marcosmarxm** 2022-09-06 13:18 UTC
Labels: type/bug, community, needs-triage, team/use, autoteam

**Comment by alexnikitchuk** [comment] 2022-09-06 15:29
hey @marcosmarxm I've found the log 
[logs-1.txt.zip](https://github.com/airbytehq/airbyte/files/9498436/logs-1.txt.zip)

**Comment by dimoschi** [comment] 2023-03-25 21:33
> @marcosmarxm unfortunately it is lost, but I've managed to fix it by increasing Temporal `BlobSizeLimit` to 20Mb using config:
> 
> ```
> limit.blobSize.error:
> - value: 20971520
>   constraints: {}
> ```

How/Where did you set this variable? I'm running Airbyte using `docker compose` inside a VM. Thanks in advance.

**Comment by alexnikitchuk** [comment] 2023-03-26 15:44
> > @marcosmarxm unfortunately it is lost, but I've managed to fix it by increasing Temporal `BlobSizeLimit` to 20Mb using config:
> > ```
> > limit.blobSize.error:
> > - value: 20971520
> >   constraints: {}
> > ```
> 
> How/Where did you set this variable? I'm running Airbyte using `docker compose` inside a VM. Thanks in advance.

there should be a file `temporal/dynamicconfig/development.yaml` in the directory where you start Airbyte
