### ISSUE TITLE
fix cloud workspace and slug naming inconsistencies

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#9125] opened 2021-12-27 16:11 UTC
address https://github.com/airbytehq/oncall/issues/67

**Comment by lmossman** [comment] 2022-01-18 23:05
I opened up this issue without realizing one already existed for this problem: https://github.com/airbytehq/airbyte/issues/9524

**Comment by timroes** [comment] 2022-01-21 09:15
Duplicate of #9524

**Closed by timroes** 2022-01-21 09:15 UTC
Labels: type/bug, area/platform, airbyte-cloud
