### ISSUE TITLE
🐛 Source Woocommerce: domain extension issue

### ISSUE THREAD

**Issue by donuthack** [airbytehq/airbyte#10029] opened 2022-02-03 09:25 UTC
## Environment
- **Airbyte version**:  0.19.0-alpha
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker
- **Source Connector and version**: Woocommerce v0.1.0-rc1
- **Destination Connector and version**: Local CSV v0.2.8
- **Severity**: High
- **Step where error happened**: Setup new connection

## Current Behavior
I have tried to connect a shop which has not "com" domain and connector added ".com" after my domain which is not existing. So i just deleted it from "checking connection" function and delete https and .com from "url base" function.

## Expected Behavior
I expected shop will pass a site with different domain than .com 

## Logs
ConnectionError(MaxRetryError("HTTPSConnectionPool(host='xn-brdogram.com', port=443): Max retries exceeded with url: /wp-json/wc/v3/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2bb68df150>: Failed to establish a new connection: [Errno -2] Name or service not known'))"))

## Steps to Reproduce
1. add shop with non .com domain site

**Comment by alafanechere** [comment] 2022-02-03 18:38
Hi @donuthack, thank you for opening this issue! This connector is unfortunately not maintained by our team since we do not have a sandbox Woocommerce shop. This is why we do not publish this connector anymore.

@jsewawilson do you have an idea of the root cause of this problem?

**Comment by artem1205** [comment] 2022-11-25 18:41
fixed in PR  #10529

**Closed by artem1205** 2022-11-25 18:41 UTC
Labels: type/bug, area/connectors, community, connectors/source/woocommerce, team/connectors-python, autoteam
