### ISSUE TITLE
Hidden OAuth fields showing in UI

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#18558] opened 2022-10-27 16:20 UTC
Current Behavior: OAuth fields are rendering in the UI rather than the OAuth button (this bug just started in the last few days).  If you select "OAuth" from the dropdown, they disappear and the button appears.  There also may be a timing element to it, because _sometimes_ it does render correctly.  

I've seen this most frequently with Google Sheets, Mailchimp, and Salesforce.

![Screen Shot 2022-10-25 at 5.33.46 PM.png](https://images.zenhubusercontent.com/6269740067dc6b70dd128801/b2090385-4cbd-46fa-9339-1b9a5b7a9e2b)

![Screen Shot 2022-10-27 at 12.12.52 PM.png](https://images.zenhubusercontent.com/6269740067dc6b70dd128801/531efcde-1860-434c-be43-c6b79239916a)

Expected behavior: these should never be displayed in the UI.  The OAuth button should always be displayed for this scenario.

**Comment by sherifnada** [comment] 2022-10-27 16:49
@tealjulia are you able to identify the commit which caused this to start happening? the extensibility team didn't make any changes to this area recently

**Comment by tealjulia** [comment] 2022-10-27 16:51
It _may_ have been [this](https://github.com/airbytehq/airbyte/pull/17965) but I'm not positive.  However I chatted with @timroes and he thinks it's been around since before then.  I don't recall seeing the bug until this week.

**Comment by timroes** [comment] 2022-10-27 18:46
I was able to reproduce this on prod before this was live so I'm pretty sure it wasn't that change that caused it and likely always present. Given that it includes a timing component somehow it's likely we never noticed. Also changing connector types has always had some bugs in it, since we carry on the field values, which I believe is the reason here.

**Comment by timroes** [comment] 2022-11-16 08:43
This should be fixed by the recent changes we made to the `useAuthentication` hook. I'm no longer able to run into this. Thus will close it. Please comment if anyone still can reproduce this.

**Closed by timroes** 2022-11-16 08:43 UTC
Labels: type/bug, team/extensibility, team/frontend
