### ISSUE TITLE
Run check connection before running a sync or discover

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2014] opened 2021-02-09 17:34 UTC
## Tell us about the problem you're trying to solve
The saved credentials we use to connect to a given connector could expire, lose their permissions, or get invalidated out of band. 

## Describe the solution you’d like
I would like to run an explicit check operation before every sync to verify this is not the case.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368147190118) by [Unito](https://www.unito.io)

**Comment by evantahler** [comment] 2022-05-16 23:56
Duplicate of https://github.com/airbytehq/airbyte/issues/12281

**Closed by evantahler** 2022-05-16 23:56 UTC
Labels: type/enhancement, team/sources-dx
