### ISSUE TITLE
Preserve the case of table and field names in the source case (mysql -> postgres)

### ISSUE THREAD

**Issue by Aleksandr-yask** [airbytehq/airbyte#3435] opened 2021-05-17 08:34 UTC
## Tell us about the problem you're trying to solve
When I transfer data from mysql to postgres the field and table names are converted to lower case

## Describe the solution you’d like
Preserve the case of table and field names in the source case. For example TableName now convert to tablename

**Comment by ChristopheDuong** [comment] 2021-05-17 09:20
This is a limitation caused by Postgres destination:

https://docs.airbyte.io/integrations/destinations/postgres#notes-about-postgres-naming-conventions

    - Quoting an identifier also makes it case-sensitive, whereas unquoted names are always folded to lower case
    - If you want to write portable applications you are advised to always quote a particular name or never quote it.

or the original source: https://www.postgresql.org/docs/9.0/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

    Quoting an identifier also makes it case-sensitive, whereas unquoted names are always folded to lower case. For example, the identifiers FOO, foo, and "foo" are considered the same by PostgreSQL, but "Foo" and "FOO" are different from these three and each other. (The folding of unquoted names to lower case in PostgreSQL is incompatible with the SQL standard, which says that unquoted names should be folded to upper case. Thus, foo should be equivalent to "FOO" not "foo" according to the standard. If you want to write portable applications you are advised to always quote a particular name or never quote it.)

Since TableName now convert to tablename, the following SQL queries are valid:
```
select * from TableName

select * from tablename
```

BTW, if you forced the capitalization, you would have to always use quote and the previous SQL queries would not be valid anymore:
```
select * from "TableName"
```
(forcing capitalization is not currently possible with airbyte yet. When custom DBT transformations is released in the short term, you should be able to do so. In the longer term, we could imagine the Airbyte UI allowing to customize final table/column names too but thatś not on the roadmap yet)

**Closed** 2021-05-17 09:24 UTC
Labels: type/enhancement
