### ISSUE TITLE
connectors-ci: huge slowdown in gradle task run following Dagger engine upgrade to > 0.5.3

### ISSUE THREAD

**Issue by alafanechere** [airbytehq/airbyte#27970] opened 2023-07-05 11:10 UTC
I observe a slowdown in running connectors test for our Java connectors.

## Before slowdown:
[A nightly run at  2023-07-04T02:11:03.813176 UTC](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/nightly_builds/master/1688430030/b78762f641b9e852cfa5fbcc5b4180445b3b4581/destination-s3/0.5.1/output.html)
* [Dagger UI](https://dagger.cloud/runs/87df094f-0aa7-4254-a781-6da0a8e5857b)
* Build connector tar duration: 02mn56s  [Gradle Scan](https://gradle.com/s/5swqoeanckv6s)
* Integration test run: 8mn54

## After slowdown
[A connector test run on master at 2023-07-05T10:44:18.942748 UTC
](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/manual/master/1688552057/6a0aec7f3976793f9c6d8e22f27855d32fa687c1/destination-s3/0.5.1/output.html)
* [Dagger UI](https://alpha.dagger.cloud/runs/52a4094c-8bbd-406a-9a28-34530d89eea3)
* Build connector tar duration: 10mn20s [Gradle Scan](https://gradle.com/s/mea5molamhl6k) 
* Integration test run: 17mn10s

## Local run
I can locally run the build tar operation without dagger cache in 6mn.

## Hypothesis:
* A regression introduced by upgrading to Dagger 0.6.2: in the [first run on 0.6.2](https://storage.cloud.google.com/airbyte-ci-reports-multi/airbyte-ci/connectors/test/nightly_builds/augustin_connectors-ci_unpin-dagger-cli/1688048053/405b5148ccbb34b567dfc51bec14c716003e8051/destination-s3/0.5.1/output.html) building the tar file took 10mn.

**Comment by alafanechere** [comment] 2023-07-05 15:58
Hey @gerhard , don't you have access to our engine logs? I thought it was something Erik implemented.
To run the same pipeline locally you should follow the instructions [here](https://github.com/airbytehq/airbyte/blob/master/tools/ci_connector_ops/ci_connector_ops/pipelines/README.md#L1), but you won't likely be able to run it as you'd need access to our secret store which we're not currently sharing.

**Comment by gerhard** [comment] 2023-07-05 16:04
OK, so running the pipeline locally is impractical. Will stop trying to figure it out locally.

I know that we have some Engine logs & telemetry too, but I am not familiar with how it all fits together. Let me see if I can figure it out.

**Comment by gerhard** [comment] 2023-07-05 16:16
I can see all logs for all your Dagger Engines. I am trying to filter the logs by specific Engine ID. Looking for the Engine IDs used in the two runs.

**Comment by gerhard** [comment] 2023-07-05 18:16
For run `52a4094c-8bbd-406a-9a28-34530d89eea3` which uses Dagger Engine `v0.6.2`, I am **not** able to find the Engine logs. FWIW, `dagger.io/engine: eaf5c91a137e`. That is the slow run where `exec ./gradlew --no-daemon --scan --build-cache :airbyte-integrations:connectors:destination-s3:distTar -x airbyteDocker` takes `1537.22s`.

For run `87df094f-0aa7-4254-a781-6da0a8e5857b`, which uses Dagger Engine `v0.5.3`, I am able to find the Engine logs. FWIW, `dagger.io/engine: dagger-engine-pv6rn`. That is the good run where `exec ./gradlew --no-daemon --scan --build-cache :airbyte-integrations:connectors:destination-s3:distTar -x airbyteDocker` takes `504.19s`.

While looking at all the Engine logs, I have noticed that some Engines have 16 CPUs, while others have 32CPUs. Since I am unable to find any logs that confirm the configuration of `dagger.io/engine: eaf5c91a137e`, I cannot verify its configuration.

Stopping here for today.

**Comment by alafanechere** [comment] 2023-07-05 18:44
@gerhard If think this [run](https://alpha.dagger.cloud/runs/78b36068-504b-4020-81aa-4c9ff927b028) uses 16 CPU  and the `distTar` step took 439.24s

**Comment by gerhard** [comment] 2023-07-05 18:50
OK!

How difficult would it be to make `Test Pipeline - destination-s3` run locally, without access to your secret store?

**Comment by alafanechere** [comment] 2023-07-05 21:42
@gerhard Conor is working out an access for you now.
Just for context: I wanted to upgrade to a later version to get less aggressive error message truncation. The error messages looked better on 0.6.2, but this performance problem led me to revert.

**Comment by gerhard** [comment] 2023-07-06 11:07
That is helpful, thank you!

Being able to run the pipeline locally, without requiring access to your secret store, would most certainly help with ruling out environment-specific issues. It will also allow us to test local Dagger changes, in much tighter loops, which will help us help you quicker.

**Comment by evantahler** [comment] 2023-07-06 16:07
@gerhard - @alafanechere will be on vacation next week.  I'll help out as needed - just keep replying to this issue

**Comment by gerhard** [comment] 2023-07-06 18:53
I continued digging into this & I find it suspicious that the fast builds are running on engines that start with `dagger-engine-`, or `dev-dagger-engine-`, while the slow builds are running on engines that are names with 12 random alphanumeric characters, e.g. `eaf5c91a137e `. The random naming suggests to me that this is an auto-provisioned Engine, running in Docker, and is not a standalone Engine.

Would it be possible to re-run these tests in Dagger Engine `v0.6.3`, then share the Cloud run ID & the engine name? For example, Cloud run ID `87df094f-0aa7-4254-a781-6da0a8e5857b` ran against `dagger-engine-pv6rn` which is `v0.5.3`.

**Comment by gerhard** [comment] 2023-07-06 19:04
One thing that I really missed in troubleshooting this is the ability to re-run the problematic pipeline in an environment with profiling enabled for the Dagger Engine. If I could run this specific test in a lab environment, that would really speed things up since I could easily add all the instrumentation that I don't have.

For starters, I would have all system metrics in great detail, especially for the network layer which usually introduces a lot of variability. Disk & memory are my second suspects.

Next, I would have continuous profiling running. eBPF makes this a lot easier than it used to be. Usually, installing the right tool provides all the visibility that I would need to understand where in the stack the problem is coming from.

While I am not suggesting that we should install all these things in your environment, I would very much like to run the problematic test in my lab environment. Is that feasible?

**Comment by marcosnils** [comment] 2023-07-07 02:59
> I continued digging into this & I find it suspicious that the fast builds are running on engines that start with `dagger-engine-`, or `dev-dagger-engine-`, while the slow builds are running on engines that are names with 12 random alphanumeric characters, e.g. `eaf5c91a137e `. The random naming suggests to me that this is an auto-provisioned Engine, running in Docker, and is not a standalone Engine.

:wave: Marcos from Dagger here. @evantahler @alafanechere, @gerhard's conclusion seems to be correct. Looking at your PR to bump the engine (https://github.com/airbytehq/airbyte/pull/28008/files#diff-8bba74a834b43cc4f45b74d9e25f898d291bc2d8c537e423325e4da1487efaa1L98), seems like you're accidentally removing the ` _EXPERIMENTAL_DAGGER_RUNNER_HOST` env variable which is required in order for Dagger to use your own provisioned runners. Bringing back that variable should resolve this issue.

**Comment by gerhard** [comment] 2023-07-07 11:59
Another possibility is that you are specifying these env vars directly on the self-hosted runner, which would make sense to me. It would be worth double-checking that this is the case, since the run with `v0.6.2` suggests otherwise.

Now that I am able to run this locally, I will perform one run on `v0.5.3`, and another one on `v0.6.3`, and compare the results.

**Comment by alafanechere** [comment] 2023-07-07 14:07
Thank you for the investigation! I'll try keeping `_EXPERIMENTAL_DAGGER_RUNNER_HOST`. I thought it had to be set to use a custom Dagger engine version (the one we  originally pinned) and removed it because we want to use the official releases. No problem to set it back there, I'll try again.

**Comment by alafanechere** [comment] 2023-07-07 14:57
@gerhard @marcosnils setting this env var back indeed solved the performance issue! https://github.com/airbytehq/airbyte/actions/runs/5487610482/jobs/9999291214

**Comment by gerhard** [comment] 2023-07-07 15:24
Great to know that adding back the `_EXPERIMENTAL_DAGGER_RUNNER_HOST` env var back fixed this for you! Setting this env var bypasses the auto-provisioning mechanism, and uses an Engine which is already provisioned, which is what we want in this case.

I would suggest to add `_EXPERIMENTAL_DAGGER_RUNNER_HOST` on the self-hosted runner, since that is where the Engine integration is configured. For example, if the engine communication changed to a TCP socket (instead of the current UNIX socket), then the change would need to happen in the K8s config and also in the workflow config. I think of this as weak [encapsulation](https://en.wikipedia.org/wiki/Encapsulation_(computer_programming)). The workflow configs should be as simple as possible, and keeping infra-specific concerns such as this one in infra seems like a good idea to me.

**Comment by alafanechere** [comment] 2023-07-07 16:38
Thank you for the suggestion @gerhard! We'll do it!
Not sure it's totally related but I'm struggling with running a dagger-in-dagger use case we are trying to introduce (e.g https://github.com/airbytehq/airbyte/pull/28000/commits/f5e9b97992434a761e8edd7facb5d9b8a64db0bf) . Is it the right approach?  In this context the `cat_container` is running dagger code and should share the same engine as `airbyte-ci`. The implementation on https://github.com/airbytehq/airbyte/pull/28000/ works locally.

**Comment by jpadams** [comment] 2023-07-13 03:37
> Great to know that adding back the `_EXPERIMENTAL_DAGGER_RUNNER_HOST` env var back fixed this for you! Setting this env var bypasses the auto-provisioning mechanism, and uses an Engine which is already provisioned, which is what we want in this case.
> 
> I would suggest to add `_EXPERIMENTAL_DAGGER_RUNNER_HOST` on the self-hosted runner, since that is where the Engine integration is configured. For example, if the engine communication changed to a TCP socket (instead of the current UNIX socket), then the change would need to happen in the infra/K8s config and also in the workflow config. I think of this as weak [encapsulation](https://en.wikipedia.org/wiki/Encapsulation_(computer_programming)). The workflow configs should be as simple as possible, and keeping infra-specific concerns such as this one in infra seems like a good idea to me.

@gerhard Please comment on whether Airbyte can now upgrade to v0.6.3 of engine, cli, python sdk.
We'd like them to pick up some logging improvements that have landed.

cc @cpdeethree @jlongtine @kpenfound @aluzzardi

**Comment by gerhard** [comment] 2023-07-14 17:00
For now, I would recommend sticking with Engine & CLI [`v0.6.2`](https://github.com/dagger/dagger/releases/tag/v0.6.2), which means Python SDK [`v0.6.2`](https://github.com/dagger/dagger/releases/tag/sdk%2Fpython%2Fv0.6.2). We would like to get these issues fixed before recommending an upgrade to a newer version:
- https://github.com/dagger/dagger/issues/5433
- https://github.com/dagger/dagger/issues/5450

cc @vito @sipsma

**Closed** 2023-07-19 22:24 UTC
Labels: team/connector-ops, CI/P0
