### ISSUE TITLE
Mongodb TLS Connection Problem

### ISSUE THREAD

**Issue by abelncm** [airbytehq/airbyte#35657] opened 2024-02-27 12:45 UTC
### Connector Name

source-mongodb-v2

### Connector Version

1.2.13

### What step the error happened?

Configuring a new connector

### Relevant information

I upgraded to the latest version of mongodb connector, and i can no longer connect to my self hosted mongo instance. Error:

Configuration check failed
Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=SOME-IP:27017, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketWriteException: Exception sending message}, caused by {javax.net.ssl.SSLHandshakeException: Remote host terminated the handshake}, caused by {java.io.EOFException: SSL peer shut down incorrectly}}]

I cannot even disable TLS in the connection string (?tls=false)

Please, my work is on hold because of this!

### Relevant log output

```shell
2024-02-27 12:38:31 platform > Docker volume job log path: /tmp/workspace/52b9a84b-be98-49f5-8918-9921bb357a9e/0/logs.log
2024-02-27 12:38:31 platform > Executing worker wrapper. Airbyte version: 0.50.54
2024-02-27 12:38:31 platform > Attempt 0 to save workflow id for cancellation
2024-02-27 12:38:31 platform > 
2024-02-27 12:38:31 platform > ----- START CHECK -----
2024-02-27 12:38:31 platform > 
2024-02-27 12:38:31 platform > Using default value for environment variable SIDECAR_KUBE_CPU_LIMIT: '2.0'
2024-02-27 12:38:31 platform > Using default value for environment variable SOCAT_KUBE_CPU_LIMIT: '2.0'
2024-02-27 12:38:31 platform > Using default value for environment variable SIDECAR_KUBE_CPU_REQUEST: '0.1'
2024-02-27 12:38:31 platform > Using default value for environment variable SOCAT_KUBE_CPU_REQUEST: '0.1'
2024-02-27 12:38:31 platform > Using default value for environment variable LAUNCHDARKLY_KEY: ''
2024-02-27 12:38:31 platform > Checking if airbyte/source-mongodb-v2:1.2.12 exists...
2024-02-27 12:38:31 platform > airbyte/source-mongodb-v2:1.2.12 was found locally.
2024-02-27 12:38:31 platform > Creating docker container = source-mongodb-v2-check-52b9a84b-be98-49f5-8918-9921bb357a9e-0-ezcoi with resources io.airbyte.config.ResourceRequirements@129b4057[cpuRequest=,cpuLimit=,memoryRequest=,memoryLimit=,additionalProperties={}] and allowedHosts null
2024-02-27 12:38:31 platform > Preparing command: docker run --rm --init -i -w /data/52b9a84b-be98-49f5-8918-9921bb357a9e/0 --log-driver none --name source-mongodb-v2-check-52b9a84b-be98-49f5-8918-9921bb357a9e-0-ezcoi --network host -v airbyte_workspace:/data -v /tmp/airbyte_local:/local -e DEPLOYMENT_MODE=OSS -e WORKER_CONNECTOR_IMAGE=airbyte/source-mongodb-v2:1.2.12 -e AUTO_DETECT_SCHEMA=true -e LAUNCHDARKLY_KEY= -e SOCAT_KUBE_CPU_REQUEST=0.1 -e SOCAT_KUBE_CPU_LIMIT=2.0 -e FIELD_SELECTION_WORKSPACES= -e USE_STREAM_CAPABLE_STATE=true -e AIRBYTE_ROLE=dev -e WORKER_ENVIRONMENT=DOCKER -e APPLY_FIELD_SELECTION=false -e WORKER_JOB_ATTEMPT=0 -e OTEL_COLLECTOR_ENDPOINT=http://host.docker.internal:4317 -e FEATURE_FLAG_CLIENT=config -e AIRBYTE_VERSION=0.50.54 -e WORKER_JOB_ID=52b9a84b-be98-49f5-8918-9921bb357a9e airbyte/source-mongodb-v2:1.2.12 check --config source_config.json
2024-02-27 12:38:31 platform > Reading messages from protocol version 0.2.0
2024-02-27 12:38:33 platform > 2024-02-27 12:38:33 INFO i.a.i.s.m.MongoDbSource(main):47 - starting source: class io.airbyte.integrations.source.mongodb.MongoDbSource
2024-02-27 12:38:33 platform > 2024-02-27 12:38:33 INFO i.a.c.i.b.IntegrationCliParser(parseOptions):126 - integration args: {check=null, config=source_config.json}
2024-02-27 12:38:33 platform > 2024-02-27 12:38:33 INFO i.a.c.i.b.IntegrationRunner(runInternal):132 - Running integration: io.airbyte.integrations.source.mongodb.MongoDbSource
2024-02-27 12:38:33 platform > 2024-02-27 12:38:33 INFO i.a.c.i.b.IntegrationRunner(runInternal):133 - Command: CHECK
2024-02-27 12:38:33 platform > 2024-02-27 12:38:33 INFO i.a.c.i.b.IntegrationRunner(runInternal):134 - Integration config: IntegrationConfig{command=CHECK, configPath='source_config.json', catalogPath='null', statePath='null'}
2024-02-27 12:38:34 platform > 2024-02-27 12:38:34 WARN c.n.s.JsonMetaSchema(newValidator):278 - Unknown keyword groups - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by evantahler** [comment] 2024-03-22 16:08
Closing as duplicate of https://github.com/airbytehq/airbyte/issues/33452 - join us over there!

**Closed by evantahler** 2024-03-22 16:08 UTC
Labels: type/bug, area/connectors, community, needs-triage, autoteam, team/db-dw-sources, team/use
