### ISSUE TITLE
Add limit for JDBC based source connectors

### ISSUE THREAD

**Issue by mcfuhrt** [airbytehq/airbyte#12297] opened 2022-04-23 12:59 UTC
## Tell us about the problem you're trying to solve
Sometimes the amount of data to be synchronised is so large that the initial sync can take several hours. Sometimes during a long sync, the database may shut down or become unavailable during replication times. 

If models are to be created with dbt, it is necessary that a sync has already been successfully completed so that the data schema is known to the analytics engineers.

For these cases, it would be helpful to be able to specify a limit for the select command. 

## Describe the solution you’d like
Specify a limit in the configuration. For incremental syncs, it would be good if the initial full refresh is sorted in ascending order according to the configured cursor field to prevent the full refresh from only fetching "limit" rows, which would not correspond to the necessary sorting for the incremental sync.

## Describe the alternative you’ve considered or used
Sync as before

## Are you willing to submit a PR?
Yes

**Comment by marcosmarxm** [comment] 2022-04-27 19:53
Closing as duplicate of https://github.com/airbytehq/airbyte/issues/4314

**Closed by marcosmarxm** 2022-04-27 19:53 UTC
Labels: type/enhancement, community, needs-triage, team/use, autoteam
