### ISSUE TITLE
A deleted connection still causes retries

### ISSUE THREAD

**Issue by n0rritt** [airbytehq/airbyte#1872] opened 2021-01-28 01:00 UTC
## Expected Behavior
When I delete a connection that is in a `running` state, data synchronization between the source and the destination should stop and no further syncs should be triggered anymore.

## Current Behavior
The connection is deleted (i.e. disappears) in the front-end but when I export the configuration I still see the deleted connection details in `airbyte_config/SOURCE_CONNECTION.yaml`. What is more troublesome is that when I create a new connection (to a different source), airbyte still tries to sync between the source and destination of the deleted connection, spawning docker containers that run unnoticed by end-users and consuming resources.

UPDATE: This only seems to be retries (3) for failed syncs

## Steps to Reproduce
1. create connection from Google Sheets to Redshift (source should have large amount of rows so that the connection keeps running)
1. delete the running connection
1. check running docker containers and system processes, the sync should still be running
1. stop the source and destination docker containers, system resources should be freed by that
1. create a new connection in Airbyte frontend to another Google Sheet document, but triggered manually, the new connection should not start any processes
1. however checking running docker container and inspecting the logs of `airbyte/destination-redshift` container will show that a sync is happening for the deleted connection

## Severity of the bug for you
Low - This causes system resources to be blocked on our side when users are trying to import Google Sheets that are to big, but they cannot delete or undo the sync. But for now we can mitigate the problem by manually killing the processes and avoiding large data imports.

## Airbyte Version
0.14.1-alpha

## Additional context
* Instance: AWS EC2 Ubuntu 20.04 [ami-0502e817a62226e03](https://eu-central-1.console.aws.amazon.com/ec2/v2/home?region=eu-central-1#Images:imageId=ami-0502e817a62226e03)
* Docker: version 19.03.11, build dd360c7 (snap package)
* docker-compose: docker-compose version 1.26.2, build eefe0d31

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368209893767) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment] 2021-01-28 01:54
@sherifnada does this mean we should just filter sync job retries by the existence of the source and destination?

**Comment by jrhizor** [comment] 2021-02-11 20:19
Our workflow engine work should address this.

**Comment by davinchia** [comment] 2021-04-22 14:15
@jrhizor since we have temporal, can this be closed?

**Comment by jrhizor** [comment] 2021-04-22 16:15
I'm not 100% sure. Our approach for it changed since I posted that comment. 

We'll need to run the steps posted to try to reproduce.

**Comment by cgardens** [comment] 2022-06-29 23:20
this should be fixed now.

**Closed by cgardens** 2022-06-29 23:20 UTC
Labels: type/bug, priority/medium, team/oss
