### ISSUE TITLE
Setting up MSSQL connection fails with a source with many (850+) tables

### ISSUE THREAD

**Issue by MarvinSchenkel** [airbytehq/airbyte#4546] opened 2021-07-05 13:42 UTC
## Enviroment
- **Airbyte version**:  example is 0.27.0-alpha
- **OS Version / Instance**: Ubuntu 20.04 on WSL2
- **Deployment**: Docker
- **Source Connector and version**: Microsoft SQL Server (MSSQL) 0.3.2
- **Destination Connector and version**: N/A
- **Severity**: Medium
- **Step where error happened**: Setup new connection

## Current Behavior
I am running into the following error when setting up an MS SQL -> Local CSV connection:
```
Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: Some part of your SQL statement is nested too deeply. Rewrite the query or break it up into smaller queries.
```
Both the source and destination are validated successfully, this error shows up during the analysis of the source schema.
Details:
* Using an Azure Synapse database
* Source contains 850 tables (this is probably the culprit)

## Expected Behavior
I expect being able to setup syncing between the MS SQL tables and my destination.

## Logs
<details>
<summary>LOG</summary> 

```

airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} - Exception in thread "main" com.microsoft.sqlserver.jdbc.SQLServerException: Some part of your SQL statement is nested too deeply. Rewrite the query or break it up into smaller queries.
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:602)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7375)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3206)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.executeQuery(SQLServerPreparedStatement.java:446)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at com.microsoft.sqlserver.jdbc.SQLServerDatabaseMetaData.getColumns(SQLServerDatabaseMetaData.java:756)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at org.apache.commons.dbcp2.DelegatingDatabaseMetaData.getColumns(DelegatingDatabaseMetaData.java:227)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at org.apache.commons.dbcp2.DelegatingDatabaseMetaData.getColumns(DelegatingDatabaseMetaData.java:227)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.lambda$discoverInternal$22(AbstractJdbcSource.java:464)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at io.airbyte.db.jdbc.DefaultJdbcDatabase.bufferedResultSetQuery(DefaultJdbcDatabase.java:70)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at io.airbyte.db.jdbc.StreamingJdbcDatabase.bufferedResultSetQuery(StreamingJdbcDatabase.java:63)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.discoverInternal(AbstractJdbcSource.java:463)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.getTables(AbstractJdbcSource.java:359)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.discover(AbstractJdbcSource.java:161)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:95)
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.a.c.i.LineGobbler(voidCall):85 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} -     at io.airbyte.integrations.source.mssql.MssqlSource.main(MssqlSource.java:123)
airbyte-scheduler   | 2021-07-05 06:55:02 INFO i.a.w.t.TemporalAttemptExecution(lambda$getWorkerThread$2):149 - {job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} - Completing future exceptionally...
airbyte-scheduler   | io.airbyte.workers.WorkerException: Discover job subprocess finished with exit code 1
airbyte-scheduler   |   at io.airbyte.workers.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:90) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
airbyte-scheduler   |   at io.airbyte.workers.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:44) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
airbyte-scheduler   |   at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
airbyte-scheduler   |   at java.lang.Thread.run(Thread.java:832) [?:?]
airbyte-scheduler   | 2021-07-05 06:55:02 INFO i.a.w.t.TemporalAttemptExecution(get):133 - {ActivityId=262dcdbd-ddb8-369c-b108-a8a4781f2c0f, ActivityType=Run, Namespace=default, RunId=23e5c07a-b081-401f-93a4-6b6fb35ff100, TaskQueue=DISCOVER_SCHEMA, WorkflowId=4ade6857-ae50-411f-8eaf-ed0d45dff847, job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} - Stopping cancellation check scheduling...
airbyte-scheduler   | 2021-07-05 06:55:02 WARN i.t.i.s.POJOActivityTaskHandler$POJOActivityImplementation(execute):243 - {ActivityId=262dcdbd-ddb8-369c-b108-a8a4781f2c0f, ActivityType=Run, Namespace=default, RunId=23e5c07a-b081-401f-93a4-6b6fb35ff100, TaskQueue=DISCOVER_SCHEMA, WorkflowId=4ade6857-ae50-411f-8eaf-ed0d45dff847, job_log_path=/tmp/workspace/a982faeb-98bc-4408-ae47-8f46321f1369/0/logs.log} - Activity failure. ActivityId=262dcdbd-ddb8-369c-b108-a8a4781f2c0f, activityType=Run, attempt=1
airbyte-scheduler   | java.util.concurrent.ExecutionException: io.airbyte.workers.WorkerException: Discover job subprocess finished with exit code 1
airbyte-scheduler   |   at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
airbyte-scheduler   |   at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063) ~[?:?]
airbyte-scheduler   |   at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:131) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
airbyte-scheduler   |   at io.airbyte.workers.temporal.DiscoverCatalogWorkflow$DiscoverCatalogActivityImpl.run(DiscoverCatalogWorkflow.java:107) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
airbyte-scheduler   |   at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
airbyte-scheduler   |   at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
airbyte-scheduler   |   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
airbyte-scheduler   |   at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
airbyte-scheduler   |   at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:277) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:216) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:181) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:192) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
airbyte-scheduler   |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
airbyte-scheduler   |   at java.lang.Thread.run(Thread.java:832) [?:?]
airbyte-scheduler   | Caused by: io.airbyte.workers.WorkerException: Discover job subprocess finished with exit code 1
airbyte-scheduler   |   at io.airbyte.workers.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:90) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
airbyte-scheduler   |   at io.airbyte.workers.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:44) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
airbyte-scheduler   |   at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
airbyte-scheduler   |   ... 1 more
airbyte-scheduler   | 2021-07-05 06:55:02 ERROR i.t.i.s.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor(logWorkflowExecutionException):323 - {Namespace=default, RunId=23e5c07a-b081-401f-93a4-6b6fb35ff100, TaskQueue=DISCOVER_SCHEMA, WorkflowId=4ade6857-ae50-411f-8eaf-ed0d45dff847, WorkflowType=DiscoverCatalogWorkflow} - Workflow execution failure WorkflowId=4ade6857-ae50-411f-8eaf-ed0d45dff847, RunId=23e5c07a-b081-401f-93a4-6b6fb35ff100, WorkflowType=DiscoverCatalogWorkflow
airbyte-scheduler   | io.temporal.failure.ActivityFailure: scheduledEventId=5, startedEventId=6, activityType='Run', activityId='262dcdbd-ddb8-369c-b108-a8a4781f2c0f', identity='1@878a1928a7e4', retryState=RETRY_STATE_MAXIMUM_ATTEMPTS_REACHED
airbyte-scheduler   |   at java.lang.Thread.getStackTrace(Thread.java:1598) ~[?:?]
airbyte-scheduler   |   at io.temporal.internal.sync.ActivityStubBase.execute(ActivityStubBase.java:48) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.sync.ActivityInvocationHandler.lambda$getActivityFunc$0(ActivityInvocationHandler.java:59) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.sync.ActivityInvocationHandlerBase.invoke(ActivityInvocationHandlerBase.java:65) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at com.sun.proxy.$Proxy40.run(Unknown Source) ~[?:?]
airbyte-scheduler   |   at io.airbyte.workers.temporal.DiscoverCatalogWorkflow$WorkflowImpl.run(DiscoverCatalogWorkflow.java:70) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
airbyte-scheduler   |   at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
airbyte-scheduler   |   at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
airbyte-scheduler   |   at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
airbyte-scheduler   |   at java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
airbyte-scheduler   |   at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation$RootWorkflowInboundCallsInterceptor.execute(POJOWorkflowImplementationFactory.java:289) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.sync.POJOWorkflowImplementationFactory$POJOWorkflowImplementation.execute(POJOWorkflowImplementationFactory.java:253) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.sync.WorkflowExecuteRunnable.run(WorkflowExecuteRunnable.java:52) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.sync.SyncWorkflow.lambda$start$0(SyncWorkflow.java:126) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.sync.CancellationScopeImpl.run(CancellationScopeImpl.java:101) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.sync.WorkflowThreadImpl$RunnableWrapper.run(WorkflowThreadImpl.java:107) [temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
airbyte-scheduler   |   at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
airbyte-scheduler   |   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
airbyte-scheduler   |   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
airbyte-scheduler   |   at java.lang.Thread.run(Thread.java:832) [?:?]
airbyte-scheduler   | Caused by: io.temporal.failure.ApplicationFailure: message='io.airbyte.workers.WorkerException: Discover job subprocess finished with exit code 1', type='java.util.concurrent.ExecutionException', nonRetryable=false
airbyte-scheduler   |   at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395) ~[?:?]
airbyte-scheduler   |   at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2063) ~[?:?]
airbyte-scheduler   |   at io.airbyte.workers.temporal.TemporalAttemptExecution.get(TemporalAttemptExecution.java:131) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
airbyte-scheduler   |   at io.airbyte.workers.temporal.DiscoverCatalogWorkflow$DiscoverCatalogActivityImpl.run(DiscoverCatalogWorkflow.java:107) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
airbyte-scheduler   |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method:0) ~[?:?]
airbyte-scheduler   |   at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
airbyte-scheduler   |   at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
airbyte-scheduler   |   at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[?:?]
airbyte-scheduler   |   at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityInboundCallsInterceptor.execute(POJOActivityTaskHandler.java:277) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.sync.POJOActivityTaskHandler$POJOActivityImplementation.execute(POJOActivityTaskHandler.java:216) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.sync.POJOActivityTaskHandler.handle(POJOActivityTaskHandler.java:181) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:192) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.worker.ActivityWorker$TaskHandlerImpl.handle(ActivityWorker.java:154) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at io.temporal.internal.worker.PollTaskExecutor.lambda$process$0(PollTaskExecutor.java:73) ~[temporal-sdk-1.0.4.jar:?]
airbyte-scheduler   |   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
airbyte-scheduler   |   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
airbyte-scheduler   |   at java.base/java.lang.Thread.run(Thread.java:832) ~[?:?]
airbyte-scheduler   | Caused by: io.temporal.failure.ApplicationFailure: message='Discover job subprocess finished with exit code 1', type='io.airbyte.workers.WorkerException', nonRetryable=false
airbyte-scheduler   |   at io.airbyte.workers.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:90) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
airbyte-scheduler   |   at io.airbyte.workers.DefaultDiscoverCatalogWorker.run(DefaultDiscoverCatalogWorker.java:44) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
airbyte-scheduler   |   at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:146) ~[io.airbyte-airbyte-workers-0.27.0-alpha.jar:?]
airbyte-scheduler   |   at java.base/java.lang.Thread.run(Thread.java:832) ~[?:?]

```

</details>

## Steps to Reproduce
1. Setup a new connection between an MS SQL source containing many tables (850 in my example) and a Local CSV, even if my source has 850 tables

## Are you willing to submit a PR?
Not at this stage. I am closely following this project and hope to use it on a day-to-day basis as soon as Azure support comes in. I would definitely contribute if I use Airbyte on a daily basis.

**Comment by marcosmarxm** [comment] 2021-07-07 02:33
Thanks for opening this @MarvinSchenkel. Did you found a workaround to solve the problem? Maybe creating small dabatases with fewer tables and sync them.

**Comment by MarvinSchenkel** [comment] 2021-07-07 06:10
Hi @marcosmarxm, a smaller database definitely works in this case. However, I do not really see this as a workaround. Usually, we do not have any influence on the structure of the source database we want to sync to our data platform, since the source database is owned (and probably built) by a third party.

**Comment by afterthought** [comment] 2021-12-30 16:39
I believe we just hit this in our testing as well. Instead of errors we see this:

    2021-12-30 16:05:55 INFO i.a.w.p.a.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2021-12-30 16:05:55 INFO i.a.i.s.j.AbstractJdbcSource(discoverPrimaryKeys):190 - {} - Discover primary keys for tables: [LONG LIST OF TABLES]

And then 138s later this:

    2021-12-30 16:08:13 INFO i.a.w.t.TemporalAttemptExecution(get):144 - Stopping cancellation check scheduling...

**Comment by davrax** [comment] 2022-06-03 21:23
Also facing this, though with ~270 source tables. Source and destination are both MS SQL.

**Comment by chte** [comment] 2022-11-03 21:09
Facing the same issue with ~250 tables in the source, even if I select a schema with less than 10 tables

**Comment by Alonkad** [comment] 2023-09-18 13:01
Reproduces for us as well (over 1000 tables in a 3rd party DWH)

**Comment by evantahler** [comment] 2024-04-16 20:16
Closing as a duplicate of https://github.com/airbytehq/airbyte/issues/4564 - please follow along there

**Closed by evantahler** 2024-04-16 20:16 UTC
Labels: type/bug, area/connectors, priority/medium, connectors/sources-database, connectors/source/mssql, team/db-dw-sources, frozen
