### ISSUE TITLE
Normalization: failing to resolve table name conflicts after adding suffix and truncating - MySQL 8

### ISSUE THREAD

**Issue by dispalt** [airbytehq/airbyte#22630] opened 2023-02-09 05:52 UTC
## Environment
- **Airbyte version**:  0.40.30
- **OS Version / Instance**: AWS EKS
- **Deployment**: Kubernetes
- **Source Connector and version**: Stripe 1.0.1
- **Destination Connector and version**: MySQL 0.1.20
- **Step where error happened**: Sync Job

## Current Behavior
I select a subset of streams and get through most of them over a 9 hr period syncing from stripe to MySQL and it fails right at the end:

```
2023-02-09 04:22:00 normalization > 53 of 57 OK created table model etl_store.charges_payment_metho__ard_wallet_masterpass.................................. [SUCCESS 0 in 0.76s]
2023-02-09 04:22:00 normalization > 54 of 57 START table model etl_store.charges_payment_metho__kout_shipping_address....................................... [RUN]
2023-02-09 04:22:00 normalization > 54 of 57 OK created table model etl_store.charges_payment_metho__kout_shipping_address.................................. [SUCCESS 0 in 0.10s]
2023-02-09 04:22:00 normalization > 55 of 57 START table model etl_store.charges_payment_metho__pass_shipping_address....................................... [RUN]
2023-02-09 04:22:00 normalization > 55 of 57 ERROR creating table model etl_store.charges_payment_metho__pass_shipping_address.............................. [ERROR in 0.04s]
2023-02-09 04:22:00 normalization > 56 of 57 START table model etl_store.charges_payment_metho__ckout_billing_address....................................... [RUN]
2023-02-09 04:22:00 normalization > 56 of 57 OK created table model etl_store.charges_payment_metho__ckout_billing_address.................................. [SUCCESS 0 in 0.10s]
2023-02-09 04:22:00 normalization > 57 of 57 START table model etl_store.charges_payment_metho__rpass_billing_address....................................... [RUN]
2023-02-09 04:22:00 normalization > 57 of 57 OK created table model etl_store.charges_payment_metho__rpass_billing_address.................................. [SUCCESS 0 in 0.11s]
2023-02-09 04:22:00 normalization > Finished running 57 table models in 343.74s.
2023-02-09 04:22:00 normalization > Completed with 1 error and 0 warnings:
2023-02-09 04:22:00 normalization > Database Error in model charges_payment_metho__pass_shipping_address (models/generated/airbyte_incremental/etl_store/charges_payment_metho__pass_shipping_address.sql)
2023-02-09 04:22:00 normalization >   1054 (42S22): Unknown column '_airbyte_masterpass_hashid' in 'field list'
2023-02-09 04:22:00 normalization >   compiled SQL at ../build/run/airbyte_utils/models/generated/airbyte_incremental/etl_store/charges_payment_metho__pass_shipping_address.sql
2023-02-09 04:22:00 normalization > Done. PASS=56 WARN=0 ERROR=1 SKIP=0 TOTAL=57
```

## Expected Behavior
I would expect it not to have a sql generation error? 

## Logs
[24090ae6_8046_4e7a_9fd1_a882ff8735bc_logs_68_txt.txt](https://github.com/airbytehq/airbyte/files/10693919/24090ae6_8046_4e7a_9fd1_a882ff8735bc_logs_68_txt.txt)

## Steps to Reproduce
1. Set up sync from stripe to mysql
2. run sync

**Comment by marcosmarxm** [comment] 2023-02-14 19:42
@dispalt did you try to upgrade the schema of Stripe?

**Comment by davydov-d** [comment] 2023-08-01 07:36
I've made some research which shows that this issue can appear on connections with normalization, table name truncation and deeply nested entities. The root cause is we don't resolve conflicts after having added suffixes like "ab1"/"ab2"/"ab3" to table names and truncating them.
JSON paths are transformed into table names:
`[charges, payment_method_details, card, wallet, masterpass, billing_address]` -> `charges_payment_metho_6s_billing_address_ab3`
`[charges, payment_method_details, card, wallet, visa_checkout, billing_address]` -> `charges_payment_metho_6t_billing_address_ab3`
which is fine, but for the `shipping_address` we have a collision:
`[charges, payment_method_details, card, wallet, masterpass, shipping_address]` -> `charges_payment_metho_6_shipping_address_ab3`
`[charges, payment_method_details, card, wallet, visa_checkout, shipping_address]` -> `charges_payment_metho_6_shipping_address_ab3`
therefore there's a single file that would be used to create two tables, so one of them will naturally raise an error

**Comment by davydov-d** [comment] 2023-08-01 10:19
@edgao can you please take a look at this issue? or tell me who should I ping if you're not the right person. Thanks!

**Comment by edgao** [comment] 2023-08-01 14:47
Normalization is going away, and is no longer being updated (https://github.com/airbytehq/airbyte/issues/26028)... unfortunately we haven't gotten to destination-mysql yet, so in the meantime I'd suggest either excluding the problematic columns, or turning off normalization entirely. Under destinations v2 we won't be unnesting at all, so this won't be a problem once that project is finished.

Another option would be putting these streams in different connections and differentiating them with either a custom namespace or stream name prefix, which I think would prevent the collision..

**Comment by edgao** [comment] 2023-08-01 15:42
all airbyte users will get a raw table, and a typed+deduped table (pretty similar to today's normalization). But we won't turn sub-objects into separate tables anymore. https://github.com/airbytehq/airbyte/issues/26028 has an example of what the v2 table will look like.

**Comment by bazarnov** [comment] 2023-08-01 19:35
thank you for the answer

**Comment by edgao** [comment] 2023-08-02 14:47
I'm going to just close this now. @dispalt I put a few possible workarounds in https://github.com/airbytehq/airbyte/issues/22630#issuecomment-1660479996 - lmk if those don't work for you. Otherwise I'd recommend just waiting for the v2 project to get to destination-mysql.

**Closed by edgao** 2023-08-02 14:47 UTC
Labels: type/bug, area/connectors, community, connectors/destination/mysql, releaseStage/ga, team/destinations

**Comment by dispalt** [comment] 2023-08-02 15:17
@edgao yeah I ended up using clickhouse because I really only wanted light normalization anyways (which v2 seems like it's going to do), and it was working, but yeah I think v2 will simplify everything a lot and lead to a lot less bugs.  Anyways thanks for the help!
