### ISSUE TITLE
Postgres Source UI/UX validation: SSL modes UX should be hidden when "connect with SSL" option is not chosen 

### ISSUE THREAD

**Issue by akashkulk** [airbytehq/airbyte#20103] opened 2022-12-05 21:52 UTC
This issue has been created as a result of a bug bash here: 
https://app.zenhub.com/workspaces/db--dw-source-connectors-6333360e0a41155061efbcbd/issues/airbytehq/airbyte/17746

Steps to reproduce: 
1) Setup Postgres connector
2) Uncheck "Connect using SSL" option
3) User is still able to pick different SSL modes and choose SSL modes such as `require`, `verify-ca`, etc and enter information such as Client Certification, keys, CA certification, etc. 

The SSL mode UX should be hidden if the user is not connecting with SSL - the UX should be similar to the CDC Replication Method configuration UX which only shows up if the user chooses it. 

See screenshot here: 
https://www.loom.com/i/f4a90964d7624b3791227c99a3595fa0

**Comment by octavia-squidington-iv** [comment] 2022-12-05 21:53
cc @airbytehq/frontend

**Comment by timroes** [comment] 2022-12-05 21:56
Duplicate of https://github.com/airbytehq/airbyte/issues/15809

**Closed by timroes** 2022-12-05 21:56 UTC
Labels: type/bug, needs-triage, team/frontend
