### ISSUE TITLE
Excluding columns from MSSQL-source tables using UI

### ISSUE THREAD

**Issue by ideswart** [airbytehq/airbyte#2463] opened 2021-03-15 17:38 UTC
## Tell us about the problem you're trying to solve
Sometimes tables in sources contain columns which hold data that is only used for a certain system or hold sensitive information which are not used in a DWH for further analysis. Think of an account table with pw-hashes and whatnot in relation to GDPR subsidiarity/proportionality.

## Describe the solution you’d like
The possibility for excluding certain columns from a MSSQL-source table using the UI, instead of ```SELECT * FROM table```.

## Describe the alternative you’ve considered or used
Alternatively we would be introducing views in the source system to circumvent certain columns. However this is not always possible or feasible.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368218738323) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment] 2021-03-15 18:03
- Adding an extra SQL query field in the specs of JDBC source connectors could handle this use case yes.

- It would eventually let users override column data types at the source level too without having to actually impact the source database (of course, doing this on the destination side too is probably even more useful too)
- or do a "view" (without materializing an actual view) where multiple tables could be joined/transformed before being replicated.

**Comment by sherifnada** [comment] 2021-03-15 18:21
I've created #2464 to track the overarching request (UI + backend), since I think it would be useful to put at the Airbyte level as well so most sources don't need to implement it.

**Comment by mcfuhrt** [comment] 2021-06-29 13:01
Started the same Request [here](https://github.com/airbytehq/airbyte/issues/4400), sry for that!

**Comment by priyanka1906** [comment] 2022-02-10 14:16
Watching for a possible solution

**Comment by bleonard** [comment] 2022-09-30 20:24
Duplicate of https://github.com/airbytehq/airbyte/issues/4400

**Closed by bleonard** 2022-09-30 20:24 UTC
Labels: type/enhancement, connectors/sources-database, connectors/source/mssql, team/databases, autoteam, team/db-dw-sources
