### ISSUE TITLE
Airbyte is ignoring `JOB_MAIN_CONTAINER_MEMORY_REQUEST` in .env

### ISSUE THREAD

**Issue by honggyu-rr** [airbytehq/airbyte#30814] opened 2023-09-28 03:03 UTC
### Topic

Can't increase memory of jobs. Ignores all settings made as suggested on [this page](https://docs.airbyte.com/operator-guides/configuring-connector-resources)

EDIT: works at the connection-level, but not at the instance-level or connector-level

### Revelant information

I upgraded from an instance with 8gb of ram to an instance with 32gb of ram, and I just ran into a `Terminating due to java.lang.OutOfMemoryError: Java heap space` during a sync. I modified the .env file with `JOB_MAIN_CONTAINER_MEMORY_REQUEST=4g` and `JOB_MAIN_CONTAINER_MEMORY_LIMIT=6g` but I'm still seeing this in the sync logs:
```
2023-09-28 02:24:23 INFO i.a.w.p.DockerProcessFactory(create):143 - Creating docker container = destination-redshift-write-39-0-dhrtb with resources io.airbyte.config.ResourceRequirements@2256de7d[cpuRequest=1,cpuLimit=2,memoryRequest=1Gi,memoryLimit=2Gi,additionalProperties={}] and allowedHosts null
```
I've even updated the actor definition with the following sql:
`update actor_definition set resource_requirements = '{"jobSpecific": [{"jobType": "sync", "resourceRequirements": {"memory_limit": "4Gi", "memory_request": "6Gi"}}]}' where name = 'Redshift' and actor_type = 'destination';`

After each step, I've restarted my Airbyte instance and my settings are being ignored.

**Comment by DDynamic** [comment] 2023-09-29 23:08
I am having the same issue with Airbyte ignoring the instance-level and connector-level overrides outlined [here](https://docs.airbyte.com/operator-guides/configuring-connector-resources/). However, defining a [connection-specific](https://docs.airbyte.com/operator-guides/configuring-connector-resources/) requirement works.

**Comment by honggyu-rr** [comment] 2023-10-02 14:37
> I am having the same issue with Airbyte ignoring the instance-level and connector-level overrides outlined [here](https://docs.airbyte.com/operator-guides/configuring-connector-resources/). However, defining a [connection-specific](https://docs.airbyte.com/operator-guides/configuring-connector-resources/) requirement works.

Can you share what you updated the `resource_requirements` with in the `connection` table? I updated everything, but no luck.

**Comment by honggyu-rr** [comment] 2023-10-02 14:48
To summarize to potential contributors, the hardware settings are not working as env variables and at the connector level, but works at the connection level

**Comment by ro8inmorgan** [comment] 2023-10-03 14:34
We are observing the same here.

It does not work for Global Enviroment variables in the configmap and also does not on connector level. It only works when applying to connection level. But only for the main containers, we got no way to adjust the stdin, stdout container limits and requests anyways.

**Comment by honggyu-rr** [comment] 2023-10-03 20:32
> Also observing the same here, modifying the "JOB_MAIN_CONTAINER_MEMORY_REQUEST" set of environment variables are not being respected by the job pods. Strangely, this is only occurring on `*-read` and `*-write` pods, but the `*-check` pods are fine.
> 
> The workaround is by setting the [Configuring Connection-Specific Requirements](https://docs.airbyte.com/operator-guides/configuring-connector-resources#configuring-connection-specific-requirements) - this works for all pods of that Connection

the exact behavior I observed as well.

**Comment by gosusnp** [comment] 2023-10-16 23:31
Very sorry about this regression.

Yes, there has been a regression regarding the instance wide resource requirements. The connection level resource requirements should still work as expected.
We will prioritize a fix regarding the instance wide resource requirements.

**Comment by cnogradi** [comment] 2023-10-23 21:37
I tried using the connection specific requirements change to the database but cannot get this to work.  I am using 0.50.30:

// SQL command with example
update connection set resource_requirements = '{"cpu_limit": "0.5", "cpu_request": "0.5", "memory_limit": "500Mi", "memory_request": "500Mi"}' where id = '<id-from-step-1>';

I restarted the worker, sever and webapp but no change. Any other ideas?

**Comment by mrhallak** [comment] 2023-10-26 09:14
This is also happening on the Snowflake connector v3.2.3

**Comment by ro8inmorgan** [comment] 2023-10-31 14:05
Why was this closed? The issue is still there. Also the other containers in a job pod specifically stdout requests 500m and 2000m limit of cpu. This seems very excessive? There's no way  to control those containers either.

**Comment by cnogradi** [comment] 2023-11-07 23:50
@davinchia is there a PR for this or branch with a fix?  I can use the SIDECAR variables to fix the large amount of memory now used by all the side cars but I can't figure out how to fix the MAIN write/read workers to give them more memory than the default which causes workers to run out of memory (java heap)

**Comment by davinchia** [comment] 2023-11-08 05:05
Hi, we are going to release a new version in the next few days that should have this fix. I will post here when it is done.

**Comment by cnogradi** [comment] 2023-11-27 23:10
> Hi all, I've just released 0.50.34 that should restore the previous behaviour.
> 
> Please upgrade to this version and let me know if that fixes things.
> 
> Thank you for your patience!

I am struggle trying to confirm this is actually fixed.  Can you point me at the fix so I can make sure I have it?  I am using the latest containers but maybe I need the charts also?

**Comment by gosusnp** [comment] 2023-11-27 23:23
@cnogradi, the fix is https://github.com/airbytehq/airbyte-platform/commit/7eedfc75faa0ad8fb90f928adc285314b4a4cef8.

**Comment by cnogradi** [comment] 2023-11-28 15:04
> @cnogradi, the fix is [airbytehq/airbyte-platform@7eedfc7](https://github.com/airbytehq/airbyte-platform/commit/7eedfc75faa0ad8fb90f928adc285314b4a4cef8).

@gosusnp Thanks! However, I am still seeing strange behavior.  The check and normalization pods are taking on the value of the overrides but not the actual source and destination pods:

check pods working:

source-mssql-check-3700-4-bjhne for airbyte/source-mssql:2.0.1 with resources ConnectorResourceRequirements[main=io.airbyte.config.ResourceRequirements@44dee7b3[cpuRequest=1,cpuLimit=2,memoryRequest=1G,memoryLimit=5G,

 Attempting to start pod = destination-iceberg-check-3700-4-eebgo for airbyte/destination-iceberg:0.1.4 with resources ConnectorResourceRequirements[main=io.airbyte.config.ResourceRequirements@5d1ff68d[cpuRequest=1,cpuLimit=2,memoryRequest=1G,memoryLimit=5G

Read and write not working:

source-mssql-read-3700-4-lgpjs for airbyte/source-mssql:2.0.1 with resources ConnectorResourceRequirements[main=io.airbyte.config.ResourceRequirements@69464142[cpuRequest=500m,cpuLimit=1.5,memoryRequest=1Gi,memoryLimit=1.5Gi

destination-iceberg-write-3700-4-spbwz for airbyte/destination-iceberg:0.1.4 with resources ConnectorResourceRequirements[main=io.airbyte.config.ResourceRequirements@7b3f7526[cpuRequest=500m,cpuLimit=1.5,memoryRequest=1Gi,memoryLimit=1.5Gi

Normalization working:

 airbyte/normalization:0.4.3 with resources ConnectorResourceRequirements[main=io.airbyte.config.ResourceRequirements@2deac206[cpuRequest=1,cpuLimit=2,memoryRequest=1G,memoryLimit=5G,additionalProperties={}],

Read and write not working:

airbyte/source-mssql:2.0.1 with resources ConnectorResourceRequirements[main=io.airbyte.config.ResourceRequirements@4e8ad67c[cpuRequest=500m,cpuLimit=1.5,memoryRequest=1Gi,memoryLimit=1.5Gi,additionalProperties={}],

destination-postgres-write-3704-0-wvnny for airbyte/destination-postgres:0.4.0 with resources ConnectorResourceRequirements[main=io.airbyte.config.ResourceRequirements@607b417d[cpuRequest=500m,cpuLimit=1.5,memoryRequest=1Gi,memoryLimit=1.5Gi,additionalProperties={}],

**Comment by gosusnp** [comment] 2023-11-28 18:47
@cnogradi, I think check and normalization pod resources are configured through different environment variables:
```
CHECK_JOB_MAIN_CONTAINER_CPU_LIMIT
CHECK_JOB_MAIN_CONTAINER_CPU_REQUEST
CHECK_JOB_MAIN_CONTAINER_MEMORY_LIMIT
CHECK_JOB_MAIN_CONTAINER_MEMORY_REQUEST

NORMALIZATION_JOB_MAIN_CONTAINER_CPU_LIMIT
NORMALIZATION_JOB_MAIN_CONTAINER_CPU_REQUEST
NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_LIMIT
NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_REQUEST
```
Do you still have those configured?

**Comment by cnogradi** [comment] 2023-11-28 20:01
> @cnogradi, I think check and normalization pod resources are configured through different environment variables:
> 
> ```
> CHECK_JOB_MAIN_CONTAINER_CPU_LIMIT
> CHECK_JOB_MAIN_CONTAINER_CPU_REQUEST
> CHECK_JOB_MAIN_CONTAINER_MEMORY_LIMIT
> CHECK_JOB_MAIN_CONTAINER_MEMORY_REQUEST
> 
> NORMALIZATION_JOB_MAIN_CONTAINER_CPU_LIMIT
> NORMALIZATION_JOB_MAIN_CONTAINER_CPU_REQUEST
> NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_LIMIT
> NORMALIZATION_JOB_MAIN_CONTAINER_MEMORY_REQUEST
> ```
> 
> Do you still have those configured?

This is what I have in the worker pod:

bash-4.2$ set | grep JOB

JOB_MAIN_CONTAINER_CPU_LIMIT=2
JOB_MAIN_CONTAINER_CPU_REQUEST=1
JOB_MAIN_CONTAINER_MEMORY_LIMIT=5G
JOB_MAIN_CONTAINER_MEMORY_REQUEST=1G

I am not sure where the other values are even coming from such as the 1.5Gi memory limit - maybe somewhere in the code for worker?

**Comment by cnogradi** [comment] 2023-12-05 21:42
> @cnogradi, defaults can come a from a few places. Some connectors may have some defaults. However, if you want to override values for check and normalization, you need to define the variables I highlighted. Those should be defined the same was as `JOB_MAIN_CONTAINER_CPU_LIMIT` for example.

Hello @gosusnp I don't have an issue with Check and Normalization pods.  Those actually properly honor the JOB_MAIN_CONTAINER_* settings (per my logs above).  The problem is that Read and Write pods do not. What variables should I use for those since JOB_MAIN_CONTAINER_* does not work?

**Comment by gosusnp** [comment] 2023-12-05 23:24
@cnogradi, could you clarify which pod you're looking at for the environment variables when you say "worker pod"?
The `JOB_MAIN_CONTAINER_*` variables are read from the `airbyte-server`.

**Comment by davinchia** [comment] 2023-12-13 18:05
@cnogradi let us know. Otherwise we are going to close this issue by end of the week, thanks!

**Comment by cnogradi** [comment] 2023-12-14 00:42
> @cnogradi, could you clarify which pod you're looking at for the environment variables when you say "worker pod"? The `JOB_MAIN_CONTAINER_*` variables are read from the `airbyte-server`.

So I did confirm today that the proper values for the limits for the checks/source/dest pods are shown in the log for one of the syncs.  I did look back at the others logs and it seems that when I update the values in the configmap that something is not picking them up for all pods created since I have evidence in the log that some pods use the new values and others do not (per log above).  Must be an issue with not restarting one of the services (server or worker maybe?).

Anyways, I saw it work once so I am good!  Sorry for not getting back to you until now.  

@davinchia this issue can indeed be closed.

**Closed** 2023-12-14 18:05 UTC
Labels: area/platform, community, team/platform-move, autoteam, team/use

**Comment by jomach** [comment] 2024-12-04 20:47
same issue now on 1.2.0 oss azure deployment. 

```
  # Jobs resource requests and limits, see http://kubernetes.io/docs/user-guide/compute-resources/
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube.
  jobs:
    resources:
      ## Example:
      ## requests:
      ##    memory: 256Mi
      ##    cpu: 250m
      requests:
          memory: 4096Mi
          cpu: 500m
      # -- The requested resources for the airbyte bootloader image
      #requests: {}
      ## Example:
      ## limits:
      ##    cpu: 200m
      ##    memory: 1Gi
      # -- The resources limits for the airbyte bootloader image
      limits: 
          memory: 4096Mi
          cpu: 500m
```
