### ISSUE TITLE
🐛 Source Facebook Marketing to Bigquery Denormalized - JSON schema validation failed

### ISSUE THREAD

**Issue by octavia-squidington-iii** [airbytehq/airbyte#9169] opened 2021-12-29 03:01 UTC
Is this your first time deploying Airbyte: No
OS Version / Instance: AWS EC2 t3.Large
Memory / Disk: 8GiB / 50GB EBS
Deployment: Docker
Airbyte Version: 0.35.2-alpha
Source name/version: Facebook Marketing 0.2.30	
Destination name/version: Bigquery(denormalized) 0.2.2
Step: On sync
Description: Seems to error out towards the end when it is trying to sync to bigquery. Seeing error messages such as
```
Validation failed: null
error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details.
```

[Slack conversation]( https://airbytehq.slack.com/archives/C01MFR03D5W/p1640745269449300?thread_ts=1640745269.449300&cid=C01MFR03D5W)

### Logs:
[logs-2-2.txt](https://github.com/airbytehq/airbyte/files/7789384/logs-2-2.txt)

**Comment by eliziario** [comment] 2022-01-17 14:12
I could not reproduce the error. From the logs attached here, it looks like an issue with the destination, but the information in the logs is not enough to determine the exact nature of the error. 

I would need at least the destination catalog to proceed.

**Comment by etsybaev** [comment] 2022-04-09 09:55
Were there any updates from customers on this? Is this still reproducible?  Can't reduce this issue

![Selection_080](https://user-images.githubusercontent.com/4688354/162566828-c3251415-a3b5-49cf-9204-6f0521b2c55a.png)
![Selection_081](https://user-images.githubusercontent.com/4688354/162566829-02f24ce4-f12f-4a8c-982e-b4ac7d516394.png)
![Selection_082](https://user-images.githubusercontent.com/4688354/162566831-7dfce7fe-030f-4260-81bd-45e5151c04a6.png)

**Comment by etsybaev** [comment] 2022-04-11 08:17
Taking into consideration that nobody was able to reproduce this issue, that this ticket was raised a long time and lots of changes have been done since then (including some changes in bigquery related to facebook as per changelog) - I'm closing this ticket. I've spend pretty much time for attempts to reproduce it, but lo luck.
FYI @sherifnada

**Closed by etsybaev** 2022-04-11 08:17 UTC
Labels: type/bug, area/connectors, community, slack, connectors/sources-api, connectors/source/facebook_marketing, connectors/destinations-warehouse, connectors/destination/bigquery-denormalized
