### ISSUE TITLE
Icon library in storybook out of date

### ISSUE THREAD

**Issue by tealjulia** [airbytehq/airbyte#33543] opened 2023-12-15 19:32 UTC
The hosted icon library + local storybook builds are both missing a few icons (both in the dropdown of the main story and in the nice table in the icon docs)

We have an amazing new icon library!  Let's get it pushed to everywhere :)

**Comment by chandlerprall** [comment] 2023-12-18 16:06
refining notes:
- icons table & storybook controls dropdown are generated from typescript types -> docgen, this is usually a packager cache issue

relates to https://github.com/airbytehq/airbyte-platform-internal/issues/10350 for publishing to https://components.airbyte.dev/

**Comment by chandlerprall** [comment] 2023-12-28 18:04
I am unable to reproduce this locally. After modifying icon & its types file, the storybook UI will often not include the changes but restarting the storybook server seems to always find the changes and rebuild correctly.

**Comment by josephkmh** [comment] 2024-01-29 16:13
Closing because this cannot be reproduced!

**Closed by josephkmh** 2024-01-29 16:13 UTC
Labels: team/platform-compose, area/frontend
