### ISSUE TITLE
Sync Job log doesnt refresh automatically

### ISSUE THREAD

**Issue by yzislin** [airbytehq/airbyte#14377] opened 2022-07-02 18:37 UTC
## Environment
- 0.39.29-alpha
- AWS EC2- Ubuntu 22.04
- Docker
- Source-Github (probably happens for all)
- Local JSON (probably happens for all)
- Sync Job

## Current Behavior
When running sync job and clicking on the job to see the logs, the page does not refresh with latest logs. It used to refresh some releases back. Now, you have to click the job again to collapse the log and expand it again to see refreshed version.

## Expected Behavior
Logs should be updated at some interval

## Steps to Reproduce
1. Create Source, Destination and Connection
2. Launch Sync Job 
3. Click to view details

**Comment by timroes** [comment] 2022-07-05 16:05
Duplicate of https://github.com/airbytehq/airbyte/issues/14244 and will be fixed via https://github.com/airbytehq/airbyte/pull/14341

**Closed by timroes** 2022-07-05 16:05 UTC
Labels: type/bug, area/frontend, community, team/frontend, ui/logs
