### ISSUE TITLE
Source MySQL or MSSQL: Possibility to exclude columns from synchronisation

### ISSUE THREAD

**Issue by mcfuhrt** [airbytehq/airbyte#4400] opened 2021-06-29 12:55 UTC
## Tell us about the problem you're trying to solve
If you do not want to synchronise all columns of a table because they are either irrelevant or redundant, it would be helpful to exclude these columns from synchronisation. There may also be the case that the column contains too many characters and cannot be written to the target (e.g. coded images with 29k characters). This feature is implemented in Fivetran and in my opinion very use- and helpful.

## Describe the solution you’d like
The columns to be synchronised should also be selectable when selecting the tables in the schema.

## Describe the alternative you’ve considered or used
I cannot synchronise the required table and have to do without it

## Additional context
![Bildschirmfoto 2021-06-29 um 14 50 38](https://user-images.githubusercontent.com/39857259/123800597-c0e2ca00-d8e9-11eb-81a0-306533f2f473.png)
![Bildschirmfoto 2021-06-29 um 14 43 24](https://user-images.githubusercontent.com/39857259/123800603-c17b6080-d8e9-11eb-8740-01e42e991432.png)

## Are you willing to submit a PR?
I'm willing, but I don't know where to start and have a look at.

**Comment by sotte** [comment] 2021-10-01 13:31
Super important feature required to be GDPR compliant. I *must not* sync certain columns.

Is there anything we can do to move this ticket further along?

**Comment by grishick** [comment] 2022-07-01 00:20
I am adding this to Source MySQL to Beta epic for visibility. However, we are unlikely to fix this for MySQL beta or GA, because the [blocking issue](https://github.com/airbytehq/airbyte/issues/2227) is not going to be ready by then.

**Comment by bleonard** [comment] 2022-09-30 20:23
@sotte you can make a view and sync that. We are adding column selection to the platform and will solve this ticket as part of that.

**Comment by bleonard** [comment] 2022-09-30 20:26
Closing as duplicate of https://github.com/airbytehq/airbyte/issues/9771

**Closed by bleonard** 2022-09-30 20:26 UTC
Labels: type/enhancement, area/connectors, connectors/sources-database, connectors/source/mssql, connectors/source/mysql, team/databases, autoteam, team/db-dw-sources
