### ISSUE TITLE
Improve Source/Destination acceptance test run for Mac OS

### ISSUE THREAD

**Issue by alexandr-shegeda** [airbytehq/airbyte#13179] opened 2022-05-25 16:20 UTC
## Tell us about the problem you're trying to solve
During the run of Source/Destination acceptance tests, we were facing an issue related to the inability to open the DB connection to the docker container. It turned out that this issue is Mac OS only.

## Describe the solution you’d like
To fix this issue we need to update all acceptance tests for all connectors that use testcontainers and provide conditionally host and port, based on the current OS.

`public String resolveHost(GenericContainer container) {
    return System.getProperty("os.name").toLowerCase().startsWith("mac") ?
        Objects.requireNonNull(container.getContainerInfo()
            .getNetworkSettings()
            .getNetworks()
            .entrySet().stream()
            .findFirst()
            .get().getValue().getIpAddress())
        : container.getHost();
  }

  public int resolvePort(GenericContainer container) {
    return System.getProperty("os.name").toLowerCase().startsWith("mac") ?
        (Integer) container.getExposedPorts().get(0)
        : container.getFirstMappedPort();
  }`

## Additional context
The issue is not reproducible for other OS. This is only the issue with the specific handling method of localhost for docker on Mac OS.

**Comment by suhomud** [comment] 2022-06-07 03:24
Integration Tests Mac OS Issues


Destination ➡️

⛔️ destination-cassandra
    2022-06-03 05:25:28 ERROR i.a.i.d.c.CassandraDestination(check):43 - Can't establish Cassandra connection with reason:
    com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 1 nodes, use getAllErrors() for more): 

⛔️ destination-clickhouse
    2022-06-03 05:33:04 destination > 2022-06-03 05:33:04 ERROR i.a.i.b.FailureTrackingAirbyteMessageConsumer(start):39 - Exception while starting consumer
    2022-06-03 05:33:04 destination > java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30003ms.

⛔️ destination-clickhouse-strict-encrypt
2022-06-03 05:38:11 destination > 2022-06-03 05:38:11 ERROR i.a.i.b.FailureTrackingAirbyteMessageConsumer(start):39 - Exception while starting consumer
2022-06-03 05:38:11 destination > java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30002ms.

⛔️ destination-elasticsearch
java.net.ConnectException: Connection refused

⛔️ destination-kafka
2022-06-03 06:36:12 destination > 2022-06-03 06:36:12 ERROR i.a.i.b.FailureTrackingAirbyteMessageConsumer(accept):52 - Exception while accepting message
2022-06-03 06:36:12 destination > java.lang.RuntimeException: Cannot send message to Kafka. Error: Topic sourcenamespace_exchange_rate_test_topic not present in metadata after 60000 ms.

⛔️ destination-mariadb-columnstore
    2022-06-03 07:05:25 ERROR o.t.c.GenericContainer(tryStart):524 - Could not start container
    java.lang.IllegalStateException: Container is started, but cannot be accessed by (JDBC URL: jdbc:mariadb://localhost:58912/test), please check container logs
        at org.testcontainers.containers.JdbcDatabaseContainer.waitUntilContainerStarted(JdbcDatabaseContainer.java:165) ~[jdbc-1.17.1.jar:?]

⛔️ destination-mongodb 📝 MongodbDestinationAcceptanceTest has compiling issue 
    2022-06-03 07:28:11 destination > 2022-06-03 07:28:11 ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
    2022-06-03 07:28:11 destination > com.mongodb.MongoTimeoutException: Timed out after 30000 ms while waiting to connect. Client view of cluster state is {type=UNKNOWN, servers=[{address=localhost:60991, type=UNKNOWN, state=CONNECTING, exception={com.mongodb.MongoSocketOpenException: Exception opening socket}, caused by {java.net.ConnectException: Connection refused}}]

⛔️ destination-mqtt
    2022-06-03 07:36:21 destination > 2022-06-03 07:36:21 WARN c.n.s.JsonMetaSchema(newValidator):338 - Unknown keyword examples - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword
    2022-06-03 07:36:41 destination > 2022-06-03 07:36:41 ERROR i.a.i.b.FailureTrackingAirbyteMessageConsumer(start):39 - Exception while starting consumer
    2022-06-03 07:36:41 destination > java.lang.RuntimeException: Error connecting to MQTT broker

⛔️ destination-mssql
  2022-06-03 07:51:02 destination > 2022-06-03 07:51:02 ERROR i.a.i.d.b.BufferedStreamConsumer(close):191 - Close failed.
    2022-06-03 07:51:02 destination > java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30003ms.

⛔️ destination-mssql-strict-encrypt
    2022-06-03 07:56:48 destination > 2022-06-03 07:56:48 ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
    2022-06-03 07:56:48 destination > java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30002ms.

⛔️ destination-mysql
2022-06-03 09:16:48 destination > 2022-06-03 09:16:48 ERROR i.a.i.b.FailureTrackingAirbyteMessageConsumer(start):39 - Exception while starting consumer
2022-06-03 09:16:48 destination > java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30004ms.

⛔️ destination-mysql-strict-encrypt
SQL [set global local_infile=true]; Access denied; you need (at least one of) the SUPER or SYSTEM_VARIABLES_ADMIN privilege(s) for this operation
org.jooq.exception.DataAccessException: SQL [set global local_infile=true]; Access denied; you need (at least one of) the SUPER or SYSTEM_VARIABLES_ADMIN privilege(s) for this operation


⛔️ destination-oracle
   2022-06-03 11:14:41 destination > 2022-06-03 11:14:41 ERROR i.a.i.b.FailureTrackingAirbyteMessageConsumer(start):39 - Exception while starting consumer
    2022-06-03 11:14:41 destination > java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30005ms.

⛔️ destination-postgres
    2022-06-03 11:33:26 destination > 2022-06-03 11:33:26 ERROR i.a.i.b.FailureTrackingAirbyteMessageConsumer(start):39 - Exception while starting consumer
    2022-06-03 11:33:26 destination > java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30003ms.

⛔️ destination-pulsar
    2022-06-03 11:46:49 WARN o.a.p.c.i.ConnectionHandler(reconnectLater):106 - [non-persistent://public/default/public] [standalone-0-0] Could not get connection to broker: org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.CompletionException: org.apache.pulsar.shade.io.netty.channel.ConnectTimeoutException: connection timed out: /10.33.33.1:57553 -- Will try again in 54.029 s

⛔️ destination-redis
    2022-06-03 11:49:05 destination > 2022-06-03 11:49:05 ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
    2022-06-03 11:49:05 destination > redis.clients.jedis.exceptions.JedisConnectionException: Failed to create socket.

⛔️ destination-scylla
    2022-06-03 11:57:05 destination > 2022-06-03 11:57:05 ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
    2022-06-03 11:57:05 destination > com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/[0:0:0:0:0:0:0:1]:58877 (com.datastax.driver.core.exceptions.TransportException: [localhost/[0:0:0:0:0:0:0:1]:58877] Cannot connect), localhost/127.0.0.1:58877 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1:58877] Cannot connect))


Source ⬅️

⛔️ source-clickhouse
    2022-06-03 12:31:54 source > 2022-06-03 12:31:54 ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
    2022-06-03 12:31:54 source > java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30001ms.

⛔️ source-cockroachdb
    java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30007ms.
        at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:696)

⛔️ source-db2
    2022-06-03 12:44:45 source > 2022-06-03 12:44:45 ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
    2022-06-03 12:44:45 source > java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30002ms.

⛔️ source-jdbc
022-06-03 12:53:06 INFO i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - 2022-06-03 12:53:06 ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
    2022-06-03 12:53:06 INFO i.a.w.i.DefaultAirbyteStreamFactory(lambda$create$0):61 - java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30003ms.

⛔️ source-kafka
    2022-06-03 14:58:22 source > 2022-06-03 14:58:22 ERROR i.a.i.b.AirbyteExceptionHandler(uncaughtException):26 - Something went wrong in the connector. See the logs for more details.
    2022-06-03 14:58:22 source > org.apache.kafka.common.errors.TimeoutException: Timeout expired while fetching topic metadata

⛔️ source-mongoldb-v2
Caused by: java.net.ConnectException: Connection refused

⛔️ source-mssql-v2
2022-06-07 02:34:37 source > java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30002ms.

⛔️ source-oracle
    2022-06-07 02:53:22 source > 2022-06-07 02:53:22 ERROR i.a.i.b.s.SshWrappedSource(read):56 - Exception occurred while getting the delegate read iterator, closing SSH tunnel
    2022-06-07 02:53:22 source > java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30002ms.

⛔️ source-postgres
2022-06-07 02:59:17 source > java.lang.RuntimeException: Unable establish a connection: Could not connect with provided configuration. Error: HikariPool-1 - Connection is not available, request timed out after 30002ms.

⛔️ source-sftp
Reason: Connection refused 

⛔️ source-tidb
2022-06-07 03:13:40 source > java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30001ms.

**Closed** 2022-09-29 18:14 UTC
Labels: type/enhancement, area/connectors, Epic, team/connectors-java, team/connector-ops, team/destinations, team/db-dw-sources
