### ISSUE TITLE
elasticsearch

### ISSUE THREAD

**Issue by vsnuvt** [airbytehq/airbyte#4363] opened 2021-06-26 04:01 UTC
## Tell us about the new connector you’d like to have
* https://opendistro.github.io/for-elasticsearch/
* A lot of people use elasticsearch for analytics and Elasticsearch visualization connectors are readily available vs mellisearch

## Describe the context around this new connector
* We use elasticsearch pretty much for every thing from search, nlp, ml, correlation analytics, visualization, collaboration etc
* Which team in your company wants this integration, what for? This helps us understand the use case. Data - Integration team
* How often do you want to run syncs? - as low as 1 minute but we are looking into near real time capabilities
* If this is an API source connector, which entities/endpoints do you need supported? yes absolutely Rest API

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte? 
We have python connectors for mysql, s3, and bigquery to our Elasticsearch. We are also using streamsets for some of our pipelines.

**Comment by davinchia** [comment] 2021-06-27 09:37
This is a duplicate of #2255. Closing this in favor of that.

**Closed by davinchia** 2021-06-27 09:37 UTC
Labels: area/connectors, new-connector
