### ISSUE TITLE
Normalization Fails - airbyte renaming all fields, casts varchar (i.e. text) to varchar(256)

### ISSUE THREAD

**Issue by skwaugh** [airbytehq/airbyte#14343] opened 2022-07-01 12:43 UTC
Seems like a bad assumption to make?  Any ideas why Airbyte's normalization wants to rename every column in a 700 column table, only to move it over?  

This might be a good strategy for other databases like Snowflake, but it effectively takes Postgres offline for hours, depending on the size of the table - Postgres' vacuum comes into cleanup and takes its good ol time.

This custom connector is used in production. I haven't been able to complete a sync for two weeks, even after downgrading Airbyte to the last version for which a sync was successful.

**_Something_** was pushed that was a breaking change.  I want to solve the problem for myself - I've reviewed dozens of commits over the past 20 "releases", nearly all of which inject new and undocumented code without giving the slightest justification for its introduction.  That's fine if things work but it's grating for your users and your community.

I reached out on Slack, but its crickets over there.  I understand that everything is 'Alpha' - but you obviously wouldn't have grown this much if everyone treated the platform as if it were alpha.  if you were alpha, no one would be willing to spend considerable time and energy building these connectors.  

```
2022-07-01 10:16:46 normalization >   
2022-07-01 10:16:46 normalization > 10:16:42.681116 [debug] [Thread-5  ]: SQL status: ALTER TABLE in 0.09 seconds
2022-07-01 10:16:46 normalization > 10:16:42.683936 [debug] [Thread-5  ]: Using postgres connection "model.airbyte_utils._vow__listings_other_properties_stg"
2022-07-01 10:16:46 normalization > 10:16:42.684188 [debug] [Thread-5  ]: On model.airbyte_utils._vow__listings_other_properties_stg: /* {"app": "dbt", "dbt_version": "1.0.0", "profile_name": "normalize", "target_name": "prod", "node_id": "model.airbyte_utils._vow__listings_other_properties_stg"} */
2022-07-01 10:16:46 normalization > 
2022-07-01 10:16:46 normalization >     alter table "rmy"."_airbyte_airbyte"."_vow__listings_other_properties_stg" add column "publicremarks__dbt_alter" character varying(256);
2022-07-01 10:16:46 normalization >     update "rmy"."_airbyte_airbyte"."_vow__listings_other_properties_stg" set "publicremarks__dbt_alter" = "publicremarks";
2022-07-01 10:16:46 normalization >     alter table "rmy"."_airbyte_airbyte"."_vow__listings_other_properties_stg" drop column "publicremarks" cascade;
2022-07-01 10:16:46 normalization >     alter table "rmy"."_airbyte_airbyte"."_vow__listin
[logs-18036.txt](https://github.com/airbytehq/airbyte/files/9028823/logs-18036.txt)
gs_other_properties_stg" rename column "publicremarks__dbt_alter" to "publicremarks"
2022-07-01 10:16:46 normalization >   
2022-07-01 10:16:46 normalization > 10:16:42.742312 [debug] [Thread-5  ]: Postgres adapter: Postgres error: value too long for type character varying(256)
```
Custom Connector --> Postgres 13
Airbyte Version: 0.39.10-alpha
Source: Custom
Destination: Postgres (0.3.20)
[logs-18036.txt](https://github.com/airbytehq/airbyte/files/9028824/logs-18036.txt)

**Comment by alafanechere** [comment] 2022-07-01 15:00
Hi @skwaugh thank you for the feedback. 
Do you still have the logs of your last successful sync? It will be interesting to spot differences in Airbyte version / Normalization version and DBT postgres adapter version. 

Could the problem come from the incoming data that evolved and excesses 256 characters now?

**Comment by ChristopheDuong** [comment] 2022-07-01 17:13
What is the data type of your columns such as `"rmy"."_airbyte_airbyte"."_vow__listings_other_properties_stg"."publicremarks"` before running these syncs?

These are not "airbyte" controlling the rename queries mechanisms, but dbt.

It's probably due to a type change in the catalog emitted by airbyte though.
So dbt is trying to rename the column and make a backup copy, to safely create a new column with the same name but with a different type. then copy over the old values to the new one before dropping that copy.

A workaround could be to delete all your final tables if you still have all your data in your airbyte raw tables. normalization/dbt would recreate the final tables from scratch without doing alter statements.

**Comment by alafanechere** [comment] 2022-07-04 07:58
Hey @skwaugh I think the problem you raised was fixed by https://github.com/airbytehq/airbyte/pull/12836 . Could you please upgrade Airbyte to its latest version (or at least to 0.39.18) and check if you have the same TEXT to VARCHAR behavior?

**Comment by skwaugh** [comment] 2022-07-04 15:19
> Hi @skwaugh thank you for the feedback. Do you still have the logs of your last successful sync? It will be interesting to spot differences in Airbyte version / Normalization version and DBT postgres adapter version.
> 
> Could the problem come from the incoming data that evolved and excesses 256 characters now?

I do.  willl attach logs in subsequent column.  Thank you. The incoming data has always been in excess of 256 characters.  

Postgres types `varchar` and `text` [are equivalent](https://www.postgresql.org/docs/current/datatype-character.html) so long as a max value is not explicitly assigned, as in `varchar(64)`.  That is, the compiler does not differentiate between them.

Airbyte - or, perhaps dbt according to @ChristopheDuong - is currently taking the following approach ( which did not used to be the case):
1. Column X is of type varchar.  Postgres varchar ~= text types can hold values up 1GB0
2. New incremental data for Column X has one or more values with length >= 255 characters
3. Depending on Airbyte Version
    - **Airbyte 3.11:** Alter column X to type `varchar ( 255 )` - fails
    - **Airbyte 3.30** Alter column X to type `varchar`. 
        - Then alter all remaining 650 columns in stream to `varchar` ( despite them already being type `varchar`), with each cast taking >1600 seconds, roughly 27 minutes.  
        - 650*27 = 17,550 minutes = 292.5 hours = 12.2 days

**Comment by skwaugh** [comment] 2022-07-04 15:39
**Last Succesful Sync** - 6/15/2022 10:13am
`6.58 MB | 390 emitted records | 390 committed records | 1m 52s | Sync`
Airbyte v0.39.1a
destination-postgres v0.3.20
[Airbyte v0.39.1a | destination-postgres v0.3.20 | logs-17770.txt](https://github.com/airbytehq/airbyte/files/9040695/Airbyte.v0.39.1a.destination-postgres.v0.3.20.logs-17770.txt)

**First Failed Sync** 6/15/2022 10:37am
`NaN Bytes | no records | no records | 23h 28m 2s | Sync`
`Failure Origin: Unknown, Message: This attempt was cancelled`
**Note** I manually canceled this sync after ~24 hours.  For reasons unknown, the logs do not include the ALTER TABLE statements.  The logs are quite sparse, but other simultaneous syncs (all were failing that morning) do include those statements - verified manually via pg_stat_activity and pg_stat_statements 
`Airbyte v0.39.18a`
`destination-postgres v0.3.20`
[Airbyte v0.39.18a | destination-postgres v0.3.20 | logs-17773.txt](https://github.com/airbytehq/airbyte/files/9040736/Airbyte.v0.39.18a.destination-postgres.v0.3.20.logs-17773.txt)

**Comment by skwaugh** [comment] 2022-07-04 17:09
> Hey @skwaugh I think the problem you raised was fixed by #12836 . Could you please upgrade Airbyte to its latest version (or at least to 0.39.18) and check if you have the same TEXT to VARCHAR behavior?

Actually, the first time the sync failed was when I upgraded to `v0.39.18a`.  Thanks for the link to the dbt issue.  That looks like it definitely has something to do with it.

> What is the data type of your columns such as "rmy"."_airbyte_airbyte"."_vow__listings_other_properties_stg"."publicremarks" before running these syncs?

`_airbyte_airbyte._vow__listings_condos_properties_ab2.publicremarks = varchar`
`_airbyte_airbyte._vow__listings_condos_properties_stg.publicremarks = text`
`airbyte._vow__listings_condos_properties.publicremarks = varchar`
`airbyte._vow__listings_condos_properties.publicremarks = varchar`

Any ideas why `stg` would have `text` but not anything downstream?  

```
-- View: 	_airbyte_airbyte._vow__listings_condos_properties_ab2
WITH __dbt__cte___vow__listings_condos_properties_ab1 AS (
         SELECT
            ...
            jsonb_extract_path_text(table_alias._airbyte_data, VARIADIC ARRAY['PublicRemarks'::text]) AS publicremarks,
			...
           FROM airbyte._airbyte_raw__vow__listings_condos_properties table_alias
          WHERE 1 = 1
        )
 SELECT 
    ...
    __dbt__cte___vow__listings_condos_properties_ab1.publicremarks::character varying AS publicremarks,
 	...
  FROM __dbt__cte___vow__listings_condos_properties_ab1
  WHERE 1 = 1;


-- Table: 	_airbyte_airbyte._vow__listings_condos_properties_stg
CREATE TABLE IF NOT EXISTS _airbyte_airbyte._vow__listings_condos_properties_stg
(
	...
    publicremarks text
    ...
);

-- Table: 	airbyte._vow__listings_condos_properties
CREATE TABLE IF NOT EXISTS airbyte._vow__listings_condos_properties
(
	...
    publicremarks varchar,
 	...
)


-- Table:	airbyte._vow__listings_condos_properties
CREATE TABLE airbyte._vow__listings_condos_properties_scd (
	...
    publicremarks varchar,
    ...
);
```

**Comment by alafanechere** [comment] 2022-07-08 09:40
Thank you @skwaugh for all these details. I triaged the issue to make sure it reaches the backlog of the team responsible for normalization. We'll keep you posted.
There were recent upgrades made to the normalization, I don't think these are related to the problem you mentioned, but for reproducibility do you mind trying upgrading to the latest Airbyte version which is currently using 0.2.6 of normalization?

**Comment by marcosmarxm** [comment] 2024-02-13 17:29
Normalization was migrated to typing-deduping method doesn't use normalization anymore.

**Closed by marcosmarxm** 2024-02-13 17:29 UTC
Labels: type/bug, area/connectors, normalization, community, connectors/destination/postgres, team/destinations
