### ISSUE TITLE
Add support for servicename in oracle db connector

### ISSUE THREAD

**Issue by ilijaNL** [airbytehq/airbyte#9806] opened 2022-01-26 06:03 UTC
Currently only a sid for connection is supported in the oracle db connector. Add support for servicename (TNS alias) configuration in the oracle db connection.

**Comment by grishick** [comment] 2022-07-15 15:23
This is a duplicate of [11348](https://github.com/airbytehq/airbyte/issues/11348)

**Closed by grishick** 2022-07-15 15:23 UTC
Labels: area/connectors, community, area/databases, connectors/source/oracle, connectors/destination/oracledb, team/databases, autoteam, connectors/destination/oracle
