### ISSUE TITLE
Cannot setup Google Analytics as source

### ISSUE THREAD

**Issue by okumar-SDG** [airbytehq/airbyte#42563] opened 2024-07-26 14:33 UTC
### Connector Name

source-googleAnalytics

### Connector Version

2.4.13

### What step the error happened?

Configuring a new connector

### Relevant information

I got the below error while configuring GA as source, I am using local open source for airbyte setup.

`Learn more
Internal message: [Errno 13] Permission denied: 'source_config.json'
Failure type: system_error

Stacktrace
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 8, in <module>
    run()
  File "/airbyte/integration_code/source_google_analytics_data_api/run.py", line 17, in run
    MigrateCustomReportsCohortSpec.migrate(sys.argv[1:], source)
  File "/airbyte/integration_code/source_google_analytics_data_api/config_migrations.py", line 235, in migrate
    cls._modify_and_save(config_path, source, config),
  File "/airbyte/integration_code/source_google_analytics_data_api/config_migrations.py", line 208, in _modify_and_save
    source.write_config(migrated_config, config_path)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/connector.py", line 71, in write_config
    with open(config_path, "w") as fh:
PermissionError: [Errno 13] Permission denied: 'source_config.json'`

Any suggestion

### Relevant log output

```shell
Learn more
Internal message: [Errno 13] Permission denied: 'source_config.json'
Failure type: system_error

Stacktrace
Traceback (most recent call last):
  File "/airbyte/integration_code/main.py", line 8, in <module>
    run()
  File "/airbyte/integration_code/source_google_analytics_data_api/run.py", line 17, in run
    MigrateCustomReportsCohortSpec.migrate(sys.argv[1:], source)
  File "/airbyte/integration_code/source_google_analytics_data_api/config_migrations.py", line 235, in migrate
    cls._modify_and_save(config_path, source, config),
  File "/airbyte/integration_code/source_google_analytics_data_api/config_migrations.py", line 208, in _modify_and_save
    source.write_config(migrated_config, config_path)
  File "/usr/local/lib/python3.10/site-packages/airbyte_cdk/connector.py", line 71, in write_config
    with open(config_path, "w") as fh:
PermissionError: [Errno 13] Permission denied: 'source_config.json'
```

### Contribute

- [ ] Yes, I want to contribute

![image](https://github.com/user-attachments/assets/a6817516-bdf2-45b1-8463-99d1a83451b9)

**Comment by marcosmarxm** [comment] 2024-07-30 22:02
Are you able to create other sources?

**Comment by marcosmarxm** [comment] 2024-08-05 15:33
Duplicate of https://github.com/airbytehq/airbyte/issues/39423

**Closed by marcosmarxm** 2024-08-05 15:33 UTC
Labels: type/bug, area/connectors, community, needs-triage, team/connectors-python, autoteam

**Comment by PipeSabate** [comment] 2024-08-05 16:00
Hi! I'm having the same problem.

I currently have many connections and they work perfectly, but when I set GA4 as source I get the error "Internal message: [Errno 13] Permission denied: '/config/connectionConfiguration.json'
Failure type: system_error"

![image](https://github.com/user-attachments/assets/18321d71-08ae-484f-ad62-42e15fbfedd0)

**Comment by marcosmarxm** [comment] 2024-08-05 17:07
@PipeSabate post in #39423
