### ISSUE TITLE
Source Exhange Rate API: Invalid API Access key

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#15524] opened 2022-08-10 19:10 UTC
This Github issue is synchronized with Zendesk:

**Ticket ID:** [#1476](https://airbyte7538.zendesk.com/agent/tickets/1476)
**Priority:** normal
**Group:** Community Assistance Engineer
**Assignee:** Nataly Merezhuk

**Original ticket description:**

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">Hi all,<br>
have a setup of 0.39.32-alpha on Docker and MacOS locally, trying to test out ‘Exchange Rate API’ as a source, but receive an error of ‘Invalid API Access key’ maybe the access key needs to have a header or something else before it ?  Tried to run the same API key from terminal using curl and can get back the answer with no errors…<br>
Also have attached the screenshot from the Airbyte.</p>
<p dir="auto">Any ideas or help would be much appreciated !</p>
<p dir="auto"></p><div><a href="https://aws1.discourse-cdn.com/business7/uploads/airbyte/original/2X/f/f73f33acf7356f9d57602bc40fa74b78d40fb381.png" title="image" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;"><img src="https://aws1.discourse-cdn.com/business7/uploads/airbyte/optimized/2X/f/f73f33acf7356f9d57602bc40fa74b78d40fb381_2_406x499.png" alt="image" width="auto" height="auto" style="max-width: 100%;"><div style="display: none;">
<span>image</span><span>1160×1428 107 KB</span>
</div></a></div><p dir="auto"></p> 

[<a href="https://discuss.airbyte.io/t/exhange-rate-api-connector-invalid-api-key/1746/1" rel="noreferrer">Discourse post</a>]</div></blockquote>

## What
The exchange rate API url has changed from `https://api.exchangeratesapi.io/v1` to `https://api.apilayer.com/exchangerates_data/convert`

**Comment by marcosmarxm** [comment] 2022-08-10 19:11
*Comment made from Zendesk by Marcos Marx on 2022-08-10 at 17:04:*

<blockquote><div class="zd-comment" dir="auto"><p dir="auto">I’m having the same issue. Generated an API Key in apilayer etc. curl does not work. I went and checked the live demo and seems like the api now goes via apilayer</p>
<pre style="max-width: 694px; word-wrap: break-word;"><code style="background-color: #f9f9f9; display: block; overflow: auto; padding: 2px 5px;">curl --request GET \
--url 'https://api.apilayer.com/exchangerates_data/convert?to=usd&amp;from=eur&amp;amount=5' \
--header 'apikey:YOUR API KEY HERE'
</code></pre>
<p dir="auto">the above worked.  I check the connector code and it uses something like this</p>
<p dir="auto">curl “<a href="https://api.exchangeratesapi.io/v1/latestaccess_key=KEY" rel="noopener nofollow ugc noreferrer" style="color: #006699; font-weight: bold; text-decoration: none;">https://api.exchangeratesapi.io/v1/latestaccess_key=KEY</a>”</p>
<p dir="auto">which did not work for me. Any help would be appreciated. Spent a bit too much time on this. so will move onto other tutorials where I hope to have more success <img src="https://emoji.discourse-cdn.com/twitter/slight_smile.png?v=12" title=":slight_smile:" alt=":slight_smile:" width="20" height="20"></p> 

 [<a href="https://discuss.airbyte.io/t/exchange-rate-api-connector-invalid-api-key/1746/3" rel="noreferrer">Discourse post</a>]</div></blockquote>

**Comment by marcosmarxm** [comment] 2022-08-10 19:11
*Comment made from Zendesk by Nataly Merezhuk on 2022-08-10 at 18:19:*

<blockquote><div class="zd-comment" dir="auto">Got it, thanks for posting @dlobo. Looks like the Exchange Rate API might have been acquired by API Layer. I'll go ahead and escalate this to a GitHub issue! If you or @rainers24 would like to submit a PR, please feel free. I think this would be a simple fix.<br></div></blockquote>

**Comment by marcosmarxm** [comment] 2022-08-10 19:15
*Comment made from Zendesk by Nataly Merezhuk on 2022-08-10 at 19:14:*

<blockquote><div class="zd-comment" dir="auto">Here is the link to the issue:<br><a rel="noopener noreferrer" href="https://github.com/airbytehq/airbyte/issues/15524">https://github.com/airbytehq/airbyte/issues/15524</a><br></div></blockquote>

**Comment by jonathanneo** [comment] 2022-08-23 14:41
Hi there, I'm a community contributor. A PR created to fix this issue can be found here: https://github.com/airbytehq/airbyte/pull/15884

**Comment by natalyjazzviolin** [comment] 2022-08-24 09:44
@jonathanneo thanks!

Closing this because it's a duplicate of #14779

**Closed by natalyjazzviolin** 2022-08-24 09:44 UTC
Labels: area/connectors, lang/python, community, team/connectors-python, zendesk, connectors/source/exchange-rates-tutorial, connectors/source/exchange-rate-api

**Comment by marcosmarxm** [comment] 2022-08-25 02:34
Thanks @jonathanneo team will take a look soon to your contribution
