### ISSUE TITLE
🐛DATETIME from MySQL not returned as TIMESTAMP on postgres. It returns as text

### ISSUE THREAD

**Issue by dl-lim** [airbytehq/airbyte#3865] opened 2021-06-03 19:31 UTC
## Expected Behavior
_Tell us what should happen._
DATETIME from MySQL should end up as TIMESTAMP on postgres

## Current Behavior
_Tell us what happens instead of the expected behavior._
DATETIME from MySQL should end up as VARCHAR on postgres

## Logs
_If applicable, please upload the logs from the failing operation. For sync jobs, you can download the full logs from the UI by going to the sync attempt page and clicking the download logs button at the top right of the logs display window._
N/A

## Steps to Reproduce
1. Have DATETIME data on a mysql source
1. Push to a Postgres dest
1. Postgres data shows up as text, not date :(

## Severity of the bug for you
High

## Airbyte Version
Found in the .env file in the root of the project.
0.24.5

## Connector Version (if applicable)
Found in the admin page in the UI in the respective Source or Destination tab.
mysql 0.3.3
postgres 0.3.2

## Additional context
_Environment, version, integration..._
#3562 
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200368060087111/1200423627420003) by [Unito](https://www.unito.io)

**Comment by Morpheus1999** [comment] 2022-01-26 08:29
Dears

I just found that this issue was caused by class [https://github.com/airbytehq/airbyte/blob/v0.35.10-alpha/airbyte-protocol/models/src/main/java/io/airbyte/protocol/models/JsonSchemaPrimitive.java](url) do not have corresponging timestamp enum item and this class was used to generated stream of catalog.

**Comment by BenoitFayolle** [comment] 2022-01-28 17:11
Still an issue in connector version 0.5.1
Would love for this to be resolved!
Happy to test things out if someone knows how to resolve.

**Comment by Morpheus1999** [comment] 2022-01-29 06:59
Dears

I have created on merge request for fixing this issue.
Please kindly reviewing it.

Thanks

**Comment by tuliren** [comment] 2022-08-17 17:23
This is probably fixed by https://github.com/airbytehq/airbyte/pull/15504. Need to verify.

**Comment by tuliren** [comment] 2022-08-17 17:24
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Database-and-Warehouse-Connectors-6258a559d235e00013bec81c/issues/airbytehq/airbyte/3865?planning-poker) with ZenHub @edgao @rodireich @ryankfu @subodh1810

**Comment by tuliren** [comment] 2022-08-17 17:28
Actually we already have unit tests for this. This is fixed by #15504.

**Closed by tuliren** 2022-08-17 17:28 UTC
Labels: type/bug, area/connectors, connectors/sources-database, connectors/source/mysql, team/databases, autoteam
