### ISSUE TITLE
Infinite loop when synced

### ISSUE THREAD

**Issue by Wellers0n** [airbytehq/airbyte#29871] opened 2023-08-25 20:59 UTC
### What method are you using to run Airbyte?

Docker

### Platform Version or Helm Chart Version

0.50.6

### What step the error happened?

During the Sync

### Revelant information

Hey there.
I have a builder source with a postgres destination, this builder source calls an api and updates my postgres destination. But when I try to sync it crashes. This connection calls an ETL-DBT to create snapshots in my postgres database. Has anyone had this problem?
My ETL-DBT creates this new snapshots in the database for me, but I think it’s crashing because it’s a large amount of data at once

**Comment by girarda** [comment] 2023-09-28 15:55
@Wellers0n thanks for reporting the error.

Can you provide the following information to help us troubleshoot?
1. Do you have log messages?
2. Does the error happen in the source or in the destination?
3. If in the source, can you share the connector manifest? (the yaml representation of the connector)

**Comment by girarda** [comment] 2023-11-06 03:07
Closing because we don't have enough information to reproduce. Feel free to reopen with more details you still need help

**Closed by girarda** 2023-11-06 03:07 UTC
Labels: type/bug, community, team/extensibility, autoteam, area/connector-builder, team/use
