### ISSUE TITLE
Create a simple script to verify developer environment

### ISSUE THREAD

**Issue by michel-tricot** [airbytehq/airbyte#1888] opened 2021-01-29 01:16 UTC
## Tell us about the problem you're trying to solve
We want to help contributors onboard on Airbyte and help them identify what tools they might be missing.

## Describe the solution you’d like
Can we create a simple script that checks the current environment and checks if:

* The proper version of the JVM is active
* The proper version of python is active
* The proper version of npm is active
* The proper version of ... is active

## Describe the alternative you’ve considered or used
Listing tools in the documentation

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368086601006) by [Unito](https://www.unito.io)

**Comment by jrhizor** [comment] 2021-01-29 17:13
If this is sufficiently fast we could add a warning or failure at the top of any `./gradlew` command.

**Comment by evantahler** [comment] 2022-08-23 16:52
Closing this as it is a duplicate of https://github.com/airbytehq/airbyte/issues/3028

**Closed** 2022-08-23 16:52 UTC
Labels: type/enhancement, area/developer, team/oss
