### ISSUE TITLE
Incompatible types for comparison

### ISSUE THREAD

**Issue by machariamuguku** [airbytehq/airbyte#16147] opened 2022-08-30 22:36 UTC
Fails comparison for default value (unquoted string oss vs quoted string "oss")

[comparison](https://github.com/airbytehq/airbyte/blob/9e17f97e245bea2dc9b3bdfa0abd3b50c2a9e5a1/charts/airbyte-server/templates/deployment.yaml#L245)

[Default Value](https://github.com/airbytehq/airbyte/blob/9e17f97e245bea2dc9b3bdfa0abd3b50c2a9e5a1/charts/airbyte-server/values.yaml#L4)

Succeeds if I override default value with: 
```
server:
  deploymentMode: "oss"
```

`Error: UPGRADE FAILED: template: airbyte/charts/server/templates/deployment.yaml:245:15: executing "airbyte/charts/server/templates/deployment.yaml" at <eq .Values.deploymentMode "oss">: error calling eq: incompatible types for comparison`

**Comment by natalyjazzviolin** [comment] 2022-08-31 18:15
Hello @machariamuguku , as this issue does not have enough details for further debugging let's take it to the Airbyte forum. Please make a post in the Troubleshooting section:
https://discuss.airbyte.io/

I am closing this issue for now.

**Comment by lautaromundi** [comment] 2022-09-09 15:44
Hi! 
I have the same issue. Is related to: https://github.com/airbytehq/airbyte/pull/16334/files. 
@machariamuguku do you find the cause?

**Comment by marcosmarxm** [comment] 2022-11-30 21:51
Closed by #16334

**Closed by marcosmarxm** 2022-11-30 21:51 UTC
Labels: type/bug, community, area/platform-oss, team/prod-eng
