### ISSUE TITLE
Source Slack to BigQuery: AirbyteMessageTracker(handleDestinationEmittedState) state hash collision

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#9629] opened 2022-01-20 03:33 UTC
## Environment
- **Airbyte version**:  0.35.5-alpha
- **OS Version / Instance**: MacOS
- **Deployment**: Docker
- **Source Connector and version**: Slack dev
- **Destination Connector and version**: Bigquery 0.6.2
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
I created a Slack connection to Bigquer. After 4 hours running and logs continues print the same state I ran `docker stop source-container` after this the following message was printed:
```
2022-01-20 03:13:33 ERROR i.a.w.p.a.AirbyteMessageTracker(handleDestinationEmittedState):137 - State hash -1803066183 was already committed, likely indicating a state hash collision
io.airbyte.workers.protocols.airbyte.StateDeltaTracker$StateDeltaTrackerException: State hash -1803066183 was already committed, likely indicating a state hash collision
	at io.airbyte.workers.protocols.airbyte.StateDeltaTracker.commitStateHash(StateDeltaTracker.java:114) ~[io.airbyte-airbyte-workers-0.35.5-alpha.jar:?]
	at io.airbyte.workers.protocols.airbyte.AirbyteMessageTracker.handleDestinationEmittedState(AirbyteMessageTracker.java:134) ~[io.airbyte-airbyte-workers-0.35.5-alpha.jar:?]
	at io.airbyte.workers.protocols.airbyte.AirbyteMessageTracker.acceptFromDestination(AirbyteMessageTracker.java:81) ~[io.airbyte-airbyte-workers-0.35.5-alpha.jar:?]
	at io.airbyte.workers.DefaultReplicationWorker.lambda$getDestinationOutputRunnable$4(DefaultReplicationWorker.java:283) ~[io.airbyte-airbyte-workers-0.35.5-alpha.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
````
## Expected Behavior
*Tell us what should happen.*

## Logs
Complete logs: [logs-25-0 (1).txt](https://github.com/airbytehq/airbyte/files/7902068/logs-25-0.1.txt)

## Steps to Reproduce
1. create a slack source
2. create bigquery destination
3. sync data

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by jrhizor** [comment] 2022-01-21 23:24
@pmossman Would it make sense to use `Hashing.murmur3_128()` and `hashCode.asLong()` instead of `hashCode.hashCode()` to just decrease the chance of collision?

**Comment by pmossman** [comment] 2022-01-22 00:28
@jrhizor I'm currently generating state hashcodes like so:

```
  this.hashFunction = Hashing.murmur3_32_fixed();

  ...

  private int getStateHashCode(final AirbyteStateMessage stateMessage) {
    return hashFunction.hashBytes(Jsons.serialize(stateMessage.getData()).getBytes(Charsets.UTF_8)).hashCode();
  }
```

I just checked the logs that Marcos attached and see that the destination emitted two state messages with duplicate data:
```
state in DefaultReplicationWorker from Destination: io.airbyte.protocol.models.AirbyteMessage@19c1049c[type=STATE,log=<null>,spec=<null>,connectionStatus=<null>,catalog=<null>,record=<null>,state=io.airbyte.protocol.models.AirbyteStateMessage@1706f9d4[data={"channel_messages":{"float_ts":1.6426345051135E9},"threads":{"float_ts":1.6426272352903E9}},additionalProperties={}],additionalProperties={}]

...

state in DefaultReplicationWorker from Destination: io.airbyte.protocol.models.AirbyteMessage@13396fec[type=STATE,log=<null>,spec=<null>,connectionStatus=<null>,catalog=<null>,record=<null>,state=io.airbyte.protocol.models.AirbyteStateMessage@563bf3ef[data={"channel_messages":{"float_ts":1.6426345051135E9},"threads":{"float_ts":1.6426272352903E9}},additionalProperties={}],additionalProperties={}]
``` 

If a destination emits duplicate state like this, we can't reliably compute committed record counts, right?

**Comment by jrhizor** [comment] 2022-01-24 15:57
Oh I didn't realize there was an actual collision. Makes sense that this should be a warning then.

Since https://github.com/airbytehq/airbyte/pull/9657 is merged can we close this?

**Comment by pmossman** [comment] 2022-01-25 17:41
Yeah I think we can close this out. @marcosmarxm since you opened this ticket, the resolution here is that we've changed that ERROR log to a WARN log, because it is expected behavior when duplicate state messages are issued by the destination.

**Closed by pmossman** 2022-01-25 17:41 UTC
Labels: type/bug, needs-triage
