### ISSUE TITLE
Unable to exit onboarding - Stuck on "Set up connection" in 

### ISSUE THREAD

**Issue by duvaldt** [airbytehq/airbyte#1684] opened 2021-01-17 09:52 UTC
## Expected Behavior
I want to be able to skip the onboarding guide, reach some default page or go somewhere other than the last onboarding page.

## Current Behavior
In the final step in the onboarding guide where I setup the connection i get an error, "Fetching the schema is failed. Please try again". I'm unable to go back and change any configuration. I've tried to delete cookies, delete docker images and manually entering another url but it always gets me back to the final step, which is not working.

## Steps to Reproduce
1. git clone repo + docker compose up
2. Add postgres as source
3. Add json file as destination
4. Click next to enter final step
5. In my case I get the error here and can't go anywhere else

## Severity of the bug for you
Critial - Unable to use the software

## Additional context
Ubuntu 20.04, Postgres 12
I have a lot of schemas in my postgres database. Not sure if it's relevant or not.

**Comment by duvaldt** [comment] 2021-01-17 10:12
Somehow I get back to this page even after pulling new docker images:
![image](https://user-images.githubusercontent.com/34833807/104837449-d53f8700-58b4-11eb-8401-6fc22278ef87.png)

**Comment by cgardens** [comment] 2021-01-19 15:57
@duvaldt - The error that is being thrown is because Airbyte is detecting two columns with the same name in a table but they have different types. Looking at the log it looks like one is a varchar and was is an integer. I'm not familiar with why this would be the case. Can you share any insight as to the type of the `supplier_id` column?

Specifically if you could run this query as describe in SO and tell me what the `data_type` is for the `supplier_id`:
```
SELECT column_name,data_type 
FROM information_schema.columns 
WHERE
table_name = 'your_table_name' 
AND table_catalog = 'your_database_name' 
AND table_schema = 'your_schema_name';
```


paraphrasing from the error message you copied above the relevant information.
```
Exception in thread "main" java.lang.RuntimeException: Found multiple columns with same name: supplier_id in table: suppliers but the columns are not the same. columns: [
... 
ColumnInfo{columnName='supplier_id', columnType=VARCHAR}, 
..., 
ColumnInfo{columnName='supplier_id', columnType=INTEGER}, 
...]
```

We are happy to spend some time reproducing this and fixing the issue, but we'll best be able to help if you can help us understand how that column in your database is configured.

**Comment by duvaldt** [comment] 2021-01-19 16:31
Hmm.. been looking around for a while (it's quite a big database), and I think I might have found a "bug".

We don't have a table called suppliers with those fields. But, we have many schemas in our database, and two of those schemas contains a table called suppliers. In one of the tables, the first 10 of the listed columns exists:(ColumnInfo{columnName='publisher_id', columnType=SMALLINT}, ColumnInfo{columnName='supplier_id', columnType=VARCHAR}, ColumnInfo{columnName='org_no', columnType=VARCHAR}, ColumnInfo{columnName='name', columnType=VARCHAR}, ColumnInfo{columnName='city', columnType=VARCHAR}, ColumnInfo{columnName='email', columnType=VARCHAR}, ColumnInfo{columnName='phone', columnType=VARCHAR}, ColumnInfo{columnName='postal_code', columnType=VARCHAR}, ColumnInfo{columnName='created', columnType=TIMESTAMP}, ColumnInfo{columnName='raw', columnType=OTHER})

and in the other table, the three remaining exists:

(  ColumnInfo{columnName='supplier_id', columnType=INTEGER}, ColumnInfo{columnName='br_id', columnType=INTEGER}, ColumnInfo{columnName='supplier_name', columnType=VARCHAR}] ) 

They are referring to two different type of suppliers, that's the reason for the design, and different schemas.

Could it be possible that Airbyte somehow disregards the schemas? 

I have a few suggestions:
1. We have a lot of schemas, would it be possible to print schema-name in the logs?
2. And the most important thing, even if we find out that we have a problem with out DB, I would still like to exit from the onboarding try with a different source when playing around.

Thank you for your response, the software seems really great to work with!

/Mattias

**Comment by cgardens** [comment] 2021-01-19 16:40
aha! that's helpful. just to make sure I understanding you have two separate schemas, in one of them is a table called `suppliers` with a column called `supplier_id` that is a varchar and then in the other schema there is a table called `suppliers` with a column called `supplier_id` that is an integer? that's super helpful, i think i have an idea on where the bug might be.

**Comment by duvaldt** [comment] 2021-01-19 17:03
Yes that is correct :)

**Comment by cgardens** [comment] 2021-01-19 21:55
I have recreated this locally. Looking into what I need to do to fix it now.

**Comment by duvaldt** [comment] 2021-01-19 22:39
Awesome, thanks!

**Comment by cgardens** [comment] 2021-01-19 23:16
A [PR](https://github.com/airbytehq/airbyte/pull/1724) is up to fix this. Hoping that it will be merged and released today. If not today it would be tomorrow morning.

**Closed** 2021-01-20 02:45 UTC
Labels: area/integration, priority/high, type/bug
