### ISSUE TITLE
Product: Sync mode is not saving correctly

### ISSUE THREAD

**Issue by harshithmullapudi** [airbytehq/airbyte#12728] opened 2022-05-10 10:37 UTC
https://discuss.airbyte.io/t/google-search-console-ui-bad-config/920/4

https://user-images.githubusercontent.com/17528887/167610013-06da4f0e-f293-4c40-bf51-daeaf0dbda3c.mov

**Comment by harshithmullapudi** [comment] 2022-05-10 10:37
@danieldiamond can you check the network call and share the request  body here ?

**Comment by MaxKrog** [comment] 2022-05-11 10:57
Same issue here. Seems to be UI related, as sync is working as configured.

**Comment by danieldiamond** [comment] 2022-05-16 23:45
@harshithmullapudi Just upgraded to `0.38.3` and the `github` source connector is completely wiped clean in the UI (all tables unselected, custom format namespace deleted, etc.) . Awful experience, this should be resolved ASAP

**Comment by danieldiamond** [comment] 2022-05-16 23:54
Steps to produce this issue:
- refresh schema
- add new tables
- warning alert appears "You need to reset your connector..."
- Click Okay.
- Entire connector configuration is wiped clean

I then went reconfigure i.e. select tables, readd the custom format namespace etc. And then the other warning sign appears "Do you want to reset your connector" to which I clicked ignore i.e. don't reset. That seemed to leave things as they are.

**Comment by tealjulia** [comment] 2022-05-24 18:41
Both bugs reported in this issue (the original sync mode not saving and the configurations being overwritten) should be resolved in the latest version of Airbyte.  If you still see either in the most recent version, please let us know and if possible provide any information or steps needed to reproduce it.

**Closed by tealjulia** 2022-05-24 18:41 UTC
Labels: type/bug, team/frontend
