### ISSUE TITLE
schedule job can't be cancelled

### ISSUE THREAD

**Issue by answerMA** [airbytehq/airbyte#9776] opened 2022-01-25 03:26 UTC
## Environment
- **Airbyte version**:  example is 0.35.5-alpha
- **OS Version / Instance**: centos
- **Deployment**: Docker
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**: Low 
- **Step where error happened**: Sync job 

## Current Behavior
when the job reports failed, and it keeps running over and over again.

But it can't be cancelled by the 'cancel' button, as I click the button it doesn't give any responses.

So I have to restart whole airbyte servers to make it stop.

As I used API to stop a job, it responsed 500.

    "message": "Internal Server Error: workflowId='connection_manager_749190f6-c7a0-4efa-b1eb-0b728cb2ac70', runId='', workflowType='ConnectionManagerWorkflow'}",
    "exceptionClassName": "io.temporal.client.WorkflowServiceException",
    "exceptionStack": [
        "io.temporal.client.WorkflowServiceException: workflowId='connection_manager_749190f6-c7a0-4efa-b1eb-0b728cb2ac70', runId='', workflowType='ConnectionManagerWorkflow'}",
        "\tat io.temporal.internal.sync.WorkflowStubImpl.query(WorkflowStubImpl.java:351)",

## Expected Behavior
*Tell us what should happen.*

## Logs
Caused by: io.airbyte.workers.WorkerException: Normalization Failed.
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:60) ~[io.airbyte-airbyte-workers-0.35.5-alpha.jar:?]
	at io.airbyte.workers.DefaultNormalizationWorker.run(DefaultNormalizationWorker.java:18) ~[io.airbyte-airbyte-workers-0.35.5-alpha.jar:?]
	at io.airbyte.workers.temporal.TemporalAttemptExecution.lambda$getWorkerThread$2(TemporalAttemptExecution.java:174) ~[io.airbyte-airbyte-workers-0.35.5-alpha.jar:?]
	... 1 more

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by benmoriceau** [comment] 2022-02-02 18:09
Hello @answerMA,

Did you change the `.env` file? In particular the variable named `NEW_SCHEDULER`. It seems that this is using a new implementation of the scheduling part of airbyte. This can be also caused by having the variable set as an environment one in the shell that launches airbyte.

**Comment by marcosmarxm** [comment] 2022-06-14 01:24
Closing this issue because the Scheduler is a deprecated module.

**Closed by marcosmarxm** 2022-06-14 01:24 UTC
Labels: type/bug, area/platform, community, team/oss
