### ISSUE TITLE
Source Mssql : CDC connector cannot handle large update from source (6GB of data)

### ISSUE THREAD

**Issue by sivankumar86** [airbytehq/airbyte#23658] opened 2023-03-02 02:16 UTC
## Environment
- **Airbyte version**:  0.40.18
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: ek8s
- **Source Connector and version**: 0.4.26
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Step where error happened**: when large data update from source
- 
## Current Behavior
   Connector fails without any descriptive error message

## Expected Behavior
   It should complete without error and it may take more time than normal run

## usecase
  -  sync >200 tables from mssql to snowflake 
  -  Created a seperate connection for big tables (one table for one connection)  to avoid resource sharing issue. 

## Logs
  Attached 
[c810ba10_3e93_4c4c_976f_8605746e4520_logs_154332_txt.log](https://github.com/airbytehq/airbyte/files/10866454/c810ba10_3e93_4c4c_976f_8605746e4520_logs_154332_txt.log)

## Steps to Reproduce
1. Enable CDC and run couple for runs 
2. Insert >10 millions rows
3. Run CDC again and it failed with above error. Only it fails with huge traffic 

Work around:
   Reset the table 

## Are you willing to submit a PR?
 Sure, If i get some help on fixing what is the error ? 

Possible solutions:
         Fix the actual issue or apply max records process in each run of CDC like source-kafka connector.

**Comment by marcosmarxm** [comment] 2023-03-03 10:03
If you choose a small table it works?

**Comment by sivankumar86** [comment] 2023-03-04 06:59
@marcosmarxm  Thanks for taking a look. Yes, it works fine for small tables. it is a blocker for us  now.

**Comment by marcosmarxm** [comment] 2023-03-17 13:24
Thanks for reporting it. @sivankumar86 MSSQL is an alpha connector today and it is expected to have some bugs or performance issues. I strongly advice you to increase the pod resource to see if can helps in the sync or try a docker deployment to check if happens too.

**Comment by prateekmukhedkar** [comment] 2023-12-18 19:26
Low hanging fruit to check: Debezium queue size

**Comment by xiaohansong** [comment] 2023-12-27 20:10
locally tested but I cannot reproduce the issue. Tried to inject 10M and 70M records but both syncs finished successfully.

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXlKQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--351e8f10096356669e5dcb4934a5f7d1a521543e/Screenshot%202023-12-27%20at%2012.09.03%E2%80%AFPM.png" alt="Screenshot 2023-12-27 at 12.09.03 PM.png" />

**Comment by xiaohansong** [comment] 2023-12-27 20:11
Logs linked in the original ticket are not complete - seems it was cutoff before the error showed off. Closing this as not reproducible.

**Closed by xiaohansong** 2023-12-27 20:11 UTC
Labels: type/bug, community, area/databases, connectors/source/mssql, team/db-dw-sources
