### ISSUE TITLE
Feature Request: Error messaging for invalid cron input

### ISSUE THREAD

**Issue by TBernstein4** [airbytehq/airbyte#17318] opened 2022-09-28 12:54 UTC
## Tell us about the problem you're trying to solve
There is currently no error messaging when an invalid expression has been input for cron scheduling. The current behavior for trying to save an invalid expression is that after clicking the "Save changes" button the  "Your changes were saved!" message does not appear. There is no indicator that something went wrong. 

## Describe the solution you’d like
Either an error message indicating an invalid cron expression after the "Save changes" button is pushed or an indicator while the cron expression is being input that it is not valid (eg red outline around form field).

## Describe the alternative you’ve considered or used
N/A

## Additional context
Here is the successfully saved message which would be difficult to know to look for.
<img width="1067" alt="Screen Shot 2022-09-28 at 8 48 46 AM" src="https://user-images.githubusercontent.com/104733644/192783414-992034f9-7427-4d5d-a77d-1c2f5888745e.png">

## Are you willing to submit a PR?
Nope, out of my league. Sorry

**Comment by krishnaglick** [comment] 2022-09-28 13:57
We previously had this functionality and it was [removed](https://github.com/airbytehq/airbyte/pull/16792)
If this is re-added, we'll want to do so carefully.

**Comment by lmossman** [comment] 2022-10-13 22:18
@edmundito @krishnaglick FYI I adjusted the labels here - this issue is about the Connection Replication page so I've applied the team/workflow and ui/connection labels

**Comment by timroes** [comment] 2022-10-14 06:58
@josephkmh is this part of the PR you're working on?

**Comment by josephkmh** [comment] 2022-10-14 07:59
@timroes kind of, but currently the error message should be shown anyway after form submission. My PR just adds a quicker validation client-side.

@TBernstein4 could you let me know which invalid expression you were using? I'm not able to reproduce. When I enter an invalid cron I am getting an error message at the bottom of the form:

https://user-images.githubusercontent.com/7550957/195793892-1cb4c8b4-f525-4231-ac7a-6c73792da551.mov

**Comment by TBernstein4** [comment] 2022-10-14 16:06
@josephkmh  The original user issue was using ```0 9-19 * * *``` but I just gave it a try and received the same error messaging you encountered. I do not know what has changed since I originally posted this but it seems to me it has been fixed/added.

Are we good to close this?

**Comment by josephkmh** [comment] 2022-10-14 16:56
@TBernstein4 I'm not sure what would have changed since this was opened, but since everything seems to be working fine and we can't reproduce, fine for me to close this issue 👍

**Closed** 2022-10-14 17:46 UTC
Labels: type/enhancement, area/frontend, needs-triage, team/workflow, team/frontend, ui/connection
