### ISSUE TITLE
Allow a user to cancel a job from the UI

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#1404] opened 2020-12-19 02:28 UTC
## Tell us about the problem you're trying to solve
* If a job is failing and I know it has no hope of succeeding, I would like to cancel it so that Airbyte stops retrying that job.

**Comment by jrhizor** [comment] 2021-03-15 20:27
depends on https://github.com/airbytehq/airbyte/issues/1623, which I'm treating as the backend implementation.

**Comment by jrhizor** [comment] 2021-03-15 20:28
@johnlafleur we'll need a mockup of cancelling a sync job in the UI for Artem to look at.

**Comment by johnlafleur** [comment] 2021-03-16 03:22
Here's the design suggestion: https://www.figma.com/file/AODY4oi15iI5l0fbxHvobt/Daxtarity?node-id=21139%3A295

**Comment by jrhizor** [comment] 2021-03-29 21:14
This is a duplicate of https://github.com/airbytehq/airbyte/issues/2567

**Closed by jrhizor** 2021-03-29 21:14 UTC
Labels: priority/low, type/enhancement
