### ISSUE TITLE
Server is having memory leak

### ISSUE THREAD

**Issue by octavia-squidington-iii** [airbytehq/airbyte#9636] opened 2022-01-20 08:54 UTC
*Is this your first time deploying Airbyte:* No
*Deployment:* GCP (Compute Enginge)
*Airbyte Version:* 0.35.5-alpha
*Memory / Disk:* 16GB / 50GB
*Source name/version:* mysql latest
*Destination name/version:* bigquery latest
*Description:*
airbyte/server container is leaking memory, when I load the UI.
So when I start the docker containers and I check with "docker stats", I don't see anything strange. airbyte/server is using only 2.26% of memory (circa 360Mib).
But the moment I load the UI in my browser it starts eating memory like there is no tomorow. It goes up to 34% (5.3Gib).I dont understand why.
Because of this, when I need to make a full sync and import all my data (for example on a schema update) it hangs because the VM goes out of memory. Did anyone experienced this? What should I do?
Thank you!

 https://airbytehq.slack.com/archives/C01MFR03D5W/p1642621414274300?thread_ts=1642621414.274300&cid=C01MFR03D5W

**Comment by timroes** [comment] 2022-01-20 08:56
Duplicate of https://github.com/airbytehq/airbyte/issues/9620

**Closed by timroes** 2022-01-20 08:56 UTC
Labels: community, slack

**Comment by dtung011** [comment] 2023-06-01 17:29
Hi, my airbyte-server also uses a lot of memory eventhough I only have 1 connection run daily.
Did you guys find any solution for this problem?
