### ISSUE TITLE
Source Postgres: init container: Timeout while attempting to copy to init container, exiting with code 1...

### ISSUE THREAD

**Issue by zebesh** [airbytehq/airbyte#20120] opened 2022-12-06 05:00 UTC
## Environment
- **Airbyte version**:  0.40.23
- **OS Version / Instance**: Digital Ocean
- **Deployment**:  Kubernetes
- **Source Connector and version**: postgres 1.0.30
- **Destination Connector and version**: postgres 0.3.26
- **Step where error happened**: Sync job

## Current Behavior
Some launches fail at the container's init stage.

## Expected Behavior
tasks should run normally

## Logs
2022-12-06 04:34:10 [32mINFO[m i.a.w.p.KubePodProcess(<init>):520 - Creating pod normalization-normalize-1239-2-zklnr...
Log4j2Appender says: Waiting for init container to be ready before copying files...
2022-12-06 04:34:10 [32mINFO[m i.a.w.p.KubePodProcess(waitForInitPodToRun):309 - Waiting for init container to be ready before copying files...
Log4j2Appender says: Init container present..
2022-12-06 04:34:10 [32mINFO[m i.a.w.p.KubePodProcess(waitForInitPodToRun):313 - Init container present..
Log4j2Appender says: Init container ready..
2022-12-06 04:34:12 [32mINFO[m i.a.w.p.KubePodProcess(waitForInitPodToRun):316 - Init container ready..
Log4j2Appender says: Copying files...
2022-12-06 04:34:12 [32mINFO[m i.a.w.p.KubePodProcess(<init>):551 - Copying files...
Log4j2Appender says: Uploading file: destination_config.json
2022-12-06 04:34:12 [32mINFO[m i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):258 - Uploading file: destination_config.json
Log4j2Appender says: kubectl cp /tmp/62b68203-7cb7-4ea1-8910-d019998f510e/destination_config.json airbyte/normalization-normalize-1239-2-zklnr:/config/destination_config.json -c init
2022-12-06 04:34:12 [32mINFO[m i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):266 - kubectl cp /tmp/62b68203-7cb7-4ea1-8910-d019998f510e/destination_config.json airbyte/normalization-normalize-1239-2-zklnr:/config/destination_config.json -c init
Log4j2Appender says: Waiting for kubectl cp to complete
2022-12-06 04:34:12 [32mINFO[m i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):269 - Waiting for kubectl cp to complete
Log4j2Appender says: kubectl cp complete, closing process
2022-12-06 04:34:13 [32mINFO[m i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):283 - kubectl cp complete, closing process
Log4j2Appender says: Uploading file: destination_catalog.json
2022-12-06 04:34:13 [32mINFO[m i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):258 - Uploading file: destination_catalog.json
Log4j2Appender says: kubectl cp /tmp/779539f6-8054-4c02-9278-204b7dc2bf18/destination_catalog.json airbyte/normalization-normalize-1239-2-zklnr:/config/destination_catalog.json -c init
2022-12-06 04:34:13 [32mINFO[m i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):266 - kubectl cp /tmp/779539f6-8054-4c02-9278-204b7dc2bf18/destination_catalog.json airbyte/normalization-normalize-1239-2-zklnr:/config/destination_catalog.json -c init
Log4j2Appender says: Waiting for kubectl cp to complete
2022-12-06 04:34:13 [32mINFO[m i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):269 - Waiting for kubectl cp to complete
Log4j2Appender says: kubectl cp complete, closing process
2022-12-06 04:34:13 [32mINFO[m i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):283 - kubectl cp complete, closing process
Log4j2Appender says: Uploading file: FINISHED_UPLOADING
2022-12-06 04:34:13 [32mINFO[m i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):258 - Uploading file: FINISHED_UPLOADING
Log4j2Appender says: kubectl cp /tmp/4df8d5b5-8873-40f8-b262-a497f76bd3e5/FINISHED_UPLOADING airbyte/normalization-normalize-1239-2-zklnr:/config/FINISHED_UPLOADING -c init
2022-12-06 04:34:13 [32mINFO[m i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):266 - kubectl cp /tmp/4df8d5b5-8873-40f8-b262-a497f76bd3e5/FINISHED_UPLOADING airbyte/normalization-normalize-1239-2-zklnr:/config/FINISHED_UPLOADING -c init
Log4j2Appender says: Waiting for kubectl cp to complete
2022-12-06 04:34:13 [32mINFO[m i.a.w.p.KubePodProcess(copyFilesToKubeConfigVolume):269 - Waiting for kubectl cp to complete
Log4j2Appender says: Waiting for init container to terminate before checking exit value...
2022-12-06 04:34:23 [32mINFO[m i.a.w.p.KubePodProcess(waitForInitPodToTerminate):327 - Waiting for init container to terminate before checking exit value...
Collecting content into /tmp/toBePublished10623042132046911508.tmp before uploading.
Publishing to S3 (bucket=airbyte-dev-logs; key=job-logging/workspace/1239/2/logs.log/20221206043429_airbyte-worker-77b6dc9795-hxswf_9ecba7297c3148e59fbfc9d8c8131f03):
Log4j2Appender says: Init container terminated with exit value 1.
2022-12-06 04:35:15 [32mINFO[m i.a.w.p.KubePodProcess(waitForInitPodToTerminate):332 - Init container terminated with exit value 1.
Log4j2Appender says: Normalization executed in 1 minute 5 seconds.

**Comment by szicari-streambit** [comment] 2022-12-13 18:10
Confirmed this behavior is happening to me on Linode LKE as well. I was successfully running a sync for over 24 hours when I suddenly started getting these errors.

**Comment by sh4sh** [comment] 2022-12-21 20:08
Hey @zebesh @szicari-streambit these job failures are sometimes due to resource issues, can you try adding more resources and see if it helps?

**Comment by stephane-airbyte** [comment] 2024-01-19 18:28
closing. 1 year old, seems to be an infra issue, and no update from the reporter

**Closed by stephane-airbyte** 2024-01-19 18:28 UTC
Labels: type/bug, area/connectors, community, connectors/sources-database, connectors/source/postgres, releaseStage/ga, team/db-dw-sources
