### ISSUE TITLE
Retesting a connector in the UI has no feedback

### ISSUE THREAD

**Issue by timroes** [airbytehq/airbyte#17860] opened 2022-10-11 22:02 UTC
When using the "Retest" button on a saved connector, the retest will run, but there is no visual feedback if the restest was actually successful (and maybe even not when failed -need to validate that).

**Comment by octavia-squidington-iv** [comment] 2022-10-11 22:02
cc @airbytehq/frontend

**Comment by edmundito** [comment] 2022-10-12 13:43
Looked through the code and did notice that when testing a connection succeeds there is no implementation to show a message. Currently, a message only appears when there is an error.

**Comment by flash1293** [comment] 2022-12-05 14:44
Duplicate of https://github.com/airbytehq/airbyte/issues/15731

**Closed by flash1293** 2022-12-05 14:44 UTC
Labels: team/extensibility, team/frontend, ui/connectors
