### ISSUE TITLE
SSL Certificate input for source MySQL

### ISSUE THREAD

**Issue by potatozerg** [airbytehq/airbyte#6985] opened 2021-10-12 22:23 UTC
Currently, we don't have a real SSL connection with certificate for MySQL.
We need to add two input fields, Client Key and Client Certificate.

**Comment by noahkawasakigoogle** [comment] 2022-01-20 23:32
When you say "input" are you asking about a place to upload cert/key files through the UI? Or are you talking about JDBC parameters?

**Comment by potatozerg** [comment] 2022-01-20 23:33
@noahkawasakigoogle I'm talking about a place to upload/input cert/key files. Sorry for the confusion.

**Comment by noahkawasakigoogle** [comment] 2022-01-20 23:38
No worries was just wondering. Im not sure if someones working on this though.

This depends on how you deploy Airbyte, but theoretically you could place the needed files somewhere on an airbyte server, probably with some docker-compose/k8s volume mounts, and then use the [MySQL JDBC parameters](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-connp-props-security.html) to specify those locations to achieve this today as a workaround. Not sure if you're open to that or not.

**Comment by potatozerg** [comment] 2022-01-20 23:41
@noahkawasakigoogle We will need users to enter them, so we can't do that. But thanks for the advice!

**Comment by kodeine** [comment] 2022-03-23 01:34
Same thing is for Postgres on Digital ocean as well. They provide a special cert to make the connection. There's no place in Airbyte to upload those cert. 

Same thing is with Document DB (aws)

**Comment by tuliren** [comment] 2022-07-05 23:22
A similar implementation for Postgres: https://github.com/airbytehq/airbyte/pull/13840

**Comment by edgao** [comment] 2022-07-27 21:17
renamed this issue to be specific to just source-mysql; created https://github.com/airbytehq/airbyte/issues/15086 for the destination side

**Comment by rodireich** [comment] 2022-08-09 22:54
UI for source-mysql ssl information:
1. Disabled mode:
<img width="1096" alt="Screen Shot 2022-08-09 at 3 48 20 PM" src="https://user-images.githubusercontent.com/867491/183775281-c8e6c81c-34ff-4dab-91b5-52546fca3fc4.png">
2. Preferred
<img width="1024" alt="Screen Shot 2022-08-09 at 3 40 03 PM" src="https://user-images.githubusercontent.com/867491/183775334-430b43e7-dc0d-4366-a37e-5055c5205e02.png">
3. Required
<img width="1096" alt="Screen Shot 2022-08-09 at 3 52 57 PM" src="https://user-images.githubusercontent.com/867491/183775445-046dee74-02e8-4efa-b19a-14673821f559.png">
4. Verify-CA
<img width="1024" alt="Screen Shot 2022-08-09 at 3 40 28 PM" src="https://user-images.githubusercontent.com/867491/183775494-cbd71235-ea4c-4999-aac1-dc6fe57b6df9.png">
5. Verify-Identity
<img width="1024" alt="Screen Shot 2022-08-09 at 3 40 36 PM" src="https://user-images.githubusercontent.com/867491/183775531-e8faa47e-d572-4287-a412-9b5266190426.png">

**Comment by rodireich** [comment] 2022-08-11 05:01
Duplicate of #4599

**Closed by rodireich** 2022-08-11 05:01 UTC
Labels: type/enhancement, area/connectors, community, connectors/source/mysql, team/databases
