### ISSUE TITLE
kafka

### ISSUE THREAD

**Issue by lexcr** [airbytehq/airbyte#4899] opened 2021-07-22 00:22 UTC
## Tell us about the new connector you’d like to have
* Which source and which destination?
* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 

## Describe the context around this new connector
* Which team in your company wants this integration, what for? This helps us understand the use case.
* How often do you want to run syncs?
* If this is an API source connector, which entities/endpoints do you need supported?

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?

## Are you willing to submit a PR?

Remove this with your answer :-)

**Comment by sherifnada** [comment] 2021-07-22 01:15
duplicate of #2655 and #1855, @lexcr could you add any context to the appropriate issue there?

**Closed by sherifnada** 2021-07-22 01:15 UTC
Labels: area/connectors, new-connector
