### ISSUE TITLE
[EPIC] Gradle Caching

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#11130] opened 2022-03-15 01:12 UTC
## Describe the solution you’d like
When I run `./gradlew build` twice in a row, it should be instantaneous. Right now it takes multiple minutes.

## Execution Plan
* [ ] - https://github.com/airbytehq/airbyte/issues/11131
* [ ] - https://github.com/airbytehq/airbyte/issues/11132
* [ ] - https://github.com/airbytehq/airbyte/issues/19784
* [ ] ... add known gradle caching issue here.

**Comment by andyjih** [comment] 2022-10-06 22:24
cc @salima-airbyte to follow-up

**Comment by davinchia** [comment] 2023-04-06 23:32
This is a duplicate of https://github.com/airbytehq/airbyte-platform-internal/issues/4947.

**Closed by davinchia** 2023-04-06 23:32 UTC
Labels: type/enhancement, Epic, team/platform-compose, team/platform-move
