### ISSUE TITLE
Quoted table names in postgre source fail

### ISSUE THREAD

**Issue by cgardens** [airbytehq/airbyte#2007] opened 2021-02-09 00:23 UTC
Discovered while investigating: https://github.com/airbytehq/airbyte/issues/1926

## Current Behavior
* tables created using quoted syntax in Postgres break airbyte. e.g. if my table name is "Albatross2", Airbyte looks for public.albatross2 (which doesn't exist) and fails.

## Expected Behavior
* we should be able to handle quoted names

## Steps to Reproduce
* get a postgres intsance.
* create a table. `CREATE TABLE "Albatross2"(id varchar);`
* run airbyte

## Airbyte Version
0.14.1

## Additional context
* have not tested this for other jdbc sources, but the behavior is likely the same.

**Comment by haithem-souala** [comment] 2021-02-10 12:23
Same issue for columns name.
We've a source table with column "retailerId", in the destination database, i found "retailerid", so the sync fail.

Source: Postgres
Destination: Postgres

`
2021-02-10 12:17:32 ERROR (/tmp/workspace/21/1) LineGobbler(voidCall):69 - Exception in thread "main" java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: column "retailerid" does not exist
2021-02-10 12:17:32 ERROR (/tmp/workspace/21/1) LineGobbler(voidCall):69 -   Hint: Perhaps you meant to reference the column "billing.retailerId".
2021-02-10 12:17:32 ERROR (/tmp/workspace/21/1) LineGobbler(voidCall):69 -   Position: 37
2021-02-10 12:17:32 ERROR (/tmp/workspace/21/1) LineGobbler(voidCall):69 - 	at io.airbyte.db.jdbc.StreamingJdbcDatabase.query(StreamingJdbcDatabase.java:108)
2021-02-10 12:17:32 ERROR (/tmp/workspace/21/1) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.queryTableFullRefresh(AbstractJdbcSource.java:377)
2021-02-10 12:17:32 ERROR (/tmp/workspace/21/1) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.getFullRefreshStream(AbstractJdbcSource.java:274)
2021-02-10 12:17:32 ERROR (/tmp/workspace/21/1) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.createReadStream(AbstractJdbcSource.java:225)
2021-02-10 12:17:32 ERROR (/tmp/workspace/21/1) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.source.jdbc.AbstractJdbcSource.read(AbstractJdbcSource.java:176)
2021-02-10 12:17:32 ERROR (/tmp/workspace/21/1) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.base.IntegrationRunner.run(IntegrationRunner.java:103)
2021-02-10 12:17:32 ERROR (/tmp/workspace/21/1) LineGobbler(voidCall):69 - 	at io.airbyte.integrations.source.postgres.PostgresSource.main(PostgresSource.java:72)
2021-02-10 12:17:32 ERROR (/tmp/workspace/21/1) LineGobbler(voidCall):69 - Caused by: org.postgresql.util.PSQLException: ERROR: column "retailerid" does not exist
2021-02-10 12:17:32 ERROR (/tmp/workspace/21/1) LineGobbler(voidCall):69 -   Hint: Perhaps you meant to reference the column "billing.retailerId".
`

**Comment by cgardens** [comment] 2021-02-15 19:59
likely will solve https://github.com/airbytehq/airbyte/issues/1991 as well

**Comment by jrhizor** [comment] 2021-02-16 17:40
Unable to reproduce in Airbyte 0.14.2-alpha with source-postgres 0.1.13.

Creating values in the source:
```
→ docker exec -it 00a58dacc8ef psql -U postgres
psql (13.1 (Debian 13.1-1.pgdg100+1))
Type "help" for help.

postgres=# CREATE TABLE "Albatross2"(id varchar);
CREATE TABLE                     ^
postgres=# INSERT INTO "Albatross2" (id) VALUES ('text');
INSERT 0 1
postgres=# INSERT INTO "Albatross2" (id) VALUES ('text2');
INSERT 0 1
postgres=# INSERT INTO "Albatross2" (id) VALUES ('text3');
INSERT 0 1
```

Reading them post sync (with normalization enabled):
```
→ docker exec -it 50d11c87ea46 psql -U postgres
psql (13.1 (Debian 13.1-1.pgdg100+1))
Type "help" for help.

postgres=# select * from "public_Albatross2";
    _airbyte_emitted_at     |   _airbyte_normalized_at   |  id   | _airbyte_publ
ic_albatross2_hashid
----------------------------+----------------------------+-------+--------------
---------------------
 2021-02-16 17:37:41.829+00 | 2021-02-16 17:37:45.151971 | text  | 1cb251ec0d568
de6a929b520c4aed8d1
 2021-02-16 17:37:41.829+00 | 2021-02-16 17:37:45.151971 | text2 | fe6123a759017
e4a2af4a2d19961ed71
 2021-02-16 17:37:41.829+00 | 2021-02-16 17:37:45.151971 | text3 | 265246eadd253
90e2406a0d9bd22242b
(3 rows)
```

**Comment by jrhizor** [comment] 2021-02-16 17:50
I tried reproducing it on Airbyte 0.14.2-alpha with source-postgres 0.1.12 and I am seeing the failure described. Since it looks like upgrading to the latest source-postgres will fix the problem, I'm closing this ticket.

**Closed by jrhizor** 2021-02-16 17:50 UTC
Labels: area/integration, priority/high, type/bug

**Comment by haithem-souala** [comment] 2021-02-17 10:23
It works like a charm.
Thank you @cgardens & @jrhizor
