### ISSUE TITLE
CLI and Declarative Configuration

### ISSUE THREAD

**Issue by alexkreidler** [airbytehq/airbyte#1860] opened 2021-01-27 15:37 UTC
## Tell us about the problem you're trying to solve
As a developer, I want to be able to manage the data pipeline in human-readable configuration files rather than a UI. Then the entire state of the system is visible on-disk, similar to Terraform or Kubernetes. I really love the DX of Kubernetes-style APIs and CLIs.

## Describe the solution you’d like
It would be great to have a CLI tool for AirByte that accepts declarative configurations in YAML, JSON or other formats so that I can 

* validate source configs
* view data catalogs
* validate destination configs
* and submit source & destination configs to the API
I also want to be able to delete and edit configs via the CLI.

## Additional thoughts
Pardon my excessive buzzwords, but a GitOps/DevOps/DataOps pattern like this allows users to have multiple data environments and use Git to push new data pipeline configurations.

Let me know if you have thoughts or questions!

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368085951988) by [Unito](https://www.unito.io)

**Comment by ChristopheDuong** [comment] 2021-01-27 15:43
Thanks for the suggestion!!

Have you tried this new feature yet? 
https://docs.airbyte.io/tutorials/upgrading-airbyte

You should have a look at the produced archive files, maybe we could build something on top of that to converge to what you are proposing here

**Comment by jrhizor** [comment] 2021-01-27 20:17
Not endorsing https://github.com/signalfx/swagger-cli-client specifically, but maybe something like that could be used to support a CLI wrapper for our API?

**Comment by michel-tricot** [comment] 2021-01-27 23:29
nice. If it can brings us to 80% of what we want that's great.

We need to check to make sure that it works with the slack style API

**Comment by jrhizor** [comment] 2021-01-28 00:51
Looked a bit more at `swagger-cli-client`. It isn't maintained and doesn't even support OpenApi v3. 

However I can do something with Restish which seems pretty good.

```
# cat ~/.restish/apis.json
 {
   "airbyte": {
     "base": "http://localhost:8001",
      "spec_files": ["/Users/jrhizor/code/airbyte/airbyte-api/src/main/openapi/config.yaml"]
    }
 }
```

**Comment by jrhizor** [comment] 2021-01-28 01:04
Some more examples:

```
→ restish airbyte listsourcesforworkspace -h
List sources for workspace. Does not return deleted sources.
## Request Schema (application/json)

```schema
{
  workspaceId*: (string format:uuid)
}
```

## Response 200 (application/json)

Successful operation

```schema
{
  sources*: [
    {
      connectionConfiguration*:
      name*: (string)
      sourceDefinitionId*: (string format:uuid)
      sourceId*: (string format:uuid)
      sourceName*: (string)
      workspaceId*: (string format:uuid)
    }
  ]
}
```

and

```
→ restish airbyte listsourcesforworkspace workspaceId:5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6 -f "body"
{
  "sources": [
    {
      "connectionConfiguration": {
        "dataset_name": "table",
        "format": "csv",
        "provider": {
          "storage": "HTTPS"
        },
        "url": "https://raw.githubusercontent.com/coronatrends/coronatrends.github.io/acf3b28a58d68dcc1e337fb4b2a0555edcc4b52a/data/cities.csv"
      },
      "name": "file",
      "sourceDefinitionId": "778daa7c-feaf-4db6-96f3-70fd645acc77",
      "sourceId": "dc9c124f-2331-48c7-9802-850ed82827e9",
      "sourceName": "File",
      "workspaceId": "5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"
    },
    {
      "connectionConfiguration": {
        "dataset_name": "table1",
        "format": "csv",
        "provider": {
          "storage": "local"
        },
        "url": "/local/file.txt"
      },
      "name": "a",
      "sourceDefinitionId": "778daa7c-feaf-4db6-96f3-70fd645acc77",
      "sourceId": "0c8e9132-f8d1-4fd4-98b1-8aa003795106",
      "sourceName": "File",
      "workspaceId": "5ae6b09b-fdec-41af-aaf7-7d94cfc33ef6"
    }
  ]
}
```

The default output has the headers on top. `-o json` creates an object that contains the headers and the body as keys in an object. `-f "body"` contains just the response which you'd probably want in most cases.

**Comment by jrhizor** [comment] 2021-01-28 01:28
To make this actually usable we should make a `./tools/airbyte-cli` script that:
1. uses a version of `restish` contained in docker that uses the API_URL from .env or the default
2. make the api publish the config.yaml so we can just point there
3. change the api server url
4. add some info on docs.airbyte.io on how to use it

**Comment by alexkreidler** [comment] 2021-01-28 15:45
Hey all, thanks for the comments.

@ChristopheDuong no I haven't tried that feature

@jrhizor Restish looks really promising and it seems like it could make this fairly simple to implement, which is great. It definitely would be a great first step.

I will add a few more thoughts though. These are a little more complex and some might require a fork of Restish (hopefully with contributions back upstream):
1. It might be nice to use **more friendly subcommand-style names** like `airbyte check destination` vs `airbyte checkconnectiontodestination`, and `airbyte delete source` vs `airbyte deletesource`. This potentially could be done by creating individual mappings from subcommands like: `{"check destination": "checkconnectiontodestination"}` that would convert to the OpenAPI command, or creating some general "rules" like `create + <type> = create<type>`. It seems like option 1 would require less work to allow the existing features to provide documentation, etc, because option 2 could fail fairly often if invalid objects are provided. One consideration here is that these mappings or rules would be distributed with the code, which somewhat goes against Restish's mantra of being a generic HTTP client. Maybe there would be a way to add some custom annotations to the OpenAPI schema that indicate what the CLI command name should be for a given operation. This seems cleanest, but would also be nonstandard.
2. How does Restish do **error checking**? Does it do at least a cursory verification that the schema is valid according to the OpenAPI config? Are the errors reported in a human-readable format or can they be machine readable? These questions aren't answered in Restish docs, so that would be good to investigate
3. **Files and the create command** (delete and update too): Right now Restish accepts items from standard input, which is awesome. However, the CLI requires the user to know beforehand the type of the object they want to create and use the appropriate command-- let's say `createdestination`, and then invoke like `airbyte createdestination <my-dest.json`. In my view, the **most** ergonmic experience would be to have one command like `airbyte create -f my-dest.json` that changes which API method to call based on some data in the file (like a `type` field). Then the user can arrow-up in the terminal and only change the file name, potentially to a file of a different type, and the command would run. This would require probably the most work to get the validation/error checking to work based on the type of the resource.
4. **Recursive create**: Kubernetes allows virtually every command `kubectl apply/update/delete -f <directory>` to be called with a directory, as shown here. This allows users to manipulate swaths of configuration at once, and is one of the key tools making it DevOps-friendly. Otherwise, users would have to do it manually, or write a script. This mainly depends on point 3, allowing for a "generic creation" method. Once that's done, directory create would just select a glob of filenames supported in the directory provided (e.g. JSON, YAML, etc) and iterate over that generic create method. Depending on how each object inter-depends on existing objects or objects that need to be created in that batch, the client could parse, validate, issue all those create requests concurrently.

I know this is somewhat a lot, and Restish would be great to start. Other users may not have the same preferences with regard to CLI design/DX, so it would be probably good to get more user feedback before going down the path I've mentioned. But I do think there are plenty of benefits that make it worthwhile. Let me know if you have any questions in particular about this style of CLI.

Thanks for thinking about this and looking at some solutions!

**Comment by jrhizor** [comment] 2021-01-28 18:15
1. There is a way to create custom annotations in Restish, but not with spaces I believe. We could easily override the names of operations with a `x-cli-name` property in the open api spec file: `check-connection-to-destination` for example, which is much more readable, even if it doesn't group by operation.
2. Yeah I'll check error reporting
3 & 4: A manifest-focused CLI is definitely is an exciting idea! We'll keep this in mind, but it seems unlikely we'll work on this short term. I don't think we want to commit to maintaining a translation layer between manifests and api calls quite yet (the api is evolving fairly rapidly). 

I think it's likely we'll do the slightly cleaned up Restish wrapper in the short term and consider manifests long term.

**Comment by jrhizor** [comment] 2021-03-07 23:19
Reopening because the PR only added a version of the CLI, not the declarative piece.

**Comment by delucca** [comment] 2021-07-22 15:09
Trying to contribute regarding this issue, ArgoCD has a pretty good declarative configuration for Kubernetes. They use Kubernetes CRDs to achieve that.

IMHO (at least for Kubernetes) this is the optimal way to handle declarative configurations, because we could write new sources, destinations, and connections as CRD manifests.

**Comment by harshithmullapudi** [comment] 2021-08-12 13:43
https://github.com/harshithmullapudi/airbyte-cli I tried approaching this problem. Happy to take any suggestions.

**Comment by marcosmarxm** [comment] 2022-04-27 20:02
This is not a duplicate of https://github.com/airbytehq/airbyte/issues/2474?

**Closed** 2022-06-09 21:49 UTC
Labels: type/enhancement, team/oss
