### ISSUE TITLE
editing a oneOf config doesn't show the selected sub-schema 

### ISSUE THREAD

**Issue by jrhizor** [airbytehq/airbyte#962] opened 2020-11-12 23:06 UTC
## Expected Behavior
If you go to the source settings page for the File source with `Local Filesystem` selected on setup, you would expect to see  the `Local Filesystem` set of options immediately.

## Current Behavior
 Right now, you have to click through the dropdown to show the correct settings (it looks misconfigured until you do).

**Comment by ChristopheDuong** [comment] 2020-11-16 15:59
Local Filesystem does not actually have any dedicated options...

In the spec.json, there's only the `storage` field as child to provide the correct expected value for that option but no other parameters are customizable

**Comment by jrhizor** [comment] 2020-11-16 17:30
Yeah but it still shouldn't show the options for something besides local. The options (even if that's an empty set) should match what you previously selected when you start editing.

**Comment by cgardens** [comment] 2020-11-16 23:18
@jrhizor - can you do a gif? and then i'll assign it to artem.

**Comment by ChristopheDuong** [comment] 2020-11-18 14:48
BTW for the local filesystem option of the source file, would it be possible that:
- the UI allows browsing anywhere on your local filesystem
- when a file is selected, it is copied over to the /local/ folder 
- then the catalog.json sent to the source-file connector would have the url field with /local/ and the filename of the selected file

It would make the UX smoother for this option

**Comment by cgardens** [comment] 2020-11-18 16:21
@ChristopheDuong what you are describing is a different feature. Feel free to create a separate issue for it!

**Comment by cgardens** [comment] 2020-11-23 04:28
assigning to @jrhizor to add how to reproduce this. we can reassign when that's done!

**Comment by jrhizor** [comment] 2021-01-25 19:25
Hubspot is one example:

![Screen Cast 2021-01-25 at 11 24 17 AM](https://user-images.githubusercontent.com/120362/105755329-0268e680-5f00-11eb-892b-a7b395c9c602.gif)

**Comment by jrhizor** [comment] 2021-01-27 01:20
This is still happening:

I would expect editing the settings to show me the local file options that are filled as opposed to the HTTPS default which is empty.

![Screen Cast 2021-01-26 at 5 17 38 PM](https://user-images.githubusercontent.com/120362/105928349-a636bd00-5ffa-11eb-87de-3e84de37c2ca.gif)

**Comment by Jamakase** [comment] 2021-02-12 13:01
Ok, so the problem is that some sources work correct and others not.

Just some info on how I analyse what path is currently selected and which one is not: 

this is what we receive for json_schema for hubspot
specification:
```
{
  "connectionSpecification": {
    "properties": {
      "credentials": {
        "type": "object",
        "oneOf": [
          {
            "title": "api key",
            "required": [
              "api_key"
            ],
            "properties": {
              "api_key": {
                "type": "string"
              }
            }
          },
          {
            "title": "oauth",
            "required": [
              "client_id"
            ],
            "properties": {
              "client_id": {
                "type": "string",
                "examples": [
                  "123456789000,"
                ]
              }
            }
          }
        ]
      }
    },
    "additionalProperties": false
  }
}
```
configuration:
```
{
  "connectionConfiguration": {
    "credentials": {
      "refresh_token": "1",
      "client_secret": "1",
      "redirect_uri": "1",
      "client_id": "1"
    }
  }
}
```
So as you see there is no way to understand what path is actually currently selected, because our top level schema doesn't have anything like id or something like that we can use to identify the path.

What we are doing instead - we are checking that fields that are returned from backend match some path in json_schema and for hubspot it works just fine.


Now what's the problem with file source:
```
{
  "provider": {
    "type": "object",
    "oneOf": [
      {
        "title": "HTTPS: Public Web",
        "required": [
          "storage"
        ],
        "properties": {
          "storage": {
            "enum": [
              "HTTPS"
            ],
            "type": "string",
            "default": "HTTPS"
          }
        }
      },
      {
        "title": "Local Filesystem (limited)",
        "required": [
          "storage"
        ],
        "properties": {
          "storage": {
            "enum": [
              "local"
            ],
            "type": "string"
          }
        }
      }
    ]
  }
}
```
As you see both of them have field storage. However, it looks like they have different enum properties.

I am not sure what other rare cases we can face with json_schema, but I do not think that's evident at all, that we try to distinguish selected path based on enum value selected in one of the properties. 

I am going to improve how we understand what schema is currently selected and hope that would be enough to support all cases.

**Closed** 2021-02-23 23:08 UTC
Labels: area/frontend, priority/medium, type/bug
