### ISSUE TITLE
Incremental + dedup is not cleaning up deleted records 

### ISSUE THREAD

**Issue by anand-srinivaas** [airbytehq/airbyte#10140] opened 2022-02-07 08:10 UTC
## Environment
- **Airbyte version**:  Latest Dev
- **OS Version / Instance**: example macOS 
- **Deployment**: Docker
- **Source Connector and version**: Hubspot
- **Destination Connector and version**: Postgres
- **Severity**: High 
- **Step where error happened**: Sync job 

## Current Behavior

Hi , a newbie question here .. i'm trying to get Incremental + Dedup sync from Hubspot to Postgres.. when it comes new record or any other updates to existing record, sync is happening properly, however i read Deleted records at source is not getting updated to the destination 

## Expected Behavior
If a record at source got deleted, it should cleaned up at destination as well. [ as part of incremental similar Full Refresh + overwrite ]

**Comment by ordonezf** [comment] 2022-02-07 19:14
I'm having the same issue using postgres as source and destination.

I can see the empty json in _airbyte_raw with the deleted id and the deleted_at flag in _scd table but not in the main table.

I'm on version 0.35.18-alpha deployed on kubernetes 1.20

**Comment by edgao** [comment] 2022-07-20 15:55
Hey @anand-srinivaas @ordonezf  - I think this was fixed in v0.39.19-alpha (https://github.com/airbytehq/airbyte/pull/12846/); if you try again it should function as expected.

**Comment by ordonezf** [comment] 2022-07-20 16:14
> Hey @anand-srinivaas @ordonezf - I think this was fixed in v0.39.19-alpha (#12846); if you try again it should function as expected.

Thanks @edgao! I've been following that thread so I was aware of it. I still haven't had the time to try it but will definitely do it sometime soon :)

**Comment by anand-srinivaas** [comment] 2022-07-20 16:56
Thanks @edgao  - Will check this one.

**Comment by tim-sauchuk** [comment] 2022-08-02 20:27
I'm also finding that deleted rows are not being deleted in the destination when I run incremental + dedup from Postgres -> Postgres. I've also pulled the latest version of Airbyte. Any troubleshooting ideas?

**Comment by edgao** [comment] 2022-08-02 21:09
@tim-sauchuk can you submit a bug report (https://github.com/airbytehq/airbyte/issues/new?assignees=&labels=type%2Fbug%2C+needs-triage&template=bug-report.md&title=) ? The template will ask for some troubleshooting information which would help us narrow down what's happening.

**Closed** 2024-03-20 20:46 UTC
Labels: type/bug, area/connectors, normalization, community, area/databases, connectors/destinations-database, connectors/destination/postgres, team/destinations

**Comment by spagnoloe-amenitiz** [comment] 2024-09-03 08:52
Hello there, I am not really sure about the status of this. I currently have several connections from PostgreSQL -> Redshift configured as incremental + dedup syncs.
However, I have found that there are records in my destination that are no longer in the source because they were deleted. Hence it seems that deleted records on source are not deleted in the destination, at least for me.

What is the status of this issue? Can we expect to have deletes on destination with Airbyte?

**Comment by edgao** [comment] 2024-09-03 15:21
sources configured to use CDC will propagate deletes. Are you using source-postgres with CDC? or are you on xmin/user-defined cursor?

(the latter two will _not_ send deletes. If that's something you need, I'd recommend either using CDC, or running in full refresh overwrite.)

**Comment by spagnoloe-amenitiz** [comment] 2024-09-03 18:54
> sources configured to use CDC will propagate deletes. Are you using source-postgres with CDC? or are you on xmin/user-defined cursor?
> 
> (the latter two will _not_ send deletes. If that's something you need, I'd recommend either using CDC, or running in full refresh overwrite.)

Hi @edgao thanks for the hint! Yes I check the documentation and I noticed that only CDC supports deletes. The problem is that, if I understand correctly, configuring CDC has some caveats that limit us to make some progress:

- We need to implement all these steps (note that this has to be enabled on every table, so it will not be available by default).
![image](https://github.com/user-attachments/assets/0a8842d9-9303-4ae1-ac92-faec48ab5337)

- This is not available if we operate on a read replica
![image](https://github.com/user-attachments/assets/8a63f7a4-7dbd-4d51-85e1-0466b9f9bb8b)

Since we are reading data only, it is hard to justify connecting to a write instance :(

Other solutions like Hightouch for example implement this with diffing (see [here](https://hightouch.com/docs/getting-started/concepts#how-change-data-capture-works)), by keeping a log of all the records that were available from the last sync, and hence detecting the records to delete can be done by comparing the current records with the last run. Is that something that could make sense to implement this feature without all those requirements for CDC?

Thank you

**Comment by evantahler** [comment] 2024-09-03 21:59
> Other solutions like Hightouch for example implement this with diffing (see [here](https://hightouch.com/docs/getting-started/concepts#how-change-data-capture-works)), by keeping a log of all the records that were available from the last sync, and hence detecting the records to delete can be done by comparing the current records with the last run. Is that something that could make sense to implement this feature without all those requirements for CDC?

@spagnoloe-amenitiz That's not something on our short-term roadmap (e.g. 2024), but is be something we want to be the medium term!
