### ISSUE TITLE
MyPy tasks in AirbytePython plugin not working.

### ISSUE THREAD

**Issue by davinchia** [airbytehq/airbyte#3192] opened 2021-05-03 21:49 UTC
## Expected Behavior
This is not running.

## Current Behavior
The plugin is currently written to execute on some configuration. However this configuration is always null when the task is configured, so even though it's later passed in, MyPy never executes on the right modules.

## Severity of the bug for you
Very low - doesn't affect development.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368164350621) by [Unito](https://www.unito.io)

**Comment by maxi297** [comment] 2023-01-31 19:17
Duplicate of https://github.com/airbytehq/airbyte/issues/14907

**Closed by maxi297** 2023-01-31 19:17 UTC
Labels: type/bug, build, technical-debt, team/extensibility
