### ISSUE TITLE
MySQL CDC: keep waiting when the state is completely empty or missing for any table

### ISSUE THREAD

**Issue by tuliren** [airbytehq/airbyte#15249] opened 2022-08-03 16:50 UTC
This is a follow-up of https://github.com/airbytehq/airbyte/issues/14890.

**Comment by edgao** [comment] 2022-08-30 23:53
sprint update: I didn't make any concrete progress on this issue :/

**Comment by grishick** [comment] 2022-09-06 18:15
Note from grooming: the change will be universal for all connectors using Debezium 1.9.2

**Comment by grishick** [comment] 2022-09-06 18:17
Adding to MySQL GA Epic, because this problem shows up in MySQL Source

**Comment by bleonard** [comment] 2022-09-30 20:39
@rodireich think this is related to https://github.com/airbytehq/airbyte/issues/15040

**Comment by bleonard** [comment] 2022-11-21 23:54
@rodireich @subodh1810 What you think the status of this is? If there's something to do, can you add a better description?

**Comment by bleonard** [comment] 2023-02-22 18:27
Duplicate of #23257

**Closed by bleonard** 2023-02-22 18:27 UTC
Labels: connectors/source/mysql, team/db-dw-sources
