### ISSUE TITLE
De-nest ConnectorManagerWorkflow tests

### ISSUE THREAD

**Issue by evantahler** [airbytehq/airbyte#15887] opened 2022-08-23 17:27 UTC
After converting `airbyte-worker` to Micronaut, we should take the time to clean up the ConnectorManagerWorkflow test suite.
* it's huge, and therefore hard to follow
* it's nested and hard to run a single test

**Comment by davinchia** [comment] 2023-04-11 18:42
Duplicate of #10959

**Closed by davinchia** 2023-04-11 18:42 UTC
Labels: team/platform-move
