### ISSUE TITLE
source-postgres docs page in product: undefined is not an object (evaluating 's.split')

### ISSUE THREAD

**Issue by Bzhash420** [airbytehq/airbyte#46681] opened 2024-10-09 17:17 UTC
### Connector Name

source-postgres

### Connector Version

3.6.21

### What step the error happened?

Other

### Relevant information

<img width="1389" alt="Screenshot 2024-10-09 at 13 12 00" src="https://github.com/user-attachments/assets/ace9b294-2ace-4c4e-a045-cecb34c91ffa">

When I click on the postgres source connector, I can't configure it because I have this error directly

### Relevant log output

```shell
{
  "url": "http://localhost:8000/workspaces/752b54b6-01dc-42dd-83fe-63685b830aba/source/new-source/decd338e-5647-4c0b-adf4-da0e75f5a750",
  "airbyteVersion": "1.1.0",
  "errorType": "TypeError",
  "errorConstructor": "TypeError",
  "error": {},
  "stacktrace": "ne@http://localhost:8000/assets/DocumentationPanel-m4r58wojbs.js:2:738\ncR@http://localhost:8000/assets/core-icl96mliue.js:38:19552\nAB@http://localhost:8000/assets/core-icl96mliue.js:40:44101\nTB@http://localhost:8000/assets/core-icl96mliue.js:40:39822\nate@http://localhost:8000/assets/core-icl96mliue.js:40:39749\npb@http://localhost:8000/assets/core-icl96mliue.js:40:39600\no3@http://localhost:8000/assets/core-icl96mliue.js:40:35961\nh8@http://localhost:8000/assets/core-icl96mliue.js:40:36766\nQu@http://localhost:8000/assets/core-icl96mliue.js:38:3288\n@http://localhost:8000/assets/core-icl96mliue.js:40:34287",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.1 Safari/605.1.15",
  "featureFlags": {}
}
```

### Contribute

- [ ] Yes, I want to contribute

**Comment by tturkenitz** [comment] 2024-10-10 12:49
Looks like a duplicate of https://github.com/airbytehq/airbyte/issues/46346

**Comment by natikgadzhi** [comment] 2024-10-12 19:53
Yep, it is indeed the duplicate of https://github.com/airbytehq/airbyte/issues/46346. I'll close this one, let's chat there instead.

**Closed by natikgadzhi** 2024-10-12 19:53 UTC
Labels: type/bug, area/connectors, community, needs-triage, team/connectors-python, autoteam
