### ISSUE TITLE
Missing Hubspot Associations Data

### ISSUE THREAD

**Issue by gustavoguerra95** [airbytehq/airbyte#14639] opened 2022-07-12 19:51 UTC
## Tell us about the problem you're trying to solve
I recently noticed that when used Incremental modes in the BigQuery connector i do not get any information regarding associations. I.e. My deals table has no records on companies, contacts or line_items. While if I use Full Overwrite mode I can get the associated companies and contacts (while still no Line Items) correctly. I wonder if this behaviour is expected due to the limitations of the Hubspot API or if this is an actual issue. 

Even if there were a pure associations columns with the untreated JSON it would be better, since associations are a vital part of data analysis in Hubspot.

## Describe the solution you’d like
A way to correctly get associations data.

## Describe the alternative you’ve considered or used
Having a column with the pure associations JSON would solve the problem, since it would be possible then to extract this data using SQL. Now it is impossible to get this data.

## Are you willing to submit a PR?
Yes

**Comment by faacsousa** [comment] 2022-07-13 12:56
This seems to be Duplicate of #14390

**Comment by marcosmarxm** [comment] 2022-07-13 17:20
thanks for pointing @faacsousa

**Closed** 2022-07-13 17:20 UTC
Labels: type/enhancement, community, needs-triage, team/use, autoteam
