### ISSUE TITLE
MSSQL --> BQ Sync dropping records

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#2832] opened 2021-04-09 20:38 UTC
## Description
Context: https://airbytehq.slack.com/archives/C01MFR03D5W/p1617199919214300

Some records coming from MSSQL are not being deserialized and are being dropped in the sync worker. An example record the user reported: 

```
{
  "type": "RECORD",
  "record": {
    "stream": "stream",
    "data": {
      "TransactionRecordId": 422432,
      "chargedamount": 92,
      "chargedfxrate": 1.25642035,
      "client": "okkjpbhcozubegqvralmrlpkdyjodv🌳🌳🌳🌳🌳🌳🌳🌳🌳wyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv",
      "customername": "okkjpbh™™A@';\\\"cozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv",
      "customeraddress": "okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv",
      "customeremail": "okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv",
      "customermobile": "okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv",
      "customerid": 21900,
      "fixedfee": 0,
      "fixedfeepercentage": 0,
      "fxspreadpercentage": 3.5,
      "sendingamount": 92,
      "clientipaddress": "okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv",
      "isownbehalf": true,
      "isreverse": false,
      "laststatusrequest": "2019-04-02T10:40:01Z",
      "provider": 2,
      "providertransactionid": "2120921",
      "providerfxrate": 1,
      "receivingamount": 115.5907,
      "receivingcurrency": "USD",
      "ratetosek": 12.090413,
      "ratetosekrealtime": 12.17809,
      "receiveraddress": "okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv",
      "receiverid": 155040,
      "receivermobilecountrycode": "252",
      "receivermobile": "okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv",
      "receivername": "okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv",
      "receivingcountryalpha3": "SSS",
      "state": 6,
      "sendingcurrency": "GBP",
      "sendingcountryalpha3": "GBR",
      "sendingfxrate": 1.25642035,
      "sendinginterbankrate": 1.30199,
      "sendinginterbankraterealtime": 1.312431,
      "remittancetype": "okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv",
      "settlementcurrency": "okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv",
      "setteledamount": 119.7831,
      "transactionid": "BKM-ENMU7IIJ4",
      "transactiontime": "2019-04-01T15:33:58Z"
    },
    "emitted_at": 1617693523558
  }
}

```

as showing up in the logs from `IntegrationTestRunner.java:134`. 

## Logs
user will provide logs 

## Steps to Reproduce
TBD -- still trying to determine why the record is being dropped. The problem is that the record is not being deserialized correctly (and is therefore being logged) but we still haven't figured out exactly why it is not deserializing. 

## Severity of the bug for you
High

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1200367912513076/1200368100567851) by [Unito](https://www.unito.io)

**Comment by sayowayah** [comment] 2021-05-07 06:42
I've also encountered this issue. Can provide my details if needed.

**Comment by jrhizor** [comment] 2021-05-07 16:32
There's some indication here that some kind of new lines might not be captured properly as well https://airbytehq.slack.com/archives/C01MFR03D5W/p1620392507061000?thread_ts=1620314953.027000&cid=C01MFR03D5W

**Comment by jrhizor** [comment] 2021-05-07 19:50
Just trying to deserialize what you have there appears to work:
```
String record = "{\n" +
            "  \"type\": \"RECORD\",\n" +
            "  \"record\": {\n" +
            "    \"stream\": \"stream\",\n" +
            "    \"data\": {\n" +
            "      \"TransactionRecordId\": 422432,\n" +
            "      \"chargedamount\": 92,\n" +
            "      \"chargedfxrate\": 1.25642035,\n" +
            "      \"client\": \"okkjpbhcozubegqvralmrlpkdyjodv\uD83C\uDF33\uD83C\uDF33\uD83C\uDF33\uD83C\uDF33\uD83C\uDF33\uD83C\uDF33\uD83C\uDF33\uD83C\uDF33\uD83C\uDF33wyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv\",\n" +
            "      \"customername\": \"okkjpbh™™A@';\\\\\\\"cozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv\",\n" +
            "      \"customeraddress\": \"okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv\",\n" +
            "      \"customeremail\": \"okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv\",\n" +
            "      \"customermobile\": \"okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv\",\n" +
            "      \"customerid\": 21900,\n" +
            "      \"fixedfee\": 0,\n" +
            "      \"fixedfeepercentage\": 0,\n" +
            "      \"fxspreadpercentage\": 3.5,\n" +
            "      \"sendingamount\": 92,\n" +
            "      \"clientipaddress\": \"okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv\",\n" +
            "      \"isownbehalf\": true,\n" +
            "      \"isreverse\": false,\n" +
            "      \"laststatusrequest\": \"2019-04-02T10:40:01Z\",\n" +
            "      \"provider\": 2,\n" +
            "      \"providertransactionid\": \"2120921\",\n" +
            "      \"providerfxrate\": 1,\n" +
            "      \"receivingamount\": 115.5907,\n" +
            "      \"receivingcurrency\": \"USD\",\n" +
            "      \"ratetosek\": 12.090413,\n" +
            "      \"ratetosekrealtime\": 12.17809,\n" +
            "      \"receiveraddress\": \"okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv\",\n" +
            "      \"receiverid\": 155040,\n" +
            "      \"receivermobilecountrycode\": \"252\",\n" +
            "      \"receivermobile\": \"okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv\",\n" +
            "      \"receivername\": \"okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv\",\n" +
            "      \"receivingcountryalpha3\": \"SSS\",\n" +
            "      \"state\": 6,\n" +
            "      \"sendingcurrency\": \"GBP\",\n" +
            "      \"sendingcountryalpha3\": \"GBR\",\n" +
            "      \"sendingfxrate\": 1.25642035,\n" +
            "      \"sendinginterbankrate\": 1.30199,\n" +
            "      \"sendinginterbankraterealtime\": 1.312431,\n" +
            "      \"remittancetype\": \"okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv\",\n" +
            "      \"settlementcurrency\": \"okkjpbhcozubegqvralmrlpkdyjodvwyrqjtqayvaskraadsbotwoqhnzjyaxyrjqeowiwtqcuiqgrtuxvbnagoxbhnmkebdhbohzanqrrjtxwpmeaveggwiyzunhkuv\",\n" +
            "      \"setteledamount\": 119.7831,\n" +
            "      \"transactionid\": \"BKM-ENMU7IIJ4\",\n" +
            "      \"transactiontime\": \"2019-04-01T15:33:58Z\"\n" +
            "    },\n" +
            "    \"emitted_at\": 1617693523558\n" +
            "  }\n" +
            "}";
    AirbyteMessage deserialize = Jsons.deserialize(record, AirbyteMessage.class);
```

@sherifnada were you able to get the record in a way that you were able to replicate the failure?

**Comment by jrhizor** [comment] 2021-05-07 19:51
@sayowayah Details of failing records would be great. So far I've only been able to fully reproduce failures due to unicode line break characters.

**Comment by michel-tricot** [comment] 2021-05-08 01:09
@jrhizor Are we getting bitten by the fact that the record gets split on multiple lines?

**Comment by michel-tricot** [comment] 2021-05-08 01:09
@jrhizor Are we getting bitten by the fact that the record gets split on multiple lines?

**Comment by michel-tricot** [comment] 2021-05-08 01:15
@jrhizor The problem is probably not with `Jsons.deser` but with what data we feed in. If for any reason the record is split across multiple line for some bad encoding reason, this is exactly what I would expect to happen.

**Comment by sayowayah** [comment] 2021-05-08 03:18
@jrhizor bah sorry, I last noticed the issue almost two weeks ago and it seems like the logs are gone (UI just shows `Waiting for logs... ` forever. may also be related to my recent reinstall). i'll keep an eye out for more failures and report back. 

I know for a fact that the failed records included non-ASCII. Most of my syncs include UTF8 Chinese characters (and most syncs succeed), but I suspect some historical records include characters encoded in BIG5. perhaps related?

**Comment by akoshterek** [comment] 2021-05-08 09:32
I've found failing and similar successful records
encode(address::bytea, 'hex')

Europaplein 705 -> 4575726f7061706c65696e20373035
Europaplein 705[LSEP] -> 4575726f7061706c65696e20373035e280a8

Unicode U+2028 is indeed e280a8 in UTF-8 https://www.fileformat.info/info/unicode/char/2028/index.htm

**Comment by jrhizor** [comment] 2021-05-10 14:05
@michel-tricot I was asking about deserialization for this specific example since we have a full record message listed here, not an error showing that lines were unable to be read.

The LSEP issue, which may be just a subset of record drops doesn't directly involve our serialization method. The proposed resolution can be found here: https://github.com/airbytehq/airbyte/pull/3327

**Comment by grishick** [comment] 2022-05-20 18:56
At this point we don't have the logs or the reproduction example, so I am going to close this issue.

**Closed by grishick** 2022-05-20 18:56 UTC
Labels: type/bug, priority/high, team/connectors-java
