### ISSUE TITLE
Google Cloud Storage (GCS): Authentication (Workload ID on GKE)

### ISSUE THREAD

**Issue by userbradley** [airbytehq/airbyte#18220] opened 2022-10-20 09:15 UTC
## Tell us about the problem you're trying to solve

We are in the process of setting up Airbyte to run on GKE. 

Looking at the [GCS](https://docs.airbyte.com/integrations/destinations/gcs/) page, it shows the possible authentication options possible. 

## Describe the solution you’d like

It would be nice to be able to use the service account the pod is running as, and then use [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity)

## Describe the alternative you’ve considered or used

~Crying my self to sleep~  Using the HMAC key (See [Below](#additional-context) )

## Additional context

This is similar to https://github.com/airbytehq/airbyte/issues/13081 - where our organization does not allow anyone to create SA keys.

## Are you willing to submit a PR?

I would be happy to write the documentation, as well as provide code examples for the documentation, but my AppDev skills are... Lacking

**Comment by sajarin** [comment] 2022-10-21 17:24
@userbradley, I believe this issue is a duplicate of this issue: https://github.com/airbytehq/airbyte/issues/12437. 

If so, could you follow the thread there? It will help us track the issue and interest a lot better for this feature.

**Comment by userbradley** [comment] 2022-10-21 17:24
@sajarin apologise, most certainly!

**Closed** 2022-10-21 17:24 UTC
Labels: type/enhancement, community, needs-triage, team/use, autoteam
