### ISSUE TITLE
SLF4J: Class path contains multiple SLF4J bindings -MYSQL connector Latest build

### ISSUE THREAD

**Issue by userguy** [airbytehq/airbyte#11778] opened 2022-04-07 01:54 UTC
Hello Team , 

After Starting latest build and creating connection for mysql , i am getting error of SLF4J: Class path contains multiple SLF4J bindings 
And page reloads to setup source connector page .

┆Issue is synchronized with this [Monday item](https://airbyte-bunch.monday.com/boards/2536787439/pulses/2537097856) by [Unito](https://www.unito.io)

**Comment by grishick** [comment] 2022-07-01 00:33
Probably a duplicate of: https://github.com/airbytehq/airbyte/issues/9093

**Closed** 2022-08-03 16:36 UTC
Labels: type/bug, community, needs-triage, team/connectors-java, autoteam
