### ISSUE TITLE
Source SalesLoft: Certify to Beta

### ISSUE THREAD

**Issue by igrankova** [airbytehq/airbyte#23479] opened 2023-02-27 15:25 UTC
## Tell us about the problem you're trying to solve
Certify to Beta SalesLoft source connector.
LastPass: SalesLoft dev account

**Comment by davydov-d** [comment] 2023-03-06 11:36
duplicate of https://github.com/airbytehq/airbyte/issues/19217

**Closed by davydov-d** 2023-03-06 11:36 UTC
Labels: type/enhancement, area/connectors, connectors/sources-api, connectors/source/salesloft, team/connectors-python
