### ISSUE TITLE
🐛 Airbyte REST API: Cancel Jobs is not working as expected.

### ISSUE THREAD

**Issue by naveenpatnana** [airbytehq/airbyte#8808] opened 2021-12-15 10:26 UTC
## Environment
 Airbyte version: 0.29.22-alpha
OS Version / Instance: UBUNTU
- **Deployment**: Docker deploy env
- **Source Connector and version**: "airbyte/source-shopify:0.1.18"
- **Destination Connector and version**:  "airbyte/destination-snowflake:0.3.14"
- **Severity**: Critical
- **Step where error happened**: Sync job 

## Current Behavior
While using the "POST /v1/jobs/cancel"  api for cancelling the job which is in **pending state.**
The cancel request  getting succeeded and job state got updated to cancelled, but the problem is Airbyte creating an another new job with same connectionId and config.

## Expected Behavior
After using the cancel API, the job has to be in the cancelled state. Where no new job of that same configuration and connectionId has to be created.

## Steps to Reproduce
This is an intermittent issue.
1. Make sure to create a job ( shopify to snowflake) and it has to be in pending state.
2. Run cancel api("POST /v1/jobs/cancel") with the jobId.
3. Now we need to check the jobs list, then the new job will be created.

**Comment by alafanechere** [comment] 2022-01-05 14:01
Hi @naveenpatnana, could you please update to the latest Airbyte version and check if the bug persists? Thanks.

**Comment by thenaturalist** [comment] 2022-04-27 13:26
Hi @alafanechere I can confirm that this is working as expected on `0.36.3-alpha`

**Comment by evantahler** [comment] 2022-08-24 17:41
Closing, because things are now working as expdcted!

**Closed by evantahler** 2022-08-24 17:41 UTC
Labels: type/bug, area/platform, community, team/cloud, team/oss, autoteam
