### ISSUE TITLE
[source-intercom] malformed state line 'data' doesn't exist - since 0.6.1

### ISSUE THREAD

**Issue by seventhingsit** [airbytehq/airbyte#36893] opened 2024-04-08 11:00 UTC
### Connector Name

source-intercom

### Connector Version

0.6.1

### What step the error happened?

During the sync

### Relevant information

Since version 0.6.1 of the Intercom Airbyte Connector, the error occurs. The target is a Mysql database. 
The problem occurs with every stream area of the connector. 

### Relevant log output

```shell
2024-04-08 09:54:36 [INFO ] - Syncing stream: admins 
2024-04-08 09:54:36 [INFO ] - Marking stream admins as RUNNING
2024-04-08 09:54:36 [DEBUG] - {"type": "TRACE", "trace": {"type": "STREAM_STATUS", "emitted_at": 1712570076697.5852, "stream_status": {"stream_descriptor": {"name": "admins", "namespace": null}, "status": "RUNNING"}}}
2024-04-08 09:54:36 [ERROR] - Airbyte output line process error: Error parsing airbyte state line {"type": "STATE", "state": {"type": "STREAM", "stream": {"stream_descriptor": {"name": "admins", "namespace": null}, "stream_state": {}}, "sourceStats": {"recordCount": 8}}}: malformed state line 'data' doesn't exist. Process will be killed
2024-04-08 09:54:36 [ERROR] - Error closing airbyte runner: exit status 1
2024-04-08 09:54:36 [INFO ] - Config saved.
2024-04-08 09:54:36 [ERROR] - Error synchronization: signal: killed
```

### Contribute

- [X] Yes, I want to contribute

**Comment by natikgadzhi** [comment] 2024-04-09 05:45
@bazarnov you're probably closest of everyone to recent Intercom changes — could you take a look at that one too?

**Comment by bazarnov** [comment] 2024-04-09 12:48
@natikgadzhi 
1) There is an update available for the `source-intercom` `0.6.3`, to be considered as the major version to use, if the Customer is willing to update, they should
2) This looks like the CDK regression for the older STATE format used instead of the new one

Recommendations:
- to attach logs to try to reproduce
- to update the version to the latest one
- to reset and full-refresh the data to obtain a new STATE format and continue to go with it, assuming this is OSS.

**Comment by seventhingsit** [comment] 2024-04-09 13:18
I choose 0.6.3, and configure a full refresh for all sections, then i clear destination and start the sync again:

Still this error via docker logs:

`2024-04-09 13:13:45 [ERROR]: [8ayfom652pmtpxsjh0kx6k_intercom_all_0317d0b0_cad3_477a_87fc_905ffd14a15a] Airbyte output line process error: Error parsing airbyte state line {"type": "STATE", "state": {"type": "STREAM", "stream": {"stream_descriptor": {"name": "activity_logs", "namespace": null}, "stream_state": {"created_at": 1712586418}}, "sourceStats": {"recordCount": 3472}}}: malformed state line 'data' doesn't exist. Process will be killed
2024-04-09 13:13:45 [ERROR]: [task:8ayfom652pmtpxsjh0kx6k_intercom_all_0317d0b0_cad3_477a_87fc_905ffd14a15a]: Airbyte output line process error: Error parsing airbyte state line {"type": "STATE", "state": {"type": "STREAM", "stream": {"stream_descriptor": {"name": "activity_logs", "namespace": null}, "stream_state": {"created_at": 1712586418}}, "sourceStats": {"recordCount": 3472}}}: malformed state line 'data' doesn't exist. Process will be killed
2024-04-09 13:13:45 [ERROR]: [task:8ayfom652pmtpxsjh0kx6k_intercom_all_0317d0b0_cad3_477a_87fc_905ffd14a15a]: Error closing airbyte runner: exit status 1
2024-04-09 13:13:45 [ERROR]: [8ayfom652pmtpxsjh0kx6k_intercom_all_0317d0b0_cad3_477a_87fc_905ffd14a15a] closing airbyte runner: exit status 1
2024-04-09 13:13:45 [INFO]: [task:8ayfom652pmtpxsjh0kx6k_intercom_all_0317d0b0_cad3_477a_87fc_905ffd14a15a]: Config saved.
2024-04-09 13:13:45 [ERROR]: [8ayfom652pmtpxsjh0kx6k_intercom_all_0317d0b0_cad3_477a_87fc_905ffd14a15a] Error synchronization: signal: killed
2024-04-09 13:13:45 [ERROR]: [task:8ayfom652pmtpxsjh0kx6k_intercom_all_0317d0b0_cad3_477a_87fc_905ffd14a15a]: Error synchronization: signal: killed
2024-04-09 13:14:18 [INFO]: Processing of 0 files finished in 52.83µs`


Some more Recommendations? Otherwise we close this ticket and will wait for further updates.

**Comment by bazarnov** [comment] 2024-04-09 14:33
> then i clear destination and start the sync again

I suppose this is the issue here, you should not do this, because the source has a relation with the `destination` and the `STATE` is important here as well. 

Could you please re-set up the connection and complete it using the latest version? 

Also do you have the input STATE generated from the previous syncs?

**Comment by bazarnov** [comment] 2024-04-09 14:58
@girarda Could you please also take a look at it, it looks like something is wrong with the `data` property handling inside of the `STATE` messages. The test sync running on `0.6.3` (latest) for our sandbox: https://cloud.airbyte.com/workspaces/9ef0ca9a-d759-484c-8499-93565374eaea/connections/e0cd7ef3-d51f-4af3-b6da-c46e61285a9c/job-history shows no issues, succeeds as expected.

The `STATE` object is generated without the `data` property inside the state, but the `0.6.0` had it. 

Which makes me think about the next scenarios:
1) Destination treats the STATE incorrectly
2) Issues with Platform (OSS)?

I've also found no way to reproduce this locally, for now.

**Comment by seventhingsit** [comment] 2024-04-09 15:00
> What version of the MySQL are you using? @bazarnov 

target db for intercom connector: mariadb:10.9.3 via docker container in this case.

**Comment by seventhingsit** [comment] 2024-04-09 15:27
@bazarnov - I work with Jitsu as a control tool for the Airbyte connectors. How can I find out the destination version?

**Comment by bazarnov** [comment] 2024-04-09 17:02
You can open the `Airbyte UI` > Settings > Destinations > find the destination you use for your Intercom connection (`MySQL`, as mentioned earlier in the description) and tell the version of the tag it uses.

**Comment by seventhingsit** [comment] 2024-04-10 09:47
@bazarnov  - Ok, I mean that Jitsu as a tool only uses the sources, i.e. the connectors from Airbyte, but not the destinations and therefore has its own solution. So I probably have to go to them, right?

**Comment by bazarnov** [comment] 2024-04-10 11:07
I think if you're using something 3rd party / external management tool to orchestrate the syncs - yes, please refer to the docs or support of that tool, in particular. 

For me, it looks like the destination point validates the STATE messages incorrectly since we're not providing the `data` property inside the `STATE` anymore, so it's either stay on the `0.6.0` version, where this was available, or update the other pipeline parts, like the `destination`. Then the STATE messages should be treated as expected.

**Comment by bazarnov** [comment] 2024-06-26 11:37
Closing this one, as `non-active`. Re-open, once needed.

**Closed by bazarnov** 2024-06-26 11:37 UTC
Labels: type/bug, area/connectors, community, connectors/source/intercom, team/connectors-python
