### ISSUE TITLE
🐛 Destination Postgres: removes granted permissions when using "Full Refresh | Overwrite" 

### ISSUE THREAD

**Issue by lfrodrigues** [airbytehq/airbyte#15146] opened 2022-07-30 06:26 UTC
## Environment
- **Airbyte version**:  0.39.41-alpha
- **OS Version / Instance**: Ubuntu 18.04
- **Deployment**: Docker o
- **Source Connector and version**: Postgres 0.4.38
- **Destination Connector and version**: Postgres 0.3.21
- **Step where error happened**:  Sync job 

## Current Behavior
I have a database with that which I'm syncing data into. An external service connects there with a login that has only SELECT access on the airbyte copied data. 

After every sync (Full Refresh | Overwrite), the service loses access to the table, and I need to grant SELECT again.

## Expected Behavior
Airbyte postgres destination should not touch granted permissions on the destination table.

## Steps to Reproduce
1. Configure Postgres to Postgres Connection
2. Run the first sync
4. Grant permissions to a user different than the user airbyte uses to connect to destination Postgresto the table that was created by airbyte
5. Run sync again --> the granted permission to the new user will have disappeared from the table

**Comment by sashaNeshcheret** [comment] 2022-09-07 11:02
I was only able to reproduce this issue just when making sync with normalization, without normalization - select permissions on table remain after full refresh and override syncs. 
@grishick as far as root cause of issue is on normalization side, should i proceed with it, or better move it on airbyte or python team?

**Comment by grishick** [comment] 2022-09-08 15:17
FYI @edgao the problem is that normalization drops tables during full refresh and an unintended consequence/side effect of this behavior is that users, who may have had permissions specific to the tables created by Airbyte are affected

**Comment by marcosmarxm** [comment] 2024-03-20 20:47
Normalization and custom dbt are deprecated features and will be removed soon from the project. For that reason I'm closing the issue as it won't be implemented anymore.

**Closed by marcosmarxm** 2024-03-20 20:47 UTC
Labels: type/bug, area/connectors, normalization, lang/java, community, connectors/destination/postgres, team/destinations
