### ISSUE TITLE
Validation for discover step to avoid syncing data from 2 different source streams into 1 destination stream 

### ISSUE THREAD

**Issue by subodh1810** [airbytehq/airbyte#42443] opened 2024-07-23 14:59 UTC
https://airbytehq-team.slack.com/archives/C03GD9SV36E/p1721726745348029

**Comment by davinchia** [comment] 2024-07-24 05:20
duplicate of https://github.com/airbytehq/airbyte/issues/16173

**Closed by davinchia** 2024-07-24 05:20 UTC
Labels: team/platform-move, frozen
