### ISSUE TITLE
NetSuite data connectors

### ISSUE THREAD

**Issue by akkisapra** [airbytehq/airbyte#8359] opened 2021-12-01 06:30 UTC
## Tell us about the new connector you’d like to have
* Which source and which destination?: 
source: Netsuite, Destination: S3, Databricks

* Do you need a specific version of the underlying data source e.g: you specifically need support for an older version of the API or DB? 
 Version 2021.2 

## Describe the context around this new connector
* Why do you need this integration? How does your team intend to use the data? This helps us understand the use case.
Team will be getting all the data from ERP to Datawarehouse

* How often do you want to run syncs?
Every hour

* If this is an API source connector, which entities/endpoints do you need supported?
As many as possible

* If the connector is for a paid service, can we name you as a mutual user when we subscribe for an account? Which company should we name? 
Love to Dream

## Describe the alternative you are considering or using
What are you considering doing if you don’t have this integration through Airbyte?
3rd party data connector

## Are you willing to submit a PR?
yes

**Comment by alafanechere** [comment] 2021-12-02 13:58
Hi @akkisapra thanks for the suggestion but this is a duplicate of an already existing issue https://github.com/airbytehq/airbyte/issues/3212 please subscribe to this one to receive updates on this topic!

**Closed** 2021-12-02 13:58 UTC
Labels: area/connectors, new-connector, community
