### ISSUE TITLE
Creating a CockroachDB connection and choosing one object to sync results in every other object being synced except the chosen one

### ISSUE THREAD

**Issue by da-firebolt** [airbytehq/airbyte#10790] opened 2022-03-02 10:44 UTC
## Environment
Airbyte version: 0.35.30 as well as 0.35.42
Deployment: Kubernetes
Source connector and version:  CockroachDB 0.1.10
Destination connector and version: S3 0.2.9
Severity: High
Step where error happened: Sync job

- **Airbyte version**:  example is 0.22.0-alpha
- **OS Version / Instance**: example macOS, Windows 7/10, Ubuntu 18.04, GCP n2. , AWS EC2
- **Deployment**: example are Docker or Kubernetes deploy env
- **Source Connector and version**: (if applicable example Salesforce 0.2.3) 
- **Destination Connector and version**: (if applicable example Postgres 0.3.3) 
- **Severity**: Very Low / Low / Medium / High / Critical
- **Step where error happened**: Deploy / Sync job / Setup new connection / Update connector / Upgrade Airbyte

## Current Behavior
*Tell us what happens.*
Creating a connection with CockroachDB as source and S3 as a destination and choosing only one object to be synced out of possible 47 objects results in every object being synced except the one you've chosen. This is confirmed by querying Airbyte API for connections which will return sync catalog for all 46 objects except the one you've chosen to sync and on S3 you will get the same thing, folder and files for the 46 objects but not the one you need. 

![image](https://user-images.githubusercontent.com/89909616/156345942-01b2c1c9-1ab2-473d-adc6-a660edbb49ab.png)

## Expected Behavior
*Tell us what should happen.*
We are expecting to see only the chosen object being synced in the UI and the result should be one file on s3 instead of all of them minus the one that was supposed to be synced, also one would expect to see only the stream that you've chosen in the sync catalog instead of seeing every stream except the one you actually wanted to sync.

## Logs
Logs are too big because all objects are synced instead of only one.
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1. Choose CockroachDB as a source
2. Choose S3 as a destination (output format Parquet)
3. Create a new connection, choose Mirror source structure for the Destination Namespace and Activate one stream you want to sync  

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by marcosmarxm** [comment] 2022-03-02 23:09
Hello @da-firebolt looks you disabled the stream `audit_entries`. I recorded a video explaining how to disable/enable the streams in the new version. Let me know if helps you.
https://www.loom.com/share/61d408782116428bacedef0935d06856

**Comment by da-firebolt** [comment] 2022-03-03 11:03
Thanks Marcos, I can confirm doing it the way you present gives expected
results in the UI as well as in the sync catalog when querying Airbyte API.
Do you know why I can't choose incremental sync mode for any objects but
the moment I switch to Full refresh, the warning in red disappears and I'm
able to set up connection?

[image: image.png]

**Comment by marcosmarxm** [comment] 2022-03-03 18:49
You need to select the right Primary Key or Cursor Field.

**Comment by marcosmarxm** [comment] 2022-03-03 18:49
I'm going to close the issue @da-firebolt because it's not a bug. Let me know if you have any other questions

**Closed by marcosmarxm** 2022-03-03 18:49 UTC
Labels: type/bug, community, needs-triage

**Comment by da-firebolt** [comment] 2022-03-04 08:20
Thanks!
