### ISSUE TITLE
Salesforce source: Stuck in Jobs InProgress 

### ISSUE THREAD

**Issue by anamargaridarl** [airbytehq/airbyte#17148] opened 2022-09-26 16:31 UTC
## Environment
- **Airbyte version**: 0.40.6 - **OS Version / Instance**: AWS EC2
- **Deployment**: Kubernetes
- **Source Connector and version**: 1.0.17
- **Source Destination and version**: 0.4.35
- **Step where error happened**: Update connector

## Current Behavior
Stuck continuously logging:
> Sleeping 3.4809579870417284 seconds while waiting for Job: Opportunity/7508e000000z92DAAQ to complete. Current state: InProgress

When synchronizing the data for some fields (like Opportunity) it gets stuck in infinite job operations like the one above.
Even though the job is always new it never advances from that operation for that field.

## Expected Behavior
Read data from the opportunity field

## Steps to Reproduce
1. Activate the Opportunity field
2. Sync data

## Are you willing to submit a PR?
Yes

**Comment by marcosmarxm** [comment] 2022-09-26 17:38
@anamargaridarl do you have any idea about how many records this stream has?

**Comment by marcosmarxm** [comment] 2022-09-26 17:39
Also can you share the complete log to investigate it deeper?

**Comment by anamargaridarl** [comment] 2022-09-28 08:52
It shouldn't have more than 400 records.

[logs-4038 (3).txt](https://github.com/airbytehq/airbyte/files/9663199/logs-4038.3.txt)

**Comment by anamargaridarl** [comment] 2022-09-28 09:55
This is also happening for OpportunityLineItem with airbyte:0.40.4 and connector: 1.0.15

**Comment by marcosmarxm** [comment] 2022-09-28 16:45
@anamargaridarl are you using limit resources in Kubernetes?

**Comment by marcosmarxm** [comment] 2022-09-28 17:05
> The workers have limits of 500m for CPU and 4Gi for memory

It is possible to remove the constrain and follow the consumption for the first sync?

**Comment by anamargaridarl** [comment] 2022-09-29 12:53
I doubled on both resources and still got the same issue. 
It's weird because in version 1.0.15 this doesn't happen on the Opportunity field with the exact same source. (though it already occurs in the OpportunityLineItem) And the changes in the last versions don't seem to affect the job creation.

**Comment by marcosmarxm** [comment] 2022-09-29 17:59
@anamargaridarl sorry about not getting you a good pointer here. From your logs there isn't anything indicating a problem with the connection besides getting stuck. Do you have other connections running in this server?

My recommendation is:
- Try to deploy Airbyte using docker-compose and sync the data to check if the problem is with k8s deployment or the sync itself.
- Try a very short start date; only for validate the connection can finish;

**Comment by BenoitFayolle** [comment] 2022-09-30 10:21
Hi here, 
we have a similar issue with our `Case` object. `Opportunity`, `Account` and `OpportunityLineItem` run fine. 
We are running airbyte 0.40.7 and salesforce connector 1.0.16. 
Destination redshift 0.3.50 and s3 0.3.15 both run into the same issue.
We don't use K8s though. 
Our Case object has ~1M records. Opportunity has ~0.5M records and OpportunityLineItem has ~ 1.2M.
But Case definitely is the biggest object because it has a lot of fields and some `textarea` typed fields which are huge.
Our Case syncs got to 20M+ records read without finishing and it's also displaying these sleep messages:

> 2022-09-30 10:17:19 source > Sleeping 0.501 seconds while waiting for Job: Case/7505q000006PUZAAA4 to complete. Current state: UploadComplete
2022-09-30 10:17:20 source > Sleeping 0.502718281828459 seconds while waiting for Job: Case/7505q000006PUZAAA4 to complete. Current state: InProgress
2022-09-30 10:17:21 source > Sleeping 0.5073890560989307 seconds while waiting for Job: Case/7505q000006PUZAAA4 to complete. Current state: InProgress
2022-09-30 10:17:21 source > Sleeping 0.5200855369231877 seconds while waiting for Job: Case/7505q000006PUZAAA4 to complete. Current state: InProgress
2022-09-30 10:17:22 source > Sleeping 0.5545981500331443 seconds while waiting for Job: Case/7505q000006PUZAAA4 to complete. Current state: InProgress
2022-09-30 10:17:23 source > Sleeping 0.6484131591025766 seconds while waiting for Job: Case/7505q000006PUZAAA4 to complete. Current state: InProgress
2022-09-30 10:17:24 source > Sleeping 0.9034287934927351 seconds while waiting for Job: Case/7505q000006PUZAAA4 to complete. Current state: InProgress
2022-09-30 10:17:26 source > Sleeping 1.5966331584284585 seconds while waiting for Job: Case/7505q000006PUZAAA4 to complete. Current state: InProgress
2022-09-30 10:17:30 source > Sleeping 3.4809579870417284 seconds while waiting for Job: Case/7505q000006PUZAAA4 to complete. Current state: InProgress
2022-09-30 10:17:34 source > Sleeping 3.4809579870417284 seconds while waiting for Job: Case/7505q000006PUZAAA4 to complete. Current state: InProgress
2022-09-30 10:17:38 source > Sleeping 3.4809579870417284 seconds while waiting for Job: Case/7505q000006PUZAAA4 to complete. Current state: InProgress
2022-09-30 10:17:42 source > Sleeping 3.4809579870417284 seconds while waiting for Job: Case/7505q000006PUZAAA4 to complete. Current state: InProgress

We have manually loaded some of the staging files and noticed massive duplication of records. 
[Slack thread](https://airbytehq.slack.com/archives/C021JANJ6TY/p1664177583971679)

**Comment by BenoitFayolle** [comment] 2022-09-30 10:30
I ran airbyte locally and added some logging on the query that's being ran in the query job [here] (https://github.com/airbytehq/airbyte/blob/f0f60dcebfbd749a6781eae64f973d8102390cca/airbyte-integrations/connectors/source-salesforce/source_salesforce/streams.py#L158)  in the code
This is the 4 first queries I got (I removed the select <fields> part):

> [1] "FROM Case ORDER BY SystemModstamp ASC LIMIT 15000"                                                 
> [2] "FROM Case WHERE SystemModstamp >= 2019-03-21T17:30:19.000Z ORDER BY SystemModstamp ASC LIMIT 15000"
> [3] "FROM Case WHERE SystemModstamp >= 2019-03-21T17:30:20.000Z ORDER BY SystemModstamp ASC LIMIT 15000"
> [4] "FROM Case WHERE SystemModstamp >= 2019-03-21T17:30:20.000Z ORDER BY SystemModstamp ASC LIMIT 15000"
> 
I think this clearly shows that the connector reads the same data multiple times (as 3 and 4 are the exact same query)

**Comment by anamargaridarl** [comment] 2022-09-30 11:07
Can confirm like @BenoitFayolle that locally have similar behavior

**Comment by BenoitFayolle** [comment] 2022-09-30 13:20
After 40 query job iterations I can confirm, the query is stuck on : 
> FROM Case WHERE SystemModstamp >= 2019-03-21T17:30:20.000Z ORDER BY SystemModstamp ASC LIMIT 15000

**Comment by anamargaridarl** [comment] 2022-10-04 10:04
From my understanding, and like @BenoitFayolle mentioned, the number of objects with the date used to get the next token is bigger than the defined record limit for the job of 15000. Thus, it gets stuck with the same query. I was not having this issue with prior versions only because the source data to collect was updated after.

Can you change your approach to use a limit/offset query instead of incrementing the cursor value during each run?

**Comment by BenoitFayolle** [comment] 2022-10-04 10:17
I confirm @anamargaridarl's diagnosis:
`select count(Id) from Case where SystemModstamp = 2019-03-21T17:30:20.000Z`
returns 20824 on our dataset. The query cannot evolve because it cannot capture all the records in a single 15000 records batch for that particular timestamp

**Comment by BenoitFayolle** [comment] 2022-10-05 10:32
+1

**Comment by anamargaridarl** [comment] 2022-10-11 08:34
Hi! Do you have an approximate time for the review of the PR? Thank you

**Comment by marcosmarxm** [comment] 2022-10-11 23:29
@anamargaridarl team is working to solve the issue, as soon as possible it will merged :)

**Closed** 2022-10-13 06:05 UTC
Labels: type/bug, community, connectors/source/salesforce, team/connectors-python

**Comment by marcosmarxm** [comment] 2022-10-13 17:29
@anamargaridarl can you test the new version?

**Comment by sh4sh** [comment] 2022-10-17 21:25
Hey @anamargaridarl @BenoitFayolle , can you confirm that the [new version v1.0.22](https://docs.airbyte.com/integrations/sources/salesforce#changelog) for the salesforce source connector has fixed the issue?

**Comment by BenoitFayolle** [comment] 2022-10-18 08:06
@sh4sh  It will be hard for me to confirm because we made some dummy batch updates to any 15k+ blocks of identical systemmodstamp so we could break out of infinite loops since I didn't know when the issue would be resolved. I can confirm the 1.0.22 connector works because we run it successfully.
