### ISSUE TITLE
:sparkles: Source Insightly : Migrate Python CDK to Low-code CDK

### ISSUE THREAD

**Issue by bmcgilli** [airbytehq/airbyte#30861] opened 2023-09-29 04:09 UTC
https://docs.airbyte.com/integrations/sources/insightly

**Rules for the Connectors Hackathon**
You can only work on one connector at a time
Make sure to resolve all suggestions from the Airbyte team
Must include all streams of the connector you’re migrating. Otherwise, it will not be accepted.
If you don’t commit anything within five days, the issue may be assigned to someone else.

**Comment by aazam-gh** [comment] 2023-10-05 16:14
Raised a PR for Freshcaller. Will work on this next :)

**Comment by justinbchau** [comment] 2023-10-07 00:01
Hey @aazam-gh , it looks like you have an open issue already that doesn't have a PR linked to it just yet. I will keep this issue open for now to give others a chance.

If the issue is still open and you've submitted PRs for the other issues, I will assign this to you!

**Comment by jaydee029** [comment] 2023-10-08 04:21
Hi, I would like to work on this ,can you assign this to me

**Comment by aazam-gh** [comment] 2023-10-08 12:24
@justinbchau I was working on this issue before I was assigned the Vectara one and did not see the notification until now.

**Closed** 2023-11-14 16:23 UTC
Labels: team/triage
