### ISSUE TITLE
Temporal: prints plain password in logs

### ISSUE THREAD

**Issue by tooptoop4** [airbytehq/airbyte#14371] opened 2022-07-02 06:48 UTC
see https://github.com/temporalio/temporal/issues/3022

**Comment by evantahler** [comment] 2022-08-02 18:27
Grooming Notes:

* Update the version of Temporal that we use in OSS to the newest version.

**Comment by tooptoop4** [comment] 2022-10-12 23:06
have y'all raised a CVE yet?

**Comment by tooptoop4** [comment] 2022-10-13 01:36
that doesn't fix it. see https://github.com/temporalio/temporal/issues/3022 @benmoriceau

**Comment by benmoriceau** [comment] 2022-10-13 03:07
> that doesn't fix it. see [temporalio/temporal#3022](https://github.com/temporalio/temporal/issues/3022) @benmoriceau

@tooptoop4 we closed the issue by mistake. I still need to reproduce it locally and check that it is fixed which was not done when the issue got close through an edit in my PR description.

**Comment by benmoriceau** [comment] 2022-10-13 16:17
@tooptoop4 The issue is fixed on our side, I tested it locally. We don't depends on temporal for this issue because we don't call their `auto-setup.sh` script but a custom script on our side as you can see [here](https://github.com/airbytehq/airbyte/blob/master/airbyte-temporal/Dockerfile). A communication is being prepared on our side, I don't know if it will be a CVE. I'll close the issue when it is done.

**Comment by andyjih** [comment] 2022-10-17 20:45
Hi @tooptoop4 , we've released a fix and also published a notice in our [community forum here](https://discuss.airbyte.io/t/security-notice-temporal-logs-the-airbyte-database-password-in-plaintext/2931?u=jerri-airbyte). 

Thank you again for raising this issue with us!

**Closed by andyjih** 2022-10-17 20:45 UTC
Labels: type/bug, temporal, community, area/platform-oss, team/workflow, autoteam, platform-workflow/service
