### ISSUE TITLE
allow configuring a custom sync interval in the UI

### ISSUE THREAD

**Issue by sherifnada** [airbytehq/airbyte#4520] opened 2021-07-03 00:22 UTC
## Tell us about the problem you're trying to solve
I would like to be able to configure a number other than the UI provided defaults (say sync every 7 minutes)

**Comment by davinchia** [comment] 2021-07-04 13:23
Related to #2170

**Comment by philippeboyd** [comment] 2021-07-21 13:39
@sherifnada any news on this?

**Comment by davinchia** [comment] 2021-07-21 13:44
Everyone is focused on Cloud now so this is likely to be pushed to next month. This is definitely on the roadmap though!

**Comment by cgardens** [comment] 2021-12-18 00:33
duplicate of https://github.com/airbytehq/airbyte/issues/2170. something we are working on again.

**Closed by cgardens** 2021-12-18 00:33 UTC
Labels: type/enhancement, area/frontend
