### ISSUE TITLE
Allow /source_definitions/update update (maybe delete) a manual added Source

### ISSUE THREAD

**Issue by potatozerg** [airbytehq/airbyte#6153] opened 2021-09-16 19:23 UTC
This is causing me trouble since I added the MongoDB Java version in my Dev Airbyte and named it "test MongoDB v2".

Now the MongoDB Source is officially released with v0.29.18, but my list in Dev won't be updated because I already added it. 
If I update my Prod Airbyte, I will have a "MongoDB" Source for Prod, and "test MongoDB v2" for Dev. 

It would be really helpful if I can delete the manual added Source or change the name of it.

**Comment by cgardens** [comment] 2021-12-18 00:40
agreed. duplicate of https://github.com/airbytehq/airbyte/issues/8732 which is being actively worked on

**Closed by cgardens** 2021-12-18 00:40 UTC
Labels: type/enhancement, needs-triage
