### ISSUE TITLE
Add posibility to select and apply the Sync methods to all the streams in the Airbyte UI

### ISSUE THREAD

**Issue by bazarnov** [airbytehq/airbyte#4762] opened 2021-07-15 12:23 UTC
## Tell us about the problem you're trying to solve
As the customer/user of Airbyte, I would like to have the option to select the same sync method to all streams at once, on the stage of setting up the connections between the source connector and the destination.

## Describe the solution you’d like
Add a button or the dropdown list with the options to choose between: 
`full-refresh overwrite,  full-refresh append, Incremental refresh append, Incremental refresh append+deduplicate`

## Describe the alternative you’ve considered or used
Now it's difficult to select all the streams to a single specified sync method, the only option you have is to set sync mode for each stream manually, if you have them over 100, it takes a long time.

**Comment by sherifnada** [comment] 2021-07-15 18:03
#UIduplicate of https://github.com/airbytehq/airbyte/issues/4226. Copying description to that ticket and closing this one.

**Closed by sherifnada** 2021-07-15 18:03 UTC
Labels: area/developer, type/enhancement
