### ISSUE TITLE
Connector Builder: Show collapsable`exceptionStack` when provided

### ISSUE THREAD

**Issue by maxi297** [airbytehq/airbyte#30446] opened 2023-09-14 17:50 UTC
### What area the feature impact?

Connectors

### Revelant Information

There are exceptions today that generates more information than we show to the user. Those information would be pretty helpful for debugging. For example, given a uncaught read exception, we generated the following HTTP response:
```
{
    "exceptionStack": "Traceback (most recent call last):\n  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/connector_builder/connector_builder_handler.py\", line 62, in read_stream\n    stream_read = handler.get_message_groups(source, config, configured_catalog, limits.max_records)\n  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/connector_builder/message_grouper.py\", line 69, in get_message_groups\n    for message_group in self._get_message_groups(\n  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/connector_builder/message_grouper.py\", line 181, in _get_message_groups\n    datetime_format_inferrer.accumulate(message.record)\n  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/utils/datetime_format_inferrer.py\", line 80, in accumulate\n    self._initialize(record) if self._datetime_candidates is None else self._validate(record)\n  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/utils/datetime_format_inferrer.py\", line 61, in _initialize\n    if self._matches_format(field_value, format):\n  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/utils/datetime_format_inferrer.py\", line 49, in _matches_format\n    self._parser.parse(value, format)\n  File \"/root/.pyenv/versions/3.9.11/lib/python3.9/site-packages/airbyte_cdk/sources/declarative/datetime/datetime_parser.py\", line 29, in parse\n    return datetime.datetime.fromtimestamp(int(date), tz=datetime.timezone.utc)\nOverflowError: timestamp out of range for platform time_t\n",
    "exceptionClassName": "io.airbyte.protocol.models.AirbyteTraceMessage",
    "message": "Error reading stream with config=<a config> and catalog=<a catalog>: timestamp out of range for platform time_t"
}
```

The stacktrace is not perfect because the error message is not so explicit, but at least it shows which line of code is problematic. If this information would be displayed to the user, they could more easily communicate the issue to us and this would save time for everyone.

**Comment by lmossman** [comment] 2023-09-18 18:30
Duplicate of https://github.com/airbytehq/airbyte/issues/21750

**Closed by lmossman** 2023-09-18 18:30 UTC
Labels: team/extensibility
