### ISSUE TITLE
Source Stripe: start_date is a required field but isn't used in code

### ISSUE THREAD

**Issue by marcosmarxm** [airbytehq/airbyte#6124] opened 2021-09-16 02:29 UTC
## Enviroment
- Connector version: 0.1.17

## Current Behavior
Looks that start_date is not used in Stripe connector. Not sure if this was removed or never used.
https://github.com/airbytehq/airbyte/blob/078c6604a499c5ab68beb403d80b3068e6bef4ab/airbyte-integrations/connectors/source-stripe/source_stripe/streams.py#L76-L78

## Expected Behavior
Fields in connector specification should be used in code or removed.

## Logs
*If applicable, please upload the logs from the failing operation. 
For sync jobs, you can download the full logs from the UI by going to the sync attempt page and 
clicking the download logs button at the top right of the logs display window.*

<details>
<summary>LOG</summary> 

```

replace this with
your long log
output here

```

</details>

## Steps to Reproduce
1.
2.
3.

## Are you willing to submit a PR?

Remove this with your answer.

**Comment by Zirochkaa** [comment] 2021-09-16 07:51
It's a duplicate of #6074.

**Closed by Zirochkaa** 2021-09-16 07:51 UTC
Labels: type/bug
