### ISSUE TITLE
[API] Timeout error has occurred when creating connection by terraform

### ISSUE THREAD

**Issue by Saku3449** [airbytehq/airbyte#29506] opened 2023-08-17 02:29 UTC
### Connector Name

source-ExchangeRateAPI, destination-BigQuery

### Connector Version

0.3.1

### What step the error happened?

Configuring a new connector

### Revelant information

I have tried to establish a connection using terraform to code a configuration for AirByte that works locally.
The source is ExchangeRateAPI and the destination is BigQuery.
When I tried to create a connection using this code, I got this error

```
airbyte_connection.exchangerates_bigquery: Creating...
airbyte_connection.exchangerates_bigquery: Still creating... [10s elapsed]
airbyte_connection.exchangerates_bigquery: Still creating... [20s elapsed]
╷
│ Error: unexpected response from API. Got an unexpected response code 500
│ 
│   with airbyte_connection.exchangerates_bigquery,
│   on provider.tf line 53, in resource "airbyte_connection" "exchangerates_bigquery":
│   53: resource "airbyte_connection" "exchangerates_bigquery" {
│ 
│ **Request**:
│ POST /v1/connections HTTP/1.1
│ Host: localhost:8006
│ Accept: application/json
│ Authorization: Basic YWlyYnl0ZTpwYXNzd29yZA==
│ Content-Type: application/json
│ User-Agent: speakeasy-sdk/terraform 0.3.1 2.83.3 1.0.0
│ 
│ 
│ **Response**:
│ HTTP/1.1 500 Internal Server Error
│ Content-Length: 35
│ Connection: keep-alive
│ Content-Type: application/problem+json
│ Date: Thu, 17 Aug 2023 01:44:33 GMT
│ Server: nginx/1.25.1
│ 
│ {"type":"about:blank","status":500}
``` 
The docker log at this time is as follows

```shell
airbyte-server                    | 2023-08-17 01:44:31 INFO i.m.h.s.n.h.a.e.AccessLog(log):125 - airbyte-webapp.airbyte_airbyte_internal - - [17/Aug/2023:01:44:31 +0000] "GET /api/v1/health HTTP/1.0" 200 18
airbyte-api-server                | 2023-08-17 01:44:33 ERROR i.m.r.i.RecoveryInterceptor(resolveFallback):244 - Type [io.airbyte.api.server.forwardingClient.ConfigApiClient$Intercepted] executed with error: Read Timeout
airbyte-api-server                | io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout
airbyte-api-server                |     at io.micronaut.http.client.exceptions.ReadTimeoutException.<clinit>(ReadTimeoutException.java:26) ~[micronaut-http-client-core-3.10.0.jar:3.10.0]
airbyte-api-server                |     at io.micronaut.http.client.netty.DefaultHttpClient.lambda$exchangeImpl$33(DefaultHttpClient.java:1097) ~[micronaut-http-client-3.10.0.jar:3.10.0]
airbyte-api-server                |     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onError(ReactorSubscriber.java:64) ~[micronaut-runtime-3.10.0.jar:3.10.0]
airbyte-api-server                |     at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57) ~[micronaut-runtime-3.10.0.jar:3.10.0]
airbyte-api-server                |     at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57) ~[micronaut-runtime-3.10.0.jar:3.10.0]
airbyte-api-server                |     at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62) ~[micronaut-runtime-3.10.0.jar:3.10.0]
airbyte-api-server                |     at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
airbyte-api-server                |     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
airbyte-api-server                |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
airbyte-api-server                |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
airbyte-api-server                |     at java.lang.Thread.run(Thread.java:1589) ~[?:?]
airbyte-api-server                | 2023-08-17 01:44:33 INFO i.a.a.LoggingTrackingClient(track):55 - track. version: null, userId: null, action: Airbyte_API_Call, metadata: {user_id=00000000-0000-0000-0000-000000000000, endpoint=/v1/connections, operation=POST, status_code=500, api_version=0.50.15}
airbyte-api-server                | 2023-08-17 01:44:33 ERROR i.m.h.s.RouteExecutor(logException):444 - Unexpected error occurred: Read Timeout
airbyte-api-server                | io.micronaut.http.client.exceptions.ReadTimeoutException: Read Timeout
airbyte-api-server                |     at io.micronaut.http.client.exceptions.ReadTimeoutException.<clinit>(ReadTimeoutException.java:26) ~[micronaut-http-client-core-3.10.0.jar:3.10.0]
airbyte-api-server                |     at io.micronaut.http.client.netty.DefaultHttpClient.lambda$exchangeImpl$33(DefaultHttpClient.java:1097) ~[micronaut-http-client-3.10.0.jar:3.10.0]
airbyte-api-server                |     at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:94) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onError(ReactorSubscriber.java:64) ~[micronaut-runtime-3.10.0.jar:3.10.0]
airbyte-api-server                |     at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:295) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:280) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:419) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57) ~[micronaut-runtime-3.10.0.jar:3.10.0]
airbyte-api-server                |     at reactor.core.publisher.FluxOnErrorReturn$ReturnSubscriber.onNext(FluxOnErrorReturn.java:162) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57) ~[micronaut-runtime-3.10.0.jar:3.10.0]
airbyte-api-server                |     at reactor.core.publisher.MonoDelay$MonoDelayRunnable.propagateDelay(MonoDelay.java:271) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:286) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62) ~[micronaut-runtime-3.10.0.jar:3.10.0]
airbyte-api-server                |     at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.5.0.jar:3.5.0]
airbyte-api-server                |     at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
airbyte-api-server                |     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
airbyte-api-server                |     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
airbyte-api-server                |     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
airbyte-api-server                |     at java.lang.Thread.run(Thread.java:1589) ~[?:?]
airbyte-proxy                     | 172.21.0.1 - airbyte [17/Aug/2023:01:44:33 +0000] "POST /v1/connections HTTP/1.1" 500 35 "-" "speakeasy-sdk/terraform 0.3.1 2.83.3 1.0.0"
airbyte-api-server                | 2023-08-17 01:44:33 INFO i.m.h.s.n.h.a.e.AccessLog(log):125 - airbyte-proxy.airbyte_airbyte_internal - - [17/Aug/2023:01:44:12 +0000] "POST /v1/connections HTTP/1.0" 500 35
``` 

To solve this problem, I thought it would be better to extend the read-timeout [here](https://github.com/airbytehq/airbyte-platform/tree/main/airbyte-api-server/src/main/resources/application.yml), so I downloaded [AirByte-API-Server](https://github.com/airbytehq/airbyte-platform/tree/main/airbyte-api-server) and changed it to use the Image created from its Dockerfile.
However, the timeout error occurred in the same number of seconds.
Please make it possible to adjust the timeout for connection creation.

### Contribute

- [x] Yes, I want to contribute

**Comment by Saku3449** [comment] 2023-08-17 06:24
```python
terraform {
  required_providers {
    airbyte = {
      source  = "airbytehq/airbyte"
      version = "0.3.1"
    }
  }
}

provider "airbyte" {
  username   = "MY_USER_NAME"
  password   = "MY_PASSWORD"
  server_url = "http://localhost:8006/v1"
}

resource "airbyte_workspace" "my_workspace" {
  name = "MY_WORKSPACE_NAME"
}

resource "airbyte_source_exchange_rates" "exchangerates" {
  configuration = {
    access_key = MY_ACCESS_KEY
    ignore_weekends = true
    source_type     = "exchange-rates"
    start_date      = "2023-04-01"
  }
  name         = "Exchange Rates API"
  workspace_id = airbyte_workspace.my_workspace.workspace_id
}

resource "airbyte_destination_bigquery" "bigquery" {
  configuration = {
    big_query_client_buffer_size_mb = 15
    credentials_json                = file("./credentials.json")
    dataset_id                      = MY_DATASET_ID
    dataset_location                = "asia-northeast1"
    destination_type                = "bigquery"
    loading_method = {
      destination_bigquery_loading_method_standard_inserts = {
        method = "Standard"
      }
    }
    project_id              = MY_PROJECT_ID
    transformation_priority = "batch"
  }
  name         = "BigQuery"
  workspace_id = airbyte_workspace.my_workspace.workspace_id
}

resource "airbyte_connection" "exchangerates_bigquery" {
  configurations = {
    streams = [
      {
        cursor_field = [
          "date",
        ]
        name      = "exchange_rates"
        sync_mode = "full_refresh_overwrite"
      },
    ]
  }
  data_residency                       = "auto"
  destination_id                       = airbyte_destination_bigquery.bigquery.destination_id
  name                                 = "Exchangerates to BigQuery"
  namespace_definition                 = "destination"
  non_breaking_schema_updates_behavior = "ignore"
  schedule = {
    schedule_type = "manual"
  }
  source_id = airbyte_source_exchange_rates.exchangerates.source_id
  status    = "active"
}
```

**Comment by ashutosh-015** [comment] 2023-08-17 07:01
I think I am facing the same issue, whilst I am not using the Terraform Provider, but rather the Airbyte API directly.

**Comment by noam-jacobson** [comment] 2023-08-21 21:00
I am facing the same problem when I try to do a count or for_loop to create multiple database resources using terraform.

**Comment by noam-jacobson** [comment] 2023-08-22 01:47
Setting -parallelism=1 during any terraform cli calls seems to have helped with this issue.

**Comment by ohsawa0515** [comment] 2023-08-22 02:28
I believe there's an issue with the Airbyte API Server's Read Timeout setting.
It appears to be fixed at 20 seconds as seen here: [link](https://github.com/airbytehq/airbyte-platform/blob/main/airbyte-api-server/src/main/resources/application.yml#L21).
This fixed value prevents us from adjusting the Read Timeout as needed. It would be beneficial if this could be made configurable. Thank you for your attention to this matter.

**Comment by aibazhang** [comment] 2023-08-24 05:32
I think I am also facing the same issue when I tried to create an `airbyte_connection` via the Airbyte API.

**Comment by Miller-GS** [comment] 2023-08-24 20:08
Same here with the API!

**Comment by LukasOneLens** [comment] 2023-08-28 20:22
I'm also facing this issue, both via terraform and API.

**Comment by franviera92** [comment] 2023-09-01 20:30
I have this issue with the api-server :(

**Comment by iioo661** [comment] 2023-09-03 18:36
Also, facing the same issue.

**Comment by djememahamat** [comment] 2023-09-10 16:53
I am having the same issue using the /v1/connections endpoint :(

**Comment by chreds** [comment] 2023-09-10 18:57
Are any other API endpoints working for you? I'm wondering if this is related? https://github.com/airbytehq/airbyte/issues/30107

I'm wondering if this has something to do with trackSuccess function not seeing the success message back from airbyte-server? I see some log4j error messages during init.

**Comment by aibazhang** [comment] 2023-09-11 01:36
> I saw a recent change where the 20s timeout was increased but now it just takes longer to timeout whenever I call the api. I think the new timeout was 150s or something.

Thank you, I'll try it later.

> I can't find the commit right now.

This one?
https://github.com/airbytehq/airbyte-platform/commit/b13785c77d22e08e58116721e8bfb2a67e1c9323

**Comment by chreds** [comment] 2023-09-11 21:52
Looks like you can set your own now in 0.50.29

https://github.com/airbytehq/airbyte-platform/commit/6706409fcd61e90c2521e0e9a6fbccec201f57ab

**Comment by ashutosh-015** [comment] 2023-09-12 04:36
@chreds, even if we increase the timeout it just makes the timeout error to come on a longer response time.

**Comment by chreds** [comment] 2023-09-12 14:43
@ashutosh-015 Yes that's my experience here too.

**Comment by ashutosh-015** [comment] 2023-09-19 05:48
@chreds Any luck in making this work?

**Comment by erik-gustafsson-vargas** [comment] 2023-09-19 07:30
We upgraded airbyte helm chart to 0.49.1 and it seems like we we're previously getting a 20s timeout on the api server, to now getting a client-side terraform timeout of 60s (Client.Timeout exceeded while awaiting headers). I'm guessing it's this https://github.com/airbytehq/terraform-provider-airbyte/blob/6e55dd87be8c72bb7b6311783f79f3027b9ab20c/internal/sdk/sdk.go#L135 in airbyte provider that sets it for all airbyte resources

**Comment by chreds** [comment] 2023-09-22 09:47
> @chreds Any luck in making this work?

No. Hoping someone else can help.

**Comment by a-monteiro** [comment] 2023-09-22 14:13
We're experiencing the same issue on multiple Airbyte versions, all deployed in Kubernetes with the helm chart. We've tested from chart version 0.48.2 to 0.49.1, all with the same behavior. 
This is currently blocking us from using the Airbyte Terraform provider.

**Comment by lizdeika** [comment] 2023-10-06 10:22
Same here, any luck anyone with this?

**Comment by kenske** [comment] 2023-10-06 14:30
Running into the same issue. Running Airbyte on k8s using the helm chart. I am able to reproduce the problem with a simple CURL request to `/v1/sources`. Somehow, the first CURL request will go through just fine, but any subsequent calls will time out. The first request will also cause the healthcheck endpoint to stop responding, causing the pod to restart.

**Comment by bass2000** [comment] 2023-10-11 16:51
Getting same error

**Comment by gilbertovilarunc** [comment] 2023-10-17 21:53
This is completely blocking our company pipelines! @marcosmarxm anything we can help? It seems that many users are facing this problem. Any timeframe to fix this issue?

**Comment by mcdowell95** [comment] 2023-10-18 12:47
We are also experiencing this issue. As @chreds says:

> @chreds, even if we increase the timeout it just makes the timeout error to come on a longer response time.

Even if I were able to increase the hardcoded Terraform timeout, as commented by @erik-gustafsson-vargas:

> We upgraded airbyte helm chart to 0.49.1 and it seems like we we're previously getting a 20s timeout on the api server, to now getting a client-side terraform timeout of 60s (Client.Timeout exceeded while awaiting headers). I'm guessing it's this https://github.com/airbytehq/terraform-provider-airbyte/blob/6e55dd87be8c72bb7b6311783f79f3027b9ab20c/internal/sdk/sdk.go#L135 in airbyte provider that sets it for all airbyte resources

I still don't think this would solve the issue as it's the server that's timing out.

**Comment by JonsSpaghetti** [comment] 2023-10-20 17:16
Hey all, this should be resolved as of https://github.com/airbytehq/airbyte-platform/releases/tag/v0.50.31.

That release both includes some increased default timeouts as well as a change to how our micronaut server allocates threads in order to avoid timing out.

Please let us know if timeout issues persist on the new version.

**Comment by chreds** [comment] 2023-10-20 21:34
I can confirm this is working here for me now. For anyone with modifications to your docker-compose.yaml or .env files, make sure you merge in changes for .env and docker-compose.yaml, in particular there's a new INTERNAL_API_URL environment variable in .env and that gets referenced in the airbyte-api-server docker config now.

**Comment by a-monteiro** [comment] 2023-10-23 13:04
This isn't working for me using the 0.49.5 helm chart. I suspect it might be related to the change to the @chreds mentioned

**Comment by chreds** [comment] 2023-10-23 13:39
I'm not sure if INTERNAL_API_HOST is still used by something else (without the http://). I'm guessing it is since they created a new env variable instead (INTERNAL_API_URL). So probably something else in the helm chart needs to be updated to reference that new variable INTERNAL_API_URL and then the env config needs that added.

**Comment by a-monteiro** [comment] 2023-10-23 13:41
> I'm not sure if INTERNAL_API_HOST is still used by something else (without the http://). I'm guessing it is since they created a new env variable instead (INTERNAL_API_URL). So probably something else in the helm chart needs to be updated to reference that new variable INTERNAL_API_URL and then the env config needs that added.

Yes, I agree. I opened a [PR](https://github.com/airbytehq/airbyte-platform/pull/283) using the same approach.

**Comment by storytel-siudzinskim** [comment] 2023-10-23 16:04
I'm using helm deployment for running Airbyte and in previous versions I've been facing the timeout issue. In the newest helm chart (0.49.4) where Airbyte v0.50.31 is used the issue have changed and currently the micronaut error:
```
2023-10-23 15:11:22 [32mINFO[m i.a.a.LoggingTrackingClient(track):55 - track. version: null, userId: null, action: Airbyte_API_Call, metadata: {user_id=00000000-0000-0000-0000-000000000000, endpoint=/v1/workspaces/{workspaceId}, operation=GET, status_code=500}
2023-10-23 15:11:22 [1;31mERROR[m i.m.h.s.RouteExecutor(logException):444 - Unexpected error occurred: No available services for ID: airbyte-airbyte-server-svc:8001
        io.micronaut.discovery.exceptions.NoAvailableServiceException: No available services for ID: airbyte-airbyte-server-svc:8001
	        at io.micronaut.http.client.loadbalance.AbstractRoundRobinLoadBalancer.getNextAvailable(AbstractRoundRobinLoadBalancer.java:50) ~[micronaut-http-client-core-3.10.1.jar:3.10.1]
	        at io.micronaut.core.async.publisher.Publishers$1.doOnNext(Publishers.java:246) ~[micronaut-core-reactive-3.10.1.jar:3.10.1]
	        at io.micronaut.core.async.subscriber.CompletionAwareSubscriber.onNext(CompletionAwareSubscriber.java:56) ~[micronaut-core-reactive-3.10.1.jar:3.10.1]
	        at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89) ~[reactor-core-3.5.5.jar:3.5.5]
	        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onNext(ReactorSubscriber.java:57) ~[micronaut-runtime-3.10.1.jar:3.10.1]
	        at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2545) ~[reactor-core-3.5.5.jar:3.5.5]
	        at reactor.core.publisher.StrictSubscriber.onSubscribe(StrictSubscriber.java:77) ~[reactor-core-3.5.5.jar:3.5.5]
	        at io.micronaut.reactive.reactor.instrument.ReactorSubscriber.onSubscribe(ReactorSubscriber.java:50) ~[micronaut-runtime-3.10.1.jar:3.10.1]
	        at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68) ~[reactor-core-3.5.5.jar:3.5.5]
	        at reactor.core.publisher.Flux.subscribe(Flux.java:8671) ~[reactor-core-3.5.5.jar:3.5.5]
	        at io.micronaut.core.async.publisher.Publishers.lambda$map$3(Publishers.java:237) ~[micronaut-core-reactive-3.10.1.jar:3.10.1]
	        at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:74) ~[reactor-core-3.5.5.jar:3.5.5]
	        at reactor.core.publisher.Flux.subscribe(Flux.java:8671) ~[reactor-core-3.5.5.jar:3.5.5]
	        at reactor.core.publisher.Flux.blockFirst(Flux.java:2701) ~[reactor-core-3.5.5.jar:3.5.5]
	        at io.micronaut.http.client.netty.DefaultHttpClient$1.exchange(DefaultHttpClient.java:499) ~[micronaut-http-client-3.10.1.jar:3.10.1]
	        at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.lambda$intercept$3(HttpClientIntroductionAdvice.java:402) ~[micronaut-http-client-core-3.10.1.jar:3.10.1]
	        at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.handleBlockingCall(HttpClientIntroductionAdvice.java:510) ~[micronaut-http-client-core-3.10.1.jar:3.10.1]
	        at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.intercept(HttpClientIntroductionAdvice.java:401) ~[micronaut-http-client-core-3.10.1.jar:3.10.1]
	        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137) ~[micronaut-aop-3.10.1.jar:3.10.1]
	        at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:98) ~[micronaut-runtime-3.10.1.jar:3.10.1]
	        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137) ~[micronaut-aop-3.10.1.jar:3.10.1]
	        at io.airbyte.api.server.forwardingClient.ConfigApiClient$Intercepted.getWorkspace(Unknown Source) ~[io.airbyte-airbyte-api-server-0.50.31.jar:?]
	        at io.airbyte.api.server.services.WorkspaceServiceImpl.getWorkspace(WorkspaceService.kt:161) ~[io.airbyte-airbyte-api-server-0.50.31.jar:?]
	        at io.airbyte.api.server.services.WorkspaceServiceImpl.controllerGetWorkspace$lambda$1(WorkspaceService.kt:176) ~[io.airbyte-airbyte-api-server-0.50.31.jar:?]
	        at io.airbyte.api.server.apiTracking.TrackingHelper.callWithTracker(TrackingHelper.kt:81) ~[io.airbyte-airbyte-api-server-0.50.31.jar:?]
	        at io.airbyte.api.server.services.WorkspaceServiceImpl.controllerGetWorkspace(WorkspaceService.kt:174) ~[io.airbyte-airbyte-api-server-0.50.31.jar:?]
	        at io.airbyte.api.server.controllers.WorkspacesController.getWorkspace(WorkspacesController.kt:44) ~[io.airbyte-airbyte-api-server-0.50.31.jar:?]
	        at io.airbyte.api.server.controllers.$WorkspacesController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-api-server-0.50.31.jar:?]
	        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371) ~[micronaut-inject-3.10.1.jar:3.10.1]
	        at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594) ~[micronaut-inject-3.10.1.jar:3.10.1]
	        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303) ~[micronaut-router-3.10.1.jar:3.10.1]
	        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111) ~[micronaut-router-3.10.1.jar:3.10.1]
	        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103) ~[micronaut-http-3.10.1.jar:3.10.1]
	        at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659) ~[micronaut-http-server-3.10.1.jar:3.10.1]
	        at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49) ~[reactor-core-3.5.5.jar:3.5.5]
	        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.5.5.jar:3.5.5]
	        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.5.5.jar:3.5.5]
	        at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62) ~[micronaut-runtime-3.10.1.jar:3.10.1]
	        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.5.jar:3.5.5]
	        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.5.jar:3.5.5]
	        at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53) ~[micronaut-context-3.10.1.jar:3.10.1]
	        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
	        Suppressed: java.lang.Exception: #block terminated with an error
		        at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:99) ~[reactor-core-3.5.5.jar:3.5.5]
		        at reactor.core.publisher.Flux.blockFirst(Flux.java:2702) ~[reactor-core-3.5.5.jar:3.5.5]
		        at io.micronaut.http.client.netty.DefaultHttpClient$1.exchange(DefaultHttpClient.java:499) ~[micronaut-http-client-3.10.1.jar:3.10.1]
		        at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.lambda$intercept$3(HttpClientIntroductionAdvice.java:402) ~[micronaut-http-client-core-3.10.1.jar:3.10.1]
		        at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.handleBlockingCall(HttpClientIntroductionAdvice.java:510) ~[micronaut-http-client-core-3.10.1.jar:3.10.1]
		        at io.micronaut.http.client.interceptor.HttpClientIntroductionAdvice.intercept(HttpClientIntroductionAdvice.java:401) ~[micronaut-http-client-core-3.10.1.jar:3.10.1]
		        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137) ~[micronaut-aop-3.10.1.jar:3.10.1]
		        at io.micronaut.retry.intercept.RecoveryInterceptor.intercept(RecoveryInterceptor.java:98) ~[micronaut-runtime-3.10.1.jar:3.10.1]
		        at io.micronaut.aop.chain.MethodInterceptorChain.proceed(MethodInterceptorChain.java:137) ~[micronaut-aop-3.10.1.jar:3.10.1]
		        at io.airbyte.api.server.forwardingClient.ConfigApiClient$Intercepted.getWorkspace(Unknown Source) ~[io.airbyte-airbyte-api-server-0.50.31.jar:?]
		        at io.airbyte.api.server.services.WorkspaceServiceImpl.getWorkspace(WorkspaceService.kt:161) ~[io.airbyte-airbyte-api-server-0.50.31.jar:?]
		        at io.airbyte.api.server.services.WorkspaceServiceImpl.controllerGetWorkspace$lambda$1(WorkspaceService.kt:176) ~[io.airbyte-airbyte-api-server-0.50.31.jar:?]
		        at io.airbyte.api.server.apiTracking.TrackingHelper.callWithTracker(TrackingHelper.kt:81) ~[io.airbyte-airbyte-api-server-0.50.31.jar:?]
		        at io.airbyte.api.server.services.WorkspaceServiceImpl.controllerGetWorkspace(WorkspaceService.kt:174) ~[io.airbyte-airbyte-api-server-0.50.31.jar:?]
		        at io.airbyte.api.server.controllers.WorkspacesController.getWorkspace(WorkspacesController.kt:44) ~[io.airbyte-airbyte-api-server-0.50.31.jar:?]
		        at io.airbyte.api.server.controllers.$WorkspacesController$Definition$Exec.dispatch(Unknown Source) ~[io.airbyte-airbyte-api-server-0.50.31.jar:?]
		        at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:371) ~[micronaut-inject-3.10.1.jar:3.10.1]
		        at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594) ~[micronaut-inject-3.10.1.jar:3.10.1]
		        at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303) ~[micronaut-router-3.10.1.jar:3.10.1]
		        at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111) ~[micronaut-router-3.10.1.jar:3.10.1]
		        at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103) ~[micronaut-http-3.10.1.jar:3.10.1]
		        at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659) ~[micronaut-http-server-3.10.1.jar:3.10.1]
		        at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49) ~[reactor-core-3.5.5.jar:3.5.5]
		        at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) ~[reactor-core-3.5.5.jar:3.5.5]
		        at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) ~[reactor-core-3.5.5.jar:3.5.5]
		        at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62) ~[micronaut-runtime-3.10.1.jar:3.10.1]
		        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) ~[reactor-core-3.5.5.jar:3.5.5]
		        at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) ~[reactor-core-3.5.5.jar:3.5.5]
		        at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53) ~[micronaut-context-3.10.1.jar:3.10.1]
		        at java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
		        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
		        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
		        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

Do you have any ideas how to solve this issue? 

P.S. The health check returns `Successful operation`. Reaching any endpoint of v1 API results with: `{"type":"about:blank","status":500}`

**Comment by chreds** [comment] 2023-10-23 16:22
@storytel-siudzinskim It looks like you haven't made the changes needed for the new environment variable. You should try the PR @a-monteiro made above or wait for it to be merged in.

**Comment by ftforce** [comment] 2023-11-14 09:59
> > I'm not sure if INTERNAL_API_HOST is still used by something else (without the http://). I'm guessing it is since they created a new env variable instead (INTERNAL_API_URL). So probably something else in the helm chart needs to be updated to reference that new variable INTERNAL_API_URL and then the env config needs that added.
> 
> Yes, I agree. I opened a [PR](https://github.com/airbytehq/airbyte-platform/pull/283) using the same approach.
Any news on this?

**Comment by aibazhang** [comment] 2023-11-15 09:06
@JonsSpaghetti
I'm sorry to bother you, do we have any updates on this↑

**Comment by nhatsangvn** [comment] 2023-11-17 09:11
Thank you @aballiet , it works.

The default value `airbyte-airbyte-server-svc:8001` without scheme `http://` is having the issue.

We need to re-install the chart, seems it doesn't allow to patch directly the env.

**Comment by Andresmps** [comment] 2024-01-22 23:04
Hi!!
I was dealing with the same problem with airbyte api version 0.50.30 installed with docker compose. Particularly the error i was receiving was {"type":"about:blank","status":500}, and as some of you mentioned it appear after timeout was reach.

One important detail here is that all endpoint, in my case, were working except when I was trying to create a connection. 

I was able to solver upgrading airbyte to version 0.50.44. Hope any of you find this useful.

**Comment by pmossman** [comment] 2024-06-10 18:39
Closing as duplicate, but let us know if there are still issues here and we can re-open if needed

**Closed by pmossman** 2024-06-10 18:39 UTC
Labels: type/bug, community, team/compose, area/terraform-sdk
